### PR TITLE
fix(common): avoid calculating unnecessary branches in hashchains

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/block_hash.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVDHA3_OMWu7t6V1y:-NsgVDHB1MtRUXa_ywuc:b-mp8swk) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/block_hash.rs#L56)):*
> ```XML
>         get_events_hash_data(&block.body.transaction_outputs, &version);
> 
>     // Can't implement as a clousure because ascii_as_felt returns a Result.
> ```

You can fix this by changing the argument of chain_fn to `Fn() -> Result<Option<StarkFelt>>` and chaining the return type from `Self` to `Result<Self>`
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgV29a2qYpPfZ9n7Q1:-NsgV29a2qYpPfZ9n7Q2:b-clli46) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/transaction_hash.rs#L198)):*
> ```XML
> 
>     // Chains the result of a function to the hash chain.
>     pub fn chain_fn<F: Fn() -> Option<StarkFelt>>(self, f: F) -> Self {
> ```

Consider renaming to chain_if_fn
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVhvaEKw1Zb4QE06J:-NsgVhvaEKw1Zb4QE06K:bfqgbp4) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/transaction_hash.rs#L334)):*
> ```XML
>             if !is_deprecated {
>                 Some(*ZERO)
>             }
> ```

Unite this line with the line below it. I'm surprised rustfmt didn't fail

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/block_hash.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVDHA3_OMWu7t6V1y:-Nsgrt1k1ZPfsevj8DiO:byj5iof) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/block_hash.rs#L56)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can fix this by changing the argument of chain_fn to `Fn() -> Result<Option<StarkFelt>>` and chaining the return type from `Self` to `Result<Self>`
</blockquote></details>

Not saying you should. That's up to you

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVDHA3_OMWu7t6V1y:-Nsh8EaW1mydynJma1CK:b-6so5tv) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/block_hash.rs#L56)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Not saying you should. That's up to you
</blockquote></details>

I think it's simpler in the current way
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgV29a2qYpPfZ9n7Q1:-Nsh8W_YBo1QeL3__ScU:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/transaction_hash.rs#L198)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider renaming to chain_if_fn
</blockquote></details>

Done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVhvaEKw1Zb4QE06J:-Nsh8bj73nZaM4BlJXjA:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/transaction_hash.rs#L334)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unite this line with the line below it. I'm surprised rustfmt didn't fail
</blockquote></details>

Done

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-NsgVhvaEKw1Zb4QE06J:-NshBwGkENM0eHqIkdrU:b-e0btd1) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b02537797b9b402382fda8db1b2f6795899a6ed/crates/papyrus_common/src/transaction_hash.rs#L334)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I was talking about
```
}
else {
```

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-:-NshC25gEr5Eswg2bIqs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1799#-:-Nshji1M9yIeG9J0QM7E:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
