### PR TITLE
feat(network): add Class and Event protocols

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2155)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2155)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0Jgb4gCzkSmzCOYjJw:-O0JfeCD5UC8lgJCIpKl:b-6mi252) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L301)):*
> ```XML
>         let deprecated_declared_classes = thin_state_diff.deprecated_declared_classes;
>         let mut result = Vec::new();
>         result.extend(deprecated_declared_classes.iter().filter_map(|class_hash| {
> ```

You shouldn't filter Nones. You should return Error if there's a None. If needed, you can create a new error type for this called StateDiffAndClassesMismatch
Call map and inside it return Result<...>. And then collect all the results into Result<Vec<_>, _>
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JgFi6EpRteXuxWuzI:-O0JgFi6EpRteXuxWuzJ:b-5xyusk) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L303)):*
> ```XML
>         result.extend(deprecated_declared_classes.iter().filter_map(|class_hash| {
>             txn.get_deprecated_class(class_hash)
>                 .ok()
> ```

You're hiding storage errors here. Instead of calling ok, call map so that the error will be returned (see above comment)
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JfPPdDdx3RxSDbXh6:-O0JfPPdDdx3RxSDbXh7:b47ibxm) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L309)):*
> ```XML
> 
>         result.extend(declared_classes.keys().filter_map(|class_hash| {
>             txn.get_deprecated_class(class_hash)
> ```

get_class
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JgXXR34F-Xm6kIjQF:-O0JgXXR34F-Xm6kIjQG:b-ya81ng) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L310)):*
> ```XML
>         result.extend(declared_classes.keys().filter_map(|class_hash| {
>             txn.get_deprecated_class(class_hash)
>                 .ok()
> ```

Same as above
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JfQcq2RjN3Qk3KtZ8:-O0JfQcq2RjN3Qk3KtZ9:b-njx9dj) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L312)):*
> ```XML
>                 .ok()
>                 .flatten()
>                 .map(ApiContractClass::DeprecatedContractClass)
> ```

DeprecatedContractClass -> ContractClass

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2155)* status: all files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0Jgb4gCzkSmzCOYjJw:-O0NFwGzEdplMPOsC1F8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L301)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You shouldn't filter Nones. You should return Error if there's a None. If needed, you can create a new error type for this called StateDiffAndClassesMismatch
Call map and inside it return Result<...>. And then collect all the results into Result<Vec<_>, _>
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JgFi6EpRteXuxWuzI:-O0NG8A7BpjMlKd2zDXd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L303)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're hiding storage errors here. Instead of calling ok, call map so that the error will be returned (see above comment)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JfPPdDdx3RxSDbXh6:-O0N9JBc2FYUxnSfF3NW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L309)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

get_class
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JgXXR34F-Xm6kIjQF:-O0N9JS6C8MhiX9h5UdW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L310)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-O0JfQcq2RjN3Qk3KtZ8:-O0N9JlD8azxsFnQ09tG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b6f1fbdede1d1bee9c8b89cad9ded382a421eb4/crates/papyrus_network/src/db_executor/mod.rs#L312)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

DeprecatedContractClass -> ContractClass
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-:-O0Oy-K7Dco1fRWAFrEm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2155#-:-O0bbm8H6P9Oj4e4DeFR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
