### PR TITLE
move broadcasted txs to v3

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/889)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #880** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/880" target="_blank">Graphite</a> 
    * **PR #889** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/889" target="_blank">Graphite</a>  👈
    * **PR #879** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/879" target="_blank">Graphite</a> 
      * **PR #882** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/882" target="_blank">Graphite</a> 
        * **PR #883** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/883" target="_blank">Graphite</a> 
          * **PR #885** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/885" target="_blank">Graphite</a> 
            * **PR #877** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/877" target="_blank">Graphite</a> 
              * **PR #878** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/878" target="_blank">Graphite</a> 
                * **PR #881** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/881" target="_blank">Graphite</a> 
          * **PR #884** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/884" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/889?utm_source=stack-comment).

**Comment by dan-starkware** [comment]
@ShahakShama FYI

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/889)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/889)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/889#-:-Na68OVLA2fN8rnmOWNq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
