### PR TITLE
feat(network): add support for state diff in db executor (not in net manager yet)

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1790?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNtWDd3cI7UNL8NKU8:-NsNryy26bNDHH71vaVA:bqi2scg) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/converters/protobuf_conversion/mod.rs#L13)):*
> ```XML
>     BytesDataLengthMismatch { type_description: &'static str, num_expected: usize, value: Vec<u8> },
>     #[error("Type `{type_description}` got unsupported data type {data_type}")]
>     UnsupportedDataType { data_type: String, type_description: String },
> ```

This doesn't really belong here. my suggestion is to create a separate error for conversion from Data to protobuf with just this variant (from what I've seen you don't return any of the other protobuf errors there)

Could you also add a documentation to this error that it returns when converting protobuf to SN_API/Data and not the other way?
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsMTh9IzhjJTQIVrX:-NsNsMTi7l_qXCFv61OC:b-mdliks) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/mod.rs#L256)):*
> ```XML
>                         storage_error: err,
>                     })?
>                     .ok_or(DBExecutorError::BlockNotFound {
> ```

Create a separate error called StateDiffNotFound (IMO the errors should be equivalent to the db markers)
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsvgk2TAkUgKaDpRd:-NsNsvgk2TAkUgKaDpRe:bdqbtm2) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/test.rs#L38)):*
> ```XML
>         step: 1,
>     };
>     let (query_ids, mut receivers): (Vec<QueryId>, Vec<Receiver<Data>>) =
> ```

Add a separate test that has each time only 1 query with one of the data types and checks that the returned result matches the expected type
You can put a TODO to implement such test if you prefer working on something else right now
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNu2j1CfeZaYAKX73C:-NsNu2j1CfeZaYAKX73D:b-rfzt8v) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/network_manager/mod.rs#L233)):*
> ```XML
>         let mut data_bytes = vec![];
>         <Data as TryInto<protobuf::BlockHeadersResponse>>::try_into(data)
>             .expect("DB returned data for query that is not expected by this protocol")
> ```

Add TODO to handle this error (unless you're certain you won't miss this)
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNuBtZ1DLA3nXQWESM:-NsNuBtZ1DLA3nXQWESN:b6h3onm) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/network_manager/test.rs#L85)):*
> ```XML
>             };
>             let mut data_bytes = vec![];
>             <Data as TryInto<protobuf::BlockHeadersResponse>>::try_into(signed_header)
> ```

It will be cleaner here to write protobuf::BlockHeadersResponse::try_from

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNtWDd3cI7UNL8NKU8:-NsOBneV9xFX-W1XBb8_:b-turbpr) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/converters/protobuf_conversion/mod.rs#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This doesn't really belong here. my suggestion is to create a separate error for conversion from Data to protobuf with just this variant (from what I've seen you don't return any of the other protobuf errors there)

Could you also add a documentation to this error that it returns when converting protobuf to SN_API/Data and not the other way?
</blockquote></details>

I didn't understand the second part of your comment
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsMTh9IzhjJTQIVrX:-NsO8guZ7LsYcYrbQtGl:blf6zno) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/mod.rs#L256)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Create a separate error called StateDiffNotFound (IMO the errors should be equivalent to the db markers)
</blockquote></details>

I don't think it makes sense to create a new error type for every data type we want to support.
what we can do is add to the `BlockNotFound` error the `query_id` and `DataType` so that the error message will be more helpful.
WDYT?
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsvgk2TAkUgKaDpRd:-NsO95jl1CZtT61mnxiW:b-urq2y9) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/test.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a separate test that has each time only 1 query with one of the data types and checks that the returned result matches the expected type
You can put a TODO to implement such test if you prefer working on something else right now
</blockquote></details>

seriously? you just suggested this exact testing methodology in the last PR
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNu2j1CfeZaYAKX73C:-NsO9OtK8IUpgKX9f71d:b-3dd8sg) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/network_manager/mod.rs#L233)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to handle this error (unless you're certain you won't miss this)
</blockquote></details>

I'm not sure that that's not the right way to handle this. I'm open for suggestions. but let's do it offline, not in this PR

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsMTh9IzhjJTQIVrX:-NsP1jjPDR1B1WxveY6L:b-qsf9ez) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/mod.rs#L256)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't think it makes sense to create a new error type for every data type we want to support.
what we can do is add to the `BlockNotFound` error the `query_id` and `DataType` so that the error message will be more helpful.
WDYT?
</blockquote></details>

I agree, but in that case we should remove SignatureNotFound
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsvgk2TAkUgKaDpRd:-NsP1sCM4ktYGz9z12Tz:b-luc5fj) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/test.rs#L38)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

seriously? you just suggested this exact testing methodology in the last PR
</blockquote></details>

I'm suggesting an additional test. on top of this test

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsMTh9IzhjJTQIVrX:-Nsbd3ie1gA-z3ttQ-Ne:btywrhu) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/mod.rs#L256)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I agree, but in that case we should remove SignatureNotFound
</blockquote></details>

ok. next PR. added a todo for now
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsvgk2TAkUgKaDpRd:-NsbkXQ76MqpMI04kG5D:b4fn2e9) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/test.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm suggesting an additional test. on top of this test
</blockquote></details>

oh you mean to add a check for the returned data type? there's no need for a new test for that. we can do it in this one

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-:-Nsbmlpn2GVfeqxZhBZX:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsNsvgk2TAkUgKaDpRd:-NsblN44Dnh_Sn1R8brM:b-83sjoh) ([raw file](https://github.com/starkware-libs/papyrus/blob/d71f9a36a17783940a9b73e17e278aaf6e3b0e46/crates/papyrus_network/src/db_executor/test.rs#L38)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

oh you mean to add a check for the returned data type? there's no need for a new test for that. we can do it in this one
</blockquote></details>

Nice!
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsbmNHG9DSPgSzkDl-0:-NsbmNHG9DSPgSzkDl-1:bura6p9) ([raw file](https://github.com/starkware-libs/papyrus/blob/70c68c74313c2306bc155c5d3696a9cec068e490/crates/papyrus_network/src/db_executor/test.rs#L38)):*
> ```XML
>         step: 1,
>     };
>     let (query_ids, mut receivers): (Vec<QueryId>, Vec<(Receiver<Data>, DataType)>) =
> ```


Consider adding a comment saying that the DataType is the expected data type
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-NsbmTme3fs3jnN749_f:-NsbmTme3fs3jnN749_g:bt0csxr) ([raw file](https://github.com/starkware-libs/papyrus/blob/70c68c74313c2306bc155c5d3696a9cec068e490/crates/papyrus_network/src/db_executor/test.rs#L49)):*
> ```XML
>     receivers
>         .iter_mut()
>         .map(|(receiver, data_type)| {
> ```

Rename data_type to expected_data_type
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-Nsbmb0F4eJ4REgUHaCh:-Nsbmb0F4eJ4REgUHaCi:bt0csxr) ([raw file](https://github.com/starkware-libs/papyrus/blob/70c68c74313c2306bc155c5d3696a9cec068e490/crates/papyrus_network/src/db_executor/test.rs#L64)):*
> ```XML
>         }
>         Some(res) = receivers_stream.next() => {
>             let (data, data_type) = res.await;
> ```

Rename data_type to expected_data_type

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1790#-:-NsboYxS4JtdFymMiS2U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
