### PR TITLE
Implement Default for each config component individually.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- The default values for the configs are set centrally in the node crate.

Issue Number: 496

## What is the new behavior?

- Implement Default for each config component individually.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)

### CODE REVIEW

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9Pr1w3Ldm_P3NU8ig:-NX9Pr1x7XlrFdeoDSnZ:b-3gd63s) (no related file):*
I'm just checking that the rust looks valid since I have no input on if the default values are correct.

___
___
*[`crates/papyrus_node/src/config/mod.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9Qh62B42k7Puxd11B:-NX9Qh62B42k7Puxd11C:b-qchf0e) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_node/src/config/mod.rs#L79)):*
> ```XML
> 
> // Default configuration values.
> impl Default for ConfigBuilder {
> ```

This is ok, but I want to offer another option. Implement `Config::default`. The downside of this is that this by itself means you are building `GatewayConfig` twice, but we can mitigate this:

1. Create `fn default_chain_id() { ChainId(String::from("SN_MAIN")) }` so we only build the needed field twice instead of the entire `GatewayConfig`.
2. Just build `config = Config::default()` and then clone the needed field `chain_id: config.gateway.chain_id.clone()` 

(I like using option 2).



_Code quote:_
```XML
impl Default for ConfigBuilder {
```
___
*[`crates/papyrus_sync/src/lib.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9TJfUAk3QdPbcsz3O:-NX9TJfUAk3QdPbcsz3P:bfzg0rq) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_sync/src/lib.rs#L35)):*
> ```XML
>     pub recoverable_error_sleep_duration: Duration,
>     pub blocks_max_stream_size: u32,
>     pub state_updates_max_stream_size: u32,
> ```

Any chance we can get a comment on the units? (bytes?)



_Code quote:_
```XML
    pub blocks_max_stream_size: u32,
    pub state_updates_max_stream_size: u32,
```
___
*[`crates/papyrus_sync/src/sources/central.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9TiZ-5Lf0ZPYWigan:-NX9TiZ-5Lf0ZPYWigao:bn265rb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_sync/src/sources/central.rs#L45)):*
> ```XML
>             url: String::from("https://alpha-mainnet.starknet.io/"),
>             http_headers: None,
>             retry_config: RetryConfig {
> ```

Do we want to define a default for this? I see it is defined in a different crate though so I'm not sure if this is out of scope or if we don't want to rely on an external default...



_Code quote:_
```XML
RetryConfig
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_node/src/config/mod.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9Qh62B42k7Puxd11B:-NX9ghGC9wnzSDEAe40P:b-ol9l4l) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_node/src/config/mod.rs#L79)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is ok, but I want to offer another option. Implement `Config::default`. The downside of this is that this by itself means you are building `GatewayConfig` twice, but we can mitigate this:

1. Create `fn default_chain_id() { ChainId(String::from("SN_MAIN")) }` so we only build the needed field twice instead of the entire `GatewayConfig`.
2. Just build `config = Config::default()` and then clone the needed field `chain_id: config.gateway.chain_id.clone()` 

(I like using option 2).
</blockquote></details>

Nice! Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9TJfUAk3QdPbcsz3O:-NX9hLfD2p5oYl1ZlHre:bxro652) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_sync/src/lib.rs#L35)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Any chance we can get a comment on the units? (bytes?)
</blockquote></details>

It does not indicate the block size, this is the amount of blocks in the stream. The same for the number of state updates.
___
*[`crates/papyrus_sync/src/sources/central.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NX9TiZ-5Lf0ZPYWigan:-NX9lLet3ds3RzrmdmlT:b-ls2gl2) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ac8dd99d15bb654233ae398ab9f4f87d647a76a/crates/papyrus_sync/src/sources/central.rs#L45)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Do we want to define a default for this? I see it is defined in a different crate though so I'm not sure if this is out of scope or if we don't want to rely on an external default...
</blockquote></details>

Out of this scope...

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

___
*[`crates/papyrus_node/src/config/mod.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAEG-CBGx5oR-f2UK1:-NXAEG-CBGx5oR-f2UK2:byx2r39) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_node/src/config/mod.rs#L47)):*
> ```XML
>             monitoring_gateway: MonitoringGatewayConfig::default(),
>             storage: StorageConfig::default(),
>             sync: Some(SyncConfig::default()),
> ```

An interesting point is that this is the only line that prevents us from using `derive(Default)`, since the default for Option is `None`.



_Code quote:_
```XML
            sync: Some(SyncConfig::default()),
```

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_gateway/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAENHI5egD8P5o48T5:-NXAENHI5egD8P5o48T6:b-7l7p9b) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_gateway/src/lib.rs#L50)):*
> ```XML
>     fn default() -> Self {
>         GatewayConfig {
>             chain_id: ChainId(String::from("SN_MAIN")),
> ```

My understanding is that chain_id should get the default value in crates/papyrus_node/src/config/mod.rs and from there it's copied into GatewayConfig (and DbConfig). 
Not the other way round.



_Code quote:_
```XML
chain_id: ChainId(String::from("SN_MAIN")),
```
___
*[`crates/papyrus_storage/src/lib.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAD_t98GagugxfJDl9:-NXAD_t98GagugxfJDlA:bzhygv3) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_storage/src/lib.rs#L269)):*
> ```XML
> pub type StorageResult<V> = std::result::Result<V, StorageError>;
> 
> #[derive(Serialize, Deserialize, Clone, Default)]
> ```

Why do we need to add 'Default' here, but not in other Config classes?
(Just asking in order to understand this.)



_Code quote:_
```XML
#[derive(Serialize, Deserialize, Clone, Default)]
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_gateway/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAENHI5egD8P5o48T5:-NXAKADSBzKmu2IGJLyc:b9wtad8) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_gateway/src/lib.rs#L50)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

My understanding is that chain_id should get the default value in crates/papyrus_node/src/config/mod.rs and from there it's copied into GatewayConfig (and DbConfig). 
Not the other way round.

</blockquote></details>

It will create cyclic dependencies.
We are going to add a new crate for the config, so this default probably should be there.
___
*[`crates/papyrus_storage/src/lib.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAD_t98GagugxfJDl9:-NXAIEG366RdHBo2O-DV:b-j9akgd) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_storage/src/lib.rs#L269)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Why do we need to add 'Default' here, but not in other Config classes?
(Just asking in order to understand this.)
</blockquote></details>

Instead of implementing Default explicitly, the Default of StorageConfig is the combination of the members' defaults of this struct.

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXAENHI5egD8P5o48T5:-NXATYxcE2yK_k9m5a-r:b3ed6bc) ([raw file](https://github.com/starkware-libs/papyrus/blob/4bf22f01904c3188e4d30c82c7f0144c257561be/crates/papyrus_gateway/src/lib.rs#L50)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It will create cyclic dependencies.
We are going to add a new crate for the config, so this default probably should be there.
</blockquote></details>

Why will it create cyclic dependecies?
Can't you just remove the default value from here and put it in GatewayConfig?
(propagate_chain_id() already copies the chain_id value from ConfigBuilder to GatewayConfig.)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yoavGrs)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by OmriEshhar1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXB0ZQY3RBXOfeKbT_Y:-NXB0ZQY3RBXOfeKbT_Z:bndem1x) ([raw file](https://github.com/starkware-libs/papyrus/blob/669e5b81f823873324754f4d3ecd813541d251fe/crates/papyrus_config/src/lib.rs#L1)):*
> ```XML
> pub fn default_chain_id() -> String {
> ```

use const
___
*[`crates/papyrus_node/src/config/mod.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXB-83IBK_kEHkxsnYI:-NXB-83IBK_kEHkxsnYJ:b-iu5a37) ([raw file](https://github.com/starkware-libs/papyrus/blob/669e5b81f823873324754f4d3ecd813541d251fe/crates/papyrus_node/src/config/mod.rs#L98)):*
> ```XML
>             args: None,
>             chain_id: ChainId(default_chain_id()),
>             config: Config::default(),
> ```

These values will be read from the dump file, right?
Add TODO.

Also, consider changing it from a Default trait implementation to a function like `default_provider` as this is more like a stage during the creation of the configuration than a default builder instance.



_Code quote:_
```XML
            chain_id: ChainId(default_chain_id()),
            config: Config::default(),
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXB0ZQY3RBXOfeKbT_Y:-NXEZN6AD8gTUfHoxf3I:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/669e5b81f823873324754f4d3ecd813541d251fe/crates/papyrus_config/src/lib.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

use const
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/718#-NXB-83IBK_kEHkxsnYI:-NXE_EUl9kEys2CmQohk:bcsopm6) ([raw file](https://github.com/starkware-libs/papyrus/blob/669e5b81f823873324754f4d3ecd813541d251fe/crates/papyrus_node/src/config/mod.rs#L98)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

These values will be read from the dump file, right?
Add TODO.

Also, consider changing it from a Default trait implementation to a function like `default_provider` as this is more like a stage during the creation of the configuration than a default builder instance.
</blockquote></details>

1. Done.
2. IMO, with the description of this struct: "Builds the configuration... based on default values" is clear enough. You're processing the default.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/718#-:-NXtVMaEA8humBZqFIwJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
