### PR TITLE
Yair/deprecate declared classes

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

The first step to support 0.11

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/540)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_gateway/src/state.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NPwdJ-g69q8mubqsWMt:-NPwdJ-g69q8mubqsWMu:be6pa0b) ([raw file](https://github.com/starkware-libs/papyrus/blob/e3f79e12673e14854323aa6b9484989a76944815/crates/papyrus_gateway/src/state.rs#L138)):*
> ```XML
>     pub deployed_contracts: Vec<DeployedContract>,
>     pub storage_diffs: Vec<StorageDiff>,
>     pub declared_contract_hashes: Vec<ClassHash>,
> ```

Shouldn't this be `deprecated_declared_classes` according to the rpc?

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/state.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NPwdJ-g69q8mubqsWMt:-NQ0Mr7A6P7ZhmfKqa1V:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e3f79e12673e14854323aa6b9484989a76944815/crates/papyrus_gateway/src/state.rs#L138)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Shouldn't this be `deprecated_declared_classes` according to the rpc?
</blockquote></details>

Done.

**Review by anatgstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/540)* status: 0 of 34 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/lib.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NQ0dphCCzmQJ-F21nIi:-NQ0dphCCzmQJ-F21nIj:b-s3fsjm) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7fc5675fbd6cbfacd19e26741c2c8372677333b/crates/starknet_client/src/lib.rs#L280)):*
> ```XML
>     }
> 
>     async fn class_by_hash(
> ```

I think you should also change the name of this function



_Code quote:_
```XML
class_by_hash
```

**Comment by yair-starkware** [comment]
*[`crates/starknet_client/src/lib.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NQ0dphCCzmQJ-F21nIi:-NQ0xZbX-fxo1xkVx0SB:bpgmzod) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7fc5675fbd6cbfacd19e26741c2c8372677333b/crates/starknet_client/src/lib.rs#L280)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

I think you should also change the name of this function
</blockquote></details>

Why? It's the same function in the Feeder Gateway, just the response can be both types of classes

**Comment by anatgstarkware** [comment]
*[`crates/starknet_client/src/lib.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NQ0dphCCzmQJ-F21nIi:-NQ0yvxsCUGqXGOOXOAY:b35gv5w) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7fc5675fbd6cbfacd19e26741c2c8372677333b/crates/starknet_client/src/lib.rs#L280)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why? It's the same function in the Feeder Gateway, just the response can be both types of classes
</blockquote></details>

We will need to bring both types

**Comment by yair-starkware** [comment]
*[`crates/starknet_client/src/lib.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NQ0dphCCzmQJ-F21nIi:-NQ4e60SCSCyu-f4T6qC:b98doai) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7fc5675fbd6cbfacd19e26741c2c8372677333b/crates/starknet_client/src/lib.rs#L280)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

We will need to bring both types
</blockquote></details>

Right, I am working on it in a separate PR

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 24 files at r1, 15 of 26 files at r3, 1 of 2 files at r5, 3 of 5 files at r6, 5 of 5 files at r7, 1 of 2 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, 4 of 6 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/540#-:-NQ50__aCNA60JXTvov5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 37 files at r13, 1 of 23 files at r14, 16 of 26 files at r16, 1 of 2 files at r18, 1 of 5 files at r19, 4 of 4 files at r20, 1 of 2 files at r21, 4 of 4 files at r22, 6 of 6 files at r23, 1 of 1 files at r24, 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/540)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 12 at r25](https://reviewable.io/reviews/starkware-libs/papyrus/540#-NQdSNDa6f_irRbEAuN1:-NQdSNDa6f_irRbEAuN2:boi14s) ([raw file](https://github.com/starkware-libs/papyrus/blob/f23d73269d62c9d2537853bcbae536e5fe3b2bf7/crates/papyrus_node/src/bin/central_source_integration_test.rs#L12)):*
> ```XML
>     // default once 0.11 is on mainnet.
>     let config = Config::load(vec![
>         "--chain_id=integration".to_owned(),
> ```

I think this is also `SN_GOERLI`. We can either use `SN_GOERLI` with the set storage directory configuration to make sure no collision happens. Or use a different chain ID. In that case IMO we should maintain the `SN_*`format, consider `SN_INTEGRATION`



_Code quote:_
```XML
integration
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
