### PR TITLE
feat(JSON-RPC): getBlockWithReceipts

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrV8AcpBx0MXodZ8nTX:-NrV8AcpBx0MXodZ8nTY:b-1wcx9m) (no related file):*
Add the method to the README

___
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrVJe8GAhQibCnovMyC:-NrVJe8H9a6wB0G0P6Qn:boldppr) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a3ac0cfbdf17d940b48918c8eb29243083b5cad/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L181)):*
> ```XML
> 
>     #[instrument(skip(self), level = "debug", err, ret)]
>     async fn get_block_w_transaction_hashes(&self, block_id: BlockId) -> RpcResult<Block> {
> ```

What happened in this file? Please separate to commits and/or move code so it will be easier to review
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 789 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrVSE2c9Dd8a3LlT52e:-NrVSE2c9Dd8a3LlT52f:b8hpuok) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a3ac0cfbdf17d940b48918c8eb29243083b5cad/crates/papyrus_rpc/src/v0_7/api/test.rs#L789)):*
> ```XML
>         price_in_wei: GasPrice(random::<u128>()),
>         price_in_fri: GasPrice(random::<u128>()),
>     };
> ```

Consider avoiding random values or at least using the rng to create them



_Code quote:_
```XML
    let pending_sequencer_address = SequencerContractAddress(random::<u64>().into());
    let pending_timestamp = BlockTimestamp(random::<u64>());
    let pending_l1_gas_price = GasPricePerToken {
        price_in_wei: GasPrice(random::<u128>()),
        price_in_fri: GasPrice(random::<u128>()),
    };
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrV8AcpBx0MXodZ8nTX:-NrZPc7E7O6Sb6nIMtcI:b-h5sqj7) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add the method to the README
</blockquote></details>

It's still not fully supported, since there's a change to the receipts schema I haven't did yet

___
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrVJe8GAhQibCnovMyC:-NrZYzI10VaSZqqvmhzg:bvyb82y) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a3ac0cfbdf17d940b48918c8eb29243083b5cad/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L181)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What happened in this file? Please separate to commits and/or move code so it will be easier to review
</blockquote></details>

better?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrVJe8GAhQibCnovMyC:-NrZZ8HMDLDw2RZ_hf0L:b-cqb4ri) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a3ac0cfbdf17d940b48918c8eb29243083b5cad/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L181)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

better?
</blockquote></details>

do base vs r2 and then r2 vs r3

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NrZur6P8LCsIWiJ2sCU:-NrZQvhyEnCb7GhO9MtR:b-za0mvc) (no related file):*
Based on https://reviewable.io/reviews/starkware-libs/starknet-specs/195

___

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 2 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1492 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NroBEke3RWyd78KU8hb:-NroBEke3RWyd78KU8hc:b-4p1ntx) ([raw file](https://github.com/starkware-libs/papyrus/blob/683c079e039065b362ec863ffb7f1fa12c74de6d/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1492)):*
> ```XML
> }
> 
> impl JsonRpcServerV0_7Impl {
> ```

In a separate PR - rename the inpl structs to discard the version



_Code quote:_
```XML
JsonRpcServerV0_7Impl
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1493 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NroFYEe3lrRtiIgW5PT:-NroFYEe3lrRtiIgW5PU:bsf9rjj) ([raw file](https://github.com/starkware-libs/papyrus/blob/683c079e039065b362ec863ffb7f1fa12c74de6d/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1493)):*
> ```XML
> 
> impl JsonRpcServerV0_7Impl {
>     async fn get_block(
> ```

Instead of extra code in the RPC, add another storage function that returns the full transactions and use the storage functions here

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1492 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NroBEke3RWyd78KU8hb:-Ns1v0m7CH8jU8P2vCJP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/683c079e039065b362ec863ffb7f1fa12c74de6d/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1492)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In a separate PR - rename the inpl structs to discard the version
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1493 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-NroFYEe3lrRtiIgW5PT:-Ns1vVDwBi7fCTVvkvf3:b-mb6w7i) ([raw file](https://github.com/starkware-libs/papyrus/blob/683c079e039065b362ec863ffb7f1fa12c74de6d/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1493)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Instead of extra code in the RPC, add another storage function that returns the full transactions and use the storage functions here
</blockquote></details>

I've looked into it, and:
1. most of the RPC code comes from the pending function
2. The functions we are using are from the RPC, and making them have a shared interface is a lot of work
3. IMO doing this change will limit our ability to modify the implementation

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r5, 1 of 1 files at r6, 7 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 704 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2_04bEhfh07rbfkil:-Ns2_04bEhfh07rbfkim:boc2o46) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/transaction.rs#L704)):*
> ```XML
>         }
>     }
> }
> ```

Please move down to be after `TransactionReceiptInBlock`



_Code quote:_
```XML
impl From<GeneralTransactionReceipt> for TransactionReceiptInBlock {
    fn from(value: GeneralTransactionReceipt) -> Self {
        match value {
            GeneralTransactionReceipt::TransactionReceipt(receipt) => Self {
                finality_status: receipt.finality_status,
                transaction_hash: receipt.transaction_hash,
                output: receipt.output,
            },
            GeneralTransactionReceipt::PendingTransactionReceipt(receipt) => Self {
                finality_status: match receipt.finality_status {
                    PendingTransactionFinalityStatus::AcceptedOnL2 => {
                        TransactionFinalityStatus::AcceptedOnL2
                    }
                },
                transaction_hash: receipt.transaction_hash,
                output: match receipt.output {
                    PendingTransactionOutput::DeployAccount(deploy_account_output) => {
                        TransactionOutput::DeployAccount(deploy_account_output)
                    }
                    PendingTransactionOutput::Declare(declare_output) => {
                        TransactionOutput::Declare(declare_output)
                    }
                    PendingTransactionOutput::Invoke(invoke_output) => {
                        TransactionOutput::Invoke(invoke_output)
                    }
                    PendingTransactionOutput::L1Handler(l1_handler_output) => {
                        TransactionOutput::L1Handler(l1_handler_output)
                    }
                },
            },
        }
    }
}
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 292 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2bgSj30gY76HFNAfp:-Ns2bgSj30gY76HFNAfq:b-90lcdg) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L292)):*
> ```XML
>                             );
>                             let msg_hash = match &transaction {
>                                 super::super::transaction::Transaction::L1Handler(
> ```

Please use type alias or start from crate::



_Code quote:_
```XML
super::super::transaction::Transaction::L1Handler
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1493 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2_Yi_5KqUE7QFf1SU:-Ns2_Yi_5KqUE7QFf1SV:bqlspuv) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1493)):*
> ```XML
> 
> impl JsonRpcServerImpl {
>     async fn get_block(
> ```

Please doc



_Code quote:_
```XML
async fn get_block
```
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 1351 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2cRyp8RPFH3gho-yn:-Ns2cRyp8RPFH3gho-yo:b55yf8w) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/api/test.rs#L1351)):*
> ```XML
>         output,
>     };
>     call_api_then_assert_and_validate_schema_for_result(
> ```

Should this change in all versions? 
Consider moving to a separate PR

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: 11 of 19 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 292 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2bgSj30gY76HFNAfp:-Ns2iUcQ4mN1bxfdm_vJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L292)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use type alias or start from crate::
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 1351 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1734#-Ns2cRyp8RPFH3gho-yn:-Ns2egwp9f3mG1ebIOkr:bb0l3ho) ([raw file](https://github.com/starkware-libs/papyrus/blob/5155f0f106153ae9c668581cf08951f0a7da9b60/crates/papyrus_rpc/src/v0_7/api/test.rs#L1351)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Should this change in all versions? 
Consider moving to a separate PR
</blockquote></details>

Because this is a convenience change, I don't think we need it in all versions

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 8 files at r9, 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1734)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
