### PR TITLE
shahak/client refactor/move reader client to reader mod

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(starknet_client)!: Move FGW code to reader module
- refactor(starknet_client)!: Fix imports and rename client structs
- refactor(starknet_client)!: Rename starknet_reader_client to starknet_client
- refactor(starknet_client)!: Fix references to starknet_client in other crates

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/922)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/922)* status: 0 of 55 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

**Comment by dan-starkware** [comment]
*[`crates/starknet_reader_client/src/reader/starknet_feeder_gateway_client_test.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/922#-NaLKwF53dqpjLl52PkD:-NaLKwF53dqpjLl52PkE:brhpdji) ([raw file](https://github.com/starkware-libs/papyrus/blob/cd9acdfeb2cb1a335351168956c6302ae61ff729/crates/starknet_reader_client/src/reader/starknet_feeder_gateway_client_test.rs#L22)):*
> ```XML
> use starknet_api::{patricia_key, stark_felt};
> 
> use crate::reader::objects::state::StateUpdate;
> ```

Why not super?



_Code quote:_
```XML
crate::reader
```

**Comment by dan-starkware** [comment]
*[`crates/starknet_client/src/lib.rs` line 1 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/922#-NaLLWYoE6jmE29EIruD:-NaLLWYoE6jmE29EIruE:btagn9k) ([raw file](https://github.com/starkware-libs/papyrus/blob/1853b427f75396fa5479333457fe3d0af2121fad/crates/starknet_client/src/lib.rs#L1)):*
> ```XML
> //! Client implementation for the [`Starknet`] feeder gateway.
> ```

Please fix the documentation (generalize here and move this to the feeder client).
Can be in the next PR



_Code quote:_
```XML
Client implementation for the [`Starknet`] feeder gateway.
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 53 of 55 files at r6, 7 of 7 files at r7, 41 of 42 files at r8, 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/922)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

**Comment by dan-starkware** [comment]
*[`crates/starknet_client/Cargo.toml` line 10 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/922#-NaLM0saD1-nOv5O0sL8:-NaLM0saD1-nOv5O0sL9:b1gr1op) ([raw file](https://github.com/starkware-libs/papyrus/blob/1853b427f75396fa5479333457fe3d0af2121fad/crates/starknet_client/Cargo.toml#L10)):*
> ```TOML
> [features]
> testing = [
>     "mockall",
> ```

In the PR for fixing documentation - please add description here as well

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/922)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/starknet_reader_client/src/reader/starknet_feeder_gateway_client_test.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/922#-NaLKwF53dqpjLl52PkD:-NaLMUwz3-FMPGIWV3ll:bfdm7cf) ([raw file](https://github.com/starkware-libs/papyrus/blob/cd9acdfeb2cb1a335351168956c6302ae61ff729/crates/starknet_reader_client/src/reader/starknet_feeder_gateway_client_test.rs#L22)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not super?
</blockquote></details>

@yair-starkware asked the other way around. I had super and he asked why not crate

**Pull request merged**
