### PR TITLE
feat(network): remove query_id from block_header behaviour (#1590)

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1590)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1590** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1588** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1590#-:-Nnd-L_r-q2TrnXaJMvO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1590#-Nnd-Heh3o8aIxLdzDme:-Nnd-Heh3o8aIxLdzDmf:b1lj0az) ([raw file](https://github.com/starkware-libs/papyrus/blob/8114861b5531b1b8bd2135918fe96fede7ae4068/crates/papyrus_network/src/block_headers/behaviour_test.rs#L15)):*
> ```XML
> // static mut test_db_executor: TestDBExecutor = TestDBExecutor {};
> 
> #[test]
> ```

Why did you erase the #[test]

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1590)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1590#-Nnd-Heh3o8aIxLdzDme:-Nnd2HJ0Cgr0jFBpiYhs:b-7ql1td) ([raw file](https://github.com/starkware-libs/papyrus/blob/8114861b5531b1b8bd2135918fe96fede7ae4068/crates/papyrus_network/src/block_headers/behaviour_test.rs#L15)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did you erase the #[test]
</blockquote></details>

fixed

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1590)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
