### PR TITLE
feat: integrate consensus into main

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2133)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2133)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/papyrus_node/src/main.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-poElQ5PCBLdmGrxNp:-O-poElQ5PCBLdmGrxNq:b-95rhct) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fc946b013ac6c2834033623b332c5b6caddc3b/crates/papyrus_node/src/main.rs#L102)):*
> ```XML
>     let Ok(validator_id) = env::var("CONSENSUS_VALIDATOR_ID") else {
>         return Ok(tokio::spawn(pending()));
>     };
> ```

I thought we wanted to put a (warn?) log if this is turned off.



_Code quote:_
```XML
    let Ok(validator_id) = env::var("CONSENSUS_VALIDATOR_ID") else {
        return Ok(tokio::spawn(pending()));
    };
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-pqV-TEnEOZ0w_2XLP:-O-pqV-TEnEOZ0w_2XLQ:b-ncxygw) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fc946b013ac6c2834033623b332c5b6caddc3b/crates/sequencing/papyrus_consensus/src/lib.rs#L64)):*
> ```XML
> 
> // `Proposal` defined in the protobuf crate so we can't implement `Into` for it because the orphan
> // rule. This wrapper enable us to implement `Into` for the inner `Proposal`.
> ```

Can we define this in papyrus_consensus_context.rs so it's near the Into definition?



_Suggestion:_
```XML
// `Proposal` is defined in the protobuf crate so we can't implement `Into` for it because of the orphan
// rule. This wrapper enables us to implement `Into` for the inner `Proposal`.
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-ps8aH2Kek8EgZKt1N:-O-ps8aH2Kek8EgZKt1O:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fc946b013ac6c2834033623b332c5b6caddc3b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L218)):*
> ```XML
>         let proposal_init =
>             ProposalInit { height: BlockNumber(self.0.height), proposer: self.0.proposer };
>         let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
> ```





_Suggestion:_
```XML
        let (mut content_sender, content_receiver) = mpsc::channel(transactions.len());
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-ps41ECMOeeCSGjmLt:-O-ps41ECMOeeCSGjmLu:bijd02o) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fc946b013ac6c2834033623b332c5b6caddc3b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L222)):*
> ```XML
>             content_sender.try_send(tx).expect("Send should succeed");
>         }
>         content_sender.close_channel();
> ```

Does this not happen at the end of the function when `content_sender` is dropped?



_Code quote:_
```XML
        content_sender.close_channel();
```

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2133)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-q0CJSEwp193f6JC6Z:-O-q0CJSEwp193f6JC6_:bczd648) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82ddb13434a8d9cc9a3a28af7593512a55a67d7/crates/papyrus_node/src/main.rs#L318)):*
> ```XML
>     let state_diff_channels = network_manager.register_sqmr_subscriber(Protocol::StateDiff);
>     let consensus_channels =
>         network_manager.register_broadcast_subscriber(Topic::new("consensus"), 5)?;
> ```

5 is really small

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2133)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/papyrus_node/src/main.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-q0CJSEwp193f6JC6Z:-O-q1vFM2I1ByNIAhj7D:be62fru) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82ddb13434a8d9cc9a3a28af7593512a55a67d7/crates/papyrus_node/src/main.rs#L318)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

5 is really small
</blockquote></details>

Milestone 1 is enough. Matan wanted 100, so I changed.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2133)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/papyrus_node/src/main.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-q2gu3-gnGEAQqXwcd:-O-q2gu3-gnGEAQqXwce:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/99a0434018884bdbf2165dbbb6599369cf841849/crates/papyrus_node/src/main.rs#L104)):*
> ```XML
>         return Ok(tokio::spawn(pending()));
>     };
>     info!("Running consensus as validator {validator_id}");
> ```





_Suggestion:_
```XML
    info!("Running consensus with validator_id={validator_id}");
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 143 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2133#-O-q2xYh8W6GA5IVC2UN:-O-q2xYh8W6GA5IVC2UO:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/99a0434018884bdbf2165dbbb6599369cf841849/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L143)):*
> ```XML
>             if content.next().await.is_some() {
>                 panic!("Received more transactions than expected");
>             }
> ```





_Suggestion:_
```XML
            assert!(
                content.next().await.is_none(),
                "Received more transactions than expected"
            };
```

**Pull request merged**
