### PR TITLE
feat(JSON-RPC): add rpc server generator to reduce code duplication

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/960)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #960** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/960" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/960?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/960)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/api.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/960#-NapfJujEOjNCKphd4ps:-NapfJujEOjNCKphd4pt:bxbnbu4) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b7558c4cc92bc90edf91f9a345ce6e2fdcc6b50/crates/papyrus_gateway/src/api.rs#L142)):*
> ```XML
> }
> 
> pub trait JsonRpcServerImplGen: Sized {
> ```

Is there a need to define a trait fo this? If not, remove this trait (and put its code in an impl block of JsonRpcServerImplGenerator)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/960)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`Cargo.lock` line 4188 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/960#-NauA42694K9ie_wx97b:-NauA42694K9ie_wx97c:bhm4zb5) ([raw file](https://github.com/starkware-libs/papyrus/blob/11959113e1ae7edf575f9434a978d75052412a51/Cargo.lock#L4188)):*
> ```TOML
> [[package]]
> name = "papyrus_execution"
> version = "0.0.3"
> ```

not sure about this but it's cargo lock and I just accept 
___
*[`crates/papyrus_gateway/src/api.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/960#-NapfJujEOjNCKphd4ps:-NauA9AW1dK3bFwOQZ1x:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bb823352cbe49ed5295d3c8f75a558547bfc855f/crates/papyrus_gateway/src/api.rs#L142)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is there a need to define a trait fo this? If not, remove this trait (and put its code in an impl block of JsonRpcServerImplGenerator)
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/960#-:-Nb8Qj-T4kT0sAxUl8uL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
