### PR TITLE
feat()!: store ExecutionResources as part of transaction output

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7tsytE5XsFNnb6fcT:-Nj7tsyu3CkI3X9msuES:b6b66fo) ([raw file](https://github.com/starkware-libs/papyrus/blob/e20b90bfa2671d171cab1f001507558e3361f32d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L435)):*
> ```XML
>     pub messages_sent: Vec<MessageToL1>,
>     pub events: Vec<starknet_api::transaction::Event>,
>     pub execution_status: TransactionExecutionStatus,
> ```

Shouldn't this be deleted? I'm confused
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7slex0wVyzPYmd8XH:-Nj7slex0wVyzPYmd8XI:b-xtrhzf) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L596)):*
> ```XML
> }
> 
> /// The execution resources used by a transaction.
> ```

Consider commenting what's the difference from starknet api
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 626 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7rt8m8Pyk5YlpT_MN:-Nj7rt8m8Pyk5YlpT_MO:b-p08e2d) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L626)):*
> ```XML
> }
> 
> fn into_starknet_api_execution_resources(
> ```

Why not From?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7tsytE5XsFNnb6fcT:-Nj7uK8x5kA_TzEW8rry:brrqwx) ([raw file](https://github.com/starkware-libs/papyrus/blob/e20b90bfa2671d171cab1f001507558e3361f32d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L435)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Shouldn't this be deleted? I'm confused
</blockquote></details>

Versions 3 & 4 shouldn't return the resources so here I remove them. in version 5 I will return the SN_API struct
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7slex0wVyzPYmd8XH:-Nj7vew4EAdF4gBQiKUK:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L596)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider commenting what's the difference from starknet api
</blockquote></details>

done
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 626 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7rt8m8Pyk5YlpT_MN:-Nj7u9vh1bN-Otm7fC_Q:buswnif) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L626)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not From?
</blockquote></details>

Because ExecutionResources is defined in another crate (SN_API)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7tsytE5XsFNnb6fcT:-Nj7w0Qx-wYNtpIPx_2s:b-308cvc) ([raw file](https://github.com/starkware-libs/papyrus/blob/e20b90bfa2671d171cab1f001507558e3361f32d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L435)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Versions 3 & 4 shouldn't return the resources so here I remove them. in version 5 I will return the SN_API struct
</blockquote></details>

Oh this is execution_status, not execution_resources. My bad
But you should comment that this is the difference from starknet api
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 626 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7rt8m8Pyk5YlpT_MN:-Nj7wJWN5QTHMvNUYs8V:b46sufn) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L626)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Because ExecutionResources is defined in another crate (SN_API)
</blockquote></details>

But this ExecutionResources is defined in this crate.
You need that either the trait or the struct implementing the trait be from this crate, and the trait From<ExecutionResources> is from this crate

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7tsytE5XsFNnb6fcT:-Nj7y1Ju50e_mqK1kNk4:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/e20b90bfa2671d171cab1f001507558e3361f32d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L435)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Oh this is execution_status, not execution_resources. My bad
But you should comment that this is the difference from starknet api
</blockquote></details>

done
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 626 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-Nj7rt8m8Pyk5YlpT_MN:-Nj7x0gOD9b39IGQNeqv:b-95ckwq) ([raw file](https://github.com/starkware-libs/papyrus/blob/e32eca76ffa9c75568f5f54b58de1b73de540636/crates/starknet_client/src/reader/objects/transaction.rs#L626)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

But this ExecutionResources is defined in this crate.
You need that either the trait or the struct implementing the trait be from this crate, and the trait From<ExecutionResources> is from this crate
</blockquote></details>

It's a conversion from Client to SN_API, so the trait would be implemented on the target which is not the one in this crate

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-:-Nj83a-02kBHSZLdyhcJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1401#-:-Nj84_tnDGBDr98a7Eft:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
