### PR TITLE
fix: execute with correct versioned constants

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, 2 of 4 files at r4, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-Nsml5YL6D3odAxeWTSf:-Nsml5YL6D3odAxeWTSg:b7dzmt7) (no related file):*
We don't need the execution config preset files anymore, you can delete them and the mechanism that loads them.
The execution config should be a direct part of the RpcConfig

___
___
*[`crates/papyrus_execution/resources/versioned_constants.json` line 0 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmiY8J1XLSIantWQcb:-NsmiY8J1XLSIantWQcc:bt9q3xc) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/resources/versioned_constants.json#L0)):*
Please add the starknet version to the file name
___
*[`crates/papyrus_execution/src/lib.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmkiyY11Ms0D7Zb9TZ:-NsmkiyY11Ms0D7Zb9T_:b4385ci) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L101)):*
> ```XML
> #[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
> /// Parameters that are needed for execution.
> pub struct ExecutionConfig {
> ```

This struct should implement `SerializeConfig` and be the direct member of RpcConfig
___
*[`crates/papyrus_execution/src/lib.rs` line 820 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmjXKvCTuWCcZpIdlW:-NsmjXKvCTuWCcZpIdlX:b-fpyq7c) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L820)):*
> ```XML
> }
> 
> pub(crate) fn get_versioned_constants(
> ```

Please make this function receive the starknet_version instead of the reader and block number



_Code quote:_
```XML
get_versioned_constants
```
___
*[`crates/papyrus_execution/src/lib.rs` line 827 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmjnxV7l4eWPYFZziG:-NsmjnxV7l4eWPYFZziH:bndem1x) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L827)):*
> ```XML
>     let versioned_constants = match starknet_version {
>         Some(starknet_version) => match starknet_version {
>             StarknetVersion(version) if version == "0.13.0" => &VERSIONED_CONSTANTS_13_0,
> ```

use const



_Code quote:_
```XML
0.13.0
```
___
*[`crates/papyrus_execution/src/lib.rs` line 828 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-Nsmjrj3CFHcfJJ9t6WW:-Nsmjrj3CFHcfJJ9t6WX:bndem1x) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L828)):*
> ```XML
>         Some(starknet_version) => match starknet_version {
>             StarknetVersion(version) if version == "0.13.0" => &VERSIONED_CONSTANTS_13_0,
>             StarknetVersion(version) if version == "0.13.1" => &VERSIONED_CONSTANTS_13_1,
> ```

use const



_Code quote:_
```XML
0.13.1
```
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 835 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmqsKT69ZMBHV9QU2X:-NsmqsKT69ZMBHV9QU2Y:b-jk0k11) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L835)):*
> ```XML
>         drop(txn);
>         let state_number = StateNumber::right_after_block(block_number);
>         let execution_config = self.execution_config.clone();
> ```

No reason to clone here (same for all spec versions)



_Code quote:_
```XML
.clone();
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: 3 of 21 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-Nsml5YL6D3odAxeWTSf:-NsnLtln6ewadr5ZKfvN:bs12x76) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We don't need the execution config preset files anymore, you can delete them and the mechanism that loads them.
The execution config should be a direct part of the RpcConfig
</blockquote></details>

We will do this in a different pr as we discussed yesterday

___
___
*[`crates/papyrus_execution/src/lib.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmkiyY11Ms0D7Zb9TZ:-NsnM65O6tG843Sf0REH:b-pn3u9b) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L101)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This struct should implement `SerializeConfig` and be the direct member of RpcConfig
</blockquote></details>

see above about different pr
___
*[`crates/papyrus_execution/src/lib.rs` line 820 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmjXKvCTuWCcZpIdlW:-NsnLlTR7RdC-v9ByIXo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L820)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please make this function receive the starknet_version instead of the reader and block number
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 827 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmjnxV7l4eWPYFZziG:-NsnLly0EOI7OYFjAO--:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L827)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

use const
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 828 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-Nsmjrj3CFHcfJJ9t6WW:-NsnLmkVAF2hGm877AQm:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/src/lib.rs#L828)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

use const
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 835 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmqsKT69ZMBHV9QU2X:-NsnLoEACnqsFkKc8qBV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L835)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No reason to clone here (same for all spec versions)
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/resources/versioned_constants.json` line  at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsmiY8J1XLSIantWQcb:-NsnLgL24bghjzVGbZLO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4069e82295867b8ffb8028863e355dc4686f76c9/crates/papyrus_execution/resources/versioned_constants.json#L)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add the starknet version to the file name
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 823 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsnS-S69Fiscosnp4pB:-NsnS-S78w3crfN3kA_S:b-lg4w6q) ([raw file](https://github.com/starkware-libs/papyrus/blob/4fbf643253b28ccddd40d47c81cb733943d3ec60/crates/papyrus_execution/src/lib.rs#L823)):*
> ```XML
> 
> fn get_versioned_constants(
>     starknet_version: Option<StarknetVersion>,
> ```

Option<&StarknetVersion>



_Code quote:_
```XML
StarknetVersion
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 823 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NsnS-S69Fiscosnp4pB:-NsquS0O3VAugeliKYki:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4fbf643253b28ccddd40d47c81cb733943d3ec60/crates/papyrus_execution/src/lib.rs#L823)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Option<&StarknetVersion>
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-:-NtATozBBGsPdfxQzLtE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r11, 1 of 5 files at r13, 2 of 4 files at r17, 18 of 19 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 837 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NtBWSSTEAbTC1xfhO3v:-NtBWSSU2k4DUXG-xGEy:bddvakz) ([raw file](https://github.com/starkware-libs/papyrus/blob/73dd3ab5e82ec8fd8188670fec0880e0733e9cbd/crates/papyrus_execution/src/lib.rs#L837)):*
> ```XML
>         },
>         // If the block number is greater than the last block number that exists, we use the latest
>         // constants.
> ```

The comment is not correct, I suggest simply removing it



_Code quote:_
```XML
        // If the block number is greater than the last block number that exists, we use the latest
        // constants.
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 837 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-NtBWSSTEAbTC1xfhO3v:-NtB_lcc8swv8fAiehxj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/73dd3ab5e82ec8fd8188670fec0880e0733e9cbd/crates/papyrus_execution/src/lib.rs#L837)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The comment is not correct, I suggest simply removing it
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1804#-:-NtBjpy81PHFClXtCVhH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
