### PR TITLE
feat(JSON-RPC): add starknet_addDeployAccountTransaction

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(JSON-RPC): add type alias for DeployAccountTransaction
- feat(JSON-RPC): add starknet_addInvokeTransaction
- feat(JSON-RPC): add starknet_addInvokeTransaction

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/mod.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1021#-NbV1Tyb-HHPiCuVbqH9:-NbV1Tyb-HHPiCuVbqHA:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/145410cb748d1955f8108366735139046f4d476d/crates/papyrus_gateway/src/v0_4_0/api/mod.rs#L148)):*
> ```XML
>     ) -> RpcResult<AddInvokeOkResult>;
> 
>     /// Submits a new invoke transaction to be added to the chain.
> ```





_Suggestion:_
```XML
deploy account
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/mod.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1021#-NbV1Tyb-HHPiCuVbqH9:-NbV2ULG1DgRqAEkFW1a:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/145410cb748d1955f8108366735139046f4d476d/crates/papyrus_gateway/src/v0_4_0/api/mod.rs#L148)):*
> ```XML
>     ) -> RpcResult<AddInvokeOkResult>;
> 
>     /// Submits a new invoke transaction to be added to the chain.
> ```

Done.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021#-:-NbV2bT88eDpfTSczZdW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
