### PR TITLE
feat(consensus): set NodeId to ContractAddress

### PR DESCRIPTION
**Pull request by matan-starkware**
While not yet set in stone this is the leading contender and matches what is defined in the proto.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2078)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2078?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2078** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2078?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2077** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2077?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2069** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2069?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2064** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2064?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2059** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2059?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2058** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2058?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2078#-:-NzbqZyK7jMw8pfFu5I-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by DvirYo-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2078#-:-NzvutjfBPASiUEuHUeo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2078#-:-NzxBmALEu0pKR29NaJ6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
