### PR TITLE
Dvir/transactions module changes

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/500)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/500)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/500#-NOP3RlkChdo9fgMz9Zj:-NOP3RlkChdo9fgMz9Zk:be3xq8a) (no related file):*
this pull request creates a new module for functions that creates Transaction object

___

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/500)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/500#-NOP858l2laz8rgQx2CN:-NOP858l2laz8rgQx2CO:b7ez9d5) (no related file):*
The second and third commits are because of a git error. Sorry about that.

___

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/500#-:-NOn1CJ_0dgP6aIrTJDB:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/main.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/500#-NOn1-Qx3zMgrQ-qr1n9:-NOn1-Qx3zMgrQ-qr1nA:b-551ujf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d320402b3354dcc86c9dfeda21955081e93c3a10/crates/papyrus_load_test/src/main.rs#L12)):*
> ```XML
> use goose::goose::{Scenario, Transaction};
> use goose::{scenario, transaction, util, GooseAttack};
> use papyrus_load_test::load_tests::*;
> ```

So now this is not used, right? If so, please remove.



_Code quote:_
```XML
use papyrus_load_test::load_tests::*;
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/main.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/500#-NOn1-Qx3zMgrQ-qr1n9:-NOn1UxQBKHKNT1w1DN5:b-4ts7my) ([raw file](https://github.com/starkware-libs/papyrus/blob/d320402b3354dcc86c9dfeda21955081e93c3a10/crates/papyrus_load_test/src/main.rs#L12)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

So now this is not used, right? If so, please remove.
</blockquote></details>

It was removed in the nex pull request (#503)

**Pull request merged**
