### PR TITLE
declare class table split

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #668** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/668" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/668?utm_source=stack-comment).

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8iNG84QTUOu53_87_:-NV8iNG84QTUOu53_87a:bm052kb) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L60)):*
> ```XML
>     ThinStateDiff,
>     IndexMap<ClassHash, ContractClass>,
>     IndexMap<ClassHash, BlockNumber>,
> ```

I think we shouldn't add it. The information is within `ThinStateDiff` (and before this PR we used here `ContractClass`, not `IndexedContractClass`)
___
*[`crates/papyrus_storage/src/state/mod.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8jU88BW38ZwKQrASW:-NV8jU88BW38ZwKQrASX:bxbzl3d) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L447)):*
> ```XML
>         match res {
>             Ok(()) => continue,
>             Err(err) => return Err(err.into()),
> ```

Not related to this PR, can you please map the error to `StorageError::ClassAlreadyExists` (or add a TODO)?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8kNAkAQK2J0QqhCVC:-NV8kNAkAQK2J0QqhCVD:bi0k1w6) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L453)):*
> ```XML
> }
> 
> fn write_declared_classes_block<'env>(
> ```

Consider merging with `write_declared_classes` so we iterate over `declared_classes` only once.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8zGH4-0sUijXFaHKu:-NV8zGH4-0sUijXFaHKv:b-9q7rmh) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L250)):*
> ```XML
>             if state_number.is_after(block_number) {
>                 return Ok(Some(contract_class));
>             }
> ```

Check the block number before fetching the class (better performance)



_Code quote:_
```XML
            if state_number.is_after(block_number) {
                return Ok(Some(contract_class));
            }
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 592 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV90PO8-DfGgu5lBOVU:-NV90PO8-DfGgu5lBOVV:b-g9wowj) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L592)):*
> ```XML
>         let block_number = declared_classes_block_table
>             .get(txn, class_hash)?
>             .expect("Missing declared class {class_hash:#?}.");
> ```

No need to get the block number from the db



_Code quote:_
```XML
        let block_number = declared_classes_block_table
            .get(txn, class_hash)?
            .expect("Missing declared class {class_hash:#?}.");
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8zGH4-0sUijXFaHKu:-NVO521N61232gEno73q:b-pkfjfo) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L250)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Check the block number before fetching the class (better performance)
</blockquote></details>

is this what you meant?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8kNAkAQK2J0QqhCVC:-NVOI64o05KWIEBF_03a:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L453)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider merging with `write_declared_classes` so we iterate over `declared_classes` only once.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 592 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV90PO8-DfGgu5lBOVU:-NVO4XBJAgrlJNFxGMhO:byashlk) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L592)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No need to get the block number from the db
</blockquote></details>

what do you mean? we need to add it to the deleted_data map just like it is in `delete_declared_classes`
please explain if I missunderstood

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8zGH4-0sUijXFaHKu:-NVOnFBD4PpRGHKseETo:b-5mldyc) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L250)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

is this what you meant?
</blockquote></details>

I meant that if your'e going to return None then there is no need to get the class, so you can first compare the block number to the state number and only if needed you should fetch the class.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 592 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV90PO8-DfGgu5lBOVU:-NVOoVg_-ySm7bAipOZs:b-ghttf2) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L592)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

what do you mean? we need to add it to the deleted_data map just like it is in `delete_declared_classes`
please explain if I missunderstood
</blockquote></details>

We know the block number that is being reverted, so there is no need to get it from the storage.
When deleting the classes, we need to read the data from the storage in order to insert it into the Ommer tables.
Also, I think I would merge delete_declared_classes and delete_declared_classes_block into a single function.

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV8zGH4-0sUijXFaHKu:-NVP1IO_6GY4AehIAl-F:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L250)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I meant that if your'e going to return None then there is no need to get the class, so you can first compare the block number to the state number and only if needed you should fetch the class.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 592 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NV90PO8-DfGgu5lBOVU:-NVP1QvGBDvr1oKhXxNG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9c32473899964351131327afc65d96163ff94a88/crates/papyrus_storage/src/state/mod.rs#L592)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We know the block number that is being reverted, so there is no need to get it from the storage.
When deleting the classes, we need to read the data from the storage in order to insert it into the Ommer tables.
Also, I think I would merge delete_declared_classes and delete_declared_classes_block into a single function.
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668#-:-NVP3GX6ETbmqF9_z_2d:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 253 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NVQTP_38pH2B9mRZItw:-NVQTP_38pH2B9mRZItx:b9cfeg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/dbc758fdbd904cb3c3961c3948dfe09572217e67/crates/papyrus_storage/src/state/mod.rs#L253)):*
> ```XML
>             }
>         }
>         Ok(None)
> ```

Consider using let-else statements (early returns and less indentations) 



_Suggestion:_
```XML
        let Some(block_number) = 
            self.declared_classes_block_table.get(self.txn, class_hash)? else {return Ok(None)};
        if state_number.is_before(block_number) {
            return Ok(None);
        }
        let Some(contract_class) =
            self.declared_classes_table.get(self.txn, class_hash)? else {return Ok(None)};
        return Ok(Some(contract_class))
        }
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 445 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/668#-NVQWZC95T_jdMUxXO0z:-NVQWZC95T_jdMUxXO1-:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/dbc758fdbd904cb3c3961c3948dfe09572217e67/crates/papyrus_storage/src/state/mod.rs#L445)):*
> ```XML
>                 return Err(StorageError::ClassAlreadyExists { class_hash: (*class_hash) });
>             }
>         }
> ```





_Suggestion:_
```XML
        match [res_class, res_block].iter().any(|res| res.is_err()) {
        match (res_class, res_block) {
            false => continue,
            true => {
                return Err(StorageError::ClassAlreadyExists { class_hash: (*class_hash) });
            }
        }
```

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668#-:-NVTTjkG1VtbqiOGz50I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
