### PR TITLE
perf(storage)!: store event inside transaction output

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyFEfJC1R_y-e8ZeKC7:-NyFEfJC1R_y-e8ZeKC8:b-29e1kx) (no related file):*
I didn't delete the old ThinTransactionOutput types and functionality to make this pull request as thin as possible. It will be deleted in other PR.

___
___
*[`crates/papyrus_storage/src/body/events.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyFFCJG-z1GbvdhqV4P:-NyFFCJG-z1GbvdhqV4Q:b-uy8jdw) ([raw file](https://github.com/starkware-libs/papyrus/blob/3945651ab0cb32d6da4849c92bf16f2290f7000f/crates/papyrus_storage/src/body/events.rs#L281)):*
> ```XML
> }
> 
> #[allow(missing_docs)]
> ```

I deleted the comment because it fails the docs job in the CI, and I am going to delete this struct so I didn't take effort into it.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: all files reviewed, 13 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP8Evo56SDXxxgoUEd:-NyP8Evo56SDXxxgoUEe:bwb9ipw) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L145)):*
> ```XML
>     txn: &'txn DbTransaction<'env, RO>,
>     file_handles: &'txn FileHandlers<RO>,
>     current: Option<EventsTableKeyValue>,
> ```

Change to EventsTableKey
___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPB4pg-qsJDLrScks2:-NyP8M0K367Qfq-uM2ag:bcuo5aq) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L145)):*
> ```XML
>     txn: &'txn DbTransaction<'env, RO>,
>     file_handles: &'txn FileHandlers<RO>,
>     current: Option<EventsTableKeyValue>,
> ```

It is not clear when this is None. Document it
___
*[`crates/papyrus_storage/src/body/events.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPAosj2hr56RMCK9Yf:-NyPAosj2hr56RMCK9Yg:brf8d4c) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L146)):*
> ```XML
>     file_handles: &'txn FileHandlers<RO>,
>     current: Option<EventsTableKeyValue>,
>     tx_current: Option<(TransactionIndex, TransactionOutput)>,
> ```

Consider renaming to current_tx
___
*[`crates/papyrus_storage/src/body/events.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPB18Z5RfpMqtESpEm:-NyPB18Z5RfpMqtESpEn:bcuo5aq) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L146)):*
> ```XML
>     file_handles: &'txn FileHandlers<RO>,
>     current: Option<EventsTableKeyValue>,
>     tx_current: Option<(TransactionIndex, TransactionOutput)>,
> ```

It is not clear when this is None. Document it
___
*[`crates/papyrus_storage/src/body/events.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP9ygpDgUoq6F5tbsa:-NyP9ygpDgUoq6F5tbsb:b-b8i9n4) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L157)):*
> ```XML
>     /// Returns [`StorageError`](crate::StorageError) if there was an error.
>     fn next(&mut self) -> StorageResult<Option<(EventsTableKey, EventContent)>> {
>         let res = self.current.take();
> ```

Remove the definition of this variable and put `self.current.take()` inside the line below it
___
*[`crates/papyrus_storage/src/body/events.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPAIKyA-ujVwIkb-LN:-NyPAIKyA-ujVwIkb-LO:b-v9yjmo) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L163)):*
> ```XML
>         if self.tx_current.is_none()
>             || tx_index
>                 != self.tx_current.as_ref().expect("The None case was checked previously.").0
> ```

Consider instead
```
if self.tx_current.as_ref().map(|tx_current| tx_current.0 != tx_index).unwrap_or(true)
```
___
*[`crates/papyrus_storage/src/body/events.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPBaAh7lTnHtZw0wo0:-NyPBaAh7lTnHtZw0wo1:b-ee1e8b) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L175)):*
> ```XML
> 
>         let key = (contract_address, EventIndex(tx_index, event_offset));
>         // TODO(dvir): don't clone here the event content.
> ```

How big is an event? Are you sure it's ok to leave this TODO unimplemented
Is this function used only in RPC or in sync as well
___
*[`crates/papyrus_storage/src/body/events.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPBgQ-7Lb7XDe4srWJ:-NyPBgQ-7Lb7XDe4srWK:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/body/events.rs#L216)):*
> ```XML
>         };
>         let key = (*from_address, EventIndex(*tx_index, self.event_index_in_tx_current));
>         // TODO(dvir): don't clone here the event content.
> ```

Same here
___
*[`crates/papyrus_storage/src/db/table_types/mod.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPC5Q-C7AZssOacax2:-NyPC5Q-C7AZssOacax3:b-dzn2ad) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/db/table_types/mod.rs#L93)):*
> ```XML
> // A value place holder for tables where we don't need a value.
> #[derive(Clone, Copy, Debug, Eq, PartialEq, PartialOrd, Ord)]
> pub(crate) struct ValuePlaceHolder;
> ```

Rename to NoValue/EmptyValue
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP7vOw9Mr4MrgThbAn:-NyP7vOw9Mr4MrgThbAo:bweumge) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/papyrus_storage/src/serialization/serializers.rs#L204)):*
> ```XML
>         V2(DeclareTransactionV2) = 2,
>         V3(DeclareTransactionV3) = 3,
>     }
> ```

You should erase all the ThinTransactionOutput structs from here, right? Are you planning to do so in a future PR?
___
*[`crates/test_utils/src/lib.rs` line 494 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP82CiB0zhlnwetWXM:-NyP82CiB0zhlnwetWXN:b-hmtim2) ([raw file](https://github.com/starkware-libs/papyrus/blob/970dbc6028586f52ff8dff2e2f688259c85d9787/crates/test_utils/src/lib.rs#L494)):*
> ```XML
>         V3(DeclareTransactionV3) = 3,
>     }
>     pub struct DeclareTransactionOutput {
> ```

Same here (erasing Thin)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/body/events.rs` line 160 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPUcgNEc0T_0gsspUK:-NyPUcgNEc0T_0gsspUL:brax6wz) ([raw file](https://github.com/starkware-libs/papyrus/blob/448a0067a1e72011b0dc1241c90c65d68cf50d29/crates/papyrus_storage/src/body/events.rs#L160)):*
> ```XML
>     /// Returns [`StorageError`](crate::StorageError) if there was an error.
>     fn next(&mut self) -> StorageResult<Option<(EventsTableKey, EventContent)>> {
>         // let res = self.current.take();
> ```

Remove this instead of commenting

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP8Evo56SDXxxgoUEd:-NyPGRjxDNE5_2Q07fZy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L145)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change to EventsTableKey
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPB4pg-qsJDLrScks2:-NyPHoeE91qwVff_tBER:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L145)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It is not clear when this is None. Document it
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPB18Z5RfpMqtESpEm:-NyPHpaE8ybnTPdkw9eA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L146)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It is not clear when this is None. Document it
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP9ygpDgUoq6F5tbsa:-NyPI1ip7PDL7cZUXGP6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L157)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove the definition of this variable and put `self.current.take()` inside the line below it
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPAIKyA-ujVwIkb-LN:-NyPIOMdD3yy6eJVHn5n:b5r65c3) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L163)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider instead
```
if self.tx_current.as_ref().map(|tx_current| tx_current.0 != tx_index).unwrap_or(true)
```
</blockquote></details>

Considered. It looks confusing to me.
___
*[`crates/papyrus_storage/src/body/events.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPBaAh7lTnHtZw0wo0:-NyPIXqXCR79EvAEuiER:b-j2hm4s) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L175)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

How big is an event? Are you sure it's ok to leave this TODO unimplemented
Is this function used only in RPC or in sync as well
</blockquote></details>

1. The event is not a very big object
2. currently this is not used in the sync (and shouldn't ever be used in the sync, but we already use things we should use in the sync)
3. It is fine to leave this todo
4. to implement this todo I need to make a change in sn-api
5. In general, cloning is not our problem at all.
___
*[`crates/papyrus_storage/src/body/events.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPBgQ-7Lb7XDe4srWJ:-NyPJN-I6a6HrUflYSwB:b4te6lq) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/body/events.rs#L216)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Same answer. It will be done in the future
___
*[`crates/papyrus_storage/src/db/table_types/mod.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPC5Q-C7AZssOacax2:-NyPJhId2E3en1HRbTFk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/db/table_types/mod.rs#L93)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to NoValue/EmptyValue
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyP7vOw9Mr4MrgThbAn:-NyPJj-CBhpQMUqurhnU:bz30n8s) ([raw file](https://github.com/starkware-libs/papyrus/blob/71462d8cbb5fda76a7b1b5cd9d57e2179d19e224/crates/papyrus_storage/src/serialization/serializers.rs#L204)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should erase all the ThinTransactionOutput structs from here, right? Are you planning to do so in a future PR?
</blockquote></details>

Yes, as I wrote, this is not done in this PR to make it as thin as possible.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/body/events.rs` line 160 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-NyPUcgNEc0T_0gsspUK:-NyPVV_BAHA-iVptwAuX:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/448a0067a1e72011b0dc1241c90c65d68cf50d29/crates/papyrus_storage/src/body/events.rs#L160)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this instead of commenting
</blockquote></details>

done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2000#-:-NyPViqR2yeg6n4H6CI3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
