### PR TITLE
use pretty_assertions in tests

### PR DESCRIPTION
**Pull request by TzahiTaub**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

A failure in `assert_eq` (in tests) does not point to the exact difference.

Issue Number: N/A

## What is the new behavior?

- Use `assert_eq` from the pretty_assertions crate.  A failure will produce a colorful message pointing to the exact difference.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807)

### CODE REVIEW

**Review by yoavGrs — DISMISSED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807#-:-NZdX8pM9cptD251Y826:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807#-:-NZe48zEEzR4Al09wlnD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/807#-:-NZena5W3VmeLGxLkA_i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
