### PR TITLE
build(network): add benchmark executable to streamed_data

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
`streaned_data_protocol` is an internal abstraction of papyrus_network I don't think anything there needs to be public.. please try to find a way to keep all the `pub(crate)`

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-:-NnhFcku4Mqft_ypFmQJ:b-jwerfo)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGHGY5vpF2v72re9d:-NnhGHGY5vpF2v72re9e:b-mi8ibh) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L73)):*
> ```XML
>     let mut swarm = SwarmBuilder::with_existing_identity(key_pair)
>         .with_tokio()
>         .with_quic()
> ```

probably a good idea to be able to configure what transport to use in the test
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGsNICM_C-zi85vCS:-NnhGsNICM_C-zi85vCT:b-4ssh7e) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L99)):*
> ```XML
>     let mut outbound_session_measurements = HashMap::new();
>     while let Some(event) = swarm.next().await {
>         match event {
> ```

can you extract the match cases into functions to make it easier to read?

**Review by ShahakShama — COMMENTED** [review]
The `bin` is considered a different crate. There's nothing we can do

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-:-NnhHs280AWeqelhM777:b-tvni3c)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGHGY5vpF2v72re9d:-NnhI4qz0qlWzW_kU-Hy:b-b47flh) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L73)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

probably a good idea to be able to configure what transport to use in the test
</blockquote></details>

we plan to always use quic AFAIK

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGsNICM_C-zi85vCS:-Nni9zkK76Ax4xqFA8Lv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L99)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

can you extract the match cases into functions to make it easier to read?
</blockquote></details>

Done.

**Review by nagmo-starkware — COMMENTED** [review]
what about pub(self) / pub(un path)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-:-NniSGe53E_xF84KfmO_:bfgsqtt)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGHGY5vpF2v72re9d:-NoLRzteCeEBsmgRue5H:b-b8xoft) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

we plan to always use quic AFAIK
</blockquote></details>

I highly doubt that.. we can't be sure that other peers will use QUIC and it's easy to support TCP also. 
I can also see it being meaningful for stress testing in the future
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLSXOhDTtWOvejEuJa:-NoLSXOhDTtWOvejEuJb:be0ymd4) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L118)):*
> ```XML
> }
> #[tokio::main]
> async fn main() {
> ```

please separate swarm building from the poll loop. it'll make it much easier to focus on the important part of the code
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLTnN98oJhb0EbgPok:-NoLTnN98oJhb0EbgPol:b-q1rz5n) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L174)):*
> ```XML
>                 },
>             ) => {
>                 let OutboundSessionMeasurement { start_time, num_messages, message_size } =
> ```

isn't it important to know if it was close by peer of by request?
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLT5L24ju24DvJtVDz:-NoLT5L24ju24DvJtVE-:b-hwzd58) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L208)):*
> ```XML
>                 println!("Session {:?} failed on {}", session_id, io_error.kind());
>             }
>             _ => {}
> ```

maybe panic here? or do you expect this? if so do something here to help future self :)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NnhGHGY5vpF2v72re9d:-NoLUW0w-8cmdV2JtNdk:b-lfek87) ([raw file](https://github.com/starkware-libs/papyrus/blob/c70306f0a73703ae5c0f8131293bf2a022fa754e/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L73)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I highly doubt that.. we can't be sure that other peers will use QUIC and it's easy to support TCP also. 
I can also see it being meaningful for stress testing in the future
</blockquote></details>

Anyway, this is a feature on top of the existing benchmark exe. I suggest we add it when we need to add it
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLSXOhDTtWOvejEuJa:-NoLYPXk58JlBL7qFCfu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L118)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please separate swarm building from the poll loop. it'll make it much easier to focus on the important part of the code
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLTnN98oJhb0EbgPok:-NoLYXItBwwqalS082Zw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L174)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

isn't it important to know if it was close by peer of by request?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLT5L24ju24DvJtVDz:-NoLa21X3yMyVJ7rIywQ:b-6ae4om) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed8b911f97499dd28e8f1fa249676751fa0aea24/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L208)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

maybe panic here? or do you expect this? if so do something here to help future self :)
</blockquote></details>

Done. (I've put all the events I do expect in a separate clause)

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 143 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLexSG81XjkolTxIEv:-NoLexSG81XjkolTxIEw:b2jeg4y) ([raw file](https://github.com/starkware-libs/papyrus/blob/739a0e23e471e0e7d5426db457a0d0c33d93fa13/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L143)):*
> ```XML
> }
> 
> fn dial_if_requested(swarm: &mut Swarm<Behaviour<BasicMessage, StressTestMessage>>, args: &Args) {
> ```

I'd rather the condition be outside of the function and not send all the args but it's a stylistic choice so I leave it up to you
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLfBgy87l_wDzYilOm:-NoLfBgy87l_wDzYilOn:bq2eeql) ([raw file](https://github.com/starkware-libs/papyrus/blob/739a0e23e471e0e7d5426db457a0d0c33d93fa13/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L219)):*
> ```XML
>             | SwarmEvent::ConnectionClosed { .. } => {}
>             SwarmEvent::OutgoingConnectionError { .. } => {
>                 dial_if_requested(&mut swarm, &args);
> ```

change order

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLfBgy87l_wDzYilOm:-NoLhiaPBDAOMmYbtND3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/739a0e23e471e0e7d5426db457a0d0c33d93fa13/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L219)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

change order
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 143 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-NoLexSG81XjkolTxIEv:-NoLhrTG2IqlUeAgyUSQ:bt426o1) ([raw file](https://github.com/starkware-libs/papyrus/blob/739a0e23e471e0e7d5426db457a0d0c33d93fa13/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L143)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I'd rather the condition be outside of the function and not send all the args but it's a stylistic choice so I leave it up to you
</blockquote></details>

I prefer this way

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 1 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1591#-:-NoLhyOc72U9bmYPhg4A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
