### PR TITLE
feat(network): add BlockHeaderDBExecutor and extract common functionality

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1630)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1630?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1628** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1628?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1630** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1630?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1630?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1630#-NoqxsO10diL3fujM2VX:-NoqxsO10diL3fujM2VY:b-rkdy1z) ([raw file](https://github.com/starkware-libs/papyrus/blob/595e2ac490fbf3844cc7cd37033703a9fee041c9/crates/papyrus_network/src/db_executor/mod.rs#L27)):*
> ```XML
>     // Get an active query and the number of blocks read so far.
>     // Specific implementations may decide on the strategy.
>     fn get_active_query(&mut self) -> Option<(QueryId, &mut BlockQuery, &mut u64)>;
> ```

Why do you need to extract all this functionality to the trait? I don't see any advantage from sharing the poll_func between DummyDBExecutor andDBExecutor (especially since we're going to erase DummyDBExecutor)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1630#-NoqxsO10diL3fujM2VX:-NoumJDaAofdRjYX-dqI:b-qmul3x) ([raw file](https://github.com/starkware-libs/papyrus/blob/595e2ac490fbf3844cc7cd37033703a9fee041c9/crates/papyrus_network/src/db_executor/mod.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you need to extract all this functionality to the trait? I don't see any advantage from sharing the poll_func between DummyDBExecutor andDBExecutor (especially since we're going to erase DummyDBExecutor)
</blockquote></details>

I don't think we will.. it's useful for testing. and as I said and we discussed with Dan & Ittay I can see a paradigm where we will implement this trait many times for each data type..
anyhow even for two implementations I don't see any reason not to share the code

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1630#-:-Np-0ynY0qz8hLg17ql3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
