### PR TITLE
refactor(consensus): the Context is passed as a param instead of being held as a field by SHC

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2238?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2239** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2239?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2237?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-:-O2JxcrxEqZCzDeQ7I0V:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O7m2s1WsK0QSSVFnF:-O2O7m2tBU3HWNKC1aAF:bxeem9j) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/lib.rs#L39)):*
> ```XML
> #[allow(missing_docs)]
> async fn run_height<BlockT: ConsensusBlock>(
>     context: &impl ConsensusContext<Block = BlockT>,
> ```

IMO impl should be used only if you have this type in this 1 place. Since you're using it everywhere, IMO <ConsensusContextT: ConsensusContext> will be cleaner
Same in SHC
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O8C1u4kLvLijksN-U:-O2O8C1u4kLvLijksN-V:b4idg53) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L57)):*
> ```XML
>     pub(crate) async fn start(
>         &mut self,
>         context: &impl ConsensusContext<Block = BlockT>,
> ```

You're choosing here that each function can have a different type of context instead of having the context type hardcoded in the struct with a phantom. I'm just making sure you're aware of the 2 different options here and that you chose the one more correct to your case
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O8X-VC5bTX-WsvSHm:-O2O8X-VC5bTX-WsvSHn:b-irlfps) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L63)):*
> ```XML
> 
>     // Sends proposal and prevote.
>     assert!(matches!(shc.start(&context,).await, Ok(None)));
> ```

why ,?

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O7m2s1WsK0QSSVFnF:-O2OVy4H6xsGOmTUs0Sl:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/lib.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO impl should be used only if you have this type in this 1 place. Since you're using it everywhere, IMO <ConsensusContextT: ConsensusContext> will be cleaner
Same in SHC
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O8C1u4kLvLijksN-U:-O2OVz1m4V802E62fAH0:blau0ss) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L57)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're choosing here that each function can have a different type of context instead of having the context type hardcoded in the struct with a phantom. I'm just making sure you're aware of the 2 different options here and that you chose the one more correct to your case
</blockquote></details>

Yes I'm aware. My feeling was that `context` is basically an outside resource and the caller can pass it what it wants. It would be very weird for it to pass multiple types, but I felt that adding `PhantomData` to the struct definition increases complexity for a benefit that I am not sure exists.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-O2O8X-VC5bTX-WsvSHm:-O2OWONh8QdnELJXhy-S:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9aa2aec2846488481f8f8c4eb85dda7fb4e22e6b/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L63)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

why ,?
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238#-:-O2ObkGkAqB30zzmGVoQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2238)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
