### PR TITLE
Set logger in the gateway by collect_metrics flag

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1 and @OriStarkware)

___
*[`config/config.yaml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z1YvH3Pxc62t_3LnE:-N_Z1YvH3Pxc62t_3LnF:b-vei6sg) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/config/config.yaml#L34)):*
> ```YAML
>     max_events_keys: 100
>     # If true, collect metrics for the package.
>     collect_metrics: false
> ```

We already have a config variable with the same name; change it to:
    
    # If true, collect metrics in the gateway.
    gateway_collect_metrics: false
___
*[`crates/papyrus_gateway/src/api.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z3W2q2C2-IHP1ubgX:-N_Z3W2r-Y7xoAAV17fe:b-bll738) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/api.rs#L105)):*
> ```XML
>     max_events_chunk_size: usize,
>     max_events_keys: usize,
>     collect_metrics: bool,
> ```

Why do you need the collect_metrics here? 
I think you need this information only in the run_server function.
___
*[`crates/papyrus_gateway/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z44g-3vZE3f8oyvRQ:-N_Z44g-3vZE3f8oyvRR:bjod21z) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L122)):*
> ```XML
>     }
> }
> use gateway_metrics::MetricLogger;
> ```

Move this to the head of the file with all the other uses. This is a mistake I made.
___
*[`crates/papyrus_gateway/src/test_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z4Uk1AXAnY1ZOC_sz:-N_Z4Uk1AXAnY1ZOC_t-:bi1u0bz) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/test_utils.rs#L30)):*
> ```XML
>             config.max_events_chunk_size,
>             config.max_events_keys,
>             config.collect_metrics,
> ```

Again, I don’t think you need this here.

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: all files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware and @OriStarkware)

___
*[`config/config.yaml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z1YvH3Pxc62t_3LnE:-N_bb6aP1bF569bCbVnV:b-otooqa) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/config/config.yaml#L34)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

We already have a config variable with the same name; change it to:
    
    # If true, collect metrics in the gateway.
    gateway_collect_metrics: false

</blockquote></details>

is there a problem with using the same config variable names in different places? 
it looks like there are other some configs.
___
*[`crates/papyrus_gateway/src/lib.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_bbhYICJb2f6uyOuOJ:-N_bbhYICJb2f6uyOuOK:b-kjxjyo) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L148)):*
> ```XML
>             .await?;
>         addr = server.local_addr()?;
>         handle = server.start(methods)?;
> ```

can't you initialize addr and handle after the if-else and avoid the code duplication?



_Code quote:_
```XML
        addr = server.local_addr()?;
        handle = server.start(methods)?;
```

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: all files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @OriStarkware)

___
*[`config/config.yaml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z1YvH3Pxc62t_3LnE:-N_bcZsKC-hZZUgoXCBN:b-rcwi33) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/config/config.yaml#L34)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

is there a problem with using the same config variable names in different places? 
it looks like there are other some configs.
</blockquote></details>

In general, I think this is fine, but since this variable configuration conflicts with the monitoring collect_matrics variable (monitoring=true, this=false will not collect metrics at all), I think we should make it explicit as we can.
If you have a strong opinion on that, you can keep the name but change the description.
___
*[`crates/papyrus_gateway/src/lib.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_bbhYICJb2f6uyOuOJ:-N_be0xxAV6g9T0JEvLc:b-ksnqu) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L148)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

can't you initialize addr and handle after the if-else and avoid the code duplication?
</blockquote></details>

It can be done. What happens is those functions are chosen by the compiler by the types they operate on (generic function), so since the two branches return a server object with different types the compiler can’t choose which function to use.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware and @OmriEshhar1)

___
*[`config/config.yaml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z1YvH3Pxc62t_3LnE:-N_mMBE69khHwjB7eCGq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/config/config.yaml#L34)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In general, I think this is fine, but since this variable configuration conflicts with the monitoring collect_matrics variable (monitoring=true, this=false will not collect metrics at all), I think we should make it explicit as we can.
If you have a strong opinion on that, you can keep the name but change the description.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z44g-3vZE3f8oyvRQ:-N_mTxYU-J6fgkVLvHPG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L122)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Move this to the head of the file with all the other uses. This is a mistake I made.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/lib.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_bbhYICJb2f6uyOuOJ:-N_mT9b07CsbOXq4AzVS:b-zzakw) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L148)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

It can be done. What happens is those functions are chosen by the compiler by the types they operate on (generic function), so since the two branches return a server object with different types the compiler can’t choose which function to use.
</blockquote></details>

I don’t think it can be done easily, am I wrong?
___
*[`crates/papyrus_gateway/src/test_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z4Uk1AXAnY1ZOC_sz:-N_mHyLo7fpurGJy0pp-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/test_utils.rs#L30)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Again, I don’t think you need this here.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/api.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z3W2q2C2-IHP1ubgX:-N_mJ7nS0RzOhGNPqfwI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/api.rs#L105)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why do you need the collect_metrics here? 
I think you need this information only in the run_server function.
</blockquote></details>

Done.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @OriStarkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z44g-3vZE3f8oyvRQ:-N_mePPl9iOkTM944Yyd:bvr0446) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L122)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant only the line
"use gateway_metrics::MetricLogger;"
return the run_server function to the original location.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware and @OmriEshhar1)

___
*[`crates/papyrus_gateway/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/866#-N_Z44g-3vZE3f8oyvRQ:-N_mln-H315DgMKtOi_a:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a7179560150fa3ec1c49e8fc70c9b9785c31504/crates/papyrus_gateway/src/lib.rs#L122)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I meant only the line
"use gateway_metrics::MetricLogger;"
return the run_server function to the original location.
</blockquote></details>

Done.

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866#-:-N_my-RYBjLqDSUBbuAk:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866#-:-Na0RKEn67Xkfpa7bpqe:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/866#-:-Na0UlWK6iZDLhiBKw59:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
