### PR TITLE
return temp dir from test storage creation

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #766** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/766" target="_blank">Graphite</a>  👈
    * **PR #763** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/763" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/766?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/766#-NYqXsGGAW1GbmWJX-VJ:-NYqXsGGAW1GbmWJX-VK:b-62t59y) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b90515bf072a7a367696fbdb166b5a77c5d432d/crates/papyrus_storage/src/test_utils.rs#L25)):*
> ```XML
> };
> 
> pub fn get_test_config() -> (DbConfig, TempDir) {
> ```

Add comment explaining why do you return the tempdir. Something along the lines of
```
/// Returns a db config and the temporary directory that holds this db. The directory is returned to prolong the lifetime of this object and thus make sure the directory won't be destroyed
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/766#-NYqXsGGAW1GbmWJX-VJ:-NYwxXDe96eg-F2Evi8h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b90515bf072a7a367696fbdb166b5a77c5d432d/crates/papyrus_storage/src/test_utils.rs#L25)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add comment explaining why do you return the tempdir. Something along the lines of
```
/// Returns a db config and the temporary directory that holds this db. The directory is returned to prolong the lifetime of this object and thus make sure the directory won't be destroyed
```
</blockquote></details>

Done.

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/766#-NYwyBzf7Iap3I271ZyN:-NYwyBzf7Iap3I271ZyO:b-9z26rb) ([raw file](https://github.com/starkware-libs/papyrus/blob/265e0bcb61569e335c8cbfc3040a875febeba5db/crates/papyrus_storage/src/test_utils.rs#L26)):*
> ```XML
> 
> /// Returns a db config and the temporary directory that holds this db.
> /// The TempDir object is returned to as a handler for the lifetime of this object (the temp directory), thus make sure the directory won't be destroyed.
> ```

returned to as -> returned as
___
*[`crates/papyrus_storage/src/test_utils.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/766#-NYwyG4IBxfSXICeB7DD:-NYwyG4IBxfSXICeB7DE:b-nlci6f) ([raw file](https://github.com/starkware-libs/papyrus/blob/265e0bcb61569e335c8cbfc3040a875febeba5db/crates/papyrus_storage/src/test_utils.rs#L28)):*
> ```XML
> /// The TempDir object is returned to as a handler for the lifetime of this object (the temp directory), thus make sure the directory won't be destroyed.
> /// The caller should propagate the TempDir object until it is no longer needed.
> /// When the TempDir object is dropped, the directory is deleted.
> ```

Consider removing the last line, as it might be clear already from the previous line. I can see arguments for both ways so it's your call :)

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/766#-NYwyG4IBxfSXICeB7DD:-NZ-jCZRB1wz_qwVF4y5:bsztpab) ([raw file](https://github.com/starkware-libs/papyrus/blob/265e0bcb61569e335c8cbfc3040a875febeba5db/crates/papyrus_storage/src/test_utils.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider removing the last line, as it might be clear already from the previous line. I can see arguments for both ways so it's your call :) 
</blockquote></details>

agree but it doesn't heart to be extra

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/766#-:-NZ04hzw2icbQfV1Qvhi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
