### PR TITLE
Update config map with a map to strings.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?

- Updating a dumped config map by another source.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmJLsLAkFebk5pulIz):*
Allow updating config maps based on stringified parameter overrides.



_Code quote:_
```
- 5b0c36b: Update config map with a map to strings.
```
___
*[`crates/papyrus_config/src/config_test.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmInQr8FxAfiuj_2bM:-NYmInQr8FxAfiuj_2bN:b92zyvk) ([raw file](https://github.com/starkware-libs/papyrus/blob/5b0c36b39432bebe2a0de7d1116dc77b29bc86b5/crates/papyrus_config/src/config_test.rs#L132)):*
> ```XML
>     let updated_config_map = update_dumped_config(dumped_config, params_map).unwrap();
> 
>     assert_eq!(1234, updated_config_map.get("a").unwrap().value.as_u64().unwrap());
> ```

I think this is much easier to read. Since it's a test and we anyways are just using `unwrap` I think this is fine.



_Suggestion:_
```XML
    assert_eq!(json!(1234), updated_config_map["a"].value);
    assert_eq!(json!("/abc"), updated_config_map["b"].value);
    assert!(updated_config_map["c"].value.is_null());
```
___
*[`crates/papyrus_config/src/lib.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmH9Is5fLeZEMQXkwZ:-NYmH9Is5fLeZEMQXkw_:b8ewehr) ([raw file](https://github.com/starkware-libs/papyrus/blob/5b0c36b39432bebe2a0de7d1116dc77b29bc86b5/crates/papyrus_config/src/lib.rs#L80)):*
> ```XML
> 
> /// Replaces a JSON value with new data based on its type.
> fn replace_json(prev_value: &Value, raw_new_data: &str) -> Result<Value, SubConfigError> {
> ```

When I read the word "replace" it makes me think that this will be an in-place mutation `prev_value: &mut Value`. I can't think of a better function name, but wanted to mention this in case you did.

Based on the usage in `update_dumped_config` does it make sense to just do that? I'm fine either way.



_Code quote:_
```XML
fn replace_json(prev_value: &Value, raw_new_data: &str) -> Result<Value, SubConfigError> {
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @matan-starkware and @TzahiTaub)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmJLsLAkFebk5pulIz):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Allow updating config maps based on stringified parameter overrides.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/config_test.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmInQr8FxAfiuj_2bM:-NYqaKxj0Hal94sfYZEZ:b6mzl25) ([raw file](https://github.com/starkware-libs/papyrus/blob/5b0c36b39432bebe2a0de7d1116dc77b29bc86b5/crates/papyrus_config/src/config_test.rs#L132)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think this is much easier to read. Since it's a test and we anyways are just using `unwrap` I think this is fine.
</blockquote></details>

Nicer! Done.
___
*[`crates/papyrus_config/src/lib.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmH9Is5fLeZEMQXkwZ:-NYqbQeX0Bu8MDhuuU_A:b-lcnxc3) ([raw file](https://github.com/starkware-libs/papyrus/blob/5b0c36b39432bebe2a0de7d1116dc77b29bc86b5/crates/papyrus_config/src/lib.rs#L80)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

When I read the word "replace" it makes me think that this will be an in-place mutation `prev_value: &mut Value`. I can't think of a better function name, but wanted to mention this in case you did.

Based on the usage in `update_dumped_config` does it make sense to just do that? I'm fine either way.
</blockquote></details>

1. There is a difference between `update` and `replace`. I don't know what is the convention in Rust, but you can [find](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace) replacers that return a new object.

2. A mutable Value is not enough: I'm changing the enum type (Null => Number), in some cases. (What would be the returned type? `Option<SubConfigError>`?)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYmH9Is5fLeZEMQXkwZ:-NYqmDddER9NzRZHbbP2:bm17bzg) ([raw file](https://github.com/starkware-libs/papyrus/blob/5b0c36b39432bebe2a0de7d1116dc77b29bc86b5/crates/papyrus_config/src/lib.rs#L80)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

1. There is a difference between `update` and `replace`. I don't know what is the convention in Rust, but you can [find](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace) replacers that return a new object.

2. A mutable Value is not enough: I'm changing the enum type (Null => Number), in some cases. (What would be the returned type? `Option<SubConfigError>`?)
</blockquote></details>

Let's just leave it as is.

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 123 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYw-mhz-OhTil2pPq1k:-NYw-mhz-OhTil2pPq1l:b-9sfyu0) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/config_test.rs#L123)):*
> ```XML
>     let new_params_map = BTreeMap::from([("c".to_owned(), "true".to_owned())]);
>     let revert_config_map = update_dumped_config(updated_config_map, new_params_map);
>     assert!(revert_config_map.as_ref().unwrap().get("c").unwrap().value.as_bool().unwrap());
> ```

Consider more explicit code:
```
let new_value = ...;
update_map()
assert_eq!(updated_map[key], new_value)
```



_Code quote:_
```XML
assert!(revert_config_map.as_ref().unwrap().get("c").unwrap().value.as_bool().unwrap());
```
___
*[`crates/papyrus_config/src/lib.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxjJT-i-H9UEy_yeA:-NYvxjJT-i-H9UEy_yeB:bhd11qg) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L32)):*
> ```XML
>     ParseBoolError(#[from] ParseBoolError),
>     #[error("Insert a new param is not allowed.")]
>     NotExistParam,
> ```

ParamNotFound?



_Code quote:_
```XML
NotExistParam
```
___
*[`crates/papyrus_config/src/lib.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxwKS7NUj0Qvszbep:-NYvxwKS7NUj0Qvszbeq:b-r5gygw) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L34)):*
> ```XML
>     NotExistParam,
>     #[error("Unable to parsing {flag_type} flag type.")]
>     NotImplementedFlagType { flag_type: String },
> ```

Param instead of flag?



_Code quote:_
```XML
Flag
```
___
*[`crates/papyrus_config/src/lib.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyuFqD_qVahzKE8ZP:-NYvyuFqD_qVahzKE8ZQ:b-ge3vll) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L57)):*
> ```XML
>     }
> }
> ```

Consider moving the functionality of dumped config into a trait, implemented on BTreeMap.
I think it will be easier to read.
___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYvxGnV3HZuQ3NNVY7s:b84t831) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
> ```XML
> 
> /// Replaces a JSON value with new data based on its type.
> fn replace_json(prev_value: &Value, raw_new_data: &str) -> Result<Value, SubConfigError> {
> ```

Why do we need this function if the parameters are already flattened in the mapping? Can't we just replace the values?
___
*[`crates/papyrus_config/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyR9w78ZbMUMXRo3H:-NYvyR9w78ZbMUMXRo3I:ba5znl4) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L118)):*
> ```XML
> }
> 
> /// Updates a dumped configuration by a new raw data.
> ```

Suggestion: Returns a dumped configuration, updated with the new data.



_Code quote:_
```XML
/// Updates a dumped configuration by a new raw data.
```
___
*[`crates/papyrus_config/src/lib.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvznB9-0wuw1XKdyOq:-NYvznBAEj6fASi7zMjM:bp0bxxd) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L128)):*
> ```XML
>         } else {
>             return Err(SubConfigError::NotExistParam);
>         }
> ```

Use let-else: https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html



_Code quote:_
```XML
        if let Some(ser_param) = dumped_config.get_mut(&param_path) {
            ser_param.value = replace_json(&ser_param.value, &val)?;
        } else {
            return Err(SubConfigError::NotExistParam);
        }
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 123 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYw-mhz-OhTil2pPq1k:-NYw61yDAChJx9AVqI3j:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/config_test.rs#L123)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider more explicit code:
```
let new_value = ...;
update_map()
assert_eq!(updated_map[key], new_value)
```
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxjJT-i-H9UEy_yeA:-NYw8AG_63YA0IUoZFrP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L32)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

ParamNotFound?
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxwKS7NUj0Qvszbep:-NYw8X9SEyP3k0javX_-:b-83t1ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L34)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Param instead of flag?
</blockquote></details>

OK...
___
*[`crates/papyrus_config/src/lib.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyuFqD_qVahzKE8ZP:-NYwOEQt5QZ1FiLdkd-V:buvx2w7) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider moving the functionality of dumped config into a trait, implemented on BTreeMap.
I think it will be easier to read.
</blockquote></details>

Not in this PR.
WDYT about moving to a bin main?
___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYwMZpR8tz_mBKHK3St:bqhl1in) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this function if the parameters are already flattened in the mapping? Can't we just replace the values?
</blockquote></details>

The keys are flattened, but the values are held in JSON `Value`. I'm replacing this object.
___
*[`crates/papyrus_config/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyR9w78ZbMUMXRo3H:-NYwNyeq59sKZD5WcEmO:boj4v8f) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L118)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Suggestion: Returns a dumped configuration, updated with the new data.
</blockquote></details>

Almost done.
___
*[`crates/papyrus_config/src/lib.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvznB9-0wuw1XKdyOq:-NYw7KQj0R3d_XJ047il:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L128)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use let-else: https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html
</blockquote></details>

Done.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyuFqD_qVahzKE8ZP:-NYwXwL7-gB6x4L9vaNR:b-d4a0ot) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

By bin main you mean moving it out from the config module to the main module?
I think you will use this functionality in the config module, but maybe I'm not seeing correctly how the pieces will connect.
</blockquote></details>

I mean, adding a main function to the config module, for manually updating the default_config file.
This functionality will be a part of this main.
___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYwYorBBTPGvH5OoxgX:btyst7n) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't understand. Why is the new data a String and not SerializedParam?
</blockquote></details>

The data coming from the command line is flattened keys to string.
By this data we want to update a key to Value map.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvyuFqD_qVahzKE8ZP:-NYwa4Ci8o8QrkPP6auL:b-i7xpgc) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L57)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I mean, adding a main function to the config module, for manually updating the default_config file.
This functionality will be a part of this main.
</blockquote></details>

Oh ok..
Yeah you can do that.
___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYwaHUOCK-ZmqKFtylo:b-e07zk) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The data coming from the command line is flattened keys to string.
By this data we want to update a key to Value map.
</blockquote></details>

You can define the type of each parameter in the cmd when you prepare it

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYwdM5b82MK6ZQ2IaA7:b-8ev84j) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can define the type of each parameter in the cmd when you prepare it
</blockquote></details>

This is the current behavior, and we want to change it.
The goal is a general command function unaware of the actual params.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/769)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/769#-NYvxGnV3HZuQ3NNVY7r:-NYwsgDm-54xkyRnrQ0m:b7fgm59) ([raw file](https://github.com/starkware-libs/papyrus/blob/1c7c7215666f39f5cda7da871dba0a2e2f537313/crates/papyrus_config/src/lib.rs#L91)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This is the current behavior, and we want to change it.
The goal is a general command function unaware of the actual params.
</blockquote></details>

But you can prepare it dynamically using the default config, no need to do it manually

**Pull request closed without merging**
