### PR TITLE
refactor(consensus): the SHC goes from a task to an object which is called directly

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2079?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2079** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2079?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2078** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2078?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2077** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2077?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2069** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2069?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2064** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2064?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2059** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2059?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2058** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2058?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-NzxTe0h1-ZGCFFmxoKx:-NzxTe0h1-ZGCFFmxoKy:bb8g3q4) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/Cargo.toml#L17)):*
> ```TOML
> tokio = { workspace = true, features = ["full"] }
> papyrus_protobuf = { path = "../../papyrus_protobuf", version = "0.4.0-dev.2" }
> papyrus_network = { path = "../../papyrus_network", version = "0.4.0-dev.2" }
> ```

order alphabetically



_Code quote:_
```TOML
papyrus_protobuf = { path = "../../papyrus_protobuf", version = "0.4.0-dev.2" }
papyrus_network = { path = "../../papyrus_network", version = "0.4.0-dev.2" }
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0HPlsE1yzgHwhnTZp:-O-0HPlsE1yzgHwhnTZq:bqzb488) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L86)):*
> ```XML
>             } else {
>                 "invalid proposer"
>             });
> ```

1. consider separating this into two if statements for each error.
2. consider adding the values which not equal to the error message



_Code quote:_
```XML
            let msg = String::from(if init.height != self.height {
                "invalid height"
            } else {
                "invalid proposer"
            });
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KWMS46LMNKWZsu1b:-O-0KWMS46LMNKWZsu1c:b-t6dsf7) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L32)):*
> ```XML
>     let node_id: ValidatorId = 1_u32.into();
>     let block =
>         TestBlock { content: vec![1, 2, 3], id: BlockHash(Felt::try_from(1 as u128).unwrap()) };
> ```

consider Felt::ONE



_Code quote:_
```XML
Felt::try_from(1 as u128).unwrap()
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KmGL6a2ksDz0lrV0:-O-0KmGL6a2ksDz0lrV1:b-2y506o) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L48)):*
> ```XML
>         // 2. If we don't spawn (instead using `block_on` to send), then the channel size must be
>         //    large enough for all content. Now we don't have to consider the size.
>         let _ = tokio::spawn(async move {
> ```

Why do you need this?



_Code quote:_
```XML
let _ = 
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KGsM5feROBocAZFc:-O-0KGsM5feROBocAZFd:b-t6dsf7) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L83)):*
> ```XML
>     let proposer: ValidatorId = 2_u32.into();
>     let block =
>         TestBlock { content: vec![1, 2, 3], id: BlockHash(Felt::try_from(1 as u128).unwrap()) };
> ```

consider Felt::ONE



_Code quote:_
```XML
Felt::try_from(1 as u128).unwrap()
```
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0LTjI4DnByNTcnhml:-O-0LTjI4DnByNTcnhmm:b-bcyf6z) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/test_utils.rs#L48)):*
> ```XML
> 
> #[async_trait]
> impl NetworkSender for TestNetworkSender {
> ```

Why not use a mock of the trait?
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0JDOc-6n6Z6ZUc9xb:-O-0JDOc-6n6Z6ZUc9xc:b-ysfyss) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/test_utils.rs#L55)):*
> ```XML
>         init: ProposalInit,
>         content_receiver: mpsc::Receiver<Self::ProposalChunk>,
>         fin_receiver: oneshot::Receiver<BlockHash>,
> ```

Why implement this with logic? Doesn't empty impl will be fine?

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0HPlsE1yzgHwhnTZp:-O-0f-fa2m8ERk4XDiu0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L86)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. consider separating this into two if statements for each error.
2. consider adding the values which not equal to the error message
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KWMS46LMNKWZsu1b:-O-0fEAC4_l9CCwtK-UA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L32)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider Felt::ONE
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KmGL6a2ksDz0lrV0:-O-0tFEg7mcVyUWju5k1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0KGsM5feROBocAZFc:-O-0fOrz9hH4HL6LgRWr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L83)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider Felt::ONE
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0LTjI4DnByNTcnhml:-O-0fRto1oznxayVHEFA:bos2vo4) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/test_utils.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why not use a mock of the trait?
</blockquote></details>

Good call. The main downside is that I need to make sure to await this explicitly in the test (joinset)
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-0JDOc-6n6Z6ZUc9xb:-O-0tST9DIGGD1Msu0Ei:b-butofj) ([raw file](https://github.com/starkware-libs/papyrus/blob/b48acde106de9cb70be02384a461be4046a2f087/crates/sequencing/papyrus_consensus/src/test_utils.rs#L55)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why implement this with logic? Doesn't empty impl will be fine?
</blockquote></details>

moved to mock.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-18Gkc3wFACjsV8Glq:-O-18Gkc3wFACjsV8Glr:bnct1cu) (no related file):*
consider change propose() to send_propose()

___
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 82 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-19-J608goTWNRGesK:-O-19-J608goTWNRGesL:b-akur8x) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L82)):*
> ```XML
>         let proposer_id = self.context.proposer(&self.validators, self.height);
>         if init.height != self.height {
>             let msg = format!("invalid height: expected {}, got {}", self.height, init.height);
> ```

here use debug



_Code quote:_
```XML
ed {}, got {}", 
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-18U0EB5z5DYUXEEwP:-O-18U0EB5z5DYUXEEwQ:brrxjqg) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L14)):*
> ```XML
> 
> #[tokio::test]
> async fn propose() {
> ```

Change to start



_Code quote:_
```XML
propose
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-1CBWiATuVuIHWMhG7:-O-1CBWj9BXKpP9pRxwZ:b26uw0b) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L38)):*
> ```XML
> 
>     let block_id = block.id();
>     let joinset_clone = Arc::clone(&joinset);
> ```

why even care about the propose logic?
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-172nf4zXAF3eUnicx:-O-172nf4zXAF3eUnicy:b-h5oe7f) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L67)):*
> ```XML
> 
> #[tokio::test]
> async fn validate() {
> ```

We should decide. `validate` or `handle proposal`



_Code quote:_
```XML
validat
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-16zdWBPcgdElvQa0j:-O-16zdWBPcgdElvQa0k:bvtpy32) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L108)):*
> ```XML
>         .unwrap();
> 
>     // This calls to `context.proposer` and `context.build_proposal`.
> ```

delete this



_Code quote:_
```XML
// This calls to `context.proposer` and `context.build_proposal`.
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-156Hn01nXp6HTqa4V:-O-156Hn01nXp6HTqa4W:bw1iii1) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/types.rs#L8)):*
> ```XML
> use futures::channel::{mpsc, oneshot};
> #[cfg(test)]
> use mockall::automock;
> ```

consider use the full path in the in the cfg_attr instead of this



_Code quote:_
```XML
#[cfg(test)]
use mockall::automock;
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-18Gkc3wFACjsV8Glq:-O-1M16z8v5DeDaJmNt0:bek5p56) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider change propose() to send_propose()
</blockquote></details>

If you mean the test I renamed (see below). If you mean the `NetworkSender`, I feel like it's already in the context of a trait called "sender".

___
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 82 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-19-J608goTWNRGesK:-O-1L0gMB4P1_9pu7a5-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L82)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

here use debug
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-18U0EB5z5DYUXEEwP:-O-1L6CIEEBroT88NEqO:b-yn6q4q) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Change to start
</blockquote></details>

I renamed to proposer & validator. That's the difference I care about, not just the name of the function that we call to.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-1CBWiATuVuIHWMhG7:-O-1LZ9Y4gx6TFT-GFcZ:b-gbwsot) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L38)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why even care about the propose logic?
</blockquote></details>

discussed f2f, I care about the init and the fin from consensus, just not the content. Tried to simplify a bit.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-172nf4zXAF3eUnicx:-O-1LfaX4YEXOjLgUqAu:b-spwuvt) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L67)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

We should decide. `validate` or `handle proposal`
</blockquote></details>

Changed it to `validator` as it's the role of being a validator I was thinking about. 
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-16zdWBPcgdElvQa0j:-O-1Lpev0HtKFNzVFnQY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L108)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

delete this
</blockquote></details>

Done.

**Review by DvirYo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-:-O-1gLpy3klq91-zK0BD:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-O-16zdWBPcgdElvQa0j:-O-1g0KZ9_UBPlcL5SBw:b-9qg1u4) ([raw file](https://github.com/starkware-libs/papyrus/blob/10aebf2d1f1b8457ffab2293890021f51cfc6b64/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L108)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079)* status: 7 of 8 files reviewed, all discussions resolved

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2079#-:-O-FRqYt7H78oFCanlwH:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved

**Pull request merged**
