### PR TITLE
refactor(network): register_sqmr_subscriber receives one protocol and is generic on response type

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(protobuf): add one struct for all sync responses types
- feat(network): add conversion from Vec<u8> to DataOrFin<ThinStateDiff>
- refactor(network): register_sqmr_subscriber receives one protocol and is generic on response type

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)* status: all files reviewed, 9 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRkc665XbhknDHFuXO:-NzRkc665XbhknDHFuXP:b-aws78c) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/lib.rs#L79)):*
> ```XML
> /// This is a part of the exposed API of the network manager.
> /// This is meant to represent the different underlying p2p protocols the network manager supports.
> // TODO(shahak): Change protocol to a wrapper of string.
> ```

This would basically mirror topic from broadcast?



_Code quote:_
```XML
// TODO(shahak): Change protocol to a wrapper of string.
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRm6bLDY3O1LIQ9ciE:-NzRm6bLDY3O1LIQ9ciF:b8wt5gt) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L133)):*
> ```XML
>             Protocol::SignedBlockHeader => |x| ready(Ok(Bytes::from(HeaderQuery(x)))),
>             Protocol::StateDiff => |x| ready(Ok(Bytes::from(StateDiffQuery(x)))),
>         };
> ```

Are we planning to remove this, so SQMR becomes protocol agnostic?



_Code quote:_
```XML
        let query_fn: fn(Query) -> Ready<Result<Bytes, SendError>> = match protocol {
            Protocol::SignedBlockHeader => |x| ready(Ok(Bytes::from(HeaderQuery(x)))),
            Protocol::StateDiff => |x| ready(Ok(Bytes::from(StateDiffQuery(x)))),
        };
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRoeW522bOwal4yE5t:-NzRoeW522bOwal4yE5u:b-unjbmm) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L137)):*
> ```XML
> 
>         let response_fn: ReceivedMessagesConverterFn<Response> =
>             |(x, report_callback)| (Response::try_from(x), report_callback);
> ```

Is there a future where the networking stack automatically handles this error and calls to callback? So the receiver no longer receives an Result type, but just the type they actually want?



_Code quote:_
```XML
        let response_fn: ReceivedMessagesConverterFn<Response> =
            |(x, report_callback)| (Response::try_from(x), report_callback);
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRqVuq0yJmq2B7Lmlx:-NzRqVuq0yJmq2B7Lmly:b-y5sdar) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L357)):*
> ```XML
>                                 "Receiver buffer is full. Dropping data. outbound_session_id: \
>                                  {outbound_session_id:?}"
>                             );
> ```

Do we want something like a prometheus metric so we can monitor these kinds of events? (I guess this a general papyrus question, not specific to here)



_Code quote:_
```XML
                            error!(
                                "Receiver buffer is full. Dropping data. outbound_session_id: \
                                 {outbound_session_id:?}"
                            );
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRqtCO7s-0iz4RJyC5:-NzRqtCO7s-0iz4RJyC6:b-or6rcu) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L439)):*
> ```XML
> 
>     fn handle_sqmr_received_query(&mut self, protocol: Protocol, query: Bytes) {
>         match self.swarm.send_query(query, PeerId::random(), protocol) {
> ```

So this means that the network stack received a query from a subscriber within the node, not a peer node?

It's hard to name since we are receiving a query either way. Maybe:
- send_sqmr_query_to_peer
- handle_local_sqmr_query
- handle_sqmr_query_from_subscriber
?



_Code quote:_
```XML
    fn handle_sqmr_received_query(&mut self, protocol: Protocol, query: Bytes) {
        match self.swarm.send_query(query, PeerId::random(), protocol) {
```
___
*[`crates/papyrus_p2p_sync/src/header.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS1DAqD1wSVYDTZd5K:-NzS1DAqD1wSVYDTZd5L:b71xnl5) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header.rs#L45)):*
> ```XML
> > DataStreamFactory<QuerySender, DataReceiver, SignedBlockHeader>
>     for HeaderStreamFactory<QuerySender, DataReceiver>
> {
> ```

Switch to a where clause for the trait bounds.
Other option, we seem to be repeating these long trait bounds in many places. Maybe just define a new trait bound which implies all of them?
- QuerySender<QueryT>
- ResponseReceiver<ResponseT>



_Code quote:_
```XML
impl<
    QuerySender: Sink<Query, Error = SendError> + Unpin + Send + 'static,
    DataReceiver: Stream<Item = Response<SignedBlockHeader>> + Unpin + Send + 'static,
> DataStreamFactory<QuerySender, DataReceiver, SignedBlockHeader>
    for HeaderStreamFactory<QuerySender, DataReceiver>
{
```
___
*[`crates/papyrus_p2p_sync/src/header.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS1e5y-jDjJogQoe-T:-NzS1e5y-jDjJogQoe-U:bsz9qsa) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header.rs#L58)):*
> ```XML
>         async move {
>             let maybe_signed_header_stream_result =
>                 tokio::time::timeout(NETWORK_DATA_TIMEOUT, signed_headers_receiver.next()).await?;
> ```

What about adding the question mark here on next instead of below?



_Suggestion:_
```XML
            let maybe_signed_header_stream_result =
                tokio::time::timeout(NETWORK_DATA_TIMEOUT, signed_headers_receiver.next()?).await?;
```
___
*[`crates/papyrus_p2p_sync/src/header_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS2IIL7pBHg0wX9laC:-NzS2IIL7pBHg0wX9laD:b6j5lfj) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header_test.rs#L88)):*
> ```XML
>                 assert_eq!(*block_signature, actual_block_signature);
>             }
>             headers_sender.send((Ok(DataOrFin(None)), Box::new(|| {}))).await.unwrap();
> ```

I have nothing concrete to offer, but I wanted to point out that we are adding a lot of wrapping to what before was just a simple `None`. It may well be worth it, but just want to make sure we are thinking of this as a cost that we considered.



_Code quote:_
```XML
Ok(DataOrFin(None))
```
___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS7hBb82t4g_Jhff8w:-NzS7hBb82t4g_Jhff8x:b-vzflq6) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/stream_factory.rs#L36)):*
> ```XML
>     DataReceiver: Stream<Item = Response<InputFromNetwork>> + Unpin + Send + 'static,
>     InputFromNetwork: Send + 'static,
>     DataOrFin<InputFromNetwork>: TryFrom<Vec<u8>>,
> ```

Does this require a special implementation, or is this implemented on DataOrFin for any inner type which implements this?



_Code quote:_
```XML
    DataOrFin<InputFromNetwork>: TryFrom<Vec<u8>>,
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)* status: all files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRkc665XbhknDHFuXO:-NzSFHMdDHdskC6gXqIM:b2nhswy) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/lib.rs#L79)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This would basically mirror topic from broadcast?
</blockquote></details>

Yes
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRm6bLDY3O1LIQ9ciE:-NzSFL-T1-MPDK8Q0k_b:b-5ahjty) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L133)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are we planning to remove this, so SQMR becomes protocol agnostic?
</blockquote></details>

Yes. Added TODO
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRoeW522bOwal4yE5t:-NzSH3Zj91eb8rqetqWV:b-ipgguo) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L137)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is there a future where the networking stack automatically handles this error and calls to callback? So the receiver no longer receives an Result type, but just the type they actually want?
</blockquote></details>

I don't see a straight-forward way to implement this. Also, the sync might find it useful to know that an error has occurred
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRqVuq0yJmq2B7Lmlx:-NzSHMX-8RTyEdUxUQkV:b-lg0w5n) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L357)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Do we want something like a prometheus metric so we can monitor these kinds of events? (I guess this a general papyrus question, not specific to here)
</blockquote></details>

I'm not sure that this is the correct way to handle this. We'll need to decide in the future
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzRqtCO7s-0iz4RJyC5:-NzSHbzB3H6-E8vGLwEc:bj3yc46) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_network/src/network_manager/mod.rs#L439)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

So this means that the network stack received a query from a subscriber within the node, not a peer node?

It's hard to name since we are receiving a query either way. Maybe:
- send_sqmr_query_to_peer
- handle_local_sqmr_query
- handle_sqmr_query_from_subscriber
?
</blockquote></details>

Nice. Done
___
*[`crates/papyrus_p2p_sync/src/header.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS1DAqD1wSVYDTZd5K:-NzSHmmw7-usrc3V0m8q:b-buonud) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header.rs#L45)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Switch to a where clause for the trait bounds.
Other option, we seem to be repeating these long trait bounds in many places. Maybe just define a new trait bound which implies all of them?
- QuerySender<QueryT>
- ResponseReceiver<ResponseT>
</blockquote></details>

trait aliases are an experimental feature in rust
___
*[`crates/papyrus_p2p_sync/src/header.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS1e5y-jDjJogQoe-T:-NzSIU7QBS1C_6nvGDPm:b9pjhpd) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header.rs#L58)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What about adding the question mark here on next instead of below?
</blockquote></details>

It's a tuple of two elements which only one of them is result, but I think I can prettify it anyway. WDYT?
___
*[`crates/papyrus_p2p_sync/src/header_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS2IIL7pBHg0wX9laC:-NzSL6jxECPwZnoPF_mK:b-70iy5h) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header_test.rs#L88)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I have nothing concrete to offer, but I wanted to point out that we are adding a lot of wrapping to what before was just a simple `None`. It may well be worth it, but just want to make sure we are thinking of this as a cost that we considered.
</blockquote></details>

I think it's ok
___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS7hBb82t4g_Jhff8w:-NzSLCln8J9TcjvorkIL:bg686k) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/stream_factory.rs#L36)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Does this require a special implementation, or is this implemented on DataOrFin for any inner type which implements this?
</blockquote></details>

Requires a special implementation. This was done in #2070, #2071

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/header.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS1e5y-jDjJogQoe-T:-NzTLw0b8ZOfQZ7KOI5K:b-9mfpjr) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/header.rs#L58)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's a tuple of two elements which only one of them is result, but I think I can prettify it anyway. WDYT?
</blockquote></details>

Oh missed that. Honestly either one is fine with me.
___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS7hBb82t4g_Jhff8w:-NzTM9Ki-nEUAbCqi1o0:bq1efhd) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/stream_factory.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Requires a special implementation. This was done in #2070, #2071
</blockquote></details>

Can we change the bound to `InputFromNetwork: TryFrom<Vec<u8>>` if we did? I guess we'd also change the `auto_impl_try_from_vec_u8!` to be for inner type as well.

```
struct DataOrFin<T>(Option<T>);

impl<T> TryFrom<Vec<u8>> for DataOrFin<T>
where
    T: TryFrom<Vec<u8>>,
{
    type Error = <T as TryFrom<Vec<u8>>>::Error;

    fn try_from(bytes: Vec<u8>) -> Result<Self, Self::Error> {
        let inner = T::try_from(bytes)?;
        Ok(Self(Some(inner)))
    }
}
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2073#-NzS7hBb82t4g_Jhff8w:-NzWStbf-NtJ2Kr66dKw:b-9lc7zk) ([raw file](https://github.com/starkware-libs/papyrus/blob/e0a5763993bd73477c34dfbf7d2d7037c67b8799/crates/papyrus_p2p_sync/src/stream_factory.rs#L36)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can we change the bound to `InputFromNetwork: TryFrom<Vec<u8>>` if we did? I guess we'd also change the `auto_impl_try_from_vec_u8!` to be for inner type as well.

```
struct DataOrFin<T>(Option<T>);

impl<T> TryFrom<Vec<u8>> for DataOrFin<T>
where
    T: TryFrom<Vec<u8>>,
{
    type Error = <T as TryFrom<Vec<u8>>>::Error;

    fn try_from(bytes: Vec<u8>) -> Result<Self, Self::Error> {
        let inner = T::try_from(bytes)?;
        Ok(Self(Some(inner)))
    }
}
```
</blockquote></details>

There's a difference between converting a T to converting an Option<T>. It's a different protobuf message

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2073)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Pull request merged**
