### PR TITLE
Add constant gateway requests to the load test.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/518)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/518)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/518#-NPDQhef5KI7nzw1MCSk:-NPDQhegCzam-3vepN27:bbymx74) (no related file):*
Those requests don't have any parameters, so I treated them differently.
another way to do that is to write a macro (just for those three functions)
another way is to use the regular "create_get_transaction_function_with_requests_from_file" macro but with a file with just one line

___

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/518#-NPOSOAC1dIvAtfxNS83:-NPOSOAD6QZ2gOyxPZG3:b-krycsi) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6ee67316d9ade3dd91c786ff8255700fa35e1b/crates/papyrus_load_test/src/transactions.rs#L44)):*
> ```XML
> }
> 
> pub async fn name(user: &mut GooseUser) -> TransactionResult {
> ```

What is the purpose of this function?



_Code quote:_
```XML
pub async fn name(user: &mut GooseUser)
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/518)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/518)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/transactions.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/518#-NPOSOAC1dIvAtfxNS83:-NPRCbaz6YIDk5hQ-3QX:b-7h9ta1) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6ee67316d9ade3dd91c786ff8255700fa35e1b/crates/papyrus_load_test/src/transactions.rs#L44)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What is the purpose of this function?
</blockquote></details>

it is a mistake. i will delete this.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/518#-:-NPSI92n2uCq8NfEkVY3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
