### PR TITLE
feat(storage): collect additional db metrics

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCs8fT25NrPht2-JcG:-NoCs8fT25NrPht2-JcH:b-3hbsi9) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/lib.rs#L136)):*
> ```XML
> // TODO(dvir): add this to config.
> // Duration between updates to the storage metrics (those in the collect_storage_metrics function).
> const STORAGE_METRICS_UPDATE_INTERVAL: Duration = Duration::from_secs(10);
> ```

Note that we support durations in the config (see sync config)



_Code quote:_
```XML
// TODO(dvir): add this to config.
// Duration between updates to the storage metrics (those in the collect_storage_metrics function).
const STORAGE_METRICS_UPDATE_INTERVAL: Duration = Duration::from_secs(10);
```
___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoCosfG9HnxnO6Sa-kN:bbus16g) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
> ```XML
> pub(crate) fn collect_storage_metrics(reader: DbReader, update_interval_time: Duration) {
>     let mut interval = tokio::time::interval(update_interval_time);
>     tokio::spawn(async move {
> ```

I think the task handle should be returned from the function, perhaps kept as a member of the writer or something.
Otherwise, what happens if the storage handles are dropped or if the code here panics?
___
*[`crates/papyrus_storage/src/utils.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCqcik61P-YMP4zk42:-NoCqcik61P-YMP4zk43:bphicyy) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L105)):*
> ```XML
>             if let Ok(info) = info {
>                 absolute_counter!("storage_last_page_number", info.last_pgno() as u64);
>                 absolute_counter!("storage_last_transaction_index", info.last_txnid() as u64);
> ```

Is it possible to separate RO/RW txns?



_Code quote:_
```XML
last_txnid(
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCs8fT25NrPht2-JcG:-NoD0FfOB0nTo0YQKfQi:bktib4q) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/lib.rs#L136)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note that we support durations in the config (see sync config)
</blockquote></details>

I didn't add this to the config in this PR because some interface questions should be decided.
1. What behavior should be if the node is configured not to collect metrics but the value here is valid? Not collecting metrics at all is a bit weird.
2. If the node collects metrics and I don't want those metrics to be collected, what value should I use? Should this config value be optional?
These questions can be answered easily, but they should be agreed upon.
A question I am not 100% sure about is if we should use async code at all in the storage crate.
___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoD5R2z3eqtQt-3iuxp:b-myqoob) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the task handle should be returned from the function, perhaps kept as a member of the writer or something.
Otherwise, what happens if the storage handles are dropped or if the code here panics?
</blockquote></details>

I don't understand. What do you think we should do with the handle?
What are "storage handles"?
This is a minimalistic code that shouldn't panic. If it panics, the task will be stopped, but Tokio will catch it, and the node will not collapse. The worst case here is that the metrics will stop being collected.
I can spawn the metric collection task outside the open_storage function, but I think collecting metrics about the storage should be part of the storage itself.
I changed the function to return the handle, but the code still doesn't use this handle.
___
*[`crates/papyrus_storage/src/utils.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCqcik61P-YMP4zk42:-NoD4t8nDr2YF803OH0s:bfk2o5y) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L105)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is it possible to separate RO/RW txns?
</blockquote></details>

No. This is all that the binding enables.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoG-vzKB7N3EBHeYSuC:b-nikfcy) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don't understand. What do you think we should do with the handle?
What are "storage handles"?
This is a minimalistic code that shouldn't panic. If it panics, the task will be stopped, but Tokio will catch it, and the node will not collapse. The worst case here is that the metrics will stop being collected.
I can spawn the metric collection task outside the open_storage function, but I think collecting metrics about the storage should be part of the storage itself.
I changed the function to return the handle, but the code still doesn't use this handle.
</blockquote></details>

By storage handles I meant the reader and the writer - the monitoring task might outlive them, this is why I suggest keeping the task handle as a member of the writer. This way you can abort the handle in the drop of the writer - WDYT?

Note that the node is not the only user of the storage, and we want to collect metrics also from the Blockifier storage.
___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoGCBvj4-snX3fdDyD4:-NoGCBvj4-snX3fdDyD5:b-ap64nm) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L99)):*
> ```XML
>     let mut interval = tokio::time::interval(update_interval_time);
>     tokio::spawn(async move {
>         loop {
> ```

Consider creating a span outside the loop.



_Code quote:_
```XML
loop {
```
___
*[`crates/papyrus_storage/src/utils.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoG1G_Z6ZrrbGW0A6EQ:-NoG1G_Z6ZrrbGW0A6ER:b-rqy0az) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L101)):*
> ```XML
>         loop {
>             if let Ok(freelist_size) = reader.get_free_pages() {
>                 gauge!("storage_free_pages_number", freelist_size as f64);
> ```

Lior advised us not to use `as` because it trims the number instead of panic/error (not that I predict it will happen here...)



_Code quote:_
```XML
 as f64
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoH-AgM2J7uU0AwepGl:b-cxcrjx) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

By storage handles I meant the reader and the writer - the monitoring task might outlive them, this is why I suggest keeping the task handle as a member of the writer. This way you can abort the handle in the drop of the writer - WDYT?

Note that the node is not the only user of the storage, and we want to collect metrics also from the Blockifier storage.
</blockquote></details>

Now I understand you.
I agree this is a problem. It will come into effect only when the process will drop the reader and the writer but will not exit; in this case, the environment still be open, and metrics continue to be collected. This is not the case in papyrus or the blockifier as far as I understand.
This task should be aborted only if both the reader and the writer are dropped, so following the handle only in the writer does not completely solve the problem (although we can say that we collect metrics if the database can be changed but this way, we lose information in some cases).
Another option is when the only reference to the environment is from this task abort it and drop the environment. WDYT? This is a bit weird flow...
___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoGCBvj4-snX3fdDyD4:-NoH--GUAz4RtOCNnHzY:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider creating a span outside the loop.
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/utils.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoG1G_Z6ZrrbGW0A6EQ:-NoGzcVKCaUC7tBcy945:bsa4ejw) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L101)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Lior advised us not to use `as` because it trims the number instead of panic/error (not that I predict it will happen here...)
</blockquote></details>

As you said, this is not the problem here; this number can't be too large, and a little miss precision is not something that I am worried about.
Do we have a crate or tool we should use for those types of conversations?
___
*[`crates/papyrus_storage/src/utils.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoH4-d93AgDCajdXO9V:-NoH4-d93AgDCajdXO9W:bkkxoui) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L110)):*
> ```XML
>                 absolute_counter!("storage_last_page_number", info.last_pgno() as u64);
>                 absolute_counter!("storage_last_transaction_index", info.last_txnid() as u64);
>                 gauge!("storage_num_readers", info.num_readers() as f64);
> ```

This was deleted on purpose.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCs8fT25NrPht2-JcG:-NoGYEfL-QT49Unh34At:b-m4mx8t) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/lib.rs#L136)):*
> A question I am not 100% sure about is if we should use async code at all in the storage crate.
Good question
___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoHCqbn5vuF51qOwXeT:boc1187) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Now I understand you.
I agree this is a problem. It will come into effect only when the process will drop the reader and the writer but will not exit; in this case, the environment still be open, and metrics continue to be collected. This is not the case in papyrus or the blockifier as far as I understand.
This task should be aborted only if both the reader and the writer are dropped, so following the handle only in the writer does not completely solve the problem (although we can say that we collect metrics if the database can be changed but this way, we lose information in some cases).
Another option is when the only reference to the environment is from this task abort it and drop the environment. WDYT? This is a bit weird flow...
</blockquote></details>

Maybe the task can hold a weak reference to both the reader and the writer, and in the loop if both are None you can kill the task
___
*[`crates/papyrus_storage/src/utils.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoG1G_Z6ZrrbGW0A6EQ:-NoHEE8zBviqLSnS7Ynk:b-yktqsr) ([raw file](https://github.com/starkware-libs/papyrus/blob/7aca563bcee7a223857f0e6aa6180eee41165d98/crates/papyrus_storage/src/utils.rs#L101)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

As you said, this is not the problem here; this number can't be too large, and a little miss precision is not something that I am worried about.
Do we have a crate or tool we should use for those types of conversations?
</blockquote></details>

No, he just talked about it, and it reminded me of this 
___
*[`crates/papyrus_storage/src/utils.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoHGQi_66d-IxqEWqTu:-NoHGQi_66d-IxqEWqTv:blbb7ov) ([raw file](https://github.com/starkware-libs/papyrus/blob/121f6d509907638d80caa560bedfaef98105b545/crates/papyrus_storage/src/utils.rs#L111)):*
> ```XML
>                 let info = reader.get_db_info();
>                 if let Ok(info) = info {
>                     absolute_counter!("storage_last_page_number", info.last_pgno() as u64);
> ```

What about more statistics? for example n_entries, size, depth
Also, per table statistics?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCs8fT25NrPht2-JcG:-NoMsnFZBUbAA4aERG42:b-gf6e0d) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/lib.rs#L136)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

> A question I am not 100% sure about is if we should use async code at all in the storage crate.
Good question
</blockquote></details>

This question is irrelevant in the new implementation.
___
*[`crates/papyrus_storage/src/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoCosfF8NxBhHoKWQDP:-NoMstADEXmIytdPX5PP:bgd2mwd) ([raw file](https://github.com/starkware-libs/papyrus/blob/51cd840fc6f0f94f041480c8564ace451e400db7/crates/papyrus_storage/src/utils.rs#L94)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Maybe the task can hold a weak reference to both the reader and the writer, and in the loop if both are None you can kill the task
</blockquote></details>

Irrelevant now.
___
*[`crates/papyrus_storage/src/utils.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoHGQi_66d-IxqEWqTu:-NoMsyEG8-iQ_laWxc6U:b-jllu14) ([raw file](https://github.com/starkware-libs/papyrus/blob/121f6d509907638d80caa560bedfaef98105b545/crates/papyrus_storage/src/utils.rs#L111)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What about more statistics? for example n_entries, size, depth
Also, per table statistics?
</blockquote></details>

I don't think those metrics are very interesting to follow continually. This kind of information is available by the dbTablesStats endpoint in the monitoring.
The two last metrics are also not very important, but one of the missions of this PR is to add infrastructure for adding more metrics in the future. For example, the metrics you describe can be added fast and easily after this PR.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQjghu8sTJEDdfDQsU:-NoQjghvC9DQJpL2hIre:b-u76y8m) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e48b860f89b83aca227a75dde5d72672b2994b/crates/papyrus_storage/src/utils.rs#L99)):*
> ```XML
> /// NOTICE: This task will run forever and keep the storage environment open, unless cancelled by
> /// using the returned handle.
> /// NOTICE: this spawn a tokio task so it should be called from a tokio runtime.
> ```

Consider extracting the task creation code to the main and the util function will be just an iteration of collecting metrics (this way we can collect the metrics also from blockifier)



_Code quote:_
```XML
/// NOTICE: This task will run forever and keep the storage environment open, unless cancelled by
/// using the returned handle.
/// NOTICE: this spawn a tokio task so it should be called from a tokio runtime.
```
___
*[`crates/papyrus_storage/src/utils_test.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQkq5iEfCEK9ohxKgq:-NoQkq5iEfCEK9ohxKgr:b-oqdkct) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e48b860f89b83aca227a75dde5d72672b2994b/crates/papyrus_storage/src/utils_test.rs#L107)):*
> ```XML
>         panic!("storage_last_transaction_index is not a Counter")
>     };
>     assert!(0f64 < last_transaction);
> ```

Shouldn't this be a fixed number?



_Code quote:_
```XML
assert!(0f64 < last_transaction);
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQjghu8sTJEDdfDQsU:-NoR6jb70tcyw15SSW6a:bv1i804) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e48b860f89b83aca227a75dde5d72672b2994b/crates/papyrus_storage/src/utils.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider extracting the task creation code to the main and the util function will be just an iteration of collecting metrics (this way we can collect the metrics also from blockifier)
</blockquote></details>

I decided not to do so because this is a bit weird API, and for using this in the blockifier, we probably will need to make this not async code, so this will not help the blockifier and make the API weird.
___
*[`crates/papyrus_storage/src/utils_test.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQkq5iEfCEK9ohxKgq:-NoR6Fep8S3mgPUWBcOZ:b69dui9) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e48b860f89b83aca227a75dde5d72672b2994b/crates/papyrus_storage/src/utils_test.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't this be a fixed number?
</blockquote></details>

All the values in this test are fixed; the test is only a sanity check.
In addition, making this fixed value will require updating this any time we change the environment creation.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQjghu8sTJEDdfDQsU:-NoRfC-v7x0oWyNVfWv5:b-gxgn38) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a190efae22ff5fc7ff808b7bfe4cd275be241e1/crates/papyrus_storage/src/utils.rs#L99)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I decided not to do so because this is a bit weird API, and for using this in the blockifier, we probably will need to make this not async code, so this will not help the blockifier and make the API weird.
</blockquote></details>

But now you added tokio to the storage crate which seems wrong.
Why does making this not async won't help the blockifier? They will be able to call it from the python code.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NoQjghu8sTJEDdfDQsU:-Nof5WXl7BxVLAsWTds6:bbw455) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a190efae22ff5fc7ff808b7bfe4cd275be241e1/crates/papyrus_storage/src/utils.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

But now you added tokio to the storage crate which seems wrong.
Why does making this not async won't help the blockifier? They will be able to call it from the python code.
</blockquote></details>

The problem with using async code in the storage was that the storage functionality completlly can be run from not async runtime. When the spawning of the task was part of the opening of the db it could fail the opening if not run from async runtime.
Now when spawning this task is completely separate from the storage functionality, this is not a problem.
About the second point, the loop itself requires sleep, which, if we don't use async runtime should be different than tokio sleep. So for the blockier can use this, it requires to change also the loop itself, and in that case, it will be easier for all sides to create non async version of the collect_storage_metrics function (probably the metrics update will be extracted to a new private function).

**Review by yair-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 12 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-:-NofdOsSCOFaS11apSGy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/utils_test.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NofcuGp91EUqj1KTg2R:-NofcuGp91EUqj1KTg2S:b-rtagwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/e446ee149fd6d655722b44aa8f4632e3e321e374/crates/papyrus_storage/src/utils_test.rs#L15)):*
> ```XML
> 
> use super::update_storage_metrics;
> // use super::dump_table_to_file;
> ```

delete



_Code quote:_
```XML
// use super::dump_table_to_file;
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/utils_test.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-NofcuGp91EUqj1KTg2R:-NoffffH4h8-R2XW08a2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e446ee149fd6d655722b44aa8f4632e3e321e374/crates/papyrus_storage/src/utils_test.rs#L15)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1608#-:-NoffvGB8l7XXky1K_-T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
