### PR TITLE
support multiple /monitoring/* http targets

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/652)

### CODE REVIEW

**Comment by dan-starkware** [comment]
No need for `nginx.ingress.kubernetes.io/use-regex: "true"` annotation ?

**Comment by eranreshef-starkware** [comment]
> No need for `nginx.ingress.kubernetes.io/use-regex: "true"` annotation ?

apparently no, it works as-is.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/652)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @eranreshef-starkware)

**Comment by alon-dotan-starkware** [comment]
why its needed?

**Comment by eranreshef-starkware** [comment]
> why its needed?

the implementation of the `/monitoring` endpoint in papyrus has changed.
in the past it was a json rpc endpoint which received POST requests with the requested value (`nodeVersion`, `dbTablesStats`).in the request's *body*.
the new implementation is more RESTic and it now receives GET requests with the requested value in request url path (`/monitoring/nodeVersion`, `/monitoring/dbTablesStats`)

**Review by alon-dotan-starkware — COMMENTED** [review]
I guess Im missing something here.... why regex?
```
 path: /monitoring
 pathType: implementationspecific
```
wont do the work?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/652#-:-NUHwCKeEjbTCMp8HMt6:b-9vbfyq)* status: all files reviewed, 1 unresolved discussion (waiting on @eranreshef-starkware)

**Comment by eranreshef-starkware** [comment]
no.
The papyrus process/container has 2 different web servers running in parallel (on 2 different ports) and each one of them assumes its running as the root http path.
without this regex, the /monitoring server receives the requests with the url `http://papyrus-address/monitoring/<desired-value>` but the since the server thinks its running as the root address, it only knows to route requests without the `/monitoring` part. so this regex along with the `nginx.ingress.kubernetes.io/rewrite-target: /$2` annotation does the trick.

**Comment by eranreshef-starkware** [comment]
https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

**Comment by dan-starkware** [comment]
PTAL #656, is this better?

**Comment by eranreshef-starkware** [comment]
the issue is resolved in https://github.com/starkware-libs/papyrus/pull/656

**Pull request closed without merging**
