### PR TITLE
refactor(network): report callback for received data

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0t7Dl5PQkwmThnpWu:-O-0t7Dl5PQkwmThnpWv:b-2dzw20) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/network_manager/mod.rs#L489)):*
> ```XML
> }
> 
> fn create_external_callback_for_received_data(
> ```

Make this a struct method
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 490 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0t9fTC2Lot5T3AIPb:-O-0t9fTC2Lot5T3AIPc:b-mhctur) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/network_manager/mod.rs#L490)):*
> ```XML
> 
> fn create_external_callback_for_received_data(
>     reported_peer_sender: UnboundedSender<PeerId>,
> ```

Remove this argument. Instead, use self to get a clone of reported_peer_sender
___
*[`crates/papyrus_network/src/sqmr/behaviour_test.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0tYUrAGHxeUS5udBW:-O-0tYUrAGHxeUS5udBX:b-ln8r47) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/behaviour_test.rs#L204)):*
> ```XML
>         ToSwarm::GenerateEvent(Event::External(ExternalEvent::ReceivedData {
>             data: event_data, outbound_session_id: event_outbound_session_id,
>             peer_id: event_peer_id, // We don't care about the peer_id in this test.
> ```

This is a function, not a test. And we do care about it sometime when we call it.
___
*[`crates/papyrus_network/src/sqmr/flow_test.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0uvC62jx4Uuik1r3N:-O-0uvC62jx4Uuik1r3O:b-rbdyyg) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/flow_test.rs#L138)):*
> ```XML
>     swarm_event: SwarmEventAlias<Behaviour>,
>     current_message: &mut DefaultHashMap<(PeerId, PeerId), usize>,
>     outbound_session_id_to_peer_id: &HashMap<(PeerId, OutboundSessionId), PeerId>,
> ```

Remove this from the arguments of this function and use the peer_id from the event instead to get inbound_peer_id

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0t7Dl5PQkwmThnpWu:-O-1-k_E-GyLfilCRBQU:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/network_manager/mod.rs#L489)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a struct method
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 490 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0t9fTC2Lot5T3AIPb:-O-1-krc0H6gHUjUYT_D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/network_manager/mod.rs#L490)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this argument. Instead, use self to get a clone of reported_peer_sender
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/sqmr/behaviour_test.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0tYUrAGHxeUS5udBW:-O-0vvyM1CTlTRh7cf_k:b-3rj4hs) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/behaviour_test.rs#L204)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is a function, not a test. And we do care about it sometime when we call it.
</blockquote></details>

Meant to delete. Done.
___
*[`crates/papyrus_network/src/sqmr/flow_test.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0uvC62jx4Uuik1r3N:-O-0whfu2EDHLL2Fiher:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/flow_test.rs#L138)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this from the arguments of this function and use the peer_id from the event instead to get inbound_peer_id
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/sqmr/flow_test.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0uvC62jx4Uuik1r3N:-O-11O5mC4TOdJL2fudL:b6fujo6) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/flow_test.rs#L138)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My bad. Please keep it, but assert that inbound_peer_id is equal to the one in the map

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/sqmr/behaviour_test.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0tYUrAGHxeUS5udBW:-O-18yRD3LBH9x2Fr-r0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/behaviour_test.rs#L204)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I still see this comment
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/sqmr/flow_test.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-O-0uvC62jx4Uuik1r3N:-O-18z6625p0Fvp8cryl:b-el1bzn) ([raw file](https://github.com/starkware-libs/papyrus/blob/5995f9e6266656dd222eb3e2a1955bc69d10b43d/crates/papyrus_network/src/sqmr/flow_test.rs#L138)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

My bad. Please keep it, but assert that inbound_peer_id is equal to the one in the map
</blockquote></details>

Done.tgg

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2098#-:-O-1BkoI8H996b-xH-Mu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
