### PR TITLE
feat(JSON-RPC): estimate fee gateway endpoint

### PR DESCRIPTION
**Pull request by yair-starkware**
WIP

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/999)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/999)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 591 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/999#-Nbj3CgOBo853AdxZQf7:-Nbj3CgOBo853AdxZQf8:b4zisos) ([raw file](https://github.com/starkware-libs/papyrus/blob/97759cfca558ad9a7ccd09979aec157abcfb5b14/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L591)):*
> ```XML
> }
> 
> impl TryFrom<ExecutionError> for JsonRpcError {
> ```

Moved to the mod file

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 9 files at r1, 9 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/999)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 583 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/999#-NbjViMWE3xy4Qksro7t:-NbjViMWE3xy4Qksro7u:b-ui2oql) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b7f4ea8be656838a6324ff8a3450b654f344cbf/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L583)):*
> ```XML
>                 .into_iter()
>                 .map(|(gas_price, overall_fee)| match gas_price {
>                     // If the gas price is 0, the transaction is free, wooho!
> ```

Consider removing
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/999#-NbjUoHcE9mzM_miQD3x:-NbjUoHcE9mzM_miQD3y:b-amev5r) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b7f4ea8be656838a6324ff8a3450b654f344cbf/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1)):*
> ```XML
> use std::collections::HashSet;
> ```

In a different PR. Consider moving execution related tests to it's own module
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1879 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/999#-NbjUNZc8Uo6G0RG3AI7:-NbjUNZd9wYz8D1DJpt0:bm93s6t) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b7f4ea8be656838a6324ff8a3450b654f344cbf/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1879)):*
> ```XML
>         .as_object_mut()
>         .expect("A compiled contract must be a JSON object.")
>         .remove("abi");
> ```

Do we need to remove it?



_Code quote:_
```XML
    // ABI is not required for execution.
    raw_contract_class
        .as_object_mut()
        .expect("A compiled contract must be a JSON object.")
        .remove("abi");
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/999)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 583 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/999#-NbjViMWE3xy4Qksro7t:-NbjqeNE5wu0f3NzPn2h:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b7f4ea8be656838a6324ff8a3450b654f344cbf/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L583)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider removing
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1879 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/999#-NbjUNZc8Uo6G0RG3AI7:-Nbjr7nr4dhWZzxFD0dM:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b7f4ea8be656838a6324ff8a3450b654f344cbf/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1879)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need to remove it?
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/999#-:-Nbml_2a4iTos2GCnuo6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
