### PR TITLE
Hide unnecessary modules from the storage documentation and add missi…

### PR DESCRIPTION
**Pull request by yair-starkware**
…ng_docs warning to the storage crate

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/840)

### CODE REVIEW

**Review by DvirYo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/840#-:-N_95HoT0G4MXIXx9pFK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/lib.rs` line 272 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/840#-N_E-Psn83fvQ-xmmHaE:-N_E-Psn83fvQ-xmmHaF:brlq3fn) ([raw file](https://github.com/starkware-libs/papyrus/blob/765fa82746bc38d619f3fa69435121503ebbac85/crates/papyrus_storage/src/lib.rs#L272)):*
> ```XML
> #[allow(missing_docs)]
> #[derive(thiserror::Error, Debug)]
> pub enum StorageError {
> ```

Why not documenting these? Too trivial?



_Code quote:_
```XML
#[allow(missing_docs)]
#[derive(thiserror::Error, Debug)]
pub enum StorageError {
```

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/lib.rs` line 272 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/840#-N_E-Psn83fvQ-xmmHaE:-N_E0Os4AmZ3pQUZJqMI:blm2vs5) ([raw file](https://github.com/starkware-libs/papyrus/blob/765fa82746bc38d619f3fa69435121503ebbac85/crates/papyrus_storage/src/lib.rs#L272)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not documenting these? Too trivial?
</blockquote></details>

The error message is the documentation IMO

**Pull request merged**
