### PR TITLE
feat(network): add conversion between protobuf BuiltinCounter and HashMap<Builtin, u64>

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2043)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2043)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2043#-Ny_LRDI7-jdZR1jPbfQ:-Ny_LRDI7-jdZR1jPbfR:b-5nxne3) ([raw file](https://github.com/starkware-libs/papyrus/blob/3486252d73fd2a596960bcb25149a7a1dd303bd3/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L14)):*
> ```XML
>     fn try_from(value: ProtobufBuiltinCounter) -> Result<Self, Self::Error> {
>         let mut builtin_instance_counter = HashMap::new();
>         builtin_instance_counter.insert(Builtin::RangeCheck, value.range_check as u64);
> ```

Using `as` is bad. You should use `from`/`try_from`&`expect`

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2043)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2043#-Ny_LRDI7-jdZR1jPbfQ:-Ny_O_j9-PoGuPSO_l_m:b-zaacut) ([raw file](https://github.com/starkware-libs/papyrus/blob/3486252d73fd2a596960bcb25149a7a1dd303bd3/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Using `as` is bad. You should use `from`/`try_from`&`expect`
</blockquote></details>

u32 to u64 won't fail so its ok to use `from`/`as`

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2043)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2043#-Ny_PW1h8FpyWgdn5DMm:-Ny_Qee09fo_R22ujCxD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c983667db9f5b33762a4959881f39b00ad82d0d8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to not panic here
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2043#-:-Ny_QvtNBsgY5pcMwF1H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
