### PR TITLE
Storage migration

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKbeizAcy1naCRnr7I:-NUKbeizAcy1naCRnr7J:bbf6uv9) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L33)):*
> ```XML
> }
> 
> unsafe fn migrate_v0_to_v1(path: PathBuf) {
> ```

What is unsafe in this function?
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKbOaX5qi6FXiSO8sm:-NUKbOaX5qi6FXiSO8sn:b-do0jef) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L8)):*
> ```XML
> 
> #[cfg(test)]
> #[path = "migration_test.rs"]
> ```

Why do you need path if the name of the module is the same as the filename? At the compiler repo we often name the module itself `test`, and that's why we use path.
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKazM73nA6ScFp1PM1:-NUKazM73nA6ScFp1PM2:bnrkyv8) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L33)):*
> ```XML
> #[instrument(skip(db_config), level = "debug", err)]
> fn to_v0(db_config: &DbConfig) -> StorageResult<()> {
>     let (_, mut db_writer) = open_env(db_config.clone())?;
> ```

Why are you opening a new env in this context? I suggest letting the migrate_db get a DbWriter.
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKaumXAXJXmzjU2fG5:-NUKaumYCY99peJXyG-f:b-zcpik1) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L43)):*
> ```XML
> 
> #[instrument(skip(db_config), level = "debug", err)]
> pub(crate) fn migrate_db(db_config: &DbConfig) -> StorageResult<()> {
> ```

Why only crate level?



_Code quote:_
```XML
(crate)
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKc4hW5QOXPo0x5KfU:-NUKc4hW5QOXPo0x5KfV:b-2qgzye) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L11)):*
> ```XML
> use crate::open_storage;
> use crate::test_utils::get_test_config;
> ```

We will need some better tests of migration. Maybe including real databases stored somewhere. Worth talking about it (out of the scope of this PR)
___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKcH8LDw89hfDZe_in:-NUKcH8LDw89hfDZe_io:b3erd1h) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L14)):*
> ```XML
> fn create_test_storage_v0() -> TempDir {
>     let dir = tempdir().unwrap();
>     let db_config = DbConfig {
> ```

Don't we have some test db config somewhere?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKcZ_w5ozC1UsO4Q0l:-NUKcZ_w5ozC1UsO4Q0m:bevgnmv) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L43)):*
> ```XML
>     let (_, mut db_writer) = open_env(db_config).unwrap();
> 
>     // Simulate migration of v0 -> v1 where each value gets the next BlockNumber.
> ```

I don't get this. We don't test any lib function here. Also, we don't have a v1 anywhere. I don't get any of the tests in this file. Can you explain?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @spapinistarkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKcH8LDw89hfDZe_in:-NUL5t7q5F_BVLGCiO_s:b-d9vln9) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L14)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't we have some test db config somewhere?
</blockquote></details>

Yes, but it doesn't return a handle to the temp dir (I can change it)
___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKbeizAcy1naCRnr7I:-NUL6C9o5vZlkTNrQy-f:b-f4m66n) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L33)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What is unsafe in this function?
</blockquote></details>

drop_table - from the libmdb doc:
```
    /// # Safety
    /// Caller must close ALL other [Database] and [Cursor] instances pointing to the same dbi BEFORE calling this function.
```
___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKcZ_w5ozC1UsO4Q0l:-NUL6qBhCyI7Pd788P78:b-q3g87s) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't get this. We don't test any lib function here. Also, we don't have a v1 anywhere. I don't get any of the tests in this file. Can you explain?
</blockquote></details>

Because we currently don't have versions we need to migrate, I wanted to see what it takes to write a migration function.
v0 & v1 are just dummies for this purpose.
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKbOaX5qi6FXiSO8sm:-NUL9JDl9ODS0jchNGHe:b-npes7u) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L8)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why do you need path if the name of the module is the same as the filename? At the compiler repo we often name the module itself `test`, and that's why we use path.
</blockquote></details>

That's the format in all of the other modules in our repo.
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKazM73nA6ScFp1PM1:-NULApjW6r7DeHIwwoxZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L33)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why are you opening a new env in this context? I suggest letting the migrate_db get a DbWriter.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/migration/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKaumXAXJXmzjU2fG5:-NULAqF18BNBhXGBkIzX:ba3dfob) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/mod.rs#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why only crate level?
</blockquote></details>

Removed

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUKcZ_w5ozC1UsO4Q0l:-NULEIySBm1CkEOtB3bB:b-fgheb3) ([raw file](https://github.com/starkware-libs/papyrus/blob/31df9b28204d0f5fd681ed1e7ac97172049a3a99/crates/papyrus_storage/src/migration/migration_test.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Because we currently don't have versions we need to migrate, I wanted to see what it takes to write a migration function.
v0 & v1 are just dummies for this purpose.
</blockquote></details>

The other tests in the file:
storage_v0_creation - to see that the function create_test_storage_v0 works properly
v0_upgrade - open_storage will invoke the storage migration function that should add the storage_version table

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 7 of 12 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 12 of 14 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware and @yair-starkware)

___
*[`crates/papyrus_node/src/config/mod.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUbaDJo-msFGTV5vXv5:-NUbaDJo-msFGTV5vXv6:b-imdd5k) ([raw file](https://github.com/starkware-libs/papyrus/blob/d7445bdfd7ac8256efbada938f27e35d28dd1eca/crates/papyrus_node/src/config/mod.rs#L113)):*
> ```XML
>                         growth_step: 1 << 26, // 64MB
>                     },
>                     migrate_if_necessary: false,
> ```

The default should be true, right?
___
*[`crates/papyrus_storage/src/lib.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUb_eeqBoA5UcPdAZW1:-NUb_eeqBoA5UcPdAZW2:bbzga0o) ([raw file](https://github.com/starkware-libs/papyrus/blob/d7445bdfd7ac8256efbada938f27e35d28dd1eca/crates/papyrus_storage/src/lib.rs#L47)):*
> ```XML
> ) -> StorageResult<(StorageReader, StorageWriter)> {
>     let (db_reader, mut db_writer) = open_env(storage_config.db_config)?;
>     if storage_config.migrate_if_necessary {
> ```

Should we document that using the reader before this line is prohibited? Maybe enforce it in code?
___
*[`crates/papyrus_storage/src/migration/migration_test.rs` line 8 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NUqFtX-0-dmRVXOGNjo:-NUqFtX-0-dmRVXOGNjp:b8zqiqb) ([raw file](https://github.com/starkware-libs/papyrus/blob/9271d1fc23208127679ba57234e567ff8f4f560f/crates/papyrus_storage/src/migration/migration_test.rs#L8)):*
> ```XML
> use crate::{open_storage, STORAGE_VERSION};
> 
> #[traced_test]
> ```

What is this for? Does it have more than `logs_contain/logs_assert`?

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/654)* status: 12 of 14 files reviewed, 11 unresolved discussions (waiting on @spapinistarkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/migration/mod.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/654#-NV9ZJAHAhrCZMsifjde:-NV9ZJAHAhrCZMsifjdf:b-r5a72m) ([raw file](https://github.com/starkware-libs/papyrus/blob/9271d1fc23208127679ba57234e567ff8f4f560f/crates/papyrus_storage/src/migration/mod.rs#L99)):*
> ```XML
>         db_writer = match db_version {
>             // Upgrade storage version.
>             None => to_v0(db_writer)?,
> ```

I think we shouldn't support this kind of upgrades.
We can assume the storage is already versioned.

**Pull request closed without merging**
