### PR TITLE
feat(consensus): add README to help running milestone 1

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2141)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2141?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2131?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2126** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2141** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2141?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2134** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2138** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2138?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2137** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2137?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2141#-O0DWZYr3tYTPr3mqagF:-O0DWZYr3tYTPr3mqagG:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/e39c9cffb8e3339b9dd8a5ee8e27afddda07dce9/crates/sequencing/papyrus_consensus/README.md#L9)):*
> ```Markdown
>    1. The block 0 proposer is hard coded as ID 0.
> 
> Boot Node - this must be run first:
> ```

Consider



_Suggestion:_
```Markdown
Bootstrap
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
