### PR TITLE
test(network): add tests for broadcast subscriber in network manager

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): mixed event contains the outputting behaviour instead of notified behaviour
- feat(network): add broadcast behaviour with unimplemented
- feat(network): connect broadcast behaviour to mixed behaviour
- feat(network): add register_broadcast_subscribers without connecting to behaviour
- refactor(network): move code
- refactor(network): make StreamHashMap usable in source code (not tests only)
- feat(network): connect broadcast subscribers to behaviour
- test(network): add tests for broadcast subscriber in network manager

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1987)

### CODE REVIEW

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1987#-NyPZ5qrBAiLiSChC4_H:-NyPZ5qrBAiLiSChC4_I:b26ywnu) ([raw file](https://github.com/starkware-libs/papyrus/blob/959f46ad23ba8fd9449628a55b17ce347ec331cc/crates/papyrus_network/src/network_manager/test.rs#L93)):*
> ```XML
>     }
> 
>     pub fn get_messages_we_broadcasted_stream(&mut self) -> impl Stream<Item = (Bytes, Topic)> {
> ```

Since rust is typed, I prefer not to make the type part of the name. I understand that without the `stream` get maybe sounds like we message that are already prepared, so what about receive or does that imply we should have a receiver type to you?



_Suggestion:_
```XML
receive_messages_we_broadcasted
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1987)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1987#-NyPZ5qrBAiLiSChC4_H:-NyPbxAz1UQogYW7-XDj:bj4fvy0) ([raw file](https://github.com/starkware-libs/papyrus/blob/959f46ad23ba8fd9449628a55b17ce347ec331cc/crates/papyrus_network/src/network_manager/test.rs#L93)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Since rust is typed, I prefer not to make the type part of the name. I understand that without the `stream` get maybe sounds like we message that are already prepared, so what about receive or does that imply we should have a receiver type to you?
</blockquote></details>

How's this?

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1987)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by matan-starkware — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1987#-:-NyPoK1K6cZfQP7UBgib:b-uwkowd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
