### PR TITLE
deny unkown fields in txs of sn client

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/792)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/792)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/792#-NZKfTV47feBd4VxVyD5:-NZKfTV53J-jGtH8I7Mn:b-t3d727) (no related file):*
I'm working on adding a test for this

___

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/792)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/792#-NZKfuaJ8bmKFmY5Khnt:-NZKfuaJ8bmKFmY5Khnu:b-13xt4k) (no related file):*
Doesn't this break backward compatibility?

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Doesn't this break backward compatibility?
</blockquote></details>

I mean, forward compatibility

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/792)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/792#-NZKfuaJ8bmKFmY5Khnt:-NZKhHrJ8tgsHZ7vRU9Q:b4km1xm) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I mean, forward compatibility
</blockquote></details>

Yes, @dan-starkware approved this after some consideration between forward compatibility and bug detection

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/792#-:-NZKmje-4UF1TShJpUUF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
