### PR TITLE
build(network): add time from start of session to measurement

### PR DESCRIPTION
**Pull request by ShahakShama**
- build(network): add benchmark executable to streamed_data
- build(network): add time from start of session to measurement

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1596)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1596)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1596#-NoLWyVf1jS7WfoM2vBf:-NoLWyVf1jS7WfoM2vBg:b10tkv8) ([raw file](https://github.com/starkware-libs/papyrus/blob/d7103a1bb37842340568257bf61e256773e9a5d6/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L76)):*
> ```XML
>         outbound_session_measurements.insert(
>             outbound_session_id,
>             OutboundSessionMeasurement {
> ```

maybe clean this a bit with `OutboundSessionMeasurement::new()`?
___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1596#-NoLXFr7DrgKieE10mnH:-NoLXFr7DrgKieE10mnI:bez9cuw) ([raw file](https://github.com/starkware-libs/papyrus/blob/d7103a1bb37842340568257bf61e256773e9a5d6/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L125)):*
> ```XML
> }
> 
> struct OutboundSessionMeasurement {
> ```

please extract from this file

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1596)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/streamed_data_benchmark.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1596#-NoLXFr7DrgKieE10mnH:-NoLhBet9BAG-GHYgDqN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d7103a1bb37842340568257bf61e256773e9a5d6/crates/papyrus_network/src/bin/streamed_data_benchmark.rs#L125)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please extract from this file
</blockquote></details>

Done.

**Review by nagmo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 7 files at r2, 2 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1596#-:-NoLnJB20OmaseqekeiJ:bnfp4nl)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1596#-:-NoMe7aM850P8H69CQM0:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
