### PR TITLE
feat(JSON-RPC): return syncing state

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_gateway/src/syncing_state.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbIqvBW0tAsSmSvgtiQ:-NbIqvBW0tAsSmSvgtiR:b-257obp) ([raw file](https://github.com/starkware-libs/papyrus/blob/c43f995b65b45f5458785966d56fe990a374be1e/crates/papyrus_gateway/src/syncing_state.rs#L58)):*
> ```XML
>         return Ok(BlockHashAndNumber::default())
>     };
>     let block_hash = txn.get_block_header(block_number)?.unwrap().block_hash;
> ```

Please use expect instead 



_Code quote:_
```XML
unwrap()
```
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbIsoQ1B_2AEuxw0hRi:-NbIsoQ1B_2AEuxw0hRj:b-ejet8c) ([raw file](https://github.com/starkware-libs/papyrus/blob/c43f995b65b45f5458785966d56fe990a374be1e/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L147)):*
> ```XML
>         run_server(&gateway_config, shared_highest_block.clone(), storage_reader, NODE_VERSION)
>             .await
>             .unwrap();
> ```

Do we actually need to run a server here?



_Code quote:_
```XML
    let (server_address, _handle) =
        run_server(&gateway_config, shared_highest_block.clone(), storage_reader, NODE_VERSION)
            .await
            .unwrap();
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yoavGrs)

___
*[`crates/papyrus_gateway/src/syncing_state.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbIqvBW0tAsSmSvgtiQ:-NbJ8TYV-dCckc0JE4N3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c43f995b65b45f5458785966d56fe990a374be1e/crates/papyrus_gateway/src/syncing_state.rs#L58)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use expect instead 
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbIsoQ1B_2AEuxw0hRi:-NbJ7gFF5QhXc1BixMLT:bbpv0ur) ([raw file](https://github.com/starkware-libs/papyrus/blob/c43f995b65b45f5458785966d56fe990a374be1e/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L147)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we actually need to run a server here?
</blockquote></details>

We don't need a server, we want it.
We want the test to be unaware of routing within the gateway.
@ShahakShama

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 4 of 12 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbPA0L58LuV0S5sba35:-NbPA0L58LuV0S5sba36:b8b3jvj) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5ef817c2f5f60c106149bbd7fbb30da4b090007/crates/papyrus_gateway/src/test_utils.rs#L59)):*
> ```XML
> // Call a method on the `RPC module` without having to spin up a server.
> // Returns the raw `result field` in JSON-RPC response and the deserialized result if successful.
> pub async fn raw_call<R: JsonRpcServerImpl, T: for<'a> Deserialize<'a>>(
> ```

Why pub?
___
*[`crates/papyrus_gateway/src/test_utils.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbPAFQB-5fOt5C9CrCP:-NbPAFQB-5fOt5C9CrCQ:b2b0r6k) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5ef817c2f5f60c106149bbd7fbb30da4b090007/crates/papyrus_gateway/src/test_utils.rs#L66)):*
> ```XML
>     let req = format!(r#"{{"jsonrpc":"2.0","id":"1","method":"{method}","params":[{params}]}}"#);
>     let (resp_wrapper, _) = module.raw_json_request(req.as_str(), 1).await.expect("request format");
>     if !resp_wrapper.success {
> ```

You're in a test. If a None is equivalent to test failure you can expect here and return (Value, T) instead of Option

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbPA0L58LuV0S5sba35:-NbPBgHe076aN3xpwcLQ:b-a2ujfl) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5ef817c2f5f60c106149bbd7fbb30da4b090007/crates/papyrus_gateway/src/test_utils.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why pub?
</blockquote></details>

Changed.
___
*[`crates/papyrus_gateway/src/test_utils.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbPAFQB-5fOt5C9CrCP:-NbPCDgfAqU15CurqRAx:b-jbibtc) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5ef817c2f5f60c106149bbd7fbb30da4b090007/crates/papyrus_gateway/src/test_utils.rs#L66)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're in a test. If a None is equivalent to test failure you can expect here and return (Value, T) instead of Option
</blockquote></details>

It's a util, I'm not sure that `None` is not expected for any use case, but not really needed now.

(I can't expect here, `success` is a boolean)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: all files reviewed, 6 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/papyrus_gateway/src/api.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTCO8xAE1mOFNsnwB8:-NbTCO8xAE1mOFNsnwB9:ba3dfna) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/api.rs#L104)):*
> ```XML
>         max_events_keys,
>         starting_block,
>         shared_highest_block: shared_highest_block.clone(),
> ```

Remove?



_Code quote:_
```XML
.clone()
```
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 463 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTCp2BBWwHBkA65jGK:-NbTCp2BBWwHBkA65jGL:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L463)):*
> ```XML
>             highest_block_num: highest_block.block_number,
>         };
>         Ok(SyncingState::SyncStatus(sync_status))
> ```

Consider



_Suggestion:_
```XML
        Ok(SyncingState::SyncStatus(SyncStatus {
            starting_block_hash: self.starting_block.block_hash,
            starting_block_num: self.starting_block.block_number,
            current_block_hash: current_block.block_hash,
            current_block_num: current_block.block_number,
            highest_block_hash: highest_block.block_hash,
            highest_block_num: highest_block.block_number,
        }))
```
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 162 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTDizf-O9co1etCn3q:-NbTDizf-O9co1etCn3r:b-nykaum) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L162)):*
> ```XML
>         Arc::new(MockStarknetWriter::new()),
>     )
>     .into_rpc_module();
> ```

Can you use `get_test_rpc_server_and_storage_writer`



_Code quote:_
```XML
    let ((storage_reader, _), _temp_dir) = get_test_storage();
    let config = get_test_gateway_config();
    let shared_highest_block = get_test_highest_block();
    let module = JsonRpcServerV0_3Impl::new(
        config.chain_id,
        storage_reader,
        config.max_events_chunk_size,
        config.max_events_keys,
        BlockHashAndNumber::default(),
        shared_highest_block.clone(),
        Arc::new(MockStarknetWriter::new()),
    )
    .into_rpc_module();
```
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTEOBtC-YnYlxt7Fz5:-NbTEOBtC-YnYlxt7Fz6:b-4q5jn9) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L165)):*
> ```XML
> 
>     let (json_response_0, result_0) =
>         raw_call::<_, bool>(&module, "starknet_V0_3_syncing", "").await;
> ```

Consider also a const (as `method_name`)



_Code quote:_
```XML
"starknet_V0_3_syncing"
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/api.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTCO8xAE1mOFNsnwB8:-NbTGTsM-sWrZCl691aO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/api.rs#L104)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 463 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTCp2BBWwHBkA65jGK:-NbTH2F54z-9DgjMs-fC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L463)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 162 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTDizf-O9co1etCn3q:-NbTHU914d-EprM4Ea-n:bgu53sc) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L162)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you use `get_test_rpc_server_and_storage_writer`
</blockquote></details>

No :(
I need access to `shared_highest_block`.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTEOBtC-YnYlxt7Fz5:-NbTImIPC-t7V7r_hd0j:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L165)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider also a const (as `method_name`)
</blockquote></details>

Done.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 162 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/995#-NbTDizf-O9co1etCn3q:-NbTMwI178jFDWc0IEoz:b-3q2kqe) ([raw file](https://github.com/starkware-libs/papyrus/blob/00b4a640f4bf147b76decb8ab26d2ea6a67fa481/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L162)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

No :(
I need access to `shared_highest_block`.
</blockquote></details>

ok, in a different PR consider returning it from the util (and ignoring elsewhere, or having two utils one that returns it and another one that doesn't and use the first one)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 8 of 10 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/995)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Pull request merged**
