### PR TITLE
docs: fixed API request example

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665)

### CODE REVIEW

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-:-Npp_NVBAoLqDoipJCjn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`README.adoc` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-Npp_PJK3ZFSh7CLiLqN:-Npp_PJK3ZFSh7CLiLqO:b1htiez) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2733eb6427eb15596c0a165fae698abbbefd339/README.adoc#L226)):*
> ```AsciiDoc
> ----
> curl --location 'localhost:8080/rpc/v0_4_0' --header 'Content-Type: application/json'\
>  --data '\{"jsonrpc":"2.0","id":0,"method":"starknet_blockHashAndNumber", "params": {} }'
> ```

Maybe we can use the opportunity to change the example here to a method that has params?

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`README.adoc` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-Npp_PJK3ZFSh7CLiLqN:-Nq1fbZH9tQAklxGUyYC:b-ey41w1) ([raw file](https://github.com/starkware-libs/papyrus/blob/a16283a4d5639fb3579a36c2cf9508f762637322/README.adoc#L226)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Maybe we can use the opportunity to change the example here to a method that has params?
</blockquote></details>

great idea

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`README.adoc` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-NqLhYXJ0PaUxAaqIqpI:-NqLhYXJ0PaUxAaqIqpJ:b-f5odew) ([raw file](https://github.com/starkware-libs/papyrus/blob/c30d03269a29fad0f5f36ac38a434c98c43cae8a/README.adoc#L156)):*
> ```AsciiDoc
> ----
> mkdir <local-host-data-path>
> sudo chown -R $(id -u):$(id -g) /<local-host-data-path>
> ```

@eranreshef-starkware Is this the correct way to set permissions to the data dir?

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eranreshef-starkware and @ShahakShama)

___
*[`README.adoc` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-NqLhYXJ0PaUxAaqIqpI:-NrkJxyv6RkAPQkfS0UH:bz5tzbn) ([raw file](https://github.com/starkware-libs/papyrus/blob/c30d03269a29fad0f5f36ac38a434c98c43cae8a/README.adoc#L156)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@eranreshef-starkware Is this the correct way to set permissions to the data dir?
</blockquote></details>

pinging this

**Comment by eranreshef-starkware** [comment]
*[`README.adoc` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-NqLhYXJ0PaUxAaqIqpI:-NrkP0_d5QgcjP9KXvYt:b19bsvz) ([raw file](https://github.com/starkware-libs/papyrus/blob/c30d03269a29fad0f5f36ac38a434c98c43cae8a/README.adoc#L156)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

pinging this
</blockquote></details>

@ShahakShama WDYM?
There are multiple ways to set/change file system permissions. I am no aware of a "correct" way...

**Comment by eranreshef-starkware** [comment]
*[`README.adoc` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-NqLhYXJ0PaUxAaqIqpI:-NrnSfRyB9v2q1O3wcDY:b345fhp) ([raw file](https://github.com/starkware-libs/papyrus/blob/c30d03269a29fad0f5f36ac38a434c98c43cae8a/README.adoc#L156)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What I meant is, is it required to chown files that the dockerfile uses or maybe Eitan has an issue in how he installed docker, because on my computer it worked without this
</blockquote></details>

from what I understand from reading these instructions, these files are not used by the dockerfile. they are used by the docker daemon/runtime and are mounted into the container.
I don't think this specific `chown` is required because when calling `mkdir` with no additional permission args causes the new dir to get the relevant permissions for the user who created it. so if I understand correctly, this command doesn't in fact change anything.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1665#-:-NsISqQgAIvz2LJnORkr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
