### PR TITLE
feat(monitoring): add grafana.json to the repo

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1058)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Please add @alon-dotan-starkware

**Comment by dan-starkware** [comment]
I think it should be under deployments, right?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1058)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alon-dotan-starkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcQsW097NGwIVx2AsaD:-NcQt42TD5L_0lCBQHE1:bb6un1j) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add @alon-dotan-starkware
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcQs_u9Def6BeB-uVz0:-NcQsuiI0z0WTJGttv0M:bq9ismx) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I think it should be under deployments, right?
</blockquote></details>

That is exactly where Alon D wanted it

___

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1058)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @OriStarkware)

___
*[`Monitoring/grafana.json` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcR0NwS7xWSe9UPGYwY:-NcR0NwS7xWSe9UPGYwZ:b-fw9vuk) ([raw file](https://github.com/starkware-libs/papyrus/blob/389601c086f8eaaa5e847667cda274629412ebcc/Monitoring/grafana.json#L47)):*
> ```JSON
>     {
>       "datasource": {
>         "type": "prometheus",
> ```

looks like you didn't export it right... 
there should be templated section for data source
something like:
```
{

"\_\_inputs": \[

{

"name": "DS\_PROMETHEUS",

"label": "Prometheus",

"description": "",

"type": "datasource",

"pluginId": "prometheus",

"pluginName": "Prometheus"

},

{

"name": "DS\_ELASTICSEARCH",

"label": "Elasticsearch",

"description": "",

"type": "datasource",

"pluginId": "elasticsearch",

"pluginName": "Elasticsearch"

}

\],
```
___
*[`Monitoring/grafana.json` line 1646 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcR0W4V9yupA0gt6xOz:-NcR0W4W4X73N5KeVHNx:b-c8cteh) ([raw file](https://github.com/starkware-libs/papyrus/blob/389601c086f8eaaa5e847667cda274629412ebcc/Monitoring/grafana.json#L1646)):*
> ```JSON
>   "timepicker": {},
>   "timezone": "",
>   "title": "Papyrus-integration-ori",
> ```

Please clean all title and use generic ones

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1058)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`Monitoring/grafana.json` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcR0NwS7xWSe9UPGYwY:-NcREAuD-bQvqO6m9Q2c:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/389601c086f8eaaa5e847667cda274629412ebcc/Monitoring/grafana.json#L47)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

looks like you didn't export it right... 
there should be templated section for data source
something like:
```
{

"\_\_inputs": \[

{

"name": "DS\_PROMETHEUS",

"label": "Prometheus",

"description": "",

"type": "datasource",

"pluginId": "prometheus",

"pluginName": "Prometheus"

},

{

"name": "DS\_ELASTICSEARCH",

"label": "Elasticsearch",

"description": "",

"type": "datasource",

"pluginId": "elasticsearch",

"pluginName": "Elasticsearch"

}

\],
```
</blockquote></details>

Done.
___
*[`Monitoring/grafana.json` line 1646 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-NcR0W4V9yupA0gt6xOz:-NcREDuK0b8ECXIg3xkr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/389601c086f8eaaa5e847667cda274629412ebcc/Monitoring/grafana.json#L1646)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Please clean all title and use generic ones
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1058#-:-NcRX-0g5qX1y1Di0itz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
