### PR TITLE
feat(network): db executor support for data types with a new trait

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1789)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1789** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1789?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1789)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNJ6S4EYeOfyN6Kh4D:-NsNJ6S4EYeOfyN6Kh4E:b-86meg) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/mod.rs#L206)):*
> ```XML
> // we need to tell clippy to ignore the "needless" lifetime warning because it's not true.
> // we do need the lifetime for the automock, following clippy's suggestion will break the code.
> #[allow(clippy::needless_lifetimes)]
> ```

Could you check if `#[(cfg_attr(not(test), allow(clippy::needless_lifetimes))]` works?
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNNIhL1GVlGYSsjUnS:-NsNNIhL1GVlGYSsjUnT:b-sukgdq) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/mod.rs#L216)):*
> ```XML
> }
> 
> impl FetchBlockDataFromDb for DataType {
> ```

I think automock supports mocking methods. Could you remove the trait, make this into a method and mock the method? The motivation is to get rid of the impl in register_query
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNMnBV5lBdaW6vEyQw:-NsNMnBV5lBdaW6vEyQx:bjce92) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/test.rs#L34)):*
> ```XML
>         step: 1,
>     };
>     let query_id = db_executor.register_query(query, DataType::SignedBlockHeader, sender);
> ```

WDYT about testing all enum variants with the crate enum_iterator?
Future PR

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1789)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNJ6S4EYeOfyN6Kh4D:-NsNbxex5pBfX-5_LhEk:bu4daxf) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/mod.rs#L206)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Could you check if `#[(cfg_attr(not(test), allow(clippy::needless_lifetimes))]` works?
</blockquote></details>

it does but it doesn't help fixing the underlying problem that we don't actually need to lifetime parameter but still must have it for the mock.
I think it makes the macro much less readable and doesn't add any value.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNNIhL1GVlGYSsjUnS:-NsNcSov8ZQO4jf5RGd3:b-x1ph44) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/mod.rs#L216)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think automock supports mocking methods. Could you remove the trait, make this into a method and mock the method? The motivation is to get rid of the impl in register_query
</blockquote></details>

but then I need to either:
1. implement the db access logic outside of the db executor (which I don't want to)
2. implement the DataType here - currently possible since this is the only function but not a good software design for the future.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-NsNMnBV5lBdaW6vEyQw:-NsNbaIS1H-pIEGDBKw0:bwu3hgp) ([raw file](https://github.com/starkware-libs/papyrus/blob/4d8af666be0ba6a5f14c64364b207947df567447/crates/papyrus_network/src/db_executor/test.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

WDYT about testing all enum variants with the crate enum_iterator?
Future PR
</blockquote></details>

sounds like a good idea

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1789#-:-NsNdDsK7bOTkLXSkvTX:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1789)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
