### PR TITLE
feat(network): ensure protoc version >=3.15

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991)* status: all files reviewed, 7 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/build.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvnt-i4iaSfdgAamF-:-Nxvnt-j7VkOxvxkhrXn:b8ad0hj) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L13)):*
> ```XML
>             .arg("--version")
>             .output()
>             .expect("Failed to get protoc version, check if it is installed.")
> ```

You know that if it failed it means that protoc isn't installed. Change this message to "Protoc is not installed."
___
*[`crates/papyrus_network/build.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvoiy296NRJeiLMgo3:-NxvoBItBEVJGAGLMWsr:b-r0ax3c) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L19)):*
> ```XML
> 
>     let parts: Vec<&str> = protoc_version.split_whitespace().collect();
>     assert!(parts.len() >= 2, "Failed to determine protoc version");
> ```

Instead of asserting, in the line below write parts.get(1).expect("Failed to ...") instead of parts[1]
___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvoHsZ32x-uj8cppN0:-NxvoHsZ32x-uj8cppN1:b-qnevy1) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
> ```XML
>     let parts: Vec<&str> = protoc_version.split_whitespace().collect();
>     assert!(parts.len() >= 2, "Failed to determine protoc version");
>     let mut version_parts = parts[1].split('.').map(|part| part.parse::<u32>().unwrap_or_default());
> ```

Why do you do unwrap_or_default and not expect? Why is a parsing error equivalent to 0
___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvov6Q31Wb3RcaWkbc:-Nxvov6Q31Wb3RcaWkbd:b-pcox2m) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
> ```XML
>     let parts: Vec<&str> = protoc_version.split_whitespace().collect();
>     assert!(parts.len() >= 2, "Failed to determine protoc version");
>     let mut version_parts = parts[1].split('.').map(|part| part.parse::<u32>().unwrap_or_default());
> ```

Extract parts[1] to a variable and give it a name that will help readers understand what it contains
___
*[`crates/papyrus_network/build.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvqIrQ7wWEhGPzoAPS:-NxvqIrQ7wWEhGPzoAPT:b-g06kmg) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L22)):*
> ```XML
>     let mut version_parts = parts[1].split('.').map(|part| part.parse::<u32>().unwrap_or_default());
> 
>     match (version_parts.next(), version_parts.next()) {
> ```

No need for match here, you can just expect
```
let major = version_parts.next().expect("Error parsing ...");
let minor = version_parts.next().expect("Error parsing ...");
```
___
*[`crates/papyrus_network/build.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvs1757LZ8NwKyiiuV:-Nxvs1757LZ8NwKyiiuW:bi6g0a8) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L40)):*
> ```XML
>             }
>         }
>         _ => Err(Error::new(ErrorKind::Other, "Error parsing protoc version")),
> ```

Improve this error message
"Protoc version did not have a major and minor number"
___
*[`crates/papyrus_network/build.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvshqtAI1zBEQGhK59:-NxvshqtAI1zBEQGhK5A:b-69z6ma) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L40)):*
> ```XML
>             }
>         }
>         _ => Err(Error::new(ErrorKind::Other, "Error parsing protoc version")),
> ```

I think that it's valid that there won't be a minor version and then it's equal to 0. Use unwrap_or_default for the minor version instead

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/build.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvnt-i4iaSfdgAamF-:-NxwDDRU8GcnGCcg7wYt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You know that if it failed it means that protoc isn't installed. Change this message to "Protoc is not installed."
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvoiy296NRJeiLMgo3:-NxwDHipECXeALHAfbmI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of asserting, in the line below write parts.get(1).expect("Failed to ...") instead of parts[1]
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvoHsZ32x-uj8cppN0:-NxwDP4PEqdBiAQPMyFT:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you do unwrap_or_default and not expect? Why is a parsing error equivalent to 0
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvov6Q31Wb3RcaWkbc:-NxwGZG99ntG8KjZgFfo:b-qgdrve) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract parts[1] to a variable and give it a name that will help readers understand what it contains
</blockquote></details>

I have extracted protoc_version_parts which as the name suggests holds the individual components of the protoc version
___
*[`crates/papyrus_network/build.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvqIrQ7wWEhGPzoAPS:-NxwDQzN7e820ftrK9e0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need for match here, you can just expect
```
let major = version_parts.next().expect("Error parsing ...");
let minor = version_parts.next().expect("Error parsing ...");
```
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvs1757LZ8NwKyiiuV:-NxwDTonCVtvj1lK24BG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Improve this error message
"Protoc version did not have a major and minor number"
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-NxvshqtAI1zBEQGhK59:-NxwDUo79X_q0Am2aEsF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think that it's valid that there won't be a minor version and then it's equal to 0. Use unwrap_or_default for the minor version instead
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvov6Q31Wb3RcaWkbc:-NxwWh3mCTb66NXYnUnb:bxm8f5j) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

I have extracted protoc_version_parts which as the name suggests holds the individual components of the protoc version
</blockquote></details>

I think it's clearer if you add a middle variable called protoc_version_str that contains the 2nd element of parts

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/build.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-Nxvov6Q31Wb3RcaWkbc:-NxwYwM4216dXliwFd0f:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/281a9b9d6b6b9bd91d66dd33fa5a427925ec2c25/crates/papyrus_network/build.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think it's clearer if you add a middle variable called protoc_version_str that contains the 2nd element of parts
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1991#-:-Ny-jtQn1CNGY65lorto:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
