### PR TITLE
Add load trait for sub configs.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?
- Loading the dump file for configurations to config objects.
- Currently only for the gateway config.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtnNga24pwrokElOJU:-NXtnNga24pwrokElOJV:b-35rqki) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L10)):*
> ```XML
> 
> pub type ParamPath = String;
> pub type SerializedValue = Value;
> ```

I don't really get the value of this alias. The serialized/deserialized nature of something is all about the context it is being used in. It feels like unnecessary indirection to me.

ParamPath and Description I feel a little bit like this but those at least feel like they add more value as descriptors than this does.



_Code quote:_
```XML
pub type SerializedValue = Value;
```
___
*[`crates/papyrus_config/src/lib.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtn2F0DpB3cBHnbqyB:-NXtn2F0DpB3cBHnbqyC:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L12)):*
> ```XML
> pub type SerializedValue = Value;
> pub type Description = String;
> pub type ParamMapping = BTreeMap<ParamPath, SerializedValue>;
> ```





_Suggestion:_
```XML
ParamMap
```
___
*[`crates/papyrus_config/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtpuY_7qvKyE5Joi5f:-NXtpuY_7qvKyE5Joi5g:b-e0gs4l) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L28)):*
> ```XML
> }
> /// Serialization and deserialization for configs.
> pub trait SerdeConfig: for<'a> Deserialize<'a> + Serialize + Sized {
> ```

This is pretty complex and could be nice to have a comment (just something to point the reader to since I don't think this is very common)



_Suggestion:_
```XML
/// Serialization and deserialization for configs.
/// For an explanation of `for<'a> Deserialize<'a>` see https://doc.rust-lang.org/nomicon/hrtb.html.
pub trait SerdeConfig: for<'a> Deserialize<'a> + Serialize + Sized {
```
___
*[`crates/papyrus_config/src/lib.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtwSSJ1z8SgShJXUDP:-NXtwSSJ1z8SgShJXUDQ:b77kaaw) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L49)):*
> ```XML
>     /// Deserializes the sub-config from flatten JSON.
>     fn load(
>         serialized_configuration: &BTreeMap<ParamPath, SerializedParam>,
> ```

This is specifically for taking in the output of `dump` right? Not a generic serialization.



_Suggestion:_
```XML
config_dump
```
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NXtxiW45NJFua_Spf4W:b-vxkb9w) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
> ```XML
>     /// Deserializes the sub-config from flatten JSON. Takes the params that are rooted at this
>     /// config name.
>     fn load_sub_config(
> ```

My memory is that you said we wanted to be able to load only part of a config. Can you add an example for that?

Also what do you think of having tests here to show each of the (load/dump)_(/sub_config) with a simple struct?



_Code quote:_
```XML
load_sub_config
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: all files reviewed, 5 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtnNga24pwrokElOJU:-NXu2EZi5-jv7CEwWNbz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L10)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't really get the value of this alias. The serialized/deserialized nature of something is all about the context it is being used in. It feels like unnecessary indirection to me.

ParamPath and Description I feel a little bit like this but those at least feel like they add more value as descriptors than this does.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtn2F0DpB3cBHnbqyB:-NXu3VZeEHwyW4ywnkot:bss4a2b) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L12)):*
> ```XML
> pub type SerializedValue = Value;
> pub type Description = String;
> pub type ParamMapping = BTreeMap<ParamPath, SerializedValue>;
> ```

Removed.
___
*[`crates/papyrus_config/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtpuY_7qvKyE5Joi5f:-NXu7VwW9tnZsuFlSmjO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L28)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is pretty complex and could be nice to have a comment (just something to point the reader to since I don't think this is very common)
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtwSSJ1z8SgShJXUDP:-NXu7YJg50h__OIzLBWp:byr4flj) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L49)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is specifically for taking in the output of `dump` right? Not a generic serialization.
</blockquote></details>

Right.
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NXuDd1Q9f2vdPwgZRLX:ba7m214) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

My memory is that you said we wanted to be able to load only part of a config. Can you add an example for that?

Also what do you think of having tests here to show each of the (load/dump)_(/sub_config) with a simple struct?
</blockquote></details>

What does it mean "load part of a config"?
A test is a good idea. Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuv1I_7WQRCtxiZSu7:-NXuv1Ia4zvbpjiKS95w:bi1nc43) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L12)):*
> ```XML
>     pub a: String,
>     pub b: usize,
> }
> ```

For simplicity maybe just have 1 field?



_Suggestion:_
```XML
pub struct InnerConfig {
    pub b: usize,
}
```
___
*[`crates/papyrus_config/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuvgwh9D58AgGH0gEX:-NXuvgwh9D58AgGH0gEY:b-gzbpug) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L35)):*
> ```XML
> #[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
> pub struct OuterConfig {
>     pub inner: InnerConfig,
> ```

please make this different than `InnerConfig::config_name` to show that we handle this.



_Code quote:_
```XML
inner
```
___
*[`crates/papyrus_config/src/config_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuuppA1PhvTuOHg_Gz:-NXuuppB0M3QEKOIpLW_:bla0w0j) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L63)):*
> ```XML
>     let loaded_config = OuterConfig::load(&outer_config.dump()).unwrap();
>     assert_eq!(loaded_config, outer_config);
> }
> ```

I was hoping maybe we could have 4 test: (dump/load)_(/sub_config). Each one showing an explicit input/output? (Here is a pseudocode example). I think tests that are focused on each of the outer functions are good since they are focused and I like an explicit example (Honestly could be a good candidate for a doctest).

(see https://docs.rs/maplit/1.0.2/maplit/ for the btreemap! macro)



_Suggestion:_
```XML
#[test]
fn dump() {
    let outer_config = OuterConfig { c: 0, inner: InnerConfig { b: 2 } };
    let dump = outer_config.dump();
    let expected = btreeemap! {
        "outer.inner.b" => {description: "This is b", value: 2},
        "outer.c" => {description: "This is c", value: 0},
    };
    assert_eq!(dump, expected);
}
```
___
*[`crates/papyrus_config/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtpuY_7qvKyE5Joi5f:-NXuw_5_0MwSYHnscv5X:bu7i80d) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L28)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Feel free to rephrase if you have a better idea (unblocking)
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NXuwftpBHyvQee15Z4x:bt6my8o) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

What does it mean "load part of a config"?
A test is a good idea. Done.
</blockquote></details>

Add a test where you build OuterConfig, dump it, and then build InnerConfig from the dump.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuv1I_7WQRCtxiZSu7:-NXxqz5eBAEmYzZrq22Y:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L12)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

For simplicity maybe just have 1 field?
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuvgwh9D58AgGH0gEX:-NXxrcW019QuXkFdvIQe:b-heedf9) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L35)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

please make this different than `InnerConfig::config_name` to show that we handle this.
</blockquote></details>

They should be the same.
In the dumping, we label the inner config fields by `InnerConfig::config_name`. The loading is applied only for the outer config on a (nested) JSON object, thus the inner config elements should be labeled by the name of the inner config field. 
___
*[`crates/papyrus_config/src/config_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuuppA1PhvTuOHg_Gz:-NXy04595qTHfJkne3y_:b-5iz0k5) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L63)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I was hoping maybe we could have 4 test: (dump/load)_(/sub_config). Each one showing an explicit input/output? (Here is a pseudocode example). I think tests that are focused on each of the outer functions are good since they are focused and I like an explicit example (Honestly could be a good candidate for a doctest).

(see https://docs.rs/maplit/1.0.2/maplit/ for the btreemap! macro)
</blockquote></details>

IMO 2 tests are enough.
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NXy0v9tC76LvsZ3cfyQ:b-4pp4g9) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Add a test where you build OuterConfig, dump it, and then build InnerConfig from the dump.
</blockquote></details>

The following is possible, but it has no practical use case.
```
InnerConfig::load_sub_config(&outer_config.dump())
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuvgwh9D58AgGH0gEX:-NYIN5HI29rzI_v9xfgz:bc6w3x6) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L35)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

They should be the same.
In the dumping, we label the inner config fields by `InnerConfig::config_name`. The loading is applied only for the outer config on a (nested) JSON object, thus the inner config elements should be labeled by the name of the inner config field. 
</blockquote></details>

This seems tricky. This means that anyone who creates a SubConfig, with a field that is also a subconfig, must make the field name the same as that fields `SubConfig::config_name`? This sounds like asking for trouble.

What happens if I were to name the field `inner_config`? How would I have known about this issue? It creates tight coupling between a trait implementation and another struct's field names.
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NYIO9I1-0z9t7Rpg17y:bg6nvzg) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The following is possible, but it has no practical use case.
```
InnerConfig::load_sub_config(&outer_config.dump())
```
</blockquote></details>

OK so I guess I misunderstood. `sub_config` just means that we append `{config_name}` to `{field_name}`?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @matan-starkware and @TzahiTaub)

___
*[`crates/papyrus_config/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXuvgwh9D58AgGH0gEX:-NYImBjn0q5dypEhv2nB:b-of35de) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ee7f4c40abdd45859073a11bf98758e2661bf2/crates/papyrus_config/src/config_test.rs#L35)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This seems tricky. This means that anyone who creates a SubConfig, with a field that is also a subconfig, must make the field name the same as that fields `SubConfig::config_name`? This sounds like asking for trouble.

What happens if I were to name the field `inner_config`? How would I have known about this issue? It creates tight coupling between a trait implementation and another struct's field names.
</blockquote></details>

I agree. Changed.
Now each config should use `append_sub_config_name` for its sub-config name.
Different configs can use the same sub-config with different names.
___
*[`crates/papyrus_config/src/lib.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NXtxiW45NJFua_Spf4V:-NYImn_97rucV0v0p35U:b13auj0) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c82a504892f8a4a83237dbc35253eb67fc9ecb4/crates/papyrus_config/src/lib.rs#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

OK so I guess I misunderstood. `sub_config` just means that we append `{config_name}` to `{field_name}`?
</blockquote></details>

Right.
Now we do it in `append_sub_config_name`.

**Review by matan-starkware — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755#-:-NYM_sfv-I7pxk72-q2v:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NYM_jvFEEmNT5vNC7Z2:-NYM_jvFEEmNT5vNC7Z3:bt5ucsc) ([raw file](https://github.com/starkware-libs/papyrus/blob/75552f07dc309842cd47b8d9446236dd38083bce/crates/papyrus_config/src/lib.rs#L51)):*
> ```XML
> pub fn append_sub_config_name(
>     config_dump: BTreeMap<ParamPath, SerializedParam>,
>     prefix: &str,
> ```

Is prefix required to be the same as the field name? If so this should be commented on.



_Code quote:_
```XML
prefix: &str,
```
___
*[`crates/papyrus_config/src/lib.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NYMZoJJ-YQUBWX36-gb:-NYMZoJJ-YQUBWX36-gc:b-642v6n) ([raw file](https://github.com/starkware-libs/papyrus/blob/75552f07dc309842cd47b8d9446236dd38083bce/crates/papyrus_config/src/lib.rs#L52)):*
> ```XML
>     config_dump: BTreeMap<ParamPath, SerializedParam>,
>     prefix: &str,
> ) -> BTreeMap<ParamPath, SerializedParam> {
> ```

I think it's a little easier to read this way at the call sites.



_Suggestion:_
```XML
pub fn append_sub_config_name(
    prefix: &str,
    config_dump: BTreeMap<ParamPath, SerializedParam>,
) -> BTreeMap<ParamPath, SerializedParam> {
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @TzahiTaub)

___
*[`crates/papyrus_config/src/lib.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NYM_jvFEEmNT5vNC7Z2:-NYMgIbJ-xJf3AT9qrl7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/75552f07dc309842cd47b8d9446236dd38083bce/crates/papyrus_config/src/lib.rs#L51)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is prefix required to be the same as the field name? If so this should be commented on.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/755#-NYMZoJJ-YQUBWX36-gb:-NYMge_nAmzaWkUzO7ep:b-dseoic) ([raw file](https://github.com/starkware-libs/papyrus/blob/75552f07dc309842cd47b8d9446236dd38083bce/crates/papyrus_config/src/lib.rs#L52)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think it's a little easier to read this way at the call sites.
</blockquote></details>

Because "prefix" is something that should be at the start?
IMO the main object should be the first.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yoavGrs)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755#-:-NYNXSst-jtAWny71Iti:bnfp4nl)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yoavGrs)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yoavGrs)

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 4 of 6 files at r5, 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
