### PR TITLE
refactor(): handle errors in tasks in main

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1035#-Nbokc_bCOPvyrpdrAS4:-Nbokc_c0z2LFgp5jRG5:bsqk2vk) ([raw file](https://github.com/starkware-libs/papyrus/blob/765782d07b8013e2adc390c1339c1680101ccbd1/crates/papyrus_node/src/main.rs#L55)):*
> ```XML
> 
>     tokio::select! {
>         Err(err)= server_handle_future => {
> ```

no need to flatten?



_Code quote:_
```XML
server_handle_future
```
___
*[`crates/papyrus_node/src/main.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1035#-NbojXkO7XBz5HiMK4ha:-NbojXkO7XBz5HiMK4hb:b-oyn7tt) ([raw file](https://github.com/starkware-libs/papyrus/blob/765782d07b8013e2adc390c1339c1680101ccbd1/crates/papyrus_node/src/main.rs#L138)):*
> ```XML
> 
> #[cfg(test)]
> mod main_test {
> ```

We don''t mix test and code at the same files (or have more than one module in a file)



_Code quote:_
```XML
mod main_test {
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1035#-NdotUIcELHyuFED7pep:-NdotUIcELHyuFED7peq:b-rtylha) (no related file):*
What is the reason for version updates?

___

**Comment by DvirYo-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What is the reason for version updates?
</blockquote></details>

Because I added a dependency to the workspace.

**Comment by DvirYo-starkware** [comment]
I advise you to review this from the start.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1035#-Nbokc_bCOPvyrpdrAS4:-NbrtUrWArcOYUb1fwMC:baqm6jw) ([raw file](https://github.com/starkware-libs/papyrus/blob/765782d07b8013e2adc390c1339c1680101ccbd1/crates/papyrus_node/src/main.rs#L55)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

no need to flatten?
</blockquote></details>

No. the errors we can get are only in one format.
___
*[`crates/papyrus_node/src/main.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1035#-NbojXkO7XBz5HiMK4ha:-Ndy0SPE9kUwoHLIJ1Vj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/765782d07b8013e2adc390c1339c1680101ccbd1/crates/papyrus_node/src/main.rs#L138)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We don''t mix test and code at the same files (or have more than one module in a file)
</blockquote></details>

Done.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1035)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
