### PR TITLE
Add set_workspace_root function.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
@DvirYo-starkware please describe the problem we found so Dan will have the context

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471#-:-NMP8ikT1wAq11VJuBZw:bw2a1ld)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/test_utils/src/lib.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMP9pvu0p4Xy-tg-Jqx:-NMP9pvu0p4Xy-tg-Jqy:b-mkzt3l) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ac61adfd40eb68f88f718c13783dd778717989/crates/test_utils/src/lib.rs#L37)):*
> ```XML
>         Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("../..").join(path);
>     env::set_current_dir(workspace_root).expect("Couldn't set working dir.");
> }
> ```

I think a better solution than setting the working dir inside this function will be to return the absolute path given a relative path (relative to the workspace root) and use the result in the calling function.

This way, you can use the function for more purposes.



_Code quote:_
```XML
// Sets the workspace root to be path from the project root.
pub fn set_workspace_root(path: &str) {
    let workspace_root =
        Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("../..").join(path);
    env::set_current_dir(workspace_root).expect("Couldn't set working dir.");
}
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @dan-starkware, and @yair-starkware)

___
*[`crates/test_utils/src/lib.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMP9pvu0p4Xy-tg-Jqx:-NMhPXGv3lRU_nrGh5NJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/22ac61adfd40eb68f88f718c13783dd778717989/crates/test_utils/src/lib.rs#L37)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think a better solution than setting the working dir inside this function will be to return the absolute path given a relative path (relative to the workspace root) and use the result in the calling function.

This way, you can use the function for more purposes.
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/papyrus_node/Cargo.toml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMj8TiQ8HK0AGH_g0IS:-NMj8TiQ8HK0AGH_g0IT:b-nl9b5w) ([raw file](https://github.com/starkware-libs/papyrus/blob/4022b603778114ee524297ec29d110b61a805340/crates/papyrus_node/Cargo.toml#L16)):*
> ```TOML
> papyrus_gateway = { path = "../papyrus_gateway" }
> papyrus_monitoring_gateway = { path = "../papyrus_monitoring_gateway" }
> test_utils={path="../test_utils"}
> ```

Move to dev-dependencies



_Code quote:_
```TOML
test_utils={path="../test_utils"}
```
___
*[`crates/test_utils/src/lib.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMj92lf-GkRD6VFRMLS:-NMj92lf-GkRD6VFRMLT:ba7br0e) ([raw file](https://github.com/starkware-libs/papyrus/blob/4022b603778114ee524297ec29d110b61a805340/crates/test_utils/src/lib.rs#L32)):*
> ```XML
> };
> 
> // Return the absolute  path from the project root.
> ```

Returns



_Code quote:_
```XML
Return
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471)* status: all files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMwrACbCrhOu8f8LB4-:-NMwrACbCrhOu8f8LB40:bfurbbq) (no related file):*

currently, we set the workspace root two directories upward [Path::new("../../")]. so if we had two tests in the same file that set the workspace root, it was four directories upward. the new function gives you the absolute path from the project root and solves this problem.

___
___
*[`crates/papyrus_node/Cargo.toml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMj8TiQ8HK0AGH_g0IS:-NMwqqMGCeRDLwH34Jv0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4022b603778114ee524297ec29d110b61a805340/crates/papyrus_node/Cargo.toml#L16)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move to dev-dependencies
</blockquote></details>

Done.
___
*[`crates/test_utils/src/lib.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMj92lf-GkRD6VFRMLS:-NMwr15F1xSboKEHgUyV:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/4022b603778114ee524297ec29d110b61a805340/crates/test_utils/src/lib.rs#L32)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Returns
</blockquote></details>

done

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/471#-:-NMxEraS4phVTBmcY9zT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @DvirYo-starkware)

___
*[`-- commits` line 8 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMxDTiE3sZv8TdBPkCs):*
Did you use pull instead of rebase?



_Code quote:_
```
New commits in r4 on 29/01/2023 at 11:25:
- 4a84a9c: Merge remote-tracking branch 'refs/remotes/origin/main' into dvir/add_set_workspace_root_function
```
___
*[`crates/papyrus_node/Cargo.toml` line 33 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/471#-NMxDvWb4O50vmTa94OG:-NMxDvWb4O50vmTa94OH:bma9dke) ([raw file](https://github.com/starkware-libs/papyrus/blob/fdd9f2e15c34c8c153494017ca49f74e7e717686/crates/papyrus_node/Cargo.toml#L33)):*
> ```TOML
> [dev-dependencies]
> tempfile = { version = "3.3.0" }
> test_utils={path="../test_utils"}
> ```

Add spaces (not blocking)



_Code quote:_
```TOML
test_utils={path="../test_utils"}
```

**Pull request merged**
