### PR TITLE
feat(network): update protobuf files

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSRND8ALbTLEx8q-sF:-NqSRND8ALbTLEx8q-sG:b4aa6nh) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/behaviour_test.rs#L116)):*
> ```XML
>     assert_eq!(behaviour.handle_session_finished_call_count, 0);
> 
>     // TODO(shahak): Investigate why this causes a failure and uncomment.
> ```

explain?
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSQYK-Bceze1x8iTLT:-NqSQYK-Bceze1x8iTLU:b-5ugn1) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/mod.rs#L245)):*
> ```XML
> 
> impl From<(BlockHeader, BlockSignature)> for protobuf::SignedBlockHeader {
>     fn from((header, signature): (BlockHeader, BlockSignature)) -> Self {
> ```

group all of the fields you didn't handle and put one todo
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSOUk04Y_bXHntqeJ5:-NqSOUk04Y_bXHntqeJ6:b-7h9nfu) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
> ```XML
>         signature: BlockSignature,
>     },
>     // TODO(shahak): Investigate why Fin isn't used.
> ```

what?
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSOS5UEgBdK5ByimKx:-NqSOS5UEgBdK5ByimKy:bvzmea9) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/db_executor/mod.rs#L144)):*
> ```XML
>                                 header,
>                                 // TODO: Get the real signature from the storage.
>                                 signature: BlockSignature::default(),
> ```

we can't merge it like that to main

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: 10 of 18 files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSRND8ALbTLEx8q-sF:-NqSUI2x7up_2fO1Gwtz:b-2lj3hr) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/behaviour_test.rs#L116)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

explain?
</blockquote></details>

This is a new logic I tried to add and it failed. If you want I can erase this from this PR and move it to my side notes
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSQYK-Bceze1x8iTLT:-NqSUWMuB9mde7BbH2Qf:b36cbwr) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/mod.rs#L245)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

group all of the fields you didn't handle and put one todo
</blockquote></details>

I prefer this way. It allows us to handle each field separately easily
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSOUk04Y_bXHntqeJ5:-NqSUb644gipSD5lItRR:b-801k9u) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

what?
</blockquote></details>

It should work without allow(dead_code), but I didn't want to extend the scope of this PR more
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSOS5UEgBdK5ByimKx:-NqSfdOC1wewGhdcgIZf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/db_executor/mod.rs#L144)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

we can't merge it like that to main
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: 10 of 18 files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSOUk04Y_bXHntqeJ5:-NqWeIJL7Zst6VlUCEWh:b1r87nl) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It should work without allow(dead_code), but I didn't want to extend the scope of this PR more
</blockquote></details>

NVM, it does work
Fixed

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSQYK-Bceze1x8iTLT:-NqbH9koCjtSrEg51kk_:bqmudnx) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/mod.rs#L245)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I prefer this way. It allows us to handle each field separately easily
</blockquote></details>

you can still handle them separately just move them when you add the handling.
the way it is now is very un-intuitive.
removing the block from this but I'd really prefer it to not stay like this
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqbHy417IfYesQuppcQ:-NqbHy417IfYesQuppcR:b5x94aa) ([raw file](https://github.com/starkware-libs/papyrus/blob/6d00cbecbfcc356da255c97a236583bfae252f44/crates/papyrus_network/src/network_manager/mod.rs#L121)):*
> ```XML
>                         );
>                     }
>                 } else {
> ```

remove the else {}
surprised clippy didn't complain

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSQYK-Bceze1x8iTLT:-NqbJWMW8TgsBHUVoVPa:b-1mazut) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/mod.rs#L245)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

you can still handle them separately just move them when you add the handling.
the way it is now is very un-intuitive.
removing the block from this but I'd really prefer it to not stay like this
</blockquote></details>

I prefer the current way because it removes the chance that the person who fixes this will forget to erase the TODO
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqbHy417IfYesQuppcQ:-NqbIaci20kqq0tV-mUe:b9uk01x) ([raw file](https://github.com/starkware-libs/papyrus/blob/6d00cbecbfcc356da255c97a236583bfae252f44/crates/papyrus_network/src/network_manager/mod.rs#L121)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

remove the else {}
surprised clippy didn't complain
</blockquote></details>

clippy is disabled (see #1694)
I've run it locally and found some more errors

**Review by nagmo-starkware — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1698#-NqSRND8ALbTLEx8q-sF:-Nqc3bT_Dg45g712n-rk:b233jmk) ([raw file](https://github.com/starkware-libs/papyrus/blob/80a2368710ad9050b3c8585978bc37f330b340f1/crates/papyrus_network/src/block_headers/behaviour_test.rs#L116)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is a new logic I tried to add and it failed. If you want I can erase this from this PR and move it to my side notes
</blockquote></details>

please do

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
