### PR TITLE
documentation and improvements to StateReader

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/688)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #688** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/688" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/688?utm_source=stack-comment).

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_storage/src/state/mod.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6SVEp-VNnMXCbaRn4:-NW6SVEp-VNnMXCbaRn5:b-okevzj) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L126)):*
> ```XML
>     /// # Errors
>     /// Returns [`StorageError`] if there was an error opening the tables.
>     fn new(txn: &'env StorageTxn<'env, Mode>) -> StorageResult<Self> {
> ```

This and the following function aren’t public, so maybe we shouldn’t use this kind of documentation.
I think it is nice to have the same document format for all functions.
Wait for Dan.

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_storage/src/state/mod.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6TLXO4tB4cdkGpUrj:-NW6TLXO4tB4cdkGpUrk:b-fc524f) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L246)):*
> ```XML
> 
>     /// Returns the storage at a given state number for a given contract and key.
>     /// If no value is stored at the given state number, returns [`StarkFelt`]::default.
> ```

I think this is starknet definition of the key not being stored. I mean, the value of any key is the default value unless it is changed. So, in this case, we return the value of the key that starknet defines. If this is the case, we shouldn’t document that, check this with someone from starknet. 
Wait for Dan.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/688)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7QsaJCBXnmQ9zzCQE:-NW7QsaJCBXnmQ9zzCQF:b-gvrva9) (no related file):*
Did you create the doc and check it?

___
___
*[`crates/papyrus_storage/src/state/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7Q1Hn-PYXbfhe6sTm:-NW7Q1Hn-PYXbfhe6sTn:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L117)):*
> ```XML
> #[allow(dead_code)]
> impl<'env, Mode: TransactionKind> StateReader<'env, Mode> {
>     /// Create a new state reader from a storage transaction.
> ```





_Suggestion:_
```XML
Creates
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6SVEp-VNnMXCbaRn4:-NW7QpZpAmnwgumu6jVU:b5rmnp8) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L126)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This and the following function aren’t public, so maybe we shouldn’t use this kind of documentation.
I think it is nice to have the same document format for all functions.
Wait for Dan.
</blockquote></details>

Let's discuss f2f
___
*[`crates/papyrus_storage/src/state/mod.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7R95_DY9yC1Z6i1eF:-NW7R95_DY9yC1Z6i1eG:b-bv0pxr) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L152)):*
> ```XML
>     ///
>     /// **Note:** None means that the class in deployed_contracts table was not replaced before
>     /// state_number, it could still be declared before state_number - need to check against the
> ```

Regardless of this PR. Do you think we should unify these tables?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7fEK57mAN-0khWtx0:-NW7fEK57mAN-0khWtx1:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L245)):*
> ```XML
>     }
> 
>     /// Returns the storage at a given state number for a given contract and key.
> ```

Consider



_Suggestion:_
```XML
storage value at
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6TLXO4tB4cdkGpUrj:-NW7fTov7_Op9a-hZL-z:b-8xk45m) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L246)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think this is starknet definition of the key not being stored. I mean, the value of any key is the default value unless it is changed. So, in this case, we return the value of the key that starknet defines. If this is the case, we shouldn’t document that, check this with someone from starknet. 
Wait for Dan.
</blockquote></details>

How about writing a note that all keys have a default value of...?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7fnsI9-WYagpmtn0x:-NW7fnsI9-WYagpmtn0y:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L318)):*
> ```XML
>     }
> 
>     /// Returns the block number for a given class hash (the block it was defined in).
> ```

Consider



_Suggestion:_
```XML
in which is was defined
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/688)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6SVEp-VNnMXCbaRn4:-NWC-nou8KvjR97zGUw0:b-c0tzas) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L126)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Let's discuss f2f
</blockquote></details>

@DvirYo-starkware I didn't understand your comment. 
I'll say that there's no general guideline for documentation of private functions in rust. I do think that it's better to error on the side of over documentation and also that there is some benefit to documenting private code for the other internal developers of the system, though it shouldn't be mandatory.
having say that, do you think it is good or bad to document private functions?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW7R95_DY9yC1Z6i1eF:-NWC17Bf4HKS3MZmZNsK:b-mgwd8q) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L152)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Regardless of this PR. Do you think we should unify these tables?
</blockquote></details>

do you mean replaced & deployed tables? I think it depends if we want to know the value before replacing..
___
*[`crates/papyrus_storage/src/state/mod.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/688#-NW6TLXO4tB4cdkGpUrj:-NWC1gGA0MUhcoJEUge4:b-mjw9dx) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8429ac5cef6a5a42b954bdfbda471a761ba3516/crates/papyrus_storage/src/state/mod.rs#L246)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

How about writing a note that all keys have a default value of...?
</blockquote></details>

I don't agree with both comments:
1. the same way I documented the return value for every other function (most return `None`) I documented here that it returns the default.
2. I don't think we should say what is the default value in the comment since it might change. Instead, I linked to the `StarkFelt` object so the reader of the docs could just click it and see the documentation for the object from the `starknet_api` library.

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/688#-:-NWCgd8h1rt6YYsIEBQ9:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

**Pull request merged**
