### PR TITLE
feat(monitoring): update the grafana

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-Nehrc2_6DtUaWVe2vs3:-Nehrc2a5Zp7L8tED350:b7dggj) (no related file):*
Block Header Percentage ==> Block Header %
(replace all titles)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-NehrpL93clmdh-8Tnx1:-NehrpL93clmdh-8Tnx2:b-fb46vp) (no related file):*
For the Base Layer metrics, I think that the title should be clearer.
Maybe something like "L1 Block Number" ??
Also, I'm not sure if we want to show it in the same list. It's a bit confusing. It makes it looks like it's not fully sync-ed, but it is.

___

**Review by alon-dotan-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-:-NeiuOy61W0fmzdrifH5:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @OriStarkware)

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-NelFVSZ-0t2zDPL7Z6G:-NelFVS_6zlyl_-F4zl5:b3c9qk7) (no related file):*
Another small change:
Compiled Class Diff (CASM) ==> Compiled Class (CASM) Diff
Compiled Class % (CASM) ==> Compiled Class (CASM) %

___

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-NelGSzQCI8zWTEqW6Z_:-NelGSzQCI8zWTEqW6Za:b5g5zph) (no related file):*
Maybe put some more colors in the Sync panel.
Give a different color to the first line and to the second line to separate them from the remaining lines.

___

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-NelFVSZ-0t2zDPL7Z6G:-NemLNYB0rP1p9xh9x6f:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Another small change:
Compiled Class Diff (CASM) ==> Compiled Class (CASM) Diff
Compiled Class % (CASM) ==> Compiled Class (CASM) %
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-NelGSzQCI8zWTEqW6Z_:-NemMPIGDLXOh5kG_WW4:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Maybe put some more colors in the Sync panel.
Give a different color to the first line and to the second line to separate them from the remaining lines.
</blockquote></details>

Done.

___

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1195#-:-NemVMo43vTm5wOUeQH4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
