### PR TITLE
fix(network): fix network error handling in main

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1742)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* **#1742** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1742?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1742?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1742#-:-Nr_KJ_jEfcpSJ-Mfsvs:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1742#-Nr_K4qa-xW4Rogl55fk:-Nr_K4qa-xW4Rogl55fl:b-bkb8tl) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ec6d8eef4bf8727f70c5789a4d85a5312a50078/crates/papyrus_node/src/main.rs#L164)):*
> ```XML
> }
> 
> type NetworkRunReturn =
> ```

IMO this type alias is unnecessary, but it's style so I leave it up to you
___
*[`crates/papyrus_node/src/main.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1742#-Nr_KCg_4U-upE4rItP1:-Nr_KCg_4U-upE4rItP2:b8eski0) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ec6d8eef4bf8727f70c5789a4d85a5312a50078/crates/papyrus_node/src/main.rs#L165)):*
> ```XML
> 
> type NetworkRunReturn =
>     (BoxFuture<'static, Result<(), NetworkError>>, Option<(Sender<Query>, ResponseReceivers)>);
> ```

Add TODO to make these non option when we make network non option

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1742)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1742)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1742#-Nr_K4qa-xW4Rogl55fk:-Nr_O31-BvzfxMnBLhM8:by5ybf7) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ec6d8eef4bf8727f70c5789a4d85a5312a50078/crates/papyrus_node/src/main.rs#L164)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's clippy's fault :)
</blockquote></details>

Consider using #[allow
___
*[`crates/papyrus_node/src/main.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1742#-Nr_KCg_4U-upE4rItP1:-Nr_O6evCfN_tE9UfuAV:b-kc52w9) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ec6d8eef4bf8727f70c5789a4d85a5312a50078/crates/papyrus_node/src/main.rs#L165)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it'll still be optional.. it's because the network can work without the p2psync
</blockquote></details>

The P2P sync doesn't appear anywhere in this function. This function won't know if p2p sync is on or off

**Pull request merged**
