### PR TITLE
feat(execution): pending support for ExecutionStateReader::get_nonce

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1420)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1420)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1420#-NjNeGiFD3VSh_bF_psK:-NjNeGiFD3VSh_bF_psL:b-jyb4vc) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6334b2457988c5718ffc7b8e0f0d0d8f4a8a057/crates/papyrus_execution/src/state_reader.rs#L60)):*
> ```XML
>         )
>         .map_err(storage_err_to_state_err)
>         .map(|maybe_nonce| maybe_nonce.unwrap_or_default())
> ```

Why not 
```
map_err(storage_err_to_state_err)?
.unwrap_or_default())
```



_Code quote:_
```XML
        .map_err(storage_err_to_state_err)
        .map(|maybe_nonce| maybe_nonce.unwrap_or_default())
```

**Comment by ShahakShama** [comment]
*[`crates/papyrus_execution/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1420#-NjNeGiFD3VSh_bF_psK:-NjNfQMf0pxkpwNyp5Nc:bi7r52r) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6334b2457988c5718ffc7b8e0f0d0d8f4a8a057/crates/papyrus_execution/src/state_reader.rs#L60)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There's a ? operator
</blockquote></details>

Yes, but then I have to return Ok(....?.unwrap_or_default)
Do you think it's cleaner?

**Comment by yair-starkware** [comment]
*[`crates/papyrus_execution/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1420#-NjNeGiFD3VSh_bF_psK:-NjNfgP53cH31AhMQPGH:bb6w75z) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6334b2457988c5718ffc7b8e0f0d0d8f4a8a057/crates/papyrus_execution/src/state_reader.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, but then I have to return Ok(....?.unwrap_or_default)
Do you think it's cleaner?
</blockquote></details>

I do

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1420)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1420#-NjNeGiFD3VSh_bF_psK:-NjNg31O-W6dZhuuBZIn:b-886gsx) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6334b2457988c5718ffc7b8e0f0d0d8f4a8a057/crates/papyrus_execution/src/state_reader.rs#L60)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I do
</blockquote></details>

Fixed

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1420#-:-NjNgC7w3vAYDr71Ii4z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
