### PR TITLE
feat(protobuf): add one struct for all sync responses types

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2070)

### CODE REVIEW

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2070)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2070)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2070#-NzMYEbC0VBEyyChxsLF:-NzMYEbC0VBEyyChxsLG:b-hlpeee) ([raw file](https://github.com/starkware-libs/papyrus/blob/f32128e605992decc391a8a02c83d2597ca68c45/crates/papyrus_protobuf/src/sync.rs#L38)):*
> ```XML
> 
> #[derive(Debug, Clone, PartialEq, Eq)]
> pub struct DataOrFin<T>(pub Option<T>);
> ```

Why do this? I don't see a generic implementation for DataOrFin that would make this save code for each response. You are replacing descriptive names with a generic name. If you don't like those Response types what about just using the option raw?
 Examples:
```
impl TryFrom<protobuf::BlockHeadersResponse> for DataOrFin<SignedBlockHeader> {
->
impl TryFrom<protobuf::BlockHeadersResponse> for Option<SignedBlockHeader> {
```

```
    let res_data = DataOrFin::<SignedBlockHeader>::try_from(bytes_data).unwrap();
->
    let res_data: Option<SignedBlockHeader> = TryFrom::try_from(bytes_data).unwrap();
```



_Code quote:_
```XML
pub struct DataOrFin<T>(pub Option<T>);
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2070)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2070#-NzMYEbC0VBEyyChxsLF:-NzMmIt7Dp84u8SSQ1zX:b-1062fp) ([raw file](https://github.com/starkware-libs/papyrus/blob/f32128e605992decc391a8a02c83d2597ca68c45/crates/papyrus_protobuf/src/sync.rs#L38)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why do this? I don't see a generic implementation for DataOrFin that would make this save code for each response. You are replacing descriptive names with a generic name. If you don't like those Response types what about just using the option raw?
 Examples:
```
impl TryFrom<protobuf::BlockHeadersResponse> for DataOrFin<SignedBlockHeader> {
->
impl TryFrom<protobuf::BlockHeadersResponse> for Option<SignedBlockHeader> {
```

```
    let res_data = DataOrFin::<SignedBlockHeader>::try_from(bytes_data).unwrap();
->
    let res_data: Option<SignedBlockHeader> = TryFrom::try_from(bytes_data).unwrap();
```
</blockquote></details>

The goal is that in the sync logic we can have a function that receives a Receiver<DataOrFin<T>> and reads the data of the blocks from it

**Review by matan-starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2070)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2070#-NzMYEbC0VBEyyChxsLF:-NzN1om90wZSihDMmdm_:bfxnsx7) ([raw file](https://github.com/starkware-libs/papyrus/blob/f32128e605992decc391a8a02c83d2597ca68c45/crates/papyrus_protobuf/src/sync.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The goal is that in the sync logic we can have a function that receives a Receiver<DataOrFin<T>> and reads the data of the blocks from it
</blockquote></details>

Ok so in the future we will take advantage of having a generic. SGTM

**Pull request merged**
