### PR TITLE
feat(sync): add state diff sync to p2p sync

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/header.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM2GIg2uWipFxRDyVV:-NtM2GIg2uWipFxRDyVW:bt4ut6) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/header.rs#L43)):*
> ```XML
>     const DATA_TYPE: DataType = DataType::SignedBlockHeader;
>     const BLOCK_NUMBER_LIMIT: BlockNumberLimit = BlockNumberLimit::Unlimited;
>     const SHOULD_LOG_ADDED_BLOCK: bool = false;
> ```

I think it should be set to true
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM2wM-DNSm9KhSBg-C:-NtM2wM-DNSm9KhSBg-D:b-m00hw6) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L69)):*
> ```XML
>             num_headers_per_query: 10000,
>             // State diffs are split into multiple messages, so big queries can lead to a lot of
>             // messages in the network buffers.
> ```

did you test it to be the case? or is it your estimation?
the network buffer is configurable so normally the application side is doing what makes most sense applicatively and if needed changes the default network buffer size. (usually it's not needed since it is dynamically sized)
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM4ZEM3bnEQgheHkhi:-NtM4ZEM3bnEQgheHkhj:bcg6jds) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L102)):*
> ```XML
>         "Received an empty state diff part from the network (this is a potential DDoS vector)."
>     )]
>     EmptyStateDiffPart,
> ```

maybe we should just fail to convert it in the converter?
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM7RY_2AopONNg47ze:-NtM7RY_2AopONNg47zf:b-a0m9wn) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L110)):*
> ```XML
>          {missing_field}"
>     )]
>     OldHeaderInStorage { block_number: BlockNumber, missing_field: &'static str },
> ```

that means we need to re-sync from genesis? please add it to the error message to make it more helpful
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM7tjI8wb3Qt59kxLl:-NtM7tjI8wb3Qt59kxLm:b76hxty) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L25)):*
> ```XML
>     ) -> Result<(), StorageError> {
>         // TODO(shahak): Add a way to write ThinStateDiff to the storage.
>         let state_diff = StateDiff {
> ```

why not use a conversion function? (From/ TryFrom)
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM8jiU3pNhHXOYgFyM:-NtM8jiU3pNhHXOYgFyN:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L74)):*
> ```XML
>             let mut prev_result_len = 0;
>             let mut result_len = 0;
>             let target_len = storage_reader
> ```





_Suggestion:_
```XML
num_expected_state_diffs
```
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM8S-o4ttIYidcWKnt:-NtM8S-o4ttIYidcWKnu:b-dpywt0) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L96)):*
> ```XML
>                         return Ok(None);
>                     } else {
>                         return Err(P2PSyncError::WrongStateDiffLength {
> ```

I don't understand this error. what's possible length?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/header.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM2GIg2uWipFxRDyVV:-NtQlVm287kfAl4gkwom:b2kse53) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/header.rs#L43)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think it should be set to true
</blockquote></details>

I've set it to true everywhere and removed this variable
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM2wM-DNSm9KhSBg-C:-NtQjFDG4d8yw45I_VES:b-82d5yn) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L69)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

did you test it to be the case? or is it your estimation?
the network buffer is configurable so normally the application side is doing what makes most sense applicatively and if needed changes the default network buffer size. (usually it's not needed since it is dynamically sized)
</blockquote></details>

Yes, I initially set it to 1000 and the node failed so I tuned it down to 100. I can instead increase the header buffer limit from 100,000 to 1,000,000 if you prefer
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM4ZEM3bnEQgheHkhi:-NtQkZPXDH0e16ZdWehi:bsyayjb) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L102)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

maybe we should just fail to convert it in the converter?
</blockquote></details>

I'm not sure which is better so I've added a TODO to consider
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM7RY_2AopONNg47ze:-NtQl-8C8YU2j6vXXhY6:b-kx17j9) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L110)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

that means we need to re-sync from genesis? please add it to the error message to make it more helpful
</blockquote></details>

It means we need to re-sync from the given block number. Added to the error message
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM7tjI8wb3Qt59kxLl:-NtQk4IrAMvXTurZaVN2:b-v23iw0) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L25)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why not use a conversion function? (From/ TryFrom)
</blockquote></details>

It's a hack. I don't want other people to accidentally use it. In general you can't convert ThinStateDiff to StateDiff
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM8jiU3pNhHXOYgFyM:-NtQl8m55ZkiF-A_XJPP:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L74)):*
> ```XML
>             let mut prev_result_len = 0;
>             let mut result_len = 0;
>             let target_len = storage_reader
> ```

Done
___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM8S-o4ttIYidcWKnt:-NtQolVe1ii8p_WLLa6z:b-23viaj) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L96)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't understand this error. what's possible length?
</blockquote></details>

The length that the block's state diff could be

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM7RY_2AopONNg47ze:-NtQpqhD8IZw9WiPZ54k:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/lib.rs#L110)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It means we need to re-sync from the given block number. Added to the error message
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_p2p_sync/src/state_diff.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-NtM8S-o4ttIYidcWKnt:-NtRFtUk0SWXbKgG4wBY:b4xbspr) ([raw file](https://github.com/starkware-libs/papyrus/blob/af3dceafbaebb1416867b931731ac12f94b31c00/crates/papyrus_p2p_sync/src/state_diff.rs#L96)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

f2f
</blockquote></details>

I still think it's useful information. Improved the message

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r2, 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1812#-:-NtoXyb-5YnP8Flx0k7z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
