### PR TITLE
chore: bump blockifier version

### PR DESCRIPTION
**Pull request by dan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/resources/versioned_constants_13_0.json` line 144 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiOfB-9eRHGTemgNl:-O1BiOfB-9eRHGTemgNm:bjhapmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/resources/versioned_constants_13_0.json#L144)):*
> ```JSON
>             "range_check_gas_cost": 0,
>             "syscall_base_gas_cost": 0
>         },
> ```

@ilyalesokhin-starkware ?



_Code quote:_
```JSON
        "sha256_process_block_gas_cost": {
            "step_gas_cost": 0,
            "range_check_gas_cost": 0,
            "syscall_base_gas_cost": 0
        },
```
___
*[`crates/papyrus_execution/resources/versioned_constants_13_0.json` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiPxeAZmEK3s2xm9A:-O1BiPxeAZmEK3s2xm9B:bjhapmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/resources/versioned_constants_13_0.json#L251)):*
> ```JSON
>                 "n_memory_holes": 0,
>                 "n_steps": 0
>             },
> ```

@ilyalesokhin-starkware ?



_Code quote:_
```JSON
            "Sha256ProcessBlock": {
                "builtin_instance_counter": {},
                "n_memory_holes": 0,
                "n_steps": 0
            },
```
___
*[`crates/papyrus_execution/resources/versioned_constants_13_1.json` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiGIX4E5PqKisVeDB:-O1BiGIX4E5PqKisVeDC:bd8zgio) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/resources/versioned_constants_13_1.json#L26)):*
> ```JSON
>         ]
>     },
>     "max_recursion_depth": 50,
> ```

please sort this in a preliminary PR... impossible to review like this
___
*[`crates/papyrus_execution/src/execution_test.rs` line 792 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiUcSBSKX0piYfuJL:-O1BiUcT5v4XTQyg0Upl:bv8rz8b) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/execution_test.rs#L792)):*
> ```XML
>          (contract address: {storage_address_felt:#064x}, class hash: {class_hash_felt:#064x}, \
>          selector: UNKNOWN):\n{child}\n"
>     );
> ```

consider this style (non-blocking)



_Suggestion:_
```XML
    let class_hash = class_hash!("0x321");
    let expected = format!(
        "Contract constructor execution has failed:\n0: Error in the contract class constructor \
         (contract address: {:#064x}, class hash: {:#064x}, \
         selector: UNKNOWN):\n{child}\n",
         storage_address.0.key(), class_hash.0
    );
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1Bhl7e3yQW6pndFqC1:-O1Bhl7e3yQW6pndFqC2:b-w6hm28) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/execution_test.rs#L790)):*
> ```XML
>     let expected = format!(
>         "Contract constructor execution has failed:\n0: Error in the contract class constructor \
>          (contract address: {storage_address_felt:#064x}, class hash: {class_hash_felt:#064x}, \
> ```

Did something change in the format? It needs to be the same in all nodes
___
*[`crates/papyrus_execution/src/lib.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiIXk3n0-WCnmqa-l:-O1BiIXk3n0-WCnmqa-m:b-20wdvz) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/lib.rs#L388)):*
> ```XML
>     let next_block_number = block_context.block_info().block_number;
> 
>     pre_process_block(cached_state, ten_blocks_ago, next_block_number)?;
> ```

What changed here? IIRC pre_process_block should not be separated from the BlockContext creation so we won't miss crucial steps



_Code quote:_
```XML
    let block_context = BlockContext::new(
        block_info,
        chain_info,
        versioned_constants.clone(),
        BouncerConfig::max(),
    );
    let next_block_number = block_context.block_info().block_number;

    pre_process_block(cached_state, ten_blocks_ago, next_block_number)?;
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/resources/versioned_constants_13_1.json` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiGIX4E5PqKisVeDB:-O1C0K-IAx79aDY7NTxV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/resources/versioned_constants_13_1.json#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please sort this in a preliminary PR... impossible to review like this
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/execution_test.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1Bhl7e3yQW6pndFqC1:-O1C0MTLCqqOn8gE5eW8:bd89lpe) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/execution_test.rs#L790)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Did something change in the format? It needs to be the same in all nodes
</blockquote></details>

@dorimedini-starkware 
___
*[`crates/papyrus_execution/src/execution_test.rs` line 792 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiUcSBSKX0piYfuJL:-O1C-To11PKWDuRf7YGA:bkf6n0q) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/execution_test.rs#L792)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider this style (non-blocking)
</blockquote></details>

Sure, thanks!
___
*[`crates/papyrus_execution/src/lib.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiIXk3n0-WCnmqa-l:-O1C0XIo1VCf1o1qgPWe:bd89lpe) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/lib.rs#L388)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What changed here? IIRC pre_process_block should not be separated from the BlockContext creation so we won't miss crucial steps
</blockquote></details>

@dorimedini-starkware

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @yair-starkware, and @Yoni-Starkware)

___
*[`crates/papyrus_execution/resources/versioned_constants_13_1.json` line 180 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1C1BbXECW0z9VQfBwT:-O1C1BbXECW0z9VQfBwU:b4nkyol) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6f79c4f11283929fd189f7796353dcd38eb40e0/crates/papyrus_execution/resources/versioned_constants_13_1.json#L180)):*
> ```JSON
>             "n_memory_holes": 0,
>             "n_steps": 0
>         },
> ```

why do we see changes in these values? prices should change, this is the 0.13.1 constants file



_Code quote:_
```JSON
        "compute_os_kzg_commitment_info": {
            "builtin_instance_counter": {},
            "n_memory_holes": 0,
            "n_steps": 0
        },
```
___
*[`crates/papyrus_execution/src/execution_test.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1Bhl7e3yQW6pndFqC1:-O1C1KptEBmC9DYAH50B:b89sbhj) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/execution_test.rs#L790)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware
</blockquote></details>

stack trace output format is defined and tested in the blockifier; the formatting has changed since 0.13.1
___
*[`crates/papyrus_execution/src/lib.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiIXk3n0-WCnmqa-l:-O1C1XlYAtDvgh3tYVGQ:bt66krh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/lib.rs#L388)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware
</blockquote></details>

they were separated. sync with @Yoni-Starkware ?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @yair-starkware, and @Yoni-Starkware)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_execution/resources/versioned_constants_13_1.json` line 180 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1C1BbXECW0z9VQfBwT:-O1CWRyODYt5XJPsbwTw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6f79c4f11283929fd189f7796353dcd38eb40e0/crates/papyrus_execution/resources/versioned_constants_13_1.json#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do we see changes in these values? prices should change, this is the 0.13.1 constants file
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-O1BiIXk3n0-WCnmqa-l:-O1CWQ1S7CMMH7mNfGfF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d3fcc01b0e867228a6ebfa742c8fa66ca95345e/crates/papyrus_execution/src/lib.rs#L388)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

they were separated. sync with @Yoni-Starkware ?
</blockquote></details>

Done.

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195#-:-O1CYKNz0PT4kyPUajrT:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
