### PR TITLE
Add gateway request with two arguments.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)* status: all files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVEGs6HEW-uFwgqKT:-NPSVEGs6HEW-uFwgqKU:b-rzlc6c) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L1)):*
> ```XML
> use std::str::SplitWhitespace;
> ```

Please add documentation. 
___
*[`crates/papyrus_load_test/src/create_request.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVzAv-1tKJ6a1nChD:-NPSVzAv-1tKJ6a1nChE:bs818di) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L7)):*
> ```XML
> use crate::jsonrpc_request;
> 
> struct ArgsIter<'a> {
> ```

Please order code by importance to the reader. Specifically, move the iterator details below the requests.



_Code quote:_
```XML
struct ArgsIter<'a> {
```
___
*[`crates/papyrus_load_test/src/create_request.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVlZG1gM4CFkWO2b3:-NPSVlZG1gM4CFkWO2b4:b-n1vwfg) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L26)):*
> ```XML
> 
> pub fn get_transaction_by_block_id_and_index_by_hash(args: &str) -> jsonVal {
>     let mut iter = ArgsIter::new(args);
> ```

Please rename, maybe `arg_iter`.



_Code quote:_
```XML
iter
```
___
*[`crates/papyrus_load_test/src/create_request.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSYDnW-SCAAh7jSGO0:-NPSYDnW-SCAAh7jSGO1:b4vnky2) ([raw file](https://github.com/starkware-libs/papyrus/blob/2171201b30ea0d527f2160d2e7e4bddbe84e5441/crates/papyrus_load_test/src/create_request.rs#L29)):*
> ```XML
>     jsonrpc_request(
>         "starknet_getTransactionByBlockIdAndIndex",
>         json!([ {"block_hash": iter.next_str()},  iter.next_u64()  ]),
> ```

1. Are you sure about the evaluation order?
I think it is better to consume sequentially
```
block_hash = iter.next_str()
transaction_index = iter.next_u64()
```
and then use these instead.

2. Shouldn't the transaction index be part of the parameter mapping?



_Code quote:_
```XML
json!([ {"block_hash": iter.next_str()},  iter.next_u64()  ]),
```
___
*[`crates/papyrus_load_test/src/resources/block_hash_&_transaction_index.txt` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSUh1jAo0Wk1USwg3W:-NPSUh1k6w0L08Zh15_e:b-47wder) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/resources/block_hash_%26_transaction_index.txt#L1)):*
> ```help
> 0x47c3637b57c2b079b93c61539950c17e868a28f46cdef28f88521067f21e943 0
> ```

Please refrain from using `&` in file names.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVEGs6HEW-uFwgqKT:-NPSaM8mEpoUeSDy0oHd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add documentation. 
</blockquote></details>

Done.
___
*[`crates/papyrus_load_test/src/create_request.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVzAv-1tKJ6a1nChD:-NPSaNGMDVw6xn168y6S:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L7)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please order code by importance to the reader. Specifically, move the iterator details below the requests.
</blockquote></details>

Done.
___
*[`crates/papyrus_load_test/src/create_request.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSVlZG1gM4CFkWO2b3:-NPSaO4uCTORSFHi8qhc:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/create_request.rs#L26)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please rename, maybe `arg_iter`.
</blockquote></details>

Done.
___
*[`crates/papyrus_load_test/src/create_request.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSYDnW-SCAAh7jSGO0:-NPSbiBI5Rn0Z4IRAlZv:by8wbc) ([raw file](https://github.com/starkware-libs/papyrus/blob/2171201b30ea0d527f2160d2e7e4bddbe84e5441/crates/papyrus_load_test/src/create_request.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

1. Are you sure about the evaluation order?
I think it is better to consume sequentially
```
block_hash = iter.next_str()
transaction_index = iter.next_u64()
```
and then use these instead.

2. Shouldn't the transaction index be part of the parameter mapping?
</blockquote></details>

first: done.
second: no. this is the form of the parameters in a json request.
___
*[`crates/papyrus_load_test/src/resources/block_hash_&_transaction_index.txt` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSUh1jAo0Wk1USwg3W:-NPSaa4XAiXfdfQsGcBb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e157ed8933617ea1edb675cdd61891dc8e36b32b/crates/papyrus_load_test/src/resources/block_hash_%26_transaction_index.txt#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please refrain from using `&` in file names.
</blockquote></details>

Done.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSfMqw6KShMTThaDXU:-NPSfMqw6KShMTThaDXV:b-9zawho) ([raw file](https://github.com/starkware-libs/papyrus/blob/1369dfc0f2339eb7ed98ef4e55c0536ee8a6a406/crates/papyrus_load_test/src/create_request.rs#L39)):*
> ```XML
> 
>     // Returns the next argument as &str.
>     fn next_str(&mut self) -> String {
> ```

Replace &str to String to enable getting the values outside the macro. problem with borrowing as mutable more than once.
json!([{ "block_hash": block_hash }, transaction_index]),
instead of:
json!([{ "block_hash": iter.next_str() }, iter.next_u64()]),

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/530#-NPSYDnW-SCAAh7jSGO0:-NPSj4Kf-RkIkRzrX1hD:beornic) ([raw file](https://github.com/starkware-libs/papyrus/blob/9dc73efec61badf72d7800993fe61b432221c7f9/crates/papyrus_load_test/src/create_request.rs#L29)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

first: done.
second: no. this is the form of the parameters in a json request.
</blockquote></details>

Let's talk f2f

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/530)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
