### PR TITLE
feat: dump_declared_classes can dump for a specific block range

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/dump_declared_classes/src/main.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-a0DV-JWp_rEazS90:-Nh-a0DV-JWp_rEazS91:b-qixslp) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L11)):*
> ```XML
> /// The file path can be passed as an argument, otherwise it will be dumped to
> /// "dump_declared_classes.json".
> /// A starting block and an ending block can also be passed as optional arguments, otherwise the
> ```

A start block and an end block



_Code quote:_
```XML
A starting block and an ending block
```
___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-aOJMC9DAmZlRQX6y:-Nh-aOJMC9DAmZlRQX6z:bko4qot) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L14)):*
> ```XML
> /// entire table will be dumped.
> fn main() {
>     let matches = Command::new("Dump declared classes")
> ```

move the part of parsing the command-line parameters to a separate function.
___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-absB5kAUy6cjbzkn:-Nh-absB5kAUy6cjbzko:b-marw3q) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L14)):*
> ```XML
> /// entire table will be dumped.
> fn main() {
>     let matches = Command::new("Dump declared classes")
> ```

Add a validation that start_block value exists iff end_block value exists.
And validate that stark_block<=end_block.
(Is it possible to validate that end_block < last block ?)
___
*[`crates/dump_declared_classes/src/main.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-cy049ij4TDQGxqvL:-Nh-cy049ij4TDQGxqvM:b-lxt5aa) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L37)):*
> ```XML
> 
>     let file_path = matches.get_one::<String>("file_path").unwrap().as_str();
>     let res: StorageResult<()> =
> ```

Maybe call dump_declared_classes_table_to_file() function for both cases (with / without block-range) and inside it separate it to 2 functions (instead of doing it here).

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/dump_declared_classes/src/main.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-a0DV-JWp_rEazS90:-Nh1N4ba9O3xg8Cj8UQS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L11)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

A start block and an end block
</blockquote></details>

Done.
___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-absB5kAUy6cjbzkn:-Nh1N6KK68_RTJgGWlDi:b-vej3ju) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L14)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Add a validation that start_block value exists iff end_block value exists.
And validate that stark_block<=end_block.
(Is it possible to validate that end_block < last block ?)
</blockquote></details>

added now that both start_block and end_block are required.
added a check that start_block< end_block
also possible to check end\_block < last block, done
___
*[`crates/dump_declared_classes/src/main.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-cy049ij4TDQGxqvL:-Nh1NV5k2R7D_Bt5E_Zw:b8o6ucw) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L37)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Maybe call dump_declared_classes_table_to_file() function for both cases (with / without block-range) and inside it separate it to 2 functions (instead of doing it here).
</blockquote></details>

not relevant anymore

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)* status: all files reviewed, 8 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/dump_declared_classes/src/main.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1eLiQDFl8ZCOGAzUc:-Nh1eLiQDFl8ZCOGAzUd:b-8y9qnx) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L10)):*
> ```XML
> /// The start_block and end_block arguments are mandatory and define the block range to dump,
> /// start_block is inclusive and end_block is exclusive. The file_path is an optional parameter,
> /// otherwise the data will be dumped to "dump_declared_classes.json".
> ```

Maybe move this part of the documentation to fn get_cli_params()



_Code quote:_
```XML
/// The start_block and end_block arguments are mandatory and define the block range to dump,
/// start_block is inclusive and end_block is exclusive. The file_path is an optional parameter,
/// otherwise the data will be dumped to "dump_declared_classes.json".
```
___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1eDhy4I32qd7U4V5I:-Nh1eDhy4I32qd7U4V5J:b-3x6alu) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L14)):*
> ```XML
>     let cli_params = get_cli_params();
>     match dump_declared_classes_table_by_block_range(cli_params.start_block, cli_params.end_block, &cli_params.file_path) {
>         Ok(_) => println!("Dumped declared_classes table to file: {}", cli_params.file_path),
> ```

add . at end of sentenece (x2)
___
*[`crates/dump_declared_classes/src/main.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1daXgC3lf0Snd3Sbt:-Nh1daXgC3lf0Snd3Sbu:b-6icu8m) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L64)):*
> ```XML
>         panic!("start_block must be smaller than end_block");
>     }
>     let compile_class_marker =
> ```

compiled_class_marker



_Code quote:_
```XML
compile_class_marker
```
___
*[`crates/dump_declared_classes/src/main.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1dgQ30LOF9UhJ_vWe:-Nh1dgQ30LOF9UhJ_vWf:bmmv4uh) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L65)):*
> ```XML
>     }
>     let compile_class_marker =
>         get_compiled_class_marker().expect("couldn't get compiled class marker");
> ```

Couldn't get compiled_class marker.



_Code quote:_
```XML
couldn't get compiled class marker
```
___
*[`crates/dump_declared_classes/src/main.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1dns_3hoDbiiNC3hf:-Nh1dns_3hoDbiiNC3hg:bcg1rtk) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L66)):*
> ```XML
>     let compile_class_marker =
>         get_compiled_class_marker().expect("couldn't get compiled class marker");
>     if start_block > compile_class_marker.0 || end_block > compile_class_marker.0 {
> ```

it's enough to check end_block
___
*[`crates/papyrus_storage/src/utils_test.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1fqGu-cYZf-uhrovq:-Nh1fqGu-cYZf-uhrovr:bty9zyc) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L16)):*
> ```XML
> 
> #[test]
> fn test_dump_table_to_file() {
> ```

change the name of the test 
test_dump_declared_classes()  ?



_Code quote:_
```XML
test_dump_table_to_file
```
___
*[`crates/papyrus_storage/src/utils_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1h9WE9V96hHo06WwI:-Nh1h9WE9V96hHo06WwJ:b-9tpqlx) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L49)):*
> ```XML
>             .unwrap();
>     }
>     let txn = reader.begin_ro_txn().unwrap();
> ```

add empty line
___
*[`crates/papyrus_storage/src/utils_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1h0rC-EBs1YZjRe-P:-Nh1h0rDEdMY__EMUU46:b-k2zbzi) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L50)):*
> ```XML
>     }
>     let txn = reader.begin_ro_txn().unwrap();
>     // Test dump_declared_classes_to_file
> ```

// Test dump_table_to_file for declared_clases table.



_Code quote:_
```XML
// Test dump_declared_classes_to_file
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)* status: all files reviewed, 8 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/dump_declared_classes/src/main.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1eLiQDFl8ZCOGAzUc:-Nh1iJCf4NVYP54qg04O:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L10)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Maybe move this part of the documentation to fn get_cli_params()
</blockquote></details>

Done
___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1eDhy4I32qd7U4V5I:-Nh1iKoL5wD3OKCeqUp3:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L14)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

add . at end of sentenece (x2)
</blockquote></details>

done
___
*[`crates/dump_declared_classes/src/main.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1daXgC3lf0Snd3Sbt:-Nh1ibxf6jkVh1HyGDAX:b-q7pdcl) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L64)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

compiled_class_marker
</blockquote></details>

fixed and moved this code to utils.rs
___
*[`crates/dump_declared_classes/src/main.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1dgQ30LOF9UhJ_vWe:-Nh1iipNCKOZypUApksa:bpagbrg) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L65)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Couldn't get compiled_class marker.
</blockquote></details>

this code was deleted
___
*[`crates/dump_declared_classes/src/main.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1dns_3hoDbiiNC3hf:-Nh1iltA89IbZzgVUtNp:bvsy1gm) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/dump_declared_classes/src/main.rs#L66)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

it's enough to check end_block
</blockquote></details>

right done , now in utils.rs
___
*[`crates/papyrus_storage/src/utils_test.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1fqGu-cYZf-uhrovq:-Nh1jMIr-P-qqmJ-llIg:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L16)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

change the name of the test 
test_dump_declared_classes()  ?
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/utils_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1h9WE9V96hHo06WwI:-Nh1jXc-DB6I40y0egU3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L49)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

add empty line
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/utils_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh1h0rC-EBs1YZjRe-P:-Nh1jXP84cQdM9Nz_4I5:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a6777672c1d29c02723822b6e377b8ff9924462/crates/papyrus_storage/src/utils_test.rs#L50)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

// Test dump_table_to_file for declared_clases table.
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/dump_declared_classes/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-Nh-aOJMC9DAmZlRQX6y:-Nh1l5Tl9rv8OMN63SBm:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2ff9ce9e9335158b4a620e35b38e59879e8d1ae9/crates/dump_declared_classes/src/main.rs#L14)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

move the part of parsing the command-line parameters to a separate function.
</blockquote></details>

Done.

**Review by OmriEshhar1 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1283#-:-Nh1p8Uj5Xkbdka-sQ7E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
