### PR TITLE
fix(network): make peer_id non optional

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1756)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* **#1756** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1756?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1756?utm_source=stack-comment).

**Review by dan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1756)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1756#-Nrp_hDL89fY3WVgwEgC:-Nrp_hDL89fY3WVgwEgD:b-poec4w) ([raw file](https://github.com/starkware-libs/papyrus/blob/4caa866a9067a003a96ed536b27151e016fb3842/crates/papyrus_network/src/lib.rs#L182)):*
> ```XML
>         Self {
>             peer_id: PeerId::from_str("QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N")
>                 .expect("couldn't create exmple peer id from bytes"),
> ```

Consider 
https://doc.rust-lang.org/std/error/index.html#common-message-styles



_Suggestion:_
```XML
QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N should be a valid peer ID
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1756#-:-Ns3Aa7k-PWUZbxDMsKD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1756#-:-Ns3HlvA4-Ot1QMlHEyG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
