### PR TITLE
feat(config): add an `enforce_file_exists` flag to DbConfig + test

### PR DESCRIPTION
**Pull request by zuphitf**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1471)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1471)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @zuphitf)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1471#-NkUEMjW3_cCuCi_fZjc:-NkUEMjW3_cCuCi_fZjd:bhz5cv4) ([raw file](https://github.com/starkware-libs/papyrus/blob/df649cb3a6407a197826b610ac65183faf295519/crates/papyrus_storage/src/db/mod.rs#L158)):*
> ```XML
>     /// An error that occured when trying to open a db file that does not exist.
>     #[error("The file '{0}' does not exist.")]
>     FileDoesNotExist(PathBuf),
> ```

File is too general i think



_Suggestion:_
```XML
DBDoesNotExist
```

**Comment by zuphitf** [comment]
*[`crates/papyrus_storage/src/db/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1471#-NkUEMjW3_cCuCi_fZjc:-NkURi7S0p04o958gUhT:b15w4ea) ([raw file](https://github.com/starkware-libs/papyrus/blob/df649cb3a6407a197826b610ac65183faf295519/crates/papyrus_storage/src/db/mod.rs#L158)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

File is too general i think
</blockquote></details>

It's under `DbError::FileDoesNotExist` though. 
Also, libmdbx already checks that the folder itself exists.
DB is not super indicative. I can change it to `DbFileDoesNotExist`, not sure if it's better. Wdyt?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/papyrus_storage/src/db/db_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1471#-NkVKxb37bb1TyA9FKIc:-NkVKxb37bb1TyA9FKId:bxaavlm) ([raw file](https://github.com/starkware-libs/papyrus/blob/df649cb3a6407a197826b610ac65183faf295519/crates/papyrus_storage/src/db/db_test.rs#L29)):*
> ```XML
>     // off.
>     let result = open_env(&db_config);
>     assert_matches!(result, Err(DbError::FileDoesNotExist(_)));
> ```

Consider this instead of deriving `Debug` for `DbReader`



_Suggestion:_
```XML
    match result {
        Err(DbError::FileDoesNotExist(_)) => (),
        _ => panic!("Expected FileDoesNotExist error"),
    }
```

**Review by giladchase — APPROVED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Pull request merged**
