### PR TITLE
fix(network): move code for adding fin from network manager to db executor

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)

### CODE REVIEW

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-GfyqB7Y2K_j-Lyjtj:-O-GfyqB7Y2K_j-Lyjtk:b-90pbsn) ([raw file](https://github.com/starkware-libs/papyrus/blob/fab923d6b64c8331073ddf3f04fe2f0eb9c6c861/crates/papyrus_network/src/db_executor/mod.rs#L166)):*
> ```XML
>             // Using async block so that we can use the ? operator inside it without it
>             // returning the error to the main async block.
>             let result1: Result<(), DBExecutorError> = async move {
> ```

could you please rename `result1` and `result2` to more descriptive names, e.g. `block_data_result` and `fin_result`
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-GgbGA5I2WCJT2YapG:-O-GgbGA5I2WCJT2YapH:b-vnmcrg) ([raw file](https://github.com/starkware-libs/papyrus/blob/fab923d6b64c8331073ddf3f04fe2f0eb9c6c861/crates/papyrus_network/src/db_executor/test.rs#L166)):*
> ```XML
>         },
>     );
>     mock_data_type.expect_fin().times(1).returning(|| Data::default());
> ```

remove closure

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-GfyqB7Y2K_j-Lyjtj:-O-UmzppEAuiQ39Bdatf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fab923d6b64c8331073ddf3f04fe2f0eb9c6c861/crates/papyrus_network/src/db_executor/mod.rs#L166)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

could you please rename `result1` and `result2` to more descriptive names, e.g. `block_data_result` and `fin_result`
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-GgbGA5I2WCJT2YapG:-O-UmPFjBkmneu9wYi53:bxk40xt) ([raw file](https://github.com/starkware-libs/papyrus/blob/fab923d6b64c8331073ddf3f04fe2f0eb9c6c861/crates/papyrus_network/src/db_executor/test.rs#L166)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

remove closure
</blockquote></details>

Done. clippy agrees with you :)

**Review by asmaastarkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-:-O-V6Bcm-WSIHMY0fBQJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 212 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-Vl46B-nTOWe31KR4l:-O-Vl46B-nTOWe31KR4m:b-7ax9wb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8794f9962c4a553fdb3c669ef88561a0d2a9ba27/crates/papyrus_network/src/db_executor/mod.rs#L212)):*
> ```XML
>             }
>         });
>     }
> ```

I think it's much cleaner to just move the main logic into its own function. This is already quite a large function and the error handling at the end is a bit messy.



_Suggestion:_
```XML
#[async_trait]
impl DBExecutorTrait for DBExecutor {
    fn register_query(
        &mut self,
        query: Query,
        data_type: impl FetchBlockDataFromDb + Send + 'static,
        sender: Sender<Data>,
    ) {
        let storage_reader_clone = self.storage_reader.clone();
        tokio::task::spawn(async move {
            let query_clone = query.clone();
            let send_result =
                send_data_and_fin(query, data_type, sender, storage_reader_clone).await;

            if let Err(error) = send_result {
                if error.should_log_in_error_level() {
                    error!("Running inbound query {query_clone:?} failed on {error:?}");
                }
                Err(error)
            } else {
                Ok(())
            }
        });
    }

    async fn run(&mut self) {
        // TODO(shahak): Parse incoming queries once we receive them through channel instead of
        // through function.
        pending::<()>().await
    }
}

async fn send_data_and_fin(
    query: Query,
    data_type: impl FetchBlockDataFromDb + Send + 'static,
    mut sender: Sender<Data>,
    storage_reader: StorageReader,
) -> Result<(), DBExecutorError> {
    let fin = data_type.fin();
    let txn = storage_reader.begin_ro_txn()?;
    let start_block_number = match query.start_block {
        BlockHashOrNumber::Number(BlockNumber(num)) => num,
        BlockHashOrNumber::Hash(block_hash) => {
            txn.get_block_number_by_hash(&block_hash)?
                .ok_or(DBExecutorError::BlockNotFound {
                    block_hash_or_number: BlockHashOrNumber::Hash(block_hash),
                })?
                .0
        }
    };
    for block_counter in 0..query.limit {
        let block_number =
            BlockNumber(utils::calculate_block_number(&query, start_block_number, block_counter)?);
        let data_vec = data_type.fetch_block_data_from_db(block_number, &txn)?;
        // Using poll_fn because Sender::poll_ready is not a future
        poll_fn(|cx| sender.poll_ready(cx)).await?;
        for data in data_vec {
            // TODO: consider implement retry mechanism.
            sender.start_send(data)?;
        }
    }
    poll_fn(|cx| sender.poll_ready(cx)).await?;
    sender.start_send(fin)?;
    Ok(())
}
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 212 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2106#-O-Vl46B-nTOWe31KR4l:-O-Vu0Er1fYX8i34kYnw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8794f9962c4a553fdb3c669ef88561a0d2a9ba27/crates/papyrus_network/src/db_executor/mod.rs#L212)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think it's much cleaner to just move the main logic into its own function. This is already quite a large function and the error handling at the end is a bit messy.
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
