### PR TITLE
Tracing

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Logs are produced using the log crate, collected by log4rs.

## What is the new behavior?
Logs are produced using the tracing crate and collected by tracing_subscriber, as a first step towards using tracing in the node.

-

## Does this introduce a breaking change?

- [x] Yes
- [] No

Log level previously set by log4rs config file, now set by env variable RUST_LOG, and for now there is no way to change it dynamically during the execution of the node.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_gateway/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM0HLHN2fYzr2i3i5Xu:-NM0HLHO4QdXmsfuyECF:byn2cut) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L13)):*
> ```TOML
> futures-util = { version = "0.3.21" }
> jsonrpsee = { version = "0.13.1", features = ["full"] }
> ```

please remove
___
*[`crates/papyrus_gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM0HqAv0xOZ2bJa5gpy:-NM0HqAv0xOZ2bJa5gpz:b-stzl40) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L21)):*
> ```TOML
> tokio = { version = "1.18.2", features = ["full","sync"] }
> tokio-stream = { version = "0.1.8" }
> tracing = { version = "0.1", features = ["log"] }
> ```

Do we need it (given that this PR also introduce a subscriber)?



_Code quote:_
```TOML
 ["log"] 
```
___
*[`crates/papyrus_gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ld9e7cFhk6fAP4J2:-NM2ld9e7cFhk6fAP4J3:b3fe5y9) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L21)):*
> ```TOML
> tokio = { version = "1.18.2", features = ["full","sync"] }
> tokio-stream = { version = "0.1.8" }
> tracing = { version = "0.1", features = ["log"] }
> ```

We usually state patch number as well (MAJOR.MINOR.PATCH). Is there a specific reason here to do otherwise? 



_Code quote:_
```TOML
"0.1"
```
___
*[`crates/papyrus_node/src/main.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2mIG05OkaxzPgw4Dq:-NM2mIG05OkaxzPgw4Dr:blrkbti) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L12)):*
> ```XML
> use tracing_subscriber::{fmt, EnvFilter};
> 
> // TODO: Add to config.
> ```

Please bring up TODOs format during our next sync. IMO we should either use GH handle (especially for external contributors) or our regular naming convention. 



_Code quote:_
```XML
// TODO: Add to config.
```
___
*[`crates/papyrus_node/src/main.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ruie-vEhNkriH_5w:-NM2ruie-vEhNkriH_5x:b8nvb9w) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L13)):*
> ```XML
> 
> // TODO: Add to config.
> const DEFAULT_LEVEL: &str = "info";
> ```

Can we us `LevelFilter::Info` instead? 



_Code quote:_
```XML
 &str = "info"
```
___
*[`crates/papyrus_node/src/main.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ukKIBME4s4i-0XW2:-NM2ukKIBME4s4i-0XW3:bgm9f6z) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L54)):*
> ```XML
>     let fmt_layer = fmt::layer().compact().with_target(false);
>     let level_filter_layer =
>         EnvFilter::try_from_default_env().or_else(|_| EnvFilter::try_new(DEFAULT_LEVEL)).unwrap();
> ```

Consider something like 
`
EnvFilter::builder().with_default_directive(LevelFilter::INFO.into()).from_env_lossy();
`



_Suggestion:_
```XML
    let level_filter_layer =
        EnvFilter::try_from_default_env().or_else(|_| EnvFilter::try_new(DEFAULT_LEVEL)).unwrap();  
```
___
*[`crates/papyrus_node/src/main.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM3E70GBBEecOD0ZU9b:-NM3E70GBBEecOD0ZU9c:b-v0xd4u) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L57)):*
> ```XML
> 
>     let subscriber = tracing_subscriber::registry().with(fmt_layer).with(level_filter_layer);
>     tracing::subscriber::set_global_default(subscriber).unwrap();
> ```

Consider using [init](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/util/trait.SubscriberInitExt.html#method.init) instead. 



_Code quote:_
```XML
tracing::subscriber::set_global_default(subscriber).unwrap();
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM0HLHN2fYzr2i3i5Xu:-NM80hPt1xXgH4X4R8wM:b-6mcnb0) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

please remove
</blockquote></details>

Remove what?
___
*[`crates/papyrus_gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM0HqAv0xOZ2bJa5gpy:-NM8-Ai6397uiuMBF3eN:b-bv99g9) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L21)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need it (given that this PR also introduce a subscriber)?
</blockquote></details>

Since the Sequencer is using the storage, I thought maybe I should set this flag in all of the crates
___
*[`crates/papyrus_node/src/main.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM3E70GBBEecOD0ZU9b:-NM80FkE7DJB-uldTRog:b-2voyk2) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L57)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider using [init](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/util/trait.SubscriberInitExt.html#method.init) instead. 
</blockquote></details>

We might want another subscriber for some threads, wdyt?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)* status: 6 of 17 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM0HqAv0xOZ2bJa5gpy:-NM8wjGT9JoWVvB8Bb41:b5q0jjx) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L21)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Since the Sequencer is using the storage, I thought maybe I should set this flag in all of the crates
</blockquote></details>

Kept the flag in the storage and test_utils, removed from the other crates
___
*[`crates/papyrus_gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ld9e7cFhk6fAP4J2:-NM8wtarExzIZTnEJE1e:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dbfb09bc51d4f9d0eecc21678f3065dd1cf681b/crates/papyrus_gateway/Cargo.toml#L21)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We usually state patch number as well (MAJOR.MINOR.PATCH). Is there a specific reason here to do otherwise? 
</blockquote></details>

done
___
*[`crates/papyrus_node/src/main.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2mIG05OkaxzPgw4Dq:-NM8x69V20GhLEuBwCzc:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L12)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please bring up TODOs format during our next sync. IMO we should either use GH handle (especially for external contributors) or our regular naming convention. 
</blockquote></details>

done
___
*[`crates/papyrus_node/src/main.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ruie-vEhNkriH_5w:-NM97ykZ0mToUW2qXpK5:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we us `LevelFilter::Info` instead? 
</blockquote></details>

done
___
*[`crates/papyrus_node/src/main.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2ukKIBME4s4i-0XW2:-NM97jB336H3uFhD_qzy:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L54)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider something like 
`
EnvFilter::builder().with_default_directive(LevelFilter::INFO.into()).from_env_lossy();
`
</blockquote></details>

done
___
*[`crates/papyrus_node/src/main.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM3E70GBBEecOD0ZU9b:-NM97qZY89p1bTVym6H-:bkpbahl) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We might want another subscriber for some threads, wdyt?
</blockquote></details>

done (added comment)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_node/Cargo.toml` line 27 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NMEaX1fCUNDCDksFO1N:-NMEaX1g3lREWpRekmRg:blfspul) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cc56fcf0658644b9eb482a3d0f4f52c54a94ef/crates/papyrus_node/Cargo.toml#L27)):*
> ```TOML
> tokio = { version = "1.18.2", features = ["full","sync"] }
> tokio-stream = { version = "0.1.8" }
> tracing = { version = "0.1" }
> ```

Here as well.



_Code quote:_
```TOML
tracing = { version = "0.1" }
```
___
*[`crates/papyrus_node/src/main.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/458#-NM2mIG05OkaxzPgw4Dq:-NMEb867-CAfzRuNQA-e:bs6qvsh) ([raw file](https://github.com/starkware-libs/papyrus/blob/304c1c220d0b36d6523ebacd82e8d48c5f00027e/crates/papyrus_node/src/main.rs#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done
</blockquote></details>

Here as well

**Review by dan-starkware — APPROVED** [review]
> Reviewed 5 of 14 files at r7, 1 of 1 files at r9, 6 of 7 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/458#-:-NMSMJFTEwEsA1wEMesF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
