### PR TITLE
feat(network): update protobuf to latest version and fix code to match it

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`.github/workflows/ci.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2Att5x9mNA8egNT4:-Nm_2Att5x9mNA8egNT5:b-l3rnys) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L50)):*
> ```YAML
>       - run: echo "PROTOC_VERSION=25.1" >> $GITHUB_ENV
>       - run: echo "OS=`[ "$(uname -s)" = "Darwin" ] && echo "osx" || (echo $(uname -s | tr '[:upper:]' '[:lower:]'))`" >> $GITHUB_ENV
>       - run: echo "ARCH=`[ "$(uname -m)" = "x86_64" ] && echo "x86_64" || ([ "$(uname -m)" = "arm64" ] && echo "aarch64")`" >> $GITHUB_ENV
> ```

Define env vars with `env:` instead of this hack
___
*[`.github/workflows/ci.yml` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2HOi2TkCWKWfemlH:-Nm_2HOi2TkCWKWfemlI:b-xgzxvl) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L73)):*
> ```YAML
>       - uses: Swatinem/rust-cache@v2
>       - run: npm install -g ganache@7.4.3
>       
> ```

remove whitespaces
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2W6I0t4SWOSF9G4D:-Nm_2W6I0t4SWOSF9G4E:b5gjx2v) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L121)):*
> ```YAML
>       - uses: Swatinem/rust-cache@v2
>       
>       - run: echo "PB_REL=https://github.com/protocolbuffers/protobuf/releases" >> $GITHUB_ENV 
> ```

Try and find out how to avoid code duplication in ci.yml files
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2zSE7-e29Qb63cHZ:-Nm_2zSF9b2Dioz878ip:b-whil11) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L251)):*
> ```XML
>         Behaviour::<BlockHeadersRequest, BlockHeadersResponse>::new(SUBSTREAM_TIMEOUT);
> 
>     // TODO(shahak): Change to GetBlocks::default() when the bug that forbids sending default
> ```

Remove TODO. Same in all other places
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_33YK0FGoY45Lpahl:-Nm_33YK0FGoY45Lpahm:b-i9jxu6) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L253)):*
> ```XML
>     // TODO(shahak): Change to GetBlocks::default() when the bug that forbids sending default
>     // messages is fixed.
>     let query = BlockHeadersRequest { ..Default::default() };
> ```

Change to BlockHeadersRequest::default()
I'm surprised clippy didn't fail on this
Same in all other places

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`.github/workflows/ci.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_EA8q0ycfg3sgfnzu:-Nm_EA8r3RFZ1F6q80eA:bta85mt) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L51)):*
> ```YAML
>       - run: echo "OS=`[ "$(uname -s)" = "Darwin" ] && echo "osx" || (echo $(uname -s | tr '[:upper:]' '[:lower:]'))`" >> $GITHUB_ENV
>       - run: echo "ARCH=`[ "$(uname -m)" = "x86_64" ] && echo "x86_64" || ([ "$(uname -m)" = "arm64" ] && echo "aarch64")`" >> $GITHUB_ENV
>       - run: echo "$PB_REL/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-$OS-$ARCH.zip"
> ```

I think this line doesn't do anything

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: 12 of 14 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`.github/workflows/ci.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2Att5x9mNA8egNT4:-Nm_XWlU5YMLuvM7cT2F:b72g8ew) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Define env vars with `env:` instead of this hack
</blockquote></details>

doesn't work.. tried that.. this is the correct way to do that
___
*[`.github/workflows/ci.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_EA8q0ycfg3sgfnzu:-Nm_Z6r06kFw6ayNHcWn:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L51)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this line doesn't do anything
</blockquote></details>

removed
___
*[`.github/workflows/ci.yml` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2HOi2TkCWKWfemlH:-Nm_XxFE1qvaOibGOKi-:b-t6e7go) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

remove whitespaces
</blockquote></details>

that's intentional I did it every place I repeat this code to make it easy to understand
___
*[`.github/workflows/ci.yml` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2W6I0t4SWOSF9G4D:-Nm_Y4Vd7olIPH4PY8xx:bjqwk8w) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L121)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try and find out how to avoid code duplication in ci.yml files
</blockquote></details>

I thought about that.. we need to build an image and use that in the CI instead of rebuilding the image in each step. discussed this before with Dan and decided to not invest in it but I agree we should re-consider that.. not urgent though
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2zSE7-e29Qb63cHZ:-Nm_Z9Rt2HoO7K9PnDhD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L251)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove TODO. Same in all other places
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_33YK0FGoY45Lpahl:-Nm_ZAQVByUq3wHIwdyH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L253)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change to BlockHeadersRequest::default()
I'm surprised clippy didn't fail on this
Same in all other places
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`.github/workflows/ci.yml` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2HOi2TkCWKWfemlH:-Nm_ZPNh-r3B0pUrsfaN:bj1v1ek) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L73)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

that's intentional I did it every place I repeat this code to make it easy to understand
</blockquote></details>

Yes, but you can put a newline without whitespaces
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2zSE7-e29Qb63cHZ:-Nm_ZZa8DC6niT8UsO7t:b-gmim1d) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L251)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in handler_test and protocol_test as well. probably should've been more clear
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_33YK0FGoY45Lpahl:-Nm_ZiL19p3xFL7wN64g:b-gmim1d) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L253)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in handler_test and protocol_test as well. probably should've been more clear

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2zSE7-e29Qb63cHZ:-Nm_Zvm_ERSdamUarVxw:b-r1ywtm) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L251)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I meant in handler_test and protocol_test as well. probably should've been more clear
</blockquote></details>

and flow test
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_33YK0FGoY45Lpahl:-Nm_ZuxG-2bE-CEpJ7OY:b-r1ywtm) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L253)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I meant in handler_test and protocol_test as well. probably should've been more clear
</blockquote></details>

and flow test

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`.github/workflows/ci.yml` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2HOi2TkCWKWfemlH:-Nm__urO7LvgzMMNPw5d:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/.github/workflows/ci.yml#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, but you can put a newline without whitespaces
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_2zSE7-e29Qb63cHZ:-Nm__shhCiJbloCJQOR6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L251)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

and flow test
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-Nm_33YK0FGoY45Lpahl:-Nm__sP9E_A9jTfrddt4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea28d7fc9df56340b68b6b7e0b430ebdfb725de5/crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs#L253)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

and flow test
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1535#-:-Nm_aZyl0YMOjLv8J8J9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
