### PR TITLE
refactor(starknet_client): split error into ClientError and ReaderClientError

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/934)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/934)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/starknet_client/src/writer/mod.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/934#-Nab0zmo8NdQNC43chOp:-Nab0zmpCVkBBXCAwT_u:b-8zdqih) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6775c795b227085d5624ab302357df50d981960/crates/starknet_client/src/writer/mod.rs#L22)):*
> ```XML
> use crate::{ClientCreationError, ClientError, RetryConfig, StarknetClient};
> 
> /// Errors that may be returned from a reader client.
> ```

writer?



_Code quote:_
```XML
reader
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/934)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/934)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/writer/mod.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/934#-Nab0zmo8NdQNC43chOp:-Nab2XMe-SH3ecsmOZoa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6775c795b227085d5624ab302357df50d981960/crates/starknet_client/src/writer/mod.rs#L22)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

writer?
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/934#-:-Nab34FIEHd3RvqqRIN8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
