### PR TITLE
feat(JSON-RPC): get_transaction_receipt supports pending

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@Yael-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-:-Ngy9XsE68Fm97PDW5-W:b835xbr)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Ngy9bEy76nxvfBz4iip:-Ngy9bEy76nxvfBz4iiq:b-kb7ths) (no related file):*
LMK if this PR is too big and you prefer I split it

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json` line 2202 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh03jJk9h0udsRH0cFO:-Nh03jJk9h0udsRH0cFP:b-qqx1vp) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json#L2202)):*
> ```JSON
>                 ]
>             },
>             "PENDING_INVOKE_TXN_RECEIPT": {
> ```

This is taken from the latest version of the specs. I talked to @ArielElp and he prefers we deviate from the specs than fixing v0.4.0 on something that's already fixed in a later version

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 396 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0YXiA293tC76lj_w_:-Nh0YXiA293tC76lj_wa:b6mpb9q) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L396)):*
> ```XML
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> #[serde(untagged)]
> pub enum GeneralTransactionReceipt {
> ```

Why do the pending transactions need their own receipt type?
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0ZZl25dLYSQLYyFcB:-Nh0ZZl25dLYSQLYyFcC:bn73yti) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L407)):*
> ```XML
>         };
> 
>         let block_number = transaction_index.0;
> ```

IIUC this code is the continuation of the non-pending transaction flow. 
Consider changing to if-let and keep the whole code together.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 745 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0aHjjAKcgerrKzFbr:-Nh0_dns1FS4q4NMIHJ2:bm66eop) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L745)):*
> ```XML
> 
>     // Ask for a pending transaction.
>     let mut rng = get_rng();
> ```

Why randomness?
Can you explain what you are doing here?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 396 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0YXiA293tC76lj_w_:-Nh0akko0YfZTJAL5N4h:bqo8hr3) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L396)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do the pending transactions need their own receipt type?
</blockquote></details>

Because they have no block_hash/number, and their output and finality are more prohibiting
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0ZZl25dLYSQLYyFcB:-Nh0b4MEEsXnajRPk3W8:b-8vxlr) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L407)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IIUC this code is the continuation of the non-pending transaction flow. 
Consider changing to if-let and keep the whole code together.
</blockquote></details>

Where's the common code that I'll be saving? I don't see any intersection
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 745 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0aHjjAKcgerrKzFbr:-Nh0bEkk6Wm96_RWmpA6:bfmc1ca) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L745)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why randomness?
Can you explain what you are doing here?
</blockquote></details>

I'll explain, in function :)

**Comment by yair-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 745 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0aHjjAKcgerrKzFbr:-NhLXLWs8RC8G6ZD8820:b-uiwz70) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L745)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll explain, in function :)
</blockquote></details>

Make the pending data hard-coded instead of random

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 5 of 8 files at r8, 3 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @Yael-Starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-Nh0ZZl25dLYSQLYyFcB:-NhMO-j08UbuMiVWhhYU:b-gf6jfq) ([raw file](https://github.com/starkware-libs/papyrus/blob/d547fc3a5ccf5332e6efbc098d359d1d396f90d9/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L407)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Where's the common code that I'll be saving? I don't see any intersection
</blockquote></details>

discussed
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 770 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-NhMMsTw-dT7UDJHQ2Zf:-NhMMsTw-dT7UDJHQ2Zg:b6dt1x9) ([raw file](https://github.com/starkware-libs/papyrus/blob/6697fbc40cf25d28fedea2af9595695841e277e3/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L770)):*
> ```XML
>     assert_eq!(res.output.execution_status(), &TransactionExecutionStatus::Succeeded);
> 
>     // Ask for a pending transaction.
> ```

`// Add a pending transaction and ask for its receipt.`



_Code quote:_
```XML
// Ask for a pending transaction.
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1270 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-NhMGyZGEpYa9VHqG1oE:-NhMGyZGEpYa9VHqG1oF:b-s4w1hj) ([raw file](https://github.com/starkware-libs/papyrus/blob/6697fbc40cf25d28fedea2af9595695841e277e3/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1270)):*
> ```XML
>     let mut client_transaction_receipt = ClientTransactionReceipt::get_test_instance(rng);
>     client_transaction_receipt.transaction_hash = pending_transaction_hash;
>     let (mut client_transaction, output) = loop {
> ```

Add a comment explaining this loop.



_Code quote:_
```XML
let (mut client_transaction, output) = loop {
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1276 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-NhMK8ft3xOTrM3GvfJU:-NhMK8fu4bxPN4lCFn-Y:b-s8zbfk) ([raw file](https://github.com/starkware-libs/papyrus/blob/6697fbc40cf25d28fedea2af9595695841e277e3/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1276)):*
> ```XML
>             .into_starknet_api_transaction_output(&client_transaction);
>         let maybe_output =
>             PendingTransactionOutput::try_from(TransactionOutput::from(starknet_api_output));
> ```

This code is repeated in multiple in api_impl. Consider creating a function.



_Code quote:_
```XML
        let starknet_api_output = client_transaction_receipt
            .clone()
            .into_starknet_api_transaction_output(&client_transaction);
        let maybe_output =
            PendingTransactionOutput::try_from(TransactionOutput::from(starknet_api_output));
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 770 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-NhMMsTw-dT7UDJHQ2Zf:-NhMPn-r4UE6T4aMnl05:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6697fbc40cf25d28fedea2af9595695841e277e3/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L770)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

`// Add a pending transaction and ask for its receipt.`
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1270 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-NhMGyZGEpYa9VHqG1oE:-NhMPSAb0aV5jKNu1BOP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6697fbc40cf25d28fedea2af9595695841e277e3/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1270)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add a comment explaining this loop.
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1284#-:-NhMQIn6CcMc1JtHDg3k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @Yael-Starkware)

**Pull request merged**
