### PR TITLE
papyrus helm chart

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe): adding a helm chart and load-test as part of CI

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 1 of 16 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/values.yaml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNA_Gj86y7wI_BbuXa:-NPNA_Gj86y7wI_BbuXb:b-12k0by) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/values.yaml#L2)):*
> ```YAML
> # Default values for a papyrus deployment.
> ```

no need in values file and default values file.. its public repo merge them

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 1 of 16 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/ingress.yaml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNAvL0ACxUpwBE2KUZ:-NPNAvL0ACxUpwBE2KU_:b-34h84p) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/templates/ingress.yaml#L20)):*
> ```YAML
>             port:
>               number: {{ .Values.services.rpc.port }}
>         path: /
> ```

if it, its not mandatory



_Code quote:_
```YAML
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}-{{ template "papyrus.name" . }}"
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ tpl .Values.ingress.annotations . | nindent 4 | trim }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "papyrus.name" . }}-rpc
            port:
              number: {{ .Values.services.rpc.port }}
        path: /
        pathType: {{ .Values.ingress.pathType }}
      - backend:
          service:
            name: {{ template "papyrus.name" . }}-monitoring
            port:
              number: {{ .Values.services.monitoring.port }}
        path: /monitoring
        pathType: {{ .Values.ingress.pathType }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host }}-ssl-secret
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 1 of 16 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/svc_monitoring.yaml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNB2Ao-PCsQK5D_Y2Y:-NPNB2Ao-PCsQK5D_Y2Z:b-tpgtxa) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/templates/svc_monitoring.yaml#L11)):*
> ```YAML
>   ports:
>   - name: {{ template "papyrus.name" . }}-port
>     protocol: "{{ .Values.services.monitoring.protocol }}"
> ```

loop it



_Code quote:_
```YAML
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-monitoring
spec:
  selector:
    app: papyrus
  type: {{ .Values.services.monitoring.type }}
  ports:
  - name: {{ template "papyrus.name" . }}-port
    protocol: "{{ .Values.services.monitoring.protocol }}"
    port: {{ .Values.services.monitoring.port }}
    targetPort: {{ .Values.services.monitoring.port }}
```

**Review by eranreshef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 1 of 18 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`deployments/helm/values.yaml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNA_Gj86y7wI_BbuXa:-NPNDXeI0Bw4R5iiNNKv:bejplvw) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/values.yaml#L2)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

no need in values file and default values file.. its public repo merge them
</blockquote></details>

Done. I removed most of the content from deployments/helm/CI/values.yaml but kept some fields that are unique for the CI execution.
___
*[`deployments/helm/templates/ingress.yaml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNAvL0ACxUpwBE2KUZ:-NPNEAOL96HTtpWt-fpq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/templates/ingress.yaml#L20)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

if it, its not mandatory
</blockquote></details>

Done.
___
*[`deployments/helm/templates/svc_monitoring.yaml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNB2Ao-PCsQK5D_Y2Y:-NPNIyZz8ahyUP1qkU66:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/templates/svc_monitoring.yaml#L11)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

loop it
</blockquote></details>

Done.

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 3 files at r4, 5 of 9 files at r9, 3 of 3 files at r11, 1 of 2 files at r12, 2 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/svc_monitoring.yaml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPNB2Ao-PCsQK5D_Y2Y:-NPNzz7vAOg-AJcCMynM:b-7hb85j) ([raw file](https://github.com/starkware-libs/papyrus/blob/88290dc95654211d931031d6867e43083b60bc3c/deployments/helm/templates/svc_monitoring.yaml#L11)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

were?

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519#-:-NPO-GDC39c_bpaa57Sf:bnfp4nl)* status: 14 of 18 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
*[`.github/workflows/helm-install.yml` line 7 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOSuwTAYwQy-mCFrcT:-NPOSuwU6JvasBprdpmI:bacbdwa) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/.github/workflows/helm-install.yml#L7)):*
> ```YAML
> on:
>   workflow_dispatch:
>   pull_request:
> ```

Maybe just on merges?



_Code quote:_
```YAML
pull_request:
```

**Comment by dan-starkware** [comment]
*[`deployments/helm/values.yaml` line 19 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOTObJ-05NOw2L7-0Q:-NPOTObJ-05NOw2L7-0R:b-amb4io) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/deployments/helm/values.yaml#L19)):*
> ```YAML
> #   limits:
> #     cpu: 100m
> #     memory: 500Mi
> ```

Do we want to keep these?



_Code quote:_
```YAML
# The default resources for the pod.
# resources:
#   limits:
#     cpu: 100m
#     memory: 500Mi
#   requests:
#     cpu: 100m
#     memory: 500Mi
```

**Comment by dan-starkware** [comment]
*[`deployments/helm/CI/values.yaml` line 3 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOURAX9TtW-peSI5kA:-NPOURAX9TtW-peSI5kB:b75meui) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/deployments/helm/CI/values.yaml#L3)):*
> ```YAML
> # Default values for a papyrus deployment.
> 
> ethereumApiUrl: ETHEREUM_API_URL
> ```

shouldn't this be empty?

**Comment by eranreshef-starkware** [comment]
*[`.github/workflows/helm-install.yml` line 7 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOSuwTAYwQy-mCFrcT:-NPR3yre3oj6NzZ884Of:b-7kay3z) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/.github/workflows/helm-install.yml#L7)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Maybe just on merges?
</blockquote></details>

I want to make sure that the helm chart won't break. I'll filter the trigger to get activated only when the `deployment/*` dir is modified. ok?

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/values.yaml` line 19 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOTObJ-05NOw2L7-0Q:-NPRY2ix4aTBOouwYIns:b1rq0y6) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/deployments/helm/values.yaml#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we want to keep these?
</blockquote></details>

lets keep it until we fix the memory leak and then un-comment it?

**Review by eranreshef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/519)* status: 9 of 18 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`deployments/helm/values.yaml` line 19 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOTObJ-05NOw2L7-0Q:-NPRteFN8tlylBkZsvXZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/deployments/helm/values.yaml#L19)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

lets keep it until we fix the memory leak and then un-comment it?
</blockquote></details>

done
___
*[`deployments/helm/CI/values.yaml` line 3 at r15](https://reviewable.io/reviews/starkware-libs/papyrus/519#-NPOURAX9TtW-peSI5kA:-NPRtfZJ9gR6EGCHdDNt:brtd693) ([raw file](https://github.com/starkware-libs/papyrus/blob/20bc24a113ded1d8dfd66bbdb36f9fc030fafab6/deployments/helm/CI/values.yaml#L3)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

shouldn't this be empty?
</blockquote></details>

remvoved

**Pull request merged**
