### PR TITLE
add rpc to url and require explicit version name

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/middleware.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-EMHQ31epImFiNVst:-N_-EMHQ31epImFiNVsu:bvugix1) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L20)):*
> ```XML
> /// [`Tower`]: https://crates.io/crates/tower
> pub(crate) async fn proxy_rpc_request(req: Request<Body>) -> Result<Request<Body>, BoxError> {
>     debug!("proxy_rpc_request -> Request received: {:?}", req);
> ```

Can you use tracing::instrument?



_Code quote:_
```XML
 debug!("proxy_rpc_request -> Request received: {:?}", req);
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-FAny0YgPEuB6lhRW:-N_-FAny0YgPEuB6lhRX:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L40)):*
> ```XML
> }
> 
> pub(crate) async fn deny_requests_with_unsupported_path(
> ```

Please document.



_Code quote:_
```XML
pub(crate) async fn deny_requests_with_unsupported_path(
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-JFqGBmojalHjVQ3w:-N_-JFqGBmojalHjVQ3x:b-ek39xo) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L43)):*
> ```XML
>     req: Request<Body>,
> ) -> Result<Request<Body>, BoxError> {
>     debug!("deny_requests_with_unsupported_path -> Request received: {:?}", req);
> ```

instrument 



_Code quote:_
```XML
 debug!("deny_requests_with_unsupported_path -> Request received: {:?}", req);
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-FWFb-mRPNO8FH4CS:-N_-FWFb-mRPNO8FH4CT:b-dt8g0m) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L48)):*
> ```XML
>         true => Ok(req),
>         false => {
>             println!("Unsupported path for request {:?}", uri);
> ```

Why not logging?



_Suggestion:_
```XML
error!
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-GAB3D7kIpI-8-4T1:-N_-GAB3D7kIpI-8-4T2:b-l7je5z) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L94)):*
> ```XML
>             *verison_id == *version && *version_state != VersionState::Deprecated
>         }) else {
>         return Err(BoxError::from("Invalid path, couldn't find matching version"));
> ```

You can log in this case as well.



_Code quote:_
```XML
return Err(BoxError::from("Invalid path, couldn't find matching version"));
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-H4bo1AFj6te56jL-:-N_-H4bo1AFj6te56jL0:borr91t) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L100)):*
> ```XML
> 
> fn is_supported_path(path: &str) -> bool {
>     let re = Regex::new(r"^\/rpc\/V[0-9]_[0-9]_[0-9]$").unwrap();
> ```

Please support more than one digit.



_Code quote:_
```XML
[0-9]_[0-9]_[0-9]
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-Ga4I4uw0qXQ-YesC:-N_-Ga4I4uw0qXQ-YesD:b3iv9rk) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/middleware.rs#L104)):*
> ```XML
>         "/" | "" => false,
>         path => re.is_match(path),
>     }
> ```

Why do we need both cases? the regex does not cover the other case?



_Code quote:_
```XML
    match path {
        "/" | "" => false,
        path => re.is_match(path),
    }
```
___
*[`crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs` line 1635 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-KQG21N_3SCvaaZRd:-N_-KQG21N_3SCvaaZRe:bsqfx7y) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs#L1635)):*
> ```XML
>         r#"{"block_number": 1}"#,
>         VERSION_0_3_0,
>     )
> ```

Consider adding a utility function that adds the version. 



_Code quote:_
```XML
    let res = send_request(
        server_address,
        "starknet_getStateUpdate",
        r#"{"block_number": 1}"#,
        VERSION_0_3_0,
    )
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_07zax6N-nfvescAZc:-N_07zax6N-nfvescAZd:byc2poo) (no related file):*
In the load test, can you define a global variable and use it instead of passing the version around? Maybe lazy static?

___
___
*[`crates/papyrus_load_test/src/lib.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-yQyX5eutA0qAsMos:-N_-yQyX5eutA0qAsMot:b-mkj15) ([raw file](https://github.com/starkware-libs/papyrus/blob/ebe5d97c1ae1ca1064f03c8cd5c708271bd62562/crates/papyrus_load_test/src/lib.rs#L19)):*
> ```XML
>     user: &mut GooseUser,
>     request: &jsonVal,
>     version_id: String,
> ```

Can we use a string slice?



_Code quote:_
```XML
String
```

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: 13 of 16 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_07zax6N-nfvescAZc:-N_2uBYa-0aRbGcK1BRF:bo6ym0p) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

In the load test, can you define a global variable and use it instead of passing the version around? Maybe lazy static?
</blockquote></details>

I would even make it a hard-coded constant. I don’t think we should support several versions in the load test, and it makes the code cleaner.

___
___
*[`crates/papyrus_gateway/src/middleware.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-HOiw8-N15Bn0fbse:-N_-HOiw8-N15Bn0fbsf:br7bry5) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef832b29b97cb8bc99456fb863a7baba29acb48e/crates/papyrus_gateway/src/middleware.rs#L44)):*
> ```XML
> ) -> Result<Request<Body>, BoxError> {
>     debug!("deny_requests_with_unsupported_path -> Request received: {:?}", req);
>     let uri = &req.uri().clone();
> ```

I believe just req.uri() without clone and & will be the same.

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: 2 of 17 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_07zax6N-nfvescAZc:-N_7sesc-HZNR9rR75FH:b-2tty2s) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I would even make it a hard-coded constant. I don’t think we should support several versions in the load test, and it makes the code cleaner.
</blockquote></details>


I think we should support multiple versions.. why not? 
as for global var, sure I can but why do you think it's a better solution?
the only benefit I see is that it makes the review easier but it has the potential to create spaghetti code

___
___
*[`crates/papyrus_gateway/src/middleware.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-HOiw8-N15Bn0fbse:-N_7vlrU06ZEBMO3Kcpx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f5f98a445cc7ccd70bbac7d31e3c16d7259421f/crates/papyrus_gateway/src/middleware.rs#L44)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I believe just req.uri() without clone and & will be the same.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-EMHQ31epImFiNVst:-N_7tFJV7lQUCx4bOi3e:b-ene33m) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L20)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you use tracing::instrument?
</blockquote></details>

I thought about it. but where? I'm not sure the middleware should be in it's one span since you lose the context 
___
*[`crates/papyrus_gateway/src/middleware.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-JFqGBmojalHjVQ3w:-N_7tYgc73T9uKdnDK6f:b-2guby3) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L43)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

instrument 
</blockquote></details>

same here
___
*[`crates/papyrus_gateway/src/middleware.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-FWFb-mRPNO8FH4CS:-N_7tg8uB8ffIcUSFYhb:b5v4yn) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L48)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not logging?
</blockquote></details>

my mistake should be removed
___
*[`crates/papyrus_gateway/src/middleware.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-GAB3D7kIpI-8-4T1:-N_7uXbREFska4g31PKK:bseeqgy) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L94)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

You can log in this case as well.
</blockquote></details>

I removed the other log. I think the only place it's useful is at the start of the middleware to make sure the code flows as expected.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-H4bo1AFj6te56jL-:-N_7uBhr96rxACxSTi09:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L100)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please support more than one digit.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-Ga4I4uw0qXQ-YesC:-N_7uF0gCjEvV7i8dHeu:b6n65ds) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L104)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need both cases? the regex does not cover the other case?
</blockquote></details>

short circuit.. can be removed but I think improves readability
___
*[`crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs` line 1635 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-KQG21N_3SCvaaZRd:-N_7w1z47y-lV7L_Jkb1:brrsoxv) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs#L1635)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider adding a utility function that adds the version. 
</blockquote></details>

how is it different then sending `server_address` every time?
___
*[`crates/papyrus_load_test/src/lib.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-yQyX5eutA0qAsMos:-N_7xLAV8ofcPlmUZWbY:b2nign6) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_load_test/src/lib.rs#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we use a string slice?
</blockquote></details>

yes

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/version_config.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_9fKYHEwGAoTfeTnvU:-N_9fKYHEwGAoTfeTnvV:bpq76gj) ([raw file](https://github.com/starkware-libs/papyrus/blob/661671981bcc549035ac8b07f8f3f79a57c0f9df/crates/papyrus_gateway/src/version_config.rs#L16)):*
> ```XML
> 
> /// id of latest version that will be exposed via the default paths: http://host:port and http://host:port/
> pub const LATEST_VERSION_ID: &str = VERSION_0_3_0;
> ```

Wasn't this part on another PR?



_Code quote:_
```XML
/// id of latest version that will be exposed via the default paths: http://host:port and http://host:port/
pub const LATEST_VERSION_ID: &str = VERSION_0_3_0;
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/middleware.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-Ga4I4uw0qXQ-YesC:-N_9evTp3USQDlNsT7ns:b-pg2a6f) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/middleware.rs#L104)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

short circuit.. can be removed but I think improves readability
</blockquote></details>

I find it weird, consider documenting (event the root/empty cases can be part of the comment)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: 0 of 19 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/version_config.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_9fKYHEwGAoTfeTnvU:-N_D0Jv87Z0Be6d2utb4:b-o3fy76) ([raw file](https://github.com/starkware-libs/papyrus/blob/661671981bcc549035ac8b07f8f3f79a57c0f9df/crates/papyrus_gateway/src/version_config.rs#L16)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Wasn't this part on another PR?
</blockquote></details>

no, this PR removed the default version option so I removed the "latest" tag

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/lib.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_AhtXM2VAVAHqWXVS3:-N_AhtXM2VAVAHqWXVS4:bgdn213) ([raw file](https://github.com/starkware-libs/papyrus/blob/f0e24ac8afc693cfaab84df6167d9118cb3add3b/crates/papyrus_load_test/src/lib.rs#L99)):*
> ```XML
> const GET_TRANSACTION_RECEIPT_WEIGHT: usize = 10;
> 
> static VERSION_ID: Lazy<String> = Lazy::new(|| match std::env::var("VERSION_ID") {
> ```

How about?



_Suggestion:_
```XML
RPC_VERSION_ID
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 7 of 13 files at r3, 2 of 3 files at r4, 1 of 7 files at r6, 1 of 2 files at r8, 8 of 8 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/middleware.rs` line 104 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_Xb1zeAn0NvqGi6SQE:-N_Xb1zeAn0NvqGi6SQF:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a845b43d1734fa0bb1ee4ae6e443fc394b4ff40/crates/papyrus_gateway/src/middleware.rs#L104)):*
> ```XML
> 
> fn is_supported_path(path: &str) -> bool {
>     let re = Regex::new(r"^\/rpc\/V[0-9]+_[0-9]+_[0-9]+$").unwrap();
> ```





_Suggestion:_
```XML
.expect("should be a valid regex")
```
___
*[`crates/papyrus_load_test/src/lib.rs` line 101 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_XbsXHBTAHO7tap7MT:-N_XbsXI0DVr6QTmCAoj:bg731o8) ([raw file](https://github.com/starkware-libs/papyrus/blob/8a845b43d1734fa0bb1ee4ae6e443fc394b4ff40/crates/papyrus_load_test/src/lib.rs#L101)):*
> ```XML
> static VERSION_ID: Lazy<String> = Lazy::new(|| match std::env::var("VERSION_ID") {
>     Ok(version_id) => version_id,
>     Err(_) => panic!("VERSION_ID environment variable is not set"),
> ```

If you check this at the beginning of main, you can use unreachable here 



_Code quote:_
```XML
panic!
```
___
*[`crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs` line 1635 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/821#-N_-KQG21N_3SCvaaZRd:-N_9fW72CWpvPed_vukY:b9ppmfa) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac17a894080e97e796dd3ff0f8c9bfccfe514cac/crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs#L1635)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

how is it different then sending `server_address` every time?
</blockquote></details>

Under the hood it is the same. I think that having a specific `send_request` utility for each version would be nice and allow more code sharing in the future. Definitely not a must now.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> Dismissed @DvirYo-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
