### PR TITLE
Show a warning message when trying to sync with a bad URL.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/607)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/607)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/607#-NT9onoXCF_bwrKUrL6r:-NT9onoXCF_bwrKUrL6s:b-nkmsbp) (no related file):*
In case of not existing URL (for example dvir_yosef):


In case of existing URL but without request, we need (for example www.googke.com):


___
___
*[`crates/starknet_client/src/lib.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/607#-NT9powrD1R86oHY3ZRV:-NT9pows2577c7M8IXJO:b-a3x5fc) ([raw file](https://github.com/starkware-libs/papyrus/blob/b3c1819c03386bed0375e20359d3286acbd09405/crates/starknet_client/src/lib.rs#L212)):*
> ```XML
>                 if internal_err.is_timeout() {
>                     Some(RetryErrorCode::Timeout)
>                 } else if internal_err.is_request() {
> ```

This must be before is_connect (line 214) because when using a non-existing URL the error is also connect.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/607)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/607#-NT9onoXCF_bwrKUrL6r:-NTK-05t9QUBnbuK8j_L:bbsdrpq) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In case of not existing URL (for example dvir_yosef):


In case of existing URL but without request, we need (for example www.googke.com):

</blockquote></details>

Much better. Can we emit error (instead of warn)? 

___

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/607)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/607#-NT9onoXCF_bwrKUrL6r:-NTOMqOK1OHCn5gzePm0:b-eqvnzg) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Much better. Can we emit error (instead of warn)? 
</blockquote></details>

Done. Now it looks like this:



___

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/607)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
