### PR TITLE
feat: support pending block for get_block_w_full_transactions

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_nXn15D1Lld7tJbQp:-Nh_nXn15D1Lld7tJbQq:baejwrz) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L192)):*
> ```XML
>     #[instrument(skip(self), level = "debug", err, ret)]
>     async fn get_block_w_full_transactions(&self, block_id: BlockId) -> RpcResult<Block> {
>         if block_id == BlockId::Tag(Tag::Pending) {
> ```

consider `if let` instead of equality
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oYeP9BLWH1JBAfDh:-Nh_oYeP9BLWH1JBAfDi:b-782i9g) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L214)):*
> ```XML
>                 })
>                 .collect::<Result<Vec<_>, ErrorObjectOwned>>()?;
>             Ok(Block { status: None, header, transactions: Transactions::Full(transactions) })
> ```

Instead of indenting everything below, change this line to `return Ok...` and remove the else
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 459 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_pD8B1f8K9VBL1vQn:-Nh_pD8B1f8K9VBL1vQo:b-p28lzc) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L459)):*
> ```XML
>     // Get pending block.
>     let transaction_count = 3;
>     let client_transaction = ClientTransaction::get_test_instance(&mut get_rng());
> ```

This can fail if you randomly got a v3 transaction (which their conversion automatically returns an error). Use generate_client_transaction_and_rpc_transaction instead
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oqPK8aKfwlToIE_8:-Nh_oqPK8aKfwlToIE_9:b-g2b3bc) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L468)):*
> ```XML
>         .transactions
>         .extend(iter::repeat(client_transaction).take(transaction_count));
>     let res = module.call::<_, Block>(method_name, [BlockId::Tag(Tag::Pending)]).await.unwrap();
> ```

Use call_api_then_assert_and_validate_schema_for_result to validate the pending schema, and add in a comment:
```
// Using call_api_then_assert_and_validate_schema_for_result in order to validate the schema for pending block.
```
Could you check if in getBlockWithTxHashes's test did you use call and fix it there too?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_nXn15D1Lld7tJbQp:-Nha0gsgAOagnovoDzE8:b-u40nbo) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L192)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

consider `if let` instead of equality
</blockquote></details>

Same for get_block_w_transaction_hashes
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oYeP9BLWH1JBAfDh:-Nha0jcZ39V2Nd5d3C_n:b-u40nbo) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L214)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of indenting everything below, change this line to `return Ok...` and remove the else
</blockquote></details>

Same for get_block_w_transaction_hashes

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_nXn15D1Lld7tJbQp:-Nh_rTEZ4sNyq7xuLtPQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L192)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

consider `if let` instead of equality
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oYeP9BLWH1JBAfDh:-Nh_rZtj9zrg0kAbBIlz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L214)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of indenting everything below, change this line to `return Ok...` and remove the else
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 459 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_pD8B1f8K9VBL1vQn:-Nh_wD6R7MPQycVuJ6Dx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L459)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This can fail if you randomly got a v3 transaction (which their conversion automatically returns an error). Use generate_client_transaction_and_rpc_transaction instead
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oqPK8aKfwlToIE_8:-NhaBxDE4ESDVTY9wvjg:b-kwtt02) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L468)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use call_api_then_assert_and_validate_schema_for_result to validate the pending schema, and add in a comment:
```
// Using call_api_then_assert_and_validate_schema_for_result in order to validate the schema for pending block.
```
Could you check if in getBlockWithTxHashes's test did you use call and fix it there too?
</blockquote></details>

Done.
But the tests fail :(
It looks like something in the schema is not consistent. I couldn't figure it out.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oYeP9BLWH1JBAfDh:-NhaCFrR1LH-cfMwWub4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L214)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oqPK8aKfwlToIE_8:-NhaHjOi3zkl6IX0UKuK:b-w1vmuv) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L468)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Done.
But the tests fail :(
It looks like something in the schema is not consistent. I couldn't figure it out.
</blockquote></details>

LMK if you need help (I WFO today)

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1 and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-Nh_oqPK8aKfwlToIE_8:-NheoSlWAyh6bGR0Ombk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4652bac88fad55dbf6d44abcf5c4684dc0adab7f/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L468)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

LMK if you need help (I WFO today)
</blockquote></details>

Done.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-:-NhvkdiBEd6StVPtUOFZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1304#-:-Nhvq2iaCc0tG8XBXc7J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
