### PR TITLE
fix(starknet_client): client can parse ExecutionResources::data_availability

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1747)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1747)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1747#-NrjUfrb-UcUSjLh9Irw:-NrjUfrb-UcUSjLh9Irx:b-84gy1w) (no related file):*
Note that this will break the integration test until the Starknet team fixes the FGW. @dan-starkware your call if we can merge this (IMO we can)

___

**Review by dan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1747)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1747)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1747#-NrkUyZ26JJSb8h5SSu3:-NrkUyZ26JJSb8h5SSu4:b-cs862u) ([raw file](https://github.com/starkware-libs/papyrus/blob/f408b7ed67b52287a3282acbdaada50698dcbb06/crates/starknet_client/src/reader/objects/transaction.rs#L617)):*
> ```XML
>     // This field was added in Starknet v0.13.1
>     #[serde(default)]
>     #[serde(skip_serializing_if = "Option::is_none")]
> ```

When do we serialize this struct? 



_Code quote:_
```XML
#[serde(skip_serializing_if = "Option::is_none")]
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1747)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1747#-NrkUyZ26JJSb8h5SSu3:-NrnTLyQ3Oyyg3DQIjpD:brlsfog) ([raw file](https://github.com/starkware-libs/papyrus/blob/f408b7ed67b52287a3282acbdaada50698dcbb06/crates/starknet_client/src/reader/objects/transaction.rs#L617)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

When do we serialize this struct?
</blockquote></details>

Maybe in tests? If we don't then IMO it shouldn't derive Serialize, and if it does we need to make sure the serialization is correct

**Pull request merged**
