### PR TITLE
Bump storage version from 0 to 1

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/version.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/752#-NXl_EMn8oxG_tnvp1MB:-NXl_EMn8oxG_tnvp1MC:b-5avc97) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d9a9ccefc54d90185c8861e04d12041f7935956/crates/papyrus_node/src/version.rs#L1)):*
> ```XML
> #[cfg(test)]
> ```

This is the wrong version, right?

https://github.com/starkware-libs/papyrus/blob/522f6de91cef45fc107c4532a5d07e6e1ecfdc07/crates/papyrus_storage/src/lib.rs#L40

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/version.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/752#-NXl_EMn8oxG_tnvp1MB:-NXnSUWL1Onxzhu75vH4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d9a9ccefc54d90185c8861e04d12041f7935956/crates/papyrus_node/src/version.rs#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is the wrong version, right?

https://github.com/starkware-libs/papyrus/blob/522f6de91cef45fc107c4532a5d07e6e1ecfdc07/crates/papyrus_storage/src/lib.rs#L40
</blockquote></details>

Done.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752#-:-NXnSr1B3RpFwLGG86Pf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/752)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
