### PR TITLE
refactor(storage): use common file handler

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1281)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1281)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1281#-NgxigTK4OjdwSaFcL1A:-NgxigTK4OjdwSaFcL1B:b-sk8tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7404166246cd7ed54932b44deeb2bee14883554/crates/papyrus_storage/src/mmap_file/mod.rs#L102)):*
> ```XML
> /// A wrapper around `MMapFile` that provides both write and read interfaces.
> #[derive(Clone, Debug)]
> pub struct FileHandler<V: StorageSerde> {
> ```

I think this struct should be private (and move down in the file, maybe even into a module)



_Code quote:_
```XML
pub 
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1281)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1281#-NgxigTK4OjdwSaFcL1A:-Nh1G-K89K8MnEAQ7vnG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7404166246cd7ed54932b44deeb2bee14883554/crates/papyrus_storage/src/mmap_file/mod.rs#L102)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this struct should be private (and move down in the file, maybe even into a module)
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1281)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 143 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1281#-Nh1QLWy8ZtwRgsCo_Zo:-Nh1QLWy8ZtwRgsCo_Zp:b-nu7a0j) ([raw file](https://github.com/starkware-libs/papyrus/blob/669a97a73e85ec0d304b25a622a398fd8afe2784/crates/papyrus_storage/src/mmap_file/mod.rs#L143)):*
> ```XML
> /// Represents a memory mapped append only file.
> #[derive(Debug)]
> pub struct MMapFile<V: StorageSerde> {
> ```

Private too?



_Code quote:_
```XML
pub
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1281)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 143 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1281#-Nh1QLWy8ZtwRgsCo_Zo:-Nh1QYSx0n25MMPDWBwJ:bcc1mq3) ([raw file](https://github.com/starkware-libs/papyrus/blob/669a97a73e85ec0d304b25a622a398fd8afe2784/crates/papyrus_storage/src/mmap_file/mod.rs#L143)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Private too?
</blockquote></details>

Sure in the next PR

**Pull request merged**
