### PR TITLE
chore(network): move handle_recieved_data to trait and add tests for it

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8PZUA1PAF14nyHTqE:-Nn8PZUA1PAF14nyHTqF:bapsw25) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L175)):*
> ```XML
>                 protobuf::block_headers_response_part::HeaderMessage::Header(header) => {
>                     *ignore_event_and_return_pending = true;
>                     // ignore the result for now since it allways returns ok.
> ```

Change this comment into a TODO
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8R1MQ83D-XQlyARO-:-Nn8R1MQ83D-XQlyARO0:bx9wwzz) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L185)):*
> ```XML
>                 }
>                 protobuf::block_headers_response_part::HeaderMessage::Signatures(sigs) => {
>                     let Ok(block_header) =
> ```

Consider extracting to a method called handle_signatures_message
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8Q3du7keRYuMgMEDq:-Nn8Q3du7keRYuMgMEDr:b-uv46ro) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L196)):*
> ```XML
>                         .signatures
>                         .iter()
>                         .try_fold(vec![], |mut acc, sig| {
> ```

acc is not a good name. Rename to the full name it represents (I'm not sure what it is, accumulator?)
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8_otWCoj7dD6rogrD:-Nn8_otWCoj7dD6rogrE:bsdzs6w) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L312)):*
> ```XML
>     /// the session is closed.
>     fn close_outbound_session(&mut self, outbound_session_id: OutboundSessionId) {
>         let _newly_inserted =
> ```

Why do you keep _newly_inserted?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8_tYr0M7S_kDaP5jF:-Nn8_tYr0M7S_kDaP5jG:b-y6ilzv) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L314)):*
> ```XML
>         let _newly_inserted =
>             self.outbound_sessions_pending_termination.insert(outbound_session_id);
>         let _ = self
> ```

Why do you keep _?
If the answer to both of these is to ignore a Result, add a TODO to handle the error
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8aJv944tBAp9LJ9T9:-Nn8aJv944tBAp9LJ9TA:baf7zld) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
> ```XML
> 
> #[test]
> fn map_streamed_data_behaviour_event_to_own_event_recieve_data_simple_happy_flow() {
> ```

It's really hard to review it. I think that there are some function extraction you can do to improve general readability. Could you see what you can do and then it will be easier for me to review?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8_tYr0M7S_kDaP5jF:-NnhaVw5639QnAEgsCVh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour.rs#L314)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you keep _?
If the answer to both of these is to ignore a Result, add a TODO to handle the error
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8aJv944tBAp9LJ9T9:-Nnhcaqq39jaZX7b2RFf:b-2nxuj1) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's really hard to review it. I think that there are some function extraction you can do to improve general readability. Could you see what you can do and then it will be easier for me to review?
</blockquote></details>

I tried it and I don't think it does much in the way of simplification.. can you please try to look at it in the IDE and not in reviewable and tell me if you still think the same? I added spacing and comments for that reason

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: all files reviewed, 9 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniACiGCU2rO6OMKZSY:-NniACiGCU2rO6OMKZSZ:b22zotp) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L120)):*
> ```XML
>     ) -> Option<()>;
> 
>     fn fetch_pending_header_for_session(
> ```

Rename to `fetch_header_pending_pairing_with_signature`
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniANUjCSeCW4k5gbs6:-NniANUjCSeCW4k5gbs7:bsurtrh) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L132)):*
> ```XML
>         outbound_session_id: OutboundSessionId,
>         ignore_event_and_return_pending: &mut bool,
>     ) -> Event {
> ```

Don't implement inside the trait
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8aJv944tBAp9LJ9T9:-NniCpsQ6HEUApXmVtX_:b-b57df) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I tried it and I don't think it does much in the way of simplification.. can you please try to look at it in the IDE and not in reviewable and tell me if you still think the same? I added spacing and comments for that reason
</blockquote></details>

I'm ok with this for now. Maybe in the future we can think of how to extract some common functionality
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBzbk2ONf8PW0nIYG:-NniBzbk2ONf8PW0nIYH:baobfil) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L114)):*
> ```XML
>     let outbound_session_id = OutboundSessionId { value: rand::random() };
> 
>     // send header response event to behaviour from streamed data behaviour
> ```

Capitalizing of comments throughout the file
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniAz0B6qapVXXN8zdq:-NniAz0B6qapVXXN8zdr:bugq3zb) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
> ```XML
> 
>     // send header response event to behaviour from streamed data behaviour
>     let streamed_data_event: streamed_data::GenericEvent<
> ```

Extract streamed_data::GenericEvent<... to a type alias (possible name: StreamedDataEvent)
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBtis1T-tyzo9roAc:-NniBtis1T-tyzo9roAd:b-vy0gf0) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L132)):*
> ```XML
>     let res_event = behaviour.map_streamed_data_behaviour_event_to_own_event(
>         streamed_data_event,
>         &mut ignore_event_and_return_pending,
> ```

I assume you're getting rid of it in a future PR, right?
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBLjz6Z1kgag_9xHO:-NniBLjz6Z1kgag_9xHP:bpbyl3h) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L141)):*
> ```XML
>         }
>     );
>     assert_eq!(behaviour.store_header_pending_pairing_with_signature_call_count, 1);
> ```

What's the problem with using automock? It has functionality like checking that we called this function exactly once
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 334 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniCRMzEoAimXJPB2lz:-NniCRMzEoAimXJPB2m-:b-w0awv2) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L334)):*
> ```XML
> 
> #[test]
> fn map_streamed_data_behaviour_event_to_own_event_recieve_data_bad_flow() {
> ```

Instead of writing bad_flow write pairing_error
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 374 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniCi4PCPiqHpcqCBy-:-NniCi4PCPiqHpcqCBy0:b-k5fa7y) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L374)):*
> ```XML
> 
> #[test]
> fn map_streamed_data_behaviour_event_to_own_event_recieve_data_bad_objects() {
> ```

Instead of writing bad_objects write protobuf_conversion_error
___
*[`crates/papyrus_network/src/messages/mod.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniDYE0A5RrfdswUuXg:-NniDYE0A5RrfdswUuXh:b6nnsaq) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/messages/mod.rs#L174)):*
> ```XML
> 
> pub trait TestInstance {
>     fn test_instance() -> Self;
> ```

Why not the GetTestInstance we have in test_utils?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniACiGCU2rO6OMKZSY:-NniTmnqAfwyPIRx4Exe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L120)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to `fetch_header_pending_pairing_with_signature`
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniANUjCSeCW4k5gbs6:-NniTsca0HMIDN3CPBdv:b-k1lmwf) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L132)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Don't implement inside the trait
</blockquote></details>

that's kind of the point.. I can create a test behaviour object that have the same functionality - the default one from the trait.
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-Nn8aJv944tBAp9LJ9T9:-NniU9dF36xPflNN5ke5:bmrdfzk) ([raw file](https://github.com/starkware-libs/papyrus/blob/03a78f1fd7e5a2b8ad3e7c9c9311e8f2b2761f53/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm ok with this for now. Maybe in the future we can think of how to extract some common functionality
</blockquote></details>

agreed but for now I don't really see it simplifying stuff
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniAz0B6qapVXXN8zdq:-NniVGac3yi60Dkq4BOY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract streamed_data::GenericEvent<... to a type alias (possible name: StreamedDataEvent)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBtis1T-tyzo9roAc:-NnrW_233Dr4dQJhP1A0:bstesyh) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L132)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I assume you're getting rid of it in a future PR, right?
</blockquote></details>

didn't work on it yet but yes.. i'm planning to
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBLjz6Z1kgag_9xHO:-NnrWQVO5lfuTIMGiDTo:bsm032u) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's the problem with using automock? It has functionality like checking that we called this function exactly once
</blockquote></details>

because look at the trait implementation.. there's more than just counting calls
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 334 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniCRMzEoAimXJPB2lz:-NnrVocgC_0wUjMUjDOd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L334)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of writing bad_flow write pairing_error
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 374 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniCi4PCPiqHpcqCBy-:-NnrWNTk6qEme1X-brGd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L374)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of writing bad_objects write protobuf_conversion_error
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/messages/mod.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniDYE0A5RrfdswUuXg:-NnrYBJg8ZST0SidG4_-:brli5xy) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/messages/mod.rs#L174)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not the GetTestInstance we have in test_utils?
</blockquote></details>

I'll have to add many types from protobug to the test utils and lay out the full block header struct so use that.. I don't need to I just created the specofoc stuff I needed.. maybe in the future it will make more sense to use it

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniANUjCSeCW4k5gbs6:-Nnt42oaAwBVQJuvsV_4:bn53td3) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L132)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

that's kind of the point.. I can create a test behaviour object that have the same functionality - the default one from the trait.
</blockquote></details>

You can keep it as it is now if you have some test behaviour objects that override this and some that don't. If that's not the case, remove it from the trait or move the implementation to the object
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBLjz6Z1kgag_9xHO:-Nnt5EK1E6QHozwgDz-p:b-9wrj5d) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L141)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

because look at the trait implementation.. there's more than just counting calls
</blockquote></details>

It also has functionality for checking return type...

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniANUjCSeCW4k5gbs6:-No65RHg9mEZekXQstPI:b-sx9uv4) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L132)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can keep it as it is now if you have some test behaviour objects that override this and some that don't. If that's not the case, remove it from the trait or move the implementation to the object
</blockquote></details>

I think you didn't understand mu point.. I'l explain f2f
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBLjz6Z1kgag_9xHO:-No64uVb7cTkVOvQ8Uco:b-h61l00) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It also has functionality for checking return type...
</blockquote></details>

no.. I mean actual functionality
e.g:
```
fn fetch\_header\_pending\_pairing\_with\_signature(

&mut self,

outbound\_session\_id: OutboundSessionId,

) \-> Option<super::BlockHeader\> {

self.fetch\_pending\_header\_for\_session\_call\_count += 1;

self.header\_pending\_pairing

.remove(&outbound\_session\_id)

.and\_then(|header| TryInto::<super::BlockHeader\>::try\_into(header).ok())

}

  

fn store\_header\_pending\_pairing\_with\_signature(

&mut self,

header: protobuf::BlockHeader,

outbound\_session\_id: OutboundSessionId,

) \-> Option<()> {

self.store\_header\_pending\_pairing\_with\_signature\_call\_count += 1;

self.header\_pending\_pairing.insert(outbound\_session\_id, header.clone());

Some(())

}
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniANUjCSeCW4k5gbs6:-No6KEwUDmmmOOIJnVzm:b-c8jts4) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour.rs#L132)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think you didn't understand mu point.. I'l explain f2f
</blockquote></details>

I think you misunderstood mine too :sweat_smile:
What I said is that putting the implementation inside the trait is good only if you override this in some of the cases but not all. If you override it all the time then the implementation should be only for the source struct. If you don't override at all, this shouldn't be a trait method
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-NniBLjz6Z1kgag_9xHO:-No6Jh0p5TOpVtd6O-0r:bnyx9q1) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee5b00dca63202dd0195602d0868646ca4a8e466/crates/papyrus_network/src/block_headers/behaviour_test.rs#L141)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

no.. I mean actual functionality
e.g:
```
fn fetch\_header\_pending\_pairing\_with\_signature(

&mut self,

outbound\_session\_id: OutboundSessionId,

) \-> Option<super::BlockHeader\> {

self.fetch\_pending\_header\_for\_session\_call\_count += 1;

self.header\_pending\_pairing

.remove(&outbound\_session\_id)

.and\_then(|header| TryInto::<super::BlockHeader\>::try\_into(header).ok())

}

  

fn store\_header\_pending\_pairing\_with\_signature(

&mut self,

header: protobuf::BlockHeader,

outbound\_session\_id: OutboundSessionId,

) \-> Option<()> {

self.store\_header\_pending\_pairing\_with\_signature\_call\_count += 1;

self.header\_pending\_pairing.insert(outbound\_session\_id, header.clone());

Some(())

}
```
</blockquote></details>

You can do that too, the return_once/returning function receive a lambda that receives the parameters of the function and return the return type. Just mock here with that.
Also, you can do the asserts inside the mock instead of keeping them in a container and asserting the container later on

**Review by ShahakShama — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1582#-:-NoBLbHH0AEukIEtYgW7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
