### PR TITLE
prefix spec resource with version id

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #829** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/829" target="_blank">Graphite</a> 
    * **PR #830** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/830" target="_blank">Graphite</a> 
      * **PR #831** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/831" target="_blank">Graphite</a> 
        * **PR #832** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/832" target="_blank">Graphite</a> 
          * **PR #833** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/833" target="_blank">Graphite</a> 
            * **PR #834** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/834" target="_blank">Graphite</a> 
              * **PR #837** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/837" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/837?utm_source=stack-comment).

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/test_utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/837#-N_9PRHz1rt8emI41Pmk:-N_9PRHz1rt8emI41Pml:bgh1yss) ([raw file](https://github.com/starkware-libs/papyrus/blob/d44ba99918a836b32d556fa6f4e0c057ec42a7f0/crates/papyrus_gateway/src/test_utils.rs#L39)):*
> ```XML
>     version_id: &str,
> ) -> JSONSchema {
>     let target = format!("./resources/{}_starknet_api_openrpc.json", version_id);
> ```

Can you use the following?



_Suggestion:_
```XML
format!("./resources/{version_id}_starknet_api_openrpc.json");
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @nagmo-starkware)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @DvirYo-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/837#-N_E2Bcs156bG8WqkhED:-N_E2Bcs156bG8WqkhEE:b-o81ac1) ([raw file](https://github.com/starkware-libs/papyrus/blob/10df8a0a9152d598f4dd2a1c476d35c4d04bba27/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L42)):*
> ```XML
>     JsonRpcError, Tag,
> };
> use crate::test_utils::{
> ```

Is this related to the PR?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/837#-N_E2Bcs156bG8WqkhED:-N_X_RIT-K7JgFUm-kOk:b-px7nx4) ([raw file](https://github.com/starkware-libs/papyrus/blob/10df8a0a9152d598f4dd2a1c476d35c4d04bba27/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L42)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this related to the PR?
</blockquote></details>

yes I'm sending the version name to put it in the shcema path

**Review by dan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/837#-:-N_r7r-y1KSVyg44xLCF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
