### PR TITLE
Yair/storage db documentation

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FgBeD2UCzS3vQkYz:-N_3FgBeD2UCzS3vQkZ-:b-1kecys) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L4)):*
> ```XML
> //!
> //! Low database layer for interaction with libmdbx. The API is supposedly generic enough to easily
> //! replace the database library with other Berkley-like database implementations.
> ```

Not sure about this. 



_Code quote:_
```XML
//! Low database layer for interaction with libmdbx. The API is supposedly generic enough to easily
//! replace the database library with other Berkley-like database implementations.
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FsOqEbgkxSM-WMM0:-N_3FsOqEbgkxSM-WMM1:b3rsc6y) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L6)):*
> ```XML
> //! replace the database library with other Berkley-like database implementations.
> //!
> //! Assumptions:
> ```

Consider also adding transactional, sorted and range-based search capabilities



_Code quote:_
```XML
 Assumptions:
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3EbNl6MWBMXVyN59u:-N_3EbNl6MWBMXVyN59v:bpyh6hb) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L7)):*
> ```XML
> //!
> //! Assumptions:
> //! The serialization is consistent across code versions (though, not necessarily across machines).
> ```

Where can this this happen?



_Code quote:_
```XML
though, not necessarily across machines
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3GmGYDer7Y6ORPzDx:-N_3GmGYDer7Y6ORPzDy:b-xclmms) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L86)):*
> ```XML
>     Serialization,
> }
> type Result<V> = result::Result<V, DbError>;
> ```

Consider document and maybe rename.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FgBeD2UCzS3vQkYz:-N_3dLgm82o7X-L7Bs-f:bmuot02) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not sure about this. 
</blockquote></details>

I didn't write this, didn't want to delete
Do you think I should?
___
*[`crates/papyrus_storage/src/db/mod.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FsOqEbgkxSM-WMM0:-N_7zN4W9Ahdhqq6hbJ-:b9qq2kg) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L6)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider also adding transactional, sorted and range-based search capabilities
</blockquote></details>

Do you mean these are assumptions about the DB?
Should I add it to the above paragraph?
___
*[`crates/papyrus_storage/src/db/mod.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3EbNl6MWBMXVyN59u:-N_3dUTT5Dr8D-vW_uRr:bjca219) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L7)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Where can this this happen?
</blockquote></details>

I think Shahar wrote this.
I think that in Windows strings are saved differently so you might not be able to migrate the storage between platforms.
Docker probably solves this, but it is an external solution.
___
*[`crates/papyrus_storage/src/db/mod.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3GmGYDer7Y6ORPzDx:-N_7zxIz4onSNcc0YpA3:b-m2zcby) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L86)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider document and maybe rename.
</blockquote></details>

This alias doesn't appear in the documentation anyways...

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/db/mod.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FgBeD2UCzS3vQkYz:-N_80olW6LUloEDyk0FY:b7gt8sx) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L4)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I didn't write this, didn't want to delete
Do you think I should?
</blockquote></details>

Maybe add `in which the following assumptions hold`

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/db/mod.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FsOqEbgkxSM-WMM0:-N_810sG31aD4A-ND1qn:b-mks669) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L6)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do you mean these are assumptions about the DB?
Should I add it to the above paragraph?
</blockquote></details>

Yes. Please add to the assumptions part. Maybe as a list instead of a paragraph

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/db/mod.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3GmGYDer7Y6ORPzDx:-N_81S_UArCCyxX-atXA:bvu626f) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This alias doesn't appear in the documentation anyways... 
</blockquote></details>

got it, can still rename to be more consistent with what we do in other places.

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3FgBeD2UCzS3vQkYz:-N_85N4t5n2cKcuBiRPD:b-mxtkhy) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Maybe add `in which the following assumptions hold`
</blockquote></details>

Changed, not sure about the result
___
*[`crates/papyrus_storage/src/db/mod.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_3GmGYDer7Y6ORPzDx:-N_85WSeAIlDYeXcTKq5:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/998c0e8c43e9d70065b3c6a9f63b8db2a96e27af/crates/papyrus_storage/src/db/mod.rs#L86)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

got it, can still rename to be more consistent with what we do in other places. 
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_AefVqEiBFQjVEeVnz:-N_AefVrB8U7XMPOtZ2_:b-memk6d) ([raw file](https://github.com/starkware-libs/papyrus/blob/02514ee728e701bcaed6042954a7035cda1d06db/crates/papyrus_storage/src/db/mod.rs#L10)):*
> ```XML
> //! - The API is supposedly generic enough to easily replace the database library with other
> //! Berkley-like database implementations in which the following assumptions hold:
> //!     - The DB is transactional, sorted and has range-based search capabilities.
> ```

Sorry for going back and forth. Please
* Move the `The API is supposedly ... database implementations.` back to where it was. (no need to refer to the assumptions)
* write the new assumptions as:
  * The database is transactional with full ACID semantics.
  * The keys are always sorted and range lookups are supported.



_Code quote:_
```XML
//! Assumptions:
//! - The serialization is consistent across code versions (though, not necessarily across
//!   machines).
//! - The API is supposedly generic enough to easily replace the database library with other
//! Berkley-like database implementations in which the following assumptions hold:
//!     - The DB is transactional, sorted and has range-based search capabilities.
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/825#-N_AefVqEiBFQjVEeVnz:-N_DGonF2XVvRAtq00FF:be0x9pu) ([raw file](https://github.com/starkware-libs/papyrus/blob/02514ee728e701bcaed6042954a7035cda1d06db/crates/papyrus_storage/src/db/mod.rs#L10)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Sorry for going back and forth. Please
* Move the `The API is supposedly ... database implementations.` back to where it was. (no need to refer to the assumptions)
* write the new assumptions as:
  * The database is transactional with full ACID semantics.
  * The keys are always sorted and range lookups are supported.
</blockquote></details>

done, moved the serialization part to a guarantees section - WDYT?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
