### PR TITLE
add class deff block num api

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/674)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #674** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/674" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/674?utm_source=stack-comment).

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/state/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZtEcT1X4kIllvP6nQ:-NVZtEcT1X4kIllvP6nR:b8yzq0v) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/mod.rs#L259)):*
> ```XML
>     ) -> StorageResult<Option<BlockNumber>> {
>         let Some(block_number) = self.declared_classes_block_table.get(self.txn, class_hash)? else {return Ok(None)};
>         Ok(Some(block_number))
> ```

Would something like this work?



_Suggestion:_
```XML
        Ok(self.declared_classes_block_table.get(self.txn, class_hash)?.or(None))
```

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/674)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZw1uAAb8_73Je7E3a:-NVZw1uAAb8_73Je7E3b:bn5gh5a) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/mod.rs#L254)):*
> ```XML
>     }
> 
>     pub fn get_class_definition_block_number(
> ```

Maybe document this is works only for cairo1 classes.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZtEcT1X4kIllvP6nQ:-NVZviDt0Eq3G1Tz_dOu:b-v3oyxt) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/mod.rs#L259)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Would something like this work?
</blockquote></details>

I think even this will work:
Ok(self.declared_classes_block_table.get(self.txn, class_hash)?)
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZwAaG-Irl_jrG1FD1:-NVZwAaG-Irl_jrG1FD2:b-b2d8oo) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/state_test.rs#L94)):*
> ```XML
>     assert_matches!(statetxn.get_class_definition_at(state1, &nc0).unwrap(), Some(_));
>     assert_matches!(statetxn.get_class_definition_at(state2, &nc0).unwrap(), Some(_));
>     assert_matches!(
> ```

Add this to all three states and use assert_eq! instead of assert_matches!

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/674)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZw1uAAb8_73Je7E3a:-NVZxKog8q3v_HkIKG0V:brwedda) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/mod.rs#L254)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Maybe document this is works only for cairo1 classes.
</blockquote></details>

my tendency is to say no since the point of "deprecating" is to not have to keep dealing with old stuff.. but I'm open for opinions. @dan-starkware what do you think?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZtEcT1X4kIllvP6nQ:-NVZx8VZ5JZYzD_RvyX2:b-4llhx1) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/mod.rs#L259)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think even this will work:
Ok(self.declared_classes_block_table.get(self.txn, class_hash)?)
</blockquote></details>

do you think either of this options make it more readable? I'm not sure it does...
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZwAaG-Irl_jrG1FD1:-NVZxqVi40mdxdE1r5Y8:b-vfn3b9) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/state_test.rs#L94)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Add this to all three states and use assert_eq! instead of assert_matches!
</blockquote></details>

agree for the `assert_eq` but what do you gain from calling it 3 times? the state is not a parameter for this function

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/674)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/state_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/674#-NVZwAaG-Irl_jrG1FD1:-NV_-Ar_C1vSmWtRAmxL:bx051cz) ([raw file](https://github.com/starkware-libs/papyrus/blob/be5f64ba0ee670d86c2788e5a493c063c7d8aad2/crates/papyrus_storage/src/state/state_test.rs#L94)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

agree for the `assert_eq` but what do you gain from calling it 3 times? the state is not a parameter for this function
</blockquote></details>

You're right; my mistake.

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/674)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

**Pull request merged**
