### PR TITLE
allow Invoke to be created when sender_address is renamed to contract_address

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/788#-NZ5zU0LEhmYZ4ndlSJL:-NZ5zU0M1AhGXvC3aI-m:bm4e78m) (no related file):*
I'm going to add a test for this PR

___

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/788#-NZKOfXyBojXyje1LXLJ:-NZKOfXyBojXyje1LXLK:b-14qwhe) ([raw file](https://github.com/starkware-libs/papyrus/blob/f98df7838dae80f45e21c67f38d683e3ac1cd5a2/crates/starknet_client/src/objects/transaction.rs#L233)):*
> ```XML
>     pub calldata: Calldata,
>     // In early versions the `sender_address` field was renamed to `contract_address`.
>     #[serde(alias = "contract_address")]
> ```

Early versions of the transaction, or of starknet?
Are there still blocks where it is called sender_address?



_Code quote:_
```XML
    // In early versions the `sender_address` field was renamed to `contract_address`.
    #[serde(alias = "contract_address")]
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/788#-NZKOfXyBojXyje1LXLJ:-NZKPi0H3HKyEeTxnMYH:b3dmkul) ([raw file](https://github.com/starkware-libs/papyrus/blob/f98df7838dae80f45e21c67f38d683e3ac1cd5a2/crates/starknet_client/src/objects/transaction.rs#L233)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Early versions of the transaction, or of starknet?
Are there still blocks where it is called sender_address?
</blockquote></details>

Of starknet
Yes. alias allows us to have 2 possible names

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/788#-NZKOfXyBojXyje1LXLJ:-NZKPuEWBv4mrXqpYfOd:bxesaap) ([raw file](https://github.com/starkware-libs/papyrus/blob/f98df7838dae80f45e21c67f38d683e3ac1cd5a2/crates/starknet_client/src/objects/transaction.rs#L233)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Of starknet
Yes. alias allows us to have 2 possible names
</blockquote></details>

I'll change versions to versions of starknet
Do you think I should mention what does serde(alias) do or assume the reader of the code knows it?

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788#-:-NZKQb4IBr2bpGZd5vyH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/788#-NZKOfXyBojXyje1LXLJ:-NZKQO6y8U9FBv2xayyP:bedgvap) ([raw file](https://github.com/starkware-libs/papyrus/blob/f98df7838dae80f45e21c67f38d683e3ac1cd5a2/crates/starknet_client/src/objects/transaction.rs#L233)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll change versions to versions of starknet
Do you think I should mention what does serde(alias) do or assume the reader of the code knows it?
</blockquote></details>

I think it is self-explanatory

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/788#-:-NZKTi5W5coFZ6W8yaRE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

**Pull request merged**
