### PR TITLE
feat(monitoring): update the grafana json

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OriStarkware)

___
*[`Monitoring/grafana.json` line 1125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-Ndaz37t9TqPX-VD5tch:-Ndaz37t9TqPX-VD5tci:b-1t0jk8) ([raw file](https://github.com/starkware-libs/papyrus/blob/6fc0f75df12d6536dc72b33f9cd1f7a2a66ef078/Monitoring/grafana.json#L1125)):*
> ```JSON
>             "matcher": {
>               "id": "byName",
>               "options": "papyrus-mainnet-16g-bm"
> ```

what this stands for?
Please clean all options/ vars/ titles before export to public repo



_Code quote:_
```JSON
papyrus-mainnet-16g-bm
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`Monitoring/grafana.json` line 1125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-Ndaz37t9TqPX-VD5tch:-Ndy9DaxCGrqmV2heGOr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6fc0f75df12d6536dc72b33f9cd1f7a2a66ef078/Monitoring/grafana.json#L1125)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

what this stands for?
Please clean all options/ vars/ titles before export to public repo
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-:-Ndyc5XmCTg3ZUYV_68H:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)* status: all files reviewed, 4 unresolved discussions (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDHQ_n-S7_9wcULsyS:-NeDHQ_n-S7_9wcULsyT:b-mu3egs) (no related file):*
I think we don't need the 'pod' dropdown. There's just 1 option per namespace anyway. You can just select it by default and not present it.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDIEk6BQKi30WJ_xXk:-NeDIEk6BQKi30WJ_xXl:b-tq1azr) (no related file):*
'Requests and latencies' section only displays count of requests, right? (no latencies)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDIrX14lCVepdExr9r:-NeDIrX22S2upB3W-kvy:b-yi6bst) (no related file):*
Remove the word 'containers' from metrics.
E.g. 'Resources usage' instead of 'Containers resources usage', 'CPU usage' instead of 'Containers CPU usage'...

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDJGCd23FTo4UWSI9V:-NeDJGCd23FTo4UWSI9W:b-9u6lcr) (no related file):*
Add description to panels. (Can be done in a separate PR).

___

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDIrX14lCVepdExr9r:-NeDspJb9UiKKwLUp-cH:bg9nqhr) (no related file):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

Also in the title:
'Containers resources usage' -> 'Resources usage'

___

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-:-NeDuz1cAd1kJEiVFLEb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1135)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1135#-NeDvHDrDN6H1HG2lqKo:-NeDvHDs7YqBxNcYC_hB:bgmubx1) (no related file):*
wait with the merge

___

**Pull request merged**
