### PR TITLE
test(starknet_client): integration test with the starknet GW

### PR DESCRIPTION
**Pull request by TzahiTaub**
## Pull Request type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [X ] Other (please describe): integration test

## What is the new behavior?

The test sends an Eth transfer transaction to the node that sends it in its turn to the Starknet GW. Runs twice for ubuntu and macos on distinct times (as there will be a race between the sender nonces if both tests will run in parallel).

## Does this introduce a breaking change?

- [ ] Yes
- [X ] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @TzahiTaub)

___
*[`Cargo.lock` line 648 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNJa9Z1Del-JNKYeQq:-NgNJa9_CD8KsuC_a2Or:b-so2t6d) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/Cargo.lock#L648)):*
> ```TOML
>  "serde_json",
>  "sha3",
>  "starknet-crypto 0.5.1",
> ```

Why did you need to add a specific version here?
(just to understand)
___
*[`Cargo.lock` line 1702 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNJpQN4tn6vSaUV1EE:-NgNJpQN4tn6vSaUV1EF:bv0dymj) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/Cargo.lock#L1702)):*
> ```TOML
> ]
> 
> [[package]]
> ```

Just to confirm - Did you intentionally add this package ("darling") in 2 different version?
Why did you need to do this?
(Same for "darling_core", "starknet-crypto")
(just to understand)
___
*[`crates/papyrus_rpc/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNMPU16AGIUGfCq85b:-NgNMPU16AGIUGfCq85c:b-a1uvhf) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/papyrus_rpc/src/lib.rs#L56)):*
> ```XML
>     TransactionReceipt,
> };
> pub use crate::v0_4_0::write_api_result::AddInvokeOkResult;
> ```

I assume there's a good reason for this :)
Please explain.



_Code quote:_
```XML
pub use crate::v0_4_0::transaction::{
    InvokeTransaction,
    InvokeTransactionV1,
    TransactionOutput,
    TransactionReceipt,
};
pub use crate::v0_4_0::write_api_result::AddInvokeOkResult;
```
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_wql0vtW1o3Pwjtg:-NgN_wql0vtW1o3Pwjth:blc8ik) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L29)):*
> ```XML
> const MAX_FEE: u128 = ETH_TO_WEI / 1000;
> const INSUFFICIENT_FUNDS_STATUS_CODE: i32 = 2;
> const L2_ETH_CONTRACT_ADDRESS: &str =
> ```

Are these all existing contracts / users in Goerli?
(I tried to look for them. Only found one of them.)
Also, these are private-keys, right, not addresses?
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNZz08AfrMyEkg31H7:-NgNZz08AfrMyEkg31H8:b-1kfxdu) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L57)):*
> ```XML
> #[tokio::test]
> #[ignore]
> // Sends a 'transfer of eth transaction from user A to user B' to a node instance.
> ```

Add a bit more documentation about what this test for and what it's doing.
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_3EH6kA04p9GiLgD:-NgN_3EH6kA04p9GiLgE:b-dyhffy) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L64)):*
> ```XML
>         HttpClientBuilder::default().build(format!("https://{}:443/rpc/v0_4", node_url)).unwrap();
>     let sender_address = contract_address!(USER_A_ADDRESS);
>     let sender_balance = get_eth_balance(&client, sender_address).await;
> ```

The balance should be added manually to the user, right? Maybe document this.
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_FXN9DhlYH3wI2oJ:-NgN_FXN9DhlYH3wI2oK:b-z5v3mi) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L125)):*
> ```XML
>         .await
>         .unwrap();
> ```

Can you run checks here that the transfer actually occured?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`Cargo.lock` line 648 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNJa9Z1Del-JNKYeQq:-NgOBwm3EvicOis8I3bL:bnb54ek) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/Cargo.lock#L648)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Why did you need to add a specific version here?
(just to understand)
</blockquote></details>

I didn't add anything manually in this file - it was auto updated when I built the dir. I have no idea why things were updated the way they were.
___
*[`Cargo.lock` line 1702 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNJpQN4tn6vSaUV1EE:-NgOr0Xn0hcKSf_LO9Xn:bbkppy5) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/Cargo.lock#L1702)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Just to confirm - Did you intentionally add this package ("darling") in 2 different version?
Why did you need to do this?
(Same for "darling_core", "starknet-crypto")
(just to understand)
</blockquote></details>

As above - this is auto generated.
___
*[`crates/papyrus_rpc/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNMPU16AGIUGfCq85b:-NgOCELvArds5l2eRX4C:b-lx68fw) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/papyrus_rpc/src/lib.rs#L56)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I assume there's a good reason for this :)
Please explain.
</blockquote></details>

I'm reexporting these private structs, so the test (which is in a different crate) can access them. Removed the ones not currently used.
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_wql0vtW1o3Pwjtg:-NgOCYhB3dtU043214sy:bk0mdrh) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L29)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Are these all existing contracts / users in Goerli?
(I tried to look for them. Only found one of them.)
Also, these are private-keys, right, not addresses?
</blockquote></details>

These are for starknet-integration over goerli. The contract and selectors are the same for all other starknet tesnets over goerli. The addresses are addresses and not private keys (the private key used is stored as a secret in the 
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgNZz08AfrMyEkg31H7:-NgOqK_c9mipRj2yYH5K:b-1cpayq) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L57)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Add a bit more documentation about what this test for and what it's doing.
</blockquote></details>

Is this better?
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_3EH6kA04p9GiLgD:-NgOqb46A1lEQzT-Jjh-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L64)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

The balance should be added manually to the user, right? Maybe document this.
</blockquote></details>

Done.
___
*[`crates/starknet_client/tests/gateway_integration_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgN_FXN9DhlYH3wI2oJ:-NgOqciG2TUPKesvpEO6:b-axw3i) ([raw file](https://github.com/starkware-libs/papyrus/blob/2a7cf20fb7148d6161c43d007a9f4b9864e80ac9/crates/starknet_client/tests/gateway_integration_test.rs#L125)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Can you run checks here that the transfer actually occured?
</blockquote></details>

A part of the todo - once we'll have "pending" support.

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by OmriEshhar1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgSu_M98gyFmqAHAcMI:-NgSu_M98gyFmqAHAcMJ:b-p50hbb) (no related file):*
Can you TAL [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) to avoid cloning the workflow? 

___
___
*[`crates/starknet_client/Cargo.toml` line 51 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgSv4oYC-t04zxSghCc:-NgSv4oYC-t04zxSghCd:bm26bkv) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c09b679347c7c0084384317bb32b182db699f9f/crates/starknet_client/Cargo.toml#L51)):*
> ```TOML
> rand_chacha.workspace = true
> papyrus_common = { path = "../papyrus_common"}
> papyrus_rpc = { path = "../papyrus_rpc"}
> ```

This does not result in a circular dependency? 



_Code quote:_
```TOML
papyrus_rpc = { path = "../papyrus_rpc"}
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgSu_M98gyFmqAHAcMI:-NgVtzoD5Ztkf1-BfSpw:b5f5xxc) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you TAL [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) to avoid cloning the workflow?
</blockquote></details>

Best solution I found is defining a `workflow_call` - as the `runs-on` can't have expression or conditions in it.

___

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @OmriEshhar1, and @TzahiTaub)

___
*[`crates/starknet_client/Cargo.toml` line 51 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgSv4oYC-t04zxSghCc:-NgW-VAW8vrIkx4eBj01:b-2qi5la) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c09b679347c7c0084384317bb32b182db699f9f/crates/starknet_client/Cargo.toml#L51)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This does not result in a circular dependency?
</blockquote></details>

Apperantly not, but moved to papyrus_rpc as discussed.

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @TzahiTaub)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 6 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 3 of 10 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`.github/workflows/nightly-tests.yml` line 2 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgnVTck3DWqp1YZ3TqX:-NgnVTck3DWqp1YZ3TqY:b32whk) ([raw file](https://github.com/starkware-libs/papyrus/blob/8faccea4c58d52e0b360d7c1220365973093df56/.github/workflows/nightly-tests.yml#L2)):*
> ```YAML
> name: nightly-tests
> # We run gateway_integration_test in different times, to avoid a nonce race between parallel runs.
> ```

at



_Code quote:_
```YAML
in
```
___
*[`.github/workflows/nightly-tests.yml` line 14 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgnW8ebBXVRiZneYeqZ:-NgnW8ebBXVRiZneYeq_:bscd7pw) ([raw file](https://github.com/starkware-libs/papyrus/blob/8faccea4c58d52e0b360d7c1220365973093df56/.github/workflows/nightly-tests.yml#L14)):*
> ```YAML
>     with:
>       os: ubuntu-latest
>     if: github.event.schedule != '30 3 * * *'
> ```

isn't it better to do
if: github.event.schedule == '30 0 * * *'
?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`.github/workflows/nightly-tests.yml` line 2 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgnVTck3DWqp1YZ3TqX:-NgndDWB8-zJRf3WLi2O:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8faccea4c58d52e0b360d7c1220365973093df56/.github/workflows/nightly-tests.yml#L2)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

at
</blockquote></details>

Done.
___
*[`.github/workflows/nightly-tests.yml` line 14 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-NgnW8ebBXVRiZneYeqZ:-NgndGbtEtdQgWAHp2B7:bi2t5rf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8faccea4c58d52e0b360d7c1220365973093df56/.github/workflows/nightly-tests.yml#L14)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

isn't it better to do
if: github.event.schedule == '30 0 * * *'
?
</blockquote></details>

There is also an option to manually trigger the test (the `workflow_dispatch` under the `on` part).  In that case, I want to run over ubuntu - i.e., ubuntu should be the default unless the trigger is schedule at 3:30 AM.

**Review by OmriEshhar1 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258#-:-NgneFYr0tvF8JlM00Ub:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 8 files at r5, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 8 files at r5, 3 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
