### PR TITLE
feat(consensus): add run_consensus

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2108#-O-H6gW98hvxKFQTA5Ft:-O-H6gWAEZRyFVisZDBg:b-jbn808) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e6b44e54b5a428db60c307c5f9ba6b93bd87fc3/crates/sequencing/papyrus_consensus/src/lib.rs#L43)):*
> ```XML
>                 .expect("Failed to receive a message from network")
>                 .expect("Network receiver closed unexpectedly");
>             let (proposal_init, content_receiver, fin_receiver) = proposal.into();
> ```

Since we don't fill `content_receiver` anywhere else, this means that `into` pre-fills the receiver will all of the transactions, right? (I think this is fine for now since this is a fake flow anyways)



_Code quote:_
```XML
            let (proposal_init, content_receiver, fin_receiver) = proposal.into();
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2108#-O-H6gW98hvxKFQTA5Ft:-O-Uls9b-QmVp8SWm2gh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e6b44e54b5a428db60c307c5f9ba6b93bd87fc3/crates/sequencing/papyrus_consensus/src/lib.rs#L43)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Since we don't fill `content_receiver` anywhere else, this means that `into` pre-fills the receiver will all of the transactions, right? (I think this is fine for now since this is a fake flow anyways)
</blockquote></details>

Done.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2108#-O-H6gW98hvxKFQTA5Ft:-O-Um-EB6KPav074hOlX:bb7pcsz) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e6b44e54b5a428db60c307c5f9ba6b93bd87fc3/crates/sequencing/papyrus_consensus/src/lib.rs#L43)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

true

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
