### PR TITLE
add readme describing how to setup the environment

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/544)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/544#-:-NQJsui78BcWInMHyOM8:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @anatgstarkware, @dan-starkware, and @DvirYo-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/544)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @anatgstarkware, @DvirYo-starkware, and @ShahakShama)

___
*[`docs/CONTRIBUTING.md` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQK4Zdo0kYrA5toLy01:-NQK4Zdo0kYrA5toLy02:b7vkvbi) ([raw file](https://github.com/starkware-libs/papyrus/blob/78ac5fab865e21d3c57241ef5398c5872c8814c4/docs/CONTRIBUTING.md#L45)):*
> ```Markdown
> 
> Then, you will need to install
> - [Rust 1.67](https://www.rust-lang.org/tools/install)
> ```

Consider editing this to make it clear that the version should be >=1.67 (we test against 1.67)



_Code quote:_
```Markdown
Rust 1.67]
```
___
*[`docs/CONTRIBUTING.md` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQK5eq40Jy8l1JOmn7D:-NQK5eq40Jy8l1JOmn7E:b1m3cc4) ([raw file](https://github.com/starkware-libs/papyrus/blob/78ac5fab865e21d3c57241ef5398c5872c8814c4/docs/CONTRIBUTING.md#L47)):*
> ```Markdown
> - [Rust 1.67](https://www.rust-lang.org/tools/install)
> - [Rust nightly toolchain 2022-07-27](https://rust-lang.github.io/rustup/installation/index.html#installing-nightly)
> - [Ganache 7.4.3](https://www.npmjs.com/package/ganache) (Note that you'll need to install 7.4.3 and not a version above it)
> ```

IMO it should also say that 
* We will relax the version dependency
* Where do we use this (For example, if someone is doing a config PR she probably doesn't really need this dependency) 



_Code quote:_
```Markdown
[Ganache 7.4.3]
```
___
*[`docs/CONTRIBUTING.md` line 54 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQK4IVl2dO4jY9M2fTa:-NQK4IVl2dO4jY9M2fTb:brumczb) ([raw file](https://github.com/starkware-libs/papyrus/blob/78ac5fab865e21d3c57241ef5398c5872c8814c4/docs/CONTRIBUTING.md#L54)):*
> ```Markdown
> - Be formatted according to [rustfmt](https://github.com/rust-lang/rustfmt).
> - Be linted according to [clippy](https://github.com/rust-lang/rust-clippy)
> - Not include unused dependencies.
> ```

Not sure we need to explicitly state the CI tests, but if so you can add here `[udeps](https://github.com/est31/cargo-udeps)`



_Code quote:_
```Markdown
Not include unused dependencies.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/544)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @anatgstarkware and @DvirYo-starkware)

___
*[`docs/CONTRIBUTING.md` line 54 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQK4IVl2dO4jY9M2fTa:-NQKE6Ls1IkLg9UN4goD:b-auhj4f) ([raw file](https://github.com/starkware-libs/papyrus/blob/78ac5fab865e21d3c57241ef5398c5872c8814c4/docs/CONTRIBUTING.md#L54)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not sure we need to explicitly state the CI tests, but if so you can add here `[udeps](https://github.com/est31/cargo-udeps)`
</blockquote></details>

I think it's nice for the users to know how their code should be formatted before submitting a PR and finding out it doesn't pass CI. Note that I only mentioned the stages that IMO most developers will find out that their CI fails because of them if they don't know about them

**Comment by yair-starkware** [comment]
*[`docs/CONTRIBUTING.md` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQKEvCb21qdMQ0C_0i_:-NQKcHA45HT-ouqih6gP:bw03k6m) ([raw file](https://github.com/starkware-libs/papyrus/blob/56606e326c3a03e82b2874c583eae00c3e24171d/docs/CONTRIBUTING.md#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The link here doesn't work, how can I make it work?
</blockquote></details>

npm install -g ganache@7.4.3

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/544#-:-NQVnA6s9PQqnNIUZiev:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware and @DvirYo-starkware)

**Comment by dan-starkware** [comment]
*[`docs/CONTRIBUTING.md` line 49 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/544#-NQVnIfMBUuPmVL7M0DZ:-NQVnIfMBUuPmVL7M0D_:b-d02ew3) ([raw file](https://github.com/starkware-libs/papyrus/blob/130f0b383111e97a4525bc06ab289fade4b2c812/docs/CONTRIBUTING.md#L49)):*
> ```Markdown
> - [Ganache 7.4.3](https://www.npmjs.com/package/ganache)
>   - You'll need to install 7.4.3 and not a version above it. We'll relax this in the future.
>   - You'll need Ganache only for the [papyrus_base_layer](../crates/papyrus_base_layer/) crate.
> ```

Consider `the tests of`



_Code quote:_
```Markdown
the 
```

**Pull request merged**
