### PR TITLE
Documentation for header, body and state modules of the storage crate

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/835)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/835)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8mArJ-YWv9tVH2xBU:-N_8mArJ-YWv9tVH2xBV:b9iap44) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/header.rs#L20)):*
> ```XML
> //! #     chain_id: ChainId("SN_MAIN".to_owned()),
> //! #     min_size: 1 << 20,    // 1MB
> //! #     max_size: 1 << 35,    // 32GB
> ```

Consider changing to smaller numbers.
___
*[`crates/papyrus_storage/src/body/events.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8pbIf9GBZ7u6ySlvB:-N_8pbIf9GBZ7u6ySlvC:by7gaia) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/body/events.rs#L3)):*
> ```XML
> //! Interface for iterating over events from the storage.
> //!
> //! Events are part of the transaction output. Each transaction output holds an array of events.
> ```

I don’t think this should be here. If the transaction outputs will not contain any events, you can still use this module to iterate over events.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8tya69TABrDSP6u-o:-N_8tya69TABrDSP6u-p:bti27r3) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L120)):*
> ```XML
> {
>     /// Appends a state diff to the storage.
>     /// *Arg deployed_contract_class_definitions: Until Starknet version 0.11 users could implicitly
> ```

I believe you want to add a space after the *. Currently, it looks like * and not a dot.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8teIk9hlBulM3RjHd:-N_8teIk9hlBulM3RjHe:b-865upl) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L121)):*
> ```XML
>     /// Appends a state diff to the storage.
>     /// *Arg deployed_contract_class_definitions: Until Starknet version 0.11 users could implicitly
>     /// declare new classes by deploying contracts. To append a state diff with such classes, you
> ```

"To enforce that no commit happen after a failure, we consume and return Self on success."
Consider putting this in an inner doc like in similar functions.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/835)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8mArJ-YWv9tVH2xBU:-N_9cEg94SdSlDLlGyjd:bd74uyd) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/header.rs#L20)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider changing to smaller numbers.
</blockquote></details>

These are the same values we use in the tests (see get_test_config).
___
*[`crates/papyrus_storage/src/body/events.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8pbIf9GBZ7u6ySlvB:-N_9cRcyCZ2QmipyB0nT:btnk61t) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/body/events.rs#L3)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don’t think this should be here. If the transaction outputs will not contain any events, you can still use this module to iterate over events.
</blockquote></details>

I'm not sure I understand what you mean.
Do you mean in the case of an empty array?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8tya69TABrDSP6u-o:-N_9dZXd3TLCeDo9bknQ:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L120)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I believe you want to add a space after the *. Currently, it looks like * and not a dot.
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/state/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8teIk9hlBulM3RjHd:-N_9d_ly7cs85IvkXO66:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L121)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

"To enforce that no commit happen after a failure, we consume and return Self on success."
Consider putting this in an inner doc like in similar functions.
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/835)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_AY1YM28moBLtuXKNM:-N_AY1YM28moBLtuXKNN:bd5vww2) ([raw file](https://github.com/starkware-libs/papyrus/blob/3338f058b7ed34cb017316b6ed33d8e18337973b/crates/papyrus_storage/src/header.rs#L9)):*
> ```XML
> //! ```
> //! use papyrus_storage::open_storage;
> //! # use papyrus_storage::db::DbConfig;
> ```

This means the users cannot copy paste code from documentation, right?
Is there a way to integrate a `show hidden lines` functionality? 



_Code quote:_
```XML
# use papyrus_storage::db::DbConfig;
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8teIk9hlBulM3RjHd:-N_AbT2z9W4Ril0KpA-M:b5mfghh) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L121)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done
</blockquote></details>

Instead of repeating this maybe we want to have it once in a higher component in the crate documentation.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_AY1YM28moBLtuXKNM:-N_DBzp15qhNJdPEBqTV:bybt2gm) ([raw file](https://github.com/starkware-libs/papyrus/blob/3338f058b7ed34cb017316b6ed33d8e18337973b/crates/papyrus_storage/src/header.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This means the users cannot copy paste code from documentation, right?
Is there a way to integrate a `show hidden lines` functionality? 
</blockquote></details>

I didn't find this option.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/835#-N_8teIk9hlBulM3RjHd:-N_DFKpZ1zwqpsukp6uz:biag3mc) ([raw file](https://github.com/starkware-libs/papyrus/blob/bab2d152c7597a02f4b2bc78abd86f67b2a92166/crates/papyrus_storage/src/state/mod.rs#L121)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Instead of repeating this maybe we want to have it once in a higher component in the crate documentation. 
</blockquote></details>

Will do that in another PR (across all writers)

**Pull request merged**
