### PR TITLE
feat(consensus): add validator flow to SingleHeightConsensus

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2059?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2059** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2059?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2058** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2058?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz88mp82EQU7jcWH2fE:-Nz88mp82EQU7jcWH2fF:bto401l) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L62)):*
> ```XML
>             .expect("failed to send proposal to peering");
>         let block = block_receiver.await.expect("failed to build block");
>         // TODO: Switch this to the Proposal signature.
> ```

TODO(matan)
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz890Pt1jQ1RDM66iNQ:-Nz890Pt1jQ1RDM66iNR:b402kif) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L69)):*
> ```XML
>     async fn validate(&mut self, proposer_id: NodeId) -> BlockT {
>         let Some(msg) = self.from_peering_receiver.next().await else {
>             panic!("Peering component disconnected from SingleHeightConsensus");
> ```

Why not just regular expect()?
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz89a8f6YWm-CWWnYeX:-Nz89a8f6YWm-CWWnYeY:b5xfrt0) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L78)):*
> ```XML
>         };
>         assert_eq!(init.height, self.height);
>         assert_eq!(init.proposer, proposer_id);
> ```

We don't use assert in not test code.
In this case, we should return an error and start the shc again
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8B57_3a7MzIbkoeCE:-Nz8B57_3a7MzIbkoeCF:b-7yh91y) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L109)):*
> ```XML
> 
>     // Send the proposal from the peer.
>     let (fin_sender, fin_receiver) = oneshot::channel();
> ```

why this isn't part of the TestFields
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8Aqjy8YjGSIQtInOZ:-Nz8Aqjy8YjGSIQtInO_:bswlbqi) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L120)):*
> ```XML
>     fin_sender.send(block.id()).unwrap();
> 
>     // This calls to `context.proposer` and `context.build_proposal`.
> ```

why not assert_eq for the block itself?
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8CAAD1Twq7Uv2qblH:-Nz8CAAD1Twq7Uv2qblI:b-qmphhp) ([raw file](https://github.com/starkware-libs/papyrus/blob/cbdc72a6007dbb26b9981b3253414ea945398ba6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L94)):*
> ```XML
>     let node_id: NodeId = 1;
>     let proposer: NodeId = 2;
>     let block: TestBlock = 2;
> ```

just wrap u32 and not type alias



_Code quote:_
```XML
TestBlock = 2;
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz89Aht6YHiHixUEY4K:-Nz89Aht6YHiHixUEY4L:bctv6aw) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/types.rs#L139)):*
> ```XML
> // Peering components.
> pub(crate) enum PeeringConsensusMessage<ProposalChunkT> {
>     // TODO: Switch the oneshot channel to be a Signature when we add.
> ```

again matan



_Code quote:_
```XML
// TODO
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz890Pt1jQ1RDM66iNQ:-NzCpyWy53vSuNzr4YFJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L69)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why not just regular expect()?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz89a8f6YWm-CWWnYeX:-NzCw55i1-r-rp50YI4f:b-lkfy08) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L78)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

We don't use assert in not test code.
In this case, we should return an error and start the shc again
</blockquote></details>

I updated the next PR which adds errors to do exactly that.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8B57_3a7MzIbkoeCE:-NzCqj3y6eC94VuN7EQD:bjtn18o) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L109)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why this isn't part of the TestFields
</blockquote></details>

Reviewable is not showing me the text under this, but I did a minor refactor of TestFields which I hope helps.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8Aqjy8YjGSIQtInOZ:-NzCqF_r1Lh_42KwNLCU:bd8ob8o) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L120)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why not assert_eq for the block itself?
</blockquote></details>

I think the check you are referring to is above:
```
    assert_eq!(shc.run().await, block);
```

Here I am checking what is sent via peering. Peering doesn't sent the fully built block.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8CAAD1Twq7Uv2qblH:-NzCqfwRBIgaFMz1C83Y:brsy3bi) ([raw file](https://github.com/starkware-libs/papyrus/blob/cbdc72a6007dbb26b9981b3253414ea945398ba6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L94)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

just wrap u32 and not type alias
</blockquote></details>

As discussed we changed this back to the old vec implementation.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz89Aht6YHiHixUEY4K:-NzCrR9HEghYy8wwtsiD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/types.rs#L139)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

again matan
</blockquote></details>

Done.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8Aqjy8YjGSIQtInOZ:-NzN0Vny8gwxoe7Jb5cY:bcyun7e) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L120)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think the check you are referring to is above:
```
    assert_eq!(shc.run().await, block);
```

Here I am checking what is sent via peering. Peering doesn't sent the fully built block.
</blockquote></details>

I don't understand what you are saying. `shc.run()` will return the block that passed consensus.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-NzN-9m0EWYBVuNFTrJ3:-NzN-9m0EWYBVuNFTrJ4:b-eym94e) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb3fe26664d5aa9c5ae7436d7713e47dde46c6ed/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L39)):*
> ```XML
> 
>     // This should be called after all of the mock's expectations have been set.
>     async fn begin_test(
> ```

Why should this be called after mock sets?
I prefer the previous function name.

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-Nz8Aqjy8YjGSIQtInOZ:-NzNC4ia7pPuyvWL8fzT:b-nytf8x) ([raw file](https://github.com/starkware-libs/papyrus/blob/fd9e2f13d9aeb5fe303e16e04488c7dd421fcff3/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L120)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don't understand what you are saying. `shc.run()` will return the block that passed consensus.
</blockquote></details>

Sorry Reviewable showed me the wrong text quoted before. I updated it now.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-NzN-9m0EWYBVuNFTrJ3:-NzN9CGhAdbOj3HIkwzW:b-ap6wkt) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb3fe26664d5aa9c5ae7436d7713e47dde46c6ed/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L39)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why should this be called after mock sets?
I prefer the previous function name.
</blockquote></details>

I expanded the comment to explain why.

I changed the name back to `new_shc`.

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2059#-:-NzNDe0P4TaHGz5cQo5u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
