### PR TITLE
Dvir/create request vector

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)

### CODE REVIEW

**Comment by DvirYo-starkware** [comment]
first commit: just add a function to create the vector of request
second commit: add a general way to create a function that returns a Transaction

**Comment by DvirYo-starkware** [comment]
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

first commit: just add a function to create the vector of request
second commit: add a general way to create a function that returns a Transaction
</blockquote></details>

the second commit also include minor changes in the names (like in this code)



_Code quote (from crates/papyrus_load_test/src/scenarios.rs):_
```XML
use crate::transactions;

pub fn block_by_number() -> Scenario {
    scenario!("block_by_number")
        .register_transaction(transactions::get_block_with_tx_hashes_by_number())
}

pub fn block_by_hash() -> Scenario {
    scenario!("block_by_hash")
        .register_transaction(transactions::get_block_with_tx_hashes_by_hash())
}
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/scenarios.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdF71j9owkCAzXu1Lk:-NOdF71j9owkCAzXu1Ll:b-9fiscm) ([raw file](https://github.com/starkware-libs/papyrus/blob/4447a6b10f7ca1763bf111a55e12e18a40a6e53d/crates/papyrus_load_test/src/scenarios.rs#L13)):*
> ```XML
> pub fn block_by_hash() -> Scenario {
>     scenario!("block_by_hash")
>         .register_transaction(transactions::get_block_with_tx_hashes_by_hash())
> ```

only naming changes



_Code quote:_
```XML
use crate::transactions;

pub fn block_by_number() -> Scenario {
    scenario!("block_by_number")
        .register_transaction(transactions::get_block_with_tx_hashes_by_number())
}

pub fn block_by_hash() -> Scenario {
    scenario!("block_by_hash")
        .register_transaction(transactions::get_block_with_tx_hashes_by_hash())
}
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdF_u7C4ZMA-rSrQiR:-NOdF_u7C4ZMA-rSrQiS:b-m5r8pa) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c9003e1f918e396e98e2f9a3d1a3d5eea40cfa0/crates/papyrus_load_test/src/transactions.rs#L25)):*
> ```XML
>             "starknet_getBlockWithTxHashes",
>             json!([{ "block_hash": "0x47c3637b57c2b079b93c61539950c17e868a28f46cdef28f88521067f21e943" }]),
>         ),
> ```

now this function is create by the macro "create_read_from_file_transaction!"



_Code quote:_
```XML
pub fn block_by_hash() -> Transaction {
    let requests = vec![
        jsonrpc_request(
            "starknet_getBlockWithTxHashes",
            json!([{ "block_hash": "0x47c3637b57c2b079b93c61539950c17e868a28f46cdef28f88521067f21e943" }]),
        ),
        jsonrpc_request(
            "starknet_getBlockWithTxHashes",
            json!([{ "block_hash": "0x2a70fb03fe363a2d6be843343a1d81ce6abeda1e9bd5cc6ad8fa9f45e30fdeb" }]),
        ),
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdFsgQC__Jxyv2CYSB:-NOdFsgQC__Jxyv2CYSC:br8p677) ([raw file](https://github.com/starkware-libs/papyrus/blob/4447a6b10f7ca1763bf111a55e12e18a40a6e53d/crates/papyrus_load_test/src/transactions.rs#L61)):*
> ```XML
> }
> 
> create_read_from_file_transaction! {
> ```

create the function that was deleted



_Code quote:_
```XML
create_read_from_file_transaction! {
    get_block_with_tx_hashes_by_hash, "crates/papyrus_load_test/src/resources/block_hash.txt";
}
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdFxwu-FcEnJ14Eey5:-NOdFxwu-FcEnJ14Eey6:b-corm1q) ([raw file](https://github.com/starkware-libs/papyrus/blob/4447a6b10f7ca1763bf111a55e12e18a40a6e53d/crates/papyrus_load_test/src/transactions.rs#L43)):*
> ```XML
>     }
>     requests
> }
> ```

This macro is because we gonna have more than 10 functions with exactly the same structure

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyYNHx9CDzq1b_Eu36:-NOyYNHx9CDzq1b_Eu37:bwh79qj) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L36)):*
> ```XML
> 
> fn create_requests_vector(path: &str, convert_to_request: fn(&str) -> jsonVal) -> Vec<jsonVal> {
>     let file = File::open(path).unwrap();
> ```

Consider proper error handling



_Code quote:_
```XML
.unwrap()
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyY7tJ3wZv_RLSbzOy:-NOyY7tJ3wZv_RLSbzOz:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L35)):*
> ```XML
> }
> 
> fn create_requests_vector(path: &str, convert_to_request: fn(&str) -> jsonVal) -> Vec<jsonVal> {
> ```

Please document.



_Code quote:_
```XML
 Vec<jsonVal> 
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 40 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyYxQxDC_2vSkXo0F3:-NOyYxQxDC_2vSkXo0F4:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L40)):*
> ```XML
>     let mut requests = Vec::<jsonVal>::new();
>     for line in reader.lines() {
>         requests.push(convert_to_request(&line.unwrap()));
> ```

Same



_Code quote:_
```XML
unwrap())
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/transactions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdFxwu-FcEnJ14Eey5:-NOyafNk6QYVInkT2Fcw:bin2oyr) ([raw file](https://github.com/starkware-libs/papyrus/blob/b92a69ca5a542866549639adced2697ecb3da49d/crates/papyrus_load_test/src/transactions.rs#L43)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This macro is because we gonna have more than 10 functions with exactly the same structure
</blockquote></details>

IMO the rule of three applies here.
Currently there is only one usage.
It would be nice to see a PR that only refactor duplicate code. 
___
*[`crates/papyrus_load_test/src/transactions.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyaOa46wjcYKKZI4b6:-NOyaOa53s3P8h7tmN7_:bxpuae1) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L55)):*
> ```XML
>         pub fn $name() -> Transaction {
>             let requests = create_requests_vector($file_name, create_request::$name);
>             random_request_transaction(requests).set_name(stringify!($name))
> ```

This was missing in the current code, right? 



_Code quote:_
```XML
set_name
```

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/transactions.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyY7tJ3wZv_RLSbzOy:-NOygQUJ9pF5cXAg0KxT:b-qhkh3i) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L35)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Also rename
___
*[`crates/papyrus_load_test/src/transactions.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOygYy77R_1Kg4Bn14x:-NOygYy77R_1Kg4Bn14y:b-n6ctzl) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L50)):*
> ```XML
> //          random_request_transaction(requests).set_name(Name)
> //      }
> macro_rules! create_read_from_file_transaction {
> ```

Please rename



_Code quote:_
```XML
create_read_from_file_transaction
```
___
*[`crates/papyrus_load_test/src/transactions.rs` line 61 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOygc-d4o_WcZrbkiFD:-NOygc-d4o_WcZrbkiFE:b-avsrlz) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L61)):*
> ```XML
> }
> 
> create_read_from_file_transaction! {
> ```

Please move this higher in the file



_Code quote:_
```XML
create_read_from_file_transaction!
```

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/transactions.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOyY7tJ3wZv_RLSbzOy:-NOyswQJ3LY5rpMLKNUt:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/1605252cc474ce15f2adf7f5da9c5415a7d8af03/crates/papyrus_load_test/src/transactions.rs#L35)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Also rename
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)* status: all files reviewed, 6 unresolved discussions

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/506#-NOdFxwu-FcEnJ14Eey5:-NPBk2S4BH2iJdM8nNf7:b3jgfxj) ([raw file](https://github.com/starkware-libs/papyrus/blob/b92a69ca5a542866549639adced2697ecb3da49d/crates/papyrus_load_test/src/transactions.rs#L43)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO the rule of three applies here.
Currently there is only one usage.
It would be nice to see a PR that only refactor duplicate code. 
</blockquote></details>

i understand it now

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/506)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

**Pull request merged**
