### PR TITLE
Declare V2

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/561)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Build fails, please add testing feature to the test_utils SN_API dependency.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 34 files at r9, 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/561)* status: 3 of 40 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/transaction.rs` line 33 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhDwut1r84BuFIfVRG:-NRhDwut1r84BuFIfVRH:bnoctau) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/papyrus_gateway/src/transaction.rs#L33)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct DeclareTransactionV0Or1 {
> ```

Consider something more readable, maybe `DeclareTransactionV0V1`



_Code quote:_
```XML
DeclareTransactionV0Or1
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/561)* status: 4 of 40 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @yair-starkware)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 27 of 34 files at r9, 13 of 13 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/561)* status: all files reviewed, 5 unresolved discussions (waiting on @anatgstarkware and @yair-starkware)

___
*[`crates/starknet_client/src/lib.rs` line 140 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhb4au5pyR8Xg7Yk0Q:-NRhb4au5pyR8Xg7Yk0R:b-7rt55j) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/lib.rs#L140)):*
> ```XML
>     #[error("Wrong type of contract class")]
>     BadContractClassType,
>     #[error("Invalid transaction.")]
> ```

Consider adding some more info (can be a TODO)



_Code quote:_
```XML
    #[error("Invalid transaction.")]
    BadTransaction,
```
___
*[`crates/starknet_client/src/objects/block_test.rs` line 148 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhbGZg3-IMf6HlZq2-:-NRhbGZg3-IMf6HlZq20:bgxmgut) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/block_test.rs#L148)):*
> ```XML
>         transaction_index: TransactionOffsetInBlock(0),
>         transaction_hash: err_block.transactions[0].transaction_hash(),
>         ..err_block.transaction_receipts[4].clone()
> ```

Please explain the change.



_Code quote:_
```XML
[4]
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRha-EO-yZQ9JV8jQkG:-NRha-EO-yZQ9JV8jQkH:bsfgwh5) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L61)):*
> ```XML
>     }
> 
>     type Error = ClientError;
> ```

Consider moving the error type before the fn



_Code quote:_
```XML
type Error = ClientError;
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhaDCjEPjwOROvHE1d:-NRhaDCjEPjwOROvHE1e:b-coc88j) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L134)):*
> ```XML
>     }
> 
>     type Error = ClientError;
> ```

Smae here



_Code quote:_
```XML
type Error = ClientError;
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 150 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRha_7n1ts_--v34poA:-NRha_7n1ts_--v34poB:b-av51ih) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L150)):*
> ```XML
> }
> 
> impl TryFrom<IntermediateDeclareTransaction> for starknet_api::transaction::DeclareTransactionV2 {
> ```

Consider reordering (V2 after V1).



_Code quote:_
```XML
impl TryFrom<IntermediateDeclareTransaction> for starknet_api::transaction::DeclareTransactionV2 {
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 260 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhahOU6giMryV5Em9h:-NRhahOU6giMryV5Em9i:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L260)):*
> ```XML
>     }
> 
>     type Error = ClientError;
> ```

Same



_Code quote:_
```XML
 type Error = ClientError;
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 278 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhakYu2B7FInStepAt:-NRhakYu2B7FInStepAu:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L278)):*
> ```XML
>     }
> 
>     type Error = ClientError;
> ```

Same here



_Code quote:_
```XML
type Error = ClientError;
```
___
*[`crates/starknet_client/src/objects/transaction.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhapqo32mKj4Gi3Ttm:-NRhapqo32mKj4Gi3Ttn:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L294)):*
> ```XML
>     }
> 
>     type Error = ClientError;
> ```

Same here



_Code quote:_
```XML
type Error = ClientError;
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/561)* status: 35 of 40 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhB8tS5_MkbfsAPGub:-NRht8v37R5gMnJZoGXI:b-y1dz0x) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Build fails, please add testing feature to the test_utils SN_API dependency.
</blockquote></details>

couldn't reproduce it locally, but I added testing anyways.

___
___
*[`crates/papyrus_gateway/src/transaction.rs` line 33 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhDwut1r84BuFIfVRG:-NRhuMyc47RMBRS-l5al:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/papyrus_gateway/src/transaction.rs#L33)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider something more readable, maybe `DeclareTransactionV0V1`
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/transaction.rs` line 101 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhE4TQCjLO8dwfEr4c:-NRhuS1I8jSxHMm4S4i8:btd9143) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/papyrus_gateway/src/transaction.rs#L101)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider something more readable, maybe `V0V1`
</blockquote></details>

added another variant with the same struct
___
*[`crates/papyrus_storage/src/serializers.rs` line 320 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhWrZS05uu6y-TBoDw:-NRhujhBC92tj7DN5_88:bc90zu8) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/papyrus_storage/src/serializers.rs#L320)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why did the discriminants change?
</blockquote></details>

mistake, reverted
___
*[`crates/starknet_client/src/lib.rs` line 140 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhb4au5pyR8Xg7Yk0Q:-NRhv5R9AxzOL513mKeB:b-iw1i2d) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/lib.rs#L140)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider adding some more info (can be a TODO)
</blockquote></details>

Added todo
___
*[`crates/starknet_client/src/objects/block_test.rs` line 148 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhbGZg3-IMf6HlZq2-:-NRhvKRL6wfAhkE1a725:b10htmh) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/block_test.rs#L148)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please explain the change.
</blockquote></details>

I added another transaction to the block in the test, so the index of the tx receipt increased
___
*[`crates/starknet_client/src/objects/transaction.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRha-EO-yZQ9JV8jQkG:-NRhy3jv-v9GBQUVcH2N:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L61)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider moving the error type before the fn
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/transaction.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhaDCjEPjwOROvHE1d:-NRhy5a_D9YpDOnldSNK:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L134)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Smae here
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/transaction.rs` line 150 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRha_7n1ts_--v34poA:-NRhxKqj2jpW95iWIDhC:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L150)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider reordering (V2 after V1).
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/transaction.rs` line 260 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhahOU6giMryV5Em9h:-NRhy7Pa2d_OzZvXyGSQ:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L260)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Same
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/transaction.rs` line 278 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhakYu2B7FInStepAt:-NRhy8j52fu7kj6lQeee:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L278)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/transaction.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/561#-NRhapqo32mKj4Gi3Ttm:-NRhy9sL9zYn1njbKHtS:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/85df3c2b6952fac656e8d156b7e09de83d5d4cb3/crates/starknet_client/src/objects/transaction.rs#L294)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done

**Pull request merged**
