### PR TITLE
fix(network): handle store_header_pending_pairing_with_signature error

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1603)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1603?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1590** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1588** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1600** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1601** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1602** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #1603** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1603?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1603?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1603)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-Nnt5ZTsBIHF0NLZi_W1:-Nnt5ZTtBNzWXGrO9MuD:bsck7p9) ([raw file](https://github.com/starkware-libs/papyrus/blob/554389eb66e084bbb619dfe4b05a2b78e9cec1f3/crates/papyrus_network/src/block_headers/behaviour.rs#L164)):*
> ```XML
>                         .store_header_pending_pairing_with_signature(header, outbound_session_id)
>                     else {
>                         // Got two headers in a raw without a signature in between.
> ```

raw -> row
BTW, Ittay said this is not an error, and that the peer can send 0 or 1 signature messages between each header message. Let's first merge everything to main and then fix it.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-Nnt6XyZ6qsvAwtMgP91:-Nnt69Sx6Veun78Cu70g:bamgdhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/554389eb66e084bbb619dfe4b05a2b78e9cec1f3/crates/papyrus_network/src/block_headers/behaviour.rs#L255)):*
> ```XML
>         header: protobuf::BlockHeader,
>         outbound_session_id: OutboundSessionId,
>     ) -> Option<()> {
> ```

Return Result<(), The-enum-that-contains-PairingError> and then you don't need to map the error
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-Nnt715f3QkMLxG1I2zw:-Nnt715f3QkMLxG1I2zx:bamgdhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/554389eb66e084bbb619dfe4b05a2b78e9cec1f3/crates/papyrus_network/src/block_headers/behaviour.rs#L266)):*
> ```XML
>         &mut self,
>         outbound_session_id: OutboundSessionId,
>     ) -> Option<BlockHeader> {
> ```

Return Result<(), The-enum-that-contains-PairingError> and then you don't need to map the error

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1603)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-Nnt6XyZ6qsvAwtMgP91:-No7Jz907WgsSk4HEr0T:b-l7ftiv) ([raw file](https://github.com/starkware-libs/papyrus/blob/554389eb66e084bbb619dfe4b05a2b78e9cec1f3/crates/papyrus_network/src/block_headers/behaviour.rs#L255)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Return Result<(), The-enum-that-contains-PairingError> and then you don't need to map the error
</blockquote></details>

changed it but I don't think it helped much in readability
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-Nnt715f3QkMLxG1I2zw:-No7K2XW5WEasX6a6Bnd:b-f85f7n) ([raw file](https://github.com/starkware-libs/papyrus/blob/554389eb66e084bbb619dfe4b05a2b78e9cec1f3/crates/papyrus_network/src/block_headers/behaviour.rs#L266)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Return Result<(), The-enum-that-contains-PairingError> and then you don't need to map the error
</blockquote></details>

in this case it will just move the map to the main function since I need the value it returns and if it's an error I'll need to map it to an event so I'm leaving it like it is

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1603#-:-NoBmQJ82iwJWuC6_d6-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
