### PR TITLE
feat(network): add tracing info to behaviours

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1928)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1928?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1928** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1928?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1927** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1927?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1926** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1926?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1928)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1928#-NvzY0wS9VfxUOn5dhhb:-NvzY0wS9VfxUOn5dhhc:b-brngut) (no related file):*
All the logs in this PR should be in debug or trace level

___
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1928#-NvzXrvi2RWICPHe-onH:-NvzXrvi2RWICPHe-onI:b-nygy3h) ([raw file](https://github.com/starkware-libs/papyrus/blob/ccb5ef8f7969697d72b7eeea4f8780778731d124/crates/papyrus_network/src/peer_manager/mod.rs#L113)):*
> ```XML
>             if let Some(connection_id) = peer.connection_id() {
>                 info!(
>                     "Session: {:?} assigned to peer: {:?} with connection id: {:?}",
> ```

Remove `:` from the sentence. It doesn't fit the sentence flow
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1928#-NvzXLqx4JFoERl7zULk:-NvzXLqx4JFoERl7zULl:b-nygy3h) ([raw file](https://github.com/starkware-libs/papyrus/blob/ccb5ef8f7969697d72b7eeea4f8780778731d124/crates/papyrus_network/src/peer_manager/mod.rs#L133)):*
> ```XML
>                         .insert(*peer_id, vec![outbound_session_id]);
>                 }
>                 info!("Dialing peer: {:?} with multiaddr: {:?}", peer_id, peer.multiaddr());
> ```

Remove `:` from the sentence. It doesn't fit the sentence flow

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1928)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1928#-NvzY0wS9VfxUOn5dhhb:-NwhgekJ-KevKHHqKk2d:b8i5xfa) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

All the logs in this PR should be in debug or trace level
</blockquote></details>

This is still not fixed

___

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1928)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
