### PR TITLE
release: use constants for transaction versions

### PR DESCRIPTION
**Pull request by barak-b-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1150)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1150)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @dan-starkware)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1150#-NdxQ-2N6MeKnb6WlOLu:-NdxQ-2N6MeKnb6WlOLv:b-94et7m) ([raw file](https://github.com/starkware-libs/papyrus/blob/2364d944be938b031c680d975e4391946cc5e521/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L38)):*
> ```XML
> use crate::v0_3_0::error::JsonRpcError;
> 
> // TODO(yair): Make these functions regular consts.
> ```

Remove TODO? 
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1150#-NdxQGB60-MejFzYjqzE:-NdxQGB60-MejFzYjqzF:bqjb6fz) ([raw file](https://github.com/starkware-libs/papyrus/blob/2364d944be938b031c680d975e4391946cc5e521/crates/starknet_client/src/reader/objects/transaction.rs#L47)):*
> ```XML
> use crate::reader::ReaderClientError;
> 
> lazy_static! {
> ```

Does this still need to be lazy?

**Review by elintul — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1150)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @ShahakShama)

**Comment by yair-starkware** [comment]
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1150#-NdxQGB60-MejFzYjqzE:-Ne2I2_84i_shYY16fW3:b-a56w6q) ([raw file](https://github.com/starkware-libs/papyrus/blob/2364d944be938b031c680d975e4391946cc5e521/crates/starknet_client/src/reader/objects/transaction.rs#L47)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@yair-starkware I saw you've added the `lazey_static!` macro, it's still needed?
</blockquote></details>

You can remove the whole block and use the constants directly in the code.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1150#-NdxQ-2N6MeKnb6WlOLu:-Ne2J1-j16UuUtcnZ0FQ:b-gi9w9p) ([raw file](https://github.com/starkware-libs/papyrus/blob/2364d944be938b031c680d975e4391946cc5e521/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L38)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@yair-starkware can it be removed?
I didn;t know if you want the functions to return constants or change the functions themselves to constants.
</blockquote></details>

Remove the functions and use the constants directly

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1150#-:-Ne2SbGTAYilpo-qMiTf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/papyrus/pull/1171) PR as part of bumping version from 0.0.4 to 0.0.5.

**Pull request closed without merging**
