### PR TITLE
fix: read_pending_data() for get_block api-s

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-Ni4xok743s0h6Il3w7-:-Ni4xok743s0h6Il3w70:bzdql50) ([raw file](https://github.com/starkware-libs/papyrus/blob/811a42b507827d27d93a5f123b531666008d8b72/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L203)):*
> ```XML
>         if let BlockId::Tag(Tag::Pending) = block_id {
>             let block =
>                 read_pending_data(&self.pending_data, &self.storage_reader).await?.block.clone();
> ```

Remove the clone. read_pending_data already clones it from the lock. Same above
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 627 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-Ni4y8D4BpbYgiOZ4wp4:-Ni4y8D4BpbYgiOZ4wp5:b-2cz6rx) ([raw file](https://github.com/starkware-libs/papyrus/blob/811a42b507827d27d93a5f123b531666008d8b72/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L627)):*
> ```XML
>         &module,
>         method_name,
>         &Some(BlockId::HashOrNumber(BlockHashOrNumber::Hash(BlockHash(stark_felt!(
> ```

You should test instead that when calling with BlockId::Tag(Tag::Pending) you get a block with data from the head block and no txs. Same above

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 627 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-Ni4y8D4BpbYgiOZ4wp4:-Ni5GTw4C4hjWQbVgkaD:b-vugaoh) ([raw file](https://github.com/starkware-libs/papyrus/blob/811a42b507827d27d93a5f123b531666008d8b72/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L627)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But something is wrong with the first test. For some reason the transactions type is not the expected one.
I'll need to debug.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 627 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-Ni4y8D4BpbYgiOZ4wp4:-Ni96psX4xo4TAisXZW_:b-36dyl8) ([raw file](https://github.com/starkware-libs/papyrus/blob/811a42b507827d27d93a5f123b531666008d8b72/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L627)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

But something is wrong with the first test. For some reason the transactions type is not the expected one.
I'll need to debug.
</blockquote></details>

OK. Test fixed. Although something is still strange. I'm expecting to get response of type Transactions::Full and I'm getting Transactions::Hashes instead. Can it be that because the list of transaction is empty it doesn't know which one to use??

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 493 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-NiAKoNL35x1ea5gdLOZ:-NiANSkA2GlhKMEhhpWt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f5139b6819a3688e9208a2b63d1c4bf52ac2c50e/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L493)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use match instead, or unite into a single if like this:
```
if let Transaction::Hashes(transactions) | Transactions::Full(transactions = res_block.transactions.clone() {
    assert...
} else {
    panic...
}
```
same below
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1349#-:-NiAN_0IAOioQATmm5_C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
