### PR TITLE
feat(network): handle db executore restults

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1625)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1625** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1625?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1625?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1625)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-NoQvXx50utjO23bhiVz:-NoQvXx50utjO23bhiW-:bmwma92) ([raw file](https://github.com/starkware-libs/papyrus/blob/0efd59c8d29cc131d8f7f94a1e32e1be5037aaed/crates/papyrus_network/src/network_manager.rs#L64)):*
> ```XML
> 
>     fn handle_db_executor_result(&mut self, (query_id, data): (QueryId, Data)) {
>         if let Some(inbound_session_id) = self.query_id_to_inbound_session.get(&query_id) {
> ```

Use let else instead of if let. removes an indentation to the entire function
Even better, use expect instead of `else { panic!(`
___
*[`crates/papyrus_network/src/network_manager.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-NoQvqEd8BS0DINNrb_2:-NoQvfk80I5fzGl8r8eg:b-hbcitg) ([raw file](https://github.com/starkware-libs/papyrus/blob/0efd59c8d29cc131d8f7f94a1e32e1be5037aaed/crates/papyrus_network/src/network_manager.rs#L65)):*
> ```XML
>     fn handle_db_executor_result(&mut self, (query_id, data): (QueryId, Data)) {
>         if let Some(inbound_session_id) = self.query_id_to_inbound_session.get(&query_id) {
>             let inbound_session_id = *inbound_session_id;
> ```

Try to see if it works moving the * to the if let statement:
let Some(inbound_session_id) = *self.query...
I think it should work because Option<T> should have Copy if T has Copy
maybe you need to insert a get_ref() at the end
___
*[`crates/papyrus_network/src/network_manager.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-NoQwJ1G0qdNJvPfMdKc:-NoQwJ1G0qdNJvPfMdKd:bayxfyc) ([raw file](https://github.com/starkware-libs/papyrus/blob/0efd59c8d29cc131d8f7f94a1e32e1be5037aaed/crates/papyrus_network/src/network_manager.rs#L69)):*
> ```XML
>                 self.query_id_to_inbound_session.remove(&query_id);
>             }
>             if self.swarm.behaviour_mut().send_data(data, inbound_session_id).is_err() {
> ```

use expect instead and add a TODO at the start of this file to handle errors properly throughout the file

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1625)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-NoQvXx50utjO23bhiVz:-NoQxRw10V2MucmLZmHz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0efd59c8d29cc131d8f7f94a1e32e1be5037aaed/crates/papyrus_network/src/network_manager.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use let else instead of if let. removes an indentation to the entire function
Even better, use expect instead of `else { panic!(`
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-NoQwJ1G0qdNJvPfMdKc:-NoQxkWX8TUJvQ-PCpk9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0efd59c8d29cc131d8f7f94a1e32e1be5037aaed/crates/papyrus_network/src/network_manager.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use expect instead and add a TODO at the start of this file to handle errors properly throughout the file
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1625#-:-NoQy5_T9Rgpoqw5SkZn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
