### PR TITLE
use serde internal tags for SN client txs

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZRFTxhCsjV8H_RnWEu:-NZRFTxhCsjV8H_RnWEv:bqa6rcp) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction.rs#L31)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Clone, Eq, PartialEq)]
> #[serde(tag = "type")]
> // Note: When deserializing an untagged enum, no variant can be a prefix of variants to follow.
> ```

Remove the comment



_Code quote:_
```XML
// Note: When deserializing an untagged enum, no variant can be a prefix of variants to follow.
```
___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWKOl86SiRCyswMt13:-NZWKOl86SiRCyswMt14:b-kl43c0) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L29)):*
> ```XML
> fn load_invoke_with_contract_address_transaction_succeeds() {
>     let json_str: String = read_resource_file("invoke_transaction.json");
>     let json_str = json_str.replace("sender_address", "contract_address");
> ```

document



_Code quote:_
```XML
let json_str = json_str.replace("sender_address", "contract_address");
```
___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWLIhj52nWs7kgRePt:-NZWLIhj52nWs7kgRePu:bp2kxza) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L78)):*
> ```XML
> #[test]
> fn load_transaction_wrong_type_fails() {
>     for (file_name, new_type) in [
> ```

rename: wrong_tx_type
Also document what is happening.



_Code quote:_
```XML
new_type
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWKOl86SiRCyswMt13:-NZe1_Fa7o9Jdrc_qME3:b-q9i4o9) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

document
</blockquote></details>

I don't see a reason to document this line. Is there something unreadable you noticed here?
___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWLIhj52nWs7kgRePt:-NZe1tiR1aHDWs5I0YmE:b-7n7ukk) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L78)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

rename: wrong_tx_type
Also document what is happening.

</blockquote></details>

I'll rename to new_wrong_type
Is there something unreadable here you've noticed that requires documenting?

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWKOl86SiRCyswMt13:-NZeStdvA3FpRorNqJ8A:b8vr3gm) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L29)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't see a reason to document this line. Is there something unreadable you noticed here?
</blockquote></details>

The reader doesn't know the reason for this replacement
___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWLIhj52nWs7kgRePt:-NZeT4XF8f_Uj9-K-nGR:bw7pw32) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L78)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll rename to new_wrong_type
Is there something unreadable here you've noticed that requires documenting?
</blockquote></details>

It requires careful reading to notice that the json doesn't match the type. The renaming might help, but I think it is worth a little comment

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/objects/transaction.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZRFTxhCsjV8H_RnWEu:-N_DzKHeC1TljiWPKbby:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Remove the comment
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWKOl86SiRCyswMt13:-N_E2ToM-Quhcoef6I68:bkyujg5) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The reader doesn't know the reason for this replacement
</blockquote></details>

I hope I now made my code readable enough so that the reader will know the reason for this replacement

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/objects/transaction_test.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/800#-NZWLIhj52nWs7kgRePt:-N_E3Feb8KQyZexVsKSS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d82355cdeadc0b11c8bef30ca4164a46485fbaa/crates/starknet_client/src/objects/transaction_test.rs#L78)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It requires careful reading to notice that the json doesn't match the type. The renaming might help, but I think it is worth a little comment
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800#-:-N_SWl6X8Bf59pKi2Wia:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
