### PR TITLE
add SN writer client responses

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_YjS1c3IK6gqhsjUy0:b-oii911) (no related file):*
I don't understand.
Is this testing that the responses we get from the gateway match the schema?
Why do we need to do this?

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_llo3_9D2mAz8tSahg:b1vqk8k) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't understand.
Is this testing that the responses we get from the gateway match the schema?
Why do we need to do this?
</blockquote></details>

We need to return the response to the papyrus gateway because that's the response it returns to the user of Papyrus
So I wrote this structs and as you said, we need to check that the responses from the SN gateway match the schema of the structs I'm passing to the papyrus gateway

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We need to return the response to the papyrus gateway because that's the response it returns to the user of Papyrus
So I wrote this structs and as you said, we need to check that the responses from the SN gateway match the schema of the structs I'm passing to the papyrus gateway
</blockquote></details>

Got it.
I think the responses should be in a separate module outside the client, imported by both the writer client and the GW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_mw36XDZtIFENISWwT:b-eis4j3) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Got it.
I think the responses should be in a separate module outside the client, imported by both the writer client and the GW
</blockquote></details>

The GW is going to have its own response object because the RPC format is different than the SN GW format

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The GW is going to have its own response object because the RPC format is different than the SN GW format
</blockquote></details>

SN   --->   SN Client   --->   Papyrus GW   --->   Users
         resp 1          do things                     resp 2


Currently resp 1 & resp 2 are identical and sit in the client, but in the future they will be separated?
If so, I still think they should be decoupled right now

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_nFM1f5bkD9nMDYULl:bbyp5lv) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

SN   --->   SN Client   --->   Papyrus GW   --->   Users
         resp 1          do things                     resp 2


Currently resp 1 & resp 2 are identical and sit in the client, but in the future they will be separated?
If so, I still think they should be decoupled right now
</blockquote></details>

I didn't understand :sweat_smile: 

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I didn't understand :sweat_smile: 
</blockquote></details>

Sorry, reviewable destroyed my nice plot



_Code snippet:_
```
SN   --->   SN Client   --->   Papyrus GW   --->   Users
   resp 1            do things             resp 2
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_nFnss5M8qCfh2sIO3:b-qv8zh0) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Sorry, reviewable destroyed my nice plot
</blockquote></details>

Yes. Why do you think they should be decoupled?

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes. Why do you think they should be decoupled?
</blockquote></details>

Because one needs to pass the RPC tests and the other doesn't

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/862#-N_YjS1c3IK6gqhsjUy-:-N_nG0JP9K6fI9XXkgCN:b-x8xwu6) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Because one needs to pass the RPC tests and the other doesn't
</blockquote></details>

So you agree there should be two separate classes?

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

So you agree there should be two separate classes?
</blockquote></details>

Yes, but why do you write the tests on the client structs?

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/862#-:-Na66KHI24Ce6wD3ftXT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
