### PR TITLE
Bump starknet api version, location of transaction hash.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaAkazb5DmnjphTP6rR:b-4iwdt5) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
> ```XML
> gen_test_from_thin_transaction_output_macro!(L1Handler);
> 
> // TODO(dvir): fix this test (consider to delete it).
> ```

@nagmo-starkware what is the purpose of this test?
How should it be fixed (or should it be deleted?)



_Code quote:_
```XML
// TODO(dvir): fix this test (consider to delete it).
```
___
*[`crates/papyrus_storage/src/body/mod.rs` line 356 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaBOebL1Ox5V_5iGlM4:-NaBOebL1Ox5V_5iGlM5:b-qanf71) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_storage/src/body/mod.rs#L356)):*
> ```XML
>         for (offset, tx_output) in transaction_outputs
>             .iter()
>             // .zip(transactions.iter().map(|(tx, _exec_status)| tx.transaction_hash()))
> ```

Delete the line
___
*[`crates/papyrus_storage/src/body/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAzqUV7i0ddb9-DJJj:-NaAzqUV7i0ddb9-DJJk:b3o3cea) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_storage/src/body/mod.rs#L384)):*
> ```XML
> 
>         markers_table.upsert(&self.txn, &MarkerKind::Body, &block_number)?;
>         Ok((self, Some((transactions, transaction_outputs, events))))
> ```

Add the tx hashes to the deleted data returned from the function

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaBc9BPAW6mioXy4g0P:b-8pwuqh) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@nagmo-starkware what is the purpose of this test?
How should it be fixed (or should it be deleted?)
</blockquote></details>

it tests the conversion from starknet_api::transaction to papyrus_gateway::transaction
I don't see any reason not to fix it

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaBdsrK13kELER3ys3v:-NaBdsrK13kELER3ys3w:bj9mj9n) (no related file):*
The last commit is because of a mistake I made in the original commit.

___
___
*[`crates/papyrus_storage/src/body/mod.rs` line 356 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaBOebL1Ox5V_5iGlM4:-NaBRjzy2pwvByTdA9NK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_storage/src/body/mod.rs#L356)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Delete the line
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAzqUV7i0ddb9-DJJj:-NaBdhcx-GMIve5goE7Z:bke0qm2) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_storage/src/body/mod.rs#L384)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add the tx hashes to the deleted data returned from the function
</blockquote></details>

Done. also added todo to save this information in an ommer table.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaBlBnH6e6r6CEde4aX:b-17h418) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it tests the conversion from starknet_api::transaction to papyrus_gateway::transaction
I don't see any reason not to fix it
</blockquote></details>

The transaction hash is no longer part of the transaction.
Also, I think the problematic part in the conversion is the transaction type, not getting the right transaction hash

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaBm8i_D-JQdBW1fBoi:b-cztj1) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The transaction hash is no longer part of the transaction.
Also, I think the problematic part in the conversion is the transaction type, not getting the right transaction hash
</blockquote></details>

even without the lines that check the tx hash the test is still valid since it actually converts the objects. as for the type I'll be the last to say not to test something.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaBmfKh1wPqh14EU4tS:b39ya3y) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

even without the lines that check the tx hash the test is still valid since it actually converts the objects. as for the type I'll be the last to say not to test something.
</blockquote></details>

@DvirYo-starkware please remove the hash checks and leave the unwraps, add a todo to check the conversion against the expected GW transaction

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/895#-NaAkazb5DmnjphTP6rQ:-NaBqHvHBSjpEtvtXzgu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f180c6efdd02985989618bc3cbf44775983d84d/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@DvirYo-starkware please remove the hash checks and leave the unwraps, add a todo to check the conversion against the expected GW transaction
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/895#-:-NaBw99m5KmMaBSPwUc_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
