### PR TITLE
Remove sync error ParentBlockHashMismatch

### PR DESCRIPTION
**Pull request by anatgstarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/499)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/499)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8c4R3Pk0N-UJIb6U:-NOO8c4R3Pk0N-UJIb6V:b-pvhb01) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L77)):*
> ```XML
>         info!("State sync started.");
>         loop {
>             if let Err(err) = self.sync_while_ok().await {
> ```

What about unrecoverable errors?
___
*[`crates/papyrus_sync/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8rFN5JCeaZFE1-ig:-NOO8rFN5JCeaZFE1-ih:b-du48yz) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L122)):*
> ```XML
> 
>     // Tries to store the incoming data.
>     async fn process_sync_event(&mut self, sync_event: SyncEvent) -> Result<bool, StateSyncError> {
> ```

Consider changing from bool to enum



_Code quote:_
```XML
bool
```

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8c4R3Pk0N-UJIb6U:-NOOCuyv-xDkU0g0wXLt:b-u2po6) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L77)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What about unrecoverable errors?
</blockquote></details>

I think ParentBlockHashMismatch was the only unrecoverable error

**Comment by yair-starkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8c4R3Pk0N-UJIb6U:-NOOJsiU0KcaRfW6ZPsN:b-nlwzlh) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L77)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

I think ParentBlockHashMismatch was the only unrecoverable error
</blockquote></details>

It was a recoverable error, together with CentralSourceError and StorageError::InnerError.
The rest of the errors are unrecoverable.

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8c4R3Pk0N-UJIb6U:-NOOKcov8ZYky41_mRR9:b-886gsx) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L77)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It was a recoverable error, together with CentralSourceError and StorageError::InnerError.
The rest of the errors are unrecoverable.
</blockquote></details>

Fixed

**Comment by yair-starkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8rFN5JCeaZFE1-ig:-NOPDn4L9epHefT_Rh9c:bxd89kk) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L122)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider changing from bool to enum
</blockquote></details>

Continuing Slack chat - I think an enum is better because:
1. it is more readable - you don't need to wonder what is the meaning of the boolean
2. It is expandable with more output variants
Regarding what the variants should be - currently only DetectedRevert. In the future we can add Done

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOO8rFN5JCeaZFE1-ig:-NOPrf0R9XFhnDqUznCO:be1he2t) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2cbd0ade88cd55cbc08e0efbd84fc344acd0b17/crates/papyrus_sync/src/lib.rs#L122)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Continuing Slack chat - I think an enum is better because:
1. it is more readable - you don't need to wonder what is the meaning of the boolean
2. It is expandable with more output variants
Regarding what the variants should be - currently only DetectedRevert. In the future we can add Done
</blockquote></details>

Changed to `DetectedRevert` type as discussed

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/499)* status: all files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOd0qMb2_CYU9uVtJbR:-NOd0qMb2_CYU9uVtJbS:budlcfa) ([raw file](https://github.com/starkware-libs/papyrus/blob/fa46d61701053e6960c3893752f2cac2cc333ab6/crates/papyrus_sync/src/lib.rs#L90)):*
> ```XML
>                     return Err(err);
>                 }
>                 Ok(()) => continue,
> ```

Why change this? The function should never reach this code.
___
*[`crates/papyrus_sync/src/lib.rs` line 145 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOd1IE1Ar_TWrYwv1Dm:-NOd1IE1Ar_TWrYwv1Dn:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/fa46d61701053e6960c3893752f2cac2cc333ab6/crates/papyrus_sync/src/lib.rs#L145)):*
> ```XML
>             }
>         }
>         Ok(())
> ```

same

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 145 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOd1IE1Ar_TWrYwv1Dm:-NOd3MJP8jTqgFMhnPjh:b-krsobi) ([raw file](https://github.com/starkware-libs/papyrus/blob/fa46d61701053e6960c3893752f2cac2cc333ab6/crates/papyrus_sync/src/lib.rs#L145)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

It returns if it detected a revert

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/499#-NOd0qMb2_CYU9uVtJbR:-NOd3VaaAB-bFIFefbaQ:bn7tn7c) ([raw file](https://github.com/starkware-libs/papyrus/blob/fa46d61701053e6960c3893752f2cac2cc333ab6/crates/papyrus_sync/src/lib.rs#L90)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why change this? The function should never reach this code.
</blockquote></details>

We will reach this code if a revert happens

**Pull request closed without merging**
