### PR TITLE
feat(JSON-RPC): add addDeclareTransaction

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1033)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1033)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 575 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-NbjuEf3BGUnVI4LJTiI:-NbjuEf3BGUnVI4LJTiJ:bvy3dub) ([raw file](https://github.com/starkware-libs/papyrus/blob/a2e1745b31e8bda3b080c9ef1e301ae29879d348/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L575)):*
> ```XML
>         declare_transaction: BroadcastedDeclareTransaction,
>     ) -> RpcResult<AddDeclareOkResult> {
>         let result = self
> ```

I think we should have a trace-level log of the transactions.
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1913 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-NbjuXgvAyjcEeqGblqt:-NbjuXgw74DUEbJYS82H:b-5bz93j) ([raw file](https://github.com/starkware-libs/papyrus/blob/a2e1745b31e8bda3b080c9ef1e301ae29879d348/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1913)):*
> ```XML
> trait AddTransactionTest
> where
>     <<Self as AddTransactionTest>::ClientTransaction as TryFrom<Self::Transaction>>::Error: Debug,
> ```

Add a comment explaining this

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1033)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 575 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-NbjuEf3BGUnVI4LJTiI:-NbmQ4Sz30gLm5rGaL2A:b-gq9hk8) ([raw file](https://github.com/starkware-libs/papyrus/blob/a2e1745b31e8bda3b080c9ef1e301ae29879d348/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L575)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we should have a trace-level log of the transactions.
</blockquote></details>

Why? Do we have a trace log level for other RPC methods?
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1913 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-NbjuXgvAyjcEeqGblqt:-NbmQFJJDpKk7IQdA_dv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a2e1745b31e8bda3b080c9ef1e301ae29879d348/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1913)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add a comment explaining this
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-:-Nbmk5HQ4iF6YKRbw4TD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 575 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1033#-NbjuEf3BGUnVI4LJTiI:-Nbmk9SFBKfPIBJ-rNUT:b-90mfm2) ([raw file](https://github.com/starkware-libs/papyrus/blob/a2e1745b31e8bda3b080c9ef1e301ae29879d348/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L575)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why? Do we have a trace log level for other RPC methods?
</blockquote></details>

If there's a bug we would like to see what was the transaction right?
In the execution I add a trace level log

**Pull request merged**
