### PR TITLE
fix(gateway): v4 handle rejected blocks in tx receipt

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/915)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #888** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/888" target="_blank">Graphite</a> 
    * **PR #877** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/877" target="_blank">Graphite</a> 
      * **PR #915** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/915" target="_blank">Graphite</a>  👈
      * **PR #914** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/914" target="_blank">Graphite</a> 
      * **PR #881** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/881" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/915?utm_source=stack-comment).

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/915)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 221 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/915#-NaMeWqCD4lSc6F5gCsj:-NaMeWqD5nCm616h58hQ:brarzdx) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6ecb66fee4bcf2c8877e3b4732b9533ee344a39/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L221)):*
> ```XML
>         if status == BlockStatus::Rejected {
>             return Err(ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
>         }
> ```

Comment?



_Code quote:_
```XML
        if status == BlockStatus::Rejected {
            return Err(ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
        }
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/915#-:-NafPP6P5Bj0gkNAv6Bp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
