### PR TITLE
Revert "Separate block headers and body sync (#761)"

### PR DESCRIPTION
**Pull request by dan-starkware**
This reverts commit bc645cca84c992835311c22684847ab807f2c354.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/813)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/813#-:-NZybuvY6Jk22DxCDTVv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/813)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/813#-NZye99W1WS91Rucs1bz:-NZye99W1WS91Rucs1c-:b-131xzw) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f1daadbbdd910e2fd4933cb39434f4afbed9f9f/crates/papyrus_sync/src/lib.rs#L468)):*
> ```XML
>             let state_marker = txn.get_state_marker()?;
>             let last_block_number = txn.get_header_marker()?;
>             drop(txn);
> ```

consider keeping the change here (to be consistent with fn stream_new_blocks()):

            let state_marker;
            let last_block_number;
            {
                let txn = reader.begin_ro_txn()?;
                state_marker = txn.get_state_marker()?;
                last_block_number = txn.get_header_marker()?;
            }



_Code quote:_
```XML
            let txn = reader.begin_ro_txn()?;
            let state_marker = txn.get_state_marker()?;
            let last_block_number = txn.get_header_marker()?;
            drop(txn);
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/813)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 468 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/813#-NZye99W1WS91Rucs1bz:-NZyeYxt6mnJXoWDsQQn:bhnnypz) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f1daadbbdd910e2fd4933cb39434f4afbed9f9f/crates/papyrus_sync/src/lib.rs#L468)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

consider keeping the change here (to be consistent with fn stream_new_blocks()):

            let state_marker;
            let last_block_number;
            {
                let txn = reader.begin_ro_txn()?;
                state_marker = txn.get_state_marker()?;
                last_block_number = txn.get_header_marker()?;
            }

</blockquote></details>

Let's do that in a separate PR.

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/813)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
