### PR TITLE
feat(network): add wrapper for Option<SignedBlockHeader> and add converters to/from Vec<u8>

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2063)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2063)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2063#-NyzUXKd-dgWRc_argJp:-Nz1m6149o69W4RhRgAb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdd85e80cd285d98f64f948ba41292d0f6c673cc/crates/papyrus_protobuf/src/sync.rs#L41)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

use the same name as in the protobuf, or add TODO to rename it for consistency
</blockquote></details>

Done.

**Review by asmaastarkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2063#-:-Nz1u6lu6ozdeO8iaJ5R:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2063#-:-Nz7hKAlCXrzHNaFRJmD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2063#-:-Nz7hz6D5nh4w0iFiLeM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
