### PR TITLE
feat(consensus): add event handling to the state machine

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2161** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2159** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OjPmo2Bn_xw0nEaBc:-O0OjPmo2Bn_xw0nEaBd:brsh7he) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L146)):*
> ```XML
>     // The node finishes building a proposal in response to the state machine sending out
>     // GetProposal.
>     fn handle_get_proposal(
> ```

Should this also add 1 to prevote and precommit? That is, do we count our own votes?



_Code quote:_
```XML
fn handle_get_proposal(
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0O_VFx8qp4ZqGlFEbo:-O0O_VFx8qp4ZqGlFEbp:b-1z8n9e) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L153)):*
> ```XML
>         if !self.awaiting_get_proposal || self.round != round {
>             return Vec::new();
>         }
> ```

On what scenario this happens?
Should we pass some kind of response? Maybe wrapping the return value with a result with some information?



_Code quote:_
```XML
        if !self.awaiting_get_proposal || self.round != round {
            return Vec::new();
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OiGaF1Czmm0n1jLN4:-O0OiGaF1Czmm0n1jLN5:brwdoto) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L232)):*
> ```XML
>         let q = (2 * self.validators.len() / 3) + 1;
>         q as u32
>     }
> ```

Assuming validator set is static, can be computer once during init.



_Code quote:_
```XML
    fn quorum(&self) -> u32 {
        let q = (2 * self.validators.len() / 3) + 1;
        q as u32
    }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OQXbnAFqRkTdRB8tm:-O0OQXboB1zEPLEYoth4:b-hd2u4y) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L9)):*
> ```XML
> fn create_state_machine(is_proposer: bool) -> StateMachine {
>     StateMachine::new(
>         if is_proposer { 1_u32.into() } else { 2_u32.into() },
> ```

Consider using consts, with meaningful names, instead



_Code quote:_
```XML
1_u32
```

**Comment by dan-starkware** [comment]
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OxSk68RrrQDKau0f2:-O0OxSk68RrrQDKau0f3:b-u8vxj7) ([raw file](https://github.com/starkware-libs/papyrus/blob/e1afb08d18b8ae5be155d27f105ee843e5fed5cf/crates/sequencing/papyrus_consensus/src/state_machine.rs#L193)):*
> ```XML
>     }
> 
>     fn advance_step(&mut self, step: Step) -> Vec<StateMachineEvent> {
> ```

Consider renaming



_Suggestion:_
```XML
advance_to_step
```

**Comment by dan-starkware** [comment]
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OyluFCk1k4ykwUYgc:-O0OyluFCk1k4ykwUYgd:b-qj0pd6) ([raw file](https://github.com/starkware-libs/papyrus/blob/e1afb08d18b8ae5be155d27f105ee843e5fed5cf/crates/sequencing/papyrus_consensus/src/state_machine.rs#L163)):*
> ```XML
>     }
> 
>     // A proposal from a peer (or self) node.
> ```

Why self?



_Code quote:_
```XML
(or self)
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0P2oCoBIIdj6XCBinA:-O0P2oCoBIIdj6XCBinB:b-o9vbvu) (no related file):*
Document sending events to self to act the same as events from a peer

___
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OjPmo2Bn_xw0nEaBc:-O0TGlYy1KFCUvJtfI1n:bcqttlf) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L146)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Should this also add 1 to prevote and precommit? That is, do we count our own votes?
</blockquote></details>

No. I wrote a comment on `handle_event` that should help clarify this.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0O_VFx8qp4ZqGlFEbo:-O0THfNN8HE8mCvm8FqI:bogk36x) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L153)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

On what scenario this happens?
Should we pass some kind of response? Maybe wrapping the return value with a result with some information?
</blockquote></details>

The scenario that comes to mind is in the future if there is timeoutPropose for a proposer. I was imagining the SHC has 2 semi independent tasks - timeoutPropose and BuildBlock. With timeouts we don't plan to cancel them if they are no longer relevant, and just let the SM ignore them silently. So I figured we'd basically do that here with GetValue.

I believe we want this validation since the SM can't make too many assumptions about how it is called and the argument is how to respond: ignore like this, assertion, return an error.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OiGaF1Czmm0n1jLN4:-O0TJXZsA3gbvk5k_RhZ:b-2myadv) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L232)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Assuming validator set is static, can be computer once during init.
</blockquote></details>

Good call; this actually lets me remove `validators` entirely as a field/input.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OyluFCk1k4ykwUYgc:-O0TIdUo-y0kXNpZlAdP:bz8xva0) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dfa1ece87a68be7a6fc35cbd5c649fb13cb02ac/crates/sequencing/papyrus_consensus/src/state_machine.rs#L163)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why self?
</blockquote></details>

As discussed the state machine handles its own output events just like any other event. I hope the comment on `handle_event` clears that up.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OQXbnAFqRkTdRB8tm:-O0TRft6EG-_2rZ4zdON:bgxv5mu) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider using consts, with meaningful names, instead
</blockquote></details>

I can't use a const to build `ContractAddress`, but I made the naming more meaningful.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0O_VFx8qp4ZqGlFEbo:-O0P3hiO6MszD3fi5415:b-ndvn3r) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine.rs#L153)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

On what scenario this happens?
Should we pass some kind of response? Maybe wrapping the return value with a result with some information?
</blockquote></details>

Please add a comment explaining why we need this.
No need to wrap with result, add a TODO to consider that.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0P2oCb7gLfhwTgsN-Y:-O0P2oCb7gLfhwTgsN-Z:bmamctb) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dfa1ece87a68be7a6fc35cbd5c649fb13cb02ac/crates/sequencing/papyrus_consensus/src/state_machine.rs#L118)):*
> ```XML
>                         events_queue.push_back(e.clone());
>                     }
>                     _ => {}
> ```

Please explain in



_Code quote:_
```XML
                match e {
                    StateMachineEvent::Propose(_, _)
                    | StateMachineEvent::Prevote(_, _)
                    | StateMachineEvent::Precommit(_, _) => {
                        events_queue.push_back(e.clone());
                    }
                    _ => {}
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0bev5zBnRRBw0e6g-Y:-O0bev5zBnRRBw0e6g-Z:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/eda37fce98871105f2837b8df1c8c0beabd83b81/crates/sequencing/papyrus_consensus/src/state_machine.rs#L59)):*
> ```XML
>         total_weight: u32,
>         leader_fn: Box<dyn Fn(Round) -> ValidatorId>,
>     ) -> Self {
> ```





_Suggestion:_
```XML
    pub fn new(
        id: ValidatorId,
        /// total_weight - the total voting weight of all validators for this height.
        total_weight: u32,
        leader_fn: Box<dyn Fn(Round) -> ValidatorId>,
    ) -> Self {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OQXbnAFqRkTdRB8tm:-O0bhjdJ7lspHgeWSm7q:b4md2bo) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L9)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I can't use a const to build `ContractAddress`, but I made the naming more meaningful.
</blockquote></details>

TAL https://crates.io/crates/once_cell
I think it might even found its way into the standard library.

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0P2oCb7gLfhwTgsN-Y:-O0cPuVGCJoUcMLRFD2D:bjsbv1y) ([raw file](https://github.com/starkware-libs/papyrus/blob/6dfa1ece87a68be7a6fc35cbd5c649fb13cb02ac/crates/sequencing/papyrus_consensus/src/state_machine.rs#L118)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please explain in
</blockquote></details>

I put the explanation just on top of the for loop.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0bev5zBnRRBw0e6g-Y:-O0cQtzrDgjlqT-oT0jx:b1aglzg) ([raw file](https://github.com/starkware-libs/papyrus/blob/eda37fce98871105f2837b8df1c8c0beabd83b81/crates/sequencing/papyrus_consensus/src/state_machine.rs#L59)):*
> ```XML
>         total_weight: u32,
>         leader_fn: Box<dyn Fn(Round) -> ValidatorId>,
>     ) -> Self {
> ```

I can't put a doc comment in the middle of the params list. So moving it here makes this comment not appear when running cargo doc, and this is a pub function.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2160#-O0OQXbnAFqRkTdRB8tm:-O0cQ_aI37WPFW7plQVp:b-dzjc52) ([raw file](https://github.com/starkware-libs/papyrus/blob/666cbb065661eb3a9c1684fa93db0a7533f33a25/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

TAL https://crates.io/crates/once_cell
I think it might even found its way into the standard library.
</blockquote></details>

I actually remove the need for this in a couple PRs so I'll just skip the merge conflict here.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2160)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
