### PR TITLE
feat(network): add state diff part struct identical to protobuf

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxuget60EQAG8hc3tw:-Nyxuget60EQAG8hc3tx:b-53qnje) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L50)):*
> ```XML
>         // Has value only if the nonce was updated in this block.
>         nonce: Option<Nonce>,
>         storage_diffs: IndexMap<StorageKey, StarkFelt>,
> ```

domain?

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxv4GW7Z1r8gk8AVhu:-Nyxv4GW7Z1r8gk8AVhv:b-ifvig) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L43)):*
> ```XML
> // TODO(shahak): Implement conversion to/from protobuf.
> #[derive(Debug, Clone, PartialEq, Eq)]
> pub enum StateDiffPart {
> ```

why do we use a different name then the protobuf one?
___
*[`crates/papyrus_protobuf/src/sync.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-NyxvTST77EaGofurI5g:-NyxvTST77EaGofurI5h:bdztxc4) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L58)):*
> ```XML
>     DeprecatedDeclaredClass {
>         class_hash: ClassHash,
>     },
> ```

no fin option

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware and @eitanm-starkware)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxv4GW7Z1r8gk8AVhu:-NyyT_YC37rXRRCEmP5w:b-srdr3j) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L43)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

why do we use a different name then the protobuf one?
</blockquote></details>

I've now created a struct with the protobuf one :)
___
*[`crates/papyrus_protobuf/src/sync.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxuget60EQAG8hc3tw:-NyyTRN41FGnOxmDID5A:b-bbbrby) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L50)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

domain?
</blockquote></details>

Domain is always L1 until we support volition
___
*[`crates/papyrus_protobuf/src/sync.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-NyxvTST77EaGofurI5g:-NyyThQXCiW07tfr_GoJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L58)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

no fin option
</blockquote></details>

Done.

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxv4GW7Z1r8gk8AVhu:-NyyiDuW2Lf6VOG25Lse:bbb9k33) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I've now created a struct with the protobuf one :)
</blockquote></details>

why part?

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxv4GW7Z1r8gk8AVhu:-Nyyj7FF0uCYykZjk4KH:b6gr948) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Because it's not a full state diff. I can rename to chunk if you prefer
</blockquote></details>

probably better to rename, statediffchunk or partialstatediff

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @eitanm-starkware)

___
*[`crates/papyrus_protobuf/src/sync.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-Nyxv4GW7Z1r8gk8AVhu:-Nyym0keChySHqcmzfeM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fec25cb80c8bb9b9827750f512c0e508b133e885/crates/papyrus_protobuf/src/sync.rs#L43)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

probably better to rename, statediffchunk or partialstatediff
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061#-:-NyytNqW64p6bleMJo65:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2061)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
