### PR TITLE
test(JSON-RPC): add option to ignore functions in converage report

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #932** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/932" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/932?utm_source=stack-comment).

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/932#-Nag6dGcEKa6qNEeLLbt:-Nag6dGd06bmiaysvJt_:b-sc8umw) (no related file):*
remove the #![cfg_attr(coverage_nightly, feature(no_coverage))] from crates you don't use it.
In general, it is very weird you need to put this in the libs file of each crate.

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/932#-Nag6dGcEKa6qNEeLLbt:-NagAN-L0wxVWQbFRHSM:b-n3wub6) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

remove the #![cfg_attr(coverage_nightly, feature(no_coverage))] from crates you don't use it.
In general, it is very weird you need to put this in the libs file of each crate.
</blockquote></details>

you must put it there to define the no coverage feature. 
It defines it for the entire crate and it has to be in the top most file in the crate.
I've put it on all crates to not bother anyone else with figuring this out next time they put this attribute and the code doesn't compile

___

**Review by DvirYo-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/932#-Nag6dGcEKa6qNEeLLbt:-NalVbmR2Bp26qwm4b51:b-dxykc1) (no related file):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

you must put it there to define the no coverage feature. 
It defines it for the entire crate and it has to be in the top most file in the crate.
I've put it on all crates to not bother anyone else with figuring this out next time they put this attribute and the code doesn't compile
</blockquote></details>

Ask Dan for approval of the pr

___

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 4 of 14 files at r1, 1 of 8 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/932#-NbjIDHr-hY8BylycGRg:-NbjIDHr-hY8BylycGRh:b-bvhdcp) ([raw file](https://github.com/starkware-libs/papyrus/blob/6178a18ae32ceee5f00dd2181e8c34029feffdbe/crates/papyrus_config/src/lib.rs#L4)):*
> ```XML
> // crate
> #![cfg_attr(coverage_nightly, feature(no_coverage))]
> #![warn(missing_docs)]
> ```

Consider. In other crates as well.



_Suggestion:_
```XML
#![cfg_attr(coverage_nightly, feature(no_coverage))]

#![warn(missing_docs)]
```
___
*[`crates/papyrus_gateway/src/v0_3_0/transaction.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/932#-NbjNPCF3elM8cprJVT8:-NbjNPCF3elM8cprJVT9:b-wnawcb) ([raw file](https://github.com/starkware-libs/papyrus/blob/6178a18ae32ceee5f00dd2181e8c34029feffdbe/crates/papyrus_gateway/src/v0_3_0/transaction.rs#L371)):*
> ```XML
>         }
>     }
> }
> ```

Not related to this PR - This looks suspiciously naive. Can we use the SN_API type directly?



_Code quote:_
```XML
impl From<starknet_api::transaction::TransactionOutput> for TransactionOutput {
    #[cfg_attr(coverage_nightly, no_coverage)]
    fn from(tx_output: starknet_api::transaction::TransactionOutput) -> Self {
        match tx_output {
            starknet_api::transaction::TransactionOutput::Declare(declare_tx_output) => {
                TransactionOutput::Declare(declare_tx_output)
            }
            starknet_api::transaction::TransactionOutput::Deploy(deploy_tx_output) => {
                TransactionOutput::Deploy(deploy_tx_output)
            }
            starknet_api::transaction::TransactionOutput::DeployAccount(deploy_tx_output) => {
                TransactionOutput::DeployAccount(deploy_tx_output)
            }
            starknet_api::transaction::TransactionOutput::Invoke(invoke_tx_output) => {
                TransactionOutput::Invoke(invoke_tx_output)
            }
            starknet_api::transaction::TransactionOutput::L1Handler(l1_handler_tx_output) => {
                TransactionOutput::L1Handler(l1_handler_tx_output)
            }
        }
    }
}
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/932#-NbjIDHr-hY8BylycGRg:-NbmlsZs9uRktj5dAtNd:bma7542) ([raw file](https://github.com/starkware-libs/papyrus/blob/6178a18ae32ceee5f00dd2181e8c34029feffdbe/crates/papyrus_config/src/lib.rs#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider. In other crates as well.
</blockquote></details>

rust fmt removed the new line :)

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932#-:-NbnlX6b6TADpziNRaHw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/932)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
