### PR TITLE
fix(gateway): v3 rejectedb locks and reverted tx handle

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/899)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #899** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/899" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/899?utm_source=stack-comment).

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/899#-NaBN32Y87sP26BYLDtz:-NaBN32Y87sP26BYLDu-:b443vmw) ([raw file](https://github.com/starkware-libs/papyrus/blob/2e1a8ffcfb20dff79d31c2557df3117a6c1dd53c/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L204)):*
> ```XML
> 
>         if status == BlockStatus::Rejected {
>             return Err(ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
> ```

Did we agree on this Error?
@ArielElp 



_Code quote:_
```XML
BlockNotFound
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 220 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/899#-NaLtoMCD9MtetgD6kdC:-NaLtoMCD9MtetgD6kdD:bemvc9v) ([raw file](https://github.com/starkware-libs/papyrus/blob/a53e71ccc40a2e0faf084c45ec7cc66f08f58d80/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L220)):*
> ```XML
> 
>         if status == BlockStatus::Rejected {
>             return Err(ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
> ```

Consider adding a comment



_Code quote:_
```XML
        if status == BlockStatus::Rejected {
            return Err(ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 234 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/899#-NaLu0cT1iGC6EnjA6z_:-NaLu0cT1iGC6EnjA6za:bemvc9v) ([raw file](https://github.com/starkware-libs/papyrus/blob/a53e71ccc40a2e0faf084c45ec7cc66f08f58d80/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L234)):*
> ```XML
>         if transaction_execution_status == TransactionExecutionStatus::Reverted {
>             return Err(ErrorObjectOwned::from(JsonRpcError::TransactionReverted))?;
>         }
> ```

Consider adding a comment



_Code quote:_
```XML
        if transaction_execution_status == TransactionExecutionStatus::Reverted {
            return Err(ErrorObjectOwned::from(JsonRpcError::TransactionReverted))?;
        }
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/899)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/899)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/899#-NaBN32Y87sP26BYLDtz:-NaLupevECsRr5dMa3LK:btavlk9) ([raw file](https://github.com/starkware-libs/papyrus/blob/2e1a8ffcfb20dff79d31c2557df3117a6c1dd53c/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L204)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Did we agree on this Error?
@ArielElp 
</blockquote></details>

approved with Ariel

**Pull request merged**
