### PR TITLE
feat(JSON-RPC): add spec api implementation coverage test

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1087)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1078** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1078" target="_blank">Graphite</a> 
    * **PR #1079** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1079" target="_blank">Graphite</a> 
      * **PR #1080** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1080" target="_blank">Graphite</a> 
        * **PR #1087** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1087" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1087?utm_source=stack-comment).

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1087#-:-NcNIAr_7spExURoip1d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

**Review by dan-starkware — COMMENTED** [review]
:thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1087#-:-NcOJzjj4yRRND0AYj-I:b4c9lyr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
