### PR TITLE
chore(network): handle report receiver

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2234)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2234)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2OZkcW5UOU209jnxfu:-O2OZkcW5UOU209jnxfv:b-kclzdo) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L359)):*
> ```XML
>                 );
>                 if let Some(report_receiver) =
>                     self.sqmr_outbound_report_receivers.remove(&outbound_session_id)
> ```

rename sqmr_outbound_report_receivers to sqmr_outbound_report_receivers_waiting_assignment
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2OZzKi7FTU8M4KNw57:-O2OZzKi7FTU8M4KNw58:b-lswgfr) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L361)):*
> ```XML
>                     self.sqmr_outbound_report_receivers.remove(&outbound_session_id)
>                 {
>                     self.handle_report_receiver(peer_id, report_receiver)
> ```

rename handle_report_receiver to handle_new_report_receiver
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2O_7TH6OnjDBNw87TA:-O2O_7TH6OnjDBNw87TB:b-rnconw) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L386)):*
> ```XML
>                         self.sqmr_outbound_report_receivers.remove(&outbound_session_id)
>                     {
>                         error!("Report receiver was not consumed. Dropping it.");
> ```

This is not an error. change the log level to debug/info and type "Outbound session failed before peer assigned to it. Ignoring incoming reports for the session."
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2Oa9tUASZeJcv0jjCy:-O2Oa9tUASZeJcv0jjCz:b-sknoti) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L398)):*
> ```XML
>                         self.sqmr_outbound_report_receivers.remove(&outbound_session_id)
>                     {
>                         error!("Report receiver was not consumed. Dropping it.");
> ```

Change the error message here to. "Outbound session finished with no messages in it. Ignoring incoming reports for the session"
Regarding the error log level, right now it's not an error since you can close a session with no messages in it. But in the future I'd expect us to remove report receivers from `sqmr_outbound_report_receivers` once the session is assigned and not once we got a response, and then this should be error log level, so I'm ok with either one

**Review by ShahakShama — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2234)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2234)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2OZkcW5UOU209jnxfu:-O2TVioz066a0wE5KtYx:bs7wumx) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L359)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename sqmr_outbound_report_receivers to sqmr_outbound_report_receivers_waiting_assignment
</blockquote></details>

Done. 
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2OZzKi7FTU8M4KNw57:-O2TVibUBY2BOj2nJ-Xe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L361)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename handle_report_receiver to handle_new_report_receiver
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2O_7TH6OnjDBNw87TA:-O2TViDD1VhcYd-9d_De:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L386)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not an error. change the log level to debug/info and type "Outbound session failed before peer assigned to it. Ignoring incoming reports for the session."
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-O2Oa9tUASZeJcv0jjCy:-O2TVXEeAi5lqVKXQuJ1:b-jzrkej) ([raw file](https://github.com/starkware-libs/papyrus/blob/bef8ce694f251f288f0fbec564e2fe2a232f787a/crates/papyrus_network/src/network_manager/mod.rs#L398)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the error message here to. "Outbound session finished with no messages in it. Ignoring incoming reports for the session"
Regarding the error log level, right now it's not an error since you can close a session with no messages in it. But in the future I'd expect us to remove report receivers from `sqmr_outbound_report_receivers` once the session is assigned and not once we got a response, and then this should be error log level, so I'm ok with either one
</blockquote></details>

leaving as error

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2234#-:-O2TiPJnEvTsm-SnrPOs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request closed without merging**
