### PR TITLE
refactor(execution): removed the ExecutionConfig struct

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/lib.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-Ne7XMqXARmi2szzsUpN:-Ne7XMqXARmi2szzsUpO:b-azbagk) ([raw file](https://github.com/starkware-libs/papyrus/blob/acdd5a7c801b11873bf5bab86595b70c79d25758/crates/papyrus_rpc/src/lib.rs#L55)):*
> ```XML
> 
> /// The path to the default execution config file.
> const DEFAULT_CONFIG_FILE: &str = "config/execution_config/default_config.json";
> ```

Delete - the rest of the default values are defined without consts



_Code quote:_
```XML
/// The path to the default execution config file.
const DEFAULT_CONFIG_FILE: &str = "config/execution_config/default_config.json";
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-Ne7bu8e0tGVy-Hzj5df:-Ne7bu8e0tGVy-Hzj5dg:be8omlh) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cef6c96ab135b4985d6cba5c4738294e5977b6e/crates/papyrus_config/src/validators.rs#L18)):*
> ```XML
> pub fn validate_file_exists(path: &Path) -> Result<(), ValidationError> {
>     if !path.exists() {
>         return Err(ValidationError::new("File not found"));
> ```

Add the file path to the error message

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-Ne7bu8e0tGVy-Hzj5df:-Ne7txKQ5FxlYV6PG8nn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cef6c96ab135b4985d6cba5c4738294e5977b6e/crates/papyrus_config/src/validators.rs#L18)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add the file path to the error message
</blockquote></details>

Done.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_config/src/validators.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-Ne7bu8e0tGVy-Hzj5df:-Ne7wKfC2pYeyiQzPLec:b-n5fs1g) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cef6c96ab135b4985d6cba5c4738294e5977b6e/crates/papyrus_config/src/validators.rs#L18)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`return Err(ValidationError::new(format!("File '{file_path}' does not exist.").as_str());`

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-Ne7bu8e0tGVy-Hzj5df:-Ne7xFNs7EKmviRjdaho:b-r15usk) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cef6c96ab135b4985d6cba5c4738294e5977b6e/crates/papyrus_config/src/validators.rs#L18)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

`return Err(ValidationError::new(format!("File '{file_path}' does not exist.").as_str());`
</blockquote></details>

The validators crate is already taking care of passing the params into the error.
I checked and this is the error that it outputs: 
ValidationErrors({"rpc": Struct(ValidationErrors({"execution_config": Field([ValidationError { code: "File not found", message: None, params: {"value": String("config/execution_config/default_config.jso")} }])}))})

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160#-:-NeCPd460yFF3jAcV_eQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
