### PR TITLE
Dan/monitoring/axum

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)

### CODE REVIEW

**Review by eranreshef-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTO5jv46hqeT0xUNpFw:-NTO5jv46hqeT0xUNpFx:b-ugg4bu) ([raw file](https://github.com/starkware-libs/papyrus/blob/72222c7c23127453e03a7f856da6b95dc5aad150/crates/papyrus_monitoring_gateway/src/lib.rs#L40)):*
> ```XML
>         &self,
>     ) -> tokio::task::JoinHandle<std::result::Result<(), hyper::Error>> {
>         let server_address = SocketAddr::from_str(&self.config.server_address)
> ```

I think the word "server" is too generic. This variable should the address of a specific server type.



_Code quote:_
```XML
server
```
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTO60nXCqEq29J4MKd5:-NTO60nXCqEq29J4MKd6:b-43vziy) ([raw file](https://github.com/starkware-libs/papyrus/blob/72222c7c23127453e03a7f856da6b95dc5aad150/crates/papyrus_monitoring_gateway/src/lib.rs#L47)):*
> ```XML
>             self.general_config_representation.clone(),
>         );
>         info!("Starting monitoring gateway, listening on {server_address:}.");
> ```

I think additional config values should be printed, at least in debug mode.

**Review by eranreshef-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTO6b6a41xVj6FuDCPX:-NTO6b6b5EHLxidPxxU6:bibhyoy) ([raw file](https://github.com/starkware-libs/papyrus/blob/72222c7c23127453e03a7f856da6b95dc5aad150/crates/papyrus_monitoring_gateway/src/lib.rs#L40)):*
> ```XML
>         &self,
>     ) -> tokio::task::JoinHandle<std::result::Result<(), hyper::Error>> {
>         let server_address = SocketAddr::from_str(&self.config.server_address)
> ```

I think the word "server" is too generic. This variable should contain the address of a specific server type.



_Code quote:_
```XML
server
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @eranreshef-starkware and @yair-starkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTNfl1x8b4XMvTp-nxv:-NTNvKuDBmdX7KQPhl8f:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L35)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do you need this function?
</blockquote></details>

Done.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTNf6jA7GA6DqraoBKg:-NTNwX2j5kUbS0-nx5zH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L37)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

add 
```#[instrument(skip(storage_reader), level = "debug", err)]```
</blockquote></details>

Done.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTO6b6a41xVj6FuDCPX:-NTSqwJMAzlpnMQhjx2k:b-f7uwor) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L40)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

I think the word "server" is too generic. This variable should contain the address of a specific server type.
</blockquote></details>

We are in a monitor server library, I think the context is clear. I'll make sure all logs include the server type though.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTNdZTR1uISiSM6hrCd:-NTNwgMX6zdGSyNFHhv0:bal9gzi) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider returning a result instead of expecting (the gateway also returns a result).
Also, I think the message is unclear - maybe "Expecting a valid address for the monitoring server.” 
</blockquote></details>

Changed according to https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTO60nXCqEq29J4MKd5:-NTSqtY64hFEdwHmSO38:b-o0dk48) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L47)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

I think additional config values should be printed, at least in debug mode.
</blockquote></details>

Done. (through the tracing span)
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTNgOTe1RtptEIo9dfb:-NTNwwpm0blUrcoIIYDc:b-5w5tpg) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L85)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this function needed?
</blockquote></details>

Not really, just wanted to have the same format for all routes. This also makes easier to use the instrument attribute.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/612#-NTNh55YALDIc3lhttje:-NTSgYpUEbxIQlE9mb0j:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/383a5e345e8e43b80dc7068238015567c7df1312/crates/papyrus_monitoring_gateway/src/lib.rs#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Derive thiserror instead of implementing From
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612#-:-NTStzaD-ysk-l_JIABv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @eranreshef-starkware)

**Review by eranreshef-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
