### PR TITLE
Add broadcasted tx struct with openrpc tests

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 8 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2pqLGDTqQb3bhJ8Wi:-N_444ip-nzicopxiQol:b2ni1ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't understand why V1 is from the client and V2 isn't.
</blockquote></details>

doc

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: 2 of 9 files reviewed, 8 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2kdMl1VDF6Ff5G2mS:-N_7OcQT4uVeTNxJte3B:bq9d74k) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L8)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please document why this is externalized.
</blockquote></details>

Should I make this pub and document that this is externalized since these structs are required to create a tx or make this private and add this imports when I want to create txs?
___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2pqLGDTqQb3bhJ8Wi:-N_7QCkC3I-8GhtosqDs:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2snbe4FDToxZxzRdd:-N_8NJQxBvoKYQXi7RXa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not add the broadcasted transactions to test_utils? 
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2roaTCVFkkLCMQTGy:-N_8NHrz2KEAvlcqRvBm:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not Calldata::get_test_instance()?
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2sYLa5aAEMLPvMOkz:-N_8NIaWDut3br4Ujoox:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L32)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/lib.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2tK7T4qF__gFewjyI:-N_7ST289BXL4iW4SgTg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/lib.rs#L3)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it needs to be pub because the API needs to expose the broadcasted transactions
</blockquote></details>

Done.
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2m7v2Cv-qLp6Ik7WS:-N_7TttaA-0ltM5xxxoe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/starknet_writer_client/src/objects/transaction.rs#L75)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

deprecated ContractClass
</blockquote></details>

Done.
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2mOm78JXjoaIu1sRd:-N_7TtXl84vJSZckaAO8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/starknet_writer_client/src/objects/transaction.rs#L87)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think you should mention the difference between SN_API, not the gateway.
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2kdMl1VDF6Ff5G2mS:-N_8T7tY4qePMdlMpnww:b3xg0qy) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L8)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Should I make this pub and document that this is externalized since these structs are required to create a tx or make this private and add this imports when I want to create txs?
</blockquote></details>

Maybe create a public alias?
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_8TmzZ9vJK-FvMER7_:-N_8TmzZ9vJK-FvMER7a:b-g4x52o) ([raw file](https://github.com/starkware-libs/papyrus/blob/6aa14010c907ae34ea13c16633127fe841a58747/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L41)):*
> ```XML
>         pub abi: String,
>     }
> }
> ```

Why are you doing this here and not in the TestUtils crate?



_Code quote:_
```XML
auto_impl_get_test_instance! {
    pub struct BroadcastedDeclareV2Transaction {
        pub contract_class: ContractClass,
        pub compiled_class_hash: CompiledClassHash,
        pub sender_address: ContractAddress,
        pub nonce: Nonce,
        pub max_fee: Fee,
        pub version: TransactionVersion,
        pub signature: TransactionSignature,
    }
    pub struct ContractClass {
        pub sierra_program: Vec<StarkFelt>,
        pub contract_class_version: String,
        pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
        pub abi: String,
    }
}
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2kdMl1VDF6Ff5G2mS:-N_8WDk71DOwM13ViYZL:bv8o2l5) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L8)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Consider renaming to Broadcasted instead of Client - I think it can solve much confusion.
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_8TmzZ9vJK-FvMER7_:-N_8WbaF8Ijzfm8yBPhg:b-tg59lc) ([raw file](https://github.com/starkware-libs/papyrus/blob/6aa14010c907ae34ea13c16633127fe841a58747/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Because this crate depends on the test_util, and doing what you suggested will cause a cyclic dependency
</blockquote></details>

Oh the TestUtils works only on SN_API types, I didn't realize that...
This is another indication that the Broadcasted transactions should be there.
Resolving the issue for now.

**Review by yair-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_2kdMl1VDF6Ff5G2mS:-N_8hKyv07JaFnbDHGYW:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/1791236bf85df8547465bdb8c12c5121964fec88/crates/papyrus_gateway/src/broadcasted_transaction.rs#L8)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider renaming to Broadcasted instead of Client - I think it can solve much confusion.
</blockquote></details>

Done

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 7 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824#-:-N_8ipCi8Xj61IbbQNNO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E30EZ0S-d-VA6vWNi:-N_E30EZ0S-d-VA6vWNj:b-rlwugb) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L19)):*
> ```XML
>     #[serde(rename = "DECLARE")]
>     // Declare is not from the client because the broadcasted transaction of declare has slight
>     // alterations from the client declare.
> ```

No need for that IMO.



_Code quote:_
```XML
    // Declare is not from the client because the broadcasted transaction of declare has slight
    // alterations from the client declare.
```

**Comment by dan-starkware** [comment]
Please add doc comments where relevant.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E42OoBQwBq77P4y5z:-N_E42OoBQwBq77P4y6-:b4vw29x) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L32)):*
> ```XML
>     DeclareV1(BroadcastedDeclareV1Transaction),
>     // DeclareV2 is not from the client because the broadcasted transaction of declare v2 has
>     // slight alterations from the client declare v2.
> ```

Why do we refer to it here?



_Code quote:_
```XML
    // DeclareV2 is not from the client because the broadcasted transaction of declare v2 has
    // slight alterations from the client declare v2.
```

**Comment by dan-starkware** [comment]
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 82 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EAb-W1-MY1yUM8OQK:-N_EAb-W1-MY1yUM8OQL:byp18fd) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L82)):*
> ```XML
>     #[serde(default)]
>     pub abi: Option<Vec<DeprecatedContractClassAbiEntry>>,
>     // The program is compressed.
> ```

Remove

**Comment by dan-starkware** [comment]
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_ECrMp2vlxBvhNfAE3:-N_ECrMp2vlxBvhNfAE4:b-tbigzu) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L76)):*
> ```XML
> 
> // The only difference between this and ContractClass in starknet_api (in the
> // deprecated_contract_class module) is in the program.
> ```

Will defining generic fields (with default types) in the API work?
These comments are made to break..



_Code quote:_
```XML
// The only difference between this and ContractClass in starknet_api (in the
// deprecated_contract_class module) is in the program.
```

**Comment by dan-starkware** [comment]
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EDOYb0GcdZ5gaiFAy:-N_EDOYb0GcdZ5gaiFAz:bw52pjx) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L120)):*
> ```XML
> }
> 
> #[cfg(any(feature = "testing", test))]
> ```

Maybe in test_utils?



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
```

**Comment by dan-starkware** [comment]
*[`crates/starknet_writer_client/Cargo.toml` line 11 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EDsqY-5ifPsy_YkPm:-N_EDsqY-5ifPsy_YkPn:b4awvnc) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/Cargo.toml#L11)):*
> ```TOML
> testing = [
>     "rand",
>     "rand_chacha",
> ```

Do we need these? Who needs it, we don't see these as conditional compilation features.



_Code quote:_
```TOML
    "rand",
    "rand_chacha",
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 9 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E30EZ0S-d-VA6vWNi:-N_EFrWq24NLHHYX3DNa:byp18fd) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

No need for that IMO.
</blockquote></details>

Remove
___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E42OoBQwBq77P4y5z:-N_EFtmW-LsGKsRIcvU8:bbn0cnu) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L32)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we refer to it here?
</blockquote></details>

Move to top
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EGwR1EXXi5XkgMHN2:-N_EGwR1EXXi5XkgMHN3:b-xodb1w) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
> ```XML
> 
> fn validate_tx_fits_rpc(tx: BroadcastedTransaction) {
>     let schema = block_on(get_starknet_spec_api_schema(&["BROADCASTED_TXN"]));
> ```

Just make sure we don't loose performance 



_Code quote:_
```XML
 block_on
```
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EHL8n-uKZxxOIj5SQ:-N_EHL8n-uKZxxOIj5SR:bylt42h) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
> ```XML
> 
> fn validate_tx_fits_rpc(tx: BroadcastedTransaction) {
>     let schema = block_on(get_starknet_spec_api_schema(&["BROADCASTED_TXN"]));
> ```

Can we do the IO part once for all tests?



_Code quote:_
```XML
(get_starknet_spec_api_schema
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E3Ctv600wAoKZND5V:-N_E_qlhBXsbxEY_pDb1:b-4d4k4i) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add doc comments where relevant. 
</blockquote></details>

Will be done in next PR

___
___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E30EZ0S-d-VA6vWNi:-N_E3vZwAqTHvZM3U_Cg:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done
___
*[`crates/papyrus_gateway/src/broadcasted_transaction.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_E42OoBQwBq77P4y5z:-N_E4Kbq-QIybQCoFAcQ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction.rs#L32)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Move to top
</blockquote></details>

Done
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EGwR1EXXi5XkgMHN2:-N_EmdVJCxOlrvAXybYt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Just make sure we don't loose performance 
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EHL8n-uKZxxOIj5SQ:-N_EmduSChboZC-5-B7M:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we do the IO part once for all tests?
</blockquote></details>

Done.
___
*[`crates/starknet_writer_client/Cargo.toml` line 11 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EDsqY-5ifPsy_YkPm:-N_EpPdl80Qe1Fj97Imm:b-v9iayo) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/Cargo.toml#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need these? Who needs it, we don't see these as conditional compilation features.
</blockquote></details>

The macro uses them. I've changed it so that the macro makes sure we don't need to add a use statement for rand and rand_chacha but we still need to depend on those crates
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_ECrMp2vlxBvhNfAE3:-N_Emsux4zbuxsrSDnB_:b-7zozo6) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L76)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Will defining generic fields (with default types) in the API work?
These comments are made to break..
</blockquote></details>

In a future PR
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 82 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EAb-W1-MY1yUM8OQK:-N_Ems444NUI76wbDtUf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L82)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EDOYb0GcdZ5gaiFAy:-N_EpNcl-0jli2j1NPK4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5bf27bb08d3a2ce6349a5f163454be947d88499f/crates/starknet_writer_client/src/objects/transaction.rs#L120)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Maybe in test_utils?
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824#-:-N_Et6jWCzii45z_ey4j:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EHL8n-uKZxxOIj5SQ:-N_F0QYX77IMIWwxVBPr:b3xr9qm) ([raw file](https://github.com/starkware-libs/papyrus/blob/72730e39fb1242b51bfe4aa37b41dd3e807680b9/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Will it be shared among all test-cases? Can you direct me to the corresponding documentation?

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/broadcasted_transaction_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/824#-N_EHL8n-uKZxxOIj5SQ:-N_STAVa9-ckdHZUzT4w:bqe5x2x) ([raw file](https://github.com/starkware-libs/papyrus/blob/72730e39fb1242b51bfe4aa37b41dd3e807680b9/crates/papyrus_gateway/src/broadcasted_transaction_test.rs#L45)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Will it be shared among all test-cases? Can you direct me to the corresponding documentation?
</blockquote></details>

https://docs.rs/lazy_static/latest/lazy_static/
I added a println to get_starknet_spec_api_schema and it was printed only once

**Review by dan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/824#-:-N_SWdK02cMZLXPoufV8:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
