### PR TITLE
feat(network): add peer manager struct - not used yet

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1874** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1874?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)* status: all files reviewed, 22 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwln4W8aSfdxofHZkA:-Nuwln4W8aSfdxofHZkB:b5brk17) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L24)):*
> ```XML
>     query_to_peer_map: HashMap<QueryId, PeerId>,
>     config: PeerManagerConfig,
>     last_peer_idx: usize,
> ```

idx -> index
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwo42b-387CuktxPon:-NuwnmfN65WJJL3RAXnH:b-ncrgvi) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L36)):*
> ```XML
> pub(crate) enum PeerManagerError {
>     #[error("No such peer: {0}")]
>     NoSuchPeer(PeerId),
> ```

I like this. We should rename our other errors in the network to NoSuch*
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuws7nh3hxAUJjXd5oH:-Nuws7nh3hxAUJjXd5oI:bb7bl4y) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L43)):*
> ```XML
> impl Default for PeerManagerConfig {
>     fn default() -> Self {
>         Self { target_num_for_peers: 100, blacklist_timeout: Duration::MAX }
> ```

Please check that adding Duration::MAX to an Instant won't cause overflow
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmK8_ANKRWY77r1P2:-NuwmK8_ANKRWY77r1P3:b-lw641c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L57)):*
> ```XML
>     }
> 
>     fn add_peer(&mut self, mut peer: P) {
> ```

pub fn
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmNOtBchYhmjzoXSf:-NuwmNOtBchYhmjzoXSg:b-lw641c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L67)):*
> ```XML
>     }
> 
>     fn assign_peer_to_query(&mut self, query_id: QueryId) -> Option<(PeerId, Multiaddr)> {
> ```

pub fn
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmZKEAWKH6RZJ4npV:-NuwmZKEAWKH6RZJ4npW:b-pzwms0) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L71)):*
> ```XML
>             return None;
>         }
>         let peer = self.peers.iter().skip(self.last_peer_idx).find(|(_, peer)| !peer.is_blocked());
> ```

If you didn't find in the range [last_peer_idx, peers.len()), you should look in the range [0, last_peer_idx)
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmP1j5vlbatfp-bJi:-NuwmP1j5vlbatfp-bJj:b-lw641c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L79)):*
> ```XML
>     }
> 
>     fn report_peer(
> ```

pub fn
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmRBP0vuZUIVOrPxt:-NuwmRBP0vuZUIVOrPxu:b-lw641c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L92)):*
> ```XML
>     }
> 
>     fn report_query(
> ```

pub fn
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwnf7qBRoHexyWQw6n:-Nuwnf7qBRoHexyWQw6o:b-x2yvhx) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L105)):*
> ```XML
>             }
>         } else {
>             Err(PeerManagerError::NoSuchPeer(PeerId::random()))
> ```

Make a different variant called NoSuchQuery
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwmSuxAFvhnCdnALI-:-NuwmSuxAFvhnCdnALI0:b-lw641c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L109)):*
> ```XML
>     }
> 
>     fn more_peers_needed(&self) -> bool {
> ```

pub fn
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwsVPQDCuw9gQDCJWZ:-NuwsVPQDCuw9gQDCJW_:b-rhf1g5) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L110)):*
> ```XML
> 
>     fn more_peers_needed(&self) -> bool {
>         self.peers.len() < self.config.target_num_for_peers
> ```

Add TODO to consider counting only non blocked peers
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwoQNF-KarePVNiFTX:-NuwoQNF-KarePVNiFTY:b-rtgho3) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L13)):*
> ```XML
>     fn update_reputation(&mut self, reason: ReputationModifier) -> Result<(), PeerError>;
> 
>     fn get_id(&self) -> PeerId;
> ```

Remove the get, it doesn't correspond to rust style guide
Additionally, change the id to peer_id. It's a term from libp2p (The second point is relevant even if you disagree on the first)
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwoE1P2G6FEsnhpj8v:-NuwoE1P2G6FEsnhpj8w:bhajy6s) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L15)):*
> ```XML
>     fn get_id(&self) -> PeerId;
> 
>     fn get_multiaddr(&self) -> Multiaddr;
> ```

Remove the get, it doesn't correspond to rust style guide
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwnGAp9nqLd3-5O-Ge:-NuwnGAp9nqLd3-5O-Gf:btjpwwv) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L17)):*
> ```XML
>     fn get_multiaddr(&self) -> Multiaddr;
> 
>     fn set_timeout_duration(&mut self, duration: Duration);
> ```

Why not put it as part of the constructor `fn new(duration: Duration) -> Self` and then the timeout_duration will be non option and you can erase PeerError
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwojLy17U0kRFYpMqb:-NuwojLy17U0kRFYpMqc:b-jojfvb) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L30)):*
> ```XML
> #[derive(Clone)]
> pub(crate) struct Peer {
>     id: PeerId,
> ```

id -> peer_id
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwryHaEig8cPrUA4av:-NuwryHaEig8cPrUA4aw:b-cxi2a2) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L32)):*
> ```XML
>     id: PeerId,
>     multiaddr: Multiaddr,
>     timed_out_until: Option<time::Instant>,
> ```

Consider importing Instant. I don't see a difference between Instant and Duration
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwon774XWj-N4qCXWz:-Nuwon774XWj-N4qCXX-:b-jojfvb) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L38)):*
> ```XML
> #[allow(dead_code)]
> impl Peer {
>     pub fn new(id: PeerId, multiaddr: Multiaddr) -> Self {
> ```

id -> peer_id
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwouKk-8fXRrmCYET7:-NuwouKk-8fXRrmCYET8:b-kn9dtw) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L45)):*
> ```XML
> impl PeerTrait for Peer {
>     fn update_reputation(&mut self, _reason: ReputationModifier) -> Result<(), PeerError> {
>         if let Some(timeout_duration) = self.timeout_duration {
> ```

Consider using let else
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwp1qaCtABPD6N3DhO:-Nuwp1qaCtABPD6N3DhP:bftq8b) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L65)):*
> ```XML
> 
>     fn is_blocked(&self) -> bool {
>         if let Some(timed_out_until) = self.timed_out_until {
> ```

Consider `self.timed_out_until.map(|timed_out_until| timed_out_until > time::Instant::now()).unwrap_or(false)`
Both are valid. Choose whatever you think is cleaner
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwrbaHBq1chFYQoBSE:-NuwrbaHBq1chFYQoBSF:b-8ch3ke) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L1)):*
> ```XML
> use std::time::Duration;
> ```

Add test with a low blacklist_timeout in the config and check that the peer becomes unblocked after you sleep for blacklist_timeout
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwqojy5YLJRw5clLiZ:-Nuwqojy5YLJRw5clLi_:b1j8rk7) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L33)):*
> ```XML
> 
>     // Verify that the peers are assigned in a round-robin fashion
>     match res1.unwrap().0 {
> ```

Isn't it always guaranteed that the first peer will be the first?
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwqzgh6WHfd-xOUk0m:-Nuwqzgh6WHfd-xOUk0n:b-qkglxj) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L46)):*
> ```XML
> }
> 
> #[test]
> ```

Add test where there are no blocked peers. You can do it in this test if you want
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwq7h91pN4DOAUqZdO:-Nuwq7hAB5E4Z5v4_Ts5:b-5h5hfe) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L178)):*
> ```XML
>     let peer_id = PeerId::random();
>     let mut peer = MockPeerTrait::new();
>     let mut mockall_seq = mockall::Sequence::new();
> ```

Reminding you to erase this if we decide erasing set_timeout_duration :)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuws7nh3hxAUJjXd5oH:-Nv0RqLiDH-7-5X9-A6_:b1c07m6) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L43)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

moved to chrono time to support all OSs (previous version works only on linux without panic)
</blockquote></details>

Could you add a comment above the use statement stating why we use chrono and not std?
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwnGAp9nqLd3-5O-Ge:-Nv0SF7zEOIZ9DV44Nm8:b-hxjhii) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L17)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

because peer is public interface and I don't want the  consumers to have the ability to put whatever timeout they want. I want the peer manager to have control of it.
</blockquote></details>

You can make the `new` function pub(super)
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwqzgh6WHfd-xOUk0m:-Nv0SoYb5wdU17tUltsF:bme5fl0) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L46)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

isn't it the previous test `peer_assignment_round_robin`?
</blockquote></details>

Sorry, I meant where all peers are blocked in my original comment
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nv0SXqf6x9cJIYCoB1N:-Nv0SXqgAAZy39d0ArkC:b-xl6mvc) ([raw file](https://github.com/starkware-libs/papyrus/blob/76d379e18ecd83a6c07e2303d32c80f3b5506561/crates/papyrus_network/src/peer_manager/test.rs#L83)):*
> ```XML
>     peer.update_reputation(ReputationModifier::Bad {}).unwrap();
>     assert!(peer.is_blocked());
>     sleep(time::Duration::from_secs(1)).await;
> ```

Does this test take 1 second? If yes, reduce the timeout to 10/50 milliseconds and anyway, extract the time to a constant at the start of the test

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwq7h91pN4DOAUqZdO:-Nv0TBa02C2OibOwF8Zf:bvds3qf) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L178)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

:)
</blockquote></details>

Still reminding because that discussion is open

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuws7nh3hxAUJjXd5oH:-Nv0aNsI35-XkZ4Oe-Pk:bsrcuw5) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/mod.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Could you add a comment above the use statement stating why we use chrono and not std?
</blockquote></details>

I think no one will ever give a shit but sure...
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-NuwnGAp9nqLd3-5O-Ge:-Nv0Zyhe-AERUay9TMdW:b-onyhga) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/peer.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can make the `new` function pub(super)
</blockquote></details>

no.. I do want the ability to create new peers just not to set the timeout duration.
once you add a peer you pass ownership to the peer manager which then is setting the duration
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nuwqzgh6WHfd-xOUk0m:-Nv0_ICo7U0n5t2U4bR4:b-968w6b) ([raw file](https://github.com/starkware-libs/papyrus/blob/5d501d989f963770db4837b13be49fb975c97612/crates/papyrus_network/src/peer_manager/test.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Sorry, I meant where all peers are blocked in my original comment
</blockquote></details>

given you can block a peer it's the same functionality as having no peers.. I don't see the value in it
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-Nv0SXqf6x9cJIYCoB1N:-Nv0iAP81IoL5rkTHYBh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76d379e18ecd83a6c07e2303d32c80f3b5506561/crates/papyrus_network/src/peer_manager/test.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Does this test take 1 second? If yes, reduce the timeout to 10/50 milliseconds and anyway, extract the time to a constant at the start of the test
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1874#-:-NvRLzDl-Iq8P4X9Jwrl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
