### PR TITLE
feat: add PendingBlockHeader struct

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)* status: all files reviewed, 6 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1-Fkb2u36XQmQBZ2T:-Nh1-Fkb2u36XQmQBZ2U:b-f3y44n) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L18)):*
> ```XML
>     pub block_hash: BlockHash,
>     pub parent_hash: BlockHash,
>     pub block_number: BlockNumber,
> ```

Consider putting here a pending block header with serde(flatten)
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh14P7r1cPs18eNbFqe:-Nh14P7r1cPs18eNbFqf:b-t1l5l1) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L25)):*
> ```XML
> 
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct PendingBlockHeader {
> ```

Add deny_unknown_fields. Otherwise a non-pending block header can be accidentally deserialized as pending
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh0zijE9hiwjLhAwtK-:-Nh0zijE9hiwjLhAwtK0:b-nq50s3) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L33)):*
> ```XML
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> #[serde(untagged)]
> pub enum BlockHeaderOrPending {
> ```

The convention I did was GeneralXXX, but we can go with your convention.
Tell me what do you prefer and either I/you will change my/your PR
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh144HzCwRAKHj0hANc:-Nh144HzCwRAKHj0hANd:b-b4go89) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L53)):*
> ```XML
> impl From<starknet_api::block::BlockHeader> for BlockHeaderOrPending {
>     fn from(header: starknet_api::block::BlockHeader) -> Self {
>         let block_header = BlockHeader {
> ```

Use From of BlockHeader
I think it's best to just use the BlockHeader conversion and wrap it with BlockHeaderOrPending whenever you need. It's much more explicit. Here you're not sure if the returning header is pending or not
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh14kaA05A1PLsHlq4V:-Nh14kaA05A1PLsHlq4W:bcrkna6) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L378)):*
> ```XML
>         transactions: Transactions::Full(vec![expected_transaction]),
>     };
>     let expected_block_header = match expected_block.clone().header {
> ```

Consider using let else instead
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 469 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh14r2MEaXar6ePspwL:-Nh14r2MEaXar6ePspwM:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L469)):*
> ```XML
>         transactions: Transactions::Hashes(vec![block.body.transaction_hashes[0]]),
>     };
>     let expected_block_header = match expected_block.clone().header {
> ```

Same here

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1 and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1-Fkb2u36XQmQBZ2T:-Nh16kD82-nvOeRijeLb:buq1ik2) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider putting here a pending block header with serde(flatten)
</blockquote></details>

Not done.
Theoretically we might want to add properties to PendingBlockHeader and not to BlockHeader.
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh14P7r1cPs18eNbFqe:-Nh16fzT4rSg18846p30:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L25)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add deny_unknown_fields. Otherwise a non-pending block header can be accidentally deserialized as pending
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh0zijE9hiwjLhAwtK-:-Nh17-6j6D7a2B3_cPpU:b6dkrfe) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L33)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The convention I did was GeneralXXX, but we can go with your convention.
Tell me what do you prefer and either I/you will change my/your PR
</blockquote></details>

I don't see any example of that format. But anyway, done.
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh144HzCwRAKHj0hANc:-Nh1A4VXEaSHZ6JlDdjQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use From of BlockHeader
I think it's best to just use the BlockHeader conversion and wrap it with BlockHeaderOrPending whenever you need. It's much more explicit. Here you're not sure if the returning header is pending or not
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)* status: all files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh0zijE9hiwjLhAwtK-:-Nh1GT2N87sgUrWof1_X:b-xg0ni0) ([raw file](https://github.com/starkware-libs/papyrus/blob/448dcaa169087602cd707685ea6bbd37b268fe3c/crates/papyrus_rpc/src/v0_4_0/block.rs#L33)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I don't see any example of that format. But anyway, done.
</blockquote></details>

Yes. It's in PR
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 379 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1Ggc5DQaqTP0lgSGi:-Nh1Ggc64cAaZcd3wPVS:b73etl4) ([raw file](https://github.com/starkware-libs/papyrus/blob/796a73921f6417953efbe2ee72bdffe657da06c9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L379)):*
> ```XML
>     };
>     let expected_block_header =
>         if let GeneralBlockHeader::BlockHeader(block_header) = expected_block.clone().header {
> ```

Why double let?
```
let GeneralBlockHeader::BlockHeader(expected_block_header) = expected_block.clone().header else {
    panic...
}
```

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 382 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1H4pv-ZCC42ROCEO-:-Nh1H4pv-ZCC42ROCEO0:b-uf4vb2) ([raw file](https://github.com/starkware-libs/papyrus/blob/796a73921f6417953efbe2ee72bdffe657da06c9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L382)):*
> ```XML
>             block_header
>         } else {
>             panic!("Expected block header");
> ```

Try to find a better message
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1H8YeE2D7i_P90RPV:-Nh1H8YeE2D7i_P90RPW:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/796a73921f6417953efbe2ee72bdffe657da06c9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L471)):*
> ```XML
>         transactions: Transactions::Hashes(vec![block.body.transaction_hashes[0]]),
>     };
>     let expected_block_header =
> ```

Same here

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 379 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1Ggc5DQaqTP0lgSGi:-Nh1Hm934TmyvSExz2lf:b-qnssuh) ([raw file](https://github.com/starkware-libs/papyrus/blob/796a73921f6417953efbe2ee72bdffe657da06c9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L379)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why double let?
```
let GeneralBlockHeader::BlockHeader(expected_block_header) = expected_block.clone().header else {
    panic...
}
```

</blockquote></details>

right. this is what happens when using chat GPT :(
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-Nh1H8YeE2D7i_P90RPV:-Nh1Ld4j0APGlV59SLjj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/796a73921f6417953efbe2ee72bdffe657da06c9/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L471)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285#-:-Nh1QUd71pdbr2x1C6Ht:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
