### PR TITLE
feat(JSON-RPC): add deprecated contract class to getCompiledContractC…

### PR DESCRIPTION
**Pull request by Yael-Starkware**
…lass

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDL6ECFtYBVHubwKi:-NzhDL6ECFtYBVHubwKj:bgjra52) (no related file):*
The contract could be a big object. You should consider maybe compressing it before sending it to the network

___
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1453 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhCdLBAk48t9DWyCmp:-NzhCdLBAk48t9DWyCmq:b4jztil) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1453)):*
> ```XML
>         }
> 
>         if let Some(casm) = storage_txn.get_casm(&class_hash).map_err(internal_server_error)? {
> ```

Why did you change the error type?



_Code quote:_
```XML
internal_server_error
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1460 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDApwADyDZDy3gQvv:-NzhDApwADyDZDy3gQvw:b-2l9bzo) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1460)):*
> ```XML
>             .ok_or_else(|| ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND))?;
>         let deprecated_compiled_contract_class = storage_txn
>             .get_state_reader()
> ```

Consider creating state reader only once



_Code quote:_
```XML
.get_state_reader()
```
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3574 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDfJYBvHg15BmxPsa:-NzhDfJYBvHg15BmxPsb:b2i836p) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/test.rs#L3574)):*
> ```XML
>     let casm_class_hash = ClassHash(stark_felt!("0x1"));
>     let casm_contract_class = CasmContractClass::get_test_instance(&mut get_rng());
>     let deprecated_class_hash = ClassHash(stark_felt!("0x2"));
> ```

Consider using the constant of felt



_Code quote:_
```XML
stark_felt!("0x2")
```
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3585 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhEDwh6klFlnY335Q-:-NzhEDwh6klFlnY335Q0:b-nus5lk) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/test.rs#L3585)):*
> ```XML
>                 declared_classes: IndexMap::from([
>                     (casm_class_hash, CompiledClassHash::default()),
>                     (deprecated_class_hash, CompiledClassHash::default()),
> ```

There is a different section in the state diff for deprecated classes

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDL6ECFtYBVHubwKi:-NzhHPOpELrytuNFIS8B:b-pflipl) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

The contract could be a big object. You should consider maybe compressing it before sending it to the network
</blockquote></details>

Currently we use the rpc call only for testing. the actual product will work with p2p so no need to optimize atm.

___
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1453 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhCdLBAk48t9DWyCmp:-NzhHiwE4zG-fIuDtZnh:b-3y3uwr) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1453)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why did you change the error type?
</blockquote></details>

There was a confusion about the way the class hash table works.
I think now it should be fixed. 
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1460 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDApwADyDZDy3gQvv:-NzhIDUx2dZcR1tU6skp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1460)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider creating state reader only once
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3574 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhDfJYBvHg15BmxPsa:-NzhJlqt02lkxgTPecnw:b-1iolgf) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/test.rs#L3574)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider using the constant of felt
</blockquote></details>

done.

people here don't like consts inside function but it seems fit to me, let me know what you think.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3585 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-NzhEDwh6klFlnY335Q-:-NzhJuyr05wBEJKKM1YH:bm9p5li) ([raw file](https://github.com/starkware-libs/papyrus/blob/4abd393aa1f32469fb5a1b70ce3a6030f63848d4/crates/papyrus_rpc/src/v0_7/api/test.rs#L3585)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

There is a different section in the state diff for deprecated classes
</blockquote></details>

oh that explains a lot! I thought I found a bug in the storage reader! but now it makes sense.
I hope now it's right.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3571 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-1Osdp9FiePquuAb6I:-O-1Osdp9FiePquuAb6J:bcvkwls) ([raw file](https://github.com/starkware-libs/papyrus/blob/a1275f3e43325ace2e6823cdc397a5e46a7cbf0c/crates/papyrus_rpc/src/v0_7/api/test.rs#L3571)):*
> ```XML
>     const DEPRECATED_CLASS_HASH: ClassHash = ClassHash(StarkFelt::from_u128(2));
>     const INVALID_CLASS_HASH: ClassHash = ClassHash(StarkFelt::from_u128(3));
> ```

not sure how you feel about constants inside a function, do you think it's batter to change it to regular variable?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3571 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-1Osdp9FiePquuAb6I:-O-1P56E2PVNWKPjyozl:b-ab1jwr) ([raw file](https://github.com/starkware-libs/papyrus/blob/a1275f3e43325ace2e6823cdc397a5e46a7cbf0c/crates/papyrus_rpc/src/v0_7/api/test.rs#L3571)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure how you feel about constants inside a function, do you think it's batter to change it to regular variable?
</blockquote></details>

*better

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3571 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-1Osdp9FiePquuAb6I:-O-UQ5QA4QZo3vWRDKFM:bgoj8hb) ([raw file](https://github.com/starkware-libs/papyrus/blob/a1275f3e43325ace2e6823cdc397a5e46a7cbf0c/crates/papyrus_rpc/src/v0_7/api/test.rs#L3571)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

*better
</blockquote></details>

actually it looked bad , so I made them variables.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1444 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W-c3YAcuDW_DVGInu:-O-W-c3YAcuDW_DVGInv:b-22p6m4) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1444)):*
> ```XML
>     ) -> RpcResult<CompiledContractClass> {
>         let storage_txn = self.storage_reader.begin_ro_txn().map_err(internal_server_error)?;
>         let state_reader = storage_txn.get_state_reader().map_err(internal_server_error)?;
> ```

Do it in one line



_Code quote:_
```XML
        let storage_txn = self.storage_reader.begin_ro_txn().map_err(internal_server_error)?;
        let state_reader = storage_txn.get_state_reader().map_err(internal_server_error)?;
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1446 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W1Zfa3s9Z7UmKkQyu:-O-W1Zfa3s9Z7UmKkQyv:b8hamon) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1446)):*
> ```XML
>         let state_reader = storage_txn.get_state_reader().map_err(internal_server_error)?;
>         let block_number = get_accepted_block_number(&storage_txn, block_id)?;
>         if let Some(class_definition_block_number) = state_reader
> ```

Consider adding a comment here to say that this is the logic for cairo1
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1461 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W20Mm93Kr8zHQ5uML:-O-W20Mm93Kr8zHQ5uMM:bkgr8yh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1461)):*
> ```XML
> 
>         let state_number = StateNumber::right_after_block(block_number)
>             .ok_or_else(|| ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND))?;
> ```

This error should be `internal_server_error`.  The fact we fail to get the state after the block has nothing to do with the CLASS_HASH_NOT_FOUND error.



_Code quote:_
```XML
.ok_or_else(|| ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND))?;
```
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1462 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W2MReAypGwsltCSEi:-O-W2MReAypGwsltCSEj:b-lgrysa) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1462)):*
> ```XML
>         let state_number = StateNumber::right_after_block(block_number)
>             .ok_or_else(|| ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND))?;
>         let deprecated_compiled_contract_class = state_reader
> ```

Here, consider adding a comment for cairo0 classes
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3568 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W5Fzb74L5tplciWTK:-O-W5Fzb74L5tplciWTL:b-whcc89) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3568)):*
> ```XML
> }
> 
> #[tokio::test]
> ```

Add todo to the test to add cases for block numbers that are not the latest.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3570 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W2sm_3wMcpl5inn5J:-O-W2sm_3wMcpl5inn5K:b9tv2np) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3570)):*
> ```XML
> #[tokio::test]
> async fn get_compiled_contract_class() {
>     let casm_class_hash = ClassHash(felt!("0x1"));
> ```

Consider using Felt constants. Felt::ONE...
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3570 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W4k21BzmoPKZeNJpq:-O-W4k21BzmoPKZeNJpr:b-atviga) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3570)):*
> ```XML
> #[tokio::test]
> async fn get_compiled_contract_class() {
>     let casm_class_hash = ClassHash(felt!("0x1"));
> ```

Consider changing this to `sierra_class_hash`. The compiled class hash is a different thing.



_Code quote:_
```XML
casm_class_hash
```
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3586 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W3sID67mwpdd7eKBk:-O-W3sID67mwpdd7eKBl:bv3enno) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3586)):*
> ```XML
>         .append_state_diff(
>             BlockNumber(0),
>             starknet_api::state::ThinStateDiff {
> ```

You forgot the field `deprecated_declared_classes` of the `ThinStateDiff`
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3594 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W4P_n0_ZvfH1T2a_5:-O-W4P_n0_ZvfH1T2a_6:b-94cvq7) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3594)):*
> ```XML
>         .append_casm(&casm_class_hash, &casm_contract_class)
>         .unwrap()
>         .append_classes(BlockNumber(0), &[], &[(deprecated_class_hash, &deprecated_contract_class)])
> ```

Please also add Sierra corresponding to the casm to the storage. Or at least add a comment about that
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3614 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W5Cln3Ksp8IbZr-aL:-O-W5Cln3Ksp8IbZr-aM:b-p3n1wk) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3614)):*
> ```XML
>     assert_eq!(res, CompiledContractClass::V0(deprecated_contract_class));
> 
>     // Ask for an invalid class hash.
> ```

consider: not existing



_Code quote:_
```XML
an invalid
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1444 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W-c3YAcuDW_DVGInu:-O-W6nanE0yUIvli7jFy:b-pbqw9c) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1444)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Do it in one line
</blockquote></details>

but I need both storage_txn and state_reader for the following code.
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1446 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W1Zfa3s9Z7UmKkQyu:-O-W6tKNC_t2h5Lylfv-:b-7rl0jd) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1446)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider adding a comment here to say that this is the logic for cairo1
</blockquote></details>

done.
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1461 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W20Mm93Kr8zHQ5uML:-O-W7VT08N0GfW6w5-m5:b-7rl0jd) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1461)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This error should be `internal_server_error`.  The fact we fail to get the state after the block has nothing to do with the CLASS_HASH_NOT_FOUND error.
</blockquote></details>

done.
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1462 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W2MReAypGwsltCSEi:-O-W84cY7I_kD_fTN1TP:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1462)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Here, consider adding a comment for cairo0 classes
</blockquote></details>

done
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3568 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W5Fzb74L5tplciWTK:-O-W8Drx8ZPoOpZmV2kH:b-7rl0jd) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3568)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Add todo to the test to add cases for block numbers that are not the latest.
</blockquote></details>

done.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3570 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W2sm_3wMcpl5inn5J:-O-W8UL74MrmD1U8G2iK:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3570)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider using Felt constants. Felt::ONE...
</blockquote></details>

done
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3570 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W4k21BzmoPKZeNJpq:-O-W8g4E0qrIRI54uNpa:bu6mz1m) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3570)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider changing this to `sierra_class_hash`. The compiled class hash is a different thing.
</blockquote></details>

right.
changed everything to cairo1 and cairo0 for readability.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3586 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W3sID67mwpdd7eKBk:-O-W9GSB3ShmXhkrNFrl:bruejnc) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3586)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

You forgot the field `deprecated_declared_classes` of the `ThinStateDiff`
</blockquote></details>

I did not forget it, I just went through the code and saw that this field is not used in this flow.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3594 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W4P_n0_ZvfH1T2a_5:-O-W9cQO4-FgHZkvjuhJ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3594)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Please also add Sierra corresponding to the casm to the storage. Or at least add a comment about that
</blockquote></details>

done.
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3614 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W5Cln3Ksp8IbZr-aL:-O-W9c9K8nDzFPYAdp9x:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3614)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider: not existing
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3586 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W3sID67mwpdd7eKBk:-O-aVtoD9YNZZ7CLPnTq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/test.rs#L3586)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I did not forget it, I just went through the code and saw that this field is not used in this flow.
</blockquote></details>

Done.

**Review by DvirYo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-:-O-ad8Cu7BocGzircsy2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1444 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-W-c3YAcuDW_DVGInu:-O-acDPA5z9O5Br2dIsM:b-hc0i94) ([raw file](https://github.com/starkware-libs/papyrus/blob/8dfd3edb14d8d45ffb186f5cafe2064856d16308/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1444)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but I need both storage_txn and state_reader for the following code.
</blockquote></details>

You right.
___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1446 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-acGVCE9ElqEDRTeL2:-O-acGVCE9ElqEDRTeL3:bawa0tc) ([raw file](https://github.com/starkware-libs/papyrus/blob/34ff089b327cb789532cac7fb0cabdb7a7cfdb5c/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1446)):*
> ```XML
>         let state_reader = storage_txn.get_state_reader().map_err(internal_server_error)?;
>         let block_number = get_accepted_block_number(&storage_txn, block_id)?;
>         // Check if this class exists in the Cairo1 classes table.
> ```

Consider adding a new line here



_Code quote:_
```XML
        let block_number = get_accepted_block_number(&storage_txn, block_id)?;
        // Check if this class exists in the Cairo1 classes table.
```
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3569 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-acmqEE_d7TuqDIOHH:-O-acmqEE_d7TuqDIOHI:bhfvnq0) ([raw file](https://github.com/starkware-libs/papyrus/blob/34ff089b327cb789532cac7fb0cabdb7a7cfdb5c/crates/papyrus_rpc/src/v0_7/api/test.rs#L3569)):*
> ```XML
> 
> #[tokio::test]
> // TODO (Yael 16/06/2024): Add a test case for block_number which is not the latest.
> ```

move it before the `#[tokio::test]`



_Code quote:_
```XML
// TODO (Yael 16/06/2024): Add a test case for block_number which is not the latest.
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/api/api_impl.rs` line 1446 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-acGVCE9ElqEDRTeL2:-O-e-pqqACG8kcM2U__c:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/34ff089b327cb789532cac7fb0cabdb7a7cfdb5c/crates/papyrus_rpc/src/v0_7/api/api_impl.rs#L1446)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider adding a new line here
</blockquote></details>

done
___
*[`crates/papyrus_rpc/src/v0_7/api/test.rs` line 3569 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2093#-O-acmqEE_d7TuqDIOHH:-O-e-q_l9wXjdifgKi6J:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/34ff089b327cb789532cac7fb0cabdb7a7cfdb5c/crates/papyrus_rpc/src/v0_7/api/test.rs#L3569)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

move it before the `#[tokio::test]`
</blockquote></details>

done

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2093)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
