### PR TITLE
chore: add readme for the monitoring gateway

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: all files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware and @nagmo-starkware)

___
*[`README.md` line 130 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNYkSK73QCGJ0Doba3:-NcNYkSK73QCGJ0Doba4:bwkd2gn) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L130)):*
> ```Markdown
> 
> 
> ## sending API requests to the node
> ```

Let's be consistent about capitalization.
I personally prefer capitalizing all words in titles. 
We can also capitalize just the first word. 
Just make it consistent.
In any case, always capitalize Papyrus, because it's a name.



_Code quote:_
```Markdown
## sending API requests to the node
```
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNYMEX8QXptwhE5Kyy:-NcNYMEX8QXptwhE5Kyz:b3lrcqo) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
> ```Markdown
> ## Papyrus Monitoring API
> Papyrus returns information about the running node in the `monitoring` path.<br />
> Example query: `https://<papyrus_url>/monitoring/alive`
> ```

URL: `https://<papyrus_url>/monitoring/alive`



_Code quote:_
```Markdown
Example query: `https://<papyrus_url>/monitoring/alive`
```
___
*[`README.md` line 184 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNY6m5EBqNzxFCZBBZ:-NcNY6m5EBqNzxFCZBB_:b8wouxo) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L184)):*
> ```Markdown
> ### Endpoints
> 
> `alive`<br />Returns status code 200 if the node is alive.<br />
> ```

To be more accurate, it returns "200 OK".



_Code quote:_
```Markdown
200
```
___
*[`README.md` line 188 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNXbRl-Z375PdmKYjd:-NcNXbRl-Z375PdmKYje:bp5c9hq) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L188)):*
> ```Markdown
> `nodeConfig`<br /> Returns the configuration which the node runs with.<br />
> `dbTablesStats`<br /> Returns statistics of the node database. <br />
> `metrics`<br /> Returns metrics about the node.<br />
> ```

Returns metrics of the node activity. See details below.



_Code quote:_
```Markdown
 Returns metrics about the node.
```
___
*[`README.md` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNWwls1lckz-UvvOa1:-NcNWwls1lckz-UvvOa2:b-rc77vw) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L191)):*
> ```Markdown
> 
> ### Metrics
> Metrics about the node are available in the metric path. By default, the node will not collect metrics, and the metric path will return an error code 405 - Method Not Allowed. To collect metrics, change the configuration value `collect_metrics`.
> ```

set the configuration value `collect_metrics` to true.



_Code quote:_
```Markdown
change the configuration value `collect_metrics`.
```
___
*[`README.md` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNX7wq3RayUpcRdU53:-NcNX7wq3RayUpcRdU54:b-cazl4h) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L192)):*
> ```Markdown
> ### Metrics
> Metrics about the node are available in the metric path. By default, the node will not collect metrics, and the metric path will return an error code 405 - Method Not Allowed. To collect metrics, change the configuration value `collect_metrics`.
> Papyrus collects three kinds of metrics: gateway metrics, sync metrics, and proccesse metrics.
> ```

You mention here 3 types of metrics, but then you only give more details for Gateway Metrics. 
I suggest that you also add short sections for the other 2 types.



_Code quote:_
```Markdown
gateway metrics, sync metrics, and proccesse metrics
```

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: all files reviewed, 16 unresolved discussions (waiting on @DvirYo-starkware and @OmriEshhar1)

___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQt1AR49M97s-Pve5d:-NcQt1AR49M97s-Pve5e:bp9aex1) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L31)):*
> ```Markdown
>   - [Configuration](#configuration)
> - [Running `papyrus` with Docker](#running-papyrus-with-docker)
> - [Endpoints](#endpoints)
> ```

please add monitoring to the table of contents
___
*[`README.md` line 179 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQtQaM8St1anFHzTwq:-NcQtQaM8St1anFHzTwr:bohm5rv) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L179)):*
> ```Markdown
> 
> ## Papyrus Monitoring API
> Papyrus returns information about the running node in the `monitoring` path.<br />
> ```

consider rephrasing to something like:
Endpoint for retrieving monitoring information for the running node is available at...
___
*[`README.md` line 179 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuCd73ZjuFgbzmiNX:-NcQuCd73ZjuFgbzmiNY:b-3y7wtb) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L179)):*
> ```Markdown
> 
> ## Papyrus Monitoring API
> Papyrus returns information about the running node in the `monitoring` path.<br />
> ```

use double white space for a line break everywhere



_Suggestion:_
```Markdown
.  
```
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQu2fB6wgUL-dGuuK6:-NcQu2fB6wgUL-dGuuK7:bnb2onf) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
> ```Markdown
> ## Papyrus Monitoring API
> Papyrus returns information about the running node in the `monitoring` path.<br />
> Example query: `https://<papyrus_url>/monitoring/alive`
> ```

other examples in this readme uses localhost to indicate papyrus address. either change them all or change this to match.
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQvJdp4aprTbJEN_5D:-NcQvJdp4aprTbJEN_5E:b583skj) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
> ```Markdown
> ## Papyrus Monitoring API
> Papyrus returns information about the running node in the `monitoring` path.<br />
> Example query: `https://<papyrus_url>/monitoring/alive`
> ```

put a complete query not just the url. you didn't mention anywhere how to actually call the api.
put a complete curl command so the user can see it's an HTTP GET RESTfull request
___
*[`README.md` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuS-8AMWijDhGXDlT:-NcQuS-8AMWijDhGXDlU:bs6akok) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L182)):*
> ```Markdown
> Example query: `https://<papyrus_url>/monitoring/alive`
> 
> ### Endpoints
> ```

please use a table for endpoints like we did for the API endpoints
___
*[`README.md` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuz1O3Vr8fUeYbGJB:-NcQuz1O3Vr8fUeYbGJC:b-1do2zc) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L182)):*
> ```Markdown
> Example query: `https://<papyrus_url>/monitoring/alive`
> 
> ### Endpoints
> ```

state the action instead of "Return the..." e.g "get node version" instead of "Returns the version of the node"
___
*[`README.md` line 184 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNY6m5EBqNzxFCZBBZ:-NcQr_i28eNVUfPpJ9vM:bww9htw) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L184)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

To be more accurate, it returns "200 OK".
</blockquote></details>

I actually think the way it is now is better. the OK part is the meaning of the 200 status code in the [http spec](https://www.rfc-editor.org/rfc/rfc9110#status.200)

BTW if you read the spec (linked above) you'll see that maybe a better response is 204
___
*[`README.md` line 184 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuh8o0i_xYhOdk7O8:-NcQuh8o0i_xYhOdk7O9:b-eulcc) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L184)):*
> ```Markdown
> ### Endpoints
> 
> `alive`<br />Returns status code 200 if the node is alive.<br />
> ```

use the standard name for this



_Suggestion:_
```Markdown
Liveliness endpoint
```
___
*[`README.md` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQvlrcCNCQhV_BJqMj:-NcQvlrcCNCQhV_BJqMk:b-ys93p1) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L186)):*
> ```Markdown
> `alive`<br />Returns status code 200 if the node is alive.<br />
> `nodeVersion`<br /> Returns the version of the node.<br />
> `nodeConfig`<br /> Returns the configuration which the node runs with.<br />
> ```

can be ambiguous. maybe say "get the current node configuration"



_Code quote:_
```Markdown
Returns the configuration which the node runs with
```
___
*[`README.md` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQwWA2DhsiDPcbVORX:-NcQwWA2DhsiDPcbVORY:bqjoj76) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L187)):*
> ```Markdown
> `nodeVersion`<br /> Returns the version of the node.<br />
> `nodeConfig`<br /> Returns the configuration which the node runs with.<br />
> `dbTablesStats`<br /> Returns statistics of the node database. <br />
> ```

please add a section about this like you did for the metrics. can be short but I have no idea what to expect in this endpoint at the moment

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @nagmo-starkware and @OmriEshhar1)

___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQt1AR49M97s-Pve5d:-NcRAR4F9wcVzhFCXgIh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L31)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please add monitoring to the table of contents
</blockquote></details>

Done.
___
*[`README.md` line 130 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNYkSK73QCGJ0Doba3:-NcRAjL8CZTF4P6SF67Y:bjc55kz) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L130)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Let's be consistent about capitalization.
I personally prefer capitalizing all words in titles. 
We can also capitalize just the first word. 
Just make it consistent.
In any case, always capitalize Papyrus, because it's a name.
</blockquote></details>

I changed the headers I wrote to only start with capital letters, like most of the current headers. The changes to other headers (and papyrus to Papyrus) I will do in a different pull request.
___
*[`README.md` line 179 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuCd73ZjuFgbzmiNX:-NcRCBbs-K7mxpWf0MIf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L179)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

use double white space for a line break everywhere
</blockquote></details>

Done.
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNYMEX8QXptwhE5Kyy:-NcREiJB6Q-ieuwEoe6j:b-lkwki7) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

URL: `https://<papyrus_url>/monitoring/alive`
</blockquote></details>

I have changed this part following Nevo's comment.
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQu2fB6wgUL-dGuuK6:-NcRFbVT711TflBoBTRW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

other examples in this readme uses localhost to indicate papyrus address. either change them all or change this to match.
</blockquote></details>

Done.
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQvJdp4aprTbJEN_5D:-NcRFqN_97KhAqPm5MXI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

put a complete query not just the url. you didn't mention anywhere how to actually call the api.
put a complete curl command so the user can see it's an HTTP GET RESTfull request
</blockquote></details>

Done.
___
*[`README.md` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuS-8AMWijDhGXDlT:-NcRG4q3Aq5IXoQoDaNU:buqxxvb) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L182)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please use a table for endpoints like we did for the API endpoints
</blockquote></details>

I don`t think this is a good idea. First, we don’t have versions of this gateway, and because the methods are not defined in the spec but only by us, we need to add a short explanation for each endpoint. Overall doing it in a table will not make the readme more consistent or readable.
___
*[`README.md` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuz1O3Vr8fUeYbGJB:-NcRHy-J4XYEpE81qhdk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L182)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

state the action instead of "Return the..." e.g "get node version" instead of "Returns the version of the node"
</blockquote></details>

Done.
___
*[`README.md` line 184 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNY6m5EBqNzxFCZBBZ:-NcRIBog37HJRwHaqRQC:baqsltl) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L184)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I actually think the way it is now is better. the OK part is the meaning of the 200 status code in the [http spec](https://www.rfc-editor.org/rfc/rfc9110#status.200)

BTW if you read the spec (linked above) you'll see that maybe a better response is 204
</blockquote></details>

The 200 status code is what Eran requested for this endpoint...
___
*[`README.md` line 184 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuh8o0i_xYhOdk7O8:-NcRIWvW9wmKS03Yjrn-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L184)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

use the standard name for this
</blockquote></details>

Done.
___
*[`README.md` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQvlrcCNCQhV_BJqMj:-NcRJEMS8FoRyW6w-MNi:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L186)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

can be ambiguous. maybe say "get the current node configuration"
</blockquote></details>

Done.
___
*[`README.md` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQwWA2DhsiDPcbVORX:-NcRO7aa5byQTkbPpsUk:bij4jst) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L187)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please add a section about this like you did for the metrics. can be short but I have no idea what to expect in this endpoint at the moment
</blockquote></details>

I added a link to more details.
___
*[`README.md` line 188 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNXbRl-Z375PdmKYjd:-NcRLDqPA7tovoZNuuvM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L188)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Returns metrics of the node activity. See details below.
</blockquote></details>

Done.
___
*[`README.md` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNWwls1lckz-UvvOa1:-NcRLGyWBn5GZ1HUAZmV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L191)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

set the configuration value `collect_metrics` to true.
</blockquote></details>

Done.
___
*[`README.md` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcNX7wq3RayUpcRdU53:-NcRLRqw2n2E16FCQKLW:bxklzvv) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L192)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

You mention here 3 types of metrics, but then you only give more details for Gateway Metrics. 
I suggest that you also add short sections for the other 2 types.
</blockquote></details>

I don`t have what to write about them. The names of those metrics explain themselves.

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: all files reviewed, 9 unresolved discussions (waiting on @nagmo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware and @OmriEshhar1)

___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQt1AR49M97s-Pve5d:-NcRwtwEEloiXHSyMHcb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L31)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

change to all lower case. the link is not working otherwise
</blockquote></details>

Done.
___
*[`README.md` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQvJdp4aprTbJEN_5D:-NcRx3J_49uaHTWgomeK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L180)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please be event more explicit. i.e `curl -X GET  https://localhost:8081/monitoring/alive`
</blockquote></details>

Done.
___
*[`README.md` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcQuS-8AMWijDhGXDlT:-NcRxJIv6M4mJjrlZCE_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/34f7ff2d0efee35b269b50fe40ac23011a9f36d5/README.md#L182)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

then maybe add a dot at the beginning of each endpoint (with a * ) like you did in the gateway metrics section
</blockquote></details>

Done.
___
*[`README.md` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcRVbZK5EhcOrziEedr:-NcRzfw2BqEFmI4LGRp-:btmx9d8) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad78cdb98d08da880aaa27d30f897c262e0cf16a/README.md#L208)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't understand this last sentence.
</blockquote></details>

I added an example of an illegal method.
___
*[`README.md` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcRVq6k85-yQ0932fto:-NcS0J2GDaoA-VA5NXYC:bsdld3g) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad78cdb98d08da880aaa27d30f897c262e0cf16a/README.md#L208)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please consider the following
</blockquote></details>

The label terminology should be known for how to use metrics in general. I think, in this case, we don`t need to use "simpler" language.

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`README.md` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1088#-NcRVq6k85-yQ0932fto:-NcS73oqDghJdK6Dx-BY:b-3rkfrx) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad78cdb98d08da880aaa27d30f897c262e0cf16a/README.md#L208)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

The label terminology should be known for how to use metrics in general. I think, in this case, we don`t need to use "simpler" language.
</blockquote></details>

I'm not sure what do you mean by that.. the label semantic is not a general agreed upon thing and a random reader of the docs would not know what you mean.
I'm leaving it up to you to decide if you want to leave it like that or not but I think the explanation is not very easy to understand.

**Pull request merged**
