### PR TITLE
feat(common): calculate invoke transaction hash

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1117)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1117)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UttJ5mTE5zMDqQOj:-Nd-UttJ5mTE5zMDqQOk:b-ffy5e2) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L59)):*
> ```XML
>     expected_hash: StarkHash,
> ) -> Result<bool, StarknetApiError> {
>     if get_transaction_hash(transaction, chain_id)? == expected_hash {
> ```

Consider moving this inside the vector and changing the name of the vector from deprecated_hashes to possible_hashes
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UDJj4EE1R5dSZ-PF:-Nd-UDJkA0pbPVVwSjaX:b7p1qi3) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L140)):*
> ```XML
>         .chain(&transaction.version.0)
>         .chain(contract_address.0.key())
>         .chain(&ZERO)
> ```

Comment what is this zero (I know it's not related to this PR)
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UctQ8hHpW0FJHZGy:-Nd-UctR1hXro_Tdxu9a:b-c609bh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L185)):*
> ```XML
>         )
>         .chain_if(&StarkFelt::from(0_u8), !is_deprecated)
>         .chain(&ascii_as_felt(chain_id.0.as_str())?)
> ```

How did the tests pass in the previous PR?
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-Umuo2mKVloCoYTvh:-Nd-Umuo2mKVloCoYTvi:b-q3rv7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L227)):*
> ```XML
>         .chain(&ONE) // Version
>         .chain(transaction.sender_address.0.key())
>         .chain(&ZERO)
> ```

Comment what is this zero

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1117)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UttJ5mTE5zMDqQOj:-Nd-YBT4Cj4AQisWAWPa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider moving this inside the vector and changing the name of the vector from deprecated_hashes to possible_hashes
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UDJj4EE1R5dSZ-PF:-Nd-YM9j5Lt02LDlk3tC:biul2sf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L140)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Comment what is this zero (I know it's not related to this PR)
</blockquote></details>

I'm following the [docs](https://starknet-io.github.io/starknet-docs/pr-775/documentation/architecture_and_concepts/Network_Architecture/Blocks/transactions/#deploy_account_hash_calculation).
That zero there has no meaning.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UctQ8hHpW0FJHZGy:-Nd-XStaCmCnxOryBwEh:b8b25vt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L185)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

How did the tests pass in the previous PR?
</blockquote></details>

Why not?
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-Umuo2mKVloCoYTvh:-Nd-Z2Xc7NxwcsOrF9zz:b8zt5wq) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L227)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Comment what is this zero
</blockquote></details>

There is no explanation in the [documentation](https://starknet-io.github.io/starknet-docs/pr-775/documentation/architecture_and_concepts/Network_Architecture/Blocks/transactions/#v1_hash_calculation).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-:-Nd-_mmr8XIyDyCeer8B:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UDJj4EE1R5dSZ-PF:-Nd-_D1qCXLZx6v75ovu:b-1uomnb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L140)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm following the [docs](https://starknet-io.github.io/starknet-docs/pr-775/documentation/architecture_and_concepts/Network_Architecture/Blocks/transactions/#deploy_account_hash_calculation).
That zero there has no meaning.
</blockquote></details>

Does it have a future meaning? A placeholder for something we currently don't implement?
Ask product
When they respond to you, comment this in a future PR
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UctQ8hHpW0FJHZGy:-Nd-_Pwh8Deexapk2uZl:b-e47qlt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L185)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

The chain_id wasn't included in the hash
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-Umuo2mKVloCoYTvh:-Nd-_ZwA0LKmOY2idINU:b-aqo4k2) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L227)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

There is no explanation in the [documentation](https://starknet-io.github.io/starknet-docs/pr-775/documentation/architecture_and_concepts/Network_Architecture/Blocks/transactions/#v1_hash_calculation).
</blockquote></details>

Please report this to product that this isn't documented and if they explain to you the meaning of this comment it in a future PR

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1117)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1117#-Nd-UctQ8hHpW0FJHZGy:-Nd00oCv9mnAE3fy7rfy:bpzhugl) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ae394a3531be2e2d7279b08295df19c608586b8/crates/papyrus_common/src/transaction_hash.rs#L185)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The chain_id wasn't included in the hash
</blockquote></details>

It was.

**Pull request merged**
