### PR TITLE
refactor(consensus): state machine returns VecDeque instead of Vec

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2167)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2167?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2168** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2168?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2167** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2167?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2166** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2166?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2161** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2159** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2167#-:-O0o4qSlBwOiikg9_qSo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2167#-:-O0qmQfD25CLI6as6-ay:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2167#-:-O0shf839wj42s3jZsa2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
