### PR TITLE
perf(storage)!: merge tabels with tx index key

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_6/execution_test.rs` line 765 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyPsfle9aEi4_JLvNdl:-NyPsfle9aEi4_JLvNdm:b1dtk0c) ([raw file](https://github.com/starkware-libs/papyrus/blob/2e858b12b6f118666dfc45f5b402097fa26341fa/crates/papyrus_rpc/src/v0_6/execution_test.rs#L765)):*
> ```XML
>             BlockBody {
>                 transactions: vec![tx1, tx2],
>                 transaction_outputs: vec![
> ```

without adding one more tx output, this test will now fail because the block has 2 tx but only one tx output.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_6/execution_test.rs` line 765 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyPsfle9aEi4_JLvNdl:-NyTmzHq2ntOgYsdjkbL:b-jlg4im) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_rpc/src/v0_6/execution_test.rs#L765)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

without adding one more tx output, this test will now fail because the block has 2 tx but only one tx output.
</blockquote></details>

It might be good to add a test that this fails
___
*[`crates/papyrus_storage/src/body/events.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyTnxDH6hpZM0saGBa0:-NyTnxDH6hpZM0saGBa1:bm0jmjt) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_storage/src/body/events.rs#L118)):*
> ```XML
> // TODO(dvir): add transaction hash to the return value. In the RPC when returning events this is
> // with the transaction hash. We can do it efficiently here because we anyway read the relevant
> // entry in the transaction_metadata table..
> ```

This also good for validations, since the event hash calculation depends on the transaction hash
___
*[`crates/papyrus_storage/src/body/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyTpU6oD4ZMjnGF5e2b:-NyTpU6oD4ZMjnGF5e2c:brmxxh2) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_storage/src/body/mod.rs#L278)):*
> ```XML
>         transaction_metadata_table: TransactionMetadataTable<'env>,
>     ) -> StorageResult<Option<Vec<TransactionOutput>>> {
>         if self.get_body_marker()? <= block_number {
> ```

There's code duplication with the functions below. Consider adding a utility function that receives a function that converts metadata to what you need
I did something similar in the RPC. You can TAL if you want
___
*[`crates/papyrus_storage/src/body/mod.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyTol5P4jw16Av_2y4B:-NyTol5P4jw16Av_2y4C:bykozwo) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_storage/src/body/mod.rs#L301)):*
> ```XML
>     }
> 
>     fn get_transactions_in_block(
> ```

For next time, if you move code around and make changes to it, split it into two commits to make it easier for the reviewer

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_6/execution_test.rs` line 765 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyPsfle9aEi4_JLvNdl:-Nyy85AY0D_9KWemWLLj:bkghple) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_rpc/src/v0_6/execution_test.rs#L765)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It might be good to add a test that this fails
</blockquote></details>

I added todo for that.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2022#-NyTpU6oD4ZMjnGF5e2b:-Nyy9Ito2teL1TvCnDSC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/03ea944429721144c07dd530797cf365e77ab1c7/crates/papyrus_storage/src/body/mod.rs#L278)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

There's code duplication with the functions below. Consider adding a utility function that receives a function that converts metadata to what you need
I did something similar in the RPC. You can TAL if you want
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2022)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
