### PR TITLE
feat(starknet_client): support v3 transactions in starknet_client

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/starknet_client/resources/reader/declare_v3.json` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYCusEI-RmVZBhEfH:-NijYCusEI-RmVZBhEfI:b-8u2lt1) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/reader/declare_v3.json#L26)):*
> ```JSON
>         "max_fee": "0x0",
>         "type": "DECLARE"
>     }
> ```

Add newline and indent this entire file with one less indent
___
*[`crates/starknet_client/resources/reader/deploy_account_v3.json` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYKik3YNoCbqCGCsV:-NijYKik3YNoCbqCGCsW:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/reader/deploy_account_v3.json#L36)):*
> ```JSON
>     "version": "0x3",
>     "type": "DEPLOY_ACCOUNT"
> }
> ```

Same here
___
*[`crates/starknet_client/resources/reader/invoke_v3.json` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYMviCwMe_4ydBMez:-NijYMviCwMe_4ydBMf-:bk64xxs) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/reader/invoke_v3.json#L35)):*
> ```JSON
>     "version": "0x3",
>     "type": "INVOKE_FUNCTION"
> }
> ```

Add newline
___
*[`crates/starknet_client/resources/writer/deploy_account_v3.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYPtFDhcOM9ueM_E-:-NijYPtFDhcOM9ueM_E0:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/writer/deploy_account_v3.json#L37)):*
> ```JSON
>     "fee_data_availability_mode": 0,
>     "paymaster_data": []
> }
> ```

Same here
___
*[`crates/starknet_client/resources/writer/invoke_v3.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYRiP9RN31mcUeuyD:-NijYRiP9RN31mcUeuyE:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/writer/invoke_v3.json#L37)):*
> ```JSON
>     "paymaster_data": [],
>     "account_deployment_data": []
> }
> ```

Same here
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Nij_RUO2o17Ubqlox1K:-Nij_RUO2o17Ubqlox1L:b-p8gtve) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/reader/objects/transaction.rs#L330)):*
> ```XML
>     pub fee_data_availability_mode: Option<ReservedDataAvailabilityMode>,
>     pub paymaster_data: Option<PaymasterData>,
>     #[serde(alias = "sender_address")]
> ```

Comment why is this so
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijaujZ4FGrTLTMNoPR:-NijaujZ4FGrTLTMNoPS:bheibiu) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/writer/objects/transaction.rs#L108)):*
> ```XML
>     pub nonce: Nonce,
>     pub signature: TransactionSignature,
>     pub nonce_data_availability_mode: ReservedDataAvailabilityMode,
> ```

This means that the writer client will fail until starknet is upgraded. @dan-starkware what should we do here? Should we have some form of versioning for the writer client? maybe we can query starknet on what is the starknet version and according to that decide if to fill the field

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: all files reviewed, 8 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijdEuY-Yl2ArNuw8aK:-NijdEuY-Yl2ArNuw8aL:b-e5z1yq) ([raw file](https://github.com/starkware-libs/papyrus/blob/21cf42a81588d3413495c550591fa193c888e67b/crates/starknet_client/src/reader/objects/transaction.rs#L173)):*
> ```XML
>     pub compiled_class_hash: Option<CompiledClassHash>,
>     pub sender_address: ContractAddress,
>     pub nonce_data_availability_mode: Option<ReservedDataAvailabilityMode>,
> ```

Change to `ReservedDataAvailabilityMode`, and add `#[serde(default)]`
Same for the rest

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: 14 of 30 files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1 and @ShahakShama)

___
*[`crates/starknet_client/resources/reader/declare_v3.json` line 26 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Niob-pC2PBMCiwRcXBV:-Niob-pC2PBMCiwRcXBW:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/21cf42a81588d3413495c550591fa193c888e67b/crates/starknet_client/resources/reader/declare_v3.json#L26)):*
> ```JSON
>         "max_fee": "0x0",
>         "type": "DECLARE"
>     }
> ```

done
___
*[`crates/starknet_client/resources/reader/deploy_account_v3.json` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYKik3YNoCbqCGCsV:-Niob2pO0bcRjB1CpkBa:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/reader/deploy_account_v3.json#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done
___
*[`crates/starknet_client/resources/reader/invoke_v3.json` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYMviCwMe_4ydBMez:-Niob3YR6dTFn4iuSMMk:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/reader/invoke_v3.json#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add newline
</blockquote></details>

done
___
*[`crates/starknet_client/resources/writer/deploy_account_v3.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYPtFDhcOM9ueM_E-:-Niob67i7cGt5mDjGX_1:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/writer/deploy_account_v3.json#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done
___
*[`crates/starknet_client/resources/writer/invoke_v3.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijYRiP9RN31mcUeuyD:-Niob7Mi4-r0jxgMrzyo:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/resources/writer/invoke_v3.json#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Nij_RUO2o17Ubqlox1K:-NiobDRi96k4HEx7gxSj:b-zgpuwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/reader/objects/transaction.rs#L330)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Comment why is this so
</blockquote></details>

I'm still checking with Elin is the name has changed actually or they gave me a wrong example json. lets push this and I'll handle in the next commit.
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-NijdEuY-Yl2ArNuw8aK:-Niob8ar1IJOtSXs51V9:b3vidh4) ([raw file](https://github.com/starkware-libs/papyrus/blob/21cf42a81588d3413495c550591fa193c888e67b/crates/starknet_client/src/reader/objects/transaction.rs#L173)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change to `ReservedDataAvailabilityMode`, and add `#[serde(default)]`
Same for the rest
</blockquote></details>

will add skip if none in a separate commit

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: 13 of 30 files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1 and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Nij_RUO2o17Ubqlox1K:-NioiXrI7YzG_bqpXTg5:b-5cqjg3) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/reader/objects/transaction.rs#L330)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

I'm still checking with Elin is the name has changed actually or they gave me a wrong example json. lets push this and I'll handle in the next commit.
</blockquote></details>

ok I checked and indeed they changed the name, added a comment.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Nij_RUO2o17Ubqlox1K:-NioketA557mtvZCFDdA:b-nihtru) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/reader/objects/transaction.rs#L330)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

ok I checked and indeed they changed the name, added a comment.
</blockquote></details>

In that case, change it so that the sender_address is the name of the field and the alias is contract_address (Add a TODO to change it if this causes a big change)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1 and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-Nij_RUO2o17Ubqlox1K:-Niomez7AbvI0_NeZTL9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a40d98999e1e46a3d328dfe2d391810d7cbb0fb/crates/starknet_client/src/reader/objects/transaction.rs#L330)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In that case, change it so that the sender_address is the name of the field and the alias is contract_address (Add a TODO to change it if this causes a big change)
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1380#-:-NiooXbR0ec4-dFcot8c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
