### PR TITLE
revert(network): remove close_outbound_session

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(network): drop outbound session
- revert(network): remove close_outbound_session

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1647)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1647)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1647#-NpOMxIY5oRtRIpVBWs_:-NpOMxIY5oRtRIpVBWsa:b-otqsao) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac800e92dfd91bcb3223c3d2e622d3883b0b0f90/crates/papyrus_network/src/block_headers/behaviour.rs#L143)):*
> ```XML
> 
>     // This function will panic if the outbound session doesn't exist.
>     fn handle_outbound_session_failed(&mut self, outbound_session_id: OutboundSessionId);
> ```

maybe make it return a session failed event with the session error as a parameter so you can clean up the following calls to this function

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1647)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1647#-NpOMxIY5oRtRIpVBWs_:-NpOU3rm7TZC6e0LIThd:btpn23u) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac800e92dfd91bcb3223c3d2e622d3883b0b0f90/crates/papyrus_network/src/block_headers/behaviour.rs#L143)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

maybe make it return a session failed event with the session error as a parameter so you can clean up the following calls to this function
</blockquote></details>

I prefer to leave the functions that I mock in the tests as simple as possible

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1647#-:-NpOZsdM99LuT6owGzMm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1647#-NpOMxIY5oRtRIpVBWs_:-NpOZrZv8VTVoNYFZiFE:b32wtd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac800e92dfd91bcb3223c3d2e622d3883b0b0f90/crates/papyrus_network/src/block_headers/behaviour.rs#L143)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I prefer to leave the functions that I mock in the tests as simple as possible
</blockquote></details>

ok

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1647)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1647#-NpOMxIY5oRtRIpVBWs_:-NpOyCfn6EYuhZMEOP6w:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac800e92dfd91bcb3223c3d2e622d3883b0b0f90/crates/papyrus_network/src/block_headers/behaviour.rs#L143)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

**Pull request merged**
