### PR TITLE
Storage casm

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/659)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/659)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @dan-starkware and @giladchase)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUppI6mEYjSUbCNMWo-:-NUppI6mEYjSUbCNMWo0:banqhq1) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/lib.rs#L2)):*
> ```XML
> pub mod body;
> pub mod casm;
> ```

Consider changing the mod name to something less specific, maybe `compiled_classes`

**Comment by dan-starkware** [comment]
*[`Cargo.toml` line 71 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpp2RWANM-QO0w3Fxl:-NUpp2RXAUsJO-w7w0qd:b-fqsjnr) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/Cargo.toml#L71)):*
> ```TOML
> url = { version = "2.2.2" }
> web3 = { version = "0.18.0" }
> ```

Is this intentional?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/casm.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUppYCQApOm0fY4BOdQ:-NUppYCQApOm0fY4BOdR:b-ib6695) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/casm.rs#L12)):*
> ```XML
> 
> pub trait CasmStorageReader {
>     fn get_casm(&self, class_hash: ClassHash) -> StorageResult<Option<CasmContractClass>>;
> ```

As long as we don't have specific types I think we should document what is the expected hash here.
In general, we should probably better document APIs.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/casm.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpqWeU-g2poPwU_NTQ:-NUpqWeU-g2poPwU_NTR:b-jryslp) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/casm.rs#L33)):*
> ```XML
>     fn append_casm(self, class_hash: ClassHash, casm: &CasmContractClass) -> StorageResult<Self> {
>         let casm_table = self.txn.open_table(&self.tables.casms)?;
>         casm_table.insert(&self.txn, &class_hash, casm)?;
> ```

Do we want specific error in case it already exists?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/casm_test.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpqoDSAkqr03yNLbqp:-NUpqoDSAkqr03yNLbqq:bxduxga) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/casm_test.rs#L72)):*
> ```XML
>     "compiler_version": "1.0.0"
> }"#;
>     let expected_casm = serde_json::from_str::<CasmContractClass>(casm_json).unwrap();
> ```

Why not actually read it from a json file?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/casm_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpr8lb3J-txmPOx9Od:-NUpr8lb3J-txmPOx9Oe:bysb93y) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/casm_test.rs#L75)):*
> ```XML
>     let (reader, mut writer) = get_test_storage();
> 
>     writer
> ```

Do we want a test case for re-writing a class?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/serializers.rs` line 741 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpu4ywCpH1FBMDusRE:-NUpu4ywCpH1FBMDusRF:bykkokc) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/serializers.rs#L741)):*
> ```XML
> impl StorageSerde for Hint {
>     fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>         serde_json::to_value(self)?.serialize_into(res)?;
> ```

Why using `serde_json::Value`

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/659)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @giladchase and @yair-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/serializers.rs` line 741 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NUpu4ywCpH1FBMDusRE:-NV9WAoC2HaI-HFdyNEk:b7q3pyt) ([raw file](https://github.com/starkware-libs/papyrus/blob/da70d83f544f5311892139e5d01ea39e2e6847ce/crates/papyrus_storage/src/serializers.rs#L741)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why using `serde_json::Value`
</blockquote></details>

Are there any private fields involve?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/659)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NVi1F224_Ig04gtrXeQ:-NVi1F224_Ig04gtrXeR:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/d8a45d7826b330786a2370c624bcf6bc8152d62d/crates/papyrus_storage/src/compiled_class_test.rs#L46)):*
> ```XML
>         // A workaround because StorageTxn doesn't implement Debug.
>         .map(|_| ())
>         .unwrap_err();
> ```

Consider



_Suggestion:_
```XML
    let Err(err) = writer
        .begin_rw_txn()
        .unwrap()
        .append_casm(ClassHash::default(), &CasmContractClass::default())  else {
            panic!("Unexpected Ok.");
        };
```

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/659#-NVi1F224_Ig04gtrXeQ:-NVi6sKLBE9uOwvBbQIB:b-iry7x8) ([raw file](https://github.com/starkware-libs/papyrus/blob/d8a45d7826b330786a2370c624bcf6bc8152d62d/crates/papyrus_storage/src/compiled_class_test.rs#L46)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider
</blockquote></details>

Done, thanks

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/659#-:-NViF8BjC5i4z2e3Hn03:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Pull request merged**
