### PR TITLE
feat(JSON-RPC): support version without patch

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #892** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/892" target="_blank">Graphite</a> 
    * **PR #929** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/929" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/929?utm_source=stack-comment).

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab-sgYAuH-Iv8fXV3-:-Nab-sgYAuH-Iv8fXV30:b-saqcb7) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L122)):*
> ```XML
> 
> #[tokio::test]
> async fn test_version_middleware() {
> ```

What should happen with a version with a lower patch than we have?
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-NaaxusG3Y_RqfSafi-z:-NaaxusHB3KHCE5QY1wH:btrlcwh) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L125)):*
> ```XML
>     let base_uri = "http://localhost:8080/rpc/";
>     let mut path_options = vec![];
>     VERSION_CONFIG.iter().for_each(|(version_id, _)| {
> ```

Consider adding a version name with patch and lowercase v.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab6KwO6tZdD1hWv67L:-Nab6KwO6tZdD1hWv67M:b-t8akyi) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L165)):*
> ```XML
>     };
>     let mut rng = get_rng();
>     let version_id = VERSION_CONFIG.choose(&mut rng).unwrap().0;
> ```

Instead of first declaring the variable rng you can do:
let version_id = VERSION_CONFIG.choose(&mut get_rng()).unwrap().0;
___
*[`crates/papyrus_gateway/src/middleware.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab3-3A6LfOGoVPd9-3:-Nab3-3A6LfOGoVPd9-4:b-2gjwwb) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/middleware.rs#L101)):*
> ```XML
>         return Err(BoxError::from(msg));
>     };
>     let version_comps = temp_version.split('_').collect::<Vec<_>>();
> ```

Consider doing the same thing by finding the first and last indexes of '_'; if those equal no patch, else there is a patch. Then the version variable will be the String slice from the beginning to the first '_' index.
Not very important...

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab-sgYAuH-Iv8fXV3-:-Nae_RMWEX6zHYEgJnyY:bt2q64a) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L122)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

What should happen with a version with a lower patch than we have?
</blockquote></details>

the requirement we got from product says he'll get the latest version we have. we promise to provide you with the same minor version and a patch that is gte then what you asked for.
I guess I can add a test for that but I'm not sure if it's overkill. what do you think?
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-NaaxusG3Y_RqfSafi-z:-NaeX-Zg6DqKl9zLSMi2:b-tqtu0s) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L125)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider adding a version name with patch and lowercase v.
</blockquote></details>

I think it's unnecessary since  if we see that the test supports both lowercase and capital v and also both with and without patch then we covered all the cases. can you think of a scenario it can break?
___
*[`crates/papyrus_gateway/src/middleware.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab3-3A6LfOGoVPd9-3:-NaeaFpu9J-ajgcsdf7J:b1wcuju) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/middleware.rs#L101)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider doing the same thing by finding the first and last indexes of '_'; if those equal no patch, else there is a patch. Then the version variable will be the String slice from the beginning to the first '_' index.
Not very important...
</blockquote></details>

did you mean `_`? if so then this wouldn't work since we have two underscores i.e. `v0_3_0` and the last zero is the patch.
also that means iterating twice instead of once but it's less important since it's a short string anyway

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab-sgYAuH-Iv8fXV3-:-NafDNf0BczksoqYBhpT:b-251jvf) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L122)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

the requirement we got from product says he'll get the latest version we have. we promise to provide you with the same minor version and a patch that is gte then what you asked for.
I guess I can add a test for that but I'm not sure if it's overkill. what do you think?
</blockquote></details>

I think we should add a test for that.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-NaaxusG3Y_RqfSafi-z:-NafDStZ830VuvF6Vye0:b-wqpss1) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L125)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think it's unnecessary since  if we see that the test supports both lowercase and capital v and also both with and without patch then we covered all the cases. can you think of a scenario it can break?
</blockquote></details>

It will be nice to know we cover all the cases here, and there are no actual costs for that (test runtime...).
___
*[`crates/papyrus_gateway/src/middleware.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab3-3A6LfOGoVPd9-3:-NafDykd3lywOju_kX8f:bkdmq2f) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/middleware.rs#L101)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

did you mean `_`? if so then this wouldn't work since we have two underscores i.e. `v0_3_0` and the last zero is the patch.
also that means iterating twice instead of once but it's less important since it's a short string anyway
</blockquote></details>

This is a minor optimization; you can forget it.
This is only one pass, to the first from the start and to the last from the end.
I don't understand the first point, but you can ignore this.

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-Nab-sgYAuH-Iv8fXV3-:-NafMz0l16HKzmBgTB_q:bs0tjbj) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L122)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think we should add a test for that.
</blockquote></details>

added, but currently we don't have a case that checks this. look at the code and I think you'll understand
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/929#-NaaxusG3Y_RqfSafi-z:-NafN6434-Z4w1mT0-C5:bfu5bo0) ([raw file](https://github.com/starkware-libs/papyrus/blob/82e968e94d30622894896fbdc221cb07e74dd5cb/crates/papyrus_gateway/src/gateway_test.rs#L125)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

It will be nice to know we cover all the cases here, and there are no actual costs for that (test runtime...).
</blockquote></details>

added it

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/929#-:-Nag4g6l1OKpq0cBC6w5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
