### PR TITLE
feat(execution): simulate transactions gateway endpoint

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1052)

### CODE REVIEW

**Comment by yair-starkware** [comment]
1. fix the TransactionTrace to be according to the spec
2. export test instances for testing the transaction trace against the schema
3. add the spec files (trace API)
4. add GW endpoint
5. GW tests

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/execution_test.rs` line 454 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1052#-Nbtl_Ek7zuBXrKn4MjB:-Nbtl_Ek7zuBXrKn4MjC:b-wb8azf) ([raw file](https://github.com/starkware-libs/papyrus/blob/be01ea2e85e87ed942547fb40a1b4d6a6bd2ea37/crates/papyrus_gateway/src/v0_4_0/execution_test.rs#L454)):*
> ```XML
> 
> fn prepare_storage_for_execution(mut storage_writer: StorageWriter) {
>     let class1 = serde_json::from_value::<SN_API_DeprecatedContractClass>(read_json_file(
> ```

Sorry for the mass here.
Changed things to match the storage preparation in the execution crate.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 13 of 17 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1052)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`Cargo.lock` line 4293 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1052#-Nc28ql3CXQsUP9_JwA_:-Nc28ql3CXQsUP9_JwAa:bjf6o2c) ([raw file](https://github.com/starkware-libs/papyrus/blob/c2ea0eead2a6bfabc47006984bb07e5c4dfb9109/Cargo.lock#L4293)):*
> ```TOML
>  "cairo-vm",
>  "indexmap 1.9.3",
>  "itertools 0.10.5",
> ```

Is it neede?



_Code quote:_
```TOML
 "itertools 0.10.5",
```
___
*[`crates/papyrus_gateway/src/api.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1052#-Nc2BrCg0iZOhOu_44i-:-Nc2BrCg0iZOhOu_44i0:bijr9k5) ([raw file](https://github.com/starkware-libs/papyrus/blob/be01ea2e85e87ed942547fb40a1b4d6a6bd2ea37/crates/papyrus_gateway/src/api.rs#L43)):*
> ```XML
> /// Returns a `Methods` object with all the methods from the supported APIs.
> /// Whenever adding a new API version we need to add the new version mapping here.
> #[allow(clippy::too_many_arguments)]
> ```

Please a Monday task



_Code quote:_
```XML
#[allow(clippy::too_many_arguments)]
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1052)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`Cargo.lock` line 4293 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1052#-Nc28ql3CXQsUP9_JwA_:-Nc2sxjQ7AJcv8xqNGJ8:buex7ea) ([raw file](https://github.com/starkware-libs/papyrus/blob/c2ea0eead2a6bfabc47006984bb07e5c4dfb9109/Cargo.lock#L4293)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is it neede?
</blockquote></details>

needed for sorted_by_key when ordering the events
___
*[`crates/papyrus_gateway/src/api.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1052#-Nc2BrCg0iZOhOu_44i-:-Nc2t3zL8D7pQccN_-By:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/be01ea2e85e87ed942547fb40a1b4d6a6bd2ea37/crates/papyrus_gateway/src/api.rs#L43)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please a Monday task
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1052)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Pull request merged**
