### PR TITLE
feat(network): handle try_send error from net manager to subscriber

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1737)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1737?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#1737** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1737?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1736** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1736?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1723** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1723?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1719** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1719?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1737?utm_source=stack-comment).

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1737)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/converters/mod.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1737#-NsD1u13BUEGIiXUf6S0:-NsD1u142Z6dBwwC8O59:brnans0) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca14c4d7a9ff002448e563e733d432f6fb331ba0/crates/papyrus_network/src/converters/mod.rs#L69)):*
> ```XML
> pub enum RouterError {
>     #[error("No sender for protocol {protocol:?}")]
>     NoSenderForProtocol { protocol: Protocol },
> ```

Rename to UnsupportedProtocol or UnknownProtocol
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1737#-NsDJAPUAl3kBDaWLwCO:-NsDJAPUAl3kBDaWLwCP:b-46a5qq) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca14c4d7a9ff002448e563e733d432f6fb331ba0/crates/papyrus_network/src/network_manager/mod.rs#L209)):*
> ```XML
>                         Err(RouterError::NoSenderForProtocol { protocol }) => {
>                             error!(
>                                 "No sender for protocol {protocol:?}. Dropping data. \
> ```

If you accept my rename, change the message here as well.
Something like
"The network's subscriber doesn't support the protocol {protocol:?}"
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1737#-NsDK4cJCIx6dO_D0Yhw:-NsDK4cJCIx6dO_D0Yhx:bi2sngs) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca14c4d7a9ff002448e563e733d432f6fb331ba0/crates/papyrus_network/src/network_manager/mod.rs#L218)):*
> ```XML
>                             } else if e.is_full() {
>                                 error!(
>                                     "Receiver is full. Dropping data. outbound_session_id: \
> ```

Receiver buffer

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1737)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1737#-:-NsDRKoF7jtaUBJv3SWe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
