### PR TITLE
add test for ContractClassAbiEntryType from FunctionAbiEntryType

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #771** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/771" target="_blank">Graphite</a> 
    * **PR #767** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/767" target="_blank">Graphite</a> 
      * **PR #772** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/772" target="_blank">Graphite</a>  👈
        * **PR #770** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/770" target="_blank">Graphite</a> 
          * **PR #763** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/763" target="_blank">Graphite</a> 
          * **PR #762** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/762" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/772?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/772#-NYx3A8IA6_wf4BOGEdZ:-NYx3A8IA6_wf4BOGEd_:b2dbmnm) ([raw file](https://github.com/starkware-libs/papyrus/blob/4cb828ecde8e5a3155c3b18b2c3e5a63050d58d0/crates/papyrus_gateway/src/gateway_test.rs#L105)):*
> ```XML
> #[tokio::test]
> async fn contractclassabientrytype_from_functionabientrytype() {
>     let _: ContractClassAbiEntryType =
> ```

Reduce the code duplication by creating a function with generic types that does what this test does and what the test before it did

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/772#-NYx3A8IA6_wf4BOGEdZ:-NZ4wQ2XBoFnkuym9CUg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4cb828ecde8e5a3155c3b18b2c3e5a63050d58d0/crates/papyrus_gateway/src/gateway_test.rs#L105)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Reduce the code duplication by creating a function with generic types that does what this test does and what the test before it did
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/772#-NYx3A8IA6_wf4BOGEdZ:-NZ55CKYCrXtvtli_Nwb:bq19i86) ([raw file](https://github.com/starkware-libs/papyrus/blob/4cb828ecde8e5a3155c3b18b2c3e5a63050d58d0/crates/papyrus_gateway/src/gateway_test.rs#L105)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Make sure when you merge the previous PR that there won't be a double declaration of this macro (I assume it's the same macro from #767 )

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772#-:-NZK-Rfz2xQLcsvrlW36:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/772#-NYx3A8IA6_wf4BOGEdZ:-NZKgVt7E8zLMLnDNsnO:b4kodr0) ([raw file](https://github.com/starkware-libs/papyrus/blob/4cb828ecde8e5a3155c3b18b2c3e5a63050d58d0/crates/papyrus_gateway/src/gateway_test.rs#L105)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make sure when you merge the previous PR that there won't be a double declaration of this macro (I assume it's the same macro from #767 )
</blockquote></details>

not the same macro.. I can try to merge them or layer the macros but I'm not sure there's a benefit to it.
it will definitely complicate the code..
have a closer look and let me know what you think. I'm open to trying it out if you think it will be a better approach

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
