### PR TITLE
refactor(network): db executor communicates through channels

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-iyJjl3YnZDC5AHKKW:-O-iyJjl3YnZDC5AHKKX:b-12ust4) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L3)):*
> ```XML
> mod swarm_trait;
> 
> // TODO(shahak): Uncomment
> ```

Do not merge until all the PR stack is merged so that this will be uncommented

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jd7sHELxhxxgcSJFq:-O-jd7sHELxhxxgcSJFr:b5rfgw2) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L307)):*
> ```XML
>                     Protocol::try_from(protocol_name).expect("Encountered unknown protocol");
>                 let internal_query = protocol.bytes_query_to_protobuf_request(query);
>                 match protocol {
> ```

let (sender, receiver) = match protocol etc.

to reduce duplication

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jd7sHELxhxxgcSJFq:-O-je9ve1GA3gXXeVFEr:b-a61d0) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L307)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

let (sender, receiver) = match protocol etc.

to reduce duplication
</blockquote></details>

This code is erased in #2122 . Is it ok if I don't fix this now to avoid rebases? or do you prefer I fix it nonetheless?

**Review by eitanm-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-:-O-jesFrEUnZv-l8LanW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jd7sHELxhxxgcSJFq:-O-jelLeBm2nybd2r6qg:bb7s9mg) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L307)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This code is erased in #2122 . Is it ok if I don't fix this now to avoid rebases? or do you prefer I fix it nonetheless?
</blockquote></details>

yeah

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-:-O-jmDgd4qZwrmvj9Uta:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware, @eitanm-starkware, and @ShahakShama)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jj-kl4d_L2AEVtLS2):*
I feel like making it generic is more important (or at least thinking that way made it easier for me to grok the PR)



_Suggestion:_
```
- ecb746d: refactor(network): make db executor generic over FetchBlockDataFromDb

This allows us to remove the concrete `Data` type.
```
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jmdHbBYgcKi3TVfXA:-O-jmdHc4jORbqHLQS5M:b-7zi8ni) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/db_executor/test.rs#L52)):*
> ```XML
>                 }
>             }
>         }
> ```

WDYT?



_Suggestion:_
```XML
        mut all_data = data_receiver.collect::<Vec<_>>() => {
            assert_eq!(DataOrFin(None), all_data.pop().unwrap());
            for (i, data) in all_data.into_iter().enumerate() {
                assert_eq!(data.0.unwrap().block_header.block_number.0, i as u64);
            }
        }
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-js6EmBvddgq3D_85l:-O-js6EmBvddgq3D_85m:bntb2l1) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L44)):*
> ```XML
>     header_buffer_size: usize,
>     sqmr_inbound_response_receivers:
>         StreamHashMap<InboundSessionId, BoxStream<'static, Option<Bytes>>>,
> ```

Should we move this stream to utilize the new Stream design we discussed? As in move the concept of streaming entirely out of `papyrus_network`.



_Code quote:_
```XML
    sqmr_inbound_response_receivers:
        StreamHashMap<InboundSessionId, BoxStream<'static, Option<Bytes>>>,
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jvBfA9gdPEpIROuzq:-O-jvBfA9gdPEpIROuzr:bwdhm2t) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L288)):*
> ```XML
> 
>     fn handle_sqmr_behaviour_event(&mut self, event: sqmr::behaviour::ExternalEvent) {
>         match event {
> ```

This function is nearly 100 lines. Can we have each branch call to a method?



_Code quote:_
```XML
        match event {
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jve99-AOconzBSvtF:-O-jve99-AOconzBSvtG:b8aokin) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L335)):*
> ```XML
>                     }
>                 }
>             }
> ```

Is this going to remain in the future? with explicit handling for each protocol



_Code quote:_
```XML
                match protocol {
                    Protocol::SignedBlockHeader => {
                        let (sender, receiver) = futures::channel::mpsc::channel::<
                            DataOrFin<SignedBlockHeader>,
                        >(self.header_buffer_size);
                        self.db_executor.register_query(internal_query, sender);
                        self.sqmr_inbound_response_receivers.insert(
                            inbound_session_id,
                            receiver
                                .map(|data| Some(Bytes::from(data)))
                                .chain(stream::once(ready(None)))
                                .boxed(),
                        );
                    }
                    Protocol::StateDiff => {
                        let (sender, receiver) = futures::channel::mpsc::channel::<
                            DataOrFin<StateDiffChunk>,
                        >(self.header_buffer_size);
                        self.db_executor.register_query(internal_query, sender);
                        self.sqmr_inbound_response_receivers.insert(
                            inbound_session_id,
                            receiver
                                .map(|data| Some(Bytes::from(data)))
                                .chain(stream::once(ready(None)))
                                .boxed(),
                        );
                    }
                }
            }
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @asmaastarkware, @eitanm-starkware, and @matan-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jj-kl4d_L2AEVtLS2):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I feel like making it generic is more important (or at least thinking that way made it easier for me to grok the PR)
</blockquote></details>

I didn't understand
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-js6EmBvddgq3D_85l:-O-k5cUr588IFfEeFm1X:b-2scean) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L44)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Should we move this stream to utilize the new Stream design we discussed? As in move the concept of streaming entirely out of `papyrus_network`.
</blockquote></details>

No. SG is based on a specific protobuf message that groups messages to streams. Also, here the responses are tied to some specific query in the networking level
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jvBfA9gdPEpIROuzq:-O-k60qO47Mk56n90Bjr:b-p4b08r) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L288)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This function is nearly 100 lines. Can we have each branch call to a method?
</blockquote></details>

Added a TODO for now because I'm afraid of this conflicting with the future PRs
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jve99-AOconzBSvtF:-O-k6-Ag1atezSR9-O0_:b32w12) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L335)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is this going to remain in the future? with explicit handling for each protocol
</blockquote></details>

No

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware, @eitanm-starkware, and @ShahakShama)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jj-kl4d_L2AEVtLS2):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I didn't understand
</blockquote></details>

I don't think deleting `Data` is the most important thing. I think making db executor generic is.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-js6EmBvddgq3D_85l:-O-oR6-k0y_nlhzA4aab:b6hvybw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L44)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No. SG is based on a specific protobuf message that groups messages to streams. Also, here the responses are tied to some specific query in the networking level
</blockquote></details>

Doesn't block the PR but I don't understand why `papyrus_network` sometimes handles streams and sometimes doesn't. It would make more sense to me if the networking layer either has the generic capacity to handle a stream or no capacity and we always use SG.
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-oROWY8WP5xiinSkMh:-O-oROWY8WP5xiinSkMi:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/32669c0c2173ad16bc4bdef863743ae69f973b2d/crates/papyrus_protobuf/src/converters/state_diff.rs#L94)):*
> ```XML
> auto_impl_into_and_try_from_vec_u8!(DataOrFin<StateDiffChunk>, protobuf::StateDiffsResponse);
> 
> auto_impl_into_and_try_from_vec_u8!(DataOrFin<StateDiffChunk>, protobuf::StateDiffsResponse);
> ```





_Suggestion:_
```XML
auto_impl_into_and_try_from_vec_u8!(DataOrFin<StateDiffChunk>, protobuf::StateDiffsResponse);
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware, @eitanm-starkware, and @matan-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-jj-kl4d_L2AEVtLS2):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't think deleting `Data` is the most important thing. I think making db executor generic is.
</blockquote></details>

Oh. Changed the PR title. I prefer not touching the commits themselves and they will dissappear when we merge anyway
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-js6EmBvddgq3D_85l:-O-oXWxwE2-8pp0mSCLU:b-xhb62s) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L44)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Doesn't block the PR but I don't understand why `papyrus_network` sometimes handles streams and sometimes doesn't. It would make more sense to me if the networking layer either has the generic capacity to handle a stream or no capacity and we always use SG.
</blockquote></details>

I'll be happy to explain in huddle :)
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-oROWY8WP5xiinSkMh:-O-oXchuBQj5PxhBLWCi:b-ha64sf) ([raw file](https://github.com/starkware-libs/papyrus/blob/32669c0c2173ad16bc4bdef863743ae69f973b2d/crates/papyrus_protobuf/src/converters/state_diff.rs#L94)):*
> ```XML
> auto_impl_into_and_try_from_vec_u8!(DataOrFin<StateDiffChunk>, protobuf::StateDiffsResponse);
> 
> auto_impl_into_and_try_from_vec_u8!(DataOrFin<StateDiffChunk>, protobuf::StateDiffsResponse);
> ```

Yes, I fixed it already. This was what caused the tests to fail

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-O-js6EmBvddgq3D_85l:-O-o_VDQ2T3KgT2-nL_M:b16ycbj) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecb746dbac0fc3950e18f7fb7e999264c8bf0877/crates/papyrus_network/src/network_manager/mod.rs#L44)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll be happy to explain in huddle :)
</blockquote></details>

Honestly I think I need this written out. You've tried to explain this to me a couple times already

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @eitanm-starkware)

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-:-O0Cnu6O9uYzXLR7gT9F:bnfp4nl)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @matan-starkware)

**Review by eitanm-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2120#-:-O0D6WwTBzyIzBLk6sX1:bnfp4nl)* status: 1 of 9 files reviewed, 1 unresolved discussion

**Pull request merged**
