### PR TITLE
test(network): add db executor tests

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1653** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1653?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1653?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653)* status: all files reviewed, 10 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVBFQa-QjB6S2o3HuB:-NpVBFQa-QjB6S2o3HuC:b5s8yzw) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/mod.rs#L98)):*
> ```XML
>                         .ok_or(DBExecutorError::BlockNotFound { block_number, query_id })?;
>                     // Using poll_fn because Sender::poll_ready is not a future
>                     match poll_fn(|cx| sender.poll_ready(cx)).await {
> ```

Why did this change? Is it just a stylistic change unrelated to the rest of the PR?
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCicnEFBYdRxxZYP8:-NpVCicnEFBYdRxxZYP9:b-xf788z) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L22)):*
> ```XML
> 
>     // put some data in the storage.
>     let num_of_blocks = 10;
> ```

Change to constant with ALL_CAPS (I mainly care about the ALL_CAPS)
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCJ1Z6Qhs7s1Koq60:-NpVCJ1Z6Qhs7s1Koq61:b72ttbv) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L43)):*
> ```XML
>         }
>         res = receiver.collect::<Vec<_>>() => {
>             assert_eq!(res.len(), num_of_blocks as usize);
> ```

Check the content (just the block Id is enough) or add a TODO to check
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCo3M8m3-RaT5qB6a:-NpVCo3M8m3-RaT5qB6b:b-xf788z) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L53)):*
> ```XML
>     let mut db_executor = super::BlockHeaderDBExecutor::new(storage_reader);
> 
>     let num_of_blocks = 10;
> ```

Change to constant with ALL_CAPS (I mainly care about the ALL_CAPS)
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCgSs1bfoVc4uZxNP:-NpVCgSs1bfoVc4uZxNQ:bddzi63) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L59)):*
> ```XML
>     let (sender, receiver) = futures::channel::mpsc::channel(BUFFER_SIZE);
>     let query = BlockQuery {
>         start_block: BlockNumber(num_of_blocks - 5),
> ```

Make 5 a constant
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCY8C7g6GW_SK1CW5:-NpVCY8C7g6GW_SK1CW6:b-7rfeef) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L66)):*
> ```XML
>     let _query_id = db_executor.register_query(query, sender);
> 
>     let res = receiver.collect::<Vec<_>>().await;
> ```

Why not select?
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCsMz9nsjgtTfenTy:-NpVCsMz9nsjgtTfenTz:b-ghmyg4) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L67)):*
> ```XML
> 
>     let res = receiver.collect::<Vec<_>>().await;
>     assert_eq!(res.len(), (num_of_blocks - 4) as usize);
> ```

When you make 5 a constant, change 4 here to be calculated
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCyis2scQc2fJb42E:-NpVCyis2scQc2fJb42F:b8cbz0j) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L67)):*
> ```XML
> 
>     let res = receiver.collect::<Vec<_>>().await;
>     assert_eq!(res.len(), (num_of_blocks - 4) as usize);
> ```

Validate content (or add TODO)
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVD6gt67eObA5N8RHw:-NpVD6gt67eObA5N8RHx:b-y0707j) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L79)):*
> ```XML
> 
>     // poll without registering a query.
>     let res = poll_fn(|cx| match db_executor.poll_next_unpin(cx) {
> ```

Why not `assert!(poll_fn(|cx| match db_executor.poll_next_unpin(cx)).now_or_never.is_none())`
And then you can make the test non async
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVDh5q2d16Pf9d_bJ6:-NpVDh5q2d16Pf9d_bJ7:b-pclbgq) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L146)):*
> ```XML
> }
> 
> fn insert_test_blocks_up_to(num_of_blocks: u64, storage_writer: &mut StorageWriter) {
> ```

Consider renaming to include the word storage somewhere in the name

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVBFQa-QjB6S2o3HuB:-NpYj9zi5omtYXfk7gR8:biuh7tt) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/mod.rs#L98)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did this change? Is it just a stylistic change unrelated to the rest of the PR?
</blockquote></details>

yes during testing I saw that it's easier to understand like that
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCJ1Z6Qhs7s1Koq60:-NpZ2bQn0pxpAd2zVJ6Y:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Check the content (just the block Id is enough) or add a TODO to check
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCgSs1bfoVc4uZxNP:-NpZ2uuK0GkTaIalcC0W:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make 5 a constant
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCY8C7g6GW_SK1CW5:-NpZ6N_w2Kb70MLTMByF:b-6onz8c) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L66)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not select?
</blockquote></details>

I think I had a reason but I can't remember it. changed
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCsMz9nsjgtTfenTy:-NpZ2vhJDmRLOWC0Ai2h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

When you make 5 a constant, change 4 here to be calculated
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVCyis2scQc2fJb42E:-NpZ66ih6h73EGyAfQqI:b-thhelu) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Validate content (or add TODO)
</blockquote></details>

I don't think it's needed the previous test "header_db_executor_can_register_and_run_a_query" checks the content this should cover it.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpVD6gt67eObA5N8RHw:-NpZ4_FcCuQjgXFV4zU8:bs7wumb) ([raw file](https://github.com/starkware-libs/papyrus/blob/53a95a62cab9442a00ad51a0ae61f6dbd77b0e31/crates/papyrus_network/src/db_executor/test.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not `assert!(poll_fn(|cx| match db_executor.poll_next_unpin(cx)).now_or_never.is_none())`
And then you can make the test non async
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpnaZ5gET4wyiYwtWTj:-NpnaZ5gET4wyiYwtWTk:b-uba8o6) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L46)):*
> ```XML
>             assert_eq!(res.len(), NUM_OF_BLOCKS as usize);
>             for (i, data) in res.iter().enumerate() {
>                 assert_matches!(data, super::Data::BlockHeaderAndSignature { header: BlockHeader { block_number: BlockNumber(block_number), .. }, ..} if block_number == &(i as u64 + 1));
> ```

Consider adding a use statement
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpnbXHsER6WG57Mu6i5:-NpnbXHsER6WG57Mu6i6:bo5f8kh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L60)):*
> ```XML
>     insert_to_storage_test_blocks_up_to(NUM_OF_BLOCKS, &mut storage_writer);
> 
>     const NUM_BLOCKS_DELTA: u64 = 5;
> ```

This name is confusing. Consider START_BLOCK=10 Instead
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpnbnbmDzeBo7JED7j3:-NpnbnbmDzeBo7JED7j4:bh9l43i) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L74)):*
> ```XML
>         res = db_executor.next() => {
>             let poll_res = res.unwrap();
>             assert!(poll_res.is_err());
> ```

Consider checking what error type did you get
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-Npnayv97jKkMZlrtcbl:-Npnayv97jKkMZlrtcbm:bly4gz) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L83)):*
> ```XML
> 
> #[tokio::test]
> async fn header_db_executor_stream_pending_with_no_query() {
> ```

Make this test non-async
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-Npnc34X9CpA9b2duoRU:-Npnc34X9CpA9b2duoRV:bjrkeuj) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L151)):*
> ```XML
> 
> fn insert_to_storage_test_blocks_up_to(num_of_blocks: u64, storage_writer: &mut StorageWriter) {
>     for i in 0..=num_of_blocks {
> ```

This ..= causes confusion. I'd expect this function to put num_blocks blocks in the storage, not num_blocks + 1

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-NpnbXHsER6WG57Mu6i5:-NpoXaQQ0zQ1cHx-wC0I:bjblknj) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This name is confusing. Consider START_BLOCK=10 Instead
</blockquote></details>

but that changes the logic of the test :) 
here if you change the `NUM_OF_BLOCKS` the start block would change also. 
is it better like this?
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-Npnc34X9CpA9b2duoRU:-NpoaUwYAgvoo6TP2RNW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8fcdbe638d916e6e6802135c18d60fd3b2a10244/crates/papyrus_network/src/db_executor/test.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This ..= causes confusion. I'd expect this function to put num_blocks blocks in the storage, not num_blocks + 1
</blockquote></details>

Done.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-:-Npoegkw5OCqCr5EELDm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1653#-:-NppaAaD7EWH8hL9MSyV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
