### PR TITLE
chore: add state_diff_length, receipt_commitment to BlockHeader from SN API

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: all files reviewed, 7 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1ytF2GUIU1jlecYj):*
Please specify the changes



_Code quote:_
```
bring new BlockHeader from SN API
```
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1b4S9YvqMRMscXX9:-Nsw1b4S9YvqMRMscXXA:ba9bpec) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L31)):*
> ```XML
>                     .ok_or(StorageSerdeError::Migration)?;
>                 Ok(v1_header.into())
>             }
> ```

```
if older_version < 1 {
    Ok(StorageBlockHeaderV0::try_from_older_version(bytes)?.into())
}
```



_Code quote:_
```XML
            0 => {
                let v0_header = StorageBlockHeaderV0::deserialize_from(bytes)
                    .ok_or(StorageSerdeError::Migration)?;
                Ok(StorageBlockHeaderV1::from(v0_header).into())
            }
            1 => {
                let v1_header = StorageBlockHeaderV1::deserialize_from(bytes)
                    .ok_or(StorageSerdeError::Migration)?;
                Ok(v1_header.into())
            }
```
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1pYUALet_PByGF2i:-Nsw1pYUALet_PByGF2j:bcloakl) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L155)):*
> ```XML
>         }
>     }
> }
> ```

Move up



_Code quote:_
```XML
impl From<StorageBlockHeaderV1> for StorageBlockHeader {
    fn from(v1_header: StorageBlockHeaderV1) -> Self {
        Self {
            block_hash: v1_header.block_hash,
            parent_hash: v1_header.parent_hash,
            block_number: v1_header.block_number,
            l1_gas_price: v1_header.l1_gas_price,
            l1_data_gas_price: v1_header.l1_data_gas_price,
            state_root: v1_header.state_root,
            sequencer: v1_header.sequencer,
            timestamp: v1_header.timestamp,
            l1_da_mode: v1_header.l1_da_mode,
            state_diff_commitment: v1_header.state_diff_commitment,
            state_diff_length: None,
            receipt_commitment: None,
            transaction_commitment: v1_header.transaction_commitment,
            event_commitment: v1_header.event_commitment,
            n_transactions: v1_header.n_transactions,
            n_events: v1_header.n_events,
        }
    }
}
```
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw2rBz03IkpIRrg_qc:-Nsw2rBz03IkpIRrg_qd:b-gutgks) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L16)):*
> ```XML
> 
> #[test]
> fn header_v0_to_v2() {
> ```

current



_Code quote:_
```XML
v2
```
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw2i0RA8uWN3eMMMWJ:-Nsw2i0SCKS-AMirq28f:b-gutgks) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L52)):*
> ```XML
>     txn.commit().unwrap();
> 
>     // Read the headers, expecting to get the V1 version via the migration.
> ```

current



_Code quote:_
```XML
V1
```
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw3octDIRMM5i3PXrT:-Nsw3octDIRMM5i3PXrU:b-2guby3) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L81)):*
> ```XML
> 
> #[test]
> fn header_v1_to_v2() {
> ```

same here



_Code quote:_
```XML
v2
```
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw3cqA3NsxxXWkOz-7:-Nsw3cqA3NsxxXWkOz-8:b5u3v7u) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L107)):*
> ```XML
>         .upsert(&txn.txn, &MarkerKind::Header, &BlockNumber(1))
>         .unwrap();
>     txn.commit().unwrap();
> ```

Can we extract this to a shared function?



_Code quote:_
```XML
    let ((reader, mut writer), _dir) = get_test_storage();
    // Insert a headers V1 to the db.
    let header_v1 = StorageBlockHeaderV1::get_test_instance(&mut get_rng());
    writer
        .begin_rw_txn()
        .unwrap()
        .update_starknet_version(&BlockNumber(0), &StarknetVersion::default())
        .unwrap()
        .commit()
        .unwrap();

    // No easy way to insert a deprecated version into the db.
    let v1_table_id = writer
        .db_writer
        .create_simple_table::<BlockNumber, VersionWrapper<StorageBlockHeaderV1, 1>>(
            reader.tables.headers.name,
        )
        .unwrap();
    let txn = writer.begin_rw_txn().unwrap();
    let v1_table = txn.open_table(&v1_table_id).unwrap();
    v1_table.insert(&txn.txn, &BlockNumber(0), &header_v1).unwrap();
    txn.open_table(&txn.tables.markers)
        .unwrap()
        .upsert(&txn.txn, &MarkerKind::Header, &BlockNumber(1))
        .unwrap();
    txn.commit().unwrap();
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: all files reviewed, 7 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1ytF2GUIU1jlecYj):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please specify the changes
</blockquote></details>

Fixed on the title (that's what matters)
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1b4S9YvqMRMscXX9:-NswBZMhCUhaGvZ0U9oO:b-mqw6u7) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

```
if older_version < 1 {
    Ok(StorageBlockHeaderV0::try_from_older_version(bytes)?.into())
}
```
</blockquote></details>

What? why?
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1pYUALet_PByGF2i:-NswBkNGDNEFt0sueOtQ:b-juknx1) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L155)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move up
</blockquote></details>

I think it should be here

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw2rBz03IkpIRrg_qc:-NswFDJ75oUpYdRAkzVh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L16)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

current
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw2i0RA8uWN3eMMMWJ:-NswFCdi6pcMZJQE21HH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L52)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

current
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/deprecated/migrations_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw3octDIRMM5i3PXrT:-NswFCFr0JtoyyfQNCfz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations_test.rs#L81)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1b4S9YvqMRMscXX9:-NswHH3S0ZPqOy8BKWh1:b-pl2f25) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What? why?
</blockquote></details>

Let's say you reach v10 - will each version implement migration from each of the previous versions?
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1pYUALet_PByGF2i:-NswIKtQAnyxzNra4ne2:b-3m3gbv) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L155)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think it should be here
</blockquote></details>

I think the newer the version the more interesting it is to the reader

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1b4S9YvqMRMscXX9:-NswKvME9azfIUOWBJUJ:b-vmmkcj) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Let's say you reach v10 - will each version implement migration from each of the previous versions?
</blockquote></details>

I think yes
___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1pYUALet_PByGF2i:-NswKz9G3ozptYd-pXLv:bqetskf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L155)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the newer the version the more interesting it is to the reader
</blockquote></details>

Ah, that's what you meant

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/deprecated/migrations.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-Nsw1b4S9YvqMRMscXX9:-NswSjsr6XGI6XfFhluy:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e628d749703486ceb78bc5514113e00bb233b4d/crates/papyrus_storage/src/deprecated/migrations.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think yes
</blockquote></details>

Done

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1811#-:-NswWlPi5koUbfJU2Zcy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
