### PR TITLE
feat(reader client): get the latest block

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/983)

### CODE REVIEW

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/983)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/papyrus_sync/src/lib.rs` line 581 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/983#-NbA6xmx7dec5ajwrFLo:-NbA6xmx7dec5ajwrFLp:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/1aafa70892ed452eb02d6392a43789d670c37a42/crates/papyrus_sync/src/lib.rs#L581)):*
> ```XML
>             let header_marker = reader.begin_ro_txn()?.get_header_marker()?;
>             let latest_block = central_source.get_latest_block().await?;
>             let block_marker = latest_block.map_or(BlockNumber::default(), |block| block.block_number.next());
> ```





_Suggestion:_
```XML
central_block_marker
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/983)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 581 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/983#-NbA6xmx7dec5ajwrFLo:-NbA8E1w1HOShDte5oOb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1aafa70892ed452eb02d6392a43789d670c37a42/crates/papyrus_sync/src/lib.rs#L581)):*
> ```XML
>             let header_marker = reader.begin_ro_txn()?.get_header_marker()?;
>             let latest_block = central_source.get_latest_block().await?;
>             let block_marker = latest_block.map_or(BlockNumber::default(), |block| block.block_number.next());
> ```

Done.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/983)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/983)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
