### PR TITLE
feat(network): add peer id to config

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1704?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1663** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1663?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1670** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1670?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1704** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1704?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
        * **PR #1705** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1705?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1704?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrA0JST7VIxMVhz-hCn:-NrA0JSU8I7MhWENILnT:b-ovi4l2) (no related file):*
Add TODO in the node crate to assert that if peer_id is None then p2p_sync is None once p2p_sync is merged

___
___
*[`crates/papyrus_network/src/lib.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrA-yv_EP2wcd5mgGUg:-NrA-yva5TVJagY5Tcw5:b-60tzrx) ([raw file](https://github.com/starkware-libs/papyrus/blob/85a2a1f6dc299d56f7857cc570e305ef6c05cadf/crates/papyrus_network/src/lib.rs#L129)):*
> ```XML
>                 "peer_id",
>                 &self.peer_id,
>                 "Peer ID to send requests to.",
> ```

Add details on the format of the string. Maybe an example
Also, explain what None means
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrAIpu20LZqvr-dqiP_:-NrAIpu20LZqvr-dqiPa:b-uy1jir) ([raw file](https://github.com/starkware-libs/papyrus/blob/85a2a1f6dc299d56f7857cc570e305ef6c05cadf/crates/papyrus_network/src/network_manager/mod.rs#L222)):*
> ```XML
> 
>         let db_executor = BlockHeaderDBExecutor::new(storage_reader);
>         let peer_id = peer_id.and_then(|str| PeerId::from_str(&str[..]).ok());
> ```

Don't hide the failure here
In general, I think that in NetworkConfig peer_id should be of type PeerId and that you should add a serializer (same thing we do for Duration)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrFowg5EN2GRWs7wgGu:-NrFpZN53WftQT769L0q:b-i70mct) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c0aeaf63ec6cad67f25efbfa2020b0fadf1dcf3/crates/papyrus_network/src/lib.rs#L132)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should dump self.peer_id here. Otherwise you're lying about the value
What I meant is to add peer_id_example to the description below, but http link is a good alternative
</blockquote></details>

a peer id is a hash so an example is not very usefull. 
the value here is an example that shows up in the config dump file not the value of self (which doesn't exist at this point since it's before we create the network).
I know it's confusing it's something that Yair has listed to fix.. 
___
*[`crates/papyrus_network/src/lib.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrFonb6-6y0vKEUvXzr:-NrFqmenDby4VsKlCbI-:bqeb4l7) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c0aeaf63ec6cad67f25efbfa2020b0fadf1dcf3/crates/papyrus_network/src/lib.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

the peer -> the node
</blockquote></details>

how is it different from the `tcp_port` description above?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrFowg5EN2GRWs7wgGu:-NrFtAjlA0_qo3HASOqU:bz4w3k) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c0aeaf63ec6cad67f25efbfa2020b0fadf1dcf3/crates/papyrus_network/src/lib.rs#L132)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

a peer id is a hash so an example is not very usefull. 
the value here is an example that shows up in the config dump file not the value of self (which doesn't exist at this point since it's before we create the network).
I know it's confusing it's something that Yair has listed to fix..
</blockquote></details>

I don't understand. Asked Yair in slack
___
*[`crates/papyrus_network/src/lib.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-NrFonb6-6y0vKEUvXzr:-NrFstgX3Xp_ONKDNGoz:b-7llfo7) ([raw file](https://github.com/starkware-libs/papyrus/blob/3c0aeaf63ec6cad67f25efbfa2020b0fadf1dcf3/crates/papyrus_network/src/lib.rs#L134)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

how is it different from the `tcp_port` description above?
</blockquote></details>

You're right, fix it there as well.
In general, when you reference the current peer, you call it node. And when you reference other peers you call them peers

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1704#-:-NrVKwuj1NHkUBR0EXKO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
