### PR TITLE
test(network): add test for network manager

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(network): send fin when encountering DB executor error
- test(network): add test for network manager

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1683)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1683)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1683#-NqRWdWX8OuC0W_Ks9CZ:-NqRWdWX8OuC0W_Ks9C_:b-nuueuy) ([raw file](https://github.com/starkware-libs/papyrus/blob/1d047ce219af857adff6702869f2aa7f9fe0db48/crates/papyrus_network/src/network_manager/mod.rs#L47)):*
> ```XML
>     }
> 
>     pub(self) fn inner_new(
> ```

please rename. you can take notes from python and name it something like `super_new` or use generic in the name like `generic_new`/`generic_constructor`
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1683#-NqRYIK6E--_xYDaaxe7:-NqRYIK6E--_xYDaaxe8:b-cyu5wu) ([raw file](https://github.com/starkware-libs/papyrus/blob/1d047ce219af857adff6702869f2aa7f9fe0db48/crates/papyrus_network/src/network_manager/test.rs#L144)):*
> ```XML
> 
> #[tokio::test]
> async fn process_incoming_query() {
> ```

please add comments to explain the test.. it takes a lot of effort to understand the flow you are testing

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1683)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1683#-NqRWdWX8OuC0W_Ks9CZ:-NqRZjQy7dQsw9w1_krs:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1d047ce219af857adff6702869f2aa7f9fe0db48/crates/papyrus_network/src/network_manager/mod.rs#L47)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please rename. you can take notes from python and name it something like `super_new` or use generic in the name like `generic_new`/`generic_constructor`
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1683#-NqRYIK6E--_xYDaaxe7:-NqR_KQQDO6xqB_CKloB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1d047ce219af857adff6702869f2aa7f9fe0db48/crates/papyrus_network/src/network_manager/test.rs#L144)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please add comments to explain the test.. it takes a lot of effort to understand the flow you are testing
</blockquote></details>

Done.

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1683#-:-NqRaKGR-vLWvMu30P3d:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
