### PR TITLE
feat(network): add conversions from protobuf to transaction outputs

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-NyopJb20MPMqbW0uk6k:-Nyop7yK1J6INFz4ArZD:bkvng65) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a8f5f8a0c0a2b8de69dacce7db82a6fe437569e/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L94)):*
> ```XML
>     type Error = ProtobufConversionError;
>     fn try_from(value: protobuf::receipt::Deploy) -> Result<Self, Self::Error> {
>         let common = value
> ```

There's a lot of code duplication here. Could you create a helper function that receives a protobuf::receipt::Common and outputs the following with types as they appear in SN API output: actual_fee, messages_sent, contract_address, execution_status, execution_resources?
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-Nyooi230F4xWHgZq7me:-Nyooi230F4xWHgZq7mf:bht64su) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a8f5f8a0c0a2b8de69dacce7db82a6fe437569e/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L130)):*
> ```XML
>         })?);
> 
>         let execution_status = common.revert_reason.map_or_else(
> ```

No need to use map_or_else, you can use map_or since there's no cost here for creating the value and not using it
Same in the other functions

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-NyopJb20MPMqbW0uk6k:-NyopwwE6jFEWiq59NaI:by6fgkz) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a8f5f8a0c0a2b8de69dacce7db82a6fe437569e/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L94)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

There's a lot of code duplication here. Could you create a helper function that receives a protobuf::receipt::Common and outputs the following with types as they appear in SN API output: actual_fee, messages_sent, contract_address, execution_status, execution_resources?
</blockquote></details>

It will also need to receive a string for ProtobufConversionError

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-NyopJb20MPMqbW0uk6k:-Nyp-Vq2EOkWbWvZLrwB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a8f5f8a0c0a2b8de69dacce7db82a6fe437569e/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L94)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It will also need to receive a string for ProtobufConversionError
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-Nyooi230F4xWHgZq7me:-Nyp-VMx13yYoXnLr0MW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a8f5f8a0c0a2b8de69dacce7db82a6fe437569e/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to use map_or_else, you can use map_or since there's no cost here for creating the value and not using it
Same in the other functions
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-Nyp0_7N8Op0nAgI1qOC:-Nyp0_7N8Op0nAgI1qOD:b-ktviip) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d950213973fe41662190902751f1b092feb3f91/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L24)):*
> ```XML
> use crate::protobuf_messages::protobuf::{self};
> 
> fn parse_common_receipt_fields(
> ```

Put this at the end of the file

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-Nyp0_7N8Op0nAgI1qOC:-Nyp3KKh9xzaFgDgTnKa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d950213973fe41662190902751f1b092feb3f91/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put this at the end of the file
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2053#-:-Nyp3Ul0E0eDEzQ8UZTn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
