### PR TITLE
feat(consensus): add tracing instrumentation and logging to consensus

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2138)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2138?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2134** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2131?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2126** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2138** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2138?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2137** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2137?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2125** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2125?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2138)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DUTDf6VNo_KrUJAA7:-O0DUTDf6VNo_KrUJAA8:bc38amw) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/papyrus_node/src/main.rs#L101)):*
> ```XML
> ) -> anyhow::Result<JoinHandle<Result<(), ConsensusError>>> {
>     let Ok(validator_id) = env::var("CONSENSUS_VALIDATOR_ID") else {
>         debug!("CONSENSUS_VALIDATOR_ID is not set. Not running consensus.");
> ```

Can remain info IMO



_Code quote:_
```XML
debug!
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DVEfhE2zYgKDJIemV:-O0DVEfhE2zYgKDJIemW:b-ectrd7) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/lib.rs#L23)):*
> ```XML
> 
> // TODO(dvir): add test for this.
> #[instrument(
> ```

Consider adding explicit level



_Code quote:_
```XML
#[instrument(
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DUgGd7I0pXCV-pc8P:-O0DUgGd7I0pXCV-pc8Q:b-hzb1mg) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/lib.rs#L24)):*
> ```XML
> // TODO(dvir): add test for this.
> #[instrument(
>     skip(context, start_height, network_receiver),
> ```

Why skipping start height?



_Code quote:_
```XML
start_height
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DV2aiEHWzpDYmIjE1:-O0DV2ajEXXnmGlyh3e2:bk4zpx2) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L40)):*
> ```XML
>     }
> 
>     #[instrument(skip(self), fields(height=self.height.0), level = "info")]
> ```

Why not debug?



_Code quote:_
```XML
level = "info"
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DV6e25teNFs9Ln9dy:-O0DV6e25teNFs9Ln9dz:bk4zpx2) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L76)):*
> ```XML
>         skip(self, init, content_receiver, fin_receiver),
>         fields(height = %self.height),
>         level = "info"
> ```

Why not debug?



_Code quote:_
```XML
level = "info"
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2138)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DUgGd7I0pXCV-pc8P:-O0Dw9c977MEw4ppXN6H:b78jqnd) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/lib.rs#L24)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why skipping start height?
</blockquote></details>

Because these fields are printed out with every single log within this scope. I only want to print the starting height once when I begin.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2138#-O0DUgGd7I0pXCV-pc8P:-O0IhLng4FshKz7Z0ERr:b-l3t7ti) ([raw file](https://github.com/starkware-libs/papyrus/blob/502079070b3268c3be5047ab40e22df50a40a10d/crates/sequencing/papyrus_consensus/src/lib.rs#L24)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Because these fields are printed out with every single log within this scope. I only want to print the starting height once when I begin.
</blockquote></details>

That's not necessarily a bad thing, I'm fine either way

**Pull request merged**
