### PR TITLE
fix(ci): fix docker cache

### PR DESCRIPTION
**Pull request by idan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2200)

### CODE REVIEW

**Review by eranreshef-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by eranreshef-starkware** [comment]
:lgtm:

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2200)* status: all files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`.github/workflows/ci.yml` line 244 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2200#-O1IqsbJ7sEB_6ovT_qA:-O1IqsbJ7sEB_6ovT_qB:b-9unw6p) ([raw file](https://github.com/starkware-libs/papyrus/blob/935fbb6fb6f95eea7d5d9cfa153533a67a2b690b/.github/workflows/ci.yml#L244)):*
> ```YAML
>       - name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v3
>         
> ```

delete?



_Code quote:_
```YAML
·······
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
