### PR TITLE
Yair/replace class

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/563)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_storage/src/state/mod.rs` line 157 at r14](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NR2XIRl4h9be_lsJKim:-NR2XIRm6EYtLYtFZxsS:b-cl2ki0) ([raw file](https://github.com/starkware-libs/papyrus/blob/84720637df6707d78cff857465efc35381b3f79b/crates/papyrus_storage/src/state/mod.rs#L157)):*
> ```XML
>     ) -> StorageResult<Option<ClassHash>> {
>         // Check if the class was replaced before state_number.
>         if let Some(class_hash) = self.get_replaced_class_hash(state_number, address)? {
> ```

I think all class hashes should be taken from the deployed_contracts_table, replaced or not. The replaced classes will be gone after regenesis.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/state/mod.rs` line 30 at r14](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NR2WjAq4yHECWgDPP-T:-NR3CQnb2L7fzlfN_x0p:b-st4zgo) ([raw file](https://github.com/starkware-libs/papyrus/blob/84720637df6707d78cff857465efc35381b3f79b/crates/papyrus_storage/src/state/mod.rs#L30)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Why doesn’t it look like the DeployedContractsTable?
</blockquote></details>

The class can be replaced multiple times, so when you execute a transaction you need the class from the block of the transaction.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r9, 2 of 37 files at r15, 3 of 3 files at r16, 7 of 7 files at r17, 4 of 4 files at r18, 21 of 21 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/563)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NRg_toW8yOxeBrDYEHv:-NRg_toW8yOxeBrDYEHw:bo2yu34) (no related file):*
How do you test the new functionality?

___
___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 11 at r19](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NRgXGhi8_NsXwCPy9sX:-NRgXGhi8_NsXwCPy9sY:bkqj22l) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b91940e563159f0721abc2b86af312133e4e239/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L11)):*
> ```XML
>     let config = Config::load(vec![
>         "--chain_id=SN_GOERLI".to_owned(),
>         "--central_url=https://external.integration.starknet.io/".to_owned(),
> ```

Please use `to_string` instead 



_Code quote:_
```XML
.to_owned
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/563)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NRg_toW8yOxeBrDYEHv:-NRgxxVDBtGQgrhe0_TJ:b-lil228) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

How do you test the new functionality?
</blockquote></details>

Added test to the storage

___
___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 11 at r19](https://reviewable.io/reviews/starkware-libs/papyrus/563#-NRgXGhi8_NsXwCPy9sX:-NRgxrP_4jV80flKcb4z:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b91940e563159f0721abc2b86af312133e4e239/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use `to_string` instead 
</blockquote></details>

Done

**Pull request merged**
