### PR TITLE
feat(storage): add kind of storage read benchmark

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`papyrus_utilities.Dockerfile` line 22 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVx1iYBUP4I89p1L9U:-NtVx1iYBUP4I89p1L9V:bqlsr7o) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0ef3fb90f4eb563efd6145d913f48d6183e0e85/papyrus_utilities.Dockerfile#L22)):*
> ```
> RUN CARGO_INCREMENTAL=0 cargo build --target x86_64-unknown-linux-musl --release --package papyrus_storage --bin dump_declared_classes
> 
> # Build dump_declared_classes.
> ```

Please fix



_Code quote:_
```
# Build dump_declared_classes.
```
___
*[`papyrus_utilities.Dockerfile` line 36 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVx4Sy1Egs8L0Sm-ub:-NtVx4Sy1Egs8L0Sm-uc:bqlsr7o) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0ef3fb90f4eb563efd6145d913f48d6183e0e85/papyrus_utilities.Dockerfile#L36)):*
> ```
> COPY --from=utilities_builder /app/target/x86_64-unknown-linux-musl/release/dump_declared_classes /app/target/release/dump_declared_classes
> 
> # Copy the dump_declared_classes executable.
> ```

Please fix



_Code quote:_
```
# Copy the dump_declared_classes executable.
```
___
*[`crates/papyrus_storage/src/document_calls.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVz9ZJ-as-ndK2SuHI:-NtVz9ZJ-as-ndK2SuHJ:b-stm6kh) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0ef3fb90f4eb563efd6145d913f48d6183e0e85/crates/papyrus_storage/src/document_calls.rs#L2)):*
> ```XML
> //! This module is used to log calls to the storage system. This is useful for benchmarking
> //! and used in the storage_benchmark tool.
> ```

can you link to it?



_Code quote:_
```XML
storage_benchmark
```
___
*[`crates/papyrus_storage/src/document_calls.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtW0XCG4D5tyP1AeIQE:-NtW0XCG4D5tyP1AeIQF:byi9vdt) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0ef3fb90f4eb563efd6145d913f48d6183e0e85/crates/papyrus_storage/src/document_calls.rs#L28)):*
> ```XML
>     file.write_all(b"\n").expect("Failed to write a new line to file");
>     file.flush().expect("Failed to flush file");
> }
> ```

Please rephrase expect messages with "should"
https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style



_Code quote:_
```XML
lazy_static! {
    pub(crate) static ref QUERY_FILE: Mutex<File> = Mutex::new(
        File::create(QUERY_FILE_PATH).expect("Failed to create document_calls.txt file")
    );
}

// Adds a query to the document_calls file.
pub(crate) fn add_query(query: StorageQuery) {
    let query_string = serde_json::to_string(&query).expect("Failed to serialize query");
    let mut file = QUERY_FILE.lock().expect("Failed to lock file");
    file.write_all(query_string.as_bytes()).expect("Failed to write query to file");
    file.write_all(b"\n").expect("Failed to write a new line to file");
    file.flush().expect("Failed to flush file");
}
```
___
*[`crates/papyrus_storage/src/lib.rs` line 784 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtQijLC1WrQVxQghhXK:-NtQijLC1WrQVxQghhXL:b-re3vf) ([raw file](https://github.com/starkware-libs/papyrus/blob/60a9cbc0aa09030fe8a02a2a56e8efb39a008442/crates/papyrus_storage/src/lib.rs#L784)):*
> ```XML
> #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
> #[serde(rename_all = "snake_case")]
> pub enum StorageQuery {
> ```

Can this be elsewhere?
Maybe closer to corresponding modules?



_Code quote:_
```XML
pub enum StorageQuery
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

___
*[`papyrus_utilities.Dockerfile` line 22 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVx1iYBUP4I89p1L9U:-NtWa2e99QE2JftN43Lw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2391388c5e37b3988bcf0f9ec88355b75f540215/papyrus_utilities.Dockerfile#L22)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix
</blockquote></details>

Done.
___
*[`papyrus_utilities.Dockerfile` line 36 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVx4Sy1Egs8L0Sm-ub:-NtWa3O915ZITiX17907:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2391388c5e37b3988bcf0f9ec88355b75f540215/papyrus_utilities.Dockerfile#L36)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/document_calls.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtVz9ZJ-as-ndK2SuHI:-NtWbjtlAnzNtMpCau6u:b-qxxvfz) ([raw file](https://github.com/starkware-libs/papyrus/blob/2391388c5e37b3988bcf0f9ec88355b75f540215/crates/papyrus_storage/src/document_calls.rs#L2)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

can you link to it?
</blockquote></details>

I added todo for that. Only After publishing the binary crate I will have what to put a link to.
___
*[`crates/papyrus_storage/src/document_calls.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtW0XCG4D5tyP1AeIQE:-NtjqSOWCJSqaaMe_fsJ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/2391388c5e37b3988bcf0f9ec88355b75f540215/crates/papyrus_storage/src/document_calls.rs#L28)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please rephrase expect messages with "should"
https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1769#-NtjqUu9BFGMBlBL5UxV:-NtjqUuA0eEvwtfypOwD:b6r5un4) ([raw file](https://github.com/starkware-libs/papyrus/blob/41f0b295a98ff9e8fbd7d1483b34c55b9d5ac2eb/crates/papyrus_storage/src/bin/storage_benchmark.rs#L16)):*
> ```XML
> // TODO(dvir): consider adding tests.
> 
> pub fn main() {
> ```

By making this public, if and when we publish this tool, I will have this function to link from the storage crate documentation.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)* status: all files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
