### PR TITLE
feat(monitoring): add ready function

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1209#-NfGnCBa1zYEA9zv4HOw:-NfGnCBa1zYEA9zv4HOx:b55dv8k) (no related file):*
Fix CI issues

___
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1209#-NfGmodl1G0iKPlcUJ0H:-NfGmodl1G0iKPlcUJ0I:b-kl43c0) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b7e622d3acd77e552c2909dc795408f82decf9c/crates/papyrus_monitoring_gateway/src/lib.rs#L189)):*
> ```XML
> }
> 
> async fn is_ready() -> String {
> ```

document

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1209#-NfGnCBa1zYEA9zv4HOw:-NfGtufM5W3uD1uP8WhD:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Fix CI issues
</blockquote></details>

Done.

___

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1209#-:-NfGw_96BLj7dRvq0AP4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
