### PR TITLE
refactor(consensus): switch StateMachine from GetProposal to StartValue

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2166?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2166** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2166?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2161** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2159** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166)* status: all files reviewed, 13 unresolved discussions (waiting on @asmaastarkware, @dan-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qi-0-7MXRczR-n5T_:-O0qi-0-7MXRczR-n5Ta:blp1l48) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L13)):*
> ```XML
> 
> #[derive(Debug, Clone, PartialEq)]
> pub enum StateMachineEvent {
> ```

Document this. I guess it's an important enum for the entire consensus understanding so it needs to be clear what each event means. Also, isn't Decision and StartRound the same?
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qm29W4l0or17BhDlu:-O0qm29W4l0or17BhDlv:bifdbv8) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L17)):*
> ```XML
>     // BlockHash, Round
>     Proposal(BlockHash, Round),
>     Prevote(BlockHash, Round),
> ```

Do we want to add weight to prevote and precommit?
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qiSRI7t91OOMBVGGV:-O0qiSRI7t91OOMBVGGW:b9nnh2e) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L44)):*
> ```XML
>     prevotes: HashMap<Round, HashMap<BlockHash, u32>>,
>     precommits: HashMap<Round, HashMap<BlockHash, u32>>,
>     // When true, the state machine will wait for a GetProposal event, cacheing all other input
> ```

I think it's caching and not cacheing. And I think the more correct word is buffering
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qjIKH-piO6q6RcD5q:-O0qjIKH-piO6q6RcD5r:b-rpm88t) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L65)):*
> ```XML
>     }
> 
>     pub fn start(&mut self) -> Vec<StateMachineEvent> {
> ```

Document this function. Especially the return value
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qjRJm07EeVK5b1Rcr:-O0qjRJm07EeVK5b1Rcs:b-7vf46q) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L73)):*
> ```XML
>     ///
>     /// If we have just started a new round and are awaiting `StartRound` then any event other than
>     /// `StartRound` will be cached for processing after `StartRound` is received. If an event we
> ```

Same as before. cached -> buffered

You're going a bit into implementation details here. You can state that if the event can't be handled now, it will be buffered until the moment it can be handled
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qjpZXDT2GmUQjeOgf:-O0qjpZXDT2GmUQjeOgg:b-4pvb9a) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L76)):*
> ```XML
>     /// can handle is received, then we handle it and all other cached events.
>     ///
>     /// This returns a set of events back to the caller. The caller should not pass the output
> ```

In order to make this more clear, please create a different type for OutputStateMachineEvent and InputStateMachineEvent and type above them that the user should not convert one into another (instead of this comment)
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qkVHtE4JTrKsDqUgo:-O0qkVHtE4JTrKsDqUgp:b-fzya4u) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L151)):*
> ```XML
>     }
> 
>     // Returned to the node if we are not the proposer.
> ```

WDYM "Returned to the node"? DYM this function does nothing if we're not the proposer? If yes, write that
Also, I don't see this part in the code itself
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qkkV80UCXrQL4bk6Z:-O0qkkV80UCXrQL4bk6_:b4jolod) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L211)):*
> ```XML
>             return Vec::new();
>         };
>         // Can only occur due to a malicious proposer.
> ```

Add TODO to handle malicious proposer instead of panicing
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qlJ0--Q-w3U9rcnWn:-O0qlJ0--Q-w3U9rcnWo:buk3ph3) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L9)):*
> ```XML
> #[test_case(true; "proposer")]
> #[test_case(false; "validator")]
> fn in_order(is_proposer: bool) {
> ```

This is not a good test name. Try to make it more descriptive
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0ql3NyBS24hWtGiiHV:-O0ql3NyBS24hWtGiiHW:bw8fqap) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L10)):*
> ```XML
> #[test_case(false; "validator")]
> fn in_order(is_proposer: bool) {
>     let mut sm = StateMachine::new(4);
> ```

Rename sm to state_machine. Same in other tests
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qky_n863NWfXAC52x:-O0qky_n863NWfXAC52y:b2io5qz) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L15)):*
> ```XML
>     assert_eq!(events.remove(0), StateMachineEvent::StartRound(None, 0));
>     if is_proposer {
>         events = sm.handle_event(StateMachineEvent::StartRound(Some(BlockHash(Felt::ONE)), 0));
> ```

Extract BlockHash(Felt::ONE) to a constant. Same in other tests
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qlgat0aFj-QUniRbd:-O0qlgat0aFj-QUniRbe:b83afdj) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L47)):*
> ```XML
>     assert_eq!(events.remove(0), StateMachineEvent::StartRound(None, 0));
>     assert!(events.is_empty());
>     events.append(&mut sm.handle_event(StateMachineEvent::StartRound(None, 0)));
> ```

append -> extend?
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qlBpSDlbti78VWw-z:-O0qlBpSDlbti78VWw0-:b-a5q52s) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L68)):*
> ```XML
> 
> #[test]
> fn cache_events_during_start_round() {
> ```

cache -> buffer

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qm29W4l0or17BhDlu:-O0s7B5KEg-5LqmUX2bw:bhly4th) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L17)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We do want to add weight, but not yet. We're trying very hard to break things into small steps.
</blockquote></details>

I think that in cases like this it's good to write a TODO in every place you know what is the next change so that it will be easier for you to add it later on. Unblocking for now
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qjIKH-piO6q6RcD5q:-O0s7N4N8MBCCY1DSMAU:b-n36tqt) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L65)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You still didn't document the return value. You can fix it later on
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qjpZXDT2GmUQjeOgf:-O0sDDB_4VLT4YWuldAq:b6cy036) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L76)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

You are replacing the comment here "don't mirror my own events back" with either a comment not to convert the types or by enforcing in code they cannot be converted. The problem is that when the state machine wants to send a message it also needs to receive that very same message. Even if we had 2 types without a `From` impl, we could still expect the user the build an `InputEvent` from an `OutputEvent` manually.

We must make a design decision about what is more pleasant for the SHC, mirroring messages back to SM or not.
</blockquote></details>

Resolving for now, but think of a better way for this

**Review by ShahakShama — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @dan-starkware, and @matan-starkware)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @dan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-O0qm29W4l0or17BhDlu:-O0sHg6I2uEBRvBj80Be:bqk0lad) ([raw file](https://github.com/starkware-libs/papyrus/blob/697108d5b9c5320d170e8521cdef23a0afff8d3e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think that in cases like this it's good to write a TODO in every place you know what is the next change so that it will be easier for you to add it later on. Unblocking for now
</blockquote></details>

There are a lot of places, but most are obvious. I added the TODO to the places I think are more likely to be forgotten.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2166#-:-O0sanyh2F9HTHl_ukw1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware and @dan-starkware)

**Pull request merged**
