### PR TITLE
feat(network): add macro for impl TryFrom<Vec<u8>> and Into<Vec<u8>> and use it in query

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2060)

### CODE REVIEW

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2060#-:-NyxhWkT-ADdo7LPZMOX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2060)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2060#-NyxoZc11EiDxRzLE84D:-NyxoZc239wQaVNEcyVr:b-7rlldf) (no related file):*
Blocking until @DvirYo-starkware reviews

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2060)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2060#-NyxoZc11EiDxRzLE84D:-Nyxoi7D9tiOoewjx41M:b-jvknz6) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Blocking until @DvirYo-starkware reviews
</blockquote></details>

Looks like I can't block my own PR :sweat_smile: 

___

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2060#-:-Nyy3qNzBdCJGmo6UzQq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Pull request merged**
