### PR TITLE
test(starknet_client): fix gateway integration test

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1497)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1497)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_rpc/tests/gateway_integration_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1497#-NlMi7Un5D4enfiq1L35:-NlMi7Un5D4enfiq1L36:b-lbr9gt) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9369820248e59782ead2080e6fa0dba6a4bef2a/crates/papyrus_rpc/tests/gateway_integration_test.rs#L44)):*
> ```XML
>                     L2_ETH_CONTRACT_ADDRESS,
>                     EntryPointSelector(stark_felt!(BALANCE_OF_ENTRY_POINT_SELECTOR)),
>                     calldata![*account.0.key()],
> ```

These should be wrapped with CallRequest (added yesterday)



_Code quote:_
```XML
                    L2_ETH_CONTRACT_ADDRESS,
                    EntryPointSelector(stark_felt!(BALANCE_OF_ENTRY_POINT_SELECTOR)),
                    calldata![*account.0.key()],
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_rpc/tests/gateway_integration_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1497#-NlMi7Un5D4enfiq1L35:-NlMtgDk0kj97Ay0Gb4p:bfvdtbo) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9369820248e59782ead2080e6fa0dba6a4bef2a/crates/papyrus_rpc/tests/gateway_integration_test.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

These should be wrapped with CallRequest (added yesterday)
</blockquote></details>

`rpc_params!` takes care of this, right? Like `contract\_address`for `L2_ETH_CONTRACT_ADDRESS`

**Comment by yair-starkware** [comment]
*[`crates/papyrus_rpc/tests/gateway_integration_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1497#-NlMi7Un5D4enfiq1L35:-NlMwv9A71qusS4USuK9:beq2hqe) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9369820248e59782ead2080e6fa0dba6a4bef2a/crates/papyrus_rpc/tests/gateway_integration_test.rs#L44)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

`rpc_params!` takes care of this, right? Like `contract\_address`for `L2_ETH_CONTRACT_ADDRESS`
</blockquote></details>

I don't think so because the serialization is different

**Comment by yair-starkware** [comment]
*[`crates/papyrus_rpc/tests/gateway_integration_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1497#-NlMi7Un5D4enfiq1L35:-NlMxDtV5ar3lfEf_7iO:bpabo7u) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9369820248e59782ead2080e6fa0dba6a4bef2a/crates/papyrus_rpc/tests/gateway_integration_test.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think so because the serialization is different
</blockquote></details>

Maybe I'm wrong, did you try it?

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1497)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/tests/gateway_integration_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1497#-NlMi7Un5D4enfiq1L35:-NlN2HjZ9kbW8fADeJjd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9369820248e59782ead2080e6fa0dba6a4bef2a/crates/papyrus_rpc/tests/gateway_integration_test.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Maybe I'm wrong, did you try it?
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1497)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
