### PR TITLE
build: add option to compile the node without rpc

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-NqY5cZ88W0aAFXVcsWk:-NqY5cZ88W0aAFXVcsWl:bxn0r40) ([raw file](https://github.com/starkware-libs/papyrus/blob/a37d3f39b78ebb7ea1e74de429b1be43f8f0acde/crates/papyrus_node/src/bin/dump_config.rs#L43)):*
> ```XML
> }
> 
> #[cfg(not(feature = "rpc"))]
> ```

Does something break if we keep the RPC config in the default file in the scenario of no rpc?
If not, I think we should avoid creating another default config file.
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-NqY6SdH5YaMWpJd8PbT:-NqY6SdH5YaMWpJd8PbU:b-ksphsw) ([raw file](https://github.com/starkware-libs/papyrus/blob/a37d3f39b78ebb7ea1e74de429b1be43f8f0acde/crates/papyrus_node/src/bin/dump_config.rs#L76)):*
> ```XML
> 
> /// Updates the default config file by:
> /// cargo run --bin dump_config -q
> ```

Don't we need to run without the rpc feature somehow in case we want to keep both default files?



_Code quote:_
```XML
cargo run --bin dump_config -q
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-NqY5cZ88W0aAFXVcsWk:-NqafNrC3ecPSOGST774:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a37d3f39b78ebb7ea1e74de429b1be43f8f0acde/crates/papyrus_node/src/bin/dump_config.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Does something break if we keep the RPC config in the default file in the scenario of no rpc?
If not, I think we should avoid creating another default config file.
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-NqY6SdH5YaMWpJd8PbT:-NqafNOg-swERbjWAU5z:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a37d3f39b78ebb7ea1e74de429b1be43f8f0acde/crates/papyrus_node/src/bin/dump_config.rs#L76)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Don't we need to run without the rpc feature somehow in case we want to keep both default files?
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_node/src/main.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqathlg3YCvVQ2LzWVV:-Nqathlg3YCvVQ2LzWVW:b-gujrf3) ([raw file](https://github.com/starkware-libs/papyrus/blob/e13238b4261c1dba0f9a341dd0260d839892a2a3/crates/papyrus_node/src/main.rs#L5)):*
> ```XML
> 
> use std::env::args;
> use std::future::{self, pending, Future};
> ```

Is this on purpose?



_Code quote:_
```XML
self
```
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqauzy0DMW4IU36yajc:-Nqauzy0DMW4IU36yajd:b-muyfs6) ([raw file](https://github.com/starkware-libs/papyrus/blob/e13238b4261c1dba0f9a341dd0260d839892a2a3/crates/papyrus_node/src/bin/dump_config.rs#L72)):*
> ```XML
>         ),
>         vec!["monitoring_gateway.collect_metrics".to_owned()],
>     )];
> ```

Do we still need this extra code? We don't dump default config for no rpc anymore, right?



_Code quote:_
```XML
#[cfg(not(feature = "rpc"))]
lazy_static! {
    /// Returns vector of (pointer target name, pointer target serialized param, vec<pointer param path>)
    /// to be applied on the dumped node config.
    /// The config updates will be performed on the shared pointer targets, and finally, the values
    /// will be propagated to the pointer params.
    static ref CONFIG_POINTERS: Vec<((ParamPath, SerializedParam), Vec<ParamPath>)> = vec![(
        ser_pointer_target_param(
            "chain_id",
            &ChainId("SN_MAIN".to_string()),
            "The chain to follow. For more details see https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#chain-id.",
        ),
        vec!["storage.db_config.chain_id".to_owned()],
    ),
    (
        ser_pointer_target_param(
            "starknet_url",
            &"https://alpha-mainnet.starknet.io/".to_string(),
            "The URL of a centralized Starknet gateway.",
        ),
        vec!["central.url".to_owned(), "monitoring_gateway.starknet_url".to_owned()],
    ),
    (
        ser_pointer_target_param(
            "collect_metrics",
            &false,
            "If true, collect metrics for the node.",
        ),
        vec!["monitoring_gateway.collect_metrics".to_owned()],
    )];
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqathlg3YCvVQ2LzWVV:-NqawA7-2qd5sd531xFE:bnga3h4) ([raw file](https://github.com/starkware-libs/papyrus/blob/e13238b4261c1dba0f9a341dd0260d839892a2a3/crates/papyrus_node/src/main.rs#L5)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this on purpose?
</blockquote></details>

This is a rebase result. See the full diff and it will be clearer
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqauzy0DMW4IU36yajc:-NqawUZj9PTfW8Fw5QsX:b-nrmo03) ([raw file](https://github.com/starkware-libs/papyrus/blob/e13238b4261c1dba0f9a341dd0260d839892a2a3/crates/papyrus_node/src/bin/dump_config.rs#L72)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do we still need this extra code? We don't dump default config for no rpc anymore, right?
</blockquote></details>

Yes, as the destination of the pointers changes between the features. This has nothing to do with the default config

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqb9kPw5fJUq9li_a3N:-Nqb9kPw5fJUq9li_a3O:bgb4436) ([raw file](https://github.com/starkware-libs/papyrus/blob/0801a30cbd27bb0bd89960c9417a91cc3d347df4/crates/papyrus_node/src/bin/dump_config.rs#L6)):*
> ```XML
> 
> #[cfg(feature = "rpc")]
> use lazy_static::lazy_static;
> ```

Put everything in a module and use `#[cfg(feature = "rpc")]` on the whole thing

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqb9kPw5fJUq9li_a3N:-NqbByeF0LmVfUX0Owj3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0801a30cbd27bb0bd89960c9417a91cc3d347df4/crates/papyrus_node/src/bin/dump_config.rs#L6)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Put everything in a module and use `#[cfg(feature = "rpc")]` on the whole thing
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqb9kPw5fJUq9li_a3N:-NqbDqzf7XZQ6MfQ4VhF:b5ptlcc) ([raw file](https://github.com/starkware-libs/papyrus/blob/0801a30cbd27bb0bd89960c9417a91cc3d347df4/crates/papyrus_node/src/bin/dump_config.rs#L6)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in the same file but I guess that's fine.
Also make a function that will be called in `main` so all the `use` statements can be in the module too

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Nqb9kPw5fJUq9li_a3N:-NqbGgq4B_1omas_fpf2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0801a30cbd27bb0bd89960c9417a91cc3d347df4/crates/papyrus_node/src/bin/dump_config.rs#L6)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I meant in the same file but I guess that's fine.
Also make a function that will be called in `main` so all the `use` statements can be in the module too
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-:-NqbH1_N6LzqiN4_KjWd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: all files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`.github/workflows/ci.yml` line 118 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7F-I4EMRHeoMIwtxY:-Ns7F-I4EMRHeoMIwtxZ:b-1oty1u) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/.github/workflows/ci.yml#L118)):*
> ```YAML
> 
>       - run: |
>           cargo test -p papyrus_node --no-default-features
> ```

Can we have something more explicit, like `--no-rpc`



_Code quote:_
```YAML
no-default-features
```
___
*[`crates/papyrus_node/src/main.rs` line 71 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7FbGeCHOUcnYxZ9TC:-Ns7FbGeCHOUcnYxZ9TD:bnie9n9) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/main.rs#L71)):*
> ```XML
>     _storage_reader: StorageReader,
> ) -> anyhow::Result<impl Future<Output = Result<(), JoinError>>> {
>     Ok(futures::future::pending())
> ```

Please explain the difference between this pending and the one imported, sort the multiple pending



_Code quote:_
```XML
(futures::future::pending(
```
___
*[`crates/papyrus_node/src/main.rs` line 100 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7GJAg7WGk4xJNFSZO:-Ns7GJAg7WGk4xJNFSZP:b-mria49) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/main.rs#L100)):*
> ```XML
>         block: PendingBlockOrDeprecated::Current(PendingBlock {
>             parent_block_hash: BlockHash(
>                 GENESIS_HASH.try_into().expect("Failed converting genesis hash to StarkHash"),
> ```

Is it related to this PR?



_Code quote:_
```XML
 GENESIS_HASH.try_into().expect("Failed converting genesis hash to StarkHash"),
```
___
*[`crates/papyrus_node/src/main_test.rs` line 23 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7Gy7Y8xEaTJHd1gOz:-Ns7Gy7Y8xEaTJHd1gP-:bsnhlrq) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/main_test.rs#L23)):*
> ```XML
> 
> #[cfg(not(feature = "rpc"))]
> fn fix_execution_config_path(_config: &mut NodeConfig) {}
> ```

Please explain why RPC and execution are coupled here



_Code quote:_
```XML
#[cfg(feature = "rpc")]
fn fix_execution_config_path(config: &mut NodeConfig) {
    let default_execution_config_path = RpcConfig::default().execution_config;
    config.rpc.execution_config =
        get_absolute_path(default_execution_config_path.to_str().unwrap());
}

#[cfg(not(feature = "rpc"))]
fn fix_execution_config_path(_config: &mut NodeConfig) {}
```
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7ILGWDB8bZ3OHTnoK:-Ns7ILGWDB8bZ3OHTnoL:b-9wg9ak) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/bin/dump_config.rs#L59)):*
> ```XML
>     with_rpc::dump_config();
>     // TODO(shahak): Try to find a way to remove this binary altogether when the feature rpc is
>     // turned off.
> ```

Please check this and otherwise move the inner module into a separate file



_Code quote:_
```XML
    // TODO(shahak): Try to find a way to remove this binary altogether when the feature rpc is
    // turned off.
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 45 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7MM0CEKUI7H6iUphm:-Ns7MM0CEKUI7H6iUphn:b-bt6dor) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/config/mod.rs#L45)):*
> ```XML
> pub struct NodeConfig {
>     #[validate]
>     pub rpc: RpcConfig,
> ```

I would expect this to be conditionally as well



_Code quote:_
```XML
pub rpc: RpcConfig,
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 99 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7Ih7pC-aJY4T9j-eO:-Ns7Ih7pC-aJY4T9j-eP:b94unvl) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/config/mod.rs#L99)):*
> ```XML
> }
> 
> // TODO(shahak): Try to make this config empty.
> ```

What fails?



_Code quote:_
```XML
Try to make this config empty
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`.github/workflows/ci.yml` line 118 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7F-I4EMRHeoMIwtxY:-Nt9tWzX54Z9Rklo5e7l:bllzy1r) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/.github/workflows/ci.yml#L118)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we have something more explicit, like `--no-rpc`
</blockquote></details>

Sadly no https://github.com/rust-lang/cargo/issues/3126
___
*[`crates/papyrus_node/src/main.rs` line 100 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7GJAg7WGk4xJNFSZO:-NtAEXv89eWY_KW1M4Ue:b68psk2) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/main.rs#L100)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is it related to this PR?
</blockquote></details>

Yes. I fixed it by changing starknet api in the Cargo.toml to be with feature testing but I think this shows we shouldn't use this macro here. WDYT?
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7ILGWDB8bZ3OHTnoK:-Nt9w1iQ1YjmUdUoacQ6:b-9gdhys) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/bin/dump_config.rs#L59)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please check this and otherwise move the inner module into a separate file
</blockquote></details>

Looks like someone else moved it to a separate module for me :)
___
*[`crates/papyrus_node/src/config/mod.rs` line 45 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7MM0CEKUI7H6iUphm:-NtA-MTKCkrDSc3Dldoh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/config/mod.rs#L45)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I would expect this to be conditionally as well
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 99 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1689#-Ns7Ih7pC-aJY4T9j-eO:-NtA-Mge-mMdHvu7J3-G:bx6um56) ([raw file](https://github.com/starkware-libs/papyrus/blob/99ace0d5265e7d1ecde2b1bab93faf6527acb1fb/crates/papyrus_node/src/config/mod.rs#L99)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What fails?
</blockquote></details>

Irrelevant due to previous comment

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 5 files at r3, 8 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
