### PR TITLE
chore(test_utils): replace goerli transaction hashes with mainnet

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj3Q2z8Y1uZEjadUie:-Nwj3Q2z8Y1uZEjadUif:by6vrd7) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_common/src/transaction_hash.rs#L119)):*
> ```XML
> // On mainnet, from this block number onwards, there are no deprecated transactions,
> // enabling us to validate against a single hash calculation.
> pub const MAINNET_TRANSACTION_HASH_WITH_VERSION: BlockNumber = BlockNumber(1470);
> ```

after moving the script to common reduce this



_Suggestion:_
```XML
pub(crate)
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj3IRPAiWJRmXAPGHv:-Nwj3IRPAiWJRmXAPGHw:booxliw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L0)):*
move this to common
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4TvjBWqv285ld6Uu:-Nwj4Tvk4a6iF_pfqkVs:b-2z18u) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L84)):*
> ```XML
> 
> /// Function to generate a set of tuples containing transaction type and version
> fn get_all_transaction_types() -> HashSet<TransactionInfo> {
> ```

consider implementing this using the enum `TransactionType` and iterating over the variants: https://stackoverflow.com/questions/21371534/in-rust-is-there-a-way-to-iterate-through-the-values-of-an-enum
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4xVC3TVqVEvxMX3t:-Nwj4xVC3TVqVEvxMX3u:b-fifz0q) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L148)):*
> ```XML
>         MAINNET_TRANSACTION_HASH_WITH_VERSION.0
>     } else {
>         get_current_block_number_with_rpc(&client, node_url.clone()).await?
> ```

naming is a bit confusing. I thought you are getting the block number and an RPC handler



_Suggestion:_
```XML
via/using
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj5FQ77I9cFRp2nmV5:-Nwj5FQ77I9cFRp2nmV6:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L154)):*
> ```XML
>         println!("Processing block number: {}", block_number);
>         let block_transactions_from_rpc =
>             get_block_transactions_with_rpc(&client, node_url.clone(), block_number).await?;
> ```

same



_Code quote:_
```XML
with
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj5Lcp7R4LEsgDCNr5:-Nwj5Lcp7R4LEsgDCNr6:b-6dxwu7) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L155)):*
> ```XML
>         let block_transactions_from_rpc =
>             get_block_transactions_with_rpc(&client, node_url.clone(), block_number).await?;
>         let block_transactions = block_transactions_from_rpc["result"]["transactions"]
> ```

why not do all of this unwrapping in the function `get_block_transaction_with_rpc`?

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj3Q2z8Y1uZEjadUie:-Nwj9fL_EwlXmrsXorau:b-m1p9qr) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_common/src/transaction_hash.rs#L119)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

after moving the script to common reduce this
</blockquote></details>

see comment
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4TvjBWqv285ld6Uu:-NwjAEW7DDiD-HgB8MLK:b-dgob8j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L84)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

consider implementing this using the enum `TransactionType` and iterating over the variants: https://stackoverflow.com/questions/21371534/in-rust-is-there-a-way-to-iterate-through-the-values-of-an-enum
</blockquote></details>

not all enums have the same versions making it easier to hard code it. we could create a greater hashset then what actually exists but this means that the script will always only end when we get to the last block as it wont find transactions with versions that don't yet exist. note that we use a heuristic that jumps between blocks each iteration as older blocks tend to have transactions that we don't see as often in newer blocks, meaning that we don't always get all transactions anyhow.. wdyt?
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4xVC3TVqVEvxMX3t:-Nwj7Ekm9jAhXzS24T1_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L148)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

naming is a bit confusing. I thought you are getting the block number and an RPC handler
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj5FQ77I9cFRp2nmV5:-Nwj7FB76Ec0v4BQrvaR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L154)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj5Lcp7R4LEsgDCNr5:-Nwj9MK0CXcB1Oqp_RY4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L155)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why not do all of this unwrapping in the function `get_block_transaction_with_rpc`?
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj3IRPAiWJRmXAPGHv:-Nwj9NrbCaMgdgCa2FSW:b-idsnpi) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

move this to common
</blockquote></details>

Dan and I discussed that it was better suited as an example of papyrus node usage (two birds)

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4TvjBWqv285ld6Uu:-NwmvWhq0SOMlspbGlwd:b-wkjz7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L84)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

not all enums have the same versions making it easier to hard code it. we could create a greater hashset then what actually exists but this means that the script will always only end when we get to the last block as it wont find transactions with versions that don't yet exist. note that we use a heuristic that jumps between blocks each iteration as older blocks tend to have transactions that we don't see as often in newer blocks, meaning that we don't always get all transactions anyhow.. wdyt?
</blockquote></details>

I think it's fine. worst case you'll run it again with a different increment size
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4xVC3TVqVEvxMX3t:-NwmuVAR7uv0wDPu-vc8:b-ju3kiw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L148)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4TvjBWqv285ld6Uu:-NwmyPrmD-ZmNMFfy0mz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L84)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think it's fine. worst case you'll run it again with a different increment size
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4xVC3TVqVEvxMX3t:-Nwmy3s5EgVMBG934A-F:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L148)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't see the change
</blockquote></details>

Done.

**Review by nagmo-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1937#-Nwj4TvjBWqv285ld6Uu:-NwnjKIa9VpQODbq-dez:bfk5n5h) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef3c3574edc3798f80f5745d250197ee9329536d/crates/papyrus_node/examples/get_transaction_hash.rs#L84)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was referring to the jump between iterations. I actually agree with your feedback about the iteration of the enum variants.
I'm ok with both options.

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1937)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
