### PR TITLE
test(protobuf): add transaction conversion test

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GDZLm9eetDmmmUB6U:-O-GDZLm9eetDmmmUB6V:b-gldr3x) ([raw file](https://github.com/starkware-libs/papyrus/blob/4ddeb63de8cafe2f35d7c409210cc10ac4f90872/crates/papyrus_protobuf/src/converters/transaction_test.rs#L90)):*
> ```XML
>     let mut transaction =
>         starknet_api::transaction::DeclareTransactionV3::get_test_instance(&mut rng);
>     transaction.resource_bounds = ResourceBoundsMapping(
> ```

Reduce code duplication by creating a lazy_static (https://docs.rs/lazy_static/latest/lazy_static/) that contains a ResourceBoundsMapping
___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GDtT64Rg7gvqLPyrK:-O-GDtT64Rg7gvqLPyrL:b3ban6g) ([raw file](https://github.com/starkware-libs/papyrus/blob/4ddeb63de8cafe2f35d7c409210cc10ac4f90872/crates/papyrus_protobuf/src/converters/transaction_test.rs#L208)):*
> ```XML
> }
> 
> fn create_execution_resources() -> ExecutionResources {
> ```

Make this a lazy_static (https://docs.rs/lazy_static/latest/lazy_static/)

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GDZLm9eetDmmmUB6U:-O-GJgXv9dDHYNT7PLou:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4ddeb63de8cafe2f35d7c409210cc10ac4f90872/crates/papyrus_protobuf/src/converters/transaction_test.rs#L90)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Reduce code duplication by creating a lazy_static (https://docs.rs/lazy_static/latest/lazy_static/) that contains a ResourceBoundsMapping
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GDtT64Rg7gvqLPyrK:-O-GJgsh1u5vYx09JQSF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4ddeb63de8cafe2f35d7c409210cc10ac4f90872/crates/papyrus_protobuf/src/converters/transaction_test.rs#L208)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a lazy_static (https://docs.rs/lazy_static/latest/lazy_static/)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GMmH02YGEijxnSrbV:-O-GMmH02YGEijxnSrbW:b-o04jbt) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d8d2150c4639a9bb3a4bbd39727c75cdb575a21/crates/papyrus_protobuf/src/converters/transaction_test.rs#L183)):*
> ```XML
> }
> 
> lazy_static! {
> ```

You can unite the two lazy_static blocks into one block with both consts

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-O-GMmH02YGEijxnSrbV:-O-GNRvp7w9t1bdtaFcH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d8d2150c4639a9bb3a4bbd39727c75cdb575a21/crates/papyrus_protobuf/src/converters/transaction_test.rs#L183)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can unite the two lazy_static blocks into one block with both consts
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2104#-:-O-GNZoC1siQvPiF4bZ-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
