### PR TITLE
Yair/execution/call gw

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/941)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/941#-Nafu8q94iccOre4hqxt:-Nafu8q94iccOre4hqxu:b-chzlrf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3af11f93d5d77a63b1ffa2659e658b68606f0f03/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L480)):*
> ```XML
> }
> 
> impl TryFrom<ExecutionError> for JsonRpcError {
> ```

@EvyatarO Can you please provide a mapping from Blockifier errors to JSON-RPC errors?



_Code quote:_
```XML
impl TryFrom<ExecutionError> for JsonRpcError {
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1838 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/941#-NafueVI8unFUoUERa5M:-NafueVI8unFUoUERa5N:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/3af11f93d5d77a63b1ffa2659e658b68606f0f03/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1838)):*
> ```XML
> 
> #[tokio::test]
> async fn execution() {
> ```





_Suggestion:_
```XML
execution_call
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/941)* status: 1 of 18 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/Cargo.toml` line 11 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/941#-Nafv8SpDFVZ5nrFX3mg:-Nafv8Sq2v8jeS7QH0V6:b-16u2uz) ([raw file](https://github.com/starkware-libs/papyrus/blob/3af11f93d5d77a63b1ffa2659e658b68606f0f03/crates/papyrus_gateway/Cargo.toml#L11)):*
> ```TOML
> anyhow.workspace = true
> base64.workspace = true
> blockifier.workspace = true
> ```

Can we avoid this import?
IMO only the execution should depend on the Blockifier.



_Code quote:_
```TOML
blockifier.workspace = true
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/941)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_gateway/Cargo.toml` line 11 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/941#-Nafv8SpDFVZ5nrFX3mg:-NakpGst3KC2GZdNUztT:bmf7z1o) ([raw file](https://github.com/starkware-libs/papyrus/blob/3af11f93d5d77a63b1ffa2659e658b68606f0f03/crates/papyrus_gateway/Cargo.toml#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we avoid this import?
IMO only the execution should depend on the Blockifier.
</blockquote></details>

Done by `pub use`
___
*[`crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/941#-Nafu8q94iccOre4hqxt:-NakmOy6AXEIEJktlmYq:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3af11f93d5d77a63b1ffa2659e658b68606f0f03/crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs#L480)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@EvyatarO Can you please provide a mapping from Blockifier errors to JSON-RPC errors?
</blockquote></details>

done

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 18 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/941)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 4 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/941#-Nauwc7d37YVsgtsc4OW:-Nauwc7d37YVsgtsc4OX:b54fu81) ([raw file](https://github.com/starkware-libs/papyrus/blob/dbf4fbc3cbe8126bc3eb7d71ebd822185f3a4ba4/crates/papyrus_execution/src/execution_utils.rs#L4)):*
> ```XML
> 
> // Expose the tool for creating entry point selectors from function names.
> pub use blockifier::abi::abi_utils::selector_from_name;
> ```

Is it used only for tests? If so, consider conditional compilation 



_Code quote:_
```XML
pub use blockifier::abi::abi_utils::selector_from_name;
```
___
*[`crates/papyrus_gateway/src/v0_4_0/api/mod.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/941#-NauwFeV9W6WdRkH3Ox6:-NauwFeV9W6WdRkH3Ox7:b-nsjop5) ([raw file](https://github.com/starkware-libs/papyrus/blob/dbf4fbc3cbe8126bc3eb7d71ebd822185f3a4ba4/crates/papyrus_gateway/src/v0_4_0/api/mod.rs#L121)):*
> ```XML
> 
>     /// Executes the entry point of the contract at the given address with the given calldata,
>     /// returns the result (Retdata).
> ```

Delete? Do we have such a type?

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/mod.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/941#-NauwFeV9W6WdRkH3Ox6:-NauxNSr8kVrKPYEygHT:b-trcv4n) ([raw file](https://github.com/starkware-libs/papyrus/blob/dbf4fbc3cbe8126bc3eb7d71ebd822185f3a4ba4/crates/papyrus_gateway/src/v0_4_0/api/mod.rs#L121)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Delete? Do we have such a type?
</blockquote></details>

It's a type of the blockifier, and the execution has more output other than the retdata, so I think it might help to mention that only the retdata is returned.

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/941)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

**Pull request merged**
