### PR TITLE
refactor(consensus): the list of validators is passed expliecitly the SHC

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2237)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2239** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2239?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2237?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2237#-:-O2JxS3h-haBKpTS---t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2237#-:-O2O1pme6jtcZeoSoqUL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2237#-O2O1bY1ARFYoKEbw5Fv:-O2O1bY1ARFYoKEbw5Fw:bgorz3r) ([raw file](https://github.com/starkware-libs/papyrus/blob/9cc64d9e78ab23aff8a194d01caee2dfd053db4e/crates/sequencing/papyrus_consensus/src/lib.rs#L53)):*
> ```XML
>     let validators = context.validators(height).await;
>     let mut shc =
>         SingleHeightConsensus::new(Arc::clone(&context), height, validator_id, validators);
> ```

use context.clone() instead of Arc::clone

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2237)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2237#-O2O1bY1ARFYoKEbw5Fv:-O2OQqS39zTh55W1OJCV:b-1iios0) ([raw file](https://github.com/starkware-libs/papyrus/blob/9cc64d9e78ab23aff8a194d01caee2dfd053db4e/crates/sequencing/papyrus_consensus/src/lib.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use context.clone() instead of Arc::clone
</blockquote></details>

Deleted in next PR so ignoring so I can merge without re-LGTM

**Pull request merged**
