### PR TITLE
test(monitoring): test is_alive of the gateway and the feeder gateway

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1435)

### CODE REVIEW

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1435#-:-NjqEJkO56-2rOQRH8yF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1435#-:-NjrP_HL7H24gtfdqy-_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
