### PR TITLE
feat(JSON-RPC): add starknet_addInvokeTransaction

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(JSON-RPC): use JsonRpcError for write_api errors
- feat(JSON-RPC): add starknet_addInvokeTransaction

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1016)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1016)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1865 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1016#-NbTiMQYC-NyATihx7UD:-NbTiMQYC-NyATihx7UE:bktxa6r) ([raw file](https://github.com/starkware-libs/papyrus/blob/161ad624f2f6b0b838c688de14d642d8c13b5da6/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1865)):*
> ```XML
> 
> #[async_trait]
> trait AddTransactionTest {
> ```

This reduces code duplication with tests of other tx types in a future PR

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1016#-:-NbUIS1b360-GvIEmyH8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
