### PR TITLE
feat(network): pm pasue discovery

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1912)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1912?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1912** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1912?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1911** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1911?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1908** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1908?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1905** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1905?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1912)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-Nvbc3ot5ALpX9_WHP-2:-Nvbc3ou74SeJOj1pJ_e:blvuapa) ([raw file](https://github.com/starkware-libs/papyrus/blob/f3a1b6a48ba4758267aa5cdb4cf466dcbf18f397/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L13)):*
> ```XML
> 
> #[derive(Debug)]
> // #[cfg_attr(test, derive(PartialEq))]
> ```

Erase this. If we'll need it we'll return it
___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-NvbduUM5jpHMd7oNRQg:-NvbduUM5jpHMd7oNRQh:b83bm7v) ([raw file](https://github.com/starkware-libs/papyrus/blob/f3a1b6a48ba4758267aa5cdb4cf466dcbf18f397/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L16)):*
> ```XML
> pub enum Event {
>     NotifyStreamedBytes(streamed_bytes::behaviour::FromOtherBehaviour),
>     NotifyDiscovery(discovery::FromOtherBehaviourEvent),
> ```

Consider splitting this into RequestPauseDiscovery and RequestResumeDiscovery because you don't use the other variants (KadQueryFinished)
Maybe the same is true for SB
___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-NvbeIi18o8r45qrRPrr:-NvbeIi18o8r45qrRPrs:bdwhoim) ([raw file](https://github.com/starkware-libs/papyrus/blob/f3a1b6a48ba4758267aa5cdb4cf466dcbf18f397/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L122)):*
> ```XML
>                         .set_connection_id(Some(connection_id));
>                 } else if self.peers.get(&peer_id).is_none() {
>                     if self.more_peers_needed() {
> ```

IMO you should always add a peer from connection established and after you add it do this check. This way you'll pause discovery at the moment you've connected to the last peer you want and not when discovery gave you a peer you don't want
___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-NvbcE9N6-bi6ZWHHqOO:-NvbcE9N6-bi6ZWHHqOP:bu338fc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f3a1b6a48ba4758267aa5cdb4cf466dcbf18f397/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L125)):*
> ```XML
>                         self.add_peer(P::new(peer_id, endpoint.get_remote_address().clone()))
>                     } else {
>                         // TODO: consider how and in which cases we resume discovery
> ```

IMO you should do this TODO now. Another alternative is to not merge this PR now and I'll continue it later. I don't want to get stuck on the same malicious/buggy peers forever and endless discovery is better than that
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-NvbcKj4AbtO3oIte6n8:-NvbcKj4AbtO3oIte6n9:b-knbln4) ([raw file](https://github.com/starkware-libs/papyrus/blob/f3a1b6a48ba4758267aa5cdb4cf466dcbf18f397/crates/papyrus_network/src/peer_manager/mod.rs#L157)):*
> ```XML
>     }
> 
>     pub fn more_peers_needed(&self) -> bool {
> ```

Make this function private

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1912#-:-Nvet-Lb4zQESIXOeQ2k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1912)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
