### PR TITLE
feat(common): add PendingClasses struct

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1262)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1262)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware, @DvirYo-starkware, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1262#-NgOXvzI9zqHpxejCD1f:-NgOXvzI9zqHpxejCD1g:b-eyiu10) (no related file):*
Cherry-pick of some of the code of #1250   

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1262)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, @yair-starkware, and @yoavGrs)

___
*[`crates/papyrus_common/src/pending_classes.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1262#-NgP4grDAKHN5qiYkw3Q:-NgSzv126HfqOSYdFAg1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b4500b930dccb8d239626a9858a04acbdc8175a2/crates/papyrus_common/src/pending_classes.rs#L35)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Derive default instead
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/pending_classes.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1262#-NgP705H66QtBhoQO8qp:-NgSzcEK9jb6N76tailx:b6ueq32) ([raw file](https://github.com/starkware-libs/papyrus/blob/b4500b930dccb8d239626a9858a04acbdc8175a2/crates/papyrus_common/src/pending_classes.rs#L40)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't know how this struct will be used, but isn't it better to return a reference and clone it outside only when needed?
</blockquote></details>

This is what @DvirYo-starkware wrote in his PR:
Return object and not a reference because there is no use for it and to prevent abuse of long lock.  
Maybe I will change this after implementing the gw side.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1262#-:-NgTKOkR7uit5uWVI45d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @DvirYo-starkware, and @yoavGrs)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @DvirYo-starkware, and @yoavGrs)

**Pull request merged**
