### PR TITLE
test: add testing of pending block for get_block_w_transaction_hashes()

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1302)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1302)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-NhS8V2VBcf9z7SyKVZe:-NhS8V2VBcf9z7SyKVZf:b-jmf4by) ([raw file](https://github.com/starkware-libs/papyrus/blob/add84a7e6116a087601737701c1686929cf27435/crates/papyrus_rpc/src/v0_4_0/block.rs#L24)):*
> ```XML
> }
> 
> #[derive(Debug, Default, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> ```

use auto_impl_get_test_instance and get_test_instance() instead of Default and default()
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 2570 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-NhS8hl-0k5h8sqn9Zso:-NhS8hl-0k5h8sqn9Zsp:bgow2kg) ([raw file](https://github.com/starkware-libs/papyrus/blob/add84a7e6116a087601737701c1686929cf27435/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L2570)):*
> ```XML
> }
> 
> fn get_test_pending_block(transaction_count: usize) -> Block {
> ```

rename to get_test_pending_block_with_transaction_hashes

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1302)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 2570 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-NhS8hl-0k5h8sqn9Zso:-NhSA3mF4pbH4fHRZXj0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/add84a7e6116a087601737701c1686929cf27435/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L2570)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to get_test_pending_block_with_transaction_hashes
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-NhS8V2VBcf9z7SyKVZe:-NhSDEy3792vUEtD0AmT:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/add84a7e6116a087601737701c1686929cf27435/crates/papyrus_rpc/src/v0_4_0/block.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use auto_impl_get_test_instance and get_test_instance() instead of Default and default()
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1302)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 2586 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-NhW5kCv5bZhdcwVVTwB:-NhW32F-EbkDX19d6lGf:b-9dtyhm) ([raw file](https://github.com/starkware-libs/papyrus/blob/d50e9a920fd52a59cbd0b00c526b88122a889a2c/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L2586)):*
> ```XML
>         status: None,
>         transactions: Transactions::Hashes(vec>             TransactionHash::get_test_instance(&mut get_rng(),);
> ```

remove the ,
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 2586 at r2 ([raw file](https://github.com/starkware-libs/papyrus/blob/d50e9a920fd52a59cbd0b00c526b88122a889a2c/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L2586)):*
> ```XML
>         status: None,
>         transactions: Transactions::Hashes(vec![
>             TransactionHash::get_test_instance(&mut get_rng(),);
> ```

Use the same rng in both places instead of calling get_rng twice (create a variable called rng)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1302#-:-NhWYHrc7i_2_8dTAAhs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
