### PR TITLE
feat(execution): calculate transaction hashes for execution

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1140)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Why are there version changes?

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1140)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1140#-NeCIh7aBUYFkHHxrd1F:-NeCIh7aBUYFkHHxrd1G:by83qqq) ([raw file](https://github.com/starkware-libs/papyrus/blob/edeb14e6b8821ec37c017ad1d25418ba70bd947d/crates/papyrus_execution/src/lib.rs#L281)):*
> ```XML
>     /// Applies a non consuming function on the transaction as if it was of type [Transaction] of
>     /// StarknetAPI and returns the result without cloning the original transaction.
>     fn apply_on_transaction<F, T>(self, func: F) -> (Self, T)
> ```

Please add a TODO to refactor this



_Code quote:_
```XML
fn apply_on_transaction<F, T>(self, func: F) -> (Self, T)
```
___
*[`crates/papyrus_rpc/src/v0_4_0/execution_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1140#-NeCJcMh0HW-Z-xCIGUq:-NeCJcMh0HW-Z-xCIGUr:bdfhnqf) ([raw file](https://github.com/starkware-libs/papyrus/blob/edeb14e6b8821ec37c017ad1d25418ba70bd947d/crates/papyrus_rpc/src/v0_4_0/execution_test.rs#L183)):*
> ```XML
> 
>     // TODO(yair): verify this is the correct fee, got this value by printing the result of the
>     // call.
> ```

Can you verify this now? Or better wait for published blockifier crate that matches the deployed environment?



_Code quote:_
```XML
    // TODO(yair): verify this is the correct fee, got this value by printing the result of the
    // call.
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1140)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1140#-NeCHbGs1Wenx1iPJek2:-NeCNayy17eOHt1yQXKQ:bkajphj) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why are there version changes?
</blockquote></details>

Mistake, fixed

___
___
*[`crates/papyrus_execution/src/lib.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1140#-NeCIh7aBUYFkHHxrd1F:-NeCO5qR7NaLcGUCJlX-:buhfhh9) ([raw file](https://github.com/starkware-libs/papyrus/blob/edeb14e6b8821ec37c017ad1d25418ba70bd947d/crates/papyrus_execution/src/lib.rs#L281)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a TODO to refactor this
</blockquote></details>

Done, but I can't think of something better
___
*[`crates/papyrus_rpc/src/v0_4_0/execution_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1140#-NeCJcMh0HW-Z-xCIGUq:-NeCL5Sh7NqH_QlgZxYY:bdywzkw) ([raw file](https://github.com/starkware-libs/papyrus/blob/edeb14e6b8821ec37c017ad1d25418ba70bd947d/crates/papyrus_rpc/src/v0_4_0/execution_test.rs#L183)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you verify this now? Or better wait for published blockifier crate that matches the deployed environment?
</blockquote></details>

I still can't because it is not a transaction from the blockchain but a test setup, so I have nothing to compare it to.
I think we should give up verifying the fee estimation on test setups and verify the fee calculation using the traceTransaction once we use the same version of blockifier.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
