### PR TITLE
refactor(network): use DataOrFin in db executor's Data

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)

### CODE REVIEW

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-_UgmS6jgmCZcResKW:-O-_TuuP00V_3upjG01k:b-qp2an2) ([raw file](https://github.com/starkware-libs/papyrus/blob/6206f999e2b3e50fe183463e1bad5e696623256a/crates/papyrus_network/src/db_executor/mod.rs#L64)):*
> ```XML
>             }
>             Data::StateDiffChunk(maybe_state_diff_chunk) => {
>                 let state_diffs_response =
> ```

suggestion: rename the variable to `data` and use `into` as done above, or change the above conversions to use `from`
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-_V1-tBVfHEFgS4-a6:-O-_V1-u-cH7dY14qW8n:b-fh1lhx) ([raw file](https://github.com/starkware-libs/papyrus/blob/6206f999e2b3e50fe183463e1bad5e696623256a/crates/papyrus_network/src/db_executor/test.rs#L79)):*
> ```XML
>                         Data::BlockHeaderAndSignature(DataOrFin(Some(signed_header))) => {
>                             assert_eq!(signed_header.block_header.block_number.0, i as u64);
>                             assert_eq!(*requested_data_type, DataType::SignedBlockHeader);
> ```

remove this assertion (you already validated it) or add 2 cases to this match and delete the above one

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-_UgmS6jgmCZcResKW:-O-_dft442akcgxUHdCz:by41omh) ([raw file](https://github.com/starkware-libs/papyrus/blob/6206f999e2b3e50fe183463e1bad5e696623256a/crates/papyrus_network/src/db_executor/mod.rs#L64)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

suggestion: rename the variable to `data` and use `into` as done above, or change the above conversions to use `from`
</blockquote></details>

I've changed the above to be like this one
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-_V1-tBVfHEFgS4-a6:-O-_e7pzAHkB68ov495o:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6206f999e2b3e50fe183463e1bad5e696623256a/crates/papyrus_network/src/db_executor/test.rs#L79)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

remove this assertion (you already validated it) or add 2 cases to this match and delete the above one
</blockquote></details>

Done.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-:-O-_fzBBBZrHe4mnApqc:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aKt5984eDuzSRat6_:-O-aKt5A2kBTLRhdjKhg:b3kre) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/mod.rs#L42)):*
> ```XML
> #[derive(Clone)]
> pub enum Data {
>     BlockHeaderAndSignature(DataOrFin<SignedBlockHeader>),
> ```

?



_Suggestion:_
```XML
SignedBlockHeader(DataOrFin<SignedBlockHeader>)
```
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aLLUT3vCT_Fy1PVVH:-O-aLLUT3vCT_Fy1PVVI:bvgs2jl) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/test.rs#L75)):*
> ```XML
>                             assert_eq!(*requested_data_type, DataType::StateDiff);
>                         }
>                     }
> ```

This is separate because of the none case?



_Code quote:_
```XML
                    match &data {
                        Data::BlockHeaderAndSignature(_) => {
                            assert_eq!(*requested_data_type, DataType::SignedBlockHeader);
                        }
                        Data::StateDiffChunk(_) => {
                            assert_eq!(*requested_data_type, DataType::StateDiff);
                        }
                    }
```
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aLRn567xPkMNXkM81:-O-aLRn567xPkMNXkM82:b-olivzl) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/test.rs#L85)):*
> ```XML
>                         _ => {
>                             assert_eq!(i, len - 1);
>                         }
> ```

WDYT of this instead of 2 matches (safe for StateDiff)



_Suggestion:_
```XML
                    match data {
                        Data::BlockHeaderAndSignature(DataOrFin(maybe_header)) => {
                            assert_eq!(*requested_data_type, DataType::SignedBlockHeader);
                            if let Some(header) = maybe_header {
                                assert_eq!(header.block_header.block_number.0, i as u64);
                            }
                        }
                        Data::StateDiffChunk(DataOrFin(Some(_state_diff)))  => {
                            // TODO: check the state diff.
                        }
                        _ => {
                            assert_eq!(i, len - 1);
                        }
```
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aMs2tCU5hNGZzIe5G:-O-aMs2u-3XSd5KDl7X5:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/network_manager/test.rs#L149)):*
> ```XML
>             protobuf::BlockHeadersResponse::decode(&data[..]).unwrap(),
>         )
>         .unwrap();
> ```





_Suggestion:_
```XML
        let data: DataOrFin<SignedBlockHeader> =
            protobuf::BlockHeadersResponse::decode(&data[..]).unwrap().try_into().unwrap();
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aKt5984eDuzSRat6_:-O-deew92tLzRzhG-DXx:b-doa5jz) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/mod.rs#L42)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

You're right, but this enum is going to be erased in the next PR and I prefer avoiding more conflicts if the change isn't going to last anyway
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aLLUT3vCT_Fy1PVVH:-O-df89sB9zxnBNh6aCI:b2nign6) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/test.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is separate because of the none case?
</blockquote></details>

yes
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aLRn567xPkMNXkM81:-O-df3L3AyseEJu0easu:blwe027) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/db_executor/test.rs#L85)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

WDYT of this instead of 2 matches (safe for StateDiff)
</blockquote></details>

I actually like the two matches, and we plan to fill this TODO at some point
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aMs2tCU5hNGZzIe5G:-O-dffAyEMa4rPlYkbiu:b4kts2h) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/network_manager/test.rs#L149)):*
> ```XML
>             protobuf::BlockHeadersResponse::decode(&data[..]).unwrap(),
>         )
>         .unwrap();
> ```

Why? Gilad's style guide says to prefer try_from over try_into if possible (IMO we should use try_into only if the type can be deduced without writing it)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2113)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2113#-O-aMs2tCU5hNGZzIe5G:-O-eetSU8a6QrgxaBUJb:bzb2x0z) ([raw file](https://github.com/starkware-libs/papyrus/blob/eb6b58e530deda35682fc407eafd9a48a3d89c14/crates/papyrus_network/src/network_manager/test.rs#L149)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why? Gilad's style guide says to prefer try_from over try_into if possible (IMO we should use try_into only if the type can be deduced without writing it)
</blockquote></details>

If that's what the style guide says then sure. I'm surprised it can't be deduced from:

```
        data_sender.unbounded_send(Data::BlockHeaderAndSignature(data)).unwrap();
```

**Pull request merged**
