### PR TITLE
fix(sync): sleep when sync receives None and remove timeout hack

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1800)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1800)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshKz6R7Q2OQAPU5mQK:-NshKz6R7Q2OQAPU5mQL:b-81sbuv) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L41)):*
> ```XML
>                 "wait_period_for_new_data",
>                 &self.wait_period_for_new_data.as_secs(),
>                 "Time in seconds to wait when a query returned with partial data before sending a \
> ```

I liked better the old phrasing. you're not sure it's **returned** with partial..
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshL4GL-o-tzuh_lYaR:-NshL4GL-o-tzuh_lYaS:bs47nue) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L69)):*
> ```XML
>     // TODO(shahak): Move this error to network.
>     WrongSignaturesLength { signatures: Vec<BlockSignature> },
>     #[error("Network returned more responses than expected for a query.")]
> ```

add a todo here to remove this error once we can handle it
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshLHzjAal27g94Pw4r:-NshLHzjAal27g94Pw4s:b4mdnwe) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L111)):*
> ```XML
>         loop {
>             if matches!(control, P2PSyncControl::QueryFinishedPartially) {
>                 debug!(
> ```

I don't think we need this debug.. up to you 
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshLQJO-JCKcocKv2wq:-NshLQJO-JCKcocKv2wr:boyvsoj) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L142)):*
> ```XML
>         while current_block_number.0 < end_block_number {
>             let maybe_signed_header_stream_result =
>                 self.response_receivers.signed_headers_receiver.next().await;
> ```

what if it never joins?

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1800)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshLQJO-JCKcocKv2wq:-Nslv35h04cT-pNnHvTY:b-8o0xmo) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L142)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Then the sync will be stuck too, and that is the expected behaviour
</blockquote></details>

as discessed f2f

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-:-NsmMv6KDsoL3tP4mxsQ:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1800)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @nagmo-starkware)

___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1800#-NshLQJO-JCKcocKv2wq:-NslwmwB2D5B_Rv3sbtO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/436be8fe8af4d544ad13341b5e67030ee2deedd4/crates/papyrus_p2p_sync/src/lib.rs#L142)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

as discessed f2f
</blockquote></details>

Done.

**Pull request merged**
