### PR TITLE
docs: readme update

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #888** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/888" target="_blank">Graphite</a> 
    * **PR #877** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/877" target="_blank">Graphite</a> 
      * **PR #916** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/916" target="_blank">Graphite</a>  👈
      * **PR #915** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/915" target="_blank">Graphite</a> 
      * **PR #914** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/914" target="_blank">Graphite</a> 
      * **PR #881** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/881" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/916?utm_source=stack-comment).

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #888** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/888" target="_blank">Graphite</a> 
    * **PR #877** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/877" target="_blank">Graphite</a> 
      * **PR #916** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/916" target="_blank">Graphite</a>  👈
      * **PR #915** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/915" target="_blank">Graphite</a> 
      * **PR #914** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/914" target="_blank">Graphite</a> 
      * **PR #881** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/881" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/916?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaH5iiZ7LScvoDsvYGs:-NaH5iiZ7LScvoDsvYGt:b4wtq8a) ([raw file](https://github.com/starkware-libs/papyrus/blob/49fcbeb6343c4c432333c7dcff60cfb4a4421b9c/README.md#L134)):*
> ```Markdown
> * V0_4_0
> Assuming the node is exposed at `local-host:8080` one might send requests via curl with:
> `curl --location 'localhost:8080/rpc/V0_3_0' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":0,"method":"starknet_blockHashAndNumber"}'`
> ```

Put this in a code block and not code line (
```
text
```
instead of `text`
___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaH60IY9oXXExdzXOih:-NaH60IY9oXXExdzXOii:b-14e0b8) ([raw file](https://github.com/starkware-libs/papyrus/blob/49fcbeb6343c4c432333c7dcff60cfb4a4421b9c/README.md#L134)):*
> ```Markdown
> * V0_4_0
> Assuming the node is exposed at `local-host:8080` one might send requests via curl with:
> `curl --location 'localhost:8080/rpc/V0_3_0' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":0,"method":"starknet_blockHashAndNumber"}'`
> ```

Choose a method that receives one argument and add the argument to the example

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaH60IY9oXXExdzXOih:-NaHBpPh-Ai-bWLDNppq:b-5h59ip) ([raw file](https://github.com/starkware-libs/papyrus/blob/49fcbeb6343c4c432333c7dcff60cfb4a4421b9c/README.md#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Choose a method that receives one argument and add the argument to the example
</blockquote></details>

I picked this on purpose. I looked for something as small as possible. my intention is not to show how to use curl or json rpc but to show the path to send requests to

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaH60IY9oXXExdzXOih:-NaL1C0r53Luo2zqXhpd:bbyp6lk) ([raw file](https://github.com/starkware-libs/papyrus/blob/49fcbeb6343c4c432333c7dcff60cfb4a4421b9c/README.md#L134)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I picked this on purpose. I looked for something as small as possible. my intention is not to show how to use curl or json rpc but to show the path to send requests to
</blockquote></details>

If that's your purpose, then you can just say that you can query the node at the URL `localhost:8080/rpc/V0_3_0`

**Review by ShahakShama — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`README.md` line 133 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaL1ggU93FmGJuhC6Gh:-NaL1ggU93FmGJuhC6Gi:bsoauvp) ([raw file](https://github.com/starkware-libs/papyrus/blob/0f4bd2b8df9e619f1056b3230c824fb06566b49a/README.md#L133)):*
> ```Markdown
> * V0_3_0
> * V0_4_0
> Assuming the node is exposed at `local-host:8080` one might send requests via curl with:
> ```

local-host -> localhost

**Comment by dan-starkware** [comment]
*[`README.md` line 132 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaLMniLCN2MYZ7ezybR:-NaLMniM5tKa454xi4ql:bcbj617) ([raw file](https://github.com/starkware-libs/papyrus/blob/521c14e475344585b4a3bd3217b8960dd5d1111e/README.md#L132)):*
> ```Markdown
> Current supported versions are:
> * V0_3_0
> * V0_4_0
> ```

Consider:
* Add a reference to the spec
* No patch here



_Code quote:_
```Markdown
Current supported versions are:
* V0_3_0
* V0_4_0
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaLN47c4UFJTxF_IOzq:-NaLN47c4UFJTxF_IOzr:bh1q6v5) (no related file):*
I think this PR should be merged only after we wire v4

___

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaLN47c4UFJTxF_IOzq:-NbnCGLw0RujoSWJLs-F:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I think this PR should be merged only after we wire v4
</blockquote></details>

Done.

___
___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NaH60IY9oXXExdzXOih:-NbnCKeb8Ynum1rOV3RD:b-fqcztz) ([raw file](https://github.com/starkware-libs/papyrus/blob/49fcbeb6343c4c432333c7dcff60cfb4a4421b9c/README.md#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If that's your purpose, then you can just say that you can query the node at the URL `localhost:8080/rpc/V0_3_0`
</blockquote></details>

I think this is a good example. if you disagree let's talk

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916#-:-NbnDKnPDn48xnDr5yfZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`README.md` line 136 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NbonIB7ATgnSaKuEZRi:-NbonIB7ATgnSaKuEZRj:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/083a4b539096bbbeb5eabfb4c58fbec0ed0d66d3/README.md#L136)):*
> ```Markdown
> 
> 
> See spec at: [starknet-specs repo](https://github.com/starkware-libs/starknet-specs/)  
> ```





_Suggestion:_
```Markdown
See specification at: [starknet-specs repo](https://github.com/starkware-libs/starknet-specs/).
```
___
*[`README.md` line 140 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/916#-Nbonu7V2y324RhirccH:-Nbonu7V2y324RhirccI:b-ensghj) ([raw file](https://github.com/starkware-libs/papyrus/blob/083a4b539096bbbeb5eabfb4c58fbec0ed0d66d3/README.md#L140)):*
> ```Markdown
> ```bash
> curl --location 'localhost:8080/rpc/v0_3' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":0,"method":"starknet_blockHashAndNumber"}'
> ```
> ```

Consider breaking the code to multiple lines so reader won't have to scroll.



_Code quote:_
```Markdown
Assuming the node is exposed at `localhost:8080` one might send requests via curl with:
```bash
curl --location 'localhost:8080/rpc/v0_3' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":0,"method":"starknet_blockHashAndNumber"}'
```
```
___
*[`README.md` line 178 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/916#-NbookT6AMziXZgqNkPV:-NbookT6AMziXZgqNkPW:bt8ak6t) ([raw file](https://github.com/starkware-libs/papyrus/blob/083a4b539096bbbeb5eabfb4c58fbec0ed0d66d3/README.md#L178)):*
> ```Markdown
> ## Deployment
> We provide a helm chart for deploying the node to a kubernetes cluster.
> It is located under the deployments folder.
> ```

Consider something like, if a folder doesn't work you can use the README



_Suggestion:_
```Markdown
[deployments folder](deployments/helm)
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/916#-:-Nbs7IUC4pWieAkP8mCX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
