### PR TITLE
chore(consensus): reuse db and prevent InsufficientPeers error

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)* status: all files reviewed, 11 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 139 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TPH5455Z1HHZcXKvU:-O2TPH5455Z1HHZcXKvV:bja6p0k) ([raw file](https://github.com/starkware-libs/papyrus/blob/2db883be016615ed376a2349c3f7c9478fd49707/crates/sequencing/papyrus_consensus/run_consensus.py#L139)):*
> ```Python
>     # 1. The bootnode (validator 1) is started first for network peering.
>     # 2. Validators 2+ are started next to join the network through the bootnode.
>     # 3. Validator 0, which is the proposer, is started last so the validators don't miss the proposals.
> ```

Why did you remove this?



_Code quote:_
```Python
    # Validators are started in a specific order to ensure proper network formation:
    # 1. The bootnode (validator 1) is started first for network peering.
    # 2. Validators 2+ are started next to join the network through the bootnode.
    # 3. Validator 0, which is the proposer, is started last so the validators don't miss the proposals.
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TUdKe2HG15uE3ymTe:-O2TUdKe2HG15uE3ymTf:brqq1t8) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L149)):*
> ```Python
>     return nodes
> 
> def acquire_lock(data_dir):
> ```

Have you tested this both succeeding and failing?



_Code quote:_
```Python
def acquire_lock(data_dir):
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVlthBfZ9g1FCDGxc:-O2TVlthBfZ9g1FCDGxd:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L165)):*
> ```Python
>     logs_dir = tempfile.mkdtemp()
> 
>     if db_dir:
> ```





_Suggestion:_
```Python
    if db_dir is not None:
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVDsw5CYt-vyPULVw:-O2TVDsw5CYt-vyPULVx:b-r27mxk) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L166)):*
> ```Python
> 
>     if db_dir:
>         assert os.path.exists(db_dir), f"The specified directory {db_dir} does not exist."
> ```

listdir triggers `FileNotFoundError` which I think is descriptive enough.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 167 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVG0o0bZcVmL6ExKa:-O2TVG0o0bZcVmL6ExKb:bw7ggu6) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L167)):*
> ```Python
>     if db_dir:
>         assert os.path.exists(db_dir), f"The specified directory {db_dir} does not exist."
>         data_dirs = [d for d in os.listdir(db_dir) if os.path.isdir(os.path.join(db_dir, d))]
> ```

Just create here as a set.



_Suggestion:_
```Python
        data_dirs = {d for d in os.listdir(db_dir) if os.path.isdir(os.path.join(db_dir, d))}
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 172 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVM4xDeluuTED2MJr:-O2TVM4xDeluuTED2MJs:bldl7c0) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L172)):*
> ```Python
>         assert (
>             len(data_dirs) == num_validators
>         ), f"The specified directory {db_dir} must contain exactly {num_validators} validator directories."
> ```

This is not needed based on the `expected_dirs` check below.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 176 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVSK_7evN_cC9qPjO:-O2TVSK_7evN_cC9qPjP:bg4u1jk) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L176)):*
> ```Python
>         # Ensure the directories are named data0, data1, ..., data{num_validators - 1}
>         expected_dirs = {f"data{i}" for i in range(num_validators)}
>         actual_dirs = set(data_dirs)
> ```

Create as set above
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TTCfV20hFQ4oly0jG:-O2TTCfV20hFQ4oly0jH:bdjw98r) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L180)):*
> ```Python
>         assert (
>             expected_dirs == actual_dirs
>         ), f"The directories in {db_dir} must be named {', '.join(expected_dirs)}."
> ```

We want to know that there are enough db folders. We don't care if there are also other folders.



_Suggestion:_
```Python
        assert (
            expected_dirs.issubset(actual_dirs)
        ), f"The directories in {db_dir} must be named {', '.join(expected_dirs)}."
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TWSTL9btROKiUVNEe:-O2TWSTM91k2dtHQST5R:bdeiks6) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L187)):*
> ```Python
> 
>     # Acquire lock on the db_dir
>     lock_fd = acquire_lock(db_dir)
> ```

Using __enter__ and __exit__ to enable a with statement is a more pythonic way. Means you don't need to put the close explicitly here.



_Suggestion:_
```Python
with LockFile(db_dif) as lockfile:
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 209 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TRXpy5sCsSQF7TSun:-O2TRXpz5x45feoTF7--:bayxn9j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L209)):*
> ```Python
>     parser.add_argument("--base_layer_node_url", required=True)
>     parser.add_argument("--num_validators", type=int, required=True)
>     parser.add_argument("--db_dir", required=False, default=None)
> ```

Let's add a description:

Directory with existing DBs that this simulation can reuse.



_Code quote:_
```Python
    parser.add_argument("--db_dir", required=False, default=None)
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TWvJw7KPF-Bu04mh_:-O2TWvJw7KPF-Bu04mha:b3tl4ru) ([raw file](https://github.com/starkware-libs/papyrus/blob/a76a40940aa6186acd729e5c7ec0683f91c01ece/crates/sequencing/papyrus_consensus/src/lib.rs#L116)):*
> ```XML
> {
>     // Add a short delay to allow peers to connect and avoid "InsufficientPeers" error
>     tokio::time::sleep(std::time::Duration::from_secs(5)).await;
> ```

Let's make this part of the consensus config.



_Code quote:_
```XML
    // Add a short delay to allow peers to connect and avoid "InsufficientPeers" error
    tokio::time::sleep(std::time::Duration::from_secs(5)).await;
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 139 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TPH5455Z1HHZcXKvU:-O2TXjyr-u1nixYRGvmQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2db883be016615ed376a2349c3f7c9478fd49707/crates/sequencing/papyrus_consensus/run_consensus.py#L139)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why did you remove this?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TUdKe2HG15uE3ymTe:-O2TiV6d0IilpWTx6pYh:bgbzowk) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L149)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Have you tested this both succeeding and failing?
</blockquote></details>

Yes, I have run simulations with the following cases:
1. without db_dir.
2. reuse an existing db_dir with a single simulation.
3. used an invalid db_dir that either doesn't exist or doesn't have the required data dirs.
4. ran multiple simulations simultaneously using the same db_dir.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVlthBfZ9g1FCDGxc:-O2TXj9MBfFEs3cHDR8e:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L165)):*
> ```Python
>     logs_dir = tempfile.mkdtemp()
> 
>     if db_dir:
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVDsw5CYt-vyPULVw:-O2TZDCjBnmSqo6vpuwg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L166)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

listdir triggers `FileNotFoundError` which I think is descriptive enough.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 167 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVG0o0bZcVmL6ExKa:-O2TXi_4AEz5smFY4nwB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L167)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Just create here as a set.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 172 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVM4xDeluuTED2MJr:-O2TXv9x58Mav-r2MBZd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L172)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is not needed based on the `expected_dirs` check below.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 176 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TVSK_7evN_cC9qPjO:-O2TXwBVBg5JgJWNfzRN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L176)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Create as set above
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 180 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TTCfV20hFQ4oly0jG:-O2U45xB0-1bOSGvFf-J:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L180)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We want to know that there are enough db folders. We don't care if there are also other folders.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TWSTL9btROKiUVNEe:-O2UBB8f9i331nkOk3Na:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L187)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Using __enter__ and __exit__ to enable a with statement is a more pythonic way. Means you don't need to put the close explicitly here.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 209 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TRXpy5sCsSQF7TSun:-O2TYTRMBaqZ0KfxyCxb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L209)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's add a description:

Directory with existing DBs that this simulation can reuse.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TWvJw7KPF-Bu04mh_:-O2UBDM08IjiUQsDsbkI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a76a40940aa6186acd729e5c7ec0683f91c01ece/crates/sequencing/papyrus_consensus/src/lib.rs#L116)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's make this part of the consensus config.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)* status: all files reviewed, 7 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TUdKe2HG15uE3ymTe:-O2UDhTVB2j0NtFNRgYH:b-l8xzkm) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L149)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Yes, I have run simulations with the following cases:
1. without db_dir.
2. reuse an existing db_dir with a single simulation.
3. used an invalid db_dir that either doesn't exist or doesn't have the required data dirs.
4. ran multiple simulations simultaneously using the same db_dir.
</blockquote></details>

Great.

Have you tried running multiple simulations simultaneously correctly (different db_dir)?
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 38 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UFdMu07RnjeeIZQVN:-O2UFdMu07RnjeeIZQVO:b-e1re2p) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L38)):*
> ```Python
>         command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
>         result = subprocess.run(command, shell=True, capture_output=True, text=True)
>         # returns the most recently decided height, or None if node is not ready or consensus has not yet reached any height.
> ```

This line is too long.



_Code quote:_
```Python
        # returns the most recently decided height, or None if node is not ready or consensus has not yet reached any height.
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 186 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UEjZB8X47kr9FIWHe:-O2UEjZB8X47kr9FIWHf:b1v8q4b) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L186)):*
> ```Python
>         actual_dirs = {d for d in os.listdir(db_dir) if os.path.isdir(os.path.join(db_dir, d))}
> 
>         # Ensure the directories are named data0, data1, ..., data{num_validators - 1}
> ```

Let's just delete this and the empty line above. I think it's obvious enough from he code, and we can see the `else` right here where we originally created them.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 203 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UF9CzEDIOQtAbomAf:-O2UF9D-67uE41B8mwnQ:bhc6ake) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L203)):*
> ```Python
>         print(
>             f"Output files will be stored in: {logs_dir} and data files will be stored in: {db_dir}"
>         )
> ```

I think it's easier to read these on 2 separate lines (see how you feel actually running the script).



_Suggestion:_
```Python
        print(f"DB files will be stored in: {db_dir}")
        print(f"Logs will be stored in: {logs_dir}")
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 27 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UG9PZEi-yonzUeD3i:-O2UG9PZEi-yonzUeD3j:bisaw7d) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/config.rs#L27)):*
> ```XML
>     pub num_validators: u64,
>     /// The delay in seconds before starting consensus to prevent InsufficientPeers error.
>     pub consensus_delay: u64,
> ```

Can you put a Duration in a config?



_Suggestion:_
```XML
Duration
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UGMnS-MHOqJDhr4mm:-O2UGMnS-MHOqJDhr4mn:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/config.rs#L61)):*
> ```XML
>                 &self.consensus_delay,
>                 "The delay in seconds before starting consensus to prevent 'InsufficientPeers' \
>                  error.",
> ```





_Suggestion:_
```XML
Delay (seconds) before starting consensus to give time for network peering.
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UGak13MWZWLhFY8GW:-O2UGak13MWZWLhFY8GX:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/lib.rs#L109)):*
> ```XML
>     start_height: BlockNumber,
>     validator_id: ValidatorId,
>     consensus_delay: u64,
> ```





_Suggestion:_
```XML
Duration
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)* status: all files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2TUdKe2HG15uE3ymTe:-O2URt9f9nLI42BE02xh:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a5ce3d0909a2e86c33a0826cf37a087e7ef0d31/crates/sequencing/papyrus_consensus/run_consensus.py#L149)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Great.

Have you tried running multiple simulations simultaneously correctly (different db_dir)?
</blockquote></details>

done
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 38 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UFdMu07RnjeeIZQVN:-O2URsJz4UY3VTu5qwde:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L38)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This line is too long.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 186 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UEjZB8X47kr9FIWHe:-O2UHxuc9UAJiBKzdplI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L186)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's just delete this and the empty line above. I think it's obvious enough from he code, and we can see the `else` right here where we originally created them.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 203 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UF9CzEDIOQtAbomAf:-O2UI9G0DkyP2Wtntr06:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e540b919cd8ac7600b5d955c883184b51d11652/crates/sequencing/papyrus_consensus/run_consensus.py#L203)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think it's easier to read these on 2 separate lines (see how you feel actually running the script).
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 27 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UG9PZEi-yonzUeD3i:-O2URwI-Drxhs817BmLZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/config.rs#L27)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you put a Duration in a config?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UGMnS-MHOqJDhr4mm:-O2US3qy1ViOSJG5pSG0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/config.rs#L61)):*
> ```XML
>                 &self.consensus_delay,
>                 "The delay in seconds before starting consensus to prevent 'InsufficientPeers' \
>                  error.",
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2242#-O2UGak13MWZWLhFY8GW:-O2US4kX4Jh_LOFhui3v:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b97d984cc5d7d4c2a830700d1ab7d847c5814cd6/crates/sequencing/papyrus_consensus/src/lib.rs#L109)):*
> ```XML
>     start_height: BlockNumber,
>     validator_id: ValidatorId,
>     consensus_delay: u64,
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2242)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request closed without merging**
