### PR TITLE
style(common): remove unwraps from production code

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeTdvP76MB48pvY-lH:-NdeTdvP76MB48pvY-lI:b-8rcd06) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs#L223)):*
> ```XML
>             let parent_header: BlockHeader = get_block_header_by_number(&txn, parent_block_number)?;
>             old_root = parent_header.new_root;
>         }
> ```

Consider replacing this code with ok_or_else



_Code quote:_
```XML
        // Get the old root.
        let maybe_parent_block_number = get_block_number(
            &txn,
            BlockId::HashOrNumber(BlockHashOrNumber::Hash(header.parent_hash)),
        );
        let mut old_root =
            GlobalRoot(StarkHash::try_from(GENESIS_HASH).map_err(internal_server_error)?);
        if let Ok(parent_block_number) = maybe_parent_block_number {
            let parent_header: BlockHeader = get_block_header_by_number(&txn, parent_block_number)?;
            old_root = parent_header.new_root;
        }
```
___
*[`crates/starknet_client/src/reader/mod.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeUYHTDh5l2gvlRWDD:-NdeUYHTDh5l2gvlRWDE:b5ca4he) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/starknet_client/src/reader/mod.rs#L232)):*
> ```XML
>         // regenesissed.
>         // Use default value for CasmConractClass that are malformed in the integration environment.
>         if [
> ```

Please add todo to make this array a const

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeTdvP76MB48pvY-lH:-NdedGnP-r_vd0RywH1r:b-dn8cd6) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs#L223)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider replacing this code with ok_or_else
</blockquote></details>

I'm not sure how.
___
*[`crates/starknet_client/src/reader/mod.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeUYHTDh5l2gvlRWDD:-NdefKZP1Gf1hmNJqq6O:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/starknet_client/src/reader/mod.rs#L232)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add todo to make this array a const
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeTdvP76MB48pvY-lH:-NdehnFh9N-CLseb2dv8:b-ee66wu) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs#L223)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm not sure how.
</blockquote></details>

Right, it is not the way...
maybe something like this:
```
let old_root = match get_block_number(
    &txn,
    BlockId::HashOrNumber(BlockHashOrNumber::Hash(header.parent_hash)),
) {
    Ok(parent_block_number) => get_block_header_by_number(&txn, parent_block_number)?.new_root,
    Err(_) => GlobalRoot(StarkHash::try_from(GENESIS_HASH).map_err(internal_server_error)?),
};
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-NdeTdvP76MB48pvY-lH:-NdexEHH6qCbEbwKl4Na:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea6f2115ad703dd696e073254c925b7eebedd763/crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs#L223)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Right, it is not the way...
maybe something like this:
```
let old_root = match get_block_number(
    &txn,
    BlockId::HashOrNumber(BlockHashOrNumber::Hash(header.parent_hash)),
) {
    Ok(parent_block_number) => get_block_header_by_number(&txn, parent_block_number)?.new_root,
    Err(_) => GlobalRoot(StarkHash::try_from(GENESIS_HASH).map_err(internal_server_error)?),
};
```
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143#-:-NdkSNiL14LIcdEnM-oo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
