### PR TITLE
feat(monitoring): report peer id in monitoring gateway

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1809)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1809?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1809** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1786** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1786?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1809)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1809#-NtGcuuIBnH1Ql7SJN-g:-NtGcuuIBnH1Ql7SJN-h:b4z7kg0) (no related file):*
Add this to the readma

___

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1809#-:-NtKCCfz-5cXAMDImaMu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1809#-:-NtLA2aF3tur00xZkunL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1809#-NtLRcMH3Q47H0CVeie7:-NtLRcMH3Q47H0CVeie8:b-dmlgc3) ([raw file](https://github.com/starkware-libs/papyrus/blob/c27ecd83e4ed969916e96267e450b0214036d4ba/crates/papyrus_monitoring_gateway/src/lib.rs#L187)):*
> ```XML
> }
> 
> #[allow(clippy::too_many_arguments)]
> ```

Instead of "allow" and cloning each argument, consider cloning the MonitoringServer and moving it to the app function.
Another option is to try to move the app function inside the MonitoringServer.
Or add todo for now.

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1809)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Pull request merged**
