### PR TITLE
Dvir/save tx status

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na1jtY-D1NsFXgpeUsy:-Na1jtY-D1NsFXgpeUsz:bip51j7) (no related file):*
1. I made minor changes in the gateway just make it compile.
2. Because this pull request is after the serialization change of EntryPointOffset in starknet-api there are two tests in the gateway that fails. The fix is in Nevo pull request. I can rebase this pull request on top of it or fix this in a different pull request.

___
___
*[`crates/papyrus_storage/src/body/mod.rs` line 334 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na1ked55tBHY8wIfAaP:-Na1ked55tBHY8wIfAaQ:b-8yqejb) ([raw file](https://github.com/starkware-libs/papyrus/blob/48762b30d0c6baf37b20fda7fffcb9855f10f0ba/crates/papyrus_storage/src/body/mod.rs#L334)):*
> ```XML
>     block_number: BlockNumber,
> ) -> StorageResult<()> {
>     for index in 0..block_body.transactions.len() {
> ```

This code will panic if the transaction vector and the execution status vector are in different lengths. In the node flow, this will not happen because we pass only a valid block body. I can add a check in the beginning and return an error if the length is different, but I think this is unnecessary.

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #888** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/888" target="_blank">Graphite</a>  👈
    * **PR #877** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/877" target="_blank">Graphite</a> 
      * **PR #881** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/881" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/888?utm_source=stack-comment).

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/body/body_test.rs` line 86 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5mQJLD3JYTca9-mAH:-Na5mQJLD3JYTca9-mAI:bbbx56j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/body_test.rs#L86)):*
> ```XML
> 
>     for (block_number, tx_offset, original_index) in tx_cases {
>         let expected_tx: Option<(
> ```

I think the explicit type is unnecessary.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5lWDZ91CUBOFJGeb1:-Na5lWDZ91CUBOFJGeb2:bq83a3i) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/mod.rs#L35)):*
> ```XML
> //!
> //! let stored_body_transactions = reader.begin_ro_txn()?.get_block_transactions(BlockNumber(0))?;
> //! let expected_transactions_with_exec_statuses = Block::default().body.transactions.into_iter().zip(Block::default().body.transaction_execution_statuses.into_iter()).collect::<Vec<_>>();
> ```

Use the "block" variable instead of creating the "Block::default().body" again.

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 2 of 3 files at r6, 2 of 4 files at r7, 4 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: all files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/transaction.rs` line 22 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5iFNR6wCXuLFh26nm:-Na5iFNR6wCXuLFh26nn:b-lnon32) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_gateway/src/transaction.rs#L22)):*
> ```XML
>         .ok_or_else(|| ErrorObjectOwned::from(JsonRpcError::BlockNotFound))?;
> 
>     Ok(transactions.into_iter().map(|(tx, _)| Transaction::from(tx)).collect())
> ```

consider 



_Suggestion:_
```XML
_execution_status
```
___
*[`crates/papyrus_storage/src/body/body_test.rs` line 89 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5lWmm0238l6J0dDQe:-Na5lWmm0238l6J0dDQf:bhzd0a5) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/body_test.rs#L89)):*
> ```XML
>             starknet_api::transaction::Transaction,
>             starknet_api::transaction::TransactionExecutionStatus,
>         )> = original_index.map(|i| (txs[i].clone(), tx_exec_sts[i].clone()));
> ```

How come now we need the type?



_Code quote:_
```XML
        let expected_tx: Option<(
            starknet_api::transaction::Transaction,
            starknet_api::transaction::TransactionExecutionStatus,
        )> = original_index.map(|i| (txs[i].clone(), tx_exec_sts[i].clone()));
```
___
*[`crates/papyrus_storage/src/body/mod.rs` line 334 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na1ked55tBHY8wIfAaP:-Na5jPBUAO4wLrh4jLvC:b-ceq4h7) ([raw file](https://github.com/starkware-libs/papyrus/blob/48762b30d0c6baf37b20fda7fffcb9855f10f0ba/crates/papyrus_storage/src/body/mod.rs#L334)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This code will panic if the transaction vector and the execution status vector are in different lengths. In the node flow, this will not happen because we pass only a valid block body. I can add a check in the beginning and return an error if the length is different, but I think this is unnecessary.
</blockquote></details>

Please add a ['panic' section](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#commonly-used-sections)
___
*[`crates/papyrus_storage/src/body/mod.rs` line 339 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5kQhU7PJuEIAAjGvR:-Na5kQhU7PJuEIAAjGvS:b-lpfshr) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/mod.rs#L339)):*
> ```XML
>         let transaction_index = TransactionIndex(block_number, tx_offset_in_block);
>         // A transaction must have an execution status.
>         let tx = block_body.transactions[index].clone();
> ```

Can we avoid cloning here?



_Code quote:_
```XML
clone()
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware, @nagmo-starkware, and @yair-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/transaction.rs` line 22 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5iFNR6wCXuLFh26nm:-Na60uVuAoQPme5Vzrhx:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_gateway/src/transaction.rs#L22)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

consider 
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/body/body_test.rs` line 86 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5mQJLD3JYTca9-mAH:-Na60rT-E3H79FV5s7Q5:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/body_test.rs#L86)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think the explicit type is unnecessary.
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/body/mod.rs` line 334 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na1ked55tBHY8wIfAaP:-Na5zTRe6-9om6XVYyto:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/48762b30d0c6baf37b20fda7fffcb9855f10f0ba/crates/papyrus_storage/src/body/mod.rs#L334)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a ['panic' section](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#commonly-used-sections)
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 339 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/888#-Na5kQhU7PJuEIAAjGvR:-Na5yCTiB-bIYQkjpHZT:b67swul) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac332bbef740fb53215b47fc5d2ccb13b6c5b753/crates/papyrus_storage/src/body/mod.rs#L339)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we avoid cloning here?
</blockquote></details>

It will be done.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/888)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @yair-starkware)

**Pull request merged**
