### PR TITLE
Fix bug in reverts (not deleting the events)

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

When reverting a block, the events are not deleted (though they remain unreachable).

Issue Number: N/A

## What is the new behavior?

The events are deleted.

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/485)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_storage/src/body/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/485#-NNGJTt9EelagO4r55Jn:-NNGJTtACrQONdLuG087:bg4f1kl) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bc01b6c2341a520fdff5037df373e619b9f8a60/crates/papyrus_storage/src/body/mod.rs#L226)):*
> ```XML
>         for (offset, tx_hash) in tx_hashes_iter.enumerate() {
>             let tx_index = TransactionIndex(block_number, TransactionOffsetInBlock(offset));
>             if let Some(events) = self.get_transaction_events(tx_index)? {
> ```

It's more efficient to do it like this:
```
let tx_output = self.get_transaction_output(tx_index)?;
for (index, from_address) in tx_output.events_contract_addresses().into_iter().enumerate() {
    key = (event.from_address, EventIndex(tx_index, EventIndexInTransactionOutput(index)));
    events_table.delete(&self.txn, &key)?;
}
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/485)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_storage/src/body/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/485#-NNGJTt9EelagO4r55Jn:-NNGrIGU2vo2RaI9U45M:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bc01b6c2341a520fdff5037df373e619b9f8a60/crates/papyrus_storage/src/body/mod.rs#L226)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

It's more efficient to do it like this:
```
let tx_output = self.get_transaction_output(tx_index)?;
for (index, from_address) in tx_output.events_contract_addresses().into_iter().enumerate() {
    key = (event.from_address, EventIndex(tx_index, EventIndexInTransactionOutput(index)));
    events_table.delete(&self.txn, &key)?;
}
```
</blockquote></details>

Done

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/485#-:-NNHUQ7S1yqyXVNAAvFn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
