### PR TITLE
Documentation for the storage lib file

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-2-wb7eDeo9CCizks:-N_-2-wb7eDeo9CCizkt:b-g5ioph) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L13)):*
> ```XML
> //!
> //! ```rust
> //! use papyrus_storage::{open_storage, StorageReader, StorageWriter, StorageResult};
> ```

Try to remove unnecessary imports.
___
*[`crates/papyrus_storage/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-23tH3vfMV3fUNHPk:-N_-23tH3vfMV3fUNHPl:b1ox9mp) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L15)):*
> ```XML
> //! use papyrus_storage::{open_storage, StorageReader, StorageWriter, StorageResult};
> //! use papyrus_storage::db::DbConfig;
> //! use papyrus_storage::header::{HeaderStorageReader, HeaderStorageWriter};    // Import the header API.
> ```

Consider putting the comments above the relevant line.
___
*[`crates/papyrus_storage/src/lib.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-2Q1J0gXd6PKhnIAl:-N_-2Q1J0gXd6PKhnIAm:b-x7ydmi) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L19)):*
> ```XML
> //!
> //! let db_config: DbConfig;
> //! let (reader, writer) = open_storage(db_config).unwrap();
> ```

Try to run this and make sure it works. This will not compile without the writer will be declared as mut.
___
*[`crates/papyrus_storage/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-NZzxMGzB49z7pC2qDsy:-NZzxMGzB49z7pC2qDsz:b-aua742) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L74)):*
> ```XML
> use crate::version::{VersionStorageReader, VersionStorageWriter};
> 
> /// The current version of the storage crate.
> ```

Consider "database content" instead of "storage crate." This version is different from the version of the storage as a crate.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-2-wb7eDeo9CCizks:-N_-kaV72IZyvWyaXNYG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L13)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Try to remove unnecessary imports.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-23tH3vfMV3fUNHPk:-N_-klON2Gut9yGIbnIf:bfmh0jx) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L15)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider putting the comments above the relevant line.
</blockquote></details>

In most documentations I saw, it is in the same line: https://docs.rs/rand/0.8.5/rand/
___
*[`crates/papyrus_storage/src/lib.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_-2Q1J0gXd6PKhnIAl:-N_-l1Pk6ozQIYby7rYA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L19)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Try to run this and make sure it works. This will not compile without the writer will be declared as mut.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/820#-NZzxMGzB49z7pC2qDsy:-N_-lNnJ1IW7MAtwRkJg:b-tb5u7o) ([raw file](https://github.com/starkware-libs/papyrus/blob/86951b1111d690387c107b351a7371480567a091/crates/papyrus_storage/src/lib.rs#L74)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider "database content" instead of "storage crate." This version is different from the version of the storage as a crate.
</blockquote></details>

I changed it to 'storage code', because it refers to the code being run to read/write the data while existing data can be stored with a different value.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 215 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_3CB6HEbIi5jIxgWHj:-N_3CB6HEbIi5jIxgWHk:bmtgdvy) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e383cdb9fa5e6b525d36bf8f274c0ca510adea7/crates/papyrus_storage/src/lib.rs#L215)):*
> ```XML
> 
> struct_field_names! {
>     struct Tables {
> ```

Please document this as well



_Code quote:_
```XML
struct Tables
```
___
*[`crates/papyrus_storage/src/lib.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_3AvSc7VvEgbMccTcw:-N_3AvSc7VvEgbMccTcx:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e383cdb9fa5e6b525d36bf8f274c0ca510adea7/crates/papyrus_storage/src/lib.rs#L264)):*
> ```XML
> #[derive(thiserror::Error, Debug)]
> pub enum StorageError {
>     /// Errors related to the database.
> ```





_Suggestion:_
```XML
 underlying database
```

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/lib.rs` line 215 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_3CB6HEbIi5jIxgWHj:-N_3HHpe4uDVnbaiRXI9:b9p4gmw) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e383cdb9fa5e6b525d36bf8f274c0ca510adea7/crates/papyrus_storage/src/lib.rs#L215)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document this as well
</blockquote></details>

This is not a public struct.
Do you want me to document it for papyrus developers / forkers?

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/lib.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/820#-N_3AvSc7VvEgbMccTcw:-N_3Lno69UQJqbfUiPcc:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e383cdb9fa5e6b525d36bf8f274c0ca510adea7/crates/papyrus_storage/src/lib.rs#L264)):*
> ```XML
> #[derive(thiserror::Error, Debug)]
> pub enum StorageError {
>     /// Errors related to the database.
> ```

done

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820#-:-N_3MVGXAC1nHmICsxVX:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
