### PR TITLE
feat(network): modify db executor to return results by channel

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1648)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1648?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1628** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1628?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1630** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1630?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1633** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1633?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1648** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1648?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1648?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1648)* status: all files reviewed, 13 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpO_V_O1HSP9VR52mtM:-NpO_V_O1HSP9VR52mtN:b-ysv3g3) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L19)):*
> ```XML
>     db_executor: db_executor::BlockHeaderDBExecutor,
>     buffer_size: usize,
>     query_results_router: StreamCollection,
> ```

consider stream instead of router (and changing the names and comments across the code accordingly)
___
*[`crates/papyrus_network/src/network_manager.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOYUSZ4Jx1gjSE3zMz:-NpOYUSZ4Jx1gjSE3zN-:b8a4qp1) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L22)):*
> ```XML
> }
> 
> impl<'a> NetworkManager {
> ```

Why <'a>
___
*[`crates/papyrus_network/src/network_manager.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOYhzC2doOVbYkr0ti:-NpOYhzC2doOVbYkr0tj:b-npuzyl) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L27)):*
> ```XML
>     pub fn new(swarm: Swarm<Behaviour>, storage_reader: StorageReader) -> Self {
>         let db_executor = db_executor::BlockHeaderDBExecutor::new(storage_reader);
>         Self { swarm, db_executor, buffer_size: 1000, query_results_router: SelectAll::new() }
> ```

SelectAll::new() -> StreamCollection::new()
___
*[`crates/papyrus_network/src/network_manager.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOZ5iz0mDDX8LRBTjU:-NpOZ5iz0mDDX8LRBTjV:bdqt4tp) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L77)):*
> ```XML
>             Event::NewInboundQuery { query, inbound_session_id } => {
>                 debug!(
>                     "Received new inbound query: {query:?} for session id: {inbound_session_id:?}"
> ```

I saw from the pathfinder logs that they write from which peer id did the new query came from. Do you think we should add peer_id just for logging? (anyway not for this PR)
___
*[`crates/papyrus_network/src/network_manager.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOZN2g5Z9lIUEcm-SX:-NpOZN2g5Z9lIUEcm-SY:b-5nromo) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L84)):*
> ```XML
>                     .push(receiver.map(move |data| (data, inbound_session_id)).boxed());
>                 // TODO: use query id for bookkeeping.
>                 // self.query_id_to_inbound_session.insert(query_id, (inbound_session_id,
> ```

You can remove this. I'm not sure that our bookkeeping will look like this and we always have git
___
*[`crates/papyrus_network/src/network_manager.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOZvmx3B4bOsU31zSX:-NpOZvmx3B4bOsU31zSY:b-fcoobe) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L102)):*
> ```XML
>     }
> 
>     fn handle_query_results_routing(&mut self, res: Option<(Data, InboundSessionId)>) {
> ```

Rename to handle_query_result. You have a single result here and you're not routing it here
___
*[`crates/papyrus_network/src/network_manager.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpO_HAMCW-ccbPOOgKY:-NpO_HAMCW-ccbPOOgKZ:b5890gz) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L105)):*
> ```XML
>         match res {
>             None => {
>                 // we're done handling all the queries we had. need to reset the router.
> ```

explain why you need to reset. Maybe something like
```
The results stream is exhausted. We'll create a new empty stream so that it can produce items again
```
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOaEe85HMEJwqQqUqi:-NpOaEe85HMEJwqQqUqj:b-hxcboj) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L52)):*
> ```XML
> }
> 
> pub trait DBExecutor: Stream<Item = Result<QueryId, DBExecutorError>> + Unpin {
> ```

Describe in a comment that the outputted `QueryId`s are finished
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpObP769zGTgC7cyeuv:-NpObP769zGTgC7cyeuw:b-8malho) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L73)):*
> ```XML
> impl DBExecutor for BlockHeaderDBExecutor {
>     fn register_query(&mut self, query: BlockQuery, sender: Sender<Data>) -> QueryId {
>         // TODO: when registering a query we should state what type of data we want to receive.
> ```

Consider removing this TODO given that this struct is called BlockHeaderDBExecutor
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOc6PBBqFwCTGDvvcn:-NpOc6PBBqFwCTGDvvco:b-ithrii) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L76)):*
> ```XML
>         // TODO: consider create a sized vector and increase its size when needed.
>         let query_id = QueryId(self.query_counter);
>         self.query_counter += 1;
> ```

The convention from StreamedData is to call this next_query_id. If you convince me it should be counter I'll rename it in StreamedData
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOcfYM2O1t-ygRQiWJ:-NpOcfYM2O1t-ygRQiWK:b-pe7buk) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L78)):*
> ```XML
>         self.query_counter += 1;
>         let storage_reader_clone = self.storage_reader.clone();
>         let mut sender_clone = sender.clone();
> ```

Why do you clone the sender? You can just move it (and declare it mut in the function declaration)
If the problem is that you don't call any owning function inside the lambda, then try to maybe do `let sender = sender` inside the lambda
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOnvCd5Ql-VYeKJFXW:-NpOnvCd5Ql-VYeKJFXX:b1m42u7) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L81)):*
> ```XML
>         self.query_execution_set.push(tokio::task::spawn(async move {
>             {
>                 for block_counter in 0..=query.limit {
> ```

Consider extracting to a function
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOd7Rz11J2Uos0lP4F:-NpOd7Rz11J2Uos0lP4G:bnself3) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/db_executor/mod.rs#L93)):*
> ```XML
>                         })?
>                         .ok_or(DBExecutorError::BlockNotFound { block_number, query_id })?;
>                     if let Ok(()) = poll_fn(|cx| sender_clone.poll_ready(cx)).await {
> ```

Consider adding the following comment
`// Using poll_fn because Sender::poll_ready is not a future`

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1648)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpO_V_O1HSP9VR52mtM:-NpPlJP0E6Aeg5esVcfM:b-s1r2n2) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L19)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

but it's not just a stream.. it is actually routing the results of the query to the behaviour
</blockquote></details>

I still disagree but I'll pick my fights :)
___
*[`crates/papyrus_network/src/network_manager.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-NpOZvmx3B4bOsU31zSX:-NpPlRPH3YGHaBrHkzDd:b-690jcs) ([raw file](https://github.com/starkware-libs/papyrus/blob/742abf134af552a9c2bd6d863dd0c4b30578e1e7/crates/papyrus_network/src/network_manager.rs#L102)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I disagree.. that is in fact the routing. I get a result and rout it to the behaviour with the right session id.
</blockquote></details>

Then make it non-plural (handle_query_result_routing)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1648#-:-NpPnOktDA1QWNaUdGs0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
