### PR TITLE
refactor(storage): add type for table

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518)* status: 0 of 16 files reviewed, 9 unresolved discussions

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrbeAm-JCp-JlKuw5d:-NlrbeAm-JCp-JlKuw5e:b-hn33qm) (no related file):*
for each table type, we need:
- define an empty struct with the type
- implement a function for DbWriter to create this type of table
- implement the Table trait for TableHandle with this table type
- implement the DbCursorTrait for DbCursor with this table type

I have already done also with the common prefix table type (this includes different logic). when this pull request is approved I will push also the common prefix.

___
___
*[`crates/papyrus_storage/src/serializers.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrZHmbDB49mp0bjsgp:-NlrZHmbDB49mp0bjsgq:b-deu4d8) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/serializers.rs#L443)):*
> ```XML
>     (usize, Vec<Hint>);
>     (usize, Vec<String>);
>     (u32, u32);
> ```

needed for tests
___
*[`crates/papyrus_storage/src/db/db_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrZS_K9mGHr9iA-Ca8:-NlrZS_K9mGHr9iA-Ca9:b-uznvdw) ([raw file](https://github.com/starkware-libs/papyrus/blob/c4e6bdbda1d2cb3cf034263ce84191366444650a/crates/papyrus_storage/src/db/db_test.rs#L105)):*
> ```XML
> 
> #[test]
> fn insert_duplicate_key() {
> ```

this test is now a part of the table_test function
___
*[`crates/papyrus_storage/src/db/mod.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrZofAA9NparX1CDrE:-NlrZofAA9NparX1CDrF:b-by13pb) ([raw file](https://github.com/starkware-libs/papyrus/blob/c4e6bdbda1d2cb3cf034263ce84191366444650a/crates/papyrus_storage/src/db/mod.rs#L300)):*
> ```XML
>     _value_type: PhantomData<V>,
> }
> ```

this code is the implementation of the Table trait for the SimpleTable type
___
*[`crates/papyrus_storage/src/db/mod.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-Nlr_3eO5yjJ6EFfW58k:-Nlr_3eO5yjJ6EFfW58l:b-dclrjf) ([raw file](https://github.com/starkware-libs/papyrus/blob/c4e6bdbda1d2cb3cf034263ce84191366444650a/crates/papyrus_storage/src/db/mod.rs#L368)):*
> ```XML
>     _value_type: PhantomData<V>,
> }
> ```

this code is the implementation of the DbCursorTrait trait for the SimpleTable type
___
*[`crates/papyrus_storage/src/db/table_types/mod.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-Nlr_9Z1-1vVfTA6ecSb:-Nlr_9Z1-1vVfTA6ecSc:bn9zbgb) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/db/table_types/mod.rs#L15)):*
> ```XML
>     type TableType;
> 
>     #[allow(clippy::type_complexity)]
> ```

I can get rid of this by defining:
            type TableDbCursor = DbCursor<'txn, Mode, Self::Key, Self::Value, Self::TableType>;
and move the 'txn to the trait level instead of the function level

I think the current option is better.
___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-Nlr_piyEIofL657k86V:-Nlr_piyEIofL657k86W:btv3xw7) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/db/table_types/simple_table.rs#L44)):*
> ```XML
> }
> 
> impl<'env, K: StorageSerde + Debug, V: StorageSerde + Debug> Table<'env>
> ```

the code here and in the DbCursorTrait implementation is copied, no logical changes were made.
___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-Nlra3aI4UChlCNwfitC:-Nlra3aI4UChlCNwfitD:b-rkwwft) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/db/table_types/simple_table.rs#L169)):*
> ```XML
>     }
> }
> ```

for all table types, the test will look the same.
___
*[`crates/papyrus_storage/src/db/table_types/test_utils.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrakD91WdQv00sPh9w:-NlrakD91WdQv00sPh9x:b-r2fb9n) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/db/table_types/test_utils.rs#L5)):*
> ```XML
> 
> pub(crate) fn table_test<T>(
>     table_id: TableIdentifier<(u32, u32), u32, T>,
> ```

this type of key makes this function good for a table type with a common prefix.
in general, the purpose of those two functions is to be broad enough to test for all the table types.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 16 files at r1, 10 of 14 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518)* status: all files reviewed (commit messages unreviewed), 12 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/serializers.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrZHmbDB49mp0bjsgp:-NousugQEDRuzfkLuNEB:b-7z5h0n) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/serializers.rs#L443)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

needed for tests
</blockquote></details>

Can we do this instead?
```
#[cfg(test)]
auto_storage_serde! {
    (u32, u32);
}
```
___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowAPJ76Yt-NpfOHLhi:-NowAPJ85PH-_vCppMBv:b6g2kpc) ([raw file](https://github.com/starkware-libs/papyrus/blob/056357063a96c0780329a807eb03dace1f220ece/crates/papyrus_storage/src/db/table_types/simple_table.rs#L60)):*
> ```XML
>         &'env self,
>         txn: &'txn DbTransaction<'env, Mode>,
>     ) -> DbResult<DbCursor<'txn, Mode, Self::Key, V, SimpleTable>> {
> ```

Why not Self::Value/TableVariat?



_Suggestion:_
```XML
 V, SimpleTable
 Also below
```
___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowAssh1napKxvqDlbn:-NowAssh1napKxvqDlbo:b2vlgx5) ([raw file](https://github.com/starkware-libs/papyrus/blob/056357063a96c0780329a807eb03dace1f220ece/crates/papyrus_storage/src/db/table_types/simple_table.rs#L144)):*
> ```XML
>     }
> 
>     #[allow(clippy::should_implement_trait)]
> ```

What is the meaning of this?



_Code quote:_
```XML
#[allow(clippy::should_implement_trait)]
```
___
*[`crates/papyrus_storage/src/db/table_types/test_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowBUuC9JPoobQ5H7rz:-NowBUuC9JPoobQ5H7s-:b-a5jzs9) ([raw file](https://github.com/starkware-libs/papyrus/blob/056357063a96c0780329a807eb03dace1f220ece/crates/papyrus_storage/src/db/table_types/test_utils.rs#L9)):*
> ```XML
> type TableValue = NoVersionValueWrapper<u32>;
> 
> pub(crate) fn table_test<T: TableType>(
> ```

Consider splitting into multiple tests.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518)* status: 14 of 17 files reviewed, 11 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowAPJ76Yt-NpfOHLhi:-NoznZJjBHWUj0awO10d:bnk1buy) ([raw file](https://github.com/starkware-libs/papyrus/blob/aac08a3b2e5c348bca833b070c01bf738b8e35dc/crates/papyrus_storage/src/db/table_types/simple_table.rs#L60)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not Self::Value/TableVariat?
</blockquote></details>

I fixed the Self::Value. This implementation is for a specific table type, so we know it and do not need to use a generic name.
___
*[`crates/papyrus_storage/src/db/table_types/simple_table.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowAssh1napKxvqDlbn:-NozomBA-o5shAEZ-LWg:bzie0ie) ([raw file](https://github.com/starkware-libs/papyrus/blob/aac08a3b2e5c348bca833b070c01bf738b8e35dc/crates/papyrus_storage/src/db/table_types/simple_table.rs#L144)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What is the meaning of this?
</blockquote></details>

It was a mistake.
___
*[`crates/papyrus_storage/src/db/table_types/test_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NowBUuC9JPoobQ5H7rz:-NozpC0N-yqgyA_nh416:b-9x4i2j) ([raw file](https://github.com/starkware-libs/papyrus/blob/aac08a3b2e5c348bca833b070c01bf738b8e35dc/crates/papyrus_storage/src/db/table_types/test_utils.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider splitting into multiple tests.
</blockquote></details>

I decided to do it in one test to prevent a long setup in each test. The test is not long or complicated so I think this is fine like this.
___
*[`crates/papyrus_storage/src/serializers.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-NlrZHmbDB49mp0bjsgp:-NozqbX11tveYmuTphbs:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/72cd6f5c95173a7050bad6fb237f9ef3771f065d/crates/papyrus_storage/src/serializers.rs#L443)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we do this instead?
```
#[cfg(test)]
auto_storage_serde! {
    (u32, u32);
}
```
</blockquote></details>

Done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518)* status: all files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1518#-:-Np-ack64GuVgvw4lkKq:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
