### PR TITLE
chore(JSON-RPC): copy v0_6 into v0_7

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1725)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1725#-Nr9viI1B-4HkVKTU3wY:-Nr9viI1B-4HkVKTU3wZ:bhbcipy) ([raw file](https://github.com/starkware-libs/papyrus/blob/b3ffc6a2f6630e238e30e6c11f7570e7745e68ed/crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap#L1)):*
> ```
> ---
> ```

Mistake?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1725)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1725#-Nr9viI1B-4HkVKTU3wY:-Nr9w3ig3q8isaceF1uM:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/b3ffc6a2f6630e238e30e6c11f7570e7745e68ed/crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Mistake?
</blockquote></details>

Done

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 26 of 29 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1725)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/version_config.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1725#-Nr9wYmR4wBkgW8HqBUp:-Nr9wYmR4wBkgW8HqBUq:b-sfuwcn) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ebfd897ce82151c506bccec1acdcd75edfac0b0/crates/papyrus_rpc/src/version_config.rs#L42)):*
> ```XML
>     (VERSION_0_5, VersionState::Supported),
>     (VERSION_0_6, VersionState::Supported),
>     (VERSION_0_7, VersionState::Supported),
> ```

Change and add todo



_Code quote:_
```XML
Supported
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1725)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/version_config.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1725#-Nr9wYmR4wBkgW8HqBUp:-NrAVeSjERuMBqzHI5Xv:b-s79epu) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ebfd897ce82151c506bccec1acdcd75edfac0b0/crates/papyrus_rpc/src/version_config.rs#L42)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Change and add todo
</blockquote></details>

This causes test failures

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1725)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
