### PR TITLE
Add throttling bypass.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/404)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/config/mod.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/404#-NLZtJ4r9M9VxdKxs3yW:-NLZtJ4r9M9VxdKxs3yX:b937zhd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca113bafea160027b1927918451ae42b16f07603/crates/papyrus_node/src/config/mod.rs#L55)):*
> ```XML
>     #[error(transparent)]
>     Serde(#[from] serde_yaml::Error),
>     #[error("Cml http_header \"{illegal_header}\" is not a valid format")]
> ```

Consider:
```
#[error("CLA http_header \"{illegal_header}\" is not valid. The Expected format is name:value")]
    CLAHttpHeader { illegal_header: String },
```



_Code quote:_
```XML
    #[error("Cml http_header \"{illegal_header}\" is not a valid format")]
    CmlHttpHeaderFormat { illegal_header: String },
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r3, 1 of 4 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/404)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_node/src/config/mod.rs` line 7 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/404#-NLZxocD10tUx78F3J85:-NLZxocD10tUx78F3J86:be87j3g) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca113bafea160027b1927918451ae42b16f07603/crates/papyrus_node/src/config/mod.rs#L7)):*
> ```XML
> 
> use std::collections::HashMap;
> use std::env::{args, ArgsOs};
> ```

Why do we need these?



_Code quote:_
```XML
use std::env::{args, ArgsOs};
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/404)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/config/mod.rs` line 7 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/404#-NLZxocD10tUx78F3J85:-NLZz9yw-ABotCavEfbo:b-ehqtap) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca113bafea160027b1927918451ae42b16f07603/crates/papyrus_node/src/config/mod.rs#L7)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need these?
</blockquote></details>

it was added because rebase conflict with yair commit.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/config/mod.rs` line 7 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/404#-NLZxocD10tUx78F3J85:-NL_A1-RBMdmcZktFUac:b7oo03g) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca113bafea160027b1927918451ae42b16f07603/crates/papyrus_node/src/config/mod.rs#L7)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

it was added because rebase conflict with yair commit.
</blockquote></details>

I don't see it in main, please try and remove



_Code quote (from config/config.yaml):_
```YAML
X-Throttling-Bypass: 7559cf8255094addfae700e9c7fb6071831c5243e44
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r3, 1 of 7 files at r9, 5 of 6 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/404#-:-NLpoKBj1D-VjN6iFasZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
