### PR TITLE
feat(consensus): add support in SingleHeightConsensus for votes

### PR DESCRIPTION
**Pull request by matan-starkware**
I don't add tests for votes and proposals coming out of order since that is fundamentally part of
the state machine.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2174?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2174** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2174?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2169** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2169?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2168** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2168?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2167** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2167?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2166** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2166?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2161** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2159** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @asmaastarkware, @matan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 48 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1BwZqDCo-qXUeVLpHT:-O1BwZqDCo-qXUeVLpHU:bq1ju99) ([raw file](https://github.com/starkware-libs/papyrus/blob/9e07282615b82ce8276f619edcd123bf324f3819/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L48)):*
> ```XML
>     ) -> Self {
>         let validators = context.validators(height).await;
>         // TODO(matan): Use actual weight to require voting.
> ```

We still don't use actual weights, only count, right?



_Code quote:_
```XML
 // TODO(matan): Use actual weight to require voting.
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Cj6vcDmTvTcGUzpI4:-O1Cj6vcDmTvTcGUzpI5:bnkftw1) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L141)):*
> ```XML
>             ConsensusMessage::Proposal(_) => {
>                 unimplemented!("Proposals should use `handle_proposal` due to fake streaming")
>             }
> ```

Not sure why this is not handled here. Please add a TODO to consider moving it.



_Code quote:_
```XML
            ConsensusMessage::Proposal(_) => {
                unimplemented!("Proposals should use `handle_proposal` due to fake streaming")
            }
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1CjXCiAykKjhk6YrUg:-O1CjXCiAykKjhk6YrUh:b-5tyavg) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L152)):*
> ```XML
> 
>     async fn handle_prevote(&mut self, vote: Vote) -> Result<Option<BlockT>, ConsensusError> {
>         if let Some(old) = self.prevotes.get(&(0, vote.voter)) {
> ```

Consider using something like a const ROUND_ZERO
This will make fixing/cleaning easier.



_Code quote:_
```XML
0
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Ck4q3-3ly3eaZcTc5:-O1Ck4q3-3ly3eaZcTc6:b-44b7gm) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L170)):*
> ```XML
>     }
> 
>     async fn handle_precommit(&mut self, vote: Vote) -> Result<Option<BlockT>, ConsensusError> {
> ```

This is very similar to handle_prevote, consider (add TODO) refactoring



_Code quote:_
```XML
handle_precommit
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 228 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Cl5cl0lqGeOEozCpY:-O1Cl5cm2W90IYeRtEAW:byquu61) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L228)):*
> ```XML
>             if let Some(block) = res? {
>                 return Ok(Some(block));
>             }
> ```

Do we need this?



_Code quote:_
```XML
            if let Some(block) = res? {
                return Ok(Some(block));
            }
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 284 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Cb4rCELaKraGYHiFb:-O1Cb4rCELaKraGYHiFc:bb3apa2) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L284)):*
> ```XML
>         let vote = Vote { vote_type, height: self.height.0, block_hash, voter: self.id };
>         if let Some(old) = votes.insert((round, self.id), vote.clone()) {
>             panic!("State machine should not send repeat votes: old={:?}, new={:?}", old, vote);
> ```

Do we want to panic here? (as opposed to propagate `ConsensusError`)
How about error level log and a TODO to consider switching to propagating the error for now?



_Code quote:_
```XML
panic!("State machine should not send repeat votes: old={:?}, new={:?}", old, vote);
```

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-:-O1Fh_pZ9KC7ZITQJCMC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 48 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1BwZqDCo-qXUeVLpHT:-O1FrH-n2gCgeDWU6d7h:bxsyxaa) ([raw file](https://github.com/starkware-libs/papyrus/blob/9e07282615b82ce8276f619edcd123bf324f3819/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L48)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We still don't use actual weights, only count, right?
</blockquote></details>

Well implicitly all weights are 1. I should have written "change from using weight of 1 to require votes"
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Cj6vcDmTvTcGUzpI4:-O1G5w5M7D15TEpQ1uB7:b-pvotsa) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L141)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not sure why this is not handled here. Please add a TODO to consider moving it.
</blockquote></details>

I tried a bit and this leads to a lot of rebase conflicts, so I will work on putting this as the end of this PR stack.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Ck4q3-3ly3eaZcTc5:-O1FsfYz2_cx1ZHYOz_E:bepwwkn) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L170)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is very similar to handle_prevote, consider (add TODO) refactoring
</blockquote></details>

I just changed it here. I already did this for the state machine vote.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 284 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-O1Cb4rCELaKraGYHiFb:-O1G3iAxCZTp83hsM05l:b-8in188) ([raw file](https://github.com/starkware-libs/papyrus/blob/03e54772c958726ded6ca3de20ee2927eaf89e37/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L284)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we want to panic here? (as opposed to propagate `ConsensusError`)
How about error level log and a TODO to consider switching to propagating the error for now?
</blockquote></details>

I added a TODO. This is a much larger task than this one place, since every `assert` and `expect` are themselves just wrappers around `panic`. Perhaps converting the consensus crate to this model could be a good task for me to work on with Asmaa?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2174#-:-O1GAGBQDLkxmLqMtoeD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Pull request merged**
