### PR TITLE
feat(ci): add storage benchmark ci job and github pages

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)* status: 2 of 6 files reviewed, all discussions resolved

___
*[`.github/workflows/benchmark.yaml` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxByyBVCOOBa3Ybc8WF:-NxByyBVCOOBa3Ybc8WG:b-n6d6dn) ([raw file](https://github.com/starkware-libs/papyrus/blob/a5d77d64be2d41a4850eb5b7eef3c6fbb96861fc/.github/workflows/benchmark.yaml#L20)):*
> ```YAML
> 
>       # - name: Set a unique run identifier
>       #   run: echo "UNIQE_ID=${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV
> ```

Please remove



_Code quote:_
```YAML
      # - name: Set a unique run identifier
      #   run: echo "UNIQE_ID=${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV
```

**Review by RoeiE-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)* status: 5 of 6 files reviewed, all discussions resolved

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eranreshef-starkware, and @RoeiE-starkware)

___
*[`.github/workflows/benchmark.yaml` line 32 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxI0lqA7RlyMl_MoT7a:-NxI0lqA7RlyMl_MoT7b:bq37hmy) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fd699a97b7959a13068ad88f2ea3e515caed07/.github/workflows/benchmark.yaml#L32)):*
> ```YAML
>           location: "${{ secrets.GKE_CI_CLUSTER_REGION }}"
> 
>       - name: Run load test
> ```

change this to storage benchmark



_Code quote:_
```YAML
- name: Run load test
```
___
*[`deployments/storage-benchmark/cm.yaml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxI1GBj7OJErktvhrRA:-NxI1GBj7OJErktvhrRB:bce3fig) ([raw file](https://github.com/starkware-libs/papyrus/blob/96ca05445e5446ecad6eabd3641f124221aa9ba6/deployments/storage-benchmark/cm.yaml#L3)):*
> ```YAML
> apiVersion: v1
> data:
>   queries.txt: |
> ```

this will be a much bigger file in the future, so maybe we should already give it a path to a file

**Comment by eranreshef-starkware** [comment]
*[`deployments/storage-benchmark/cm.yaml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxI1GBj7OJErktvhrRA:-NxMKmdPBV4ujrMQdIOh:b-7zi8tj) ([raw file](https://github.com/starkware-libs/papyrus/blob/96ca05445e5446ecad6eabd3641f124221aa9ba6/deployments/storage-benchmark/cm.yaml#L3)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

this will be a much bigger file in the future, so maybe we should already give it a path to a file
</blockquote></details>

WDYM?

**Comment by eranreshef-starkware** [comment]
*[`.github/workflows/benchmark.yaml` line 32 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxI0lqA7RlyMl_MoT7a:-NxMLNZO8brSSVfm83MH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/08fd699a97b7959a13068ad88f2ea3e515caed07/.github/workflows/benchmark.yaml#L32)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

change this to storage benchmark
</blockquote></details>

Done.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/storage-benchmark/cm.yaml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxI1GBj7OJErktvhrRA:-NxMiXme9jbQGRK8KjKw:b-e0fkmb) ([raw file](https://github.com/starkware-libs/papyrus/blob/96ca05445e5446ecad6eabd3641f124221aa9ba6/deployments/storage-benchmark/cm.yaml#L3)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

The requests .txt file going to be tens of thousands of rows. I think it will be easier to give just a path to this file (if possible) instead of copying the file content to this config map.

**Review by dan-starkware — APPROVED** [review]

**Review by RoeiE-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-:-NxCvzJH12omKKVWrFHG:bnfp4nl)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/storage-benchmark/cm.yaml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxT-Kun0ymZxeiaGhvx:-NxT-Kuo6_hQN7wf9rOF:bdmi9l3) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b3264b646ab6c677cf9be4e88914ba2ee381592/deployments/storage-benchmark/cm.yaml#L17)):*
> ```YAML
>     {"get_class_hash_at":[121,"0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6"]}
>     {"get_class_hash_at":[121,"0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6"]}
>     {"get_class_hash_at":[201,"0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6"]}
> ```

A lot of lines are repeated here; should that be the case?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @RoeiE-starkware)

___
*[`deployments/storage-benchmark/cm.yaml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-NxT-Kun0ymZxeiaGhvx:-NxftB150vmOghRyfqvo:b2nhswy) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b3264b646ab6c677cf9be4e88914ba2ee381592/deployments/storage-benchmark/cm.yaml#L17)):*
<details><summary><i>Previously, RoeiE-starkware wrote…</i></summary><blockquote>

A lot of lines are repeated here; should that be the case?
</blockquote></details>

Yes

**Review by RoeiE-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1962#-:-NxgGafCAHEd4BvcJYlb:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]

**Pull request merged**
