### PR TITLE
fix(JSON-RPC,execution): look for class hash in replaced classes too

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1476)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1476#-Nkjsh5D4fvemwUkKYWT:-Nkjsh5D4fvemwUkKYWU:b-6rz0g4) ([raw file](https://github.com/starkware-libs/papyrus/blob/e550769e0a34bd305aa811c17e9d4c306461d142/crates/papyrus_execution/src/execution_utils.rs#L203)):*
> ```XML
>     {
>         // Searching first in the replaced classes because if the contract was deployed and
>         // replaced, the replaced class is the contract's class.
> ```

This is not a possible situation (I asked this a long time ago) - the state diff will be built as if the contract was deployed with the replacing class.
Consider merging the classes into a single container.



_Code quote:_
```XML
        // Searching first in the replaced classes because if the contract was deployed and
        // replaced, the replaced class is the contract's class.
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1476#-:-NlHy7hIB_-eDx2MNCHL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1476#-Nkjsh5D4fvemwUkKYWT:-NlI4U2q78VYvgYQ6uc1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e550769e0a34bd305aa811c17e9d4c306461d142/crates/papyrus_execution/src/execution_utils.rs#L203)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is not a possible situation (I asked this a long time ago) - the state diff will be built as if the contract was deployed with the replacing class.
Consider merging the classes into a single container.
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1476)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
