### PR TITLE
feat(sync): store old block's pending until we download pending from new block

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL2HAY9B4W-u8ZVIsS:-NhL2HAY9B4W-u8ZVIsT:b4ve9kc) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_node/src/main.rs#L23)):*
> ```XML
> use papyrus_sync::{StateSync, StateSyncError};
> use starknet_api::block::BlockHash;
> use starknet_api::hash::{StarkFelt, GENESIS_HASH};
> ```

IMO this is chain specific (mainnet / mainnet post regenesis / private SN may all have different genesis hashes)



_Code quote:_
```XML
GENESIS_HASH
```
___
*[`crates/papyrus_node/src/main.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL1rfhCBfSIOZs_v4S:-NhL1rfhCBfSIOZs_v4T:b-wm73x5) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_node/src/main.rs#L56)):*
> ```XML
>             ..Default::default()
>         },
>         ..Default::default()
> ```

Can this be the impl of `PendingData::default()`



_Code quote:_
```XML
        block: PendingBlock {
            parent_block_hash: BlockHash(stark_felt!(GENESIS_HASH)),
            ..Default::default()
        },
        ..Default::default()
```
___
*[`crates/papyrus_sync/src/lib.rs` line 894 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL39l_D87TCxFGPa26:-NhL39l_D87TCxFGPa27:b-crca1g) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_sync/src/lib.rs#L894)):*
> ```XML
>         _ => {
>             txn.get_block_header(
>                 header_marker.prev().expect("Calling prev() on non-zero header marker failed."),
> ```

Consider changing based [on](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style)



_Suggestion:_
```XML
All blocks other than the first block should have a predecessor.
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL2HAY9B4W-u8ZVIsS:-NhLDJwu0SbjLylFUlCB:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_node/src/main.rs#L23)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO this is chain specific (mainnet / mainnet post regenesis / private SN may all have different genesis hashes)
</blockquote></details>

Done
___
*[`crates/papyrus_node/src/main.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL1rfhCBfSIOZs_v4S:-NhLC9Mb1_cSmKkDBcVc:bvf9y30) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_node/src/main.rs#L56)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can this be the impl of `PendingData::default()`
</blockquote></details>

This will be problematic if we have custom genesis hash
___
*[`crates/papyrus_sync/src/lib.rs` line 894 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-NhL39l_D87TCxFGPa26:-NhL9sKLCvJFlTBfOD2_:b9nyxke) ([raw file](https://github.com/starkware-libs/papyrus/blob/6c343bb4d6e619aa2a085945d4f2a60143ca8d19/crates/papyrus_sync/src/lib.rs#L894)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider changing based [on](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style)
</blockquote></details>

I prefer it this way

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291#-:-NhLFake1JJ_sWeVCL-k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
