### PR TITLE
Yair/new contract class

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/550)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 7 of 7 files at r2, 4 of 4 files at r3, 7 of 8 files at r4, 5 of 6 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/550)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @anatgstarkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuGneDBoeaL1PE4thG:-NQuGneDBoeaL1PE4thH:b-hdkgix) (no related file):*
As a general note, I think we shouldn't deal with ommer tables, only return deleted data in reverts. 

___
___
*[`crates/papyrus_gateway/src/lib.rs` line 359 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy-YyLC_F0OYWjYC7s:-NQy-YyLC_F0OYWjYC7t:bpze2pf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/papyrus_gateway/src/lib.rs#L359)):*
> ```XML
>         let state_reader = txn.get_state_reader().map_err(internal_server_error)?;
> 
>         if let Some(class) = state_reader
> ```

Please document briefly



_Code quote:_
```XML
if let Some(class) = state_reader
```
___
*[`crates/papyrus_gateway/src/state.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy0I5Y3QjSiG74nt0M:-NQy0I5Y3QjSiG74nt0N:b-6fkizl) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/papyrus_gateway/src/state.rs#L102)):*
> ```XML
>         Self {
>             sierra_program: class.sierra_program,
>             contract_class_version: "0.1.0".to_owned(),
> ```

This is intentional? 



_Code quote:_
```XML
contract_class_version: "0.1.0".to_owned(),
```
___
*[`crates/papyrus_storage/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuHjmT-77_wGQ30S6H:-NQuHjmT-77_wGQ30S6I:b-sjvljf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/lib.rs#L118)):*
> ```XML
>         block_hash_to_number: TableIdentifier<BlockHash, BlockNumber>,
>         contract_storage: TableIdentifier<(ContractAddress, StorageKey, BlockNumber), StarkFelt>,
>         declared_classes: TableIdentifier<ClassHash, IndexedDeclaredContract>,
> ```

Can we call these classes instead of contracts? (TODO, in a different PR)



_Code quote:_
```XML
IndexedDeclaredContrac
```
___
*[`crates/papyrus_storage/src/serializers.rs` line 270 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuRWUN0oyHE4tqbVQY:-NQuRWUN0oyHE4tqbVQZ:b1o574l) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/serializers.rs#L270)):*
> ```XML
>         pub deployed_contracts: IndexMap<ContractAddress, ClassHash>,
>         pub storage_diffs: IndexMap<ContractAddress, IndexMap<StorageKey, StarkFelt>>,
>         pub declared_classes: IndexMap<ClassHash, CompiledClassHash>,
> ```

This means we store the compiled hash twice, right?
Consider storing it only here.



_Code quote:_
```XML
pub declared_classes: IndexMap<ClassHash, CompiledClassHash>,
```
___
*[`crates/papyrus_storage/src/state/data.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuShjbCnHZ0IH4CGQ5:-NQuShjbCnHZ0IH4CGQ6:b-2bh79f) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/state/data.rs#L9)):*
> ```XML
> use starknet_api::state::{ContractClass, StateDiff, StorageKey};
> 
> pub type DeclaredClasses = IndexMap<ClassHash, (CompiledClassHash, ContractClass)>;
> ```

Do we need the compiled class hash here?



_Code quote:_
```XML
CompiledClassHash
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 377 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQxyF0-9OBdxPSHrTqd:-NQxyF0-9OBdxPSHrTqe:b-u8vxj7) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/state/mod.rs#L377)):*
> ```XML
>     txn: &DbTransaction<'env, RW>,
>     block_number: BlockNumber,
>     declared_classes_table: &'env DeprecatedDeclaredClassesTable<'env>,
> ```

Consider renaming



_Code quote:_
```XML
declared_classes_table: &'env DeprecatedDeclaredClassesTable<'env>,
```
___
*[`crates/starknet_client/src/objects/state.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQtmnXA3-5iRwijfVyX:-NQtmnXA3-5iRwijfVyY:ba3dfna) ([raw file](https://github.com/starkware-libs/papyrus/blob/281bf12d5e2657354e3b08a99969acd34ff2e3b5/crates/starknet_client/src/objects/state.rs#L71)):*
> ```XML
> }
> 
> // TODO(yair): fill the struct.
> ```

Remove?



_Code quote:_
```XML
// TODO(yair): fill the struct.
```
___
*[`crates/starknet_client/src/objects/state.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQtoApjALx5FM41TgPf:-NQtoApjALx5FM41TgPg:b-ncz6e3) ([raw file](https://github.com/starkware-libs/papyrus/blob/281bf12d5e2657354e3b08a99969acd34ff2e3b5/crates/starknet_client/src/objects/state.rs#L91)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct DeclaredClassHashEntry {
> ```

Please document.
Do we need this struct? Can we use a vector of tuples or a mapping from class hash to compiled hash instead?



_Code quote:_
```XML
pub struct DeclaredClassHashEntry {
```
___
*[`crates/starknet_client/src/objects/state.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuBcmL8jlLPBtS_Wyp:-NQuBcmL8jlLPBtS_Wyq:b-ax332p) ([raw file](https://github.com/starkware-libs/papyrus/blob/6a50160c82de027c46bea3f5269c1f413b673306/crates/starknet_client/src/objects/state.rs#L38)):*
> ```XML
> impl StateDiff {
>     // Returns the declared class hashes and after them the deployed class hashes that weren't in
>     // the declared.
> ```

Please edit to accommodate the two type of declared. Consider adding a visualization in the spirit of:
[declared , old declared, deployed]



_Code quote:_
```XML
    // Returns the declared class hashes and after them the deployed class hashes that weren't in
    // the declared.
```
___
*[`crates/test_utils/src/lib.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy1PGr38NYvDCX4L5T:-NQy1PGr38NYvDCX4L5U:bomj7bq) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/test_utils/src/lib.rs#L177)):*
> ```XML
>     let mut rng = ChaCha8Rng::seed_from_u64(0);
>     let mut res = StateDiff::get_test_instance(&mut rng);
>     // TODO(anatg): fix StateDiff::get_test_instance so the declared_classes will have different
> ```

@anatgstarkware 



_Code quote:_
```XML
    // TODO(anatg): fix StateDiff::get_test_instance so the declared_classes will have different
    // hashes than the deprecated_contract_classes.
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/550)* status: 7 of 34 files reviewed, 5 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 359 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy-YyLC_F0OYWjYC7s:-NRRjkrZ-pzAvxWMoPsM:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/papyrus_gateway/src/lib.rs#L359)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document briefly
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/state.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy0I5Y3QjSiG74nt0M:-NRReMo-5JW1jsM5gGD4:bwy2m0w) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/papyrus_gateway/src/state.rs#L102)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is intentional? 
</blockquote></details>

Yes, changed to const
___
*[`crates/papyrus_storage/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuHjmT-77_wGQ30S6H:-NRRefnF3a6KyGa-Gokc:b-iw1i2d) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/lib.rs#L118)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we call these classes instead of contracts? (TODO, in a different PR)
</blockquote></details>

Added todo
___
*[`crates/papyrus_storage/src/serializers.rs` line 270 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuRWUN0oyHE4tqbVQY:-NRRfx739J47yO5ai8tE:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/serializers.rs#L270)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This means we store the compiled hash twice, right?
Consider storing it only here.
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/state/data.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuShjbCnHZ0IH4CGQ5:-NRRgR-11y0Nd3DmQtDK:ba3dfob) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/state/data.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need the compiled class hash here?
</blockquote></details>

Removed
___
*[`crates/papyrus_storage/src/state/mod.rs` line 377 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQxyF0-9OBdxPSHrTqd:-NRRh9HK5JrhlVQhWbhy:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d82f2e68b6199c5448ba7004cc46ad7d656f095f/crates/papyrus_storage/src/state/mod.rs#L377)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider renaming
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/state.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQtmnXA3-5iRwijfVyX:-NRRhvaK3YPl6syh_oe3:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/281bf12d5e2657354e3b08a99969acd34ff2e3b5/crates/starknet_client/src/objects/state.rs#L71)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

done
___
*[`crates/starknet_client/src/objects/state.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQtoApjALx5FM41TgPf:-NRRi4ky2EhY_FcNcn4-:bljq2s4) ([raw file](https://github.com/starkware-libs/papyrus/blob/281bf12d5e2657354e3b08a99969acd34ff2e3b5/crates/starknet_client/src/objects/state.rs#L91)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document.
Do we need this struct? Can we use a vector of tuples or a mapping from class hash to compiled hash instead?
</blockquote></details>

The feeder gives a vector of mappings instead of a vector of tuples. In SN_API I fix that.
___
*[`crates/starknet_client/src/objects/state.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQuBcmL8jlLPBtS_Wyp:-NRRhs5h2QIpH5lb03cj:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/6a50160c82de027c46bea3f5269c1f413b673306/crates/starknet_client/src/objects/state.rs#L38)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please edit to accommodate the two type of declared. Consider adding a visualization in the spirit of:
[declared , old declared, deployed]
</blockquote></details>

done
___
*[`crates/test_utils/src/lib.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/550#-NQy1PGr38NYvDCX4L5T:-NRSicDZ0VsqvPnfjVVD:bywsw2v) ([raw file](https://github.com/starkware-libs/papyrus/blob/b2896c209d15581af7bde89e7767db9b5cb3dd1f/crates/test_utils/src/lib.rs#L177)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@anatgstarkware 
</blockquote></details>

Can you remove the block?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 8 of 34 files at r7, 6 of 7 files at r8, 4 of 4 files at r9, 3 of 8 files at r10, 4 of 6 files at r11, 9 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/550)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/550)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
