### PR TITLE
feat(config): privacy level for config parameters

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`config/default_config.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Ub9C9U3t5dmLA4xc:-Ne3Ub9C9U3t5dmLA4xd:b-a323qc) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/config/default_config.json#L12)):*
> ```JSON
>     "value": "0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4"
>   },
>   "central.concurrent_requests": {
> ```

IMO, this kind of parameters needs to be hidden as well - it should concern the node operator, not the node user
@dan-starkware WDYT?
___
*[`crates/papyrus_config/src/dumping.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3NJS32avPylkjq-YO:-Ne3NJS32avPylkjq-YP:b3wcml5) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L104)):*
> ```XML
>     value: &T,
>     description: &str,
>     privacy: ParamPrivacyInput,
> ```

This can be a bool



_Code quote:_
```XML
privacy: ParamPrivacyInput,
```
___
*[`crates/papyrus_config/src/dumping.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Nf5Z2jWKlw74tWFC:-Ne3Nf5Z2jWKlw74tWFD:bbfdne1) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L182)):*
> ```XML
>             description: "Flag for an optional field".to_owned(),
>             content: SerializedContent::DefaultValue(json!(is_none)),
>             privacy: ParamPrivacy::TemporaryValue,
> ```

What about a situation where we want the content of an optional parameter to be hidden, but to expose whether it is Some or None?



_Code quote:_
```XML
privacy: ParamPrivacy::TemporaryValue,
```
___
*[`crates/papyrus_config/src/dumping.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3LEpg9XnMrf8v9-y6:-Ne3LEpg9XnMrf8v9-y7:b-3q3wm8) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L231)):*
> ```XML
>     Ok(json!(config_map))
> }
> ```

1. Maybe this should be in the monitoring GW crate?
2. why do you need a trait?
You can do:
```
fn get_config_representation<T: Serialize>(config: &T) -> Result<serde_json::Value, ConfigError> {
...
}

fn get_public_config_representation<T: SerializeConfig>(config: &T) -> Result<serde_json::Value, ConfigError> {
...
}

```
Then the rest of the crates won't need to make an empty impl
___
*[`crates/papyrus_config/src/lib.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3MgwW6cpQ0XXIXfVi:-Ne3MgwW6cpQ0XXIXfVj:byldvvk) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/lib.rs#L82)):*
> ```XML
>     RequiredType(SerializationType),
> }
> ```

Move the code so it doesn't separate SerializedContent and its impl
___
*[`crates/papyrus_config/src/lib.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Lvol3fhFBksOBD3a:-Ne3Lvol3fhFBksOBD3b:b-l4ltlw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/lib.rs#L90)):*
> ```XML
>     /// The field is visible only to node's users.
>     Public,
> }
> ```

Can't we just add a bool to the ser_param functions?



_Code quote:_
```XML
/// The privacy level of a config parameter, that received as input from the configs.
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub enum ParamPrivacyInput {
    /// The field is visible only by a secret.
    Private,
    /// The field is visible only to node's users.
    Public,
}
```
___
*[`crates/papyrus_config/src/lib.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3MJrnBLKA2F0eFVXD:-Ne3MJrnBLKA2F0eFVXE:b-lffyds) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/lib.rs#L135)):*
> ```XML
>     #[serde(flatten)]
>     pub content: SerializedContent,
>     pub(crate) privacy: ParamPrivacy,
> ```

Can this be a member of the content, only in the relevant variants?



_Code quote:_
```XML
pub(crate) privacy: ParamPrivacy,
```

**Comment by yair-starkware** [comment]
*[`crates/papyrus_config/src/lib.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3MJrnBLKA2F0eFVXD:-Ne3XAqiB6xeNytwJpiA:bxnc9by) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/lib.rs#L135)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can this be a member of the content, only in the relevant variants?
</blockquote></details>

This way you wont need the temporary variant and it can just be a bool

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`config/default_config.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Ub9C9U3t5dmLA4xc:-Ne7J0ES-mHpyfxaGtKg:bpli7s6) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/config/default_config.json#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Technical parameters of the node, for example the concurrent_requests.
Parameters that should be public are the chain_id, for example
</blockquote></details>

I prefer to avoid referring to specific parameters in this PR.
Let's change it later.
___
*[`crates/papyrus_config/src/dumping.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Nf5Z2jWKlw74tWFC:-Ne4ZHUHAR2PMbuufna2:bp7prf) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IMO we need to consider the #is_none as another parameter.
In sync for example, we could add another parameter that marks whether we want to sync or not and it would be public, right?
</blockquote></details>

The privacy should affect the visibility of parameters of the finalized config.
To avoid confusion, should I move these functions to a new module? WDYT?
___
*[`crates/papyrus_config/src/dumping.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3LEpg9XnMrf8v9-y6:-Ne4_KPvCY4V-6yAHbdM:b-vr2df3) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L231)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

So I think you should also demand the secret in this function in order to return the private configuration
</blockquote></details>

In the next PR I will implement the secret.
___
*[`crates/papyrus_config/src/dumping.rs` line 232 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3wHfy1G7gbVpjQzR_:-Ne7FhOT8IrOs7gjpiQx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6bdd4f98b1b7e35b8bb0d37e07465cd4aaad366f/crates/papyrus_config/src/dumping.rs#L232)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider consolidating the function into a single function with a boolean arg.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3yEX9DHhpxXNjVRzu:-Ne7IWkR0GMGkAy_wAPn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6bdd4f98b1b7e35b8bb0d37e07465cd4aaad366f/crates/papyrus_config/src/dumping.rs#L249)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

`// Remove a nested non-public parameter. For example, if the param path is 'a.b.c.d', perform config_representation[a][b][c].remove(d)`
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_config/src/dumping.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Nf5Z2jWKlw74tWFC:-Ne7VoPJB1Z31nJn-IE9:b3ngkzn) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L182)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The privacy should affect the visibility of parameters of the finalized config.
To avoid confusion, should I move these functions to a new module? WDYT?
</blockquote></details>

SGTM, but how is it answering the optional values issue?
___
*[`crates/papyrus_config/src/dumping.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne7VNli0giDuJOLgt4I:-Ne7VNli0giDuJOLgt4J:b79wque) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b873797d026af72e1a23424dbd4f5cc145cde75/crates/papyrus_config/src/dumping.rs#L235)):*
> ```XML
> pub fn get_config_representation<T: Serialize + SerializeConfig>(
>     config: &T,
>     is_public: bool,
> ```

Rename: include_private_parameters



_Code quote:_
```XML
is_public
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne3Nf5Z2jWKlw74tWFC:-Ne7tywlCTq0NdlkpDqw:bl40ino) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae9d7a6a7327fcffae0573f0888fa683079247a7/crates/papyrus_config/src/dumping.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

SGTM, but how is it answering the optional values issue?
</blockquote></details>

Discussed.
___
*[`crates/papyrus_config/src/dumping.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-Ne7VNli0giDuJOLgt4I:-Ne7txCFEoiimTTdnzIC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b873797d026af72e1a23424dbd4f5cc145cde75/crates/papyrus_config/src/dumping.rs#L235)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename: include_private_parameters
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1155#-:-NeCQKn4A5DwU9CKwMwu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
