### PR TITLE
Send initial sync status.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Set the first sync status.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/919#-Nafjd8W00vRPgTJJgAr:-Nafjd8W00vRPgTJJgAs:b-2jiyub) (no related file):*
Add tests
(is it planned for a separate PR?)

___
___
*[`crates/papyrus_sync/src/lib.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NafiI0q6s8Vc7ekPAty:-NafiI0q6s8Vc7ekPAtz:b-h322ul) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L202)):*
> ```XML
>     //  3. Fetch data from the streams with unblocking wait while there is no new data.
>     async fn sync_while_ok(&mut self) -> StateSyncResult {
>         let starting_block = get_current_block(&self.reader)?;
> ```

starting_block should remain unchanged as long as the node is running.
This code is going to update it repeatedly, is't it?
___
*[`crates/papyrus_sync/src/lib.rs` line 631 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NaffY0zBZ36-T3JQWJ2:-NaffY0zBZ36-T3JQWJ3:b-p8tmuk) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L631)):*
> ```XML
> }
> 
> // The last fully synced block.
> ```

Gets the last fully synced block (block hash and number).



_Code quote:_
```XML
The last fully synced block.
```
___
*[`crates/papyrus_sync/src/lib.rs` line 649 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NafjWhS4rNU1hIZc3_d:-NafjWhS4rNU1hIZc3_e:b-zgvqrc) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L649)):*
> ```XML
> ) -> Result<SyncingState, StateSyncError> {
>     let current_block = get_current_block(reader)?;
>     let highest_block_number = central_source.get_block_marker().await?;
> ```

Just to confirm, if there are no block then is 0 returned?
___
*[`crates/papyrus_sync/src/lib.rs` line 665 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NaffPe5C-V7gNWj8IrS:-NaffPe5C-V7gNWj8IrT:b-kl43c0) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L665)):*
> ```XML
> }
> 
> fn get_block_hash(
> ```

document

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: 8 of 19 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/919#-Nafjd8W00vRPgTJJgAr:-NaftxhN2OrNdHR1v_XL:bb5iea9) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Add tests
(is it planned for a separate PR?)
</blockquote></details>

Yes, it's planned

___
___
*[`crates/papyrus_sync/src/lib.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NafiI0q6s8Vc7ekPAty:-NafnLHm03X1bojNvpQU:b-8xqmet) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L202)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

starting_block should remain unchanged as long as the node is running.
This code is going to update it repeatedly, is't it?
</blockquote></details>

Right, changed.
(In the previous version, it might be changed after recoverable errors).
___
*[`crates/papyrus_sync/src/lib.rs` line 631 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NaffY0zBZ36-T3JQWJ2:-NafoPDf6TPW8yxQ15_h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L631)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Gets the last fully synced block (block hash and number).
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 649 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NafjWhS4rNU1hIZc3_d:-Nafp5YxDcyVEZ21TLZv:bb77ufg) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L649)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Just to confirm, if there are no block then is 0 returned?
</blockquote></details>

Yes.
___
*[`crates/papyrus_sync/src/lib.rs` line 665 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NaffPe5C-V7gNWj8IrS:-NaftwSO-W1NdfCHZCcE:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bdf59d82f6fb13800586edaf939bc9be64d1bc8c/crates/papyrus_sync/src/lib.rs#L665)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_sync/src/lib.rs` line 685 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NagOsjfEitLMhjSIxb9:-NagOsjfEitLMhjSIxbA:b-inzx7d) ([raw file](https://github.com/starkware-libs/papyrus/blob/9cfc458bc8e5776bbe15fc1a3554750acc96024e/crates/papyrus_sync/src/lib.rs#L685)):*
> ```XML
>     let current_block = get_current_block(reader)?;
> 
>     let highest_block = loop {
> ```

why do you need to loop here?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 685 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NagOsjfEitLMhjSIxb9:-NajUjOd8VRp28yknh4c:bgktjqq) ([raw file](https://github.com/starkware-libs/papyrus/blob/9cfc458bc8e5776bbe15fc1a3554750acc96024e/crates/papyrus_sync/src/lib.rs#L685)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

why do you need to loop here?
</blockquote></details>

In the case of a revert after getting the block marker, the block hash for the corresponding block number might be None.

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_sync/src/lib.rs` line 685 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NagOsjfEitLMhjSIxb9:-Nak_n9J5R2pAUOMAjn4:blx68oi) ([raw file](https://github.com/starkware-libs/papyrus/blob/9cfc458bc8e5776bbe15fc1a3554750acc96024e/crates/papyrus_sync/src/lib.rs#L685)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In the case of a revert after getting the block marker, the block hash for the corresponding block number might be None.
</blockquote></details>

OK. Shouldn't you put a sleep in the loop? (So that it won't 'bombard' the sync APIs).
___
*[`crates/papyrus_sync/src/lib.rs` line 645 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/919#-NakFILl85QMWuDgux3Z:-NakFILl85QMWuDgux3_:b-ohmyhl) ([raw file](https://github.com/starkware-libs/papyrus/blob/12bc835a05d48214634e3023a52a8085961469cc/crates/papyrus_sync/src/lib.rs#L645)):*
> ```XML
> 
> // Writes the updated syncing state every `syncing_state_sleep_duration`.
> async fn repetitively_update_syncing_state<TCentralSource: CentralSourceTrait + Sync + Send>(
> ```

maybe 'periodically' instead of 'repetitively'



_Code quote:_
```XML
repetitively_update_syncing_state
```

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r10, 5 of 7 files at r11, 2 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_node/src/main.rs` line 70 at r12](https://reviewable.io/reviews/starkware-libs/papyrus/919#-Nau7tNa09JxxkuOqdY9:-Nau7tNa09JxxkuOqdYA:b-gtz9rx) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d01ddc67175b6c36651a01307f8bf1b518c1db8/crates/papyrus_node/src/main.rs#L70)):*
> ```XML
>                 .map_err(CentralError::ClientCreation)?,
>         );
>         tokio::spawn({
> ```

Consider moving this to run_threads()

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 70 at r12](https://reviewable.io/reviews/starkware-libs/papyrus/919#-Nau7tNa09JxxkuOqdY9:-NauDozGE3AFI7j-v4uy:b-y4gn9h) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d01ddc67175b6c36651a01307f8bf1b518c1db8/crates/papyrus_node/src/main.rs#L70)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Consider moving this to run_threads()
</blockquote></details>

I don't want to run this task when the sync config is None.
@dan-starkware FYI

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/919)* status: 11 of 21 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request closed without merging**
