### PR TITLE
papyrus_node/add_integration_testnet_to_client_integration_test

### PR DESCRIPTION
**Pull request by TzahiTaub**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

Testing the alpha testnet in the client.

Issue Number: N/A

## What is the new behavior?

Added testing of the integration testnet.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)

### CODE REVIEW

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @TzahiTaub)

___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/897#-NaAz-CK9PXCaVqL4Ib4:-NaAz-CK9PXCaVqL4Ib5:bqm6019) ([raw file](https://github.com/starkware-libs/papyrus/blob/af39295eac7dd3c2ff1f43a5b11a76ffc0282cba/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L140)):*
> ```XML
> // Call get_block on the given list of block_numbers.
> async fn test_get_block(starknet_client: &StarknetClient, block_numbers: BlocksForGetBlock) {
>     let data = serde_json::to_value(block_numbers).unwrap();
> ```

Consider defining a generic into_iter function for only int structs.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @TzahiTaub)

___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/897#-NaB3M9k9WCW_8oxpQ1h:-NaB3M9k9WCW_8oxpQ1i:bcofme1) ([raw file](https://github.com/starkware-libs/papyrus/blob/af39295eac7dd3c2ff1f43a5b11a76ffc0282cba/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L59)):*
> ```XML
>     get_blocks: BlocksForGetBlock,
>     get_state_updates: BlocksForGetStateUpdate,
>     class_hashes: ClassHashes,
> ```

Consider replacing the class_hashes with the content of this struct, to avoid serialization.



_Suggestion:_
```XML
cairo_0_class_hash: String,
cairo_1_class_hash: String,
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yoavGrs)

___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/897#-NaB3M9k9WCW_8oxpQ1h:-NavnB8T2EaMJs3DhtRJ:b-u12fru) ([raw file](https://github.com/starkware-libs/papyrus/blob/af39295eac7dd3c2ff1f43a5b11a76ffc0282cba/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L59)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Consider replacing the class_hashes with the content of this struct, to avoid serialization.
</blockquote></details>

I kind of like every test function has the same structure and that it is easy to add more classes when there will be a need to. Is serializing two strings an issue?

**Review by yoavGrs — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @yair-starkware)

___
*[`crates/starknet_client/tests/integration_test.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/897#-NbA3NbmDLRc6G2CHLam:-NbA3Nbn8TMAdRQWiVME:bbix2e9) ([raw file](https://github.com/starkware-libs/papyrus/blob/5138696de7d23c02920ff536e7e06ffe3092247b/crates/starknet_client/tests/integration_test.rs#L9)):*
> ```XML
> use tokio::join;
> 
> const NODE_VERSION: &str = "PAPYRUS-INTEGRATION-TEST-STARKNET-CLIENT";
> ```

Add FEEDER-GATEWAY before the client

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/897#-:-NbA7KxJ2TTJ-JSJ1G4e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
