### PR TITLE
feat(network): mixed behaviour in network manager

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1921** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1921?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-NvkAWqt1B_dH4nrI45r:-NvkAWqt1B_dH4nrI45s:b-u4rf6z) ([raw file](https://github.com/starkware-libs/papyrus/blob/8664cb9427e0afbc6bd4f8d199f8089847c0ffe7/crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs#L1)):*
> ```XML
> use libp2p::kad::store::MemoryStore;
> ```

Move this file to crates/papyrus_network/src/mixed_behaviour.rs and erase the rest of main_behaviour
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 399 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-Nvk9k8p3dYPmVsVxd_a:-Nvk9k8p3dYPmVsVxd_b:b-6pga1) ([raw file](https://github.com/starkware-libs/papyrus/blob/72300bf10e8055f02e033f091c8ff888c684996b/crates/papyrus_network/src/network_manager/mod.rs#L399)):*
> ```XML
>             let local_peer_id = PeerId::from_public_key(&key);
>             mixed_behaviour::MixedBehaviour {
>                 peer_manager: peer_manager::PeerManager::new(PeerManagerConfig::default()),
> ```

IMO this should sit in the mixed behaviour module
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 399 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-Nvk9nDU3IY_VHEt5kOq:-Nvk9nDU3IY_VHEt5kOr:bcx693f) ([raw file](https://github.com/starkware-libs/papyrus/blob/72300bf10e8055f02e033f091c8ff888c684996b/crates/papyrus_network/src/network_manager/mod.rs#L399)):*
> ```XML
>             let local_peer_id = PeerId::from_public_key(&key);
>             mixed_behaviour::MixedBehaviour {
>                 peer_manager: peer_manager::PeerManager::new(PeerManagerConfig::default()),
> ```

Add a TODO to add PeerManagerConfig to NetworkConfig
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-Nvk9tKd1jsKbRBCF2C2:-Nvk9tKd1jsKbRBCF2C3:b-3em9hf) ([raw file](https://github.com/starkware-libs/papyrus/blob/72300bf10e8055f02e033f091c8ff888c684996b/crates/papyrus_network/src/network_manager/mod.rs#L405)):*
> ```XML
>                     key,
>                 )),
>                 kademlia: kad::Behaviour::new(local_peer_id, MemoryStore::new(local_peer_id)),
> ```

Add a TODO to change the kademlia protocol name (or do it since it was already there in the erased code)

**Review by ShahakShama — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-NvkAWqt1B_dH4nrI45r:-NvkBoKQ3j9jpFpBWJU8:b8pslup) ([raw file](https://github.com/starkware-libs/papyrus/blob/8664cb9427e0afbc6bd4f8d199f8089847c0ffe7/crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this file to crates/papyrus_network/src/mixed_behaviour.rs and erase the rest of main_behaviour
</blockquote></details>

yes future PR
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 399 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-Nvk9k8p3dYPmVsVxd_a:-NvkC3_x29rwgfRJJSeU:b-kq0c7) ([raw file](https://github.com/starkware-libs/papyrus/blob/72300bf10e8055f02e033f091c8ff888c684996b/crates/papyrus_network/src/network_manager/mod.rs#L399)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO this should sit in the mixed behaviour module
</blockquote></details>

add a todo
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-Nvk9tKd1jsKbRBCF2C2:-NvkCKTF1XkJ_H1KOPai:be13m3q) ([raw file](https://github.com/starkware-libs/papyrus/blob/72300bf10e8055f02e033f091c8ff888c684996b/crates/papyrus_network/src/network_manager/mod.rs#L405)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO to change the kademlia protocol name (or do it since it was already there in the erased code)
</blockquote></details>

I'm not sure what was there but ok adding a todo

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, 1 of 9 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-:-NvkCynf9d55iw7oWLU_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921#-:-NvkKIB_2xb26Dx9T1Lo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 8 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
