### PR TITLE
feat(network): add db executor trait

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-Ndi6f_DBE-hxgNLYypG:-Ndi6f_DBE-hxgNLYypH:b-9mjqmz) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a81bbfcd6986ef31cc3fbd6c45e578160d8ff12/crates/papyrus_network/src/db_executor.rs#L7)):*
> ```XML
> 
> pub trait ReaderExecutor<Response: Message> {
>     fn spawn_reader(&self, blocks_range: BlocksRange) -> UnboundedSender<Response>;
> ```

I think that we need our own type for GetBlocks but that we don't need a type for GetBlocksResponse. LMK if you disagree

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifVf6CNsvMGeAFbuK:-NdifVf6CNsvMGeAFbuL:bhfvxqr) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L0)):*
please move under executor module
___
*[`crates/papyrus_network/src/db_executor.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifH-24NU585398-Wn:-NdifH-3Du9OqQsmuLBH:b-gf9ccv) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L16)):*
> ```XML
> pub struct ReaderCommunication<Response> {
>     pub result_receiver: UnboundedReceiver<Response>,
>     pub error_receiver: UnboundedReceiver<BlockError>,
> ```

didn't we say the reader only have the results and finished? 
that's also what you sent on slack
___
*[`crates/papyrus_network/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdiOag6Bd-rzB98ElhX:-NdiOag6Bd-rzB98ElhY:b-no33p) ([raw file](https://github.com/starkware-libs/papyrus/blob/9186d8c45eb5d92e34a8db91c0506132817d67a1/crates/papyrus_network/src/lib.rs#L21)):*
> ```XML
> }
> 
> pub struct BlocksRange {
> ```

I think it should be called BlockQuery. it's not only a range
___
*[`crates/papyrus_network/src/sync_notify_executor.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifaqX0wf0RYddkdbX:-NdifaqX0wf0RYddkdbY:b1kam67) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/sync_notify_executor.rs#L0)):*
move this also
___
*[`crates/papyrus_network/src/sync_notify_executor.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifkAQ-0GQhHaoOrOK:-NdifkAQ-0GQhHaoOrOL:bbkdhlf) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/sync_notify_executor.rs#L12)):*
> ```XML
> 
> pub struct WriterCommunication<Response> {
>     pub result_sender: UnboundedSender<Response>,
> ```

I think you swapped the reader and writer return structs..

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifH-24NU585398-Wn:-Ndig5YPCbUSsMo1OfvK:bhdgi6k) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L16)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

didn't we say the reader only have the results and finished? 
that's also what you sent on slack
</blockquote></details>

I got confused in slack. The reader is the one that encounters errors for each block
___
*[`crates/papyrus_network/src/db_executor.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifVf6CNsvMGeAFbuK:-NdigGOy2U3Xx5xW_g3W:bdhzuks) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please move under executor module
</blockquote></details>

IMO unnecessary. If you insist I'll do it
___
*[`crates/papyrus_network/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdiOag6Bd-rzB98ElhX:-Ndigmnq9NHAZNR_xuVe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9186d8c45eb5d92e34a8db91c0506132817d67a1/crates/papyrus_network/src/lib.rs#L21)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think it should be called BlockQuery. it's not only a range
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/sync_notify_executor.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifkAQ-0GQhHaoOrOK:-NdigTYv0OQ2B15uj9cf:b-5c0lt1) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/sync_notify_executor.rs#L12)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think you swapped the reader and writer return structs..
</blockquote></details>

As I said before. This is intentional

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifH-24NU585398-Wn:-NdjOZuH1vStJASD5S1r:b-ftw4d) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L16)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I got confused in slack. The reader is the one that encounters errors for each block
</blockquote></details>

so to make sure I understand. you want to convert the semantics? `ReaderComunication` reads messages and writes them to the DB (or more specifically send them to the sync)  
and `WriterComunication` reads from the DB and sends messages
___
*[`crates/papyrus_network/src/db_executor.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-NdifVf6CNsvMGeAFbuK:-NdjOSoh6wf_Aq3Lx516:b-40aie3) ([raw file](https://github.com/starkware-libs/papyrus/blob/aed3f6a6cad882bb1339a78b63d1b8b9fe612543/crates/papyrus_network/src/db_executor.rs#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO unnecessary. If you insist I'll do it
</blockquote></details>

it would be usefull for me in the network.

**Review by nagmo-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-:-NdjkLqT-JAbf3eNLZFA:bnfp4nl)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145#-:-NdjnxhY8jj6rhAgIEm1:bnfp4nl)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
