### PR TITLE
release: adjust Invoke transaction to V3 changes in starknet-api

### PR DESCRIPTION
**Pull request by barak-b-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146)

### CODE REVIEW

**Comment by ShahakShama** [comment]
*[`crates/papyrus_common/src/transaction_hash.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Nr2e3qw0yyNm5JRF:-Ne2Nr2f0F1EU4hSNufo:b-gyenj3) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_common/src/transaction_hash.rs#L254)):*
> ```XML
> }
> 
> fn get_invoke_transaction_v3_hash(
> ```

@yoavGrs , when this PR merges, add a test for invoke v3 hash  
@barak-b-starkware , Please add a TODO on Yoav to add such test

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, @elintul, and @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Nr2e3qw0yyNm5JRF:-Ne2PK6m0kiiGVK5y9nq:bo8qjcu) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_common/src/transaction_hash.rs#L254)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@yoavGrs , when this PR merges, add a test for invoke v3 hash  
@barak-b-starkware , Please add a TODO on Yoav to add such test
</blockquote></details>

No problem, @Yael-Starkware will probably do it.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, @elintul, and @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Ogg77v5ewSzzIq2N:-Ne2Ogg77v5ewSzzIq2O:b-wvfqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L240)):*
> ```XML
>                 }
>                 starknet_api::transaction::InvokeTransaction::V3(_) => {
>                     Err(internal_server_error("Version 3 transactions are not supported on v0.3.0"))
> ```

Same as previous PR
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2OkYS8W-vd6_AtNeT:-Ne2OkYS8W-vd6_AtNeU:b-wvfqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L263)):*
> ```XML
>                 }
>                 starknet_api::transaction::InvokeTransaction::V3(_) => {
>                     Err(internal_server_error("Version 3 transactions are not supported on v0.4.0"))
> ```

Same as previous PR
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2PIst0TD4kPv7izD9:-Ne2PIst0TD4kPv7izDA:b-ovazm6) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/starknet_client/src/writer/objects/transaction.rs#L66)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Default, Clone, Copy, Eq, PartialEq)]
> pub enum InvokeV1Type {
>     #[serde(rename = "DEPRECATED_INVOKE_FUNCTION")]
> ```

Same as previous PR. I don't like the fact that we won't be able to support starknet-v0.12 once this PR merges
Let's talk together with whomever's relevant to this (Noa?)
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Q6EA1pq4WPrzXzi7:-Ne2Q6EA1pq4WPrzXzi8:bord7k9) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/starknet_client/src/writer/objects/transaction.rs#L174)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Clone, Eq, PartialEq)]
> #[serde(deny_unknown_fields)]
> pub struct InvokeV3Transaction {
> ```

Add a TODO on me to add tests for invoke v3

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @elintul, @ShahakShama, and @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Nr2e3qw0yyNm5JRF:-Ne3LTEU3nMhxllFYliz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_common/src/transaction_hash.rs#L254)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

No problem, @Yael-Starkware will probably do it.
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Ogg77v5ewSzzIq2N:-Ne3MdM92TGW0bc-2Qvk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L240)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as previous PR
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2OkYS8W-vd6_AtNeT:-Ne3PEJNBRv9DyQXhgk2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L263)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as previous PR
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2PIst0TD4kPv7izD9:-Ne7dCoc62E1DcMEwRPf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/starknet_client/src/writer/objects/transaction.rs#L66)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as previous PR. I don't like the fact that we won't be able to support starknet-v0.12 once this PR merges
Let's talk together with whomever's relevant to this (Noa?)
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-Ne2Q6EA1pq4WPrzXzi7:-Ne7eKLk88yAAkYMFXKD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/456c0e04a377408ae07b2d71a236ff106e38447d/crates/starknet_client/src/writer/objects/transaction.rs#L174)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO on me to add tests for invoke v3
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-:-Ne7jKUm98VNCJ1k7nyY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1146#-:-NeDyaBKC7BPx609RBU5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/papyrus/pull/1171) PR as part of bumping version from 0.0.4 to 0.0.5.

**Pull request closed without merging**
