### PR TITLE
feat(network): network manager support for multiple protocols

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1801** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1801?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801)* status: all files reviewed, 15 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshL5yD3hVr73DoM7l4:-NshL5yE6ZZpLBl89AsV:b3z7l4i) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/lib.rs#L13)):*
> ```XML
> #[cfg(test)]
> mod test_utils;
> use core::fmt;
> ```

I think this should be std::fmt
___
*[`crates/papyrus_network/src/lib.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshLETjAmxMpm5mLu9i:-NshLETjAmxMpm5mLu9j:b74s3rj) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/lib.rs#L65)):*
> ```XML
> }
> 
> impl Display for DataType {
> ```

Consider using derive_more
___
*[`crates/papyrus_network/src/lib.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshLQ7_1ojKZtj3pc_K:-NshLQ7_1ojKZtj3pc_L:b-tcf277) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/lib.rs#L109)):*
> ```XML
>             }
>         }
>         .map_err(|_| QueryEncodingError)
> ```

What are the errors you're hiding here? Document why it's ok to hide them
___
*[`crates/papyrus_network/src/converters/mod.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshLwue9hqcsQ_XR0KT:-NshLwue9hqcsQ_XR0KU:b-uwx15y) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/mod.rs#L18)):*
> ```XML
>     pub(crate) fn new(mut protocol_to_receiver_map: HashMap<Protocol, Receiver<Vec<u8>>>) -> Self {
>         let signed_headers_receiver =
>             protocol_to_receiver_map.remove(&Protocol::SignedBlockHeader).map(|reciever| {
> ```

reciever -> receiver
___
*[`crates/papyrus_network/src/converters/mod.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshNcDq-hMRc6I3lsFT:-NshNcDq-hMRc6I3lsFU:bd96b8b) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/mod.rs#L22)):*
> ```XML
>                     .map(|data_bytes| {
>                         protobuf::BlockHeadersResponse::decode(&data_bytes[..])
>                             .expect("failed to decode protobuf SignedBlockHeader")
> ```

Add TODO to not panic
___
*[`crates/papyrus_network/src/converters/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshN0ms4F3U5Xs0GNFz:-NshN0ms4F3U5Xs0GNG-:b-kzvfcb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/mod.rs#L35)):*
> ```XML
>                             .expect("failed to decode protobuf StateDiff")
>                             .try_into()
>                             .expect("failed to convert ThinkStateDiff")
> ```

Think -> Thin
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/common.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshNnBl1tIZZW03r4bs:-NshNnBl1tIZZW03r4bt:bn3ah9o) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/protobuf_conversion/common.rs#L186)):*
> ```XML
> }
> 
> pub(crate) fn iteration_to_query_parts(
> ```

Impl this as `impl TryFrom<protobuf::Iteration> for InternalQuery`. If you don't want you can swap 
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshbGAV1d2Gq7CwOfJt:-NshbGAV1d2Gq7CwOfJu:bcdl36d) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/protobuf_conversion/mod.rs#L3)):*
> ```XML
> mod common;
> mod header;
> pub mod state_diff;
> ```

Why is this pub? what's the compiler error when you remove the pub?
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshSn7HAlcM68RE8e7K:-NshSn7HAlcM68RE8e7L:b-f4x6bu) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs#L233)):*
> ```XML
> }
> 
> impl From<Query> for protobuf::StateDiffsRequest {
> ```

Reduce the code duplication here, preferrably by implementing From<Query> for protobuf::Iteration
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshTBdL-dztqk-N2W0o:-NshTBdL-dztqk-N2W0p:bqxdd01) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/db_executor/mod.rs#L70)):*
> ```XML
>                     data.encode(&mut buf).map_err(|_| DataEncodingError).map(|_| buf)
>                 });
>                 if iter.any(|res: Result<Vec<u8>, DataEncodingError>| res.is_err()) {
> ```

You can collect an iterator of results into Result<Vec
Just add to the iter `.collect::<Result<Vec<_>, _>>()?`
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshTlFvDhu2FTcgTMrB:-NshTlFvDhu2FTcgTMrC:bmm3bxl) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/db_executor/mod.rs#L73)):*
> ```XML
>                     return Err(DataEncodingError);
>                 }
>                 let res_bytes = iter.fold(vec![], |mut acc, res| {
> ```

use flatten and collect instead
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshTz9F9-yjATyveCUh:-NshTz9F9-yjATyveCUi:b-ikjkyk) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/db_executor/mod.rs#L90)):*
> ```XML
>                 }
>                 .encode(buf)
>                 .map_err(|_| DataEncodingError),
> ```

Consider implementing From<ProtobufConversionError> for DataEncodingError that ignores the error and then you can do ? all across the code here without map_err
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-Nsh_cx26lVjOwCvCbAV:-Nsh_cx26lVjOwCvCbAW:b-gnjcdo) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/network_manager/mod.rs#L177)):*
> ```XML
>                 self.query_results_router.push(
>                     receiver
>                         .chain(stream::once(async move { Data::Fin(data_type) }))
> ```

impl Copy for DataType instead of the `move`
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshaJs389u1Qn5cpM_e:-NshaJs4-dnzhM_FK-Kz:b5esm85) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/network_manager/mod.rs#L213)):*
> ```XML
>                 }
>             }
>             // TODO: is this the right place to remove the outbound session id from the mapping?
> ```

Yes, it is. You can remove the TODO
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshaRVk7MWTG2oBjwcU:-NshaRVk7MWTG2oBjwcV:bs47czn) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/network_manager/mod.rs#L238)):*
> ```XML
>         let (data, inbound_session_id) = res;
>         let mut data_bytes = vec![];
>         // TODO: how should we handle fin? we need to know the protocol to encode it correctly.
> ```

We resolved this. Erase this TODO

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-:-Nslw01M08gAooy6k6az:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshLQ7_1ojKZtj3pc_K:-Nslt30nDXD14e-g7oxn:b-dmcid9) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/lib.rs#L109)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IMO `|_encode_error|` is better because `: EncodeError` implies that the code won't compile if you remove the type hint. I leave this up to you
___
*[`crates/papyrus_network/src/converters/mod.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NslvFX_BF82aY7zIIEp:-NslvFX_BF82aY7zIIEq:b-bgxys4) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b7aa36f01bbe3536aa7729259eec29bf123144f/crates/papyrus_network/src/converters/mod.rs#L17)):*
> ```XML
> impl ResponseReceivers {
>     pub(crate) fn new(mut protocol_to_receiver_map: HashMap<Protocol, Receiver<Vec<u8>>>) -> Self {
>         // TODO: instead of panicing return a stream of results with an error fo the subscriber can
> ```

fo -> for
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NslvlltET1bulRIOa20:-NslvlltET1bulRIOa21:b-auton3) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b7aa36f01bbe3536aa7729259eec29bf123144f/crates/papyrus_network/src/db_executor/mod.rs#L75)):*
> ```XML
>                     })
>                     .collect::<Result<Vec<_>, _>>()?;
>                 res.iter().flatten().for_each(|byte| buf.put_u8(*byte));
> ```

IMO for loop is more readable than for_each but I leave that up to you (please try it out before dismissing the comment and see if it looks better or not)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-NshLQ7_1ojKZtj3pc_K:-NslyqiR2pLwIAVES0J4:bu0veyl) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f0192951f6032f30831fa12faf5f9380e2e779a/crates/papyrus_network/src/lib.rs#L109)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO `|_encode_error|` is better because `: EncodeError` implies that the code won't compile if you remove the type hint. I leave this up to you
</blockquote></details>

but then it doesn't tell you what type it is :) I think it's ok like this

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-:-NsmWwBvA8VlJyFDtUQg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1801#-:-NsqxxfpD9GOc4Vua9L0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
