### PR TITLE
feat(sync): stop sync at block number from config for profiling

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1838** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1838?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5W4U1UX173_AFA-Y:-Ntz5W4U1UX173_AFA-Z:b-ijuuz7) (no related file):*
Why do you want to merge this to main?

___
___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5Q6x4qGg0qQ4Zwv6:-Ntz5Q6x4qGg0qQ4Zwv7:bps31bo) ([raw file](https://github.com/starkware-libs/papyrus/blob/5193e8a1edbb4bb9d360d7dc90b2c0f7c71295e5/crates/papyrus_p2p_sync/src/stream_factory.rs#L116)):*
> ```XML
>                         current_block_number >= stop_sync_at_block_number
>                     }) {
>                         return;
> ```

Please add log

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5W4U1UX173_AFA-Y:-Ntz5pJn9obYlE-VtFy5:btiwv8b) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do you want to merge this to main?
</blockquote></details>

I think it's useful to have the option to run profiling. this change is necessary for that

___
___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5Q6x4qGg0qQ4Zwv6:-Ntz7b94BX6hCTdbmd-l:byzio6u) ([raw file](https://github.com/starkware-libs/papyrus/blob/5193e8a1edbb4bb9d360d7dc90b2c0f7c71295e5/crates/papyrus_p2p_sync/src/stream_factory.rs#L116)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add log
</blockquote></details>

you'll get this:
`ERROR P2P Sync stopped.`
don't you think it's enough?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5Q6x4qGg0qQ4Zwv6:-Ntz9cvP1Xf9yyKg0jwT:bcggpx5) ([raw file](https://github.com/starkware-libs/papyrus/blob/5193e8a1edbb4bb9d360d7dc90b2c0f7c71295e5/crates/papyrus_p2p_sync/src/stream_factory.rs#L116)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

you'll get this:
`ERROR P2P Sync stopped.`
don't you think it's enough?
</blockquote></details>

I would prefer an informative message

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-Ntz5Q6x4qGg0qQ4Zwv6:-Nu3Al8zEcMqOcU4QVo3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5193e8a1edbb4bb9d360d7dc90b2c0f7c71295e5/crates/papyrus_p2p_sync/src/stream_factory.rs#L116)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I would prefer an informative message
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-:-Nu3DdSG4H9TU0ccoqMK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1838#-:-NuTWOmo88PSSpxqBcoS:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
