### PR TITLE
feat(network): add streamed bytes internal event

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1902** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1902?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/main_behaviour/mod.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfSG5BazHA2uH2Y3w:-NvRfSG5BazHA2uH2Y3x:b-oskioc) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/main_behaviour/mod.rs#L80)):*
> ```XML
>     ) -> Poll<ToSwarm<Self::ToSwarm, <Self::ConnectionHandler as ConnectionHandler>::FromBehaviour>>
>     {
>         let mixed_behaviour_event = ready!(self.mixed_behaviour.poll(cx));
> ```

I thought we said we will put this code in NM and erase the main behaviour
___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfe5S9a8mYLvk23WB:-NvRfe5S9a8mYLvk23WC:bp5bsgp) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L98)):*
> ```XML
> #[derive(Debug)]
> #[cfg_attr(test, derive(PartialEq))]
> pub enum InternalEvent {
> ```

I think it's clearer if it's called InputEvent. See #1903
Anyway, we need to align into one of them
___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfb3p7Q77XtR9cM4I:-NvRfb3p7Q77XtR9cM4J:b2unkyf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L99)):*
> ```XML
> #[cfg_attr(test, derive(PartialEq))]
> pub enum InternalEvent {
>     QueryAssigned(QueryId, PeerId, Multiaddr),
> ```

What about the query itself?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/main_behaviour/mod.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfSG5BazHA2uH2Y3w:-NvRh3gg5TKeSk4tLdPJ:b1598dw) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/main_behaviour/mod.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I thought we said we will put this code in NM and erase the main behaviour
</blockquote></details>

yes but we're not using the mixed behaviour in NM yet. so I put this code here. we can keep develping and test it and move it when ready.
I also don't feel like there's a need for a todo for now
___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfe5S9a8mYLvk23WB:-NvRhiP68pYl50WC-Mvc:b-9zavg3) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L98)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think it's clearer if it's called InputEvent. See #1903
Anyway, we need to align into one of them
</blockquote></details>

I answered there. let's continue the discussion in PR #1903 or offline 
___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfb3p7Q77XtR9cM4I:-NvRhN_39Nw4khQ_OgVk:b-d29tns) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L99)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What about the query itself?
</blockquote></details>

the PM only gets the query id. 
stream bytes is not using it yet but my plan is to register a pending query in SB until we get the assignment from PM. future PRs

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfb3p7Q77XtR9cM4I:-NvV-N7I-il7z7By5fxv:btu3rj3) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L99)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

the PM only gets the query id. 
stream bytes is not using it yet but my plan is to register a pending query in SB until we get the assignment from PM. future PRs
</blockquote></details>

I don't like this future plan, but let's cross the bridge when we get to it

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_bytes/behaviour.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-NvRfe5S9a8mYLvk23WB:-NvV02_DAzcBHdEfldG7:bl5kxjz) ([raw file](https://github.com/starkware-libs/papyrus/blob/a856cf574be1a57f3ccf2ab06ab0cc3eb73a1138/crates/papyrus_network/src/streamed_bytes/behaviour.rs#L98)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I answered there. let's continue the discussion in PR #1903 or offline
</blockquote></details>

I see the discussion there, you suggested `FromOtherBehaviour`. I'm ok with that. I'll fix it in the other PR as well

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1902#-:-NvVTd08DIIa7xebSfNE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
