### PR TITLE
feat(storage,starknet_client,sync,test_utils): headers V1 (with migration from V0)

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
> Reviewed 157 of 159 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 405 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFIAoKB8NPXaK-v65A:-NrFIAoKB8NPXaK-v65B:bo4y6k6) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/header.rs#L405)):*
> ```XML
> // TODO(yair): Consider moving to a separate file.
> #[derive(Debug, Default, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub(crate) struct StorageBlockHeaderV0 {
> ```

Please document from where this is taken.



_Code quote:_
```XML
pub(crate) struct StorageBlockHeaderV0 {
```
___
*[`crates/papyrus_storage/src/test_instances.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFIwrmDjN3iI5dW8WR:-NrFIwrmDjN3iI5dW8WS:b-xrbdev) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/test_instances.rs#L54)):*
> ```XML
>         pub n_events: Option<usize>,
>     }
>     pub struct StorageBlockHeaderV0 {
> ```

Can we move this to a deprecated area?



_Code quote:_
```XML
pub struct StorageBlockHeaderV0 {
```
___
*[`crates/starknet_client/src/reader/objects/block.rs` line 315 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFXbl93Tob74zepg46:-NrFXbl93Tob74zepg47:b8yros4) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/starknet_client/src/reader/objects/block.rs#L315)):*
> ```XML
>                     && block.event_commitment == EventCommitment::default()
>                 {
>                     (None, None, None, None)
> ```

Consider explaining in a short comment



_Code quote:_
```XML
                if block.transaction_commitment == TransactionCommitment::default()
                    && block.event_commitment == EventCommitment::default()
                {
                    (None, None, None, None)
```
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFJH28-v1bmCNFBM0y:-NrFJH28-v1bmCNFBM0z:b-xrbdev) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/serialization/serializers.rs#L159)):*
> ```XML
>         pub n_events: Option<usize>,
>     }
>     pub struct StorageBlockHeaderV0 {
> ```

Can we move this to a deprecated area?



_Code quote:_
```XML
 pub struct StorageBlockHeaderV0 {
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 405 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFIAoKB8NPXaK-v65A:-NrGMttaEqafmpRIDp1j:b9bojos) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/header.rs#L405)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document from where this is taken.
</blockquote></details>

You mean to specify the commit hash? The problem is that I will know the commit hash only after this PR is merged.
I can
___
*[`crates/papyrus_storage/src/test_instances.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFIwrmDjN3iI5dW8WR:-NrViBKg7WxzhhFWt9ne:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/test_instances.rs#L54)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we move this to a deprecated area?
</blockquote></details>

Done
___
*[`crates/starknet_client/src/reader/objects/block.rs` line 315 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFXbl93Tob74zepg46:-NrVioPwE-imjhwI3wXa:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/starknet_client/src/reader/objects/block.rs#L315)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider explaining in a short comment
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrFJH28-v1bmCNFBM0y:-NrViCmg9MHo5QjoJ9Sm:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/297392b14f6953a57e39475d5778b459866ac231/crates/papyrus_storage/src/serialization/serializers.rs#L159)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we move this to a deprecated area?
</blockquote></details>

Done

**Comment by dan-starkware** [comment]
Please add prerequisite PR that changes the storage crate version such that it can load older DBs
Preferably with a test that we can deserialise all older versions

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 12 of 12 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1718#-NrZlVBP64IzMzaI0FqB:-Nrjbq_p779BZya77Wwb:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add prerequisite PR that changes the storage crate version such that it can load older DBs
Preferably with a test that we can deserialise all older versions
</blockquote></details>

Done.

___

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
