### PR TITLE
feat: add ability to config profiling on/off

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-NudWbTGCdaKpM5Yjcfd:-NudWbTH2_SACIMpHdNh:b-ykplrp) (no related file):*
1.  It doesn't pass tests.
2. I have some questions about this PR, let's talk about this next week

___

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 6 of 7 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: 14 of 15 files reviewed, 9 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7FwV5-50GoQAAig-r:-Nv7FwV5-50GoQAAig-s:b-x1yzwv) (no related file):*
Add a todo to configure this on runtime using the monitoring gw.
Add a todo remove this true-false thing when our metric exporter will support more advent filtering.
Add a todo to consider configuring with levels.

As we discussed, consider different configuration names, such as true and false.
Consider changing the location of this configuration value. In my opinion, it should be next to the collect_metrics value (maybe this value is not in the correct location).

___
___
*[`config/default_config.json` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7A8Mh6RUd8gay0CrS:-Nv7A8Mh6RUd8gay0CrT:bdumngb) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/config/default_config.json#L178)):*
> ```JSON
>   },
>   "profiling": {
>     "description": "should the node track profiling information",
> ```

Should. The description in the config file starts with a capital letter
___
*[`config/default_config.json` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7BHdu5iBIvLQshqhz:-Nv7BHdu5iBIvLQshqi-:b-kam8aj) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/config/default_config.json#L178)):*
> ```JSON
>   },
>   "profiling": {
>     "description": "should the node track profiling information",
> ```

Consider using the same format as for collect metrics ."If true, collect metrics for the node.".
In addition, this information is only a set of metrics, so consider changing information to metrics. Maybe change this name to collect_profilling_metrics
___
*[`crates/papyrus_common/src/metrics.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7ALN06wB19E7xss65:-Nv7ALN06wB19E7xss66:b-ampzbl) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_common/src/metrics.rs#L36)):*
> ```XML
> pub const PAPYRUS_NUM_ACTIVE_OUTBOUND_SESSIONS: &str = "papyrus_num_active_outbound_sessions";
> 
> /// global variable set by the main config to enable profiling.
> ```

Global. Capital letter
Consider explicitly writing this collect profiling metrics.
___
*[`crates/papyrus_node/src/main.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7Ai6nCl-7uVPDJdHp:-Nv7Ai6nCl-7uVPDJdHq:bda643w) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_node/src/main.rs#L301)):*
> ```XML
>     }
> 
>     PROFILING_STATUS.get_or_init(|| config.profiling);
> ```

why not use set() instead of get_or_init(). This value should be initialized only here.
___
*[`crates/papyrus_proc_macros/Cargo.toml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7EJoG9eYlGNQCx_k-:-Nv7EJoG9eYlGNQCx_k0:b-9yd1fw) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/Cargo.toml#L16)):*
> ```TOML
> metrics.workspace = true
> metrics-exporter-prometheus.workspace = true
> papyrus_common = { path = "../papyrus_common" }
> ```

Use the version of the crate like in other places where we use papyrus_common
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7JYdA3CJ6CPdUqFMi:-Nv7JYdA3CJ6CPdUqFMj:bdyfl5z) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/src/lib.rs#L130)):*
> ```XML
>         })
>         .collect::<Vec<_>>();
>     let attr = parts
> ```

Give this variable a more explanatory name, also to the config variable.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7Injt5HC3t38fKJHj:-Nv7Injt5HC3t38fKJHk:bmzv0m8) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/src/lib.rs#L146)):*
> ```XML
>         {
>             let mut start_function_time = None;
>             if !#controll_with_config || (#controll_with_config && *(papyrus_common::metrics::PROFILING_STATUS.get().unwrap_or(&false))) {
> ```

Why not expect? This value should be a valid

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: 8 of 15 files reviewed, 9 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`config/default_config.json` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7A8Mh6RUd8gay0CrS:-NvAWshy5SbqH5EFWEmU:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/config/default_config.json#L178)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Should. The description in the config file starts with a capital letter
</blockquote></details>

Done.
___
*[`config/default_config.json` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7BHdu5iBIvLQshqhz:-NvAXCsZAe7-387v8kVE:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/config/default_config.json#L178)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider using the same format as for collect metrics ."If true, collect metrics for the node.".
In addition, this information is only a set of metrics, so consider changing information to metrics. Maybe change this name to collect_profilling_metrics
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/metrics.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7ALN06wB19E7xss65:-NvAXfqVDuAlGDjfPKTX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_common/src/metrics.rs#L36)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Global. Capital letter
Consider explicitly writing this collect profiling metrics.
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/main.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7Ai6nCl-7uVPDJdHp:-NvAXmuaD7Z5VDCPpV0D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_node/src/main.rs#L301)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why not use set() instead of get_or_init(). This value should be initialized only here.
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/Cargo.toml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7EJoG9eYlGNQCx_k-:-NvAY3DqBUp4WrErj4aE:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/Cargo.toml#L16)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Use the version of the crate like in other places where we use papyrus_common
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7JYdA3CJ6CPdUqFMi:-NvAZPNY9iuuHXlyBkwH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/src/lib.rs#L130)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Give this variable a more explanatory name, also to the config variable.
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7Injt5HC3t38fKJHj:-NvAZXfo3EM3HS1C-Nve:b-jnsmw2) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/crates/papyrus_proc_macros/src/lib.rs#L146)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why not expect? This value should be a valid
</blockquote></details>

yes it should.. but if for some reason it's not I don't see any compelling reason to panic.. worst case you won't get the metrics.
BTY an example to where it won't be valid is if you run something from another binary and not main.. since main sets it

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7FwV5-50GoQAAig-r:-NvCWHnD4HtS1BcwpLgk:b-gd2h33) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Add a todo to configure this on runtime using the monitoring gw.
Add a todo remove this true-false thing when our metric exporter will support more advent filtering.
Add a todo to consider configuring with levels.

As we discussed, consider different configuration names, such as true and false.
Consider changing the location of this configuration value. In my opinion, it should be next to the collect_metrics value (maybe this value is not in the correct location).
</blockquote></details>

Consider again adding the todos

___
___
*[`config/default_config.json` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7A8Mh6RUd8gay0CrS:-NvCTUG91pc-UaY4cfaB:b-q74425) ([raw file](https://github.com/starkware-libs/papyrus/blob/5403de8a6a7b6b69accce45b9f52d71a33d75e68/config/default_config.json#L178)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the changes.
___
*[`crates/papyrus_node/src/config/mod.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-NvCThIL2Ldq6kdBe-Ke:-NvCThIL2Ldq6kdBe-Kf:b-svx9o8) ([raw file](https://github.com/starkware-libs/papyrus/blob/8cc5d282a5022fa7704a88d100a40d880d05f640/crates/papyrus_node/src/config/mod.rs#L103)):*
> ```XML
>                 "collect_profiling_metrics",
>                 &self.collect_profiling_metrics,
>                 "If true, collect metrics for the node.",
> ```

You need to update also the defualt config file.
Also, consider adding profiling. ie "If true, collect profiling metrics for the node."

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 7 files at r2, 2 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: all files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware and @nagmo-starkware)

___
*[`crates/papyrus_proc_macros/src/lib.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-NvVW20n-klO6SO8bHeu:-NvVW20n-klO6SO8bHev:b-pa9p6m) ([raw file](https://github.com/starkware-libs/papyrus/blob/8cc5d282a5022fa7704a88d100a40d880d05f640/crates/papyrus_proc_macros/src/lib.rs#L104)):*
> ```XML
> /// This macro will emit a histogram metric with the given name and the latency of the function.
> /// The macro also receives a boolean that controls if the metric should be controlled
> /// by the profiling configuration value or not.
> ```

Suggestion: `The macro also receives a boolean for whether it will be emitted only when profiling is activated or at all times`



_Code quote:_
```XML
/// The macro also receives a boolean that controls if the metric should be controlled
/// by the profiling configuration value or not.
```
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-NvVV5p87DvHaibHuWfN:-NvVV5p87DvHaibHuWfO:bbbqhpe) ([raw file](https://github.com/starkware-libs/papyrus/blob/8cc5d282a5022fa7704a88d100a40d880d05f640/crates/papyrus_proc_macros/src/lib.rs#L127)):*
> ```XML
>         .map(|s| {
>             TokenStream::from_str(s)
>                 .expect("attribute should include metric name and controll with config boolean")
> ```

Suggestion: `Expecting metric name and bool (is for profiling only)`



_Code quote:_
```XML
"attribute should include metric name and controll with config boolean
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-Nv7FwV5-50GoQAAig-r:-Nvf37c93JrGo4GlLFFv:b8uf51s) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider again adding the todos
</blockquote></details>

I don't really see the value of this todos. if at some point someone would like to improve this he can. the todos won't help in this case IMO.

___
___
*[`crates/papyrus_node/src/config/mod.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-NvCThIL2Ldq6kdBe-Ke:-Nvf2ywLDwo70E5ZX8GX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8cc5d282a5022fa7704a88d100a40d880d05f640/crates/papyrus_node/src/config/mod.rs#L103)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

You need to update also the defualt config file.
Also, consider adding profiling. ie "If true, collect profiling metrics for the node."
</blockquote></details>

Done.

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1867#-:-NvkN4-NCoLIzXZeDbWc:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

**Pull request merged**
