### PR TITLE
chore(release): dori/bump versions in cargo toml

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [v] Other (please describe):
Upgrade VM, compiler, SN-API and blockifier.

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 886 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwj_w0PlFI1i2NqVF:-NnIwj_w0PlFI1i2NqVG:b-iegbd6) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_execution/src/execution_test.rs#L886)):*
> ```XML
> 
>     let child = blockifier::execution::errors::EntryPointExecutionError::RecursionDepthExceeded;
>     let expected = format!("Transaction validation has failed: {child}");
> ```

is this change problematic somwhere?



_Code quote:_
```XML
:
```
___
*[`crates/papyrus_network/build.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwnPoAJvmT9CfpvnU:-NnIwnPoAJvmT9CfpvnV:bz6mxff) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_network/build.rs#L7)):*
> ```XML
>     let mut prost_build = prost_build::Config::new();
>     prost_build.protoc_arg("--experimental_allow_proto3_optional");
>     prost_build.compile_protos(
> ```

maybe @ShahakShama should TAL



_Code quote:_
```XML
    let mut prost_build = prost_build::Config::new();
    prost_build.protoc_arg("--experimental_allow_proto3_optional");
    prost_build.compile_protos(
```
___
*[`crates/papyrus_rpc/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwqlh6E0PKqdTfHST:-NnIwqlh6E0PKqdTfHSU:bkyd765) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_rpc/Cargo.toml#L21)):*
> ```TOML
> lazy_static.workspace = true
> metrics.workspace = true
> papyrus_common = { path = "../papyrus_common", version = "0.4.0-dev.0" }
> ```

@yair-starkware why are these versions provided explicitly, instead of just via `path`, like the `papyrus_execution` dependency here below?



_Code quote:_
```TOML
"0.4.0-dev.0"
```
___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwynW0zkqL1iRSKS9:-NnIwynW0zkqL1iRSKSA:bl09vov) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_rpc/src/v0_4/execution_test.rs#L138)):*
> ```XML
>         gas_consumed: stark_felt!("0x68b"),
>         gas_price: *GAS_PRICE,
>         overall_fee: Fee(167500000000000,),
> ```

these constants - and the other values in the `lazy_static` - are duplicated in 3 tests. Shouldn't these be put in some common constants module? @yair-starkware 



_Code quote:_
```XML
        gas_consumed: stark_felt!("0x68b"),
        gas_price: *GAS_PRICE,
        overall_fee: Fee(167500000000000,),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_network/build.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwnPoAJvmT9CfpvnU:-NnIzviH01YgpJGAbZoU:bfuv1qu) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_network/build.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe @ShahakShama should TAL
</blockquote></details>

or @nagmo-starkware ?

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @nagmo-starkware, and @ShahakShama)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnJ6LN96J-QcR3rvUoj):*
Please write the changes in this commit explicitly. I predict we will need to search for it in the future.
Perhaps separate the const changes and the blockifier error messages to different commits.



_Code quote:_
```
Upgrade fixes
```
___
*[`crates/papyrus_execution/src/execution_test.rs` line 886 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwj_w0PlFI1i2NqVF:-NnJ5Ahn8B2cdxD5nghG:bv8attr) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_execution/src/execution_test.rs#L886)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this change problematic somwhere?
</blockquote></details>

It needs to be the same across different node implementations. Do you have the before and after?
___
*[`crates/papyrus_rpc/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwqlh6E0PKqdTfHST:-NnJ73nP0DocSPm9a4OH:b-7vo9l9) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_rpc/Cargo.toml#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@yair-starkware why are these versions provided explicitly, instead of just via `path`, like the `papyrus_execution` dependency here below?
</blockquote></details>

I think it is a mistake in the papyrus_execution dependency.
We need the explicit versions in order to publish the crates IIRC
___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwynW0zkqL1iRSKS9:-NnJ5iZX7R6jPj9NC1-I:b-41ng0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_rpc/src/v0_4/execution_test.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these constants - and the other values in the `lazy_static` - are duplicated in 3 tests. Shouldn't these be put in some common constants module? @yair-starkware
</blockquote></details>

No, the code duplication is intended

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, @ShahakShama, and @yair-starkware)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnJ6LN96J-QcR3rvUoj):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please write the changes in this commit explicitly. I predict we will need to search for it in the future.
Perhaps separate the const changes and the blockifier error messages to different commits.
</blockquote></details>

Better?
___
*[`crates/papyrus_execution/src/execution_test.rs` line 886 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwj_w0PlFI1i2NqVF:-NnJ8dlaExKqjg3SprWu:br7zmer) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_execution/src/execution_test.rs#L886)):*
WDYM? Look at the diff...?
If you mean why this test fails, then after dep upgrade and before my change, we got this error:
```
---- execution_test::blockifier_error_mapping stdout ----
thread 'execution_test::blockifier_error_mapping' panicked at crates/papyrus_execution/src/execution_test.rs:871:5:
assertion failed: `(left == right)`

Diff < left / right > :
<Contract constructor execution has failed: Execution failed due to recursion depth exceeded. Execution failed due to recursion depth exceeded.
>Contract constructor execution has failed. Execution failed due to recursion depth exceeded.
```
and if I only fix `ExecutionError::from` without fixing the test, then the test expects a `.` but the blockifier returns a `:`.
___
*[`crates/papyrus_rpc/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwqlh6E0PKqdTfHST:-NnJ9OGQ2boN2MJFStWF:bs5ns0f) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_rpc/Cargo.toml#L21)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it is a mistake in the papyrus_execution dependency.
We need the explicit versions in order to publish the crates IIRC
</blockquote></details>

ok, out of scope in this PR though IMO

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @nagmo-starkware, and @ShahakShama)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnJ6LN96J-QcR3rvUoj):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Better?
</blockquote></details>

fix(execution, JSON-RPC): fix the error message of nested blockifier errors
___
*[`crates/papyrus_execution/src/execution_test.rs` line 886 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-NnIwj_w0PlFI1i2NqVF:-NnJAaE-D0iqaJWrndlL:bgomeec) ([raw file](https://github.com/starkware-libs/papyrus/blob/4c4e8109cda9714e879c10278f7d47fd45b842c1/crates/papyrus_execution/src/execution_test.rs#L886)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? Look at the diff...?
If you mean why this test fails, then after dep upgrade and before my change, we got this error:
```
---- execution_test::blockifier_error_mapping stdout ----
thread 'execution_test::blockifier_error_mapping' panicked at crates/papyrus_execution/src/execution_test.rs:871:5:
assertion failed: `(left == right)`

Diff < left / right > :
<Contract constructor execution has failed: Execution failed due to recursion depth exceeded. Execution failed due to recursion depth exceeded.
>Contract constructor execution has failed. Execution failed due to recursion depth exceeded.
```
and if I only fix `ExecutionError::from` without fixing the test, then the test expects a `.` but the blockifier returns a `:`.
</blockquote></details>

Ok so we need to make sure everyone use ':' instead of '.'
@ArielElp FYI

**Review by yair-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-:-NnYdpKd5Kg_iwA3E9-q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586#-:-NnZKqHQ5dNivIjOz55c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

**Pull request merged**
