### PR TITLE
Dvir/endpoints to create request

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/505)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/505)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/505#-NOPVhzf45HGB_ZsmSzc:-NOPVhzf45HGB_ZsmSzd:bss3o4e) (no related file):*
first, commit just rename. the second commit does the actual changes in the functions.

___

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/create_request.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/505#-NOrzaOM0mQ7SMdTxZjg:-NOs5LesDT4dgihgj8oO:b-2h501d) ([raw file](https://github.com/starkware-libs/papyrus/blob/2173ea6fb6590cb642a06fb718b55f325deec684/crates/papyrus_load_test/src/create_request.rs#L5)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This function (and the other one as well) is not used anywhere.
Please use these in `transaction.rs` instead of using the done enpoints there.
</blockquote></details>

the next pull request will use them. the done requests currently in the code also will be deleted in the next pull requests.

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/505)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/505#-NOxE1YvBLIYotuVCaLb:-NOxE1YvBLIYotuVCaLc:b-h0rbd3) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b1cfb6b07bcca75fbb74aae19e4562f8f41930f/crates/papyrus_load_test/src/create_request.rs#L9)):*
> ```XML
> }
> 
> pub fn get_block_with_tx_hashes_by_hash(block_hash: String) -> jsonVal {
> ```

Consider `&str` instead



_Code quote:_
```XML
String
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/505#-:-NOy0r3l-UzCHEJvxotE:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
