### PR TITLE
feat(storage)!: add block signature table

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1561)

### CODE REVIEW

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1561)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_storage/src/header_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1561#-NoQrv3i3DaX8wWAMvYT:-NoQrv3i3DaX8wWAMvYU:by7geyj) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4763dfabe1becec0a02d9c36e62f89a6fd34aa3/crates/papyrus_storage/src/header_test.rs#L289)):*
> ```XML
>         Some(signature)
>     );
>     writer.begin_rw_txn().unwrap().revert_header(BlockNumber(0)).unwrap().0.commit().unwrap();
> ```

Consider asserting that the signature is returned



_Code quote:_
```XML
writer.begin_rw_txn().unwrap().revert_header(BlockNumber(0)).unwrap().0.commit().unwrap();
```
___
*[`crates/papyrus_storage/src/lib.rs` line 511 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1561#-NoQrLKM0aHY6tvX_Ofh:-NoQrLKM0aHY6tvX_Ofi:betl559) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4763dfabe1becec0a02d9c36e62f89a6fd34aa3/crates/papyrus_storage/src/lib.rs#L511)):*
> ```XML
>     InvalidBlockNumber { block: BlockNumber, compiled_class_marker: BlockNumber },
>     #[error("Attempt to write block signature of non-existing block {block_number}.")]
>     BlockSignatureForNonExistingBlock { block_number: BlockNumber },
> ```

Consider adding also the signature



_Code quote:_
```XML
BlockSignatureForNonExistingBlock { block_number: BlockNumber },
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_storage/src/header_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1561#-NoQrv3i3DaX8wWAMvYT:-Nof27D_4MvJiCl9qnWc:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4763dfabe1becec0a02d9c36e62f89a6fd34aa3/crates/papyrus_storage/src/header_test.rs#L289)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider asserting that the signature is returned
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 511 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1561#-NoQrLKM0aHY6tvX_Ofh:-Nof2Xif1ypp-rf9kpm4:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4763dfabe1becec0a02d9c36e62f89a6fd34aa3/crates/papyrus_storage/src/lib.rs#L511)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider adding also the signature
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
