### PR TITLE
test(network): add register_broadcast_subscriber for test

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)* status: all files reviewed, 12 unresolved discussions (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 505 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noW5B4UuRprcj0vv6:-O-noW5B4UuRprcj0vv7:bszpzdf) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L505)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

Change to #[cfg(feature = "testing")]. Same in all other places
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 509 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nnh5p7thUYXsz74ZX:-O-nnh5p7thUYXsz74ZY:bvhj5v2) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L509)):*
> ```XML
> 
> #[cfg(test)]
> pub fn test_register_broadcast_subscriber<T, U>()
> ```

change test_ to mock_
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nolZxBEL26vkJ15yh:-O-nolZy-qORcpV193Fv:b-d8n5ez) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
> ```XML
> #[cfg(test)]
> pub fn test_register_broadcast_subscriber<T, U>()
> -> Result<TestSubscriberChannels<T, U>, SubscriptionError>
> ```

You can have just one T. T and U will always be the same
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 530 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nnvCL9Iq9z5aQJbM2:-O-nnvCL9Iq9z5aQJbM3:b-xtzkg1) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L530)):*
> ```XML
>     let broadcasted_messages_receiver = broadcasted_messages_receiver.map(broadcasted_messages_fn);
> 
>     let network_subscribers =
> ```

Rename to subscriber_channels
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 533 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-no6s626L_GL5hNqTc:-O-no6s626L_GL5hNqTd:b-3z5tar) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L533)):*
> ```XML
>         BroadcastSubscriberChannels { messages_to_broadcast_sender, broadcasted_messages_receiver };
> 
>     let mock_messages_to_broadcast_fn: MockMessagesToBroadcastFn<U> =
> ```

Rename to mock_broadcasted_messages_fn and rename the type as well
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-npRlh2IDLuB9OfLWs:-O-npRlh2IDLuB9OfLWt:b-d1bn30) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L539)):*
> ```XML
>         mock_broadcasted_messages_sender.with(mock_messages_to_broadcast_fn);
> 
>     let mock_broadcasted_messages_fn: fn(Bytes) -> U = |x| match U::try_from(x) {
> ```

Rename to mock_messages_to_broadcast_fn
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-npVh30d6hqFbMl_mC:-O-npVh30d6hqFbMl_mD:b84tlzx) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L542)):*
> ```XML
>         Ok(result) => result,
>         Err(_) => {
>             panic!("Failed to convert Bytes to U");
> ```

I guess using unwrap failed because of clippy. Try to do expect instead and see if it works
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 548 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-novC1-HxkgnwvzmMR:-O-novC1-HxkgnwvzmMS:bxemrup) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L548)):*
> ```XML
>         mock_messages_to_broadcast_receiver.map(mock_broadcasted_messages_fn);
> 
>     let mock_network_subscribers = BroadcastNetworkMock {
> ```

Rename to mock_network
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noIR91PNLZ_kCwGlv:-O-noIR91PNLZ_kCwGlw:bvfeb0v) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L594)):*
> ```XML
> }
> 
> pub type TestSubscriberSender<T> = With<
> ```

Rename to MockBroadcastedMessagesSender
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noSwHCARrkaxAoUrJ:-O-noSwHCARrkaxAoUrK:b-n3t3m0) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L594)):*
> ```XML
> }
> 
> pub type TestSubscriberSender<T> = With<
> ```

Add cfg to all these types
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noOxQBa-Dz8DuLo3o:-O-noOxQBa-Dz8DuLo3p:bmt7st3) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L605)):*
> ```XML
>     fn((T, ReportCallback)) -> Ready<Result<(Bytes, ReportCallback), SendError>>;
> 
> pub type TestSubscriberReceiver<T> = Map<Receiver<Bytes>, fn(Bytes) -> T>;
> ```

Rename to MockMessagesToBroadcastReceiver
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 612 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nogsz1MKBdZipao80:-O-nogsz1MKBdZipao81:b7z3hdk) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L612)):*
> ```XML
> }
> 
> pub struct TestSubscriberChannels<T: TryFrom<Bytes>, U: TryFrom<Bytes>> {
> ```

This can be the same T to both types

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)* status: all files reviewed, 16 unresolved discussions (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nruj1EvXxkd3X69Pa:-O-nruj1EvXxkd3X69Pb:b-z9bfxm) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L542)):*
> ```XML
>         Ok(result) => result,
>         Err(_) => {
>             panic!("Failed to convert Bytes to U");
> ```

Change the message to "Failed to convert Bytes that we received from conversion to bytes"

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)* status: all files reviewed, 16 unresolved discussions (waiting on @DvirYo-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 505 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noW5B4UuRprcj0vv6:-O-oBTrdBUN2TEm7eXB0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L505)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change to #[cfg(feature = "testing")]. Same in all other places
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 509 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nnh5p7thUYXsz74ZX:-O-oBZcDB5rxd_2GavRA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L509)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

change test_ to mock_
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nolZxBEL26vkJ15yh:-O-oB_zrBa7i9EwmpApS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can have just one T. T and U will always be the same
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 530 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nnvCL9Iq9z5aQJbM2:-O-oBeMW7BJ6Y-t9oZUx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L530)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to subscriber_channels
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 533 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-no6s626L_GL5hNqTc:-O-oBhqX583qmEVf9ffN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L533)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to mock_broadcasted_messages_fn and rename the type as well
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-npRlh2IDLuB9OfLWs:-O-oBkDI6ICs7IPaR39H:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L539)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to mock_messages_to_broadcast_fn
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nruj1EvXxkd3X69Pa:-O-oBnRO7AiQgODE4iEW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L542)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the message to "Failed to convert Bytes that we received from conversion to bytes"
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-npVh30d6hqFbMl_mC:-O-oBypH9YeSOhL-ZlGK:b-p81obl) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L542)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I guess using unwrap failed because of clippy. Try to do expect instead and see if it works
</blockquote></details>

using expect or unwrap requires adding a Debug bound to the error type, to keep it simpler I used match
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 548 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-novC1-HxkgnwvzmMR:-O-oBqOuCzvLAJO5P_Pl:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L548)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to mock_network
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nqkLkDaqZluRm51uA:-O-oBrBuEeAmKT9avvTn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L560)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

pub
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nqmWY6Q4zkkhPquqI:-O-oBrbm8a_V4FeNv38t:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L560)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to dummy_report_callback
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nqqss9dNUbkZT2ZQs:-O-oBrwK4upOfQ19s0Dp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L560)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

cfg(feature = "testing")
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noIR91PNLZ_kCwGlv:-O-oBtnu0R6MjXmDuD1J:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L594)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to MockBroadcastedMessagesSender
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noSwHCARrkaxAoUrJ:-O-oBuGd2g2X_BoMqqt_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L594)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add cfg to all these types
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-noOxQBa-Dz8DuLo3o:-O-oBv0Y-p47Ny3rJosc:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L605)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to MockMessagesToBroadcastReceiver
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 612 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-nogsz1MKBdZipao80:-O-oBvv96IGCmKckIJtz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/44a3496ac3712848e2d7c96bbaf23b293798caf4/crates/papyrus_network/src/network_manager/mod.rs#L612)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This can be the same T to both types
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-oM3IC5GEPMFV7nkMK:-O-oM3IC5GEPMFV7nkML:b-i7963) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b65882524b1d22f9ff1cc7c18dcc12eb4ba5d55/crates/papyrus_network/src/network_manager/mod.rs#L3)):*
> ```XML
> mod swarm_trait;
> 
> #[cfg(feature = "testing")]
> ```

Not here. This should be cfg(test)
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 553 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-oMLMXEoksjQsTKBpu:-O-oMLMXEoksjQsTKBpv:box82gk) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b65882524b1d22f9ff1cc7c18dcc12eb4ba5d55/crates/papyrus_network/src/network_manager/mod.rs#L553)):*
> ```XML
> }
> 
> #[allow(dead_code)]
> ```

Try to see if clippy passes without this allow

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-oM3IC5GEPMFV7nkMK:-O-oNzkM7UizgJ1uMnWW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b65882524b1d22f9ff1cc7c18dcc12eb4ba5d55/crates/papyrus_network/src/network_manager/mod.rs#L3)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Not here. This should be cfg(test)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 553 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-O-oMLMXEoksjQsTKBpu:-O-oO-d398vyI3njMNK9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b65882524b1d22f9ff1cc7c18dcc12eb4ba5d55/crates/papyrus_network/src/network_manager/mod.rs#L553)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to see if clippy passes without this allow
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2127#-:-O-oOARS5lO3V6BXiBbc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware and @matan-starkware)

**Pull request merged**
