### PR TITLE
chore(config): unite the values of rpc.starknet_url and central.url

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1, @OriStarkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1373#-Nie2F7f4D-J48cQB2_o:-Nie2F7f4D-J48cQB2_p:bfmz48f) (no related file):*
Don't we need to change this in the presets as well?

___
___
*[`config/default_config.json` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1373#-Nie299r4ZAC9RyjjI8Q:-Nie299r4ZAC9RyjjI8R:bqlt2k6) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4cfa6cb4458a9e97101b4cc0986578826f25cb7/config/default_config.json#L72)):*
> ```JSON
>     "value": false
>   },
>   "gateways_url": {
> ```

Please use



_Suggestion:_
```JSON
starknet_url
```

**Comment by dan-starkware** [comment]
Commit type should be chore with config scope, that is, `chore(config): ...`

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @OmriEshhar1, and @yair-starkware)

___
*[`config/default_config.json` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1373#-Nie299r4ZAC9RyjjI8Q:-NihusLb2rgFhhhygp8-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4cfa6cb4458a9e97101b4cc0986578826f25cb7/config/default_config.json#L72)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use
</blockquote></details>

Done.

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`config/default_config.json` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1373#-NijTGt084jwtdMplPUL:-NijTGt084jwtdMplPUM:braqbtt) ([raw file](https://github.com/starkware-libs/papyrus/blob/38ff55e11e3cfe11c92b9df01ca8c9f092ad635c/config/default_config.json#L73)):*
> ```JSON
>   },
>   "starknet_url": {
>     "description": "URL for the Starknet feeder-gateway and for communicating with Starknet in write_api methods. It should match chain_id.",
> ```

Consider changing:
URL for the Starknet gateway and feeder-gateway.



_Code quote:_
```JSON
URL for the Starknet feeder-gateway and for communicating with Starknet in write_api methods.
```

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373#-:-Nj7lJS0Apx-oc0EyIKN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
