### PR TITLE
Stream compiled classes (Cairo 1 Casm)

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/670)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/670)* status: all files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW13dv66fBWwsZ6X-m:-NWW13dv66fBWwsZ6X-n:b-10zu6d) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central.rs#L119)):*
> ```XML
>     ) -> Result<Option<BlockHash>, CentralError>;
> 
>     fn stream_compiled_classes(
> ```

Please document (also previous methods)



_Code quote:_
```XML
 fn stream_compiled_classes
```
___
*[`crates/papyrus_sync/src/sources/central.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWD6L2g-OA0ImguuVEO:-NWD6L2g-OA0ImguuVEP:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central.rs#L219)):*
> ```XML
>                 .flat_map(|maybe_state_diff| match maybe_state_diff {
>                     Ok(state_diff) => {
>                         let res: Vec<CentralResult<(ClassHash, CompiledClassHash)>> = state_diff
> ```





_Suggestion:_
```XML
class_hashes
```
___
*[`crates/papyrus_sync/src/sources/central.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWD7-2XEIaaZXgmaWlk:-NWD7-2XEIaaZXgmaWll:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central.rs#L229)):*
> ```XML
>                 });
> 
>             let mut res = futures_util::stream::iter(class_hashes_iter)
> ```





_Suggestion:_
```XML
compiled_classes
```
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW0G8S9us1XNHeoRRm:-NWW0G8S9us1XNHeoRRn:bwvzhny) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_sync_test.rs#L429)):*
> ```XML
>             }
>         }
> ```

Can you add a TODO for testing also classes  functionality?
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW0AExE5aTZoq7o1PJ:-NWW0AExE5aTZoq7o1PK:b-pzkqr5) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_sync_test.rs#L440)):*
> ```XML
>                     yield i;
>                 }
>             }
> ```

Is there a more elegant way? 



_Code quote:_
```XML
            let res: CompiledClassesStream<'_> = stream! {
                for i in [] {
                    yield i;
                }
            }
```
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 408 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW1ds0-4JrlXAaOPs_:-NWW1ds0-4JrlXAaOPsa:bgjfwzf) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_test.rs#L408)):*
> ```XML
>         .with(predicate::eq(ClassHash(stark_felt!("0x3"))))
>         .times(1)
>         .returning(move |_x| Ok(Some(CasmContractClass::default())));
> ```

Can you loop this?



_Code quote:_
```XML
    mock.expect_compiled_class_by_hash()
        .with(predicate::eq(ClassHash(stark_felt!("0x0"))))
        .times(1)
        .returning(move |_x| Ok(Some(CasmContractClass::default())));
    mock.expect_compiled_class_by_hash()
        .with(predicate::eq(ClassHash(stark_felt!("0x1"))))
        .times(1)
        .returning(move |_x| Ok(Some(CasmContractClass::default())));
    mock.expect_compiled_class_by_hash()
        .with(predicate::eq(ClassHash(stark_felt!("0x2"))))
        .times(1)
        .returning(move |_x| Ok(Some(CasmContractClass::default())));
    mock.expect_compiled_class_by_hash()
        .with(predicate::eq(ClassHash(stark_felt!("0x3"))))
        .times(1)
        .returning(move |_x| Ok(Some(CasmContractClass::default())));
```
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 420 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW1k86CUVRLdaWrfN4:-NWW1k86CUVRLdaWrfN5:b-n6d6dn) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_test.rs#L420)):*
> ```XML
> 
>     for i in 0..4 {
>         println!("{i}");
> ```

Please remove
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW2In_3YnkxC9GfX6B:-NWW2In_3YnkxC9GfX6C:bmn2sv0) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_test.rs#L425)):*
> ```XML
>         let expected_class_hash = ClassHash(stark_felt!(format!("0x{i}").as_str()));
>         let expected_compiled_class_hash =
>             CompiledClassHash(stark_felt!(format!("0x{i}").as_str()));
> ```

Can you create the felt once and reuse it?



_Code quote:_
```XML
stark_felt!(format!("0x{i}").as_str())
```
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW3HWN8x1YAwNGcdpb:-NWW3HWN8x1YAwNGcdpc:by1sx0s) ([raw file](https://github.com/starkware-libs/papyrus/blob/74143c3f49b9be99bfea0e41835c2012f3ddf394/crates/papyrus_sync/src/sources/central_test.rs#L426)):*
> ```XML
>         let expected_compiled_class_hash =
>             CompiledClassHash(stark_felt!(format!("0x{i}").as_str()));
>         let expected_compiled_class = CasmContractClass::default();
> ```

Please move out of the loop

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/670)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW13dv66fBWwsZ6X-m:-NWWXajA31vzMHHYGewo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central.rs#L119)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document (also previous methods)
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWD6L2g-OA0ImguuVEO:-NWWXulC7qnBCTNOVJQr:b-9ne0r4) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central.rs#L219)):*
> ```XML
>                 .flat_map(|maybe_state_diff| match maybe_state_diff {
>                     Ok(state_diff) => {
>                         let res: Vec<CentralResult<(ClassHash, CompiledClassHash)>> = state_diff
> ```

Removed the variable
___
*[`crates/papyrus_sync/src/sources/central.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWD7-2XEIaaZXgmaWlk:-NWWYfB03fCUuDm0tnPZ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central.rs#L229)):*
> ```XML
>                 });
> 
>             let mut res = futures_util::stream::iter(class_hashes_iter)
> ```

Done
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW0G8S9us1XNHeoRRm:-NWWZ-jH7IGMwbO1JW1K:b3sizot) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_sync_test.rs#L429)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you add a TODO for testing also classes  functionality?
</blockquote></details>

WDYM? This tests the general syncing, not the content of the blocks.
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW0AExE5aTZoq7o1PJ:-NWWZQsf4W20Q6Erz0Ul:b7gszdq) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_sync_test.rs#L440)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is there a more elegant way? 
</blockquote></details>

Didn't find one
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 408 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW1ds0-4JrlXAaOPs_:-NWW_xzM0V83FsjTCHR6:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_test.rs#L408)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you loop this?
</blockquote></details>

Done
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 420 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW1k86CUVRLdaWrfN4:-NWWa-k79mS-QvQLBcoP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_test.rs#L420)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW2In_3YnkxC9GfX6B:-NWWdNJ4AH9tqm8u4XIB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_test.rs#L425)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you create the felt once and reuse it?
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW3HWN8x1YAwNGcdpb:-NWWdLb0BRgLc9mXmCrx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central_test.rs#L426)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move out of the loop
</blockquote></details>

Done.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_sync/src/sources/central.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW13dv66fBWwsZ6X-m:-NWWs7897Y3yvxeQeKaW:bxal44m) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central.rs#L119)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please use [doc-comments](https://doc.rust-lang.org/rust-by-example/meta/doc.html#doc-comments)?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/670)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/670)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/670#-NWW13dv66fBWwsZ6X-m:-NWX03rm674zFltdJKOw:b-f3yizy) ([raw file](https://github.com/starkware-libs/papyrus/blob/24eb84c54267d77f24d9d7b2b855be60d73647fe/crates/papyrus_sync/src/sources/central.rs#L119)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can you please use [doc-comments](https://doc.rust-lang.org/rust-by-example/meta/doc.html#doc-comments)?
</blockquote></details>

As discussed, doc comments should probably be used in public interfaces and not everywhere.

**Pull request merged**
