### PR TITLE
feat(sync): add profiling to p2p state diff sync

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-Nvkmg8C14ZEBJSVa5NN:-Nvkmg8D5oh79cxocGFE:b-cjn7ju) (no related file):*
Add units as described here: https://prometheus.io/docs/practices/naming/

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-Nvkmg8C14ZEBJSVa5NN:-NvlCo8MBP0JuK2jrtol:b-896fix) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Add units as described here: https://prometheus.io/docs/practices/naming/
</blockquote></details>

Done.

___

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-Nvkmg8C14ZEBJSVa5NN:-NvlGAs05NqXhKZ7Lry-:b-9o0olm) (no related file):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just make it pass clippy. You may also need to remove the metrics dependency from the cargo toml file

___

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-NvlGg-ED1C5YI_Z11kH:-NvlGg-ED1C5YI_Z11kI:b23nzap) (no related file):*
and change secodns to seconds

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-Nvkmg8C14ZEBJSVa5NN:-NvlOV2tDQXZmUJrZa6S:b-896fix) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Just make it pass clippy. You may also need to remove the metrics dependency from the cargo toml file
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-NvlGg-ED1C5YI_Z11kH:-NvlOVNyDjTP2nacl2PA:b-896fix) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

and change secodns to seconds
</blockquote></details>

Done.

___

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1923#-:-NvlOfvU3xhcAKcCgT3X:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

**Pull request merged**
