### PR TITLE
feat(sync): sync pending data

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/sources/pending.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NeIkRHt1ZD-Z3HplyWk:-NeIkRHt1ZD-Z3HplyWl:b-s0gc68) ([raw file](https://github.com/starkware-libs/papyrus/blob/46d398cb0ad4086ed4196b7190a17bd667bfe498/crates/papyrus_sync/src/sources/pending.rs#L37)):*
> ```XML
> #[cfg_attr(test, automock)]
> #[async_trait]
> pub trait PendingSourceTrait {
> ```

Also, pending class sync will be added to this trait.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NebQ-go-84a5osrVc6u:-NebQ-go-84a5osrVc6v:bovdjpy) (no related file):*
If you think we should do the pending sync in a different task, lets talk about this. There are disadvantages but they are not so bad.

___
___
*[`crates/papyrus_sync/src/sources/pending.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NebPllk1NcIjrg-Fces:-NebPllk1NcIjrg-Fcet:budsyj1) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/sources/pending.rs#L45)):*
> ```XML
>     for GenericPendingSource<TStarknetClient>
> {
>     async fn get_pending_data(&self) -> Result<PendingData, PendingError> {
> ```

Maybe I will change the return type to something more convenient to our gateway (currently, the format is what the feeder returns)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 629 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesOe_KDQEQ_nc4VMV9:-NesOe_KDQEQ_nc4VMVA:bg3t0h) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L629)):*
> ```XML
> }
> 
> #[allow(clippy::too_many_arguments)]
> ```

Consider gathering in a single `pending` argument instead. 



_Code quote:_
```XML
#[allow(clippy::too_many_arguments)]
```
___
*[`crates/papyrus_sync/src/lib.rs` line 645 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesOsoYCakzF5upB4sX:-NesOsoYCakzF5upB4sY:b-iofwn3) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L645)):*
> ```XML
>     try_stream! {
>         loop {
> ```

Please remove the empty line
___
*[`crates/papyrus_sync/src/lib.rs` line 657 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesPCNvBLnR7LQGuhvE:-NesPCNvBLnR7LQGuhvF:bxiuy1h) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L657)):*
> ```XML
>             if header_marker == central_block_marker {
>                 // Only if the node is fully synced until the last known block (and the chain isn't empty), sync pending data.
>                 if reader.begin_ro_txn()?.get_state_marker()? == header_marker && header_marker!=BlockNumber::default(){
> ```

Do we have this functionality elsewhere?
Assuming this logic is common and going to change, probably better having this as a function



_Code quote:_
```XML
reader.begin_ro_txn()?.get_state_marker()? == header_marker
```
___
*[`crates/papyrus_sync/src/lib.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesQM7A9u7ppw2L8XJs:-NesQM7A9u7ppw2L8XJt:b6htzqn) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L887)):*
> ```XML
>             header_marker
>                 .prev()
>                 .expect("We start asking for pending data only if the chain isn't empty"),
> ```

Can there be a race condition in which a revert happened s.t there is no prev?
Why not returning instead? 



_Code quote:_
```XML
.expect("We start asking for pending data only if the chain isn't empty"),
```
___
*[`crates/papyrus_sync/src/sync_test.rs` line 253 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesS6sv4wQyEN3folM4:-NesS6sv4wQyEN3folM5:bj1103f) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/sync_test.rs#L253)):*
> ```XML
>         block.block.parent_block_hash = BlockHash(stark_felt!("0x1"));
>         Ok(block)
>     });
> ```

Please explain this part



_Code quote:_
```XML
    mock_pending_source.expect_get_pending_data().times(1).returning(|| {
        let mut block = PendingData::default();
        block.block.parent_block_hash = BlockHash(stark_felt!("0x1"));
        Ok(block)
    });
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 629 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesOe_KDQEQ_nc4VMV9:-NfKW3aZBBncC8tx7aLy:b-uc8yy3) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L629)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider gathering in a single `pending` argument instead.
</blockquote></details>

I added to do. I will know how to deal with that better when I finish the pending class sync.
___
*[`crates/papyrus_sync/src/lib.rs` line 645 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesOsoYCakzF5upB4sX:-NfKWHKZ2G2_0SfQPOtT:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L645)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove the empty line
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 657 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesPCNvBLnR7LQGuhvE:-NfKWMOb9drns7gRbRCz:b-gi92ny) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L657)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we have this functionality elsewhere?
Assuming this logic is common and going to change, probably better having this as a function
</blockquote></details>

I don't see this functionality elsewhere. 
___
*[`crates/papyrus_sync/src/lib.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-NesQM7A9u7ppw2L8XJs:-NfKWttO4Oq5zauch3tk:b111jgk) ([raw file](https://github.com/starkware-libs/papyrus/blob/939e0f6c0cb99d76018bffdf74cda35647937ea6/crates/papyrus_sync/src/lib.rs#L887)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can there be a race condition in which a revert happened s.t there is no prev?
Why not returning instead?
</blockquote></details>

All the sync happens on a single thread, so if a revert happens, the sync will restart, and we check again that the chain is empty.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1175#-:-NfR8Mhu9tRZZN4h_Nhr:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
