### PR TITLE
refactor(base_layer): serialize required node url

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcrbvQ53W7J1qxOCNWj):*
It should be a refactor type.
___
*[`config/default_config.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcrcINr6c5hTvUnQwuc:-NcrcINr6c5hTvUnQwud:by3ya4p) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/config/default_config.json#L4)):*
> ```JSON
>   "base_layer.node_url": {
>     "description": "Ethereum node URL.",
>     "required_type": "String"
> ```

Where is the value line? Is it possible to change this value from the config file?
___
*[`crates/papyrus_node/src/config/config_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcreTrm5lQyMtMIx94P:-NcreTrnDXyQPIwmaEjr:boffejb) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_node/src/config/config_test.rs#L34)):*
> ```XML
> fn load_default_config() {
>     env::set_current_dir(get_absolute_path("")).expect("Couldn't set working dir.");
>     NodeConfig::load_and_process(get_args(vec![])).expect("Failed to load the config.");
> ```

Before this change required args() returned only the required arguments now the get_args(vec![]) returns beside the required args also Papyrus in the beginning, this is what you want?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcrbvQ53W7J1qxOCNWj):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

It should be a refactor type.
</blockquote></details>

Done.
___
*[`config/default_config.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcrcINr6c5hTvUnQwuc:-Ncur9gM7OC-Chg95Krx:b-wx3ts5) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/config/default_config.json#L4)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Where is the value line? Is it possible to change this value from the config file?
</blockquote></details>

There is no default value to change. You can set a value in a custom config file or by the command line args. Users should not edit the default config file.
If you don't set any value, the loading fails.
___
*[`crates/papyrus_node/src/config/config_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcreTrm5lQyMtMIx94P:-NcusvWM-vOGlAIKrNrs:b-9a9wnj) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_node/src/config/config_test.rs#L34)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Before this change required args() returned only the required arguments now the get_args(vec![]) returns beside the required args also Papyrus in the beginning, this is what you want?
</blockquote></details>

Yes.
There was a bug in the previous version.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @DvirYo-starkware and @yoavGrs)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcriQYY8WXqznFXKQ0q:-NcriQYY8WXqznFXKQ0r:bgxxfh0) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L48)):*
> ```XML
>     fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
>         BTreeMap::from_iter([
>             ser_required_param("node_url", SerializationType::String, "Ethereum node URL."),
> ```

Please add more precise doc, see Junos: https://juno.nethermind.io/config/#:~:text=%23%20Websocket%20endpoint%20of%20the%20Ethereum%20node%20used%20to%20verify%20the%20L2%20chain.%0A%23%20If%20using%20Infura%2C%20it%20looks%20something%20like%20%60wss%3A//mainnet.infura.io/ws/v3/your%2Dinfura%2Dproject%2Did%60



_Code quote:_
```XML
Ethereum node URL.
```
___
*[`crates/papyrus_node/src/config/config_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcreTrm5lQyMtMIx94P:-Ncrh2aoDwaAvScteGzj:b6f2nmr) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_node/src/config/config_test.rs#L34)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Before this change required args() returned only the required arguments now the get_args(vec![]) returns beside the required args also Papyrus in the beginning, this is what you want?
</blockquote></details>

Maybe the `required_args` can find what the required args from the default file by itself, and fill the value from there?
Why do we need to pass anything besides the required params?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcriQYY8WXqznFXKQ0q:-Ncv3jDk49iHQKYAEYrO:b-je6z2d) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L48)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add more precise doc, see Junos: https://juno.nethermind.io/config/#:~:text=%23%20Websocket%20endpoint%20of%20the%20Ethereum%20node%20used%20to%20verify%20the%20L2%20chain.%0A%23%20If%20using%20Infura%2C%20it%20looks%20something%20like%20%60wss%3A//mainnet.infura.io/ws/v3/your%2Dinfura%2Dproject%2Did%60
</blockquote></details>

Reverting some of my changes.
___
*[`crates/papyrus_node/src/config/config_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1112#-NcreTrm5lQyMtMIx94P:-NcuxLfH3w87mXbewD6W:b4o1ke6) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c8b678f92b484d3d2b5f693709b9b2e67bffd9/crates/papyrus_node/src/config/config_test.rs#L34)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Maybe the `required_args` can find what the required args from the default file by itself, and fill the value from there?
Why do we need to pass anything besides the required params?
</blockquote></details>

All the tests here (that call `load_and_process`) need the command name and the required params. In some of them, we pass additional args.
In the default file,  the required args have only type, no value.

These functions are utils for testing the config loading. When we use more required args, developing a more intelligent mechanism would be good.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1112)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
