### PR TITLE
chore(config): add ConsensusConfig

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sN6XA38EgbHZ583jz:-O0sN6XB7sgyfSfYP2ff:b-9hjrro) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/papyrus_node/src/config/config_test.rs#L52)):*
> ```XML
>                 serialization_type
>             }
>         };
> ```

Why are we adding this here? Does the consensus config add something significant new to our configs? There already are optional fields.



_Suggestion:_
```XML
                let parent_path =
                    param_path.split('.').collect::<Vec<&str>>().first().unwrap().to_string();
                let parent_json_value =
                    parent_path.split('.').fold(&mut config_presentation, |entry, config_name| {
                        entry.index_mut(config_name)
                    });
                // Skip the param if it is a field of an optional component and by default is None.
                if parent_json_value.is_null() {
                    continue;
                }
                serialization_type
            }
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sNuNm-ftFgSfF0W7a:-O0sNuNm-ftFgSfF0W7b:b-avmcfa) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/sequencing/papyrus_consensus/src/lib.rs#L39)):*
> ```XML
> /// Configuration for consensus.
> #[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
> pub struct ConsensusConfig {
> ```

Please create a new file `config.rs` for this.



_Code quote:_
```XML
pub struct ConsensusConfig {
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sO_xiEd4dsNUugdsR:-O0sO_xiEd4dsNUugdsS:b-f94k8q) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/sequencing/papyrus_consensus/src/lib.rs#L75)):*
> ```XML
>     fn default() -> Self {
>         Self {
>             validator_id: ValidatorId::default(),
> ```

I am fine having a default for the sake of unit testing. I want to make sure that if someone actually runs papyrus with consensus they must explicitly give the validator_id still, right?



_Code quote:_
```XML
            validator_id: ValidatorId::default(),
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sN6XA38EgbHZ583jz:-O0sPJRn6cfJuB10sfPj:b-2zv2ws) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/papyrus_node/src/config/config_test.rs#L52)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why are we adding this here? Does the consensus config add something significant new to our configs? There already are optional fields.
</blockquote></details>

validator_id is the first scenario of a required param inside an optional component, and the code doesn't take this into consideration
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sNuNm-ftFgSfF0W7a:-O0sTSPbDwVipAHppg35:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/sequencing/papyrus_consensus/src/lib.rs#L39)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please create a new file `config.rs` for this.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sO_xiEd4dsNUugdsR:-O0sR7lw2TkLWwu13mfO:b-4v5z23) ([raw file](https://github.com/starkware-libs/papyrus/blob/b211afffe61f723c524a5dfb0fcad90f38f4cde9/crates/sequencing/papyrus_consensus/src/lib.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I am fine having a default for the sake of unit testing. I want to make sure that if someone actually runs papyrus with consensus they must explicitly give the validator_id still, right?
</blockquote></details>

yes, if they don't provide it, the node won't run with consensus

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sX5NT1UJTSwKvW9SF:-O0sX5NT1UJTSwKvW9SG:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a8afbffc65e40aa32c42c13b800ed4c40530f5c/crates/papyrus_node/src/config/config_test.rs#L50)):*
> ```XML
>                     continue;
>                 }
>                 serialization_type
> ```





_Suggestion:_
```XML
                let parent_path = param_path.split('.').next().unwrap().to_string();
                let parent_json_value =
                    parent_path.split('.').fold(&mut config_presentation, |entry, config_name| {
                        entry.index_mut(config_name)
                    });
                // Skip the param if it is a field of an optional component and by default is None.
                if parent_json_value.is_null() {
                    continue;
                }
                serialization_type
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sY-0vD5Aed1nIVylw:-O0sY-0vD5Aed1nIVylx:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a8afbffc65e40aa32c42c13b800ed4c40530f5c/crates/sequencing/papyrus_consensus/src/config.rs#L20)):*
> ```XML
>     pub start_height: BlockNumber,
> }
> impl SerializeConfig for ConsensusConfig {
> ```





_Suggestion:_
```XML
}

impl SerializeConfig for ConsensusConfig {
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sXR9bD_yzeoGWbSPy:-O0sXR9bD_yzeoGWbSPz:brdwn8f) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a8afbffc65e40aa32c42c13b800ed4c40530f5c/crates/sequencing/papyrus_consensus/src/lib.rs#L16)):*
> ```XML
> use types::{ConsensusBlock, ConsensusContext, ConsensusError, ProposalInit, ValidatorId};
> 
> #[allow(missing_docs)]
> ```

What documentation is missing?

I think this would actually be a good thing to document from the start since this is something that people who aren't super familiar with consensus may interact with the config to run the node at different points.



_Code quote:_
```XML
#[allow(missing_docs)]
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sY-0vD5Aed1nIVylw:-O0sYmUuAjUyiCGWuw7I:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a8afbffc65e40aa32c42c13b800ed4c40530f5c/crates/sequencing/papyrus_consensus/src/config.rs#L20)):*
> ```XML
>     pub start_height: BlockNumber,
> }
> impl SerializeConfig for ConsensusConfig {
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sXR9bD_yzeoGWbSPy:-O0siHnZ3e9uKLwuL9Ku:bl4fmvv) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a8afbffc65e40aa32c42c13b800ed4c40530f5c/crates/sequencing/papyrus_consensus/src/lib.rs#L16)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What documentation is missing?

I think this would actually be a good thing to document from the start since this is something that people who aren't super familiar with consensus may interact with the config to run the node at different points.
</blockquote></details>

documentation above the mod, Done

**Review by matan-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0sqLzq4BUD-p0Z5_mi:-O0sqLzq4BUD-p0Z5_mj:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/ba82257634b69d489788a571b8c53471835bee70/crates/sequencing/papyrus_consensus/src/lib.rs#L17)):*
> ```XML
> 
> /// The module contains `ConsensusConfig`, which holds the
> /// configuration details for the consensus mechanism.
> ```





_Suggestion:_
```XML
/// Configures how consensus should run.
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 5 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`config/default_config.json` line 78 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0u79-y1evBBj9HOb5b:-O0u79-y1evBBj9HOb5c:blgvls8) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/config/default_config.json#L78)):*
> ```JSON
>   },
>   "consensus.#is_none": {
>     "description": "Flag for an optional field",
> ```

Can this be something more descriptive?



_Code quote:_
```JSON
"description": "Flag for an optional field"
```
___
*[`config/default_config.json` line 83 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0u7Qky1V0jyRRQ4PMQ:-O0u7Qky1V0jyRRQ4PMR:bcgfnx2) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/config/default_config.json#L83)):*
> ```JSON
>   },
>   "consensus.start_height": {
>     "description": "The height to start the consensus from.",
> ```

Please be consistent with full stop punctuation mark.



_Code quote:_
```JSON
"description": "The height to start the consensus from.",
```
___
*[`crates/papyrus_node/src/main.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uHrpcBqZpXY_8ahYW:-O0uHrpcBqZpXY_8ahYX:b-n6d6dn) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/papyrus_node/src/main.rs#L124)):*
> ```XML
>         consensus_channels.messages_to_broadcast_sender,
>     );
>     // TODO(dvir): add option to configure this value.
> ```

Please remove
___
*[`crates/papyrus_node/src/config/mod.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uKyri6Jb2SWQq2Zx-:-O0uKyri6Jb2SWQq2Zx0:b-pnl5ds) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/papyrus_node/src/config/mod.rs#L96)):*
> ```XML
>         let mut sub_configs = vec![
>             append_sub_config_name(self.central.dump(), "central"),
>             append_sub_config_name(self.central.dump(), "central"),
> ```

Not related, any reason this appears twice? 



_Code quote:_
```XML
            append_sub_config_name(self.central.dump(), "central"),
            append_sub_config_name(self.central.dump(), "central"),
```
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 13 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uBPNxEl8yfK72ElVR:-O0uBPNy1W2tQNGGdU5s:b-c3oi5h) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/sequencing/papyrus_consensus/Cargo.toml#L13)):*
> ```TOML
> futures.workspace = true
> papyrus_network = { path = "../../papyrus_network", version = "0.4.0-dev.2" }
> papyrus_config = { path = "../../papyrus_config", version = "0.4.0-dev.3" }
> ```

Why is it not aligned to the other versions?
If needed, please add a preceding PR bumping other versions.



_Code quote:_
```TOML
"0.4.0-dev.3"
```
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uB64Z2aAALSRXBvNG:-O0uB64Z2aAALSRXBvNH:bpakffu) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/sequencing/papyrus_consensus/Cargo.toml#L21)):*
> ```TOML
> tokio = { workspace = true, features = ["full"] }
> tracing.workspace = true
> serde = { workspace = true, features = ["derive"] }
> ```

Please sort alphabetically 



_Code quote:_
```TOML
serde = { workspace = true, features = ["derive"] }
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uALDXDq-sA0SpBT3o:-O0uALDXDq-sA0SpBT3p:b-35398i) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/sequencing/papyrus_consensus/src/config.rs#L16)):*
> ```XML
>     pub validator_id: ValidatorId,
>     /// The network topic of the consensus.
>     pub topic: String,
> ```

@matan-starkware not related to this PR, please consider with @ShahakShama having a wrapper around String, or at least an alias. 



_Code quote:_
```XML
 pub topic: String,
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0u92l40ZioYf_2BdWa:-O0u92l40ZioYf_2BdWb:b-e17dw9) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/sequencing/papyrus_consensus/src/lib.rs#L16)):*
> ```XML
> use types::{ConsensusBlock, ConsensusContext, ConsensusError, ProposalInit, ValidatorId};
> 
> /// Configures how consensus should run.
> ```

IMO it should be in the module itself (maybe even redundant?).
See [commenting contained items](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#commenting-contained-items)



_Code quote:_
```XML
/// Configures how consensus should run.
```

**Comment by dan-starkware** [comment]
Please fix the corresponding README accordingly

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uLpRf-j8EMYO3P7PK:-O0x4hmQEqJs7PRT2u-X:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix the corresponding README accordingly
</blockquote></details>

Done.

___
___
*[`config/default_config.json` line 78 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0u79-y1evBBj9HOb5b:-O0wcfjk7DQIEd18CSHZ:b-uoq76q) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/config/default_config.json#L78)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can this be something more descriptive?
</blockquote></details>

dump_config is responsible for adding this
___
*[`crates/papyrus_node/src/main.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uHrpcBqZpXY_8ahYW:-O0wbas48ZLnUudYu4x1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/papyrus_node/src/main.rs#L124)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2191#-O0uKyri6Jb2SWQq2Zx-:-O0wg36a-5VI6Xd-FWom:b-fxu4ja) ([raw file](https://github.com/starkware-libs/papyrus/blob/88351d38d1e8c20961d0c2f3799116d1bda12884/crates/papyrus_node/src/config/mod.rs#L96)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not related, any reason this appears twice?
</blockquote></details>

nope, deleted

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r3, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2191)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
