### PR TITLE
Add process metrics (memory and cpu usage).

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/719)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/719)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_monitoring_gateway/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/719#-NXJuI3tDwegL47dFijb:-NXJuI3uBUS3E-p0jVas:b-esll4m) ([raw file](https://github.com/starkware-libs/papyrus/blob/6495dd7a973b0b8953191cdd42c71631c17aeeb4/crates/papyrus_monitoring_gateway/Cargo.toml#L11)):*
> ```TOML
> hyper = { workspace = true, features = ["full"] }
> metrics-exporter-prometheus = { version = "0.12.1" }
> metrics-process = { version = "1.0.11" }
> ```

Why not in the workspace?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/719)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_monitoring_gateway/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/719#-NXJuI3tDwegL47dFijb:-NXJxTb79n2Vjx3_8dHM:btde479) ([raw file](https://github.com/starkware-libs/papyrus/blob/6495dd7a973b0b8953191cdd42c71631c17aeeb4/crates/papyrus_monitoring_gateway/Cargo.toml#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not in the workspace?
</blockquote></details>

Because the only use in those crates will be in the monitoring crate

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/719)* status: all files reviewed, 1 unresolved discussion

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/719)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
