### PR TITLE
feat(monitoring): update grafana.json

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113)

### CODE REVIEW

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1113#-Nd0ScgUCVV3aX7F0ilC:-Nd0ScgUCVV3aX7F0ilD:b-9isks) (no related file):*
Link to the Grafana: 
https://grafana.integration.gcp.starkex.co/d/Tv-UWle4k/papyrus-integration-ori?orgId=1&var-Pod=papyrus-mainnet-16g-bm&from=now-15m&to=now&var-namespace=papyrus-mainnet-16g-bm&var-pod=papyrus-mainnet-16g-bm-bf77597c5-lggfn

___

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @OriStarkware)

___
*[`Monitoring/grafana.json` line 2011 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1113#-Nd454CH6nj1T-a6_xCO:-Nd454CH6nj1T-a6_xCP:b-7s6wt8) ([raw file](https://github.com/starkware-libs/papyrus/blob/dfe1eec7897f805963880d32aaecd69d9499c6c2/Monitoring/grafana.json#L2011)):*
> ```JSON
>   "timepicker": {},
>   "timezone": "",
>   "title": "Papyrus-integration-ori",
> ```

clean

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`Monitoring/grafana.json` line 2011 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1113#-Nd454CH6nj1T-a6_xCO:-Nd4JjbP4hxGixmSDCNH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/dfe1eec7897f805963880d32aaecd69d9499c6c2/Monitoring/grafana.json#L2011)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

clean
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @OriStarkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1113#-:-NdP6gXq5GIyQaXU8_z5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

**Pull request merged**
