### PR TITLE
fix: disable block commitment calculation

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240)

### CODE REVIEW

**Review by yoavGrs — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240#-:-NgDWcIL52WmIXwl6HY6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1240#-NgDW4qw-gPVbiRS1T_x:-NgDW4qw-gPVbiRS1T_y:b-99l76n) (no related file):*
I'm putting my next PR that uses the commitments to validate the block hash on hold.

___

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1240#-:-NgYFpqVC_RQcLJeUL-S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
