### PR TITLE
add tests for erro flow in sync

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #772** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/772" target="_blank">Graphite</a> 
    * **PR #770** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/770" target="_blank">Graphite</a> 
      * **PR #773** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/773" target="_blank">Graphite</a> 
        * **PR #774** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/774" target="_blank">Graphite</a> 
          * **PR #775** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/775" target="_blank">Graphite</a> 
            * **PR #776** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/776" target="_blank">Graphite</a> 
              * **PR #781** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/781" target="_blank">Graphite</a>  👈
              * **PR #771** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/771" target="_blank">Graphite</a> 
                * **PR #763** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/763" target="_blank">Graphite</a> 
                * **PR #762** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/762" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/781?utm_source=stack-comment).

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQC1rt4j6jiq8bLHm9:-NZQC1rt4j6jiq8bLHmA:bj67wbu) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/lib.rs#L113)):*
> ```XML
>                 // A recoverable error occurred. Sleep and try syncing again.
>                 Err(err) if is_recoverable(&err) => {
>                     warn!("Recoverable error encountered while syncing, error: {}", err);
> ```

Instrument the function (tracing)
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQDyCe7jBuueqVgjWb:-NZQDyCe7jBuueqVgjWc:bqgnjk6) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L451)):*
> ```XML
>     let _ = simple_logger::init_with_env();
> 
>     // Mock central with one block but return wrong header.
> ```

Use constants to make it more clear what happens where:
const CORRECT_BLOCK_HASH =...
const WRONG_BLOCK_HASH =...
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 499 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQEdTb5M0HIGP1fzOr:-NZQEdTb5M0HIGP1fzOs:bi0rh95) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L499)):*
> ```XML
>         sync_result = sync_future => assert!(sync_result.is_err()),
>         storage_check_result = check_storage_future => assert!(storage_check_result),
>     }
> ```

Shouldn't this be inside a loop or something?
You want to call this twice



_Code quote:_
```XML
    tokio::select! {
        sync_result = sync_future => assert!(sync_result.is_err()),
        storage_check_result = check_storage_future => assert!(storage_check_result),
    }
```
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQHDGg6psuWxGXo32X:-NZQHDGg6psuWxGXo32Y:becjltk) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L517)):*
> ```XML
>                 if block_number.0 == 1 {
>                     yield Err(CentralError::BlockNotFound { block_number });
>                 }
> ```

Use match (not blocking)



_Code quote:_
```XML
                if block_number.0 >= 2 {
                    yield Err(CentralError::BlockNotFound { block_number });
                }
                if block_number.0 == 1 {
                    yield Err(CentralError::BlockNotFound { block_number });
                }
```
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 570 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQIbKt7nkF2bN1y0yD:-NZQIbKt7nkF2bN1y0yE:b-wu3k4j) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L570)):*
> ```XML
>             assert!(storage_check_result)
>         },
>     }
> ```

I'm not sure it actually checks the recovery, don't you need a mechanism that once the error was encountered the central will stop producing the faulty streams? like in the reverts.
I think the test can pass before encountering the error



_Code quote:_
```XML
    tokio::select! {
        sync_result = sync_future => {
            println!("sync_result: {:?}", sync_result);
            assert!(sync_result.is_ok())
        },
        storage_check_result = check_storage_future => {
            println!("storage_check_result: {:?}", storage_check_result);
            assert!(storage_check_result)
        },
    }
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQC1rt4j6jiq8bLHm9:-NZQLbN-97kEeHST1SgR:b-7uhycb) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/lib.rs#L113)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Instrument the function (tracing)
</blockquote></details>

dismiss
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQDyCe7jBuueqVgjWb:-NZQKCJg3ztiEzpzmRcf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L451)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use constants to make it more clear what happens where:
const CORRECT_BLOCK_HASH =...
const WRONG_BLOCK_HASH =...
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 499 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQEdTb5M0HIGP1fzOr:-NZQQKtu34v-Tq9fvxSj:b-ldrmxz) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L499)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't this be inside a loop or something?
You want to call this twice
</blockquote></details>

replaced with join
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQHDGg6psuWxGXo32X:-NZQQJs157wfhD6jrBkF:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L517)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use match (not blocking)
</blockquote></details>

removed
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 570 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQIbKt7nkF2bN1y0yD:-NZQQI553JBr5a9aaFsK:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/4418cc6cb57b1daacc436b29455a0d17c0d1f432/crates/papyrus_sync/src/sources/central_sync_test.rs#L570)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I'm not sure it actually checks the recovery, don't you need a mechanism that once the error was encountered the central will stop producing the faulty streams? like in the reverts.
I think the test can pass before encountering the error
</blockquote></details>

removed

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 489 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQRxiDBE-HmZRLClcD:-NZQRxiDBE-HmZRLClcE:bnat62m) ([raw file](https://github.com/starkware-libs/papyrus/blob/398681728c3c5e0dc8aa6cdac10d42fe4a1013f2/crates/papyrus_sync/src/sources/central_sync_test.rs#L489)):*
> ```XML
>     let sync_future = run_sync(reader.clone(), writer, mock);
>     let sync_res = tokio::join! {sync_future};
>     assert!(sync_res.0.is_err());
> ```

Assert that it is the expected error, not just any error (also, you can use unwrap_err)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 489 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZQRxiDBE-HmZRLClcD:-NZQZO4jCyYUtvh_i20l:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/398681728c3c5e0dc8aa6cdac10d42fe4a1013f2/crates/papyrus_sync/src/sources/central_sync_test.rs#L489)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Assert that it is the expected error, not just any error (also, you can use unwrap_err)
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZWDhtj08JzStkp6vwq:-NZWDhtj08JzStkp6vwr:b-b0bfkn) ([raw file](https://github.com/starkware-libs/papyrus/blob/29f619d530e3fa001b8ed9f0f2bbebcee714ffaa/crates/papyrus_sync/src/sources/central_sync_test.rs#L28)):*
> ```XML
> const SLEEP_DURATION_INT: u32 = 1000 * 1000 * 100;
> const SYNC_SLEEP_DURATION: Duration = Duration::new(0, SLEEP_DURATION_INT); // 100ms
> const DURATION_BEFORE_CHECKING_STORAGE: Duration = Duration::new(0, SLEEP_DURATION_INT * 2); // 200ms twice the sleep duration of the sync loop.
> ```

Not blocking:
SYNC_SLEEP_DURATION.saturating_mul(2)



_Code quote:_
```XML
Duration::new(0, SLEEP_DURATION_INT * 2)
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 488 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZeS0ABCVV4WHIilDax:-NZeS0ABCVV4WHIilDay:bgovnco) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6a582a209a12f248489037448a72d03cee6ef5/crates/papyrus_sync/src/sources/central_sync_test.rs#L488)):*
> ```XML
>     // make get_block_hash return a hash for the wrong block number
>     mock.expect_get_block_hash()
>         .returning(|_| Ok(Some(create_block_hash(WRONG_BLOCK_NUMBER, false))));
> ```

Consider extracting this whole thing to a constant 



_Code quote:_
```XML
create_block_hash(WRONG_BLOCK_NUMBER, false)
```
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 493 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZeSHhQ7eMQoP_e2eFG:-NZeSHhQ7eMQoP_e2eFH:b-rtagwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6a582a209a12f248489037448a72d03cee6ef5/crates/papyrus_sync/src/sources/central_sync_test.rs#L493)):*
> ```XML
>     let sync_future = run_sync(reader.clone(), writer, mock);
>     let sync_res = tokio::join! {sync_future};
>     println!("sync_res: {:?}", sync_res.0);
> ```

delete



_Code quote:_
```XML
println!("sync_res: {:?}", sync_res.0);
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 488 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZeS0ABCVV4WHIilDax:-N_8qhmP7kMll0YyamCt:bmm316l) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6a582a209a12f248489037448a72d03cee6ef5/crates/papyrus_sync/src/sources/central_sync_test.rs#L488)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider extracting this whole thing to a constant 
</blockquote></details>

used only once.. seems redundant
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 493 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/781#-NZeSHhQ7eMQoP_e2eFG:-N_8qh_f0lo5OlZy-Bhj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0c6a582a209a12f248489037448a72d03cee6ef5/crates/papyrus_sync/src/sources/central_sync_test.rs#L493)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781#-:-N_8uZvE9JIYEtI213iO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/781#-:-N_91eZ0ER9PHGQ5bjH-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
