### PR TITLE
refactor(storage): flush mmap according to dirty-bit

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1365)

### CODE REVIEW

**Comment by yair-starkware** [comment]
When is it going to be used? In the drop?

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1365)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1365#-Ni_Cw75CfwbT36tdrSt:-Ni_Cw763E2QgKTAcnwk:b-s92m92) ([raw file](https://github.com/starkware-libs/papyrus/blob/92eec84e4ae3e545db260d364151f72a54ac1fe3/crates/papyrus_storage/src/mmap_file/mod.rs#L185)):*
> ```XML
>         should_flush: false,
>         _value_type: PhantomData {},
>     };
> ```

Consider adding a `new` function.



_Code quote:_
```XML
    let mmap_file = MMapFile {
        config,
        file,
        mmap,
        size: size.try_into().expect("size should fit in usize"),
        offset,
        should_flush: false,
        _value_type: PhantomData {},
    };
```

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

When is it going to be used? In the drop?
</blockquote></details>

* Set on write.
* Clear on flush (conditionally)

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

* Set on write.
* Clear on flush (conditionally)
</blockquote></details>

These places set the value, but what do we do with this variable besides setting it?

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1365)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
