### PR TITLE
release: adjust Declare transaction to V3 changes in starknet-api

### PR DESCRIPTION
**Pull request by barak-b-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 11 of 19 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/papyrus_execution/src/lib.rs` line 316 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2HaJa0B-BtLkqgXlA:-Ne2HaJa0B-BtLkqgXlB:bp42r2c) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_execution/src/lib.rs#L316)):*
> ```XML
>         block_timestamp,
>         sequencer_address: *sequencer_address,
>         // TODO(barak, 01/10/2023): Change strk_fee_token_address once it exits.
> ```

exits -> exists. Same below
___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2I7nt2CMa7jG3dL9E:-Ne2I7nu1VY88Kzo2I48:br11bvq) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L218)):*
> ```XML
>                 }
>                 starknet_api::transaction::DeclareTransaction::V3(_) => {
>                     Err(internal_server_error("Version 3 transactions are not supported on v0.3.0"))
> ```

The user will receive this error not when they gave a v3 tx, but when in the storage there's a v3 tx.
Therefore, the message should reflect that
If you have the power, here return a custom error type that's not ErrorObjectOwned and map that error into an internal error with the fitting message in api_impl
If you prefer the quicker route, change the message here to something like "The requested transaction is a declare of version 3, which is not supported on v0.3.0".
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2JXn89WpM_Lvo5d2W:-Ne2JXn89WpM_Lvo5d2X:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L238)):*
> ```XML
>                 }
>                 starknet_api::transaction::DeclareTransaction::V3(_) => {
>                     Err(internal_server_error("Version 3 transactions are not supported on v0.4.0"))
> ```

Same here
___
*[`crates/papyrus_rpc/src/v0_4_0/api/mod.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2JjsA6qwv7afz9Yss:-Ne2JjsA6qwv7afz9Yst:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_4_0/api/mod.rs#L361)):*
> ```XML
>         starknet_api::transaction::Transaction::Declare(
>             starknet_api::transaction::DeclareTransaction::V3(_),
>         ) => Err(internal_server_error("Version 3 transactions are not supported on v0.4.0")),
> ```

Same here
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2L6xz2EpiE1oLBOZA:-Ne2L6xz2EpiE1oLBOZB:b-7dw471) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/starknet_client/src/writer/objects/transaction.rs#L65)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Default, Clone, Copy, Eq, PartialEq)]
> pub enum DeclareV1Type {
>     #[serde(rename = "DEPRECATED_OLD_DECLARE")]
> ```

Did you verify that these are the names we will use in starknet?
If yes, I don't like the fact that we won't be able to call declareV1 on starknet-v0.12 once we merge this PR. Could you ask the relevant people to not do it like this

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2QLti9X_EtB2xxYOj:-Ne2QLtjBsigm_ASKvv-:buhisjz) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/starknet_client/src/writer/objects/transaction.rs#L156)):*
> ```XML
> /// Starknet gateway.
> /// It has a serialization format that the Starknet gateway accepts in the `add_transaction`
> /// HTTP method.
> ```

Add a TODO on me to add tests for declare v3

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @elintul, and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2I7nt2CMa7jG3dL9E:-Ne2UtAi2_l4N31O6AYW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L218)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The user will receive this error not when they gave a v3 tx, but when in the storage there's a v3 tx.
Therefore, the message should reflect that
If you have the power, here return a custom error type that's not ErrorObjectOwned and map that error into an internal error with the fitting message in api_impl
If you prefer the quicker route, change the message here to something like "The requested transaction is a declare of version 3, which is not supported on v0.3.0".
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2JXn89WpM_Lvo5d2W:-Ne2V6NGCkycZj13ox3g:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L238)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/mod.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2JjsA6qwv7afz9Yss:-Ne2VFWHDloRlY9phab2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/papyrus_rpc/src/v0_4_0/api/mod.rs#L361)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2QLti9X_EtB2xxYOj:-Ne2VXJw1eb9z3UJTZHj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/starknet_client/src/writer/objects/transaction.rs#L156)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO on me to add tests for declare v3
</blockquote></details>

Done.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137)* status: 7 of 21 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @elintul, and @ShahakShama)

___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-Ne2L6xz2EpiE1oLBOZA:-Ne2s61OD_bD8d_UaWiC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d46fc44e113cba2824ed8f5d21476f3449f23b1/crates/starknet_client/src/writer/objects/transaction.rs#L65)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Did you verify that these are the names we will use in starknet?
If yes, I don't like the fact that we won't be able to call declareV1 on starknet-v0.12 once we merge this PR. Could you ask the relevant people to not do it like this
</blockquote></details>

Done.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-:-Ne2w4-h0Y_anCOB5JI3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/serializers.rs` line 3 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-NeCYCNLAj8tNVFUAHGG:-NeCYCNLAj8tNVFUAHGH:b6src2q) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb22b2509e7fff3703cb0100982110187116e181/crates/papyrus_storage/src/serializers.rs#L3)):*
> ```XML
> #[cfg(test)]
> #[path = "serializers_test.rs"]
> mod serializers_test;
> ```

Missing tests



_Code quote:_
```XML
mod serializers_test;
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 220 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-NeCYJ4U7ER1an1KX26y:-NeCYJ4U7ER1an1KX26z:b-a1z4bk) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb22b2509e7fff3703cb0100982110187116e181/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L220)):*
> ```XML
>                     "The requested transaction is a declare of version 3, which is not supported \
>                      on v0.3.0.",
>                 )),
> ```

Are these tested? 



_Code quote:_
```XML
                starknet_api::transaction::DeclareTransaction::V3(_) => Err(internal_server_error(
                    "The requested transaction is a declare of version 3, which is not supported \
                     on v0.3.0.",
                )),
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 9 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1137#-:-NeDyxZd-M61b8chYWum:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/papyrus/pull/1171) PR as part of bumping version from 0.0.4 to 0.0.5.

**Pull request closed without merging**
