### PR TITLE
refactor(network): db executor is removed from NetworkManager and runs in a separate task

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels
- refactor(network): db executor is removed from NetworkManager and runs in a separate task

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2122)

### CODE REVIEW

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-:-O-jyGXE16gUrkJLrQIk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2122)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-oagga5i3OPfGOgksu:-O-oagga5i3OPfGOgksv:b-l1cld5) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_network/src/db_executor/mod.rs#L79)):*
> ```XML
>     StateDiffResponsesSender:
>         Sink<DataOrFin<StateDiffChunk>, Error = SendError> + Unpin + Send + 'static,
> {
> ```

These go over 100 columns. Should we use subtypes `type Y = XXX`



_Code quote:_
```XML
where
    HeaderQueryReceiver: Stream<Item = (Result<HeaderQuery, ProtobufConversionError>, HeaderResponsesSender)>
        + Unpin,
    HeaderResponsesSender:
        Sink<DataOrFin<SignedBlockHeader>, Error = SendError> + Unpin + Send + 'static,
    StateDiffQueryReceiver: Stream<Item = (Result<StateDiffQuery, ProtobufConversionError>, StateDiffResponsesSender)>
        + Unpin,
    StateDiffResponsesSender:
        Sink<DataOrFin<StateDiffChunk>, Error = SendError> + Unpin + Send + 'static,
{
```
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 171 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-obNHa1-b4hMoF3kFx:-O-obNHa1-b4hMoF3kFy:bhkgfn3) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_network/src/db_executor/test.rs#L171)):*
> ```XML
>             Sender<DataOrFin<StateDiffChunk>>,
>         )>,
>     >,
> ```

type TestDbExecutor = ...



_Code quote:_
```XML
    DBExecutor<
        Receiver<(
            Result<HeaderQuery, ProtobufConversionError>,
            Sender<DataOrFin<SignedBlockHeader>>,
        )>,
        Receiver<(
            Result<StateDiffQuery, ProtobufConversionError>,
            Sender<DataOrFin<StateDiffChunk>>,
        )>,
    >,
```
___
*[`crates/papyrus_node/src/main.rs` line 143 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-oc6oICEWUFwLalcjE:-O-oc6oICEWUFwLalcjF:b-6m6def) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_node/src/main.rs#L143)):*
> ```XML
>     .await?;
> 
>     // P2P Sync Server task.
> ```

Why do you specify p2p?



_Code quote:_
```XML
    // P2P Sync Server task.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2122)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-oagga5i3OPfGOgksu:-O-omIsk2AG2eHtXD5Nd:b-mfblsp) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_network/src/db_executor/mod.rs#L79)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

These go over 100 columns. Should we use subtypes `type Y = XXX`
</blockquote></details>

This is not a type, it's a type bound. type bound aliases is an experimental feature in rust
But we plan to remove these generics once we create a test utility for sync like the one Asmaa created today for consensus
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 171 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-obNHa1-b4hMoF3kFx:-O-omZ3q35QugvC5WC4J:bwj4n1y) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_network/src/db_executor/test.rs#L171)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

type TestDbExecutor = ...
</blockquote></details>

This is the only place we define it, so I see no reason to create a type alias
___
*[`crates/papyrus_node/src/main.rs` line 143 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-oc6oICEWUFwLalcjE:-O-omgm8-AUa4D6x8zUs:buwwklg) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_node/src/main.rs#L143)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why do you specify p2p?
</blockquote></details>

Because there's a central sync (It doesn't have a server, but we want to connect this to the p2p sync client)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2122)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 171 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2122#-O-obNHa1-b4hMoF3kFx:-O-oo7rC2B7a28rkU1gR:b-xn7p7m) ([raw file](https://github.com/starkware-libs/papyrus/blob/c75a7c71cb74b651eb572c34b38ae675e3918fc5/crates/papyrus_network/src/db_executor/test.rs#L171)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is the only place we define it, so I see no reason to create a type alias
</blockquote></details>

just made this function hard to read. I think it's worthwhile but won't block

**Pull request merged**
