### PR TITLE
feat(common): calculate block header hash

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_common/src/block_hash.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6j-Cz77wBFlHzzQfG:-Ne6j-Cz77wBFlHzzQfH:b-dyjwv1) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L39)):*
> ```XML
> 
> // Validates hash of a starknet block by version.
> fn validate_block_hash_by_version(
> ```

Consider changing this function to calculate the hash instead of validating
___
*[`crates/papyrus_common/src/block_hash.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6j_Tx6anq4AVCmgsN:-Ne6j_TyEi2lP6NXzc4-:b3jv055) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L44)):*
> ```XML
>     chain_id: &ChainId,
> ) -> Result<bool, StarknetApiError> {
>     // Transactions leaves.
> ```

Extract to function
___
*[`crates/papyrus_common/src/block_hash.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6jUcT23XailjGJ1Ph:-Ne6jUcT23XailjGJ1Pi:bv6v2hf) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L45)):*
> ```XML
> ) -> Result<bool, StarknetApiError> {
>     // Transactions leaves.
>     let transaction_patricia_leaves =
> ```

Calculate the root here for the sake of symmetry
___
*[`crates/papyrus_common/src/block_hash.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6jgSv4ZZSQudQCHYk:-Ne6jgSv4ZZSQudQCHYl:b3jv055) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L52)):*
> ```XML
>             .collect::<Result<Vec<_>, _>>()?;
> 
>     // Events leaves.
> ```

Extract to function
___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kGra8FA8JUl85stv:-Ne6kGra8FA8JUl85stw:b-jb91va) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
> ```XML
> }
> 
> fn get_invoke_signature(transaction: &Transaction) -> Vec<StarkFelt> {
> ```

Consider renaming to "get_signature_only_from_invoke
___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-Ne6kg0Y3jbDAtN1Wq8B:bjdwx2d) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
> ```XML
> }
> 
> fn get_invoke_signature(transaction: &Transaction) -> Vec<StarkFelt> {
> ```

I'm debating if this causes a security issue. It means that a malicious peer can give us wrong signatures on a block of version <= 2. @dan-starkware WDYT?
___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Ne6l8lBCG-OFE7RD2rI:b-qa8lak) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
> ```XML
>         )
>         .expect("should be a Stark felt in hex representation"),
>         _ => unimplemented!("Sequencer address for chain"),
> ```

Does this mean we can only calculate block hashes for mainnet? Sounds problematic

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6j-Cz77wBFlHzzQfG:-Ne6xJE3E1fo3z7dbBvV:b-5v1qeq) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider changing this function to calculate the hash instead of validating
</blockquote></details>

Adding todo.
___
*[`crates/papyrus_common/src/block_hash.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6j_Tx6anq4AVCmgsN:-Ne72CWt9x-yc5h8MQAI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L44)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract to function
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6jUcT23XailjGJ1Ph:-Ne72DiI4yMneS-k7lwB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Calculate the root here for the sake of symmetry
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6jgSv4ZZSQudQCHYk:-Ne72EPoBQz9zlSFiN_D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract to function
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kGra8FA8JUl85stv:-Ne72SSi1FgY5EFPQ-SW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider renaming to "get_signature_only_from_invoke
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-Ne75fvT-MEJ3oK88EJ3:bk4lgwb) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm debating if this causes a security issue. It means that a malicious peer can give us wrong signatures on a block of version <= 2. @dan-starkware WDYT?
</blockquote></details>

a. Can we validate the signatures for these blocks?
b. What is the risk of invalid signatures?
___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Ne78MMZCN2HaWyDDYEB:bfqnfpm) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Does this mean we can only calculate block hashes for mainnet? Sounds problematic
</blockquote></details>

a. We should add the addresses of the rest of the chains. (Which chains?)
b. New chains won't use version 2.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-Ne8F8CVC2wBG07-PpNk:b-dgjaeb) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

a. Can we validate the signatures for these blocks?
b. What is the risk of invalid signatures?
</blockquote></details>

a. No, but maybe it means we should not support old hash versions and find a way to support historic blocks (allow old hash versions if the block number is smaller than a constant)
b. I'm not sure if there's a risk. That's why I asked @dan-starkware 

Generally, In blocks that have old hash versions, did the non-invoke transactions contain a signature at all? If not, then you can just return the signature. If yes, then why was it ok that the signatures weren't hashed
___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Ne8GJ0z3xygnEmtQoxc:b-36wula) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

a. We should add the addresses of the rest of the chains. (Which chains?)
b. New chains won't use version 2.
</blockquote></details>

Then add a TODO
___
*[`crates/papyrus_common/src/block_hash.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8ERSD8xr_k_immOC7:-Ne8ERSD8xr_k_immOC8:bbh7yox) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L28)):*
> ```XML
> /// Starknet.
> pub fn validate_block_hash(block: &Block, chain_id: &ChainId) -> Result<bool, StarknetApiError> {
>     // TODO(yoav): Calculate the hash instead of validating, when the block hash is removed from the
> ```

It won't be removed, and you can't calculate without knowing the version
I meant in my previous comment to the function below
___
*[`crates/papyrus_common/src/block_hash.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8ExeIE_yAYOlJ6P3D:-Ne8ExeIE_yAYOlJ6P3E:bo6umg8) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L46)):*
> ```XML
>     chain_id: &ChainId,
> ) -> Result<bool, StarknetApiError> {
>     // Events leaves.
> ```

Remove comment
___
*[`crates/papyrus_common/src/block_hash.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8EpcW2Oum7aj561Zm:-Ne8EpcW2Oum7aj561Zn:b29xx80) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L59)):*
> ```XML
>         )
>         .chain_if_else(&block.header.timestamp.0.into(), &ZERO, version >= BlockHashVersion::V1)
>         .chain(&usize_into_felt(block.body.transactions.len()))
> ```

Consider changing the function to return also the length of transactions and calling the function above

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-Ne8hnef4g7QjK1-oR9H:b-3rco1t) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

a. No, but maybe it means we should not support old hash versions and find a way to support historic blocks (allow old hash versions if the block number is smaller than a constant)
b. I'm not sure if there's a risk. That's why I asked @dan-starkware 

Generally, In blocks that have old hash versions, did the non-invoke transactions contain a signature at all? If not, then you can just return the signature. If yes, then why was it ok that the signatures weren't hashed
</blockquote></details>

In block 4889 (BlockHashVersion = V1) , there is a signed declare.
Good questions.
___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Ne8jgHT2zKNAuYJeVXv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Then add a TODO
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8ERSD8xr_k_immOC7:-Ne8eo3jBQ0GjbRjhe1g:b-yt9lbs) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It won't be removed, and you can't calculate without knowing the version
I meant in my previous comment to the function below
</blockquote></details>

Why not?! There is a TODO comment...

Oh! I got it.
___
*[`crates/papyrus_common/src/block_hash.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8ExeIE_yAYOlJ6P3D:-Ne8fTXX7iyKi36ifEZY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove comment
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/block_hash.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne8EpcW2Oum7aj561Zm:-Ne8gs5yEl12a-jYTlhM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63a3c0f736d76cdd38662862da275354692b14ad/crates/papyrus_common/src/block_hash.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider changing the function to return also the length of transactions and calling the function above
</blockquote></details>

Done.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-NeIGSc9BVlYBBh8um_3:bx2sumj) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In block 4889 (BlockHashVersion = V1) , there is a signed declare.
Good questions.
</blockquote></details>

Dan: Just let Product know.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_common/src/block_hash.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6kg0Y3jbDAtN1Wq8A:-NeIRkMU4Xe4LMLRUgAS:b-kp1cgy) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L113)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Dan: Just let Product know.
</blockquote></details>

My thought is that if we're going to verify the signatures then it's ok, but I want to hear Dan's opinion
___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-NeIS-iV1FhuI4hu6giS:bi6lma3) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add a comment that these are all the chains that have historic blocks with block hash version 2

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-NeITRz880dmSqRNkDKg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that these are all the chains that have historic blocks with block hash version 2
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Nem_lCzDb_aTKuzQkhM:b-18p0pr) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

comment, not todo

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-Ne6l8lA5mGrnKMvo42I:-Nembcy411v8SNUBlwZ6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/76c93ce6e0cd4c97e64c7942a77c5d1f02c825f8/crates/papyrus_common/src/block_hash.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

comment, not todo
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1159#-:-NeroTo-3D9B9M219Vgl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
