### PR TITLE
Yair/l1

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Crate for fetching data from the base layer
Testing requires Ganache@7.4.3 to be installed locally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r5, 7 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)* status: all files reviewed, 5 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_base_layer/Cargo.toml` line 11 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzBR7b60HtnOimCoQn:-NOzBR7b60HtnOimCoQo:b6fiq72) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/Cargo.toml#L11)):*
> ```TOML
> rustc-hex = { version = "2.1.0" }
> serde_json = { version = "1.0.81" }
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "9a1fca8" }
> ```

We recently bumped the SN_API version, please make sure this is consistent with elsewhere.



_Code quote:_
```TOML
starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "9a1fca8" }
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIFjuCT20NgsBsbL9:-NOzIFjuCT20NgsBsbLA:bqabtxq) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L16)):*
> ```XML
> 
> // Returns a Ganache instance, preset with a Starknet core contract and some state updates:
> //     starknet block number   starknet block hash   Ethereum block number
> ```

Consider reordering such that Eth block number is first.



_Code quote:_
```XML
//     starknet block number   starknet block hash   Ethereum block number
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIzDJ-fQBqr2uJzem:-NOzIzDJ-fQBqr2uJzen:bp6rb7n) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L21)):*
> ```XML
> //     300                     0x300                  30
> // The blockchain is at Ethereum block number 31.
> // Note: Requires Ganache@7.4.3 installed.
> ```

Do we need exact match?



_Code quote:_
```XML
 Requires Ganache@7.4.3 installed.
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIWXX0cQBnWFnBaX9:-NOzIWXX0cQBnWFnBaXA:b-okbyf5) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L53)):*
> ```XML
> #[test_with::executable(ganache)]
> #[tokio::test]
> // Note: the test requires ganache-cli installed, otherwise it is ignored.
> ```

Can this move before the attributes? Do we have a convention for this case?



_Code quote:_
```XML
// Note: the test requires ganache-cli installed, otherwise it is ignored.
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuDpr-EW_YYKf-AhG:-NPBuDpr-EW_YYKf-AhH:b3kre) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce98595826ef1a36c1b805a87e0a053564c0ae7d/crates/papyrus_base_layer/src/base_layer_test.rs#L37)):*
> ```XML
>     );
>     const GANACHE_DB_TAR_PATH: &str = "resources/ganache-db.tar";
>     const REL_DB_PATH: &str = "hathat";
> ```

?



_Code quote:_
```XML
hathat
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBudGKDtsPAGXPFTVJ:-NPBudGKDtsPAGXPFTVK:b-jqunpm) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce98595826ef1a36c1b805a87e0a053564c0ae7d/crates/papyrus_base_layer/src/base_layer_test.rs#L55)):*
> ```XML
> // Note: the test requires ganache-cli installed, otherwise it is ignored.
> async fn latest_proved_block_ethereum() {
>     const SN_CONTRACT_ADDR: &str = "0xe2aF2c1AE11fE13aFDb7598D0836398108a4db0A";
> ```

Please add all preset assumption to `get_test_ethereum_node` documentation



_Code quote:_
```XML
const SN_CONTRACT_ADDR: &str = "0xe2aF2c1AE11fE13aFDb7598D0836398108a4db0A";
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuwEV0wAZEtoU7_FL:-NPBuwEV0wAZEtoU7_FM:bwce5sn) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce98595826ef1a36c1b805a87e0a053564c0ae7d/crates/papyrus_base_layer/src/base_layer_test.rs#L56)):*
> ```XML
> async fn latest_proved_block_ethereum() {
>     const SN_CONTRACT_ADDR: &str = "0xe2aF2c1AE11fE13aFDb7598D0836398108a4db0A";
>     let (node, _db) = get_test_ethereum_node();
> ```

Do we need to return this from the `get_test_ethereum_node` function?



_Code quote:_
```XML
 _db
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBv30A0bHDmeeOatxP:-NPBv30A0bHDmeeOatxQ:b-tk43qy) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce98595826ef1a36c1b805a87e0a053564c0ae7d/crates/papyrus_base_layer/src/base_layer_test.rs#L66)):*
> ```XML
>     let latest_state_0_conf = contract.latest_proved_block(None).await;
>     assert_matches!(latest_state_0_conf, Ok(Some((block_number, block_hash)))
>         if block_number == BlockNumber(300) && block_hash == BlockHash(stark_felt!("0x300")));
> ```

Consider using constants for all hard-coded values.



_Code quote:_
```XML
300
```
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBvuPQ8PSTtKv7zSO7:-NPBvuPQ8PSTtKv7zSO8:b-6lt5mr) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce98595826ef1a36c1b805a87e0a053564c0ae7d/crates/papyrus_base_layer/src/base_layer_test.rs#L80)):*
> ```XML
>         if block_number == BlockNumber(100) && block_hash == BlockHash(stark_felt!("0x100")));
> 
>     let latest_state_1000_conf = contract.latest_proved_block(Some(1000)).await;
> ```

Any specific reason for 1000?
Do we know at which block (and what state) the core contract was deployed?
Maybe check right before and after that block instead?



_Code quote:_
```XML
1000
```
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 13 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzEqSP4njso2qrM68T:-NOzEqSP4njso2qrM68U:bg9fex4) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L13)):*
> ```XML
> 
> use crate::BaseLayerContract;
> const STARKNET_ABI: &str = r#"[
> ```

Consider adding a comment on how to derive this ABI.
Maybe this belongs to SN_API (if so, can be done in a separate PR)?



_Code quote:_
```XML
const STARKNET_ABI: &str = r#"[
```
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzGyOe8vP1DkQp4IL0:-NOzGyOe8vP1DkQp4IL1:bbwvgs) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L87)):*
> ```XML
> impl BaseLayerContract for EthereumBaseLayerContract {
>     type Error = EthereumBaseLayerError;
>     async fn latest_proved_block(
> ```

Empty line before?



_Code quote:_
```XML
async fn latest_proved_block(
```
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzHcDF7pv_25prdbfI:-NOzHcDF7pv_25prdbfJ:b-x3x6rn) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L106)):*
> ```XML
>         let call_state_block_hash =
>             self.contract.method::<_, U256>("stateBlockHash", ())?.block(ethereum_block_number);
>         let (state_block_number, state_block_hash) =
> ```

Consider spacing after `ethereum_block_number` and before the return.



_Code quote:_
```XML
        if ethereum_block_number.is_none() {
            return Ok(None);
        }
        let ethereum_block_number = ethereum_block_number.unwrap();
        let call_state_block_number =
            self.contract.method::<_, I256>("stateBlockNumber", ())?.block(ethereum_block_number);
        let call_state_block_hash =
            self.contract.method::<_, U256>("stateBlockHash", ())?.block(ethereum_block_number);
        let (state_block_number, state_block_hash) =
            tokio::try_join!(call_state_block_number.call(), call_state_block_hash.call())?;
        Ok(Some((
            BlockNumber(state_block_number.as_u64()),
            BlockHash(StarkHash::try_from(state_block_hash.encode_hex().as_str())?),
        )))
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 13 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzGjRn5BLhbW4Hvxzj:-NOzGjRn5BLhbW4Hvxzk:bo5cpot) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L13)):*
> ```XML
> #[async_trait]
> pub trait BaseLayerContract {
>     type Error;
> ```

Nice :)



_Code quote:_
```XML
 type Error;
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 14 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzD_rE1Yjr1HK5-9VD:-NOzD_rE1Yjr1HK5-9VE:b-ra4iiz) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L14)):*
> ```XML
> pub trait BaseLayerContract {
>     type Error;
>     /// Get the latest Starknet block that is proved on the base layer.
> ```

An empty line before?



_Code quote:_
```XML
 /// Get the latest Starknet block that is proved on the base layer.
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzGUoZ0CviKfW2NK1K:-NOzGUoZ0CviKfW2NK1L:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L17)):*
> ```XML
>     async fn latest_proved_block(
>         &self,
>         min_confirmations: Option<u64>,
> ```

Please document.



_Code quote:_
```XML
min_confirmations: Option<u64>,
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzEV-ZDvKbcHGEiftu:-NOzEV-ZDvKbcHGEiftv:bxxdube) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L18)):*
> ```XML
>         &self,
>         min_confirmations: Option<u64>,
>     ) -> Result<Option<(BlockNumber, BlockHash)>, Self::Error>;
> ```

If this becomes prevalent in the future, consider defining an alias.



_Code quote:_
```XML
(BlockNumber, BlockHash)
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIFjuCT20NgsBsbL9:-NPCPY8d6DxINxx5Yy76:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L16)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider reordering such that Eth block number is first.
</blockquote></details>

Done
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIzDJ-fQBqr2uJzem:-NPCPb_552p4rAOznQCQ:b69u1tl) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L21)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need exact match?
</blockquote></details>

I'm not sure (probably not), but if we require an exact match in rust dependencies then why shouldn't we do it here?
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIWXX0cQBnWFnBaX9:-NPCUc3E1ETrstkCAAyW:b-naigjr) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L53)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can this move before the attributes? Do we have a convention for this case?
</blockquote></details>

The rust-analyzer convention is not to have ignored tests.
Instead, they say to assert the wrong behavior, explain why it is wrong, and add a fixme.
https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#ignore

I can make the `get_test_ethereum_node` return a result and accept wrong version / not installed and pass the test.

I'm not sure which is better.
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuDpr-EW_YYKf-AhG:-NPCQMr-CmtfbxW3NIED:bgpvard) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L37)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

That's the name Remo gave... Rename?
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBudGKDtsPAGXPFTVJ:-NPCWyHvAhyMNo7yBl2c:b-cw8hxf) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L55)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add all preset assumption to `get_test_ethereum_node` documentation
</blockquote></details>

Done + moved the value to be returned from the function
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuwEV0wAZEtoU7_FL:-NPCX39S4hbsh19wkst5:b-8sdkej) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L56)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need to return this from the `get_test_ethereum_node` function?
</blockquote></details>

Yes since it's a temp dir (this is a handle to keep the dir from deletion)
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBv30A0bHDmeeOatxP:-NPD9u-4E0MY5xyY2EK-:bmjdjpx) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider using constants for all hard-coded values.
</blockquote></details>

Is it better now?
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBvuPQ8PSTtKv7zSO7:-NPDDaAZBsVq4eg8ny_5:b-i5f08p) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L80)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Any specific reason for 1000?
Do we know at which block (and what state) the core contract was deployed?
Maybe check right before and after that block instead?
</blockquote></details>

Actually, the doc lies a little bit (I wrote it before creating the db with Remo).
In the way we created the state, we needed 2 transactions per state update (update block number + update block hash), and each transaction triggers a new Ethereum block, so it's not exactly what the doc says.
We figured it was good enough.
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 13 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzEqSP4njso2qrM68T:-NPCXGh42fFMZPLrxSaB:b-fu79pp) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider adding a comment on how to derive this ABI.
Maybe this belongs to SN_API (if so, can be done in a separate PR)?
</blockquote></details>

I added a comment and moved the abi to a file.
I don't think it belongs in SN_API because it's only a partial abi.
Maybe the SN_API should have a dependency to the Cairo lang repo at some point, but currently there is no need for it anywhere.
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzGyOe8vP1DkQp4IL0:-NPCZ2L-39i3dmrDKoXJ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L87)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Empty line before?
</blockquote></details>

Done
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzHcDF7pv_25prdbfI:-NPCZhhX8UTjJQQTAOod:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L106)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider spacing after `ethereum_block_number` and before the return.
</blockquote></details>

Done
___
*[`crates/papyrus_base_layer/src/lib.rs` line 14 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzD_rE1Yjr1HK5-9VD:-NPC_0cZ46VDtIudNphC:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L14)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

An empty line before?
</blockquote></details>

Done
___
*[`crates/papyrus_base_layer/src/lib.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzGUoZ0CviKfW2NK1K:-NPCahIfCi0xc4xzFWPg:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L17)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Done
___
*[`crates/papyrus_base_layer/src/lib.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzEV-ZDvKbcHGEiftu:-NPCqF-L4GZGcEiOx43U:b-a31y7w) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/lib.rs#L18)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

If this becomes prevalent in the future, consider defining an alias.
</blockquote></details>

I think I like it better the way it is, maybe in the future I will change my mind and change it

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIzDJ-fQBqr2uJzem:-NPJVhtJ5oDSdsj5zIAE:bi04m56) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L21)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I'm not sure (probably not), but if we require an exact match in rust dependencies then why shouldn't we do it here?
</blockquote></details>

WDYM by `exact match in rust dependencies`?
Our build does not install Ganache on the host machine. What would happen if you need to upgrade your local Ganache installation?
At least add a TODO to consider relaxing this requirement. 
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIWXX0cQBnWFnBaX9:-NPJaKAH3ijQ79ieAriA:b-rlvqip) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L53)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The rust-analyzer convention is not to have ignored tests.
Instead, they say to assert the wrong behavior, explain why it is wrong, and add a fixme.
https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#ignore

I can make the `get_test_ethereum_node` return a result and accept wrong version / not installed and pass the test.

I'm not sure which is better.
</blockquote></details>

Not sure I understand, let's discuss f2f
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuDpr-EW_YYKf-AhG:-NPJWuha6Kkr6tS0nF36:b-yzjqkl) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L37)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

That's the name Remo gave... Rename?
</blockquote></details>

Does it stand for something?
Why do we need this variable? 
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuwEV0wAZEtoU7_FL:-NPJZ21q4D0WrsR9eRiG:bogn1g5) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L56)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yes since it's a temp dir (this is a handle to keep the dir from deletion)
</blockquote></details>

Consider documenting this.
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBv30A0bHDmeeOatxP:-NPJZQWb1L5hXC8_bc5L:bt2bk1y) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is it better now?
</blockquote></details>

It is better now. But I would still consider using constants for hard-coded values.
I guess it's fine for now, but when we have another test referencing these..
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 14 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPJa2JLAY0uPvhqZB4l:-NPJa2JLAY0uPvhqZB4m:b9gurwj) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b775d835249f88bfe2f36abe1346e7c70f03e70/crates/papyrus_base_layer/src/base_layer_test.rs#L14)):*
> ```XML
> use crate::BaseLayerContract;
> 
> type EthereumContractAddress = String;
> ```

Is there a type for it in Ganache?



_Code quote:_
```XML
type EthereumContractAddress = String;
```
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 47 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPJ_XdjBo8FxpCOKPla:-NPJ_XdjBo8FxpCOKPlb:bnh83rx) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b775d835249f88bfe2f36abe1346e7c70f03e70/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L47)):*
> ```XML
>         let client: Provider<Http> = Provider::<Http>::try_from(config.node_url)?;
>         // The solidity contract was pre-compiled, and only the relevant functions were kept.
>         let abi: Abi = serde_json::from_str::<Abi>(include_str!("core_contract_latest_block.abi"))?;
> ```

I was not aware of this macro.



_Code quote:_
```XML
include_str!
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NOzIzDJ-fQBqr2uJzem:-NPMQydeEMrec9ZtGtr-:b-blelpv) ([raw file](https://github.com/starkware-libs/papyrus/blob/431781660a93ddcf3e6018c61fa8163f378908bd/crates/papyrus_base_layer/src/base_layer_test.rs#L21)):*
> WDYM by exact match in rust dependencies?
In the cargo.toml we specify major.minor.patch (https://en.wikipedia.org/wiki/Software_versioning)

> Our build does not install Ganache on the host machine. What would happen if you need to upgrade your local Ganache installation?
Currently the starkware repo uses two different Ganache versions, and tox solves the version issues. I don't think updating the app will have issues.

> At least add a TODO to consider relaxing this requirement.
done
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuDpr-EW_YYKf-AhG:-NPMRbDFE171BVfO3F97:b-q42eon) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L37)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Does it stand for something?
Why do we need this variable? 
</blockquote></details>

Doesn't mean anything. It's the name of the dir he created for the data and then archived.
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBuwEV0wAZEtoU7_FL:-NPMSd3vAOWigxP13LMh:bbi8cah) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L56)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider documenting this.
</blockquote></details>

Introduced alias hiding this
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPBv30A0bHDmeeOatxP:-NPMli7j26jGFDnBMGcb:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/abe024b2dcaa4368bf2dfb6d971e2f6402f18dab/crates/papyrus_base_layer/src/base_layer_test.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

It is better now. But I would still consider using constants for hard-coded values.
I guess it's fine for now, but when we have another test referencing these..
</blockquote></details>

done
___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 14 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/488#-NPJa2JLAY0uPvhqZB4l:-NPMOz0hAUr5AEocpYil:bd18qd1) ([raw file](https://github.com/starkware-libs/papyrus/blob/6b775d835249f88bfe2f36abe1346e7c70f03e70/crates/papyrus_base_layer/src/base_layer_test.rs#L14)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is there a type for it in Ganache?
</blockquote></details>

You mean in ethers? Ganache is an app in our case, not a lib.
See TODO in EthereumBaseLayerConfig - I was thinking about using it in the configuration struct. WDYT?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/488#-:-NPMrH1YC41Ma7Cxvlf-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Pull request merged**
