### PR TITLE
feat(sync): add p2p header sync

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* **#1729** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1729?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1729?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`Cargo.lock.orig` line 0 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-NrE6t6K1F_oEuhRFh4K:-NrE6t6L3yGF-10kwqyY:b9orldr) ([raw file](https://github.com/starkware-libs/papyrus/blob/768c30a017f7112550f27edb6c51fcd8f0102c08/Cargo.lock.orig#L0)):*
Erase this file
___
*[`crates/papyrus_node/src/config/mod.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-NrE7xJs2GJ_ZGL7T-NC:-NrE7xJs2GJ_ZGL7T-ND:bpbxnu6) ([raw file](https://github.com/starkware-libs/papyrus/blob/768c30a017f7112550f27edb6c51fcd8f0102c08/crates/papyrus_node/src/config/mod.rs#L54)):*
> ```XML
>     // TODO(yair): Change NodeConfig to have an option of enum of SyncConfig or P2PSyncConfig.
>     pub p2p_sync: Option<P2PSyncConfig>,
>     pub network: Option<NetworkConfig>,
> ```

Maybe we should add a TODO to make network not optional once it's developed enough

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 12 files at r5, 5 of 13 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`config/default_config.json` line 155 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7VWa29yZbp5S7bM_z:-Ns7VWa3EEEAXMS4pCjT:bl6unjo) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/config/default_config.json#L155)):*
> ```JSON
>     "description": "The maximum amount of headers to ask from peers in each iteration.",
>     "privacy": "Public",
>     "value": 100
> ```

Consider one or two orders of magnitude higher. 



_Suggestion:_
```JSON
10000
```
___
*[`crates/papyrus_node/Cargo.toml` line 27 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7TUYZAlSf0VWBDH2c:-Ns7TUYZAlSf0VWBDH2d:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/Cargo.toml#L27)):*
> ```TOML
> papyrus_monitoring_gateway = { path = "../papyrus_monitoring_gateway", version = "0.3.0-rc.3" }
> papyrus_network = { path = "../papyrus_network", version = "0.3.0-rc.3" }
> papyrus_p2p_sync = { path = "../papyrus_p2p_sync" }
> ```

Consider



_Suggestion:_
```TOML
papyrus_p2p_sync = { path = "../papyrus_p2p_sync", version = "0.3.0-rc.3" }
```
___
*[`crates/papyrus_node/src/main.rs` line 151 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7UF753_BsVccZt-9U:-Ns7UF768UsHwSnqYS_6:b-4t9leb) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/src/main.rs#L151)):*
> ```XML
>             error!("P2P Sync stopped.");
>             res??
>         }
> ```

Do we really need two handlers? Can we have a single which is either central or P2P?



_Code quote:_
```XML
        res = sync_handle => {
            error!("Sync stopped.");
            res??
        }
        res = p2p_sync_handle => {
            error!("P2P Sync stopped.");
            res??
        }
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7VIGo0lBEBCqki07z:-Ns7VIGo0lBEBCqki08-:b-kbnhi9) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/src/config/mod.rs#L87)):*
> ```XML
>     /// None if the syncing should be disabled.
>     pub sync: Option<SyncConfig>,
>     /// One of p2p_sync or sync must be None.
> ```

Can this be validated? 



_Code quote:_
```XML
/// One of p2p_sync or sync must be None.
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_node/src/config/mod.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-NrE7xJs2GJ_ZGL7T-NC:-Ns7WdD_-1_rPPgjDllG:b-cup5s1) ([raw file](https://github.com/starkware-libs/papyrus/blob/768c30a017f7112550f27edb6c51fcd8f0102c08/crates/papyrus_node/src/config/mod.rs#L54)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Maybe we should add a TODO to make network not optional once it's developed enough
</blockquote></details>

I don't think it's needed.. it's obvious isn't it?
___
*[`Cargo.lock.orig` line  at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-NrE6t6K1F_oEuhRFh4K:-Ns7nTDT3OoCl4-msUWH:bsusc0z) ([raw file](https://github.com/starkware-libs/papyrus/blob/768c30a017f7112550f27edb6c51fcd8f0102c08/Cargo.lock.orig#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase this file
</blockquote></details>

it is erased.. "File not in pull request at selected revision."

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 5 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`config/default_config.json` line 155 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7VWa29yZbp5S7bM_z:-NsHUM-I1WlDgRp_e2L9:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/config/default_config.json#L155)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider one or two orders of magnitude higher.
</blockquote></details>

Done
___
*[`crates/papyrus_node/Cargo.toml` line 27 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7TUYZAlSf0VWBDH2c:-NsHUKqfCb6xMK5WlWCJ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/Cargo.toml#L27)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider
</blockquote></details>

Done
___
*[`crates/papyrus_node/src/main.rs` line 151 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7UF753_BsVccZt-9U:-NsHUAxQDKTySztOwY7k:b-y3pax7) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/src/main.rs#L151)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we really need two handlers? Can we have a single which is either central or P2P?
</blockquote></details>

They have different error types
___
*[`crates/papyrus_node/src/config/mod.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-NrE7xJs2GJ_ZGL7T-NC:-NsHTZaf9zTR4mUelkum:bq2ygls) ([raw file](https://github.com/starkware-libs/papyrus/blob/768c30a017f7112550f27edb6c51fcd8f0102c08/crates/papyrus_node/src/config/mod.rs#L54)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't think it's needed.. it's obvious isn't it?
</blockquote></details>

I don't think it's obvious. Added TODO
___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1729#-Ns7VIGo0lBEBCqki07z:-NsHTKK09figuHHDqGKj:bue3438) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab28b190990cbd171fea92ba970275b515dd3a96/crates/papyrus_node/src/config/mod.rs#L87)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can this be validated?
</blockquote></details>

It's already validated here
https://github.com/starkware-libs/papyrus/blob/6832940024d2659efd6f27bd5f173e84565b67ce/crates/papyrus_node/src/main.rs#L102

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: 10 of 18 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 12 files at r5, 2 of 13 files at r7, 7 of 7 files at r12, 2 of 2 files at r13, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1729)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
