### PR TITLE
Revert one block at the time

### PR DESCRIPTION
**Pull request by anatgstarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/455)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
I understand that with this change, there are fewer calls to the central per reverted block (but we create new streams per reverted block, and I'm not sure what the cost is).
Are there more advantages?

IMO the revert flow is less explicit this way.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/455#-:-NLogTUS4g1KRhFt_LKl:b-9eizcb)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLodYfpEQEfvZFkPOZt:-NLodYfpEQEfvZFkPOZu:b6fe2k) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4f86a8fb39d369bb44d2b3ec2851da79994be54/crates/papyrus_sync/src/lib.rs#L191)):*
> ```XML
>         // Assuming the central source is trusted, detect reverts by comparing the incoming block's
>         // parent hash to the current hash.
>         if let Some(prev_header) = self.verify_parent_block_hash(block_number, &block)? {
> ```

Consider extracting this code to another function and call it before store_block (or at least change the name of the function)



_Code quote:_
```XML
        if let Some(prev_header) = self.verify_parent_block_hash(block_number, &block)? {
            info!("Reverting block {}.", prev_header.block_number);
            self.revert_block(prev_header.block_number)?;

            return Err(StateSyncError::ParentBlockHashMismatch {
                block_number,
                expected_parent_block_hash: block.header.parent_hash,
                stored_parent_block_hash: prev_header.block_hash,
            });
        }
```
___
*[`crates/papyrus_sync/src/lib.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLoeIPX6dtbsJUT-6sr:-NLoeIPX6dtbsJUT-6ss:b-8l5yug) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4f86a8fb39d369bb44d2b3ec2851da79994be54/crates/papyrus_sync/src/lib.rs#L248)):*
> ```XML
> 
>     // Compares the block's parent hash to the stored block.
>     fn verify_parent_block_hash(
> ```

What you changed is that now the function returns the last header in case it doesn't match the incoming block's parent hash?
Please document

**Review by anatgstarkware — COMMENTED** [review]
There are fewer calls per block (not just reverted blocks)
I think that checking if we need to revert in two different places (and in two different ways) is redundant and less clear

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/455#-:-NLokzDy5lbHsf3ZOVfj:bgp9c1i)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLodYfpEQEfvZFkPOZt:-NLok_BX2PaisRscUDoL:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4f86a8fb39d369bb44d2b3ec2851da79994be54/crates/papyrus_sync/src/lib.rs#L191)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider extracting this code to another function and call it before store_block (or at least change the name of the function)
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLoeIPX6dtbsJUT-6sr:-NLok_lsAFdrsQnhU8el:bm1oeos) ([raw file](https://github.com/starkware-libs/papyrus/blob/a4f86a8fb39d369bb44d2b3ec2851da79994be54/crates/papyrus_sync/src/lib.rs#L248)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What you changed is that now the function returns the last header in case it doesn't match the incoming block's parent hash?
Please document
</blockquote></details>

Thanks to your previous comment, I moved the revert here, so there is no need to return the previous header. Much better, thanks

**Review by yair-starkware — APPROVED** [review]
What other calls are removed?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/455#-:-NLpCnmC70-JMvWKR7Iv:bus803h)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLpCCVwEtsHcO6woc8F:-NLpCCVwEtsHcO6woc8G:b-5ugdnm) ([raw file](https://github.com/starkware-libs/papyrus/blob/2dd441b4852ed48c6fedcb56712b2d0378b2f619/crates/papyrus_sync/src/lib.rs#L239)):*
> ```XML
>     // Assuming the central source is trusted, detect reverts by comparing the incoming block's
>     // parent hash to the current hash.
>     fn verify_parent_block_hash(
> ```

Consider renaming the function, maybe verify_block_or_revert



_Code quote:_
```XML
fn verify_parent_block_hash(
```

**Comment by anatgstarkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/455#-NLpCCVwEtsHcO6woc8F:-NLphVvIA9BQEc7QlU4_:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/2dd441b4852ed48c6fedcb56712b2d0378b2f619/crates/papyrus_sync/src/lib.rs#L239)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider renaming the function, maybe verify_block_or_revert
</blockquote></details>

Done

**Pull request closed without merging**
