### PR TITLE
fix(): run node without syncing

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1242)

### CODE REVIEW

**Review by eranreshef-starkware — APPROVED** [review]
helm related changes lgtm

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1242#-:-NfppXcz6YwO0B7__6GT:b-dz5md9)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dan-starkware, @DvirYo-starkware, and @yoavGrs)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/main.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1242#-NfqendN3CkkRNzvuYeI:-NfqendN3CkkRNzvuYeJ:be2jil3) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bdb3b48cc720d97f62a0303d796d014358633ce/crates/papyrus_node/src/main.rs#L100)):*
> ```XML
>         storage_writer: StorageWriter,
>     ) -> Result<(), StateSyncError> {
>         let Some(sync_config) = config.sync else { return Ok(()) };
> ```

What about this?



_Code quote:_
```XML
 let Some(sync_config) = config.sync else { return Ok(()) };
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1242)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yoavGrs)

___
*[`crates/papyrus_node/src/main.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1242#-NfqendN3CkkRNzvuYeI:-Nftzsh9-Y5Twa1MqBAT:b-7ql1td) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bdb3b48cc720d97f62a0303d796d014358633ce/crates/papyrus_node/src/main.rs#L100)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What about this?
</blockquote></details>

fixed

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware and @yoavGrs)

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1242)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_config/src/presentation.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1242#-NgCwyDm13Va4nP6GLpG:-NgCwyDm13Va4nP6GLpH:brcs5ky) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4f2135f35de66338c05bf4a78866478ac577105/crates/papyrus_config/src/presentation.rs#L27)):*
> ```XML
>             ParamPrivacy::Public => continue,
>             ParamPrivacy::Private => (),
>             ParamPrivacy::TemporaryValue => continue,
> ```

Why continue on temporary value?



_Code quote:_
```XML
ParamPrivacy::TemporaryValue => continue,
```

**Pull request closed without merging**
