### PR TITLE
feat(monitoring): add alerts grafana

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1237)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1237)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2Nmy-_dW3LyqatAq:-Nfp2Nmy-_dW3LyqatAr:bl3wf4a) (no related file):*
Consider renaming:
Incoming Execution Requests Rate --> Requests Rate - Execute Functions
Incoming Call Requests Rate --> Requests Rate - Call Functions

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2dSTAoupi1POi5Qe:-Nfp2dSTAoupi1POi5Qf:b-9tw01c) (no related file):*
Rename 
Execution --> Execute (2 places that I saw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2qLl2433rkARQxdf:-Nfp2qLl2433rkARQxdg:bykt6mk) (no related file):*
Consider renaming:
Execution Function Alerts --> Latency Alert - Execute Functions
Call Function Alerts --> Latency Alert - Call Functions

___

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1237)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2Nmy-_dW3LyqatAq:-NfpolenBUKdlbh5AqUc:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Consider renaming:
Incoming Execution Requests Rate --> Requests Rate - Execute Functions
Incoming Call Requests Rate --> Requests Rate - Call Functions
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2dSTAoupi1POi5Qe:-NfpolwrEe7xSD9a_xwv:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Rename 
Execution --> Execute (2 places that I saw)
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-Nfp2qLl2433rkARQxdf:-Nfpom7s0orxv-Y6-Sla:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Consider renaming:
Execution Function Alerts --> Latency Alert - Execute Functions
Call Function Alerts --> Latency Alert - Call Functions
</blockquote></details>

Done.

___

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1237#-:-NfuRlZNANR0D6bGUtaP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
