### PR TITLE
test(network): change get_connected_streams to return Stream

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(network): protocols return the IO (#1157)
- feat(network): extract get_connected_stream_futures to test utils (#1167)
- test(network): add create_swarm function
- test(network): change get_connected_streams to return Stream

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/test_utils.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-NebqmtB2ocrQORDr90Y:-NebqmtB2ocrQORDr90Z:basm2da) ([raw file](https://github.com/starkware-libs/papyrus/blob/446aacdfee989444d347f7c79ff276e288f6558b/crates/papyrus_network/src/test_utils.rs#L72)):*
> ```XML
>         TokioStreamExt::next(&mut filtered_swarm).await.unwrap(),
>     );
>     tokio::task::spawn(async move {
> ```

it's better to return the handler to the caller. just in case
___
*[`crates/papyrus_network/src/test_utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-NebqKQj1UonocsDJIxo:-NebqKQj1UonocsDJIxp:bygxd6k) ([raw file](https://github.com/starkware-libs/papyrus/blob/446aacdfee989444d347f7c79ff276e288f6558b/crates/papyrus_network/src/test_utils.rs#L79)):*
> ```XML
> 
> #[derive(Default)]
> struct GetStreamBehaviour {
> ```

consider moving the test stack to a separate file

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/test_utils.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-NebqmtB2ocrQORDr90Y:-NebrI0V1BqHCNu8Dufy:b-fxmepl) ([raw file](https://github.com/starkware-libs/papyrus/blob/446aacdfee989444d347f7c79ff276e288f6558b/crates/papyrus_network/src/test_utils.rs#L72)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's better to return the handler to the caller. just in case
</blockquote></details>

why? we won't join it because this will never end. The goal is to detach this

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/test_utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-NebqKQj1UonocsDJIxo:-NebuGbX3mviXjjFa0l6:b-t6yefj) ([raw file](https://github.com/starkware-libs/papyrus/blob/446aacdfee989444d347f7c79ff276e288f6558b/crates/papyrus_network/src/test_utils.rs#L79)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

consider moving the test stack to a separate file
</blockquote></details>

Done. Splitted to multiple commits for your convenience :)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/test_utils.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-NebqmtB2ocrQORDr90Y:-NempHCc9Q7Y0HxWB-j9:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/446aacdfee989444d347f7c79ff276e288f6558b/crates/papyrus_network/src/test_utils.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

why? we won't join it because this will never end. The goal is to detach this
</blockquote></details>

Done

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1177#-:-Neq_vN_6yE4HmgTErMs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
