### PR TITLE
feat(storage)!: add major and minor storage versions

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-NrnwegsBfOwg2D9rh5h:-NrnwegsBfOwg2D9rh5i:bqsp5tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/lib.rs#L137)):*
> ```XML
> 
> /// The current version of the storage state code.
> /// Major change required a resync, minor change does not and means versioned value change.
> ```

consider



_Suggestion:_
```XML
Major change requires a re-sync, minor change means a versioned value changed an re-sync is not required.
```
___
*[`crates/papyrus_storage/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nrnx66AD6KQYkJBwAEp:-Nrnx66B6k2zEkcmTX8P:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/lib.rs#L140)):*
> ```XML
> pub const STORAGE_VERSION_STATE: Version = Version { major: 0, minor: 13 };
> /// The current version of the storage blocks code.
> /// Major change required a resync, minor change does not and means versioned value change.
> ```





_Suggestion:_
```XML
Major change requires a re-sync, minor change means a versioned value changed an re-sync is not required.
```
___
*[`crates/papyrus_storage/src/lib.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-NrnzQJ9AinDcZQtsw15:-NrnzQJ9AinDcZQtsw16:bqsp5tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/lib.rs#L299)):*
> ```XML
>                 tracing::error!(
>                     "Storage major version has been changed, resync is needed. Ignore the \
>                      following deserialization error."
> ```

consider



_Suggestion:_
```XML
                    "Cannot deserialize storage version. Storage major version has been changed, re-sync is needed."
```
___
*[`crates/papyrus_storage/src/version.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro-VMJ8wWsX9bDxPej:-Nro-VMJ8wWsX9bDxPek:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/version.rs#L24)):*
> ```XML
>     #[error(
>         "Storage crate version {crate_version} is inconsistent with DB version {storage_version}. \
>          If the major version is different, resync is needed."
> ```





_Suggestion:_
```XML
re-sync
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro2v90BSn8qNr-clyX:-Nro2v90BSn8qNr-clyY:by6bnvw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/lib.rs#L295)):*
> ```XML
> fn get_storage_version(reader: StorageReader) -> StorageResult<Option<StorageVersion>> {
>     let current_storage_version_state =
>         reader.begin_ro_txn()?.get_state_version().map_err(|err| {
> ```

Consider matching on the result of `get_state_version` and panicking in case of deserialization error 



_Code quote:_
```XML
map_err
```
___
*[`crates/papyrus_storage/src/version.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro3Ne1ElNVsu_dd0D9:-Nro3Ne2DjkrV7Pyfa39:b-ttmuv0) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/version.rs#L14)):*
> ```XML
> const VERSION_BLOCKS_KEY: &str = "storage_version_blocks";
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> ```

Consider adding Ord



_Code quote:_
```XML
Clone, Debug, Default, Eq, PartialEq)
```
___
*[`crates/papyrus_storage/src/version_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro51Y7650k50kBSf2e:-Nro51Y7650k50kBSf2f:bad60e9) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L1)):*
> ```XML
> use core::panic;
> ```

Is this necessary?



_Code quote:_
```XML
use core::panic
```
___
*[`crates/papyrus_storage/src/version_test.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro5VPN-GIA2X_7OwE9:-Nro5VPN-GIA2X_7OwEA:b-wp2fg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L135)):*
> ```XML
>     let Err(err) = open_storage(config) else {
>         panic!("Unexpected Ok.");
>     };
> ```

unwrap_err



_Code quote:_
```XML
    let Err(err) = open_storage(config) else {
        panic!("Unexpected Ok.");
    };
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro2v90BSn8qNr-clyX:-Nro6REB8cF06GAMFVaG:b-fedcyd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/lib.rs#L295)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider matching on the result of `get_state_version` and panicking in case of deserialization error
</blockquote></details>

This is here and not in `get_state_version` because this is also relevant to the 'get_blocks_version' function. The problem is with the storage version in general and not for a specific scope.
I think we should return an error and not panic when it is possible, but I don't care to change it. 
___
*[`crates/papyrus_storage/src/version.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro3Ne1ElNVsu_dd0D9:-Nro72Sq0QEPJins03Qt:bfpo62b) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec6f69d8029f2c060b1881176fc584d08217be29/crates/papyrus_storage/src/version.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding Ord
</blockquote></details>

This is intentional. Different majors don't enable one to do everything, not use a higher major with a smaller major code or the opposite, they do not have any order they just can be equal or not.
___
*[`crates/papyrus_storage/src/version_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro51Y7650k50kBSf2e:-Nro7Y111aaWd0qmqOnw:b-cz5vsy) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

See the answer below.
___
*[`crates/papyrus_storage/src/version_test.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro5VPN-GIA2X_7OwE9:-Nro7_CeBrfOko9VOZBi:bc9zve9) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L135)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

unwrap_err
</blockquote></details>

Using unwrap_err requires the Ok value to impl Debug, which is not true for our StorageReader.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/version_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro51Y7650k50kBSf2e:-Nro9mFb6khUEF3wfzVh:bk7ktu9) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L1)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

See the answer below.
</blockquote></details>

But you still don't need to import this

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/version_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1749#-Nro51Y7650k50kBSf2e:-NroAz-32QUPmruvJH2S:bmllyli) ([raw file](https://github.com/starkware-libs/papyrus/blob/ea253fc7777c7fe1c3e6ddb4e02978ea7da1c09e/crates/papyrus_storage/src/version_test.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

But you still don't need to import this
</blockquote></details>

I didn't know that. I removed it.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1749)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
