### PR TITLE
Download deprecated classes not in storage

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Downloads a class even if it was downloaded before.

## What is the new behavior?
Before downloading a deprecated class, try to retrieve it from the storage. 
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT7dzEX1kdyxDFeAXWA:-NT7dzEX1kdyxDFeAXWB:bqvut4f) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/papyrus_node/src/main.rs#L59)):*
> ```XML
> // TODO(yair): define and implement configurable filtering.
> fn configure_tracing() {
>     let fmt_layer = fmt::layer().compact().with_target(true);
> ```

Intended?

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT81OjJD7yWFVUZim-K:-NT81OjJD7yWFVUZim-L:b-mexko3) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/papyrus_node/src/bin/central_source_integration_test.rs#L14)):*
> ```XML
>     let mut path = env::temp_dir();
>     path.push("data");
>     fs::create_dir_all(path.clone()).expect("Make a temporary `data` directory");
> ```

You can use https://docs.rs/tempdir/0.3.7/tempdir/index.html



_Code quote:_
```XML
    let mut path = env::temp_dir();
    path.push("data");
    fs::create_dir_all(path.clone()).expect("Make a temporary `data` directory");
```
___
*[`crates/starknet_client/src/lib.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT8-caADDbh3nWefPSQ:-NT8-caADDbh3nWefPSR:b-4112n1) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/starknet_client/src/lib.rs#L346)):*
> ```XML
>     Cairo1ContractClass(ContractClass),
>     APIContractClass(starknet_api::state::ContractClass),
>     APIDeprecatedContractClass(starknet_api::deprecated_contract_class::ContractClass),
> ```

Why not use a separate enum?



_Code quote:_
```XML
    APIContractClass(starknet_api::state::ContractClass),
    APIDeprecatedContractClass(starknet_api::deprecated_contract_class::ContractClass),
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

___
*[`crates/papyrus_node/src/main.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT7dzEX1kdyxDFeAXWA:-NTIRIZS2-BWx2Bub48c:bvth56w) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/papyrus_node/src/main.rs#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Intended?
</blockquote></details>

reverted
___
*[`crates/starknet_client/src/lib.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT8-caADDbh3nWefPSQ:-NTIRcGH3oBod92lSpmI:b-896fjb) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/starknet_client/src/lib.rs#L346)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not use a separate enum?
</blockquote></details>

Done

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yair-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NT7dzEX1kdyxDFeAXWA:-NTJTkYEDZy9mrkgSyam:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6251819247c96707db2b75abbd26f12f4423df5f/crates/papyrus_node/src/main.rs#L59)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

reverted
</blockquote></details>

Done.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NTJYXrA4mBQIEHE3_Et:-NTJYXrA4mBQIEHE3_Eu:bhdb4ey) ([raw file](https://github.com/starkware-libs/papyrus/blob/f003d8ee6fec3c8dcc824329b764cad25aa6bd27/crates/papyrus_node/src/bin/central_source_integration_test.rs#L25)):*
> ```XML
>     let central_source = CentralSource::new(config.central, VERSION_FULL, storage_reader)
>         .expect("Create new client");
>     let last_block_number = BlockNumber(283410);
> ```

This is weird.



_Code quote:_
```XML
283410
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/603#-NTJYXrA4mBQIEHE3_Et:-NTJYcdJ3IIEsgIhrWzP:bf2pwl9) ([raw file](https://github.com/starkware-libs/papyrus/blob/f003d8ee6fec3c8dcc824329b764cad25aa6bd27/crates/papyrus_node/src/bin/central_source_integration_test.rs#L25)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is weird.
</blockquote></details>

Never mind.

**Review by dan-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/603#-:-NTJYk9bESWnjVkfhicx:bnfp4nl)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yair-starkware)

**Pull request merged**
