### PR TITLE
Add version to the client.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/576#-NRgdddLCAIF2Bq7xjoE:-NRgdddMClACHn9yQNmT:bjnnewj) (no related file):*
1. I can pass the version as a & ‘static str, but it will make things a bit more complex (lifetime things), and because it is very cheap to create a new String, I prefer this. Do you think I should use &str instead?
2. I think it will be better to use ClientConfig struct instead of 4 different arguments; do you agree?

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576#-:-NRh0b3FCsfn_ENLignr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/576#-NRlIU3V8u99xo0iaMnu:-NRlIU3WCqkGzJtoaSzS:b-ktc206) (no related file):*
After talking with Dan, the version is not a real config option, so I remove it from the central config, and now the addition of the version is more straightforward.

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576#-:-NRmVIHwCTJp-JkVII9R:bnfp4nl)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576#-:-NT7ujTKBcIbv877T2Ma:bnfp4nl)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 17 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/576#-NT81Rt84u6JvOQuVVJI:-NT81Rt84u6JvOQuVVJJ:b-co3hnq) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0ea152dbbee46f83f32f4502b44160554f0b176/crates/papyrus_node/src/bin/central_source_integration_test.rs#L17)):*
> ```XML
>     let central_source =
>         CentralSource::new(config.central, VERSION_FULL).expect("Create new client");
>     let last_block_number = BlockNumber(283410);
> ```

This is the original number. I made a stupid mistake in the rebase.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/576#-:-NT82oR1A4z9N5XrZ758:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
