### PR TITLE
feat(network): send fin when encountering DB executor error

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptaoBx-PCHc7yeFTJB:-NptaoBx-PCHc7yeFTJC:b5lnd3) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/db_executor/mod.rs#L53)):*
> ```XML
> 
> impl DBExecutorError {
>     pub fn query_id(&self) -> Option<QueryId> {
> ```

please add "get_"
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbJw5Dh1wTdVFRrVl:-NptbJw5Dh1wTdVFRrVm:b-cfjm6t) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L98)):*
> ```XML
>             Err(err) => {
>                 debug!("Query failed. error: {err:?}");
>                 if let Some(query_id) = err.query_id() {
> ```

log if we get a join error
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptcB2o3UKBxMHmgNOz:-NptcB2o3UKBxMHmgNP-:b5wt6lz) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L103)):*
> ```XML
>                         .query_id_to_inbound_session_id
>                         .remove(&query_id)
>                         .expect("Received error on non existing query");
> ```

no need to panic here. not even log.. but you can for good measure
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbkFW5LaditVXnzRh:-NptbkFW5LaditVXnzRi:bkzcbpq) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L108)):*
> ```XML
>                         .send_data(Data::Fin, inbound_session_id)
>                         .unwrap_or_else(|e| {
>                             panic!("Failed to send data to peer. Session id not found error: {e:?}")
> ```

don't panic.. just log
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-Nptc2uq9nQexmr9FF1F:-Nptc2uq9nQexmr9FF1G:b-giyf76) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L153)):*
> ```XML
>         let (data, inbound_session_id) = res;
>         self.swarm.behaviour_mut().send_data(data, inbound_session_id).unwrap_or_else(|e| {
>             panic!("Failed to send data to peer. Session id not found error: {e:?}")
> ```

since you touched this.. also no need to panic here

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptaoBx-PCHc7yeFTJB:-NpxNWHhCogHA2GcYsP-:bl1uhc0) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/db_executor/mod.rs#L53)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please add "get_"
</blockquote></details>

I disagree. It's clear from this function name that it gets the query id
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbJw5Dh1wTdVFRrVl:-NpxKsDn5RYnYF9tpTsd:b-sdg5e4) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L98)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

log if we get a join error
</blockquote></details>

I'm already logging the error.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptcB2o3UKBxMHmgNOz:-NpxMxZT3ur7wFp0lR71:bnfybv0) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L103)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

no need to panic here. not even log.. but you can for good measure
</blockquote></details>

We do need to panic because if the mapping is wrong then possibly we can stay with a live inbound session that will never be closed
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbkFW5LaditVXnzRh:-NpxNeQ8DYdfTub0vjLY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L108)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

don't panic.. just log
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-Nptc2uq9nQexmr9FF1F:-NpxNKB1BPtslx7ehP1O:b-bqmi2y) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L153)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

since you touched this.. also no need to panic here
</blockquote></details>

We do need to panic here because the node is not functioning correctly if this happens. we requested to send data and the data disappeared

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptaoBx-PCHc7yeFTJB:-NpxXZnkCHOVeUUBcw5c:b-6ke2wn) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/db_executor/mod.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I disagree. It's clear from this function name that it gets the query id
</blockquote></details>

I think a getter should be named as such but ok
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbJw5Dh1wTdVFRrVl:-NpxXyzaBNH__5pJeiXH:bcavmfd) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L98)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm already logging the error.
</blockquote></details>

not in the case of join error.. `err.query_id()` will return `None` and it's ignored
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptcB2o3UKBxMHmgNOz:-NpxXoJf7S1WLOBKr4Qo:bl093us) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L103)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We do need to panic because if the mapping is wrong then possibly we can stay with a live inbound session that will never be closed
</blockquote></details>

let's discuss this f2f.. regardless we need to find a way to handle errors and not panic once it's connected to main
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-Nptc2uq9nQexmr9FF1F:-NpxYFxpCIcZcJTrJMK7:b-qmndaz) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L153)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We do need to panic here because the node is not functioning correctly if this happens. we requested to send data and the data disappeared
</blockquote></details>

it means we are trying to send data to the wrong session id.. worst case we won't send the data it doesn't mean that the node should crash

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptcB2o3UKBxMHmgNOz:-NqMmRpNCLfTx6iVwZHz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L103)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

let's discuss this f2f.. regardless we need to find a way to handle errors and not panic once it's connected to main
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-Nptc2uq9nQexmr9FF1F:-NqMmS_kDQ1V7uMoJXZZ:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L153)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It does, because otherwise we will have a node that skips some of the data and debugging it will be very hard
</blockquote></details>

Done

**Review by nagmo-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-:-NqREgtQAk-3naCgF5OE:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-NptbJw5Dh1wTdVFRrVl:-NqRESTD3959nWZCL31X:b-b2ykd2) ([raw file](https://github.com/starkware-libs/papyrus/blob/917910fb475883bc04185080d9fc9709b508b18d/crates/papyrus_network/src/network_manager/mod.rs#L98)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

line 97 is above the `if let`
</blockquote></details>

consider logging in the `else` clause with an error level. this debug log on line 97 will be omitted in a production build

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667#-:-NqRHQvEDh6LgyCRx0aa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1667)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
