### PR TITLE
feat(common): calculate patricia root hash

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NddDqyK7Yty5dCeFHqz:-NddDqyL5NsDzQgC75aZ:b-uuiimj) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a1d32cb5f3fb8e5e38a4cd4a981cfbcdf7f81ef/crates/papyrus_common/src/patricia_hash_tree.rs#L77)):*
> ```XML
> fn get_hash(sub_tree: SubTree<'_>) -> StarkFelt {
>     if sub_tree.height == TREE_HEIGHT {
>         return sub_tree.leaves.first().unwrap().value;
> ```

Please refrain from unwraps,
Please add a CI lint (not related to this PR)
___
*[`crates/papyrus_common/src/patricia_hash_tree_test.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NddE_ETBa-cKCx_cAGF:-NddE_ETBa-cKCx_cAGG:b17lo01) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a1d32cb5f3fb8e5e38a4cd4a981cfbcdf7f81ef/crates/papyrus_common/src/patricia_hash_tree_test.rs#L6)):*
> ```XML
> 
> #[test]
> fn test_patricia() {
> ```

Where are these values from? Please add a comment.



_Code quote:_
```XML
fn test_patricia() 
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134)* status: 0 of 7 files reviewed, all discussions resolved

___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NddDqyK7Yty5dCeFHqz:-NddOYcW5185nlee2eza:b90a232) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a1d32cb5f3fb8e5e38a4cd4a981cfbcdf7f81ef/crates/papyrus_common/src/patricia_hash_tree.rs#L77)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please refrain from unwraps,
Please add a CI lint (not related to this PR)
</blockquote></details>

1. Done.
___
*[`crates/papyrus_common/src/patricia_hash_tree_test.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NddE_ETBa-cKCx_cAGF:-NddOXFFD2D-apxLx3n5:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3a1d32cb5f3fb8e5e38a4cd4a981cfbcdf7f81ef/crates/papyrus_common/src/patricia_hash_tree_test.rs#L6)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Where are these values from? Please add a comment.
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjTSqg56qdrzt1o1MP:-NdjTSqg56qdrzt1o1MQ:bbc63gv) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L21)):*
> ```XML
> //! - A leaf: The hash is the input value of its key.
> //! - A single edge: pedersen_hash(child_hash, edge_mark) + edge_length.
> //! - '0' and '1' edges: pedersen_hash(zero_child_hash, one_child_hash).
> ```

Consider adding a link to some article about Patricia
___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjU3tc4aUmX2WatCmT:-NdjU3tc4aUmX2WatCmU:bift7bk) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L64)):*
> ```XML
>     let leaves: Vec<Entry> = values
>         .into_iter()
>         .zip(0u64..)
> ```

Use enumerate instead of zip
___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-Ndj_ICH4lv6QpDgUMi0:-Ndj_ICH4lv6QpDgUMi1:bescuzy) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L72)):*
> ```XML
> // Recursive hash calculation. There are 3 cases:
> // - Leaf: The sub tree height is maximal. It should contain exactly one entry.
> // - Edge: All the keys start with a longest common ('0's) prefix. NOTE: We assume that the keys are
> ```

We assume that the keys are in ascending order -> We assume that the keys are a continuous range
___
*[`crates/papyrus_common/src/patricia_hash_tree_test.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjajJ25_zsV8dqIVPY:-NdjajJ25_zsV8dqIVPZ:b-s5nujv) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree_test.rs#L33)):*
> ```XML
>             .unwrap();
>     assert_eq!(root, expected_root);
> }
> ```

add an example from starknet

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjTSqg56qdrzt1o1MP:-NdyArdgD5d99NgLjoh2:b4x6jzt) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L21)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider adding a link to some article about Patricia
</blockquote></details>

I'd rather avoid it, links are unmaintainable.
This definition should be self-contained.
___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjU3tc4aUmX2WatCmT:-Ndjbl64CYNsnXpB2DVB:b-pik26) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use enumerate instead of zip
</blockquote></details>

Enumerate returns `usize` type, I need `u64`.
___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-Ndj_ICH4lv6QpDgUMi0:-Ndy6NIoEFcxJxlp_R22:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We assume that the keys are in ascending order -> We assume that the keys are a continuous range
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/patricia_hash_tree_test.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjajJ25_zsV8dqIVPY:-Ndy9EYm3pHiuk5y5hCY:b-4ap1rl) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree_test.rs#L33)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add an example from starknet
</blockquote></details>

Why?
In Starknet feeder, there is no API neither for the final leaves of the tree nor for the root hash.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-:-Ne3-N7C6ak_-VL9Gk5J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/patricia_hash_tree.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1134#-NdjTSqg56qdrzt1o1MP:-Ne3-7TN2E51AmdJ5VfA:b-td83ag) ([raw file](https://github.com/starkware-libs/papyrus/blob/2da153c57e4b8d4fc00eab0b74157ceeff70e4c9/crates/papyrus_common/src/patricia_hash_tree.rs#L21)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'd rather avoid it, links are unmaintainable.
This definition should be self-contained.
</blockquote></details>

Link to a third party article. Why is it unmaintainable?

**Pull request merged**
