### PR TITLE
test(network): return network manager tests

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels
- refactor(network): db executor is removed from NetworkManager and runs in a separate task
- WIP
- test(network): return network manager tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2124)

### CODE REVIEW

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2124#-:-O081Zov-3KTU3PWui7X:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2124)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2124#-O097brI5JG-6LNrEls8:-O097brI5JG-6LNrEls9:b3y6rnj) ([raw file](https://github.com/starkware-libs/papyrus/blob/7813706b9791645419fa652ab09d1d2accb6cda8/crates/papyrus_network/src/network_manager/test.rs#L267)):*
> ```XML
>             // Calling pending to let the select arm above finish.
>             pending::<()>().await
>         } => {
> ```

Seems a bit simpler to me



_Suggestion:_
```XML
        _ = async move {
            let (query_got, mut responses_sender) = inbound_query_receiver.next().await.unwrap();
            assert_eq!(query_got.unwrap(), query);
            for response in responses_clone {
                responses_sender.feed(response).await.unwrap();
            }
            responses_sender.close().await.unwrap();
            assert_eq!(get_responses_fut.await, responses);
        } => {
```
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2124#-O0961Lr65TgE15vPMpY:-O0961Lr65TgE15vPMpZ:b-gasemj) ([raw file](https://github.com/starkware-libs/papyrus/blob/7813706b9791645419fa652ab09d1d2accb6cda8/crates/papyrus_network/src/network_manager/test.rs#L364)):*
> ```XML
>     static ref VEC2: Vec<u8> = vec![6, 7, 8];
>     static ref VEC3: Vec<u8> = vec![9, 10];
> }
> ```

I thought we put these at the top of the file?



_Code quote:_
```XML
lazy_static! {
    static ref VEC1: Vec<u8> = vec![1, 2, 3, 4, 5];
    static ref VEC2: Vec<u8> = vec![6, 7, 8];
    static ref VEC3: Vec<u8> = vec![9, 10];
}
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2124)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2124#-O097brI5JG-6LNrEls8:-O09Bwt_8rct5-M_OE1o:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7813706b9791645419fa652ab09d1d2accb6cda8/crates/papyrus_network/src/network_manager/test.rs#L267)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Seems a bit simpler to me
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2124#-O0961Lr65TgE15vPMpY:-O09C9xvB9B9jdapQPyY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7813706b9791645419fa652ab09d1d2accb6cda8/crates/papyrus_network/src/network_manager/test.rs#L364)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I thought we put these at the top of the file?
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2124)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
