### PR TITLE
refactor(network): remove InternalQuery

### PR DESCRIPTION
**Pull request by ShahakShama**
- chore(network): unite Data with SignedBlockHeader
- refactor(network): remove data_type from Query
- refactor(network): remove InternalQuery

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2048)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2048)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2048#-NyoqQhD4YJopeHGAs_k:-NyoqQhD4YJopeHGAs_l:bpbp9ka) ([raw file](https://github.com/starkware-libs/papyrus/blob/d829605693f71581f8e67fa8471e9874424456e8/crates/papyrus_network/src/lib.rs#L87)):*
> ```XML
>     pub direction: Direction,
>     pub limit: u64,
>     pub step: u64,
> ```

How did you decide which type to use, I see Internal was u64?



_Code quote:_
```XML
    pub limit: u64,
    pub step: u64,
```
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2048#-Nyoq72L5sc6bFl8qpE2:-Nyoq72L5sc6bFl8qpE3:b45h) ([raw file](https://github.com/starkware-libs/papyrus/blob/d829605693f71581f8e67fa8471e9874424456e8/crates/papyrus_network/src/network_manager/test.rs#L268)):*
> ```XML
>         GenericNetworkManager::generic_new(mock_swarm, MockDBExecutor::default(), BUFFER_SIZE);
>     // define query
>     let query_limit = 5usize;
> ```





_Suggestion:_
```XML
let query_limit: usize = 5;
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2048)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @matan-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2048#-NyoqQhD4YJopeHGAs_k:-NyovB3W1sHUcbXMRvdm:bky0etl) ([raw file](https://github.com/starkware-libs/papyrus/blob/d829605693f71581f8e67fa8471e9874424456e8/crates/papyrus_network/src/lib.rs#L87)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

How did you decide which type to use, I see Internal was u64?
</blockquote></details>

Starknet API has u64 in block number, and I have to choose one of them and use it everywhere
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2048#-Nyoq72L5sc6bFl8qpE2:-Nyov_JdBwqYYigU5pfV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d829605693f71581f8e67fa8471e9874424456e8/crates/papyrus_network/src/network_manager/test.rs#L268)):*
> ```XML
>         GenericNetworkManager::generic_new(mock_swarm, MockDBExecutor::default(), BUFFER_SIZE);
>     // define query
>     let query_limit = 5usize;
> ```

Done.

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2048)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2048)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
