### PR TITLE
chore: reenable clippy in ci by allowing blocks_in_conditions

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`.github/workflows/ci.yml` line 142 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1694#-NqN6zDb23vGsqXPfR-p:-NqN6zDb23vGsqXPfR-q:b-i782w6) ([raw file](https://github.com/starkware-libs/papyrus/blob/971aae32bd80618b4d19590ef2195822a7c87c41/.github/workflows/ci.yml#L142)):*
> ```YAML
>           cargo clippy --all-targets --all-features -- -D warnings -D future-incompatible
>         -D nonstandard-style -D rust-2018-idioms -D unused -D clippy::unwrap_used
>         -A clippy::blocks_in_conditions  # This is because of a bug in tracing: https://github.com/tokio-rs/tracing/issues/2876
> ```

Do we still need the async_trait? New Rust version supports async methods of traits except in some cases.

**Review by yair-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694#-:-Nr0vFzk7FfMYqq7-25k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694#-:-Nr10q768We_FtOMpMma:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1694)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
