### PR TITLE
chore(common): separate the block hash calculation from the commitmen…

### PR DESCRIPTION
**Pull request by yair-starkware**
…ts calculation

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1813)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1813)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1813#-NsxQ-7_AaocZJSRikQz:-NsxQ-7_AaocZJSRikR-:bi8q5oz) (no related file):*
The json files changed to 0.13.1 values

___

**Review by ShahakShama — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/block_hash_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1813#-NtL4Mxx7f93S-uFlgch:-NtL4Mxx7f93S-uFlgci:b-ppuf6o) ([raw file](https://github.com/starkware-libs/papyrus/blob/f109828affbfb36b2b23f62b80976e9a661aac24/crates/papyrus_common/src/block_hash_test.rs#L1)):*
> ```XML
> use starknet_api::block::Block;
> ```

Add a test where you remove one of the required fields (e.g transaction_commitment) and see you get an error

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1813)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/block_hash_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1813#-NtL4Mxx7f93S-uFlgch:-NtLLH8s2XFKzxHffwLn:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/f109828affbfb36b2b23f62b80976e9a661aac24/crates/papyrus_common/src/block_hash_test.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a test where you remove one of the required fields (e.g transaction_commitment) and see you get an error
</blockquote></details>

Done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1813#-:-NtQ0n-x1BDfKNMv4tZ9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
