### PR TITLE
feat(JSON-RPC): execution works if node is not synced on casms

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1492)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1492)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqlW27ZvRsi4W2prQ:-NlHqlW27ZvRsi4W2prR:bajhr38) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_execution/src/execution_test.rs#L0)):*
I think we need a test that executes a tx with a missing casm
___
*[`crates/papyrus_execution/src/state_reader.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHmf7VCG6x8dSy5PZO:-NlHmf7W1OtQd3NSKun-:b96tuhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_execution/src/state_reader.rs#L31)):*
> ```XML
>     // We want to return a custom error when missing a compiled class, but we need to return
>     // Blockifier's error, so we store the missing class's hash in case of error.
>     pub missing_compiled_class: Option<ClassHash>,
> ```

Consider changing this to a vec because there might be multiple calls to the function



_Code quote:_
```XML
Option<ClassHash>
```
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqSx67iOpIHz3bpFy:-NlHqSx67iOpIHz3bpFz:baujbq4) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_4/api/mod.rs#L528)):*
> ```XML
>     fn try_from(value: ExecutionError) -> Result<Self, Self::Error> {
>         match value {
>             ExecutionError::MissingCompiledClass { .. } => Ok(BLOCK_NOT_FOUND),
> ```

Please add a log message
___
*[`crates/papyrus_rpc/src/v0_5/api/mod.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqb8x3toYiDJFWdSc:-NlHqb8x3toYiDJFWdSd:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_5/api/mod.rs#L534)):*
> ```XML
>     fn try_from(value: ExecutionError) -> Result<Self, Self::Error> {
>         match value {
>             ExecutionError::MissingCompiledClass { .. } => Ok(BLOCK_NOT_FOUND),
> ```

same
___
*[`crates/papyrus_rpc/src/v0_6/api/mod.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqbvWAch9X1SEvBJk:-NlHqbvWAch9X1SEvBJl:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_6/api/mod.rs#L589)):*
> ```XML
>     fn try_from(value: ExecutionError) -> Result<Self, Self::Error> {
>         match value {
>             ExecutionError::MissingCompiledClass { .. } => Ok(BLOCK_NOT_FOUND),
> ```

same

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1492)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqlW27ZvRsi4W2prQ:-NlI3STn4pQ67OeXRvpq:bio1t9q) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_execution/src/execution_test.rs#L)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we need a test that executes a tx with a missing casm
</blockquote></details>

I agree. Next PR though
___
*[`crates/papyrus_execution/src/state_reader.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHmf7VCG6x8dSy5PZO:-NlI3_orEhZe8BPjLWrL:b-aycca0) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_execution/src/state_reader.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider changing this to a vec because there might be multiple calls to the function
</blockquote></details>

Once the function fails though, it shouldn't be called again. So only a single time will this variable be set
Even if I'm wrong, I don't care which of the problematic class hashes is returned in the error
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqSx67iOpIHz3bpFy:-NlIC-Mr3-f10AbTwFJ2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_4/api/mod.rs#L528)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add a log message
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_5/api/mod.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqb8x3toYiDJFWdSc:-NlIC-hK691PQC_YI4Wq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_5/api/mod.rs#L534)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_6/api/mod.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-NlHqbvWAch9X1SEvBJk:-NlIC01n1VyIZENYp4t-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/accd632f041470536fc6f46b5e9c595286b111a0/crates/papyrus_rpc/src/v0_6/api/mod.rs#L589)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1492#-:-NlIRdC96Nb0sJ_gtlY7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1492)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
