### PR TITLE
doc(starknet_client): fix doc and crate description.

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/926#-NaLltrK2m8VvMelTgym:-NaLltrLBzJfV0X8O73r:b-xsw1zk) (no related file):*
The comments here have the same format as in the writer client in #901  

___

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/926#-NaLnwqk-xn4xsRGxwCP:-NaLnwqk-xn4xsRGxwCQ:b-67wzja) (no related file):*
Consider adding 
```
#![warn(missing_docs)]
```

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/926#-NaLnwqk-xn4xsRGxwCP:-NaLo92ACuuOHNGJpJ6X:b-n1vk7l) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding 
```
#![warn(missing_docs)]
```
</blockquote></details>

Where should I add it?

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Where should I add it?
</blockquote></details>

At the top of the lib file

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/926#-NaLnwqk-xn4xsRGxwCP:-NaLqo7K35jMnLeRsbHU:b-xi5vjx) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

At the top of the lib file
</blockquote></details>

We haven't reached the level that everything is documented in this crate (and from what I understood from @dan-starkware we have no intention to do it since this crate is going to disappear once we're decentralized)

___

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
