### PR TITLE
Make get_block_by_number in the general form.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/507)

### CODE REVIEW

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_load_test/src/transactions.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/507#-NOn2UDU7oLRHwTvs7pz:-NOn2UDU7oLRHwTvs7q-:bkyexkk) ([raw file](https://github.com/starkware-libs/papyrus/blob/08c21de18c56983e15efff6b8fea972c40c64047/crates/papyrus_load_test/src/transactions.rs#L37)):*
> ```XML
> }
> 
> // Given [Name, "Path";] write the function:
> ```

this is unrelated change to the purpuse of this pull request

**Comment by DvirYo-starkware** [comment]
This pull request make the second function in the general form of read the requests from a file.
In this case all the data in the file is block number so in the future maybe we should just draw it.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/507)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/507#-NOyhWZ6ETH0NdR0EC3n:-NOyhWZ6ETH0NdR0EC3o:bb6bkk0) ([raw file](https://github.com/starkware-libs/papyrus/blob/08c21de18c56983e15efff6b8fea972c40c64047/crates/papyrus_load_test/src/create_request.rs#L5)):*
> ```XML
> use crate::jsonrpc_request;
> 
> pub fn get_block_with_tx_hashes_by_number(block_number: String) -> jsonVal {
> ```

&str



_Code quote:_
```XML
String
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/507)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
