### PR TITLE
test(JSON-RPC): send a slack alert upon GW integration test failure

### PR DESCRIPTION
**Pull request by TzahiTaub**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

gateway_integration_test failure fails the workflow with no alert.

## What is the new behavior?

- A failure will trigger sending an error message to Slack.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1273#-NgldMAw-YEzZVQ4CdHS:-NgldMAw-YEzZVQ4CdHT:b-kjuqoc) (no related file):*
is there a place where we can configure these 'secret' values which is not seen by outsiders?

___

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1273#-NgldMAw-YEzZVQ4CdHS:-NgmUVncC2FxNQhk2JW8:btceaiw) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

is there a place where we can configure these 'secret' values which is not seen by outsiders?
</blockquote></details>

In the repo settings (can only be accessed by the owner/privileged ysers).

___

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1273#-NgldMAw-YEzZVQ4CdHS:-NgmVHMb6KPwR3pIVgN-:b-hqqv6j) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

In the repo settings (can only be accessed by the owner/privileged ysers).
</blockquote></details>

The used secrets were already added

___

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273#-:-Ngmwv0yE6v-uVUbnloS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
