### PR TITLE
Yoav/sync status/share mutex

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Share a Mutex object between the gateway and the sync, for sending the sync status.  

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_sync/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1fpnvAygVm6Puv23w:-Na1fpnvAygVm6Puv23x:byzz6kl) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b3e6387da64ead9dfe1ec121b13f65aa7af116e/crates/papyrus_sync/src/lib.rs#L43)):*
> ```XML
> pub struct GenericStateSync<TCentralSource: CentralSourceTrait + Sync + Send> {
>     config: SyncConfig,
>     shared_sync_status: Arc<Mutex<Option<SyncingState>>>,
> ```

Document new parameter.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1jFl62Y51duNyjjtl:-Na1jFl62Y51duNyjjtm:bi9vxoc) (no related file):*
@dan-starkware please also review

___

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1fpnvAygVm6Puv23w:-Na5dcuUCTM9xHyGl01P:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3b3e6387da64ead9dfe1ec121b13f65aa7af116e/crates/papyrus_sync/src/lib.rs#L43)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Document new parameter.
</blockquote></details>

Done.

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 1633 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaQAMd9RNRu1tVevsM:-NaaQAMd9RNRu1tVevsN:b-82jaj5) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L1633)):*
> ```XML
> 
>     let gateway_config = get_test_gateway_config();
>     let shared_syncing_state = Arc::new(Mutex::new(SyncingState::default()));
> ```

Use the test utils?



_Code quote:_
```XML
Arc::new(Mutex::new(SyncingState::default()))
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 11 files at r4, 6 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 8 of 15 files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1636 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaQjLV4KKDm_r6swAc:-NaaQjLV4KKDm_r6swAd:b-82jaj5) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1636)):*
> ```XML
> 
>     let gateway_config = get_test_gateway_config();
>     let shared_syncing_state = Arc::new(Mutex::new(SyncingState::default()));
> ```

Use the test utils?



_Code quote:_
```XML
Arc::new(Mutex::new(SyncingState::default()));
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 202 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaTQYUBhBQNeMvv1XP:-NaaTQYUBhBQNeMvv1XQ:b-nmkmyv) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_sync/src/lib.rs#L202)):*
> ```XML
>     async fn sync_while_ok(&mut self) -> StateSyncResult {
>         // TODO(yoav): Set actual values for the sync status.
>         *self.shared_syncing_state.lock().unwrap() = SyncingState::Synced;
> ```

Is there a convention for mutex error handling? 



_Code quote:_
```XML
.unwrap()
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r4, 3 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 4 of 15 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1jFl62Y51duNyjjtl:-NaarvDq4nGoQUGG8F57:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

@dan-starkware please also review
</blockquote></details>

Done.

___
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 1633 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaQAMd9RNRu1tVevsM:-NaaizmB34P9E_8VFJqN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L1633)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Use the test utils?
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_4_0/api/test.rs` line 1636 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaQjLV4KKDm_r6swAc:-Naaj9CaDKxfmjWJZ7vW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_gateway/src/v0_4_0/api/test.rs#L1636)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Use the test utils?
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 202 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/873#-NaaTQYUBhBQNeMvv1XP:-NaarNtq84kXufn3HclR:b-wy84w0) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0661d7737e46cfd28109dc0421449bd128ecbb7/crates/papyrus_sync/src/lib.rs#L202)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is there a convention for mutex error handling? 
</blockquote></details>

I switched to using RwLock

**Review by dan-starkware — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1jFl62Y51duNyjjtl:-NabA7R573DSOGwOIQkW:bf14dcs) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Consider [tokio RwLock](https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html)
*The priority policy of Tokio’s read-write lock is _fair_ (or [_write-preferring_](https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock#Priority_policies)), in order to ensure that readers cannot starve writers. Fairness is ensured using a first-in, first-out queue for the tasks awaiting the lock; if a task that wishes to acquire the write lock is at the head of the queue, read locks will not be given out until the write lock has been released. This is in contrast to the Rust standard library’s `std::sync::RwLock`, where the priority policy is dependent on the operating system’s implementation.*

___

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider [tokio RwLock](https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html)
*The priority policy of Tokio’s read-write lock is _fair_ (or [_write-preferring_](https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock#Priority_policies)), in order to ensure that readers cannot starve writers. Fairness is ensured using a first-in, first-out queue for the tasks awaiting the lock; if a task that wishes to acquire the write lock is at the head of the queue, read locks will not be given out until the write lock has been released. This is in contrast to the Rust standard library’s `std::sync::RwLock`, where the priority policy is dependent on the operating system’s implementation.*
</blockquote></details>

In addition, `std::sync::RwLock` is blocking (the current thread until it can be acquired).

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/873#-Na1jFl62Y51duNyjjtl:-NabRA-x1E5qxqb8mldK:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

In addition, `std::sync::RwLock` is blocking (the current thread until it can be acquired).
</blockquote></details>

Done.

___

**Review by dan-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/873#-:-NafPNTA1kWHY1ZT6mfj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
