### PR TITLE
refactor(consensus): switch ValidatorId to a plain Felt

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2137)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2137?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2134** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2134?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2131?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2126** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2137** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2137?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2125** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2125?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2137)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2137#-O09L2_SEhi6wcfVq1NM:-O09R5ru-4o39a3NepXS:b-dxsz1c) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this PR needed? What's wrong with contract address?
</blockquote></details>

Well it's not actually certain that we will be using ContractAddress. Also ContractAddress didn't have Display, which is nice for readable printing. So I decided to just go to a more basic type (ContractAddress is basically just an alias for Felt anyways).

___
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2137#-O09KbCY0qYYlM7h8Kpv:-O09QbctA7dpmSGIa6K7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/77789e71e2eb76b463b753daa811f55fc3c1998d/crates/papyrus_protobuf/src/consensus.rs#L8)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why StarkHash and not felt? Is the proposer representing some hash?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2137#-O09KukV6h1oJxsyzph8:-O09QzZl6BXd5QejVWI1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/77789e71e2eb76b463b753daa811f55fc3c1998d/crates/sequencing/papyrus_consensus/src/types.rs#L15)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here. Why Hash and not Felt?
</blockquote></details>

Done.

**Comment by dan-starkware** [comment]
Please add @ittaysw (FYI) in proto/specs related PRs

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2137)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2137#-O09L2_SEhi6wcfVq1NM:-O0DvWRt9duoch3Ix1Hr:b-l40cje) (no related file):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Well it's not actually certain that we will be using ContractAddress. Also ContractAddress didn't have Display, which is nice for readable printing. So I decided to just go to a more basic type (ContractAddress is basically just an alias for Felt anyways).
</blockquote></details>

1.  ContractAddress is just a few layers of abstraction over Felt
2.  The current thought is to use contract address, but it isn't actually set in stone yet
3.  ContractAddress didn't have the Display trait and given (2) I didn't want to invest in adding it to an external crate

Dan said the Debug for ContractAddress is being fixed so there is no need to do this. Holding off on this PR for now.

___

**Pull request closed without merging**
