### PR TITLE
test(network): add discovery unit tests

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(network): add discovery behaviour
- test(network): add discovery unit tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)* status: all files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_g5cxAek9aD3bbm4V:-Nv_g5cxAek9aD3bbm4W:bf3wbpp) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L19)):*
> ```XML
> use crate::test_utils::next_on_mutex_stream;
> 
> const TIMEOUT: Duration = Duration::from_secs(5);
> ```

isn't 5 seconds a lot?
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_gg8Y5j_Vc7HvVumP:-Nv_gg8Y5j_Vc7HvVumQ:b-xa32o8) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L51)):*
> ```XML
>         FromOtherBehaviourEvent::PauseDiscovery,
>     ));
>     assert!(behaviour.next().now_or_never().is_none());
> ```

I think you should have a timeout here as well to cover the posibility that there's an event going to pop. just expect the timeout to hit 
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_h7UGCuoVe_H6oISw:-Nv_h7UGCuoVe_H6oISx:b-dk1k6h) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L60)):*
> ```XML
> 
> #[tokio::test]
> async fn discovery_outputs_single_query_on_query_finished() {
> ```

don't you want to check the event?
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_hXny26nrATYarSUG:-Nv_hXny26nrATYarSUH:bmym4ng) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L108)):*
> ```XML
>             mutex.lock().await.on_other_behaviour_event(
>                 mixed_behaviour::InternalEvent::NotifyDiscovery(
>                     FromOtherBehaviourEvent::PauseDiscovery,
> ```

shouldn't this event be resume? if not then I didn't understand the test.. please add info
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_hrbr8gCDv6mUyxhv:-Nv_hrbr8gCDv6mUyxhw:b-g8vo9x) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L127)):*
> ```XML
>     select! {
>         _ = async {
>             tokio::time::sleep(SLEEP_DURATION).await;
> ```

why do you need the sleep here? I think it should work without it

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_g5cxAek9aD3bbm4V:-Nv_iuQ8D6-bJPO8_i69:b-4144le) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L19)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

isn't 5 seconds a lot?
</blockquote></details>

We do this sleep just if the test fails (If I didn't have this timeout then a failing test will be stuck on a loop
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_gg8Y5j_Vc7HvVumP:-Nv_jhShAjKxF1pOJBuG:b-1vw5ec) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L51)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think you should have a timeout here as well to cover the posibility that there's an event going to pop. just expect the timeout to hit
</blockquote></details>

I think this is ok. The scenario you described is considered a bug (It can still happen ofc)
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_h7UGCuoVe_H6oISw:-Nv_jCOO4oLEVmAeNgNH:bh1xl62) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L60)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

don't you want to check the event?
</blockquote></details>

I do that in another test
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_hXny26nrATYarSUG:-Nv_jGQ34tbb6zEr84u0:b-bcbtlq) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L108)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

shouldn't this event be resume? if not then I didn't understand the test.. please add info
</blockquote></details>

You're right. I'll check if there's a bug here
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_hrbr8gCDv6mUyxhv:-Nv_jLQM9tIoONg5s2ja:b-2b5oi3) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L127)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why do you need the sleep here? I think it should work without it
</blockquote></details>

It works without it, but then I don't test what I want to test
I want to make sure that the call to `next` will return pending before the Notify happens, and that the Notify causes an additional poll

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_hXny26nrATYarSUG:-Nv_q9hR6JYoVEr0TWOn:bgxlk0p) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L108)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're right. I'll check if there's a bug here
</blockquote></details>

Fixed. Also fixed a bug in the test that hided this from failing the test.

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_g5cxAek9aD3bbm4V:-Nva-Z2s3PK6f4ex_Wjn:b-m4e7nb) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We do this sleep just if the test fails (If I didn't have this timeout then a failing test will be stuck on a loop
</blockquote></details>

just make it smaller. that's a  lot

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_g5cxAek9aD3bbm4V:-Nva9X9b2VAKs6GNoQ7r:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L19)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

just make it smaller. that's a  lot
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-Nv_gg8Y5j_Vc7HvVumP:-Nva9XiW5gT0xi7bwvF1:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/40b5fe69225743ba96bf7b2904754409ef20b0f0/crates/papyrus_network/src/discovery/discovery_test.rs#L51)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this is ok. The scenario you described is considered a bug (It can still happen ofc)
</blockquote></details>

Done

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1906#-:-NvaFxbL-4zarT-d4VlR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
