### PR TITLE
modify chart to support nodeSelector and tolerations

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/789)

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/789)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/789#-NZ6TQB-3H8iHY4c4yIl:-NZ6TQB-3H8iHY4c4yIm:byg3vd2) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f9926abb5f56af76f8a558f207f767779686c32/deployments/helm/values.yaml#L26)):*
> ```YAML
> deployment:
>   # Optional - nodeSelector
>   node_selector:
> ```

nodeSelector

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/789#-NZ6TQB-3H8iHY4c4yIl:-NZL7HV3-MTzc694W4LG:b-gyub1b) ([raw file](https://github.com/starkware-libs/papyrus/blob/8f9926abb5f56af76f8a558f207f767779686c32/deployments/helm/values.yaml#L26)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

nodeSelector
</blockquote></details>

done. I will make another PR to align everything to camleCase.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/789)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/789)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/789#-:-NZSgkgxCA3COB76g8-W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eranreshef-starkware)

**Pull request merged**
