### PR TITLE
Add multi-version support - no path mapping yet

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix

- [x] Feature

- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/661)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #661** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/661" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/661?utm_source=stack-comment).

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/661)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`Dockerfile` line 43 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9K-Cx-IlhWRD4HRTN:-NV9K-Cx-IlhWRD4HRTO:b-6zktkc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f43189b24e92243b5721a27656fe103f3cbb9d13/Dockerfile#L43)):*
> ```Dockerfile
> COPY --from=copy_toml /app .
> 
> # add the proc_macro code since cargo init puts autogenerated code in lib.rs file that breaks the build
> ```

`Add`
Also end the sentence with a full stop.
___
*[`crates/papyrus_gateway/Cargo.toml` line 20 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9KKHj5s2wlPXo5okk:-NV9KKHj5s2wlPXo5okl:bc58n3c) ([raw file](https://github.com/starkware-libs/papyrus/blob/f43189b24e92243b5721a27656fe103f3cbb9d13/crates/papyrus_gateway/Cargo.toml#L20)):*
> ```TOML
> tracing.workspace = true
> url.workspace = true
> papyrus_proc_macros = { path = "../papyrus_proc_macros"}
> ```

Please sort by lexicographic order
___
*[`crates/papyrus_gateway/src/test_utils.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9U3eq6ZxbBT3wddF6:-NV9U3eq6ZxbBT3wddF7:b15wtiy) ([raw file](https://github.com/starkware-libs/papyrus/blob/2fcabc5bc912b75e0d8f68ff75c99931bc467e27/crates/papyrus_gateway/src/test_utils.rs#L20)):*
> ```XML
> 
> pub(crate) fn get_test_rpc_server_and_storage_writer()
> -> (RpcModule<JsonRpcServerV0_3_0Impl>, StorageWriter) {
> ```

Seems wrong to have a specific version in the general utils.
___
*[`crates/papyrus_gateway/src/api/mod.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9UtzM-cTO5fwPEdy4:-NV9UtzM-cTO5fwPEdy5:bgq58m9) ([raw file](https://github.com/starkware-libs/papyrus/blob/39651be2245ba2bca68f608422c7fe6fe66a7d4e/crates/papyrus_gateway/src/api/mod.rs#L116)):*
> ```XML
>                 version_config::VersionState::Deprecated => None,
>                 version_config::VersionState::Supported | version_config::VersionState::Latest => {
>                     if *version_id == version_config::VERSION_0_3_0 {
> ```

Consider match here.
___
*[`crates/papyrus_gateway/src/api/v0_3_0.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9-nsn9QhlTGlbGNny:-NV9-nsn9QhlTGlbGNnz:b8ruzmv) ([raw file](https://github.com/starkware-libs/papyrus/blob/58b2b1bf4547dc6a389fd0d9321d5f125e39539b/crates/papyrus_gateway/src/api/v0_3_0.rs#L140)):*
> ```XML
> 
> #[async_trait]
> impl JsonRpcV0_3_0Server for JsonRpcServerV0_3_0Impl {
> ```

I suggest having a module for each version and separating this impl. to a different file.
Also, seems is duplicated between lib and here.
___
*[`crates/papyrus_gateway/src/api/v0_3_0.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9L-XrAIXQjEaiNUsa:-NV9L-XrAIXQjEaiNUsb:b-ndwizn) ([raw file](https://github.com/starkware-libs/papyrus/blob/f43189b24e92243b5721a27656fe103f3cbb9d13/crates/papyrus_gateway/src/api/v0_3_0.rs#L31)):*
> ```XML
>     internal_server_error, ContinuationTokenAsStruct,
> };
> #[versioned_rpc("V0_3_0")]
> ```

Can we use a const here?
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 2 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9JaxWBhLQEqpnl5pl:-NV9JaxWBhLQEqpnl5pm:bsi9of4) ([raw file](https://github.com/starkware-libs/papyrus/blob/00bcf0fab8a5d37d9ffc0cdb583c2597ba0cb666/crates/papyrus_gateway/src/api/version_config.rs#L2)):*
> ```XML
> #[derive(Eq, PartialEq, Hash)]
> #[allow(dead_code)] // TODO: nevo - remove this once other versions are implemented - hides "Supported" and "Deprecated" not constructed error
> ```

Consider moving the the specific variants.
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9JiZF8SinMnjPKUVC:-NV9JiZF8SinMnjPKUVD:b-dfn5vm) ([raw file](https://github.com/starkware-libs/papyrus/blob/00bcf0fab8a5d37d9ffc0cdb583c2597ba0cb666/crates/papyrus_gateway/src/api/version_config.rs#L3)):*
> ```XML
> #[derive(Eq, PartialEq, Hash)]
> #[allow(dead_code)] // TODO: nevo - remove this once other versions are implemented - hides "Supported" and "Deprecated" not constructed error
> pub enum VersionState {
> ```

Please document. 
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9LFqUBhMi3rdH_cFo:-NV9LFqUBhMi3rdH_cFp:b18b7bp) ([raw file](https://github.com/starkware-libs/papyrus/blob/f43189b24e92243b5721a27656fe103f3cbb9d13/crates/papyrus_proc_macros/src/lib.rs#L5)):*
> ```XML
> use syn::{parse_macro_input, ItemTrait, LitStr, Meta, TraitItem};
> 
> #[proc_macro_attribute]
> ```

Please add documentation.
I think an example of input, output would be nice. 
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9LxRiDvyQCyJoJLZL:-NV9LxRiDvyQCyJoJLZM:b-55lfdc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f43189b24e92243b5721a27656fe103f3cbb9d13/crates/papyrus_proc_macros/src/lib.rs#L57)):*
> ```XML
>     // generate the versioned trait with the new method signatures
>     let versioned_trait = syn::ItemTrait {
>         attrs: vec![syn::parse_quote!(#[rpc(server, client, namespace = "starknet")])],
> ```

Can we move this to a const?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/661)* status: 1 of 25 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/api/v0_3_0.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NV9-nsn9QhlTGlbGNny:-NVYCdc9DaFM-nZ8nSa8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/58b2b1bf4547dc6a389fd0d9321d5f125e39539b/crates/papyrus_gateway/src/api/v0_3_0.rs#L140)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I suggest having a module for each version and separating this impl. to a different file.
Also, seems is duplicated between lib and here.
</blockquote></details>

Done.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 10 of 16 files at r14, 1 of 2 files at r18, 2 of 6 files at r19, 1 of 3 files at r20, 1 of 2 files at r21, 2 of 6 files at r22, 1 of 2 files at r23, 4 of 5 files at r25, 1 of 1 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/661)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 6 at r27](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NViJOR1CyEnKPR0etLu:-NViJOR1CyEnKPR0etLv:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d7c45062d34b833b97f3b03e831d2ec16cda9c6/crates/papyrus_gateway/src/api/version_config.rs#L6)):*
> ```XML
> /// can be multiple versions that are deprecated. Latest -> method exposed via the http path "/" and "" (e.g. http://host:port/)
> /// Supported -> method exposed via the http path "/version_id" (e.g. http://host:port/V0_3_0)
> /// Deprecated -> method not exposed.
> ```





_Suggestion:_
```XML
/// Labels the jsonRPC versions we have such that one and only one version is Latest,
/// there can be multiple versions that are supported (latest is implicitly supported), and there
/// can be multiple versions that are deprecated.
/// - Latest -> corresponding methods are exposed via the http path "/" and "" (e.g. http://host:port/)
/// - Supported -> corresponding methods are exposed via the http path "/version_id" (e.g. http://host:port/V0_3_0)
/// - Deprecated -> corresponding methods are not exposed.
```
___
*[`crates/papyrus_proc_macros/Cargo.toml` line 6 at r27](https://reviewable.io/reviews/starkware-libs/papyrus/661#-NViYMsh7NubLk1Q8VD8:-NViYMsh7NubLk1Q8VD9:ba3dfna) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d7c45062d34b833b97f3b03e831d2ec16cda9c6/crates/papyrus_proc_macros/Cargo.toml#L6)):*
> ```TOML
> edition = "2021"
> 
> # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> ```

Remove?

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 14 files at r28, 1 of 2 files at r29, 1 of 6 files at r30, 1 of 3 files at r31, 1 of 2 files at r32, 2 of 6 files at r33, 1 of 2 files at r34, 4 of 6 files at r36, 2 of 2 files at r39, 1 of 2 files at r40, 9 of 10 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/661)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request closed without merging**
