### PR TITLE
feat(monitoring): add is_ready function to the monitoring gateway

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-Ni9G5ZI6A2gLe8ZMfPl:-Ni9G5ZJE82CYP9U4upA:brnchgb) ([raw file](https://github.com/starkware-libs/papyrus/blob/d1137e906775aea9d56529186bd5be5aea415227/crates/papyrus_monitoring_gateway/src/lib.rs#L209)):*
> ```XML
> #[instrument(level = "debug", ret)]
> async fn is_ready(version: &'static str, central_config: CentralSourceConfig) -> String {
>     let urls = central_config.url.clone();
> ```

url
or
starknet_url



_Code quote:_
```XML
urls
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-Ni9G5ZI6A2gLe8ZMfPl:-Ni9c35m75Feh5fDxK6Y:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d1137e906775aea9d56529186bd5be5aea415227/crates/papyrus_monitoring_gateway/src/lib.rs#L209)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

url
or
starknet_url
</blockquote></details>

Done.

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by OmriEshhar1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by yair-starkware** [comment]
I think we can remove the dependency on the central by adding the common config params to the MGW config and adding pointers to the default config.

See how we handled the same issue with ChainId config which is common to the storage and the RPC

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 9 unresolved discussions (waiting on @OriStarkware and @yair-starkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbRqV1lCwaKz4s0C0:-NiZbRqV1lCwaKz4s0C1:b-ox4wzm) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L107)):*
> ```XML
>     pub fn new(
>         config: MonitoringGatewayConfig,
>         central_config: CentralSourceConfig,
> ```

Please use only the url as part of `MonitoringGatewayConfig` 



_Code quote:_
```XML
 central_config: CentralSourceConfig,
```
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZImZZ9jfOxlNfoY-3:-NiZImZ_-22H5bQdcvRx:b-sjki02) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L202)):*
> ```XML
>         )
>         .route(
>             format!("/{MONITORING_PREFIX}/ready").as_str(),
> ```

Missing a test.



_Code quote:_
```XML
 format!("/{MONITORING_PREFIX}/ready").as_str(),
```
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbegS54_knAJ0sl6i:-NiZbegS54_knAJ0sl6j:b-sf7n9g) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L214)):*
> ```XML
>         central_config.http_headers,
>         version,
>         central_config.retry_config,
> ```

This really need to be configurable?



_Code quote:_
```XML
central_config.retry_config
```
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 221 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZK8OuAhhuTw6fL8p-:-NiZK8Ov-ijE-yxqOein:b8uyupl) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L221)):*
> ```XML
> 
>     let starknet_client =
>         StarknetGatewayClient::new(&starknet_url, version, central_config.retry_config)
> ```

Note that currently write and read endpoints have different urls.
Can you please use a shared pointer in a prequel PR?



_Code quote:_
```XML
StarknetGatewayClient::new(&starknet_url, version, central_config.retry_config)
```
___
*[`crates/starknet_client/src/reader/mod.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbmDa-ETLZKKtUqUd:-NiZbmDa-ETLZKKtUqUe:b-sjki02) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/reader/mod.rs#L188)):*
> ```XML
>     }
> 
>     pub async fn is_alive(&self) -> bool {
> ```

Missing a test.



_Code quote:_
```XML
 pub async fn is_alive(&self) -> bool {
```
___
*[`crates/starknet_client/src/reader/mod.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbnhU8aHJBzSi-LYY:-NiZbnhU8aHJBzSi-LYZ:bppsttd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/reader/mod.rs#L191)):*
> ```XML
>         let url = self.urls.feeder_gateway_is_alive.clone();
>         let response = self.request_with_retry_url(url).await;
>         let _expected = FEEDER_GATEWAY_ALIVE_RESPONSE.to_string();
> ```

Why `_` prefix?



_Suggestion:_
```XML
expected_response
```
___
*[`crates/starknet_client/src/writer/mod.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZc-X23tm_cDl2rzws:-NiZc-X23tm_cDl2rzwt:b-sjki02) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/writer/mod.rs#L141)):*
> ```XML
>     }
> 
>     pub async fn is_alive(&self) -> bool {
> ```

Missing a test.



_Code quote:_
```XML
 pub async fn is_alive(&self) -> bool {
```
___
*[`crates/starknet_client/src/writer/mod.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZc1TQB722S8spIe3R:-NiZc1TQB722S8spIe3S:bppsttd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/writer/mod.rs#L144)):*
> ```XML
>         let url = self.is_alive_url.clone();
>         let response = self.client.request_with_retry(self.client.internal_client.get(url)).await;
>         let _expected = GATEWAY_ALIVE_RESPONSE.to_string();
> ```

Why `_` prefix?



_Suggestion:_
```XML
expected_response
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @OmriEshhar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiTvnGS9g9X9IBLnTa9:-Nij206p4UzI4tHTg45B:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we can remove the dependency on the central by adding the common config params to the MGW config and adding pointers to the default config.

See how we handled the same issue with ChainId config which is common to the storage and the RPC
</blockquote></details>

Done.

___
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbRqV1lCwaKz4s0C0:-Nij21oqDTtVKqfXv6He:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L107)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use only the url as part of `MonitoringGatewayConfig`
</blockquote></details>

Done.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZImZZ9jfOxlNfoY-3:-NijJYdD44nL4J-ydw82:b-jaar7c) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L202)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Missing a test.
</blockquote></details>

I will add a test for is_ready in a different PR.
___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 221 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZK8OuAhhuTw6fL8p-:-Nij23w71MKYJ1nLE_t5:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/papyrus_monitoring_gateway/src/lib.rs#L221)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Note that currently write and read endpoints have different urls.
Can you please use a shared pointer in a prequel PR?
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/reader/mod.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZbmDa-ETLZKKtUqUd:-NijJvo68WeJsKEjJ4lv:b-jaar7c) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/reader/mod.rs#L188)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Missing a test.
</blockquote></details>

I will add a test for is_ready in a different PR.
___
*[`crates/starknet_client/src/writer/mod.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NiZc-X23tm_cDl2rzws:-NijJwR83DYJW3Rcb17v:b-jaar7c) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce375a373b3a2bf8b962c32856a34adff39a2ef6/crates/starknet_client/src/writer/mod.rs#L141)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Missing a test.
</blockquote></details>

I will add a test for is_ready in a different PR.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @OmriEshhar1, and @yair-starkware)

___
*[`crates/papyrus_monitoring_gateway/src/lib.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-NijVV967489JnDp3Lqg:-NijcM0VC6CX4RaQUGhc:b-y4z7i3) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d7b019890c214bd315e7fbdc846a93a80c1ce8c/crates/papyrus_monitoring_gateway/src/lib.rs#L57)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Should there be a hardcoded URL value here? 
Shouldn't it be a secret? And why is it here in non-test code?
</blockquote></details>

After discussing f2f we decided to keep it this way.
It is not a secret as it appears in the config and preset files.
The other parameters are specific as well so we decided to use a hardcoded url as well.

**Review by OmriEshhar1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-:-Nj7jCExBO0_CpqjbQAJ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @OriStarkware)

___
*[`config/default_config.json` line 96 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-Nj7kv3VCEhETLHeFzfg:-Nj7kv3VCEhETLHeFzfh:b-c88n1i) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d7b019890c214bd315e7fbdc846a93a80c1ce8c/config/default_config.json#L96)):*
> ```JSON
>     "pointer_target": "starknet_url",
>     "privacy": "Public"
>   },
> ```

It needs to be dumped automatically, not updated manually



_Code quote:_
```JSON
  "monitoring_gateway.starknet_url": {
    "description": "URL for the Starknet gateway and the Starknet feeder gateway.",
    "pointer_target": "starknet_url",
    "privacy": "Public"
  },
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`config/default_config.json` line 96 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1308#-Nj7kv3VCEhETLHeFzfg:-Nj7wVq22A6Wle5tM7JL:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9d7b019890c214bd315e7fbdc846a93a80c1ce8c/config/default_config.json#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It needs to be dumped automatically, not updated manually
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
> Reviewed 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 6 of 16 files at r6, 1 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
