### PR TITLE
Support optional config params.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?

- Supports optional params and sub-configs.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`config/default_config.json` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf2rJ-EstAg_5_RltK:-Naf2rJ-EstAg_5_RltL:bih9l1s) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/config/default_config.json#L78)):*
> ```JSON
>     "value": "./data"
>   },
>   "sync.#is_none": {
> ```

In a separate PR, please add to the README an explanation of the default config file from the perspective of someone who wants to configure the node.
There is a readme both for the workspace and for the crate, IMO this should be in the workspace readme.
___
*[`crates/papyrus_config/src/config_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf6L4IEg-2UkB0vbmN:-Naf6L4IEg-2UkB0vbmO:b66s0hi) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/config_test.rs#L65)):*
> ```XML
>     for outer_config in [some_outer_config, none_outer_config] {
>         let mut dumped = outer_config.dump();
>         update_optional_values(&mut dumped);
> ```

Isn't it called from the load?



_Code quote:_
```XML
update_optional_values(&mut dumped);
```
___
*[`crates/papyrus_config/src/dumping.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf4UjY4dpzZg7mK8Cd:-Naf4E3b-mcpjC9zSqRA:b-lwvzia) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L19)):*
> ```XML
> //! ```
> //!
> //! //! Supports flags for optional params and sub-configs:
> ```

Add something like: 
`The #is_none param indicates whether the param is none or not by default, and the param itself contains the default value in case the parameter is not none.`
___
*[`crates/papyrus_config/src/dumping.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf1Oe79YBDjD7chu22:-Naf1Oe79YBDjD7chu23:b48s7cs) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L88)):*
> ```XML
> }
> 
> /// Serializes optional sub config.
> ```

Explain what is going to be the result.
___
*[`crates/papyrus_config/src/dumping.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf5b3uDeHraHHohXT1:-Naf5b3uDeHraHHohXT2:b4d4hcu) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L129)):*
> ```XML
> pub fn ser_is_param_none(name: &str, is_none: bool) -> (String, SerializedParam) {
>     (
>         format!("{name}{IS_NONE_MARK}"),
> ```

Add the dot here instead of in the const
___
*[`crates/papyrus_config/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf5jHi8XFYgkuQfq7S:-Naf5jHi8XFYgkuQfq7T:b2omj0j) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/lib.rs#L46)):*
> ```XML
> use serde_json::Value;
> 
> pub(crate) const IS_NONE_MARK: &str = ".#is_none";
> ```

remove the dot
___
*[`crates/papyrus_config/src/loading.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-NaLJTCACH4JbwC59mtA:-NaLIrEd4CkLiPKdzcCp:bs7qlik) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/loading.rs#L27)):*
> ```XML
> ) -> Result<T, ConfigError> {
>     let mut nested_map = json!({});
>     // Iterates in reverse order, to give higher priority to higher entries in the nested map.
> ```

Why is it necessary?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf6L4IEg-2UkB0vbmN:-Naf81CiEsDutwvtZ8nu:b4l5cye) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/config_test.rs#L65)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't it called from the load?
</blockquote></details>

It's called from `load_and_process_config`
___
*[`crates/papyrus_config/src/dumping.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf4UjY4dpzZg7mK8Cd:-NafLX3CCL08yMt0LMpR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L19)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add something like: 
`The #is_none param indicates whether the param is none or not by default, and the param itself contains the default value in case the parameter is not none.`
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf1Oe79YBDjD7chu22:-NafMVcQ46l9dUVHuh4-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L88)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Explain what is going to be the result.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf5b3uDeHraHHohXT1:-NafN8eJ9kWIR29t28O_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/dumping.rs#L129)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add the dot here instead of in the const
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf5jHi8XFYgkuQfq7S:-NafNBGOACVkYjFfhAah:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/lib.rs#L46)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

remove the dot
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/loading.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-NaLJTCACH4JbwC59mtA:-Naf7Afv6msqsyr8vYBD:b-buabmw) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/crates/papyrus_config/src/loading.rs#L27)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it necessary?
</blockquote></details>

For not-none optional sub-configs, we don't remove the internal params.

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`config/default_config.json` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/908#-Naf2rJ-EstAg_5_RltK:-Nau2Jcg5aL0v9mymXfv:b-ghmsye) ([raw file](https://github.com/starkware-libs/papyrus/blob/622c5a6efda3103643653fef3165cd0c83595c23/config/default_config.json#L78)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In a separate PR, please add to the README an explanation of the default config file from the perspective of someone who wants to configure the node.
There is a readme both for the workspace and for the crate, IMO this should be in the workspace readme.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/papyrus/965

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/908#-:-Nb8gRpq66epXc-DJMch:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
