### PR TITLE
fix(network): map event function returns option instead of passing the boolean variable arround

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1602)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1590** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1588** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1600** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1601** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1602** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment).

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1590** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1588** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1600** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1601** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1602** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1602?utm_source=stack-comment).

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1602)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1602#-Nnt2B0w-v_6djyX6osB:-Nnt2B0w-v_6djyX6osC:b-e1xd5e) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4fe8c17c17aac0d968035824402fab54cad31e7/crates/papyrus_network/src/block_headers/behaviour.rs#L396)):*
> ```XML
>                     } else {
>                         ignore_event_and_return_pending = true;
>                         Event::SessionFailed {
> ```

Add comment saying that because of map_out you have to return an event so you're returning a dummy event and marking that it shouldn't be used.
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1602#-Nnt2PToEeQTHclz9TIw:-Nnt2PToEeQTHclz9TIx:bceukm8) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4fe8c17c17aac0d968035824402fab54cad31e7/crates/papyrus_network/src/block_headers/behaviour_test.rs#L121)):*
> ```XML
>     assert_matches!(
>         res_event,
>         None /* Some(Event::SessionFailed {session_id, session_error}) => {
> ```

Erase comment

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1602#-:-No6dZxQ4zlwsksxBoI7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
