### PR TITLE
test(starknet_client): add more tests for StarknetFeederGatewayClient

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-NbtYhyoEt3_w8RIvGJS:-NbtYhyoEt3_w8RIvGJT:b-t1g4ms) (no related file):*
1. I don’t sure we want to test any error; it will make the tests longer and the code harder to maintain. Ask Dan about that.
2. There is a reason for the weird number? Why not always use 100 as a block number, for example?

___
___
*[`crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-NbtXWjrBtTCe0cmXWU2:-NbtXWjrBtTCe0cmXWU3:btoa0l0) ([raw file](https://github.com/starkware-libs/papyrus/blob/d306e0259932d9fcaa1adef9ed4cd8b9e4d1011f/crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs#L134)):*
> ```XML
>     let body = r#"{"code": "StarknetErrorCode.BLOCK_NOT_FOUND", "message": "Block number -1 was not found."}"#;
>     let mock_no_block =
>         mock("GET", &format!("/feeder_gateway/get_state_update?{BLOCK_NUMBER_QUERY}=999999")[..])
> ```

Consider format!("/feeder_gateway/get_state_update?{BLOCK_NUMBER_QUERY}=999999").as_str() 
instead of the weird syntax. Or even use concat! or any other macro for string literals.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-NbtYhyoEt3_w8RIvGJS:-Nbx1Dx_Ccku1eHPM_5o:b-f5kmmo) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. I don’t sure we want to test any error; it will make the tests longer and the code harder to maintain. Ask Dan about that.
2. There is a reason for the weird number? Why not always use 100 as a block number, for example?
</blockquote></details>

1. We already have such tests in the base client and for get_block. Why is it problematic now?
2. I saw that's what we have in the tests here so I did the same. In general the tests here have a lot of code duplication and they unite multiple tests into one test. We should refactor this file but I don't think we have the time for this. @dan-starkware WDYT?

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-NbtXWjrBtTCe0cmXWU2:-Nbx2AzhBkqxDtX1JzKF:b-irvxzn) ([raw file](https://github.com/starkware-libs/papyrus/blob/d306e0259932d9fcaa1adef9ed4cd8b9e4d1011f/crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs#L134)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider format!("/feeder_gateway/get_state_update?{BLOCK_NUMBER_QUERY}=999999").as_str() 
instead of the weird syntax. Or even use concat! or any other macro for string literals.
</blockquote></details>

As I wrote before. I just did what we do in other tests. If you and @dan-starkware want I can on top of this PR fix the code quality of this file

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

1. We already have such tests in the base client and for get_block. Why is it problematic now?
2. I saw that's what we have in the tests here so I did the same. In general the tests here have a lot of code duplication and they unite multiple tests into one test. We should refactor this file but I don't think we have the time for this. @dan-starkware WDYT?
</blockquote></details>

IMO there's no need to spend time on code quality here, only coverage and CI time.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-NbtYhyoEt3_w8RIvGJS:-NcW62N_3lCM6HnP8C3z:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO there's no need to spend time on code quality here, only coverage and CI time.
</blockquote></details>

Done.

___

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1055#-:-NcW6V2UDueiAmKiYAbl:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

**Pull request merged**
