### PR TITLE
feat(JSON-RPC)!: add StarknetWriter as a member of JsonRpcServerV0_4Impl

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbAH8BB8hGelBcoYlxi:-NbAH8BB8hGelBcoYlxj:b-y3bcj) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6dbe6f919e7a08c82b4841b202ed7d7ead46bf3/crates/papyrus_gateway/src/lib.rs#L99)):*
> ```XML
>             ),
>         ]);
>         chain!(
> ```

Can we use append instead?



_Code quote:_
```XML
chain!(
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbB3VJB7emH9ZjFoFBh:-NbB3VJB7emH9ZjFoFBi:bwq23gr) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ce2890f4b68c31e692b38205de46f9c6f77032b/crates/papyrus_gateway/src/lib.rs#L73)):*
> ```XML
>             collect_metrics: false,
>             starknet_url: String::from("https://alpha-mainnet.starknet.io/"),
>             starknet_gateway_http_headers: None,
> ```

Why do we need this config?



_Code quote:_
```XML
starknet_gateway_http_headers: None,
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbB3VJB7emH9ZjFoFBh:-NbDPXc312aBqC9Xz-w8:b-nkkok5) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ce2890f4b68c31e692b38205de46f9c6f77032b/crates/papyrus_gateway/src/lib.rs#L73)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need this config?
</blockquote></details>

You're right. Removed from config for now. I'll remove http_headers from the client's constructor in a future PR

**Review by nagmo-starkware — COMMENTED** [review]
please note the coverage. see if you can improve it

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984#-:-NbDUfrlBRF6ZGp_MeP0:b-mms30s)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`config/default_config.json` line 58 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDVCQ889CjWFKGuJxN:-NbDVCQ98C9L-cPjs1Mk:b-z953x) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/config/default_config.json#L58)):*
> ```JSON
>     "value": 100
>   },
>   "gateway.starknet_gateway_retry_config.max_retries": {
> ```

is these config changes a part of this PR?
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 458 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDWE2JBRzdCoO6YwXC:-NbDWE2JBRzdCoO6YwXD:b-btltvu) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L458)):*
> ```XML
>         shared_syncing_state: Arc<RwLock<SyncingState>>,
>         // TODO(shahak): Put this parameter inside Self once write_api is supported in v0.3.0
>         _: Arc<dyn StarknetWriter>,
> ```

consider moving it out of the trait of having a different function to set it with a default implementation (that doesn't use the writer).

**Review by ShahakShama — COMMENTED** [review]
Future PRs will improve it

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984#-:-NbDc95E641M4sEzQpsP:bj1jrlm)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`config/default_config.json` line 58 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDVCQ889CjWFKGuJxN:-NbDcEBPBcLKvoujCVAH:b2nhswy) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/config/default_config.json#L58)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

is these config changes a part of this PR?
</blockquote></details>

Yes
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 458 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDWE2JBRzdCoO6YwXC:-NbDcKNh0kGR9If7qfmd:b-u4tbkl) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L458)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

consider moving it out of the trait of having a different function to set it with a default implementation (that doesn't use the writer).
</blockquote></details>

It should be part of the trait. We're not sure if we want to support write_api in v0.3.0, but write_api is in v0.3.0

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/lib.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDx2hQAUMj0_jcURnB:-NbDx2hR1KRemyO_pT6w:b-wt9f4t) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/crates/papyrus_gateway/src/lib.rs#L92)):*
> ```XML
>             self.starknet_gateway_retry_config.dump(),
>             "starknet_gateway_retry_config",
>         ));
> ```

Edit the description of the sub-config



_Code quote:_
```XML
        self_params_dump.append(&mut append_sub_config_name(
            self.starknet_gateway_retry_config.dump(),
            "starknet_gateway_retry_config",
        ));
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbDx2hQAUMj0_jcURnB:-NbE0xGMCows9ScjtLEx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/279a3aa7e2caa046e0da29f7ed60eb5bf7d4ce26/crates/papyrus_gateway/src/lib.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Edit the description of the sub-config
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/api.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbEA6LABSswWish8GHx:-NbEA6LABSswWish8GHy:b-os84an) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b845cd589fa6f0f2fbf8c0e3829d9fbce4bf0a2/crates/papyrus_gateway/src/api.rs#L100)):*
> ```XML
>     max_events_keys: usize,
>     shared_syncing_state: Arc<RwLock<SyncingState>>,
>     starknet_writer: Arc<dyn StarknetWriter>,
> ```

Add todo generic

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/api.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/984#-NbEA6LABSswWish8GHx:-NbEAWyIDSHQBhbgK8Q3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b845cd589fa6f0f2fbf8c0e3829d9fbce4bf0a2/crates/papyrus_gateway/src/api.rs#L100)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add todo generic
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/984#-:-NbEBQyyCnAvGdqtgu4k:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
