### PR TITLE
feat(JSON-RPC): get_class_hash_at supports pending with up-to-date check

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1350)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1350)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 583 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1350#-NiAPNW03iYhYC3dOu2i:-NiAPNW1EehQRizRZ4xD:bayu5gb) ([raw file](https://github.com/starkware-libs/papyrus/blob/e8b586d84171f647720c7edfd4e7e44ae01fef3b/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L583)):*
> ```XML
>                 }
>             }
>             BlockId::Tag(Tag::Latest)
> ```

IIUC you're trying to get the response from the pending block, and if it's not there you're trying to get it from the latest block instead.
Why is this the behavior? Shouldn't you just look at the pending block?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1350)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @OmriEshhar1, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 583 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1350#-NiAPNW03iYhYC3dOu2i:-NiDNBF37KAagNBzsrr-:b-ur7i07) ([raw file](https://github.com/starkware-libs/papyrus/blob/e8b586d84171f647720c7edfd4e7e44ae01fef3b/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L583)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

IIUC you're trying to get the response from the pending block, and if it's not there you're trying to get it from the latest block instead.
Why is this the behavior? Shouldn't you just look at the pending block?
</blockquote></details>

block_id means here to look at all the contracts that are considered deployed in this block. This can mean that either the contract was deployed in this block or in a previous block

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1350#-:-NiDtFie6vAk2FQtjmcV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
