### PR TITLE
feat(execution): implement StateReader trait for execution using t…

### PR DESCRIPTION
**Pull request by yair-starkware**
…he blockifier

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: all files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaefGSi3bkSh6QPe2Rp:-NaefGSi3bkSh6QPe2Rq:b-t5frpy) (no related file):*
Please add documentation

___
___
*[`crates/papyrus_execution/Cargo.toml` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaedMrb-VQR8fmR9FcP:-NaedMrc-LKqrrhqgsc-:b-vra0ku) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L4)):*
> ```TOML
> name = "papyrus_execution"
> version = "0.1.0"
> edition = "2021"
> ```

Please take from workspace and add a description.



_Code quote:_
```TOML
version = "0.1.0"
edition = "2021"
```
___
*[`crates/papyrus_execution/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naek9na2QU_wUEra4nS:-Naek9na2QU_wUEra4nT:b1rcmma) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L10)):*
> ```TOML
> cairo-lang-starknet.workspace = true
> cairo-vm.workspace = true
> lazy_static.workspace = true
> ```

Is this used somewhere? 



_Code quote:_
```TOML
lazy_static.workspace = true
```
___
*[`crates/papyrus_execution/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaekJByEj8U9NuFBd4H:-NaekJBz4aA4tNIhXjsn:b-aptard) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L13)):*
> ```TOML
> papyrus_storage = { path = "../papyrus_storage"}
> serde = { workspace = true, features = ["derive"] }
> serde_json = { workspace = true, features = ["arbitrary_precision"]}
> ```

IMO we should add tests to make sure each feature is indeed imported.



_Code quote:_
```TOML
features = ["arbitrary_precision"]
```
___
*[`crates/papyrus_execution/src/state_reader.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naeit6w1vrXIHIlVkyQ:-Naeit6w1vrXIHIlVkyR:b-1nmzdj) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L23)):*
> ```XML
>         &mut self,
>         contract_address: ContractAddress,
>         key: StorageKey,
> ```

By reference? (apply to all methods)



_Code quote:_
```XML
        contract_address: ContractAddress,
        key: StorageKey,
```
___
*[`crates/papyrus_execution/src/state_reader.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naej7ZP0K9WpcueSsRB:-Naej7ZP0K9WpcueSsRC:biklydb) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L32)):*
> ```XML
>     }
> 
>     // Returns the default value if the contract address is not found.
> ```

Please be consistent with comments (some methods have, other not).
In this case IMO comments are redundant.



_Code quote:_
```XML
// Returns the default value if the contract address is not found.
```
___
*[`crates/papyrus_execution/src/state_reader.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaegoSeE-rgUdDXYK85:-NaegoSeE-rgUdDXYK86:b41ew0f) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L40)):*
> ```XML
>             .get_nonce_at(self.state_number, &contract_address)
>             .map_err(storage_err_to_state_err)?
>             .unwrap_or_default())
> ```

Did we decide on this behavior?
Can you please discuss this in full-node-sequencer?



_Code quote:_
```XML
.unwrap_or_default())
```
___
*[`crates/papyrus_execution/src/state_reader.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaejWHS3HmL4N5s3h4W:-NaejWHS3HmL4N5s3h4X:b-zhz1zv) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L66)):*
> ```XML
>     }
> 
>     fn get_compiled_class_hash(&mut self, class_hash: ClassHash) -> StateResult<CompiledClassHash> {
> ```

I think we don't need this (is it implemented in the Native Blockifier?)
If so, please PR removal of this with @elintul as reviewer)



_Code quote:_
```XML
 fn get_compiled_class_hash(&mut self, class_hash: ClassHash) -> StateResult<CompiledClassHash> {
```
___
*[`crates/papyrus_execution/src/state_reader_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naem0TnAATnhJwM7sx7:-Naem0TnAATnhJwM7sx8:beh567s) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader_test.rs#L116)):*
> ```XML
>         .commit()
>         .unwrap();
> ```

Should we also check with non-default values?
Missing test-cases, right?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: 5 of 10 files reviewed, 9 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaefGSi3bkSh6QPe2Rp:-NafRlro4NGGoRz3Yn3U:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add documentation
</blockquote></details>

Done.

___
___
*[`crates/papyrus_execution/Cargo.toml` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaedMrb-VQR8fmR9FcP:-NafSFaeBXBX832QQ07u:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please take from workspace and add a description.
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naek9na2QU_wUEra4nS:-NafSoGlEtXaZYkWzPqQ:b-m036mz) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L10)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this used somewhere? 
</blockquote></details>

Removed (udeps didn't detect this)
It will be added again in following PRs.
___
*[`crates/papyrus_execution/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaekJByEj8U9NuFBd4H:-NafTiOl9V8C4M0tVm5F:b5l0ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO we should add tests to make sure each feature is indeed imported.
</blockquote></details>

Isn't Yael working on that?
___
*[`crates/papyrus_execution/src/execution_utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NagTKsj4a-WBN9hKHh5:-NagTKskBVw78UcjA1It:bw225nk) ([raw file](https://github.com/starkware-libs/papyrus/blob/a17b03e60fbe2d40d26174ba48cdf8dcdf2e170b/crates/papyrus_execution/src/execution_utils.rs#L29)):*
> ```XML
>     state_number: StateNumber,
> ) -> Result<Option<BlockifierContractClass>, ExecutionUtilsError> {
>     match txn.get_state_reader()?.get_class_definition_block_number(class_hash)? {
> ```

Fixed a bug - this function would return the casm even if the class was declared after the given state number
___
*[`crates/papyrus_execution/src/state_reader.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naej7ZP0K9WpcueSsRB:-NafUm8x9yZjkckWYZFf:b-hkzpw4) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L32)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please be consistent with comments (some methods have, other not).
In this case IMO comments are redundant.
</blockquote></details>

Currently, the storage values are defined to be 0 in uninitialized keys, while nonces and class hashes are not - this is why only some of the functions have this comment.
If we decide that nonces and class hashes should behave similarly, I will change the functions in the storage crate and remove the comments.
___
*[`crates/papyrus_execution/src/state_reader_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naem0TnAATnhJwM7sx7:-NagTvSu1-KeL1FoXZyd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader_test.rs#L116)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Should we also check with non-default values?
Missing test-cases, right?
</blockquote></details>

Done.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: 5 of 10 files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @elintul)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-Naeit6w1vrXIHIlVkyQ:-NakUHyF8GSnuorIIs2E:b-4t8mh1) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L23)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

By reference? (apply to all methods)
</blockquote></details>

Maybe in the future if we decide to change the trait
___
*[`crates/papyrus_execution/src/state_reader.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaejWHS3HmL4N5s3h4W:-NakUW7wEwA7bSFag5-g:b1xzr2p) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I think we don't need this (is it implemented in the Native Blockifier?)
If so, please PR removal of this with @elintul as reviewer)
</blockquote></details>

Elin said it will be needed

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: 5 of 10 files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @elintul)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaegoSeE-rgUdDXYK85:-NakX8G42rJQgxUm57oD:b-ghmi76) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/src/state_reader.rs#L40)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Did we decide on this behavior?
Can you please discuss this in full-node-sequencer?


</blockquote></details>

I started a discussion, wasn't resolved.

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware, @elintul, and @yair-starkware)

___
*[`crates/papyrus_execution/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaekJByEj8U9NuFBd4H:-Nap4pdQEZc9UXEsHyPZ:b-60ty49) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't Yael working on that?
</blockquote></details>

Yes, but I think it's better that she fix old code, not new code.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @elintul)

___
*[`crates/papyrus_execution/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/938#-NaekJByEj8U9NuFBd4H:-NapYXzy5VL-Ttis5n_r:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/79188f6182b46264ec62934c8d4b80484f11c5f5/crates/papyrus_execution/Cargo.toml#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Yes, but I think it's better that she fix old code, not new code.
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/938)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @elintul)

**Pull request merged**
