### PR TITLE
fix(JSON-RPC): set use_kzg_da correctly

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 8 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-Nsbef3o6lXSyGx5d6XQ:b-o2k4sf) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
> ```XML
>         charge_fee,
>         validate,
>         true,
> ```

Why is this hard-coded?



_Code quote:_
```XML
true,
```
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 854 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbcjrd7y6J9SoICI-f:-Nsbcjre6KgFu4M9yLl-:b7csom6) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L854)):*
> ```XML
>                 request.calldata,
>                 &block_execution_config,
>                 true,
> ```

Consider making a constant `IGNORE_L1_DA_MODE`



_Code quote:_
```XML
true,
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-NsbklqC1xvUaTnU3uFm:besfw7f) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is this hard-coded?
</blockquote></details>

Because we don't have tests that put false here yet

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-Nsc8a9m6ibPGIGGYEeX:b-21vbfb) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Because we don't have tests that put false here yet
</blockquote></details>

Are you adding such tests or is it a todo?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-NscA2nKAWL35dHlIuHw:b-13145d) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Are you adding such tests or is it a todo?
</blockquote></details>

The RPC already tests this, so I'm not sure we need to. WDYT?
Anyway, if we need to it will be a TODO

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-NscBpM28gxoeKtN_hjq:b1mzszb) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The RPC already tests this, so I'm not sure we need to. WDYT?
Anyway, if we need to it will be a TODO
</blockquote></details>

Maybe add a todo to think if we need such tests.
We will decide in the todo marathon

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/test_utils.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-Nsbef3nAwSrK4_ONFI5:-NscCKNB7-qv9JSS_K7c:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/32aedaf380665d7316cee58bf6b876b441965e95/crates/papyrus_execution/src/test_utils.rs#L206)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Maybe add a todo to think if we need such tests.
We will decide in the todo marathon
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1784#-:-NscCUU4AsuxPi9RHJEX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
