### PR TITLE
feat(execution): call entry point

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/940)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Please add TODOs also to Monday

**Comment by dan-starkware** [comment]
*[`crates/papyrus_execution/src/execution_test.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/940#-NafNEhBCXb070S7t5Eq:-NafNEhBCXb070S7t5Er:bk2yf03) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f53f3a5207bac64ff2baaea81bc08a34f6cd3f/crates/papyrus_execution/src/execution_test.rs#L103)):*
> ```XML
> 
> #[test]
> fn execute_call_cairo0() {
> ```

Please add a short explanation what each execute do

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/940)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/940#-NafAELiBQXx0_jlX2ao:-NafAELiBQXx0_jlX2ap:bc6odc1) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f53f3a5207bac64ff2baaea81bc08a34f6cd3f/crates/papyrus_execution/src/lib.rs#L110)):*
> ```XML
>     let mut cached_state = CachedState::new(ExecutionStateReader {
>         txn,
>         state_number: StateNumber::right_before_block(state_number.0),
> ```

This is very confusing. 



_Code quote:_
```XML
:right_before_block(state_number.0)
```

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add TODOs also to Monday
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/940)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
