### PR TITLE
feat(consensus): add sequencing crates to some CI flows

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2134)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2134?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2134** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2134?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2131?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2126** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2125** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2125?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2134)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_block_builder/src/lib.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2134#-O0IiXkU3qp4Iqh6YID8:-O0IiXkU3qp4Iqh6YID9:be2j79d) ([raw file](https://github.com/starkware-libs/papyrus/blob/cc184bbfc8cf9a63fedbce480a20a3b108114fdb/crates/sequencing/papyrus_block_builder/src/lib.rs#L55)):*
> ```XML
>             .expect("Failed to read storage")
>             .get_block_transactions(block_number)
>             .expect("Block missing in storage");
> ```

1. Is it guaranteed that the `block_number` is in storage. If so please add this to the documentation. 
2. Try and phrase these messages with `should`. From [option documentation](https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style)



_Code quote:_
```XML
.expect("Block missing in storage");
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2134#-O0Ii6chBcryE-ZzXlvC:-O0Ii6chBcryE-ZzXlvD:bot1uny) ([raw file](https://github.com/starkware-libs/papyrus/blob/aff6ab115c5fe1d40bea21e4cd2d53d8c2634751/crates/sequencing/papyrus_consensus/src/lib.rs#L4)):*
> ```XML
> // TODO(Matan): Add a description of the crate.
> // TODO(Matan): fix #[allow(missing_docs)].
> //! A consensus implementation for a [`Starknet`] node.
> ```

Consider adding instead
``//! [`Starknet`]: https://starknet.io/``



_Code quote:_
```XML
A consensus implementation for a [`Starknet`] node.
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2134)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2134#-O0Ii6chBcryE-ZzXlvC:-O0K-BtYEHkC-ah1dMn1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f0a025ba40f0cf6c37b04d96121bbc9525960e36/crates/sequencing/papyrus_consensus/src/lib.rs#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider adding instead
``//! [`Starknet`]: https://starknet.io/``
</blockquote></details>

Done.

**Pull request merged**
