### PR TITLE
Divide load test to modules.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/486)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/486)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNCC-VlCwIz_5I6j4S_:-NNCC-VlCwIz_5I6j4Sa:b-v0w9mn) ([raw file](https://github.com/starkware-libs/papyrus/blob/957f73ee741592f4ccc8a8a9002dac7eb9d0bc76/crates/papyrus_load_test/src/gateway_functions.rs#L21)):*
> ```XML
> pub async fn get_block_with_tx_hashes_by_hash<T: DeserializeOwned>(
>     user: &mut GooseUser,
>     block_hash: &str,
> ```

also change hash_str to block_hash
___
*[`crates/papyrus_load_test/src/main.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNCCIRB8wXpk9rCQFMt:-NNCCIRB8wXpk9rCQFMu:b2654im) ([raw file](https://github.com/starkware-libs/papyrus/blob/957f73ee741592f4ccc8a8a9002dac7eb9d0bc76/crates/papyrus_load_test/src/main.rs#L31)):*
> ```XML
>     let goose = register_scenarios(GooseAttack::initialize()?);
>     let metrics = goose.execute().await?;
> ```

This change is to prepare for adding more scenarios in a different function



_Code quote:_
```XML
    let goose = register_scenarios(GooseAttack::initialize()?);
    let metrics = goose.execute().await?;
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/486#-:-NNHSUFfB4_r9fcjiEOv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNHSElC4yvngbb8_mWy:-NNHSElC4yvngbb8_mWz:b-no0jg4) ([raw file](https://github.com/starkware-libs/papyrus/blob/957f73ee741592f4ccc8a8a9002dac7eb9d0bc76/crates/papyrus_load_test/src/lib.rs#L1)):*
> ```XML
> pub mod gateway_functions;
> ```

Consider `endpoints` instead.



_Code quote:_
```XML
functions
```
___
*[`crates/papyrus_load_test/src/load_tests.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNHRj340xG4kwUfuQCl:-NNHRj351HvEWqZig1V3:b-gxnv83) ([raw file](https://github.com/starkware-libs/papyrus/blob/957f73ee741592f4ccc8a8a9002dac7eb9d0bc76/crates/papyrus_load_test/src/load_tests.rs#L5)):*
> ```XML
> use crate::gateway_functions::*;
> 
> pub async fn loadtest_get_block_with_tx_hashes_by_number(
> ```

Consider removing the `loadtest_` prefix (now that it resides in a designated file)



_Code quote:_
```XML
loadtest_
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/486)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNHSElC4yvngbb8_mWy:-NNHgjGu1rW8-oiSoT7O:bfyc5x1) ([raw file](https://github.com/starkware-libs/papyrus/blob/957f73ee741592f4ccc8a8a9002dac7eb9d0bc76/crates/papyrus_load_test/src/lib.rs#L1)):*
> endpoints
done

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/486)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_load_test/src/load_tests.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/486#-NNHRj340xG4kwUfuQCl:-NNHm1IP1EzSh4MHrGi-:b-82nagh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d67684a3fc98f740f237d012be96e6337d77ec6/crates/papyrus_load_test/src/load_tests.rs#L5)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider removing the `loadtest_` prefix (now that it resides in a designated file)
</blockquote></details>

it makes conflicts with the gateway_endpoints functions.

**Pull request merged**
