### PR TITLE
add test for ContractClassAbiEntryWithType from ontractClassAbiEntry

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #766** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/766" target="_blank">Graphite</a> 
    * **PR #767** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/767" target="_blank">Graphite</a>  👈
      * **PR #763** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/763" target="_blank">Graphite</a> 
      * **PR #762** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/762" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/767?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/767#-NYqZh6q8nREnCz49XjF:-NYqZh6q8nREnCz49XjG:b-wrrzf) ([raw file](https://github.com/starkware-libs/papyrus/blob/6ba35828a7485acc304aac6f4959575d86350574/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
> ```XML
> 
> #[tokio::test]
> async fn test_contractclassabientrywithtype_from_api_contractclassabientry() {
> ```

Things regarding test name
1. our convention is to not write test_ at the start of the name. I know that there's a test in this file that doesn't follow this convention but in the rest of the files that is the convention (If you can fix it across the entire file that would be great :) )
2. I think we can get rid of _api_
3. @dan-starkware should our convention be to write the class name as it is (CapitalCase)? I think it makes sense here to call this test ContractClassAbiEntryWithType_from_ContractClassAbiEntry
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/767#-NYqkYfj5HTD8uMDJrpl:-NYqkYfk0jaGSvu3Jo_5:b-gewndl) ([raw file](https://github.com/starkware-libs/papyrus/blob/6ba35828a7485acc304aac6f4959575d86350574/crates/papyrus_gateway/src/gateway_test.rs#L110)):*
> ```XML
> async fn test_contractclassabientrywithtype_from_api_contractclassabientry() {
>     let mut rng = get_rng();
>     let _: ContractClassAbiEntryWithType =
> ```

Split this into three different tests:
ContractClassAbiEntryWithType_from_ContractClassAbiEntry_event
ContractClassAbiEntryWithType_from_ContractClassAbiEntry_function
ContractClassAbiEntryWithType_from_ContractClassAbiEntry_struct

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/767#-NYqkYfj5HTD8uMDJrpl:-NZ-i8Dq5icG75dqiCeA:b-xq3ym9) ([raw file](https://github.com/starkware-libs/papyrus/blob/6ba35828a7485acc304aac6f4959575d86350574/crates/papyrus_gateway/src/gateway_test.rs#L110)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't look at this as a function, I look at it as a test case. And I think it makes more sense to create a different test case for each thing you are testing instead of having a case that combines three cases because they are similar
</blockquote></details>

what do you think of this version? a macro that generates the tests per variant

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/767#-NYqZh6q8nREnCz49XjF:-NZ07xSx8Ad6dpax0mcB:b-fwcwb) ([raw file](https://github.com/starkware-libs/papyrus/blob/6ba35828a7485acc304aac6f4959575d86350574/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Very well. @dan-starkware regarding 3, let's see if we can configure Clippy to allow this
</blockquote></details>

feel better? :)

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767#-:-NZ54zkABPcu2O-Cgxs2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/767#-NYqkYfj5HTD8uMDJrpl:-NZ54x-r3aKbHhmdFWtX:b-vs0084) ([raw file](https://github.com/starkware-libs/papyrus/blob/6ba35828a7485acc304aac6f4959575d86350574/crates/papyrus_gateway/src/gateway_test.rs#L110)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

what do you think of this version? a macro that generates the tests per variant
</blockquote></details>

Looks great

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/767#-:-NZ62jzB089NagnykDx7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
