### PR TITLE
feat(network): improve network config for connecting to main

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1663** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1663?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1663?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobKkg6GxBtF6j7pvt:-NpobKkg6GxBtF6j7pvu:b-i8jm5n) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L41)):*
> ```XML
> 
> #[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
> pub struct NetworkConfig {
> ```

IMO the fact that the Config sits in the network crate means it's network config, but it's stylistic so whatever you prefer
___
*[`crates/papyrus_network/src/lib.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobI3yCrw9PX8eGfW-:-NpobI3yCrw9PX8eGfW0:b22quet) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L42)):*
> ```XML
> #[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
> pub struct NetworkConfig {
>     #[serde(deserialize_with = "deserialize_string_vector")]
> ```

Remove this
___
*[`crates/papyrus_network/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobFHUBzavJjUY8iLc:-NpobFHUBzavJjUY8iLd:br6r2r7) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L56)):*
> ```XML
>             ser_param(
>                 "listen_addresses",
>                 &serialize_string_vector(&self.listen_addresses),
> ```

use serde_json::to_string instead
___
*[`crates/papyrus_network/src/network_manager.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobbUI5e6ZGTqp-Vj_:-NpobbUI5e6ZGTqp-Vja:b10wfoj) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/network_manager.rs#L20)):*
> ```XML
> pub enum NetworkError {
>     #[error("Select loop encountered an unknown case")]
>     UnknownSelectCaseError,
> ```

What is this error? When will it appear?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobKkg6GxBtF6j7pvt:-Npoby446msq-i1SAbpF:bykx7gv) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO the fact that the Config sits in the network crate means it's network config, but it's stylistic so whatever you prefer
</blockquote></details>

when I connected it to main I saw that all other crates call it like that so I changed it. next PR you'll see
___
*[`crates/papyrus_network/src/lib.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobI3yCrw9PX8eGfW-:-Npoc77k513Smm7WmzwK:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L42)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

done
___
*[`crates/papyrus_network/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobFHUBzavJjUY8iLc:-NpocI_18E8w5ZsNz0YJ:b-9chp70) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/lib.rs#L56)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use serde_json::to_string instead
</blockquote></details>

as above
___
*[`crates/papyrus_network/src/network_manager.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-NpobbUI5e6ZGTqp-Vj_:-NpsD6E67YYP1b57BuPg:b-gdoaf6) ([raw file](https://github.com/starkware-libs/papyrus/blob/6368fa6250247a5049dfd9d3508dfe178e420fe4/crates/papyrus_network/src/network_manager.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What is this error? When will it appear?
</blockquote></details>

the file moved. I've removed the variant (it was used before and then I removed the usage)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-Npt10pT4bJg35YsmbvQ:-Npt0ncS5F6Iv7pT2Sj7:bxus4tb) ([raw file](https://github.com/starkware-libs/papyrus/blob/792203170ef3b9ee8766d1a85b67d12bd6090e67/crates/papyrus_network/src/network_manager/mod.rs#L17)):*
> ```XML
> type StreamCollection = SelectAll<BoxStream<'static, (Data, InboundSessionId)>>;
> 
> #[derive(thiserror::Error, Debug)]
> ```

try to remove this

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-:-NpxbI6LB9GfIJ-W4_OS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1663#-:-Npy-FT3AxZkK5zv6pj3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
