### PR TITLE
feat(JSON-RPC): get_class supports pending

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1348)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1348)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1348#-Ni435929tTVeYedkIK0:-Ni43593DVONjHz_rIUe:beydfcm) (no related file):*
We shouldn't merge this until #1339 is merged

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1348)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1348#-Ni48hRx8VaNQbm0s8x-:-Ni48hRx8VaNQbm0s8x0:b-i1djv7) (no related file):*
This PR was already approved in #1278 

___

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1348#-:-NiZl1f22CdW_f27AbdA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
