### PR TITLE
feat(network): add conversion between protobuf StateDiffsResponse and sn api

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2yYnC1xvhsFqWHY2f:-Nz2yYnC1xvhsFqWHY2g:b-o4i6x5) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L37)):*
> ```XML
>     fn try_from(value: protobuf::StateDiffsResponse) -> Result<Self, Self::Error> {
>         match value.state_diff_message {
>             Some(protobuf::state_diffs_response::StateDiffMessage::ContractDiff(contract_diff)) => {
> ```

This code is quite big. Could you extract ContractDiff, DeclaredClass and DeprecatedDeclaredClass into structs, put those structs inside the enum, add conversions to those structs to/from protobuf types and use those conversions here?
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2xS-m8YxdKGB234kL:-Nz2xS-m8YxdKGB234kM:b-b4p2bf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L48)):*
> ```XML
>                     contract_diff
>                         .class_hash
>                         .ok_or(ProtobufConversionError::MissingField {
> ```

class hash can be None. use map and transpose instead
Add a comment that class hash can be none if the contract wasn't deployed this block
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2x_Z1DZ7bm1xBvAwW:-Nz2x_Z1DZ7bm1xBvAwX:b-8w0y0q) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L54)):*
> ```XML
>                 ));
> 
>                 let nonce = contract_diff
> ```

Add a comment that nonce can be none if it wasn't updated in this block
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2yATa08E6p2RY5cI2:-Nz2yATa08E6p2RY5cI3:b-4e6087) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L59)):*
> ```XML
>                     .transpose()?;
> 
>                 let storage_diffs = if contract_diff.values.is_empty() {
> ```

Why do you need this if? I think that if you just put the code in the else block for both cases it will work fine
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz34Mj30-7te_-0FvZB:-Nz34Mj30-7te_-0FvZC:bn358n1) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L88)):*
> ```XML
>                 );
> 
>                 let Some(compiled_class_hash) = declared_class.compiled_class_hash else {
> ```

In this case I think match is clearer than let-else since both of the flows are equivalent so they should be equivalent in the level of indentations

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2yYnC1xvhsFqWHY2f:-Nz3T0MdAxv3BHIBtGgd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This code is quite big. Could you extract ContractDiff, DeclaredClass and DeprecatedDeclaredClass into structs, put those structs inside the enum, add conversions to those structs to/from protobuf types and use those conversions here?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2xS-m8YxdKGB234kL:-Nz3T10Q-TX4z8TCbYf8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

class hash can be None. use map and transpose instead
Add a comment that class hash can be none if the contract wasn't deployed this block
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2x_Z1DZ7bm1xBvAwW:-Nz3T1kD6-VxEX5Mx9tX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L54)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that nonce can be none if it wasn't updated in this block
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz2yATa08E6p2RY5cI2:-Nz3T37T2PbkDR6-iP7B:bxjekc4) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you need this if? I think that if you just put the code in the else block for both cases it will work fine
</blockquote></details>

u r right, Done
___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz34Mj30-7te_-0FvZB:-Nz3T7p871c_S_ZMAEcO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0a600c8be48f5148812ec0e13539708d2efe26e4/crates/papyrus_protobuf/src/converters/state_diff.rs#L88)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In this case I think match is clearer than let-else since both of the flows are equivalent so they should be equivalent in the level of indentations
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz3UgTwBNDDSo-YaoFL:-Nz3UgTwBNDDSo-YaoFM:b-p57l78) ([raw file](https://github.com/starkware-libs/papyrus/blob/d78b5c74f4a8bbf4d9e10bf1524f26ce5dc57c99/crates/papyrus_protobuf/src/converters/state_diff.rs#L52)):*
> ```XML
>             Some(protobuf::state_diffs_response::StateDiffMessage::DeclaredClass(
>                 declared_class,
>             )) => match declared_class.clone().compiled_class_hash {
> ```

No need to clone, do it by reference `match declared_class.compiled_class_hash.as_ref()`

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/state_diff.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2066#-Nz3UgTwBNDDSo-YaoFL:-Nz3VUM04W7KhPLmhEeE:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d78b5c74f4a8bbf4d9e10bf1524f26ce5dc57c99/crates/papyrus_protobuf/src/converters/state_diff.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to clone, do it by reference `match declared_class.compiled_class_hash.as_ref()`
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2066)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
