### PR TITLE
chore(JSON-RPC): copy v0_7 spec changes that don't require code changes

### PR DESCRIPTION
**Pull request by ShahakShama**
- chore(JSON-RPC): copy v0_6 into v0_7
- chore(JSON-RPC): copy v0_7 spec changes that don't require code changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1728)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1728)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1728#-NrAWHtv0eP6nE_EBKfb:-NrAWHtv0eP6nE_EBKfc:b32vfx) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b9fad9f7da13639f06ff96b26b9c474040689d4/crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json#L4)):*
> ```JSON
>     "openrpc": "1.0.0-rc1",
>     "info": {
>         "version": "0.6.0",
> ```

7?



_Code quote:_
```JSON
6.0
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1728)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1728#-NrAWHtv0eP6nE_EBKfb:-NrAXOKU-kjK7JHHcIGd:bnq2bay) ([raw file](https://github.com/starkware-libs/papyrus/blob/1b9fad9f7da13639f06ff96b26b9c474040689d4/crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json#L4)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

7?
</blockquote></details>

Done. @ArielElp please fix this in the specs as well

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 23 of 26 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1728#-:-NrAa-NJ72sOWgnEDEPj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1728)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
