### PR TITLE
refactor(network): move to converters-starknetapi Header & Signature to protobuf SignedBlockHeader

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1766)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1766?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1766** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1766?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1766#-:-Ns7sPqJ0r5uPSNuvrYe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1766)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1766)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
