### PR TITLE
feat(storage): add mmap file utility

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-Nfdim842kT2RlKJWTKm:-Nfdim842kT2RlKJWTKn:baigify) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L44)):*
> ```XML
>     assert_eq!(res, data);
> 
>     let reader_clone = reader;
> ```

Not sure this is what you meant. Try to clone earlier in the function.
___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdiuCf16KTofgIEM50:-NfdiuCf16KTofgIEM51:b9c9r5v) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L50)):*
> ```XML
>     dir.close().unwrap();
> }
> // TODO: test writing and reading from different locations.
> ```

Should you assign someone in the TODO? i.e. TODO(dan)
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdjFJd8TL3jEKapALQ:-NfdjFJd8TL3jEKapALR:b42qxxb) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L83)):*
> ```XML
> pub struct LocationInFile {
>     /// Offset in the file.
>     pub offset: usize,
> ```

Can this be non public? Right now it's a path to have unsafety with safe rust: Someone can change this and try to read from unallocated memory.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdjYzqBaBspKyNM31F:-NfdjYzrD96jEzRJciyz:b-mxl49h) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L90)):*
> ```XML
> impl LocationInFile {
>     /// returns the next offset in the file.
>     pub fn next_offset(&self) -> usize {
> ```

Why is this pub?
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdkFVDCmwljzzGLA3m:-NfdkFVDCmwljzzGLA3n:b34ezzw) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L154)):*
> ```XML
>     fn get(&self, location: LocationInFile) -> Option<V> {
>         debug!("Reading object at location: {:?}", location);
>         let bytes = std::borrow::Cow::from(unsafe {
> ```

Why do you need the Cow here? Consider calling deserialize from within the unsafe if it helps.

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-Nfdim842kT2RlKJWTKm:-NfejCWaB9dtBxKId4uA:b-ucfkni) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not sure this is what you meant. Try to clone earlier in the function.
</blockquote></details>

Thanks 
___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdiuCf16KTofgIEM50:-NfeiJa66HNjheztER-b:b8822u5) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L50)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should you assign someone in the TODO? i.e. TODO(dan)
</blockquote></details>

implemented
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdjFJd8TL3jEKapALQ:-NfeiP0o34R0I_z770aV:b-hicu5o) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can this be non public? Right now it's a path to have unsafety with safe rust: Someone can change this and try to read from unallocated memory.
</blockquote></details>

Right, thanks
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdjYzqBaBspKyNM31F:-NfeiPQ9-WyXZukwIcZt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why is this pub?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdkFVDCmwljzzGLA3m:-NfeiQCx063nSmg_b6ED:b-ijzjf5) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L154)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why do you need the Cow here? Consider calling deserialize from within the unsafe if it helps.
</blockquote></details>

I thought it was cheap enough (Cow::from conversion does not allocate or clone the data) and is more safe since deserialize gets `(bytes: &mut impl std::io::Read)` and might mess the underlying file.
Is this better?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-Nfdim842kT2RlKJWTKm:-NfemxDs-WK0KCBAd-Ru:b-vw9ufq) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L44)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

What makes this another reader? Didn't u mean to clone?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-Nfdim842kT2RlKJWTKm:-Nfeok-Z2r1Z7oXIrGtl:b-ne0p99) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What makes this another reader? Didn't u mean to clone?
</blockquote></details>

It is copied. We use `reader` right after `let another_reader = reader;`

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-NfdkFVDCmwljzzGLA3m:-NfesF9GB-2CyZGKQPK1:b-lk91ms) ([raw file](https://github.com/starkware-libs/papyrus/blob/32f55d075727ddc9d475b1a1775270ed1e01b53c/crates/papyrus_storage/src/mmap_file/mod.rs#L154)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I thought it was cheap enough (Cow::from conversion does not allocate or clone the data) and is more safe since deserialize gets `(bytes: &mut impl std::io::Read)` and might mess the underlying file.
Is this better?
</blockquote></details>

Mutable Reader cannot change the file

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1225#-:-NfewGtnDoWidXjWSNaj:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Pull request merged**
