### PR TITLE
refactor(network): move to converters-protobuf::SignedBlockHeader to network SignedBlockHeader

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1765)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1765)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1765#-Ns7naRL-9sgiMoN_ScF:-Ns7naRL-9sgiMoN_ScG:bh9inty) (no related file):*
You just erased code without moving it

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1765)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1765#-Ns7naRL-9sgiMoN_ScF:-Ns7oH4u0f7w6qtPcNMd:b-na8l62) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You just erased code without moving it
</blockquote></details>

my bad

___

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1765#-:-Ns7pGgb9qOHN9-HpsdP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
