### PR TITLE
fix(monitoring): change log levels

### PR DESCRIPTION
**Pull request by OriStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1384)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OriStarkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1384#-NinWgUVCOgoWF9Yhy0K:-NinWgUWDQS0w0VGRgUT:byzqqcm) ([raw file](https://github.com/starkware-libs/papyrus/blob/687ab10bd6b92f9a442bb2dd784a1436797bf809/crates/papyrus_sync/src/lib.rs#L382)):*
> ```XML
>                 .expect("block timestamp should be valid");
>         let header_latency = dt.num_seconds();
>         info!("Block {} was added. Header latency: {}.", header_latency - 1, header_latency);
> ```

??
is this correct?



_Code quote:_
```XML
header_latency - 1
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1384#-NinWgUVCOgoWF9Yhy0K:-Nio7phQ6229ggt8Xw3j:b-t8w7lb) ([raw file](https://github.com/starkware-libs/papyrus/blob/687ab10bd6b92f9a442bb2dd784a1436797bf809/crates/papyrus_sync/src/lib.rs#L382)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

??
is this correct?
</blockquote></details>

I think so, @dan-starkware am I wrong?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_sync/src/lib.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1384#-NinWgUVCOgoWF9Yhy0K:-Nj1oLB556_NKav9nzDD:b3jf9d2) ([raw file](https://github.com/starkware-libs/papyrus/blob/687ab10bd6b92f9a442bb2dd784a1436797bf809/crates/papyrus_sync/src/lib.rs#L382)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I think so, @dan-starkware am I wrong?
</blockquote></details>

It seems wrong, why info and how latency relates to Block?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1384)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1384#-NinWgUVCOgoWF9Yhy0K:-Nj7fKxh72kCcQ9v06Nu:bt2vr1b) ([raw file](https://github.com/starkware-libs/papyrus/blob/687ab10bd6b92f9a442bb2dd784a1436797bf809/crates/papyrus_sync/src/lib.rs#L382)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

It seems wrong, why info and how latency relates to Block?
</blockquote></details>

Fixed.

**Pull request closed without merging**
