### PR TITLE
Fix bug in deserializing declare tx in the gateway

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/650)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/650)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/transaction.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/650#-NU0c0Dg6XFKSLZvkJq3:-NU0c0Dg6XFKSLZvkJq4:b-nl0qmp) ([raw file](https://github.com/starkware-libs/papyrus/blob/07ac8144bb145d192f885269e69b7bec40a7de4f/crates/papyrus_gateway/src/transaction.rs#L44)):*
> ```XML
> 
> impl From<starknet_api::transaction::DeclareTransactionV0V1> for DeclareTransactionV0V1 {
>     fn from(tx: starknet_api::transaction::DeclareTransactionV0V1) -> Self {
> ```

I'd suggest to add a parameter here and avoid the code duplication

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/650)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/transaction.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/650#-NU0c0Dg6XFKSLZvkJq3:-NUaHp7o8ndWVY1lfz74:bq2wfqa) ([raw file](https://github.com/starkware-libs/papyrus/blob/abb7b55b62c6bd42d732b59a7dce195fc0698a4b/crates/papyrus_gateway/src/transaction.rs#L44)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I'd suggest to add a parameter here and avoid the code duplication
</blockquote></details>

I'm guessing you refer to this?

```
impl From<starknet_api::transaction::Transaction> for Transaction {
```

Please write comments on the code you are referring to

I don't think that the code duplication here is so bad

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/650)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by nagmo-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
