### PR TITLE
chore: update docker image tags

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1089)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`.github/workflows/docker-publish.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-NcO9Ogx2GNZ1D_WAL9u:-NcO9Ogx2GNZ1D_WAL9v:b-phm1ox) ([raw file](https://github.com/starkware-libs/papyrus/blob/667fe8309377bf5f4cbd6ed90da856167e66da47/.github/workflows/docker-publish.yml#L47)):*
> ```YAML
>           images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}
>           tags: |
>             type=match,pattern=v(.*),group=1
> ```

@alon-dotan-starkware LMK if you prefer `{{raw}}` instead



_Code quote:_
```YAML
type=match,pattern=v(.*),group=1
```

**Comment by dan-starkware** [comment]
*[`.github/workflows/docker-publish.yml` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-NcOAZUy39YjneETBFzU:-NcOAZUy39YjneETBFzV:b84qzti) ([raw file](https://github.com/starkware-libs/papyrus/blob/667fe8309377bf5f4cbd6ed90da856167e66da47/.github/workflows/docker-publish.yml#L53)):*
> ```YAML
>             # set `dev` tag for the default branch (`main`).
>             type=raw,value=dev,enable={{is_default_branch}}
>             type=raw,value={{branch}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}
> ```

LMK if there is a better convention here (maybe add a `manual` prefix or something like that)



_Code quote:_
```YAML
value={{branch}}-{{sha}}
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1089)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`.github/workflows/docker-publish.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-NcO9Ogx2GNZ1D_WAL9u:-NcOdAW9BYHlXATceMYy:but5vmw) ([raw file](https://github.com/starkware-libs/papyrus/blob/667fe8309377bf5f4cbd6ed90da856167e66da47/.github/workflows/docker-publish.yml#L47)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@alon-dotan-starkware LMK if you prefer `{{raw}}` instead
</blockquote></details>

What will be the diff? 
can you post 2 examples?

**Comment by dan-starkware** [comment]
*[`.github/workflows/docker-publish.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-NcO9Ogx2GNZ1D_WAL9u:-NcQq86PBgEOtl5cSHNK:b-p0683e) ([raw file](https://github.com/starkware-libs/papyrus/blob/667fe8309377bf5f4cbd6ed90da856167e66da47/.github/workflows/docker-publish.yml#L47)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

What will be the diff? 
can you post 2 examples?
</blockquote></details>

Just the `v` prefix, 
Given tag `v2.0.8-beta.67`
`{{raw}}` yields `v2.0.8-beta.67`
`type=match,pattern=v(.*),group=1` yields `2.0.8-beta.67`

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1089)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`.github/workflows/docker-publish.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-NcO9Ogx2GNZ1D_WAL9u:-NcRWYuG2SWAD5oBv8f0:b-93m2b0) ([raw file](https://github.com/starkware-libs/papyrus/blob/667fe8309377bf5f4cbd6ed90da856167e66da47/.github/workflows/docker-publish.yml#L47)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Just the `v` prefix, 
Given tag `v2.0.8-beta.67`
`{{raw}}` yields `v2.0.8-beta.67`
`type=match,pattern=v(.*),group=1` yields `2.0.8-beta.67`
</blockquote></details>

I prefer raw

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1089#-:-NcbQFTOAIHZxPl8CI38:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
