### PR TITLE
feat(network): protocols return the IO

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1157)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1157)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/streamed_data_protocol/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1157#-NeChjb94yX-tmJUa-sn:-NeChjb94yX-tmJUa-so:bb7r2f0) ([raw file](https://github.com/starkware-libs/papyrus/blob/4162fc403f38d5f4a1685273981f1c6f6adfeab9/crates/papyrus_network/src/streamed_data_protocol/mod.rs#L2)):*
> ```XML
> // pub mod behaviour;
> // pub mod handler;
> ```

why?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1157)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_data_protocol/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1157#-NeChjb94yX-tmJUa-sn:-NeCiSEs2m7ZbXodv1m1:b-yd53y5) ([raw file](https://github.com/starkware-libs/papyrus/blob/4162fc403f38d5f4a1685273981f1c6f6adfeab9/crates/papyrus_network/src/streamed_data_protocol/mod.rs#L2)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

We talked about this Be-al pe. look at the target branch, it's a feature branch

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_network/src/streamed_data_protocol/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1157#-NeChjb94yX-tmJUa-sn:-NeCiqzz9naPVsF2n6sS:b-q8jzb0) ([raw file](https://github.com/starkware-libs/papyrus/blob/4162fc403f38d5f4a1685273981f1c6f6adfeab9/crates/papyrus_network/src/streamed_data_protocol/mod.rs#L2)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We talked about this Be-al pe. look at the target branch, it's a feature branch
</blockquote></details>

got it

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
