### PR TITLE
make get_rand_test_body_with_events private

### PR DESCRIPTION
**Pull request by nagmo-starkware**
commit-id:30c1cdb7

---

**Stack**:
- #639
- #638
- #637
- #636 ⬅
- #635
- #634

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/636#-NU6nEejCSeI-68zKro1:-NU6nEekCNXQIQnLolOJ:b4pmumj) (no related file):*
Isn't this as #637 ? I think I've reviewed these changes several times.

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/636#-NU6nEejCSeI-68zKro1:-NUHIqbuEmuXXx8VHABz:b-alys6x) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Isn't this as #637 ? I think I've reviewed these changes several times.
</blockquote></details>

no they are different. note the this one is "get_test_**body**_with_events" and the other is "get_test_**block**_with_events"

___

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1427 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/636#-NUIdzCjEDHbwj-OXSvb:-NUIdzCjEDHbwj-OXSvc:bdbkis2) ([raw file](https://github.com/starkware-libs/papyrus/blob/a9961b93803838ea758e0c0e5cb5247d2febbf41/crates/papyrus_gateway/src/gateway_test.rs#L1427)):*
> ```XML
>             ..BlockHeader::default()
>         },
>         body: get_test_body(Some(0), 1, None, None, None),
> ```

Let's discuss this f2f.



_Code quote:_
```XML
Some(0)
```
___
*[`crates/test_utils/src/lib.rs` line 220 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/636#-NUIdU_X3zyeIrN3KvpU:-NUIdU_X3zyeIrN3KvpV:b-4i5bfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/a9961b93803838ea758e0c0e5cb5247d2febbf41/crates/test_utils/src/lib.rs#L220)):*
> ```XML
> }
> 
> // Returns a test block body with a variable number of transactions.
> ```

with events..
Though I'm fine with fixing the public functions documentation as a last PR (I think they should have much better documentation)



_Code quote:_
```XML
// Returns a test block body with a variable number of transactions.
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/636)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
