### PR TITLE
feat(network): dial peer in network run function

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1739?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#1739** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1739?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1738** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1738?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1729** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1729?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1704** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1670** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1670?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1715** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1739?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-:-NrVaO_J8yK1TqsU742f:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrV_zxo9mEfTdTuAwje:-NrV_zxo9mEfTdTuAwjf:b-28gl6z) ([raw file](https://github.com/starkware-libs/papyrus/blob/983fbdc189b67bc6bdb273657ad9959e60546f13/crates/papyrus_network/src/network_manager/mod.rs#L47)):*
> ```XML
>     pub async fn run(mut self) -> Result<(), NetworkError> {
>         if let Some(peer_id) = self.peer_id {
>             debug!("Starting network manager with peer id: {peer_id:?}");
> ```

Consider "with" -> "connected to"
and "without peer id" -> "not connected to any peer"
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrVaL_X7T9AYX5ZLbq-:-NrVaL_X7T9AYX5ZLbq0:b-q70vk4) ([raw file](https://github.com/starkware-libs/papyrus/blob/983fbdc189b67bc6bdb273657ad9959e60546f13/crates/papyrus_network/src/network_manager/test.rs#L114)):*
> ```XML
> 
>     fn dial(&mut self, peer_id: PeerId) -> Result<(), libp2p::swarm::DialError> {
>         unimplemented!("MockSwarm::dial not implemented")
> ```

Consider just returning Ok(())

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrVaL_X7T9AYX5ZLbq-:-NrVaYfy0eBmP6zBVGP7:b-ubgdx4) ([raw file](https://github.com/starkware-libs/papyrus/blob/983fbdc189b67bc6bdb273657ad9959e60546f13/crates/papyrus_network/src/network_manager/test.rs#L114)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider just returning Ok(())
</blockquote></details>

I prefer to make it obvious that it's not dealt with

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/p2p_integration_endpoint.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYrboN4shBkjz-5voZ:-NrYrboN4shBkjz-5vo_:b-4wx5v4) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_network/src/bin/p2p_integration_endpoint.rs#L48)):*
> ```XML
>         network_manager.dial(dial_address);
>     }
>     let _ = network_manager.run().await;
> ```

You should handle the error, not ignore it
___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYrwJOCQRhKwhoHnsI:-NrYrwJOCQRhKwhoHnsJ:b-yvoeux) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_network/src/network_manager/swarm_trait.rs#L53)):*
> ```XML
>     fn dial(&mut self, peer_id: PeerId) -> Result<(), DialError> {
>         let addresses = vec>             Multiaddr::from_str("/ip4/127.0.0.1/tcp/10000").expect("string to multiaddr failed"),
> ```

Why is this a hardcoded address?
___
*[`crates/papyrus_node/src/main.rs` line 163 at r3 ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_node/src/main.rs#L163)):*
> ```XML
>     let network_manager =
>         network_manager::NetworkManager::new(network_config.clone(), storage_reader.clone());
>     network_manager.run().await.expect("network manager failed");
> ```

Handle the error here in the same way it's handled with Sync. Mainly, I want to see the error when it happens

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/bin/p2p_integration_endpoint.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYrboN4shBkjz-5voZ:-NrZSpQv-qmKp526_2tB:b-9ln3j1) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_network/src/bin/p2p_integration_endpoint.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should handle the error, not ignore it
</blockquote></details>

it's the integration endpoint.. we expect it to not return and if it returns then the endpoint will shut down
___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYrwJOCQRhKwhoHnsI:-NrZT2rqCab2bqhccb2L:b-sb6ks) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_network/src/network_manager/swarm_trait.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this a hardcoded address?
</blockquote></details>

it's temporary until I'll have the PR that adds the peer stuff to the config
___
*[`crates/papyrus_node/src/main.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYs6OV3v22T_Mvgzxt:-NrZTD0b7_asAqLmci2U:b-yru4kj) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_node/src/main.rs#L163)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Handle the error here in the same way it's handled with Sync. Mainly, I want to see the error when it happens
</blockquote></details>

you've already approved the PR that fixes it. it's merged into the p2psync connection to main branch.
I'll see if I can extract the part that handles this from it and merge it to main before the rest. 
for now I suggest to merge it since I agree it looks better the other way but the functionality is the same.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-:-Nr_2tXp40pvAUoi0aqJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/bin/p2p_integration_endpoint.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-NrYrboN4shBkjz-5voZ:-NrZUGbA1MzwKzvumGNN:b-llplnd) ([raw file](https://github.com/starkware-libs/papyrus/blob/dca06f9077585ac8c327792e08bbc41370123510/crates/papyrus_network/src/bin/p2p_integration_endpoint.rs#L48)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's the integration endpoint.. we expect it to not return and if it returns then the endpoint will shut down
</blockquote></details>

Just do expect("Network manager failed")
so that the process will exit with error and not with 0
you can do it in a future PR if you prefer

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1739#-:-Nr_8gzxAj1Flh0a5dgW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
