### PR TITLE
Call method using Blockifier

### PR DESCRIPTION
**Pull request by marioiordanov**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently call functions are forwarded to the sequencer.

## What is the new behavior?

Using the Blockifier project, now the call rpc request are executed in Papyrus and are not forwarded to the sequencer.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 2 of 6 files at r3, 2 of 5 files at r4, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @marioiordanov)

___
*[`config/config.yaml` line 33 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0oRod8TukvorrBT7o:-NU0oRod8TukvorrBT7p:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/config/config.yaml#L33)):*
> ```YAML
>     # Maximum number of keys supported by the node in get_events requests.
>     max_events_keys: 100
>     # starknet token address for paying fees
> ```





_Suggestion:_
```YAML
    # Fee token address.
    fee_token_address: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0puH_A4GJ468MG2lw:-NU0puH_A4GJ468MG2lx:b-78n5r6) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L147)):*
> ```XML
>     txn: &StorageTxn<'_, Mode>,
>     block_number: BlockNumber,
> ) -> Result<blockifier::state::cached_state::CachedState<DictStateReader>, Error> {
> ```

Why not use Papyrus as the state?



_Code quote:_
```XML
blockifier::state::cached_state::CachedState<DictStateReader>
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 575 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0po_i1uLXtnsCeYB4:-NU0po_i1uLXtnsCeYB5:btwhbw2) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L575)):*
> ```XML
> 
>     #[instrument(skip(self), level = "debug", err, ret)]
>     fn call(&self, block_id: BlockId, request: FunctionCall) -> Result<FunctionCallResult, Error> {
> ```

I thought `call` is done in a context of a block number.



_Code quote:_
```XML
block_id: BlockId
```
___
*[`crates/papyrus_gateway/src/state.rs` line 139 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0ou9C1jdZh1_1H13C:-NU0ou9D4HATppP0LWCV:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/state.rs#L139)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct FunctionCallResult(pub Arc<Vec<StarkFelt>>);
> ```





_Suggestion:_
```XML
Retdata
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @marioiordanov)

___
*[`crates/papyrus_gateway/src/state.rs` line 139 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0q8PC3F5GhfoX1kS0:-NU0q8PD6sZpICy7oerC:b-l5xcmp) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/state.rs#L139)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct FunctionCallResult(pub Arc<Vec<StarkFelt>>);
> ```

What about state diff.?



_Code quote:_
```XML
FunctionCallResult
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @marioiordanov)

___
*[`crates/papyrus_gateway/src/lib.rs` line 604 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0qdrzD1icUMM09vWF:-NU0qdrzD1icUMM09vWG:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L604)):*
> ```XML
>         let call_entry_point = CallEntryPoint {
>             class_hash: Option::Some(class_hash),
>             entry_point_type: starknet_api::deprecated_contract_class::EntryPointType::External,
> ```





_Suggestion:_
```XML
EntryPointType::External
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 607 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0qhMO2MmfDsEyOOcx:-NU0qhMO2MmfDsEyOOcy:bcmyvbl) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L607)):*
> ```XML
>             entry_point_selector: request.entry_point_selector,
>             calldata: request.calldata,
>             call_type: blockifier::execution::entry_point::CallType::Call,
> ```

This can be moved to SN API.



_Code quote:_
```XML
CallType
```

**Review by marioiordanov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 2 of 12 files reviewed, 6 unresolved discussions (waiting on @elintul)

___
*[`crates/papyrus_gateway/src/lib.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0puH_A4GJ468MG2lw:-NUNtxg2-tYz42P27y2h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L147)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not use Papyrus as the state?
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/state.rs` line 139 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0q8PC3F5GhfoX1kS0:-NUNt_KECX_ybTfrNfJj:b-wgkw8j) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/state.rs#L139)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about state diff.?
</blockquote></details>

The call functions execution doesn't produce state diff

**Review by marioiordanov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 2 of 12 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/papyrus_gateway/src/lib.rs` line 575 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0po_i1uLXtnsCeYB4:-NUQ69ouA4XkGZCf2_fz:bwuvj19) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L575)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I thought `call` is done in a context of a block number.
</blockquote></details>

as per the spec it is BlockId

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 2 of 12 files reviewed, 4 unresolved discussions (waiting on @marioiordanov)

___
*[`crates/papyrus_gateway/src/lib.rs` line 575 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0po_i1uLXtnsCeYB4:-NUSeq9dDRAZ28_V6p--:bgvy8a5) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L575)):*
<details><summary><i>Previously, marioiordanov wrote…</i></summary><blockquote>

as per the spec it is BlockId
</blockquote></details>

What is a block ID?

**Review by marioiordanov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/647)* status: 2 of 12 files reviewed, 4 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/papyrus_gateway/src/lib.rs` line 575 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/647#-NU0po_i1uLXtnsCeYB4:-NUW0gom6UrOC7pFy9bP:bfu5176) ([raw file](https://github.com/starkware-libs/papyrus/blob/86f6c2b294c6c4e1397d68fad5d948639269568f/crates/papyrus_gateway/src/lib.rs#L575)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What is a block ID? 
</blockquote></details>

pub enum BlockId {
    HashOrNumber(BlockHashOrNumber),
    Tag(Tag),
}

**Pull request closed without merging**
