### PR TITLE
refactor: add strk fee contract address into config

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nrpfa7y1bP8l1lVcc4H:-Nrpfa7y1bP8l1lVcc4I:b62wszg) (no related file):*
You changed only the mainnet preset file, need to change also the other presets.
Please add a test that tries to deserialize each of the preset files into `ExecutionConfigByBlock`

___
___
*[`config/execution/mainnet.json` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nrpg3nS-b7toUtPRH-h:-Nrpg3nS-b7toUtPRH-i:b-i4owbi) ([raw file](https://github.com/starkware-libs/papyrus/blob/77cf53837ebb7854a8b59786783d5965dfbae40b/config/execution/mainnet.json#L5)):*
> ```JSON
>         "0": {
>             "strk_fee_contract_address": "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
>             "fee_contract_address": "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
> ```

rename to `eth_fee_contract_address`



_Code quote:_
```JSON
fee_contract_address
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nrpfa7y1bP8l1lVcc4H:-NsOa_pa-cPUWF-FpE55:bs7wumb) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You changed only the mainnet preset file, need to change also the other presets.
Please add a test that tries to deserialize each of the preset files into `ExecutionConfigByBlock`
</blockquote></details>

Done.

___
___
*[`config/execution/mainnet.json` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nrpg3nS-b7toUtPRH-h:-NsOadGqB8wi4wjQl0DN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/77cf53837ebb7854a8b59786783d5965dfbae40b/config/execution/mainnet.json#L5)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

rename to `eth_fee_contract_address`
</blockquote></details>

Done.

**Comment by yair-starkware** [comment]
*[`crates/papyrus_execution/src/testing_instances.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbNRRF8YMEtMulKu_X:-NsbNRRF8YMEtMulKu_Y:bqegh20) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/testing_instances.rs#L39)):*
> ```XML
> }
> /// Return a vector of execution configs, using the relative path from the testing directory.
> pub fn test_get_execution_configs() -> Vec<ExecutionConfigByBlock> {
> ```

Move this code into the test function

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nrpfa7y1bP8l1lVcc4H:-NsDK9ufC-fk1uzBbdYc:b6q8ao4) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You changed only the mainnet preset file, need to change also the other presets.
Please add a test that tries to deserialize each of the preset files into `ExecutionConfigByBlock`
</blockquote></details>

Instead of preparing expected results for each preset file and 

___
___
*[`crates/papyrus_execution/src/execution_test.rs` line 667 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbO-cw6GSCpYXF9g4w:-NsbO-cw6GSCpYXF9g4x:bqqxebv) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/execution_test.rs#L667)):*
> ```XML
> /// expected.
> #[test]
> fn test_execution_configs() {
> ```

Rename - test preset execution configuration



_Code quote:_
```XML
test_execution_configs
```
___
*[`crates/papyrus_execution/src/execution_test.rs` line 695 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbO5ux9hPm8cLr8YIW:-NsbO5ux9hPm8cLr8YIX:b-iv6jml) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/execution_test.rs#L695)):*
> ```XML
>     let vm_resource_fee_cost = Arc::new(vm_resource_fee_cost);
>     vm_resource_fee_cost
> }
> ```

Please move down in the file (we try to make the less interesting code at the end of files)



_Code quote:_
```XML
fn get_vm_resource_fee_cost_first_segment() -> Arc<HashMap<String, f64>> {
    let mut vm_resource_fee_cost = HashMap::new();
    vm_resource_fee_cost.insert("n_steps".to_owned(), 0.01);
    vm_resource_fee_cost.insert("pedersen_builtin".to_owned(), 0.32);
    vm_resource_fee_cost.insert("range_check_builtin".to_owned(), 0.16);
    vm_resource_fee_cost.insert("ecdsa_builtin".to_owned(), 20.48);
    vm_resource_fee_cost.insert("bitwise_builtin".to_owned(), 0.64);
    vm_resource_fee_cost.insert("poseidon_builtin".to_owned(), 0.32);
    vm_resource_fee_cost.insert("output_builtin".to_owned(), 1.0);
    vm_resource_fee_cost.insert("ec_op_builtin".to_owned(), 10.24);
    vm_resource_fee_cost.insert("keccak_builtin".to_owned(), 20.48);

    let vm_resource_fee_cost = Arc::new(vm_resource_fee_cost);
    vm_resource_fee_cost
}
```
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbNhke5PlJjmWruoPr:-NsbNhke5PlJjmWruoPs:bo6wv5a) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/testing_instances.rs#L41)):*
> ```XML
> pub fn test_get_execution_configs() -> Vec<ExecutionConfigByBlock> {
>     let mut execution_configs = Vec::new();
>     for path in "../../config/execution".parse::<PathBuf>().unwrap().read_dir().unwrap() {
> ```

Please save this as a variable for self-documentation, fore example:
```
let preset_files_dir = "../../config/execution";
```



_Code quote:_
```XML
"../../config/execution"
```

**Review by eitanm-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-:-NsOamK_5nN8_sYBJhWA:bnfp4nl)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 667 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbO-cw6GSCpYXF9g4w:-NscYwIu6EFZq34_lykh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/execution_test.rs#L667)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename - test preset execution configuration
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/execution_test.rs` line 695 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbO5ux9hPm8cLr8YIW:-NscYe1W4Pe3BNDVxWsw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/execution_test.rs#L695)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please move down in the file (we try to make the less interesting code at the end of files)
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbNRRF8YMEtMulKu_X:-Nsc_5spD_c_RNVivtFa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/testing_instances.rs#L39)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move this code into the test function
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsbNhke5PlJjmWruoPr:-Nsc_5Qq4gzATO6PfRj-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f1934cd5393ca8d1c54d7a5b63426da9961a98d/crates/papyrus_execution/src/testing_instances.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please save this as a variable for self-documentation, fore example:
```
let preset_files_dir = "../../config/execution";
```
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 660 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmhVZK-TlSNVASYboN:-NsmhVZK-TlSNVASYboO:b-8n28zs) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L660)):*
> ```XML
> #[test]
> fn test_default_execution_config() {
>     let mut execution_config_segments = BTreeMap::new();
> ```

Why change this function?
___
*[`crates/papyrus_execution/src/execution_test.rs` line 678 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nsme6zNCczlA82FpzlU:-Nsme6zNCczlA82FpzlV:b7bu602) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L678)):*
> ```XML
>         execution_configs.push(execution_config_file);
>     }
>     assert_eq!(execution_configs.len(), 5);
> ```

Please use constant `NUM_PRESET_FILES`



_Code quote:_
```XML
 5
```
___
*[`crates/papyrus_execution/src/execution_test.rs` line 705 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nsmg_Dp3cNp9M9Qnanz:-Nsmg_DqDAs3Gx_gZjyS:b7b57n) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L705)):*
> ```XML
>             * VersionedConstants::latest_constants().gas_cost("step_gas_cost"),
>         vm_resource_fee_cost: get_vm_resource_fee_cost_first_segment(),
>     }
> ```

You can just get this from default execution config no?



_Code quote:_
```XML
fn get_default_block_execution_config() -> BlockExecutionConfig {
    BlockExecutionConfig {
        strk_fee_contract_address: contract_address!(
            "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
        ),
        eth_fee_contract_address: contract_address!(
            "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
        ),
        invoke_tx_max_n_steps: 3_000_000,
        validate_tx_max_n_steps: 1_000_000,
        max_recursion_depth: 50,
        step_gas_cost: VersionedConstants::latest_constants().gas_cost("step_gas_cost"),
        initial_gas_cost: 10_u64.pow(8)
            * VersionedConstants::latest_constants().gas_cost("step_gas_cost"),
        vm_resource_fee_cost: get_vm_resource_fee_cost_first_segment(),
    }
```
___
*[`crates/papyrus_execution/src/execution_test.rs` line 950 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmeqcWB_LEmLdeq5f7:-NsmeqcWB_LEmLdeq5f8:b7b57n) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L950)):*
> ```XML
> 
>     Arc::new(vm_resource_fee_cost)
> }
> ```

You can just get this from default execution config no?



_Code quote:_
```XML
fn get_vm_resource_fee_cost_first_segment() -> Arc<HashMap<String, f64>> {
    let mut vm_resource_fee_cost = HashMap::new();
    vm_resource_fee_cost.insert("n_steps".to_owned(), 0.01);
    vm_resource_fee_cost.insert("pedersen_builtin".to_owned(), 0.32);
    vm_resource_fee_cost.insert("range_check_builtin".to_owned(), 0.16);
    vm_resource_fee_cost.insert("ecdsa_builtin".to_owned(), 20.48);
    vm_resource_fee_cost.insert("bitwise_builtin".to_owned(), 0.64);
    vm_resource_fee_cost.insert("poseidon_builtin".to_owned(), 0.32);
    vm_resource_fee_cost.insert("output_builtin".to_owned(), 1.0);
    vm_resource_fee_cost.insert("ec_op_builtin".to_owned(), 10.24);
    vm_resource_fee_cost.insert("keccak_builtin".to_owned(), 20.48);

    Arc::new(vm_resource_fee_cost)
}

fn get_vm_resource_fee_cost_second_segment() -> Arc<HashMap<String, f64>> {
    let mut vm_resource_fee_cost = HashMap::new();
    vm_resource_fee_cost.insert("n_steps".to_owned(), 0.005);
    vm_resource_fee_cost.insert("pedersen_builtin".to_owned(), 0.16);
    vm_resource_fee_cost.insert("range_check_builtin".to_owned(), 0.08);
    vm_resource_fee_cost.insert("ecdsa_builtin".to_owned(), 10.24);
    vm_resource_fee_cost.insert("bitwise_builtin".to_owned(), 0.32);
    vm_resource_fee_cost.insert("poseidon_builtin".to_owned(), 0.16);
    vm_resource_fee_cost.insert("output_builtin".to_owned(), 0.5);
    vm_resource_fee_cost.insert("ec_op_builtin".to_owned(), 5.12);
    vm_resource_fee_cost.insert("keccak_builtin".to_owned(), 10.24);

    Arc::new(vm_resource_fee_cost)
}
```
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmfXyFCWpBk8nbREGN:-NsmfXyFCWpBk8nbREGO:bkbqhi8) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/testing_instances.rs#L38)):*
> ```XML
>     let execution_config_file = PathBuf::from("../../config/execution/mainnet.json");
>     execution_config_file.try_into().unwrap()
> }
> ```

In a separate PR please make this lazy_static too to make tests faster (we will read the file once instead of multiple times)



_Code quote:_
```XML
pub fn test_get_default_execution_config() -> ExecutionConfigByBlock {
    let execution_config_file = PathBuf::from("../../config/execution/mainnet.json");
    execution_config_file.try_into().unwrap()
}
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 660 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmhVZK-TlSNVASYboN:-NsqvhKAC1d9gCdZVNym:byav751) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L660)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why change this function?
</blockquote></details>

implemented a helper function to reduce duplicative code between tests
___
*[`crates/papyrus_execution/src/execution_test.rs` line 705 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nsmg_Dp3cNp9M9Qnanz:-NsqvFmJApJmWGasx6R5:biehnun) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L705)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can just get this from default execution config no?
</blockquote></details>

see comment on testing against config
___
*[`crates/papyrus_execution/src/execution_test.rs` line 950 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmeqcWB_LEmLdeq5f7:-NsquqWhE09CVoz3vBvm:bk5y9o3) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L950)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can just get this from default execution config no?
</blockquote></details>

we are testing that the execution config loaded correctly against this. otherwise we would be testing it against itself

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-NsmfXyFCWpBk8nbREGN:-NsqwCdZ21-_y0DS5EJU:bb7m07t) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/testing_instances.rs#L38)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In a separate PR please make this lazy_static too to make tests faster (we will read the file once instead of multiple times)
</blockquote></details>

okay

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 678 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-Nsme6zNCczlA82FpzlU:-Nsr0m8kC3ueXfE_H6mo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b0b027751ed6f926218b5c82ec3f415a608aba16/crates/papyrus_execution/src/execution_test.rs#L678)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use constant `NUM_PRESET_FILES`
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750#-:-NtAegc9DPfstDpofVQ-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1750)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

**Pull request merged**
