### PR TITLE
feat(common): calculate hash for only-query transactions

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1488)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r2, 1 of 2 files at r3, 11 of 11 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1488)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/lib.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-NkywdXR2U7GI3Eu2MZq:-NkywdXR2U7GI3Eu2MZr:b2bj45g) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5fd3de8a1afd8766576cca86f44daa2ff846804/crates/papyrus_common/src/lib.rs#L21)):*
> ```XML
> pub struct TransactionOptions {
>     /// Transaction that shouldn't be broadcasted to StarkNet. For example, users that want to
>     /// test the execution of a transaction without revealing the signature.
> ```

Is this the go-to example in other places (blockifier, starknet, etc.)? It isn't exactly clear
___
*[`crates/papyrus_common/src/lib.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz1jom-MnfFzqu9VLc:-Nkz1jom-MnfFzqu9VLd:bx20vtn) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_common/src/lib.rs#L17)):*
> ```XML
> }
> 
> #[derive(Copy, Clone, Debug, Eq, PartialEq, Default)]
> ```

Consider adding a TODO for the missing fields. Otherwise whoever sees this might think this struct is unnecessary
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 665 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz3-il6TKUlOJnFICO:-Nkz3-il6TKUlOJnFICP:btdfs11) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_common/src/transaction_hash.rs#L665)):*
> ```XML
>     if transaction_options.only_query {
>         let query_only_bit: FieldElement =
>             stark_felt!("0x100000000000000000000000000000000").into();
> ```

Consider constructing from bytes for readability
___
*[`crates/papyrus_execution/src/execution_test.rs` line 864 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz3XbF1C4GLkQ6ow32:-Nkz3XbF1C4GLkQ6ow33:b350dy0) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_execution/src/execution_test.rs#L864)):*
> ```XML
> 
> #[test]
> fn simulate_with_query_bit() {
> ```

Rename to `simulate_with_query_bit_outputs_same_as_no_query_bit

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1488)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/lib.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-NkywdXR2U7GI3Eu2MZq:-Nkz4_-m00DO7CDxx40D:b-rsfcca) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5fd3de8a1afd8766576cca86f44daa2ff846804/crates/papyrus_common/src/lib.rs#L21)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is this the go-to example in other places (blockifier, starknet, etc.)? It isn't exactly clear
</blockquote></details>

This is the main usage of this option.
Improved the doc, WDYT?
___
*[`crates/papyrus_common/src/lib.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz1jom-MnfFzqu9VLc:-Nkz4IAC9FhHXVZt5tRO:be64qcs) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_common/src/lib.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider adding a TODO for the missing fields. Otherwise whoever sees this might think this struct is unnecessary
</blockquote></details>

There are no other fields.
Do you think passing a boolean is better?
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 665 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz3-il6TKUlOJnFICO:-Nkz5nZC7S-BSUj-UJVC:b-oxr7x9) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_common/src/transaction_hash.rs#L665)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider constructing from bytes for readability
</blockquote></details>

The bytes repr of felts is not straightforward
___
*[`crates/papyrus_execution/src/execution_test.rs` line 864 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz3XbF1C4GLkQ6ow32:-Nl2LL9P75wV8y7ALcOI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_execution/src/execution_test.rs#L864)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to `simulate_with_query_bit_outputs_same_as_no_query_bit
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1488)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_common/src/lib.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-NkywdXR2U7GI3Eu2MZq:-Nl3AWpg7f9F_CixrcgD:bb7k0qh) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5fd3de8a1afd8766576cca86f44daa2ff846804/crates/papyrus_common/src/lib.rs#L21)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is the main usage of this option.
Improved the doc, WDYT?
</blockquote></details>

lgtm
___
*[`crates/papyrus_common/src/lib.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-Nkz1jom-MnfFzqu9VLc:-Nl3AYZY8rBZbH16tvX0:b6d17d4) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ffdbe4c6755f0a5961b8456a102d4706193b524/crates/papyrus_common/src/lib.rs#L17)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There are no other fields.
Do you think passing a boolean is better?
</blockquote></details>

WDYT about converting this to an enum then?

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1488#-:-Nl3Dc8CCzhn1z4F99w4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
