### PR TITLE
feat(network): add conversion between protobuf Class and sn api

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_common/src/pending_classes.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F-54QADTzoNYp4t84:-O-F-54QADTzoNYp4t85:b-6skrrv) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_common/src/pending_classes.rs#L39)):*
> ```XML
>     ContractClass(ContractClass),
> }
> pub struct Class {
> ```

Why do you add this? domain is always L1
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F40hmEzb3bSjTZf9X:-O-F40hmEzb3bSjTZf9Y:b-9qejcc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L56)):*
> ```XML
>     type Error = ProtobufConversionError;
>     fn try_from(value: protobuf::Cairo0Class) -> Result<Self, Self::Error> {
>         let mut entry_points_by_type: HashMap<
> ```

I think you can remove the type hint. Could you try and see if the code compiles?
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F69CL2g0W9WTaDuII:-O-F69CL2g0W9WTaDuIJ:b-cr4nit) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L61)):*
> ```XML
>         > = HashMap::new();
> 
>         entry_points_by_type.insert(
> ```

These should happen only if the corresponding field is non-empty. Same for Cairo1Class
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F47e_CF8_uqOrSM0c:-O-F47e_CF8_uqOrSM0d:b-ya81ng) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L136)):*
> ```XML
>             value.program.into_iter().map(Felt::try_from).collect::<Result<Vec<_>, _>>()?;
> 
>         let mut entry_points_by_type: HashMap<state::EntryPointType, Vec<state::EntryPoint>> =
> ```

Same as above
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F6G2H-hkf4BYm9m7j:-O-F6G2H-hkf4BYm9m7k:b-f8oyjw) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L140)):*
> ```XML
>         entry_points_by_type.insert(
>             state::EntryPointType::Constructor,
>             value
> ```

```
value
                .entry_points
                .clone()
                .ok_or(ProtobufConversionError::MissingField {
                    field_description: "Cairo1Class::entry_points",
                })?
```
extract this to a variable at the start of the function

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F7NTb45rQ7D78onLF:-O-F7NTb45rQ7D78onLG:bp2sx05) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

What about conversion from DataOrFin<Class> to ClassesResponse?
Also add a call to the macro of vec_u8 on that

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F7NTb45rQ7D78onLF:-O-F7VxT9sq660_25NJI:b-b6r6iw) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What about conversion from DataOrFin<Class> to ClassesResponse?
Also add a call to the macro of vec_u8 on that
</blockquote></details>

This can be done in a future PR if you prefer :)

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)* status: all files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/pending_classes.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F-54QADTzoNYp4t84:-O-FGxqO8mogS7amkQtE:b8hnas9) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_common/src/pending_classes.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you add this? domain is always L1
</blockquote></details>

thats right, Done
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F7NTb45rQ7D78onLF:-O-FH2h29klFkfbGoS26:b-8cf0ri) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This can be done in a future PR if you prefer :)
</blockquote></details>

Done in this PR
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F40hmEzb3bSjTZf9X:-O-FH6kB6ghvri6gPH2n:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L56)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think you can remove the type hint. Could you try and see if the code compiles?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F69CL2g0W9WTaDuII:-O-FH7yW2O-aKVqU4-hv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L61)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These should happen only if the corresponding field is non-empty. Same for Cairo1Class
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F47e_CF8_uqOrSM0c:-O-FH8Ob0cRYxX9wlzev:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L136)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F6G2H-hkf4BYm9m7j:-O-FH9tNDUkL4_UXEOQb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L140)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

```
value
                .entry_points
                .clone()
                .ok_or(ProtobufConversionError::MissingField {
                    field_description: "Cairo1Class::entry_points",
                })?
```
extract this to a variable at the start of the function
</blockquote></details>

Done.

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F7NTb45rQ7D78onLF:-O-FMa6t74b_QkYfzYC4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_protobuf/src/converters/class.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Call the auto_impl macro
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-FKYQl-vIl7CiV8NIH:-O-FMb2b5-ZUj1wj-j7M:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ca3043c3080b921baa4f8013bcaf10e0a480162/crates/papyrus_protobuf/src/converters/class.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

A general conversion from i32 to u32 can fail. Change this message to "volition_domain_to_enum_int output should be convertible to u32"
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/pending_classes.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-O-F-54QADTzoNYp4t84:-O-FMaef8luE_hx0V14K:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f65a75b9249acea888a0b78e983c8b2aaa176fd6/crates/papyrus_common/src/pending_classes.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase, don't comment out
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2100#-:-O-FNk-x0vzobk4ZGg7J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
