### PR TITLE
chore: add papyrus installation script

### PR DESCRIPTION
**Pull request by AlonStark**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [:heavy_check_mark:] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently installations are done via ``helm upgrade`` and do not automatically deploy a grafana dashboard

Issue Number: N/A

## What is the new behavior?

Instead of directly installing via ``helm upgrade`` we can now use this script which will also tokenize and deploy a grafana dashboard if the deployer wants to have metrics.

-

## Does this introduce a breaking change?

- [ ] Yes
- [:heavy_check_mark: ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @AlonStark)

___
*[`install_papyrus.py` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKLZpL0FZUxJOCdN53:-NpKLZpL0FZUxJOCdN54:b-vhu70n) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L1)):*
> ```Python
> import argparse
> ```

Please move to deployments. 
___
*[`install_papyrus.py` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKO9wN2kj2koBKrKH-:-NpKO9wO9C_Ry3MwcW8q:b-5e0dje) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L13)):*
> ```Python
>     parser = argparse.ArgumentParser(description="Install Papyrus node.")
>     parser.add_argument(
>         "--pod_name", type=str, required=True, help="Name for the deployed pod."
> ```

This is used as the release name, please change accordingly 



_Code quote:_
```Python
--pod_name
```
___
*[`install_papyrus.py` line 29 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKOmTzC-dqoh1jjWKu:-NpKOmTzC-dqoh1jjWKv:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L29)):*
> ```Python
>         default=False,
>         help="Enabling this option will also deploy a grafana deashboard with the pod.",
>     )
> ```

Consider



_Suggestion:_
```Python
    parser.add_argument(
        "--with_alerts",
        action="store_true",
        default=False,
        help="Enabling this option will also deploy a grafana alerts deashboard with the pod.",
    )
```
___
*[`install_papyrus.py` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKQTH4-OcOaybXBTYf:-NpKQTH4-OcOaybXBTYg:bv7maf5) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L52)):*
> ```Python
>             line.replace("NAMESPACE", namespace).replace("${DS_PROMETHEUS}", prometheus_uid))
>     grafana_dashboard = "".join(line for line in grafana_dashboard_lines)
>     grafana_deployment_file = open(GRAFANA_DESTINATION_FILE_PATH, "r+")
> ```

Should probably be `w`



_Code quote:_
```Python
r+
```
___
*[`install_papyrus.py` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKP42Y2X-WjqbbCXuC:-NpKP42Y2X-WjqbbCXuD:b-580qqy) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L61)):*
> ```Python
>     args = parse_command_line_args()
>     print(args)
>     cmd = f"helm upgrade --install {args.pod_name} deployments/helm/ --namespace {args.namespace}"
> ```

This assumes you run it from a specific path. Please document.
And consider



_Suggestion:_
```Python
 ./deployments/helm/
```
___
*[`deployments/helm/Monitoring/alerts_grafana.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKM5KfBcFjngmEXZJM:-NpKM5KfBcFjngmEXZJN:b-n6d6dn) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/deployments/helm/Monitoring/alerts_grafana.json#L1)):*
> ```JSON
> {
> ```

Please remove
___
*[`deployments/helm/Monitoring/grafana.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKMDWl1byINPYHTym9:-NpKMDWl1byINPYHTymA:b-n6d6dn) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/deployments/helm/Monitoring/grafana.json#L0)):*
Please remove
___
*[`Monitoring/alerts_grafana.json` line 7764 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKMmvbBBnR2jdcUOmP:-NpKMmvbBBnR2jdcUOmQ:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/Monitoring/alerts_grafana.json#L7764)):*
> ```JSON
>   "timepicker": {},
>   "timezone": "",
>   "title": "NAMESPACE",
> ```

Consider



_Suggestion:_
```JSON
"NAMESPACE-alerts"
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: all files reviewed, 9 unresolved discussions (waiting on @AlonStark)

___
*[`install_papyrus.py` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKRIaA1u-u6L08SroR:-NpKRIaB9YfPhEiU12PP:b-tmf22i) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L10)):*
> ```Python
> 
> 
> def parse_command_line_args():
> ```

Please add a todo (or just implement) to add deploy monitoring dashboard (not alerts)



_Code quote:_
```Python
ef parse_command_line_args():
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: all files reviewed, 7 unresolved discussions (waiting on @AlonStark)

___
*[`deployments/helm/values.yaml` line 11 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-hSwEd0hymWdX85j:-NpV-hSwEd0hymWdX85k:bjhwqjs) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L11)):*
> ```YAML
> 
> # Ethereum node URL. A value for this variable is mandatory.
> base_layer_node_url: https://sepolia.infura.io/v3/02d1979ac909443b938cfc740f19708f
> ```

Please remove and make sure to revoke the token



_Code quote:_
```YAML
https://sepolia.infura.io/v3/02d1979ac909443b938cfc740f19708f
```
___
*[`deployments/helm/values.yaml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-vcq0JLjNfu2aMi4:-NpV-vcq0JLjNfu2aMi5:b-81g94b) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L16)):*
> ```YAML
>   # possible values: "mainnet.json", "goerli_testnet.json", "goerli_integration.json",
>   # "sepolia_testnet" and "sepolia_integration".
>   preset: sepolia_testnet
> ```

Please revert



_Code quote:_
```YAML
 sepolia_testnet
```
___
*[`deployments/helm/values.yaml` line 23 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-o3h2R5nJdp9aJzp:-NpV-o3h2R5nJdp9aJzq:b8b4ffc) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L23)):*
> ```YAML
>   image:
>     repository: ghcr.io/starkware-libs/papyrus
>     tag: 0.2.0-rc5
> ```

Why rc5?
___
*[`deployments/helm/values.yaml` line 28 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV00l4EEkAg4A3aACh:-NpV00l4EEkAg4A3aACi:bn2yo8f) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L28)):*
> ```YAML
>   # Optional - nodeSelector
>   nodeSelector:
>     role: starkdex-service
> ```

Please revert
This file is a template for public usage, should not contain Starkware related data
Same below



_Code quote:_
```YAML
role: starkdex-service
```
___
*[`install_papyrus.py` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKP42Y2X-WjqbbCXuC:-NpUz0y49gut4Zckj_Dh:b-qwa3vr) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L61)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This assumes you run it from a specific path. Please document.
And consider
</blockquote></details>

Consider doing so in a way that help the user in case of an error (maybe the ArgumentParser description)

**Review by AlonStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`deployments/helm/values.yaml` line 11 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-hSwEd0hymWdX85j:-NpV266DCgoVByVGhgFn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove and make sure to revoke the token
</blockquote></details>

Done.
___
*[`deployments/helm/values.yaml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-vcq0JLjNfu2aMi4:-NpV25dK-YZRn3joLWVX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L16)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.
___
*[`deployments/helm/values.yaml` line 23 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV-o3h2R5nJdp9aJzp:-NpV25S-78fxkiDP8uXu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L23)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why rc5?
</blockquote></details>

Done.
___
*[`deployments/helm/values.yaml` line 28 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpV00l4EEkAg4A3aACh:-NpV24e52AnW5FcMV_HC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc25ad358ff80c476547f77cdee7b7cff19ba940/deployments/helm/values.yaml#L28)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please revert
This file is a template for public usage, should not contain Starkware related data
Same below
</blockquote></details>

Done.
___
*[`deployments/helm/Monitoring/alerts_grafana.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKM5KfBcFjngmEXZJM:-NpUuMVF6XSM4hSXebPF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/deployments/helm/Monitoring/alerts_grafana.json#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`deployments/helm/Monitoring/grafana.json` line  at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKMDWl1byINPYHTym9:-NpUuNNU1UcMxPQ4HyZZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/deployments/helm/Monitoring/grafana.json#L)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`install_papyrus.py` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKLZpL0FZUxJOCdN53:-NpUtE3879ivnydfSDwo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move to deployments.
</blockquote></details>

Done.
___
*[`install_papyrus.py` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKO9wN2kj2koBKrKH-:-NpUtV7M-ioUs5qRf09X:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L13)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is used as the release name, please change accordingly
</blockquote></details>

Done.
___
*[`install_papyrus.py` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKQTH4-OcOaybXBTYf:-NpUtyT_D6AI1ivJk-is:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L52)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Should probably be `w`
</blockquote></details>

Done.
___
*[`install_papyrus.py` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-NpKP42Y2X-WjqbbCXuC:-NpUu9XFBwKeuAq5PIWG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/db45ad65866bcaffd7f9bac2f38f7044921c3177/install_papyrus.py#L61)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This assumes you run it from a specific path. Please document.
And consider
</blockquote></details>

Done.

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonStark)

**Review by AlonStark — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 7 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638#-:-NpxkJnHAxBcacBokgcf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonStark)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonStark)

**Pull request merged**
