### PR TITLE
Add README explanation on how to limit the memory usage of the node

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2K7fN9MOYyPWcw2TO:-NR2K7fO9-R3M8pHMX_R:bfla8ur) (no related file):*
I think this PR should also include a minimum recommended memory. 

___
___
*[`README.md` line 96 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2HS048T5_59sIktcs:-NR2HS048T5_59sIktct:bgcjyic) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L96)):*
> ```Markdown
> ```
> 
> ### Notes
> ```

This relates to the command line, IMO use either `####` or no `#` at all.



_Code quote:_
```Markdown
### Notes
```
___
*[`README.md` line 106 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2IMQP9-I5oRi5wdRv:-NR2IMQP9-I5oRi5wdRw:b-yz03jb) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L106)):*
> ```Markdown
> Make sure to periodically pull the latest image and re-run the node.
> 
> ### Memory usage
> ```

This is not part of 
`## Running papyrus with Docker`



_Code quote:_
```Markdown
### Memory usage
```
___
*[`README.md` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NQy6ThLDYxn1TQRRMFP:-NQy6ThLDYxn1TQRRMFQ:bazwin6) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L107)):*
> ```Markdown
> 
> ### Memory usage
> By default, the node will use all the RAM memory it can in order to cache the storage.
> ```

the memory is redundant



_Code quote:_
```Markdown
RAM memory
```
___
*[`README.md` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2IrdS0gUEJa3btRtd:-NR2IrdS0gUEJa3btRte:bgozh6l) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L107)):*
> ```Markdown
> 
> ### Memory usage
> By default, the node will use all the RAM memory it can in order to cache the storage.
> ```

`papyrus` node



_Code quote:_
```Markdown
node
```
___
*[`README.md` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2JAIm6UMetDKcaUV4:-NR2JAIm6UMetDKcaUV5:bv99586) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L107)):*
> ```Markdown
> 
> ### Memory usage
> By default, the node will use all the RAM memory it can in order to cache the storage.
> ```

IMO this makes it sound as if there exists a non-default node configuration for that.



_Code quote:_
```Markdown
By default
```
___
*[`README.md` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2JPRk6OGl-wURJXr1:-NR2JPRk6OGl-wURJXr2:bhacola) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L107)):*
> ```Markdown
> 
> ### Memory usage
> By default, the node will use all the RAM memory it can in order to cache the storage.
> ```

Consider:
The `papyrus` node utilizes a memory-mapped file as its storage medium. The allocated physical memory for the file mapping will not be evicted, as long as the kernel does not experience memory pressure issues. Consequently, the node consumes a large amount of memory, utilizing all the available RAM.



_Code quote:_
```Markdown
By default, the node will use all the RAM memory it can in order to cache the storage.
```
___
*[`README.md` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2Jiz-5u1UTq59valr:-NR2Jiz-5u1UTq59vals:bkj58p2) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L111)):*
> ```Markdown
> If you're not running any other applications on your machine, this is the recommended behavior.
> 
> Otherwise, you can limit the node's memory usage by running it in a container with limited memory.
> ```

with a limited



_Code quote:_
```Markdown
with limited memory
```
___
*[`README.md` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2JsHD6g4oGV6kNn9R:-NR2JsHD6g4oGV6kNn9S:b-l1p0q7) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L113)):*
> ```Markdown
> Otherwise, you can limit the node's memory usage by running it in a container with limited memory.
> 
> This can be done by adding the flag `--memory 1g` (For 1GB limitation) to the command above.
> ```

for a 1GB



_Code quote:_
```Markdown
For 1GB
```
___
*[`README.md` line 124 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2K1cB5RqFdxwPoLP8:-NR2K1cB5RqFdxwPoLP9:bn0qb4p) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L124)):*
> ```Markdown
> ```
> 
> For more information, look at [Docker's documentation](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)
> ```

Consider `see` instead and end the sentence with a full stop (period)



_Code quote:_
```Markdown
look at
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2K7fN9MOYyPWcw2TO:-NR2lxpICK4eFmg9J9uh:bk34qg4) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I think this PR should also include a minimum recommended memory. 
</blockquote></details>

What such minimum should be? We can throw a number out of feeling but I don't think that's a good idea

___
___
*[`README.md` line 106 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2IMQP9-I5oRi5wdRv:-NR2m7is3bXCg5pgf4D3:b8b25vt) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L106)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is not part of 
`## Running papyrus with Docker`
</blockquote></details>

Why not?
___
*[`README.md` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2JPRk6OGl-wURJXr1:-NR2mnMhEwPKkqNULYuV:b-5mzqfl) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L107)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider:
The `papyrus` node utilizes a memory-mapped file as its storage medium. The allocated physical memory for the file mapping will not be evicted, as long as the kernel does not experience memory pressure issues. Consequently, the node consumes a large amount of memory, utilizing all the available RAM.
</blockquote></details>

I think that the sentence representing the problem should be as short and simple as possible so that the reader won't skip this paragraph. The main point that we want to pass to the reader here is that the node uses all the RAM it can, not how our storage is built

**Comment by dan-starkware** [comment]
*[`README.md` line 106 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/558#-NR2IMQP9-I5oRi5wdRv:-NR2u9wb7hVBnIrnk3TP:b-ugaz0q) ([raw file](https://github.com/starkware-libs/papyrus/blob/3ed70ce2442f49e6137c1a39acc67744b463f1af/README.md#L106)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

It applies also for running the node not in a container

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558#-:-NR3697XDKlxTfCEDglD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by dan-starkware — APPROVED** [review]

**Review by ShahakShama — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/558)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
