### PR TITLE
fix: use unchecked functions when calling BlockNumber::next

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 23 of 29 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805)* status: all files reviewed, 6 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqr3b112JPt7Oz1sGt:-Nsqr3b112JPt7Oz1sGu:bwfhy74) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/header.rs#L301)):*
> ```XML
> 
>         // Reverts only the last header.
>         if current_header_marker != block_number.unchecked_next() {
> ```

I think this should be checked (the storage crate is external)
___
*[`crates/papyrus_storage/src/header.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqr9MKAnmoU1YVDH1S:-Nsqr9MKAnmoU1YVDH1T:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/header.rs#L320)):*
> ```XML
>         // TODO(shahak): Fix code duplication with get_starknet_version.
>         let mut cursor = starknet_version_table.cursor(&self.txn)?;
>         cursor.lower_bound(&block_number.unchecked_next())?;
> ```

Same here
___
*[`crates/papyrus_storage/src/body/mod.rs` line 274 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqsv2s-COLSEmmcpUv:-Nsqsv2s-COLSEmmcpUw:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/body/mod.rs#L274)):*
> ```XML
> 
>         cursor.lower_bound(&TransactionIndex(
>             block_number.unchecked_next(),
> ```

Same here
___
*[`crates/papyrus_storage/src/body/mod.rs` line 360 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-NsqszU4EeV27La4EEaY:-NsqszU4EeV27La4EEaZ:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/body/mod.rs#L360)):*
> ```XML
>         // Assert that body marker equals the reverted block number + 1
>         let current_header_marker = self.get_body_marker()?;
>         if current_header_marker != block_number.unchecked_next() {
> ```

Same here
___
*[`crates/papyrus_storage/src/state/mod.rs` line 531 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqt4SE4W1Ams1L7NjN:-Nsqt4SE4W1Ams1L7NjO:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/state/mod.rs#L531)):*
> ```XML
> 
>         // Reverts only the last state diff.
>         if current_state_marker != block_number.unchecked_next() {
> ```

Same here
___
*[`crates/papyrus_storage/src/state/mod.rs` line 546 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqt6UXBvheAFR0Yn-2:-Nsqt6UXBvheAFR0Yn-3:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/state/mod.rs#L546)):*
> ```XML
>         let compiled_classes_marker =
>             markers_table.get(&self.txn, &MarkerKind::CompiledClass)?.unwrap_or_default();
>         if compiled_classes_marker == block_number.unchecked_next() {
> ```

Same here

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805)* status: 27 of 31 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_storage/src/header.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqr3b112JPt7Oz1sGt:-Nsr-nNPE0TkQPJtRK9o:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/header.rs#L301)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this should be checked (the storage crate is external)
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/header.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqr9MKAnmoU1YVDH1S:-Nsr07BaBjXiOhwArf_V:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/header.rs#L320)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 274 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqsv2s-COLSEmmcpUv:-NsqwOeYC0yqxSv52ppd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/body/mod.rs#L274)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/mod.rs` line 360 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-NsqszU4EeV27La4EEaY:-NsqybY86BwDSvZpJYKG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/body/mod.rs#L360)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 531 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqt4SE4W1Ams1L7NjN:-Nsqz-rK7PKS5O2XhHmV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/state/mod.rs#L531)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 546 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-Nsqt6UXBvheAFR0Yn-2:-NsqzHhu-RsDLeNkMe6x:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/a90784aa0f6d2d58a6736dde4939b936c52e9c33/crates/papyrus_storage/src/state/mod.rs#L546)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-:-NsriwSj2kbfjK3PTpDB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-:-Nsrs7nxCYmNq_34DLH5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_p2p_sync/src/stream_factory.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1805#-NsrqlKf9vnjtvj0vtPp:-NsrqlKf9vnjtvj0vtPq:b-wi2fzj) ([raw file](https://github.com/starkware-libs/papyrus/blob/5413dd54e621afa110a8ea23b03f260b6fafc0ae/crates/papyrus_p2p_sync/src/stream_factory.rs#L86)):*
> ```XML
>                         info!("Added block {}.", current_block_number);
>                     }
>                     current_block_number = match current_block_number.next() {
> ```

You can do unchecked_next here. This can be done in a future PR (I can do it)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
