### PR TITLE
fix(network): if all peers are blocked, act as if there are no peers

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pExAx8wWQycmfzYRZ:-O1pExAx8wWQycmfzYR_:b-p20ugy) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L187)):*
> ```XML
>         if let Some(sleep_future) = &mut self.sleep_waiting_for_unblocked_peer {
>             pin_mut!(sleep_future);
>             ready!(sleep_future.poll(cx));
> ```

Minimize macro usage.



_Suggestion:_
```XML
            ready!(sleep_future.as_mut().poll(cx));
```
___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pFGxX-dSRViYp7WpM:-O1pFGxX-dSRViYp7WpN:b1snwb0) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L193)):*
> ```XML
>         }
>         self.sleep_waiting_for_unblocked_peer = None;
>         self.pending_events.pop().map(Poll::Ready).unwrap_or(Poll::Pending)
> ```

Didn't we do this at the beginning? At this point aren't we basically guaranteed to have nothing ready?



_Code quote:_
```XML
        self.pending_events.pop().map(Poll::Ready).unwrap_or(Poll::Pending)
```
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pFlAA96wcfJHzlhj3:-O1pFlAA96wcfJHzlhj4:bcd7zqw) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L63)):*
> ```XML
>             target_num_for_peers: 100,
>             // 1 year.
>             blacklist_timeout: Duration::from_secs(3600 * 24 * 365),
> ```

Is this the config you discussed with me and Dan about what happens if a node goes down? If so, what is the condition for blacklist? We want to be able to recover from network failures (look identical to the node crashing). I don't want a severe punishment for "honest failure".

Can we make this configurable?



_Code quote:_
```XML
            // 1 year.
            blacklist_timeout: Duration::from_secs(3600 * 24 * 365),
```
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q8BAF98oqOcECykpy:-O1q8BAF98oqOcECykpz:bm6j3s2) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L83)):*
> ```XML
>             peers_pending_dial_with_sessions: HashMap::new(),
>             sessions_received_when_no_peers: Vec::new(),
>             sleep_waiting_for_unblocked_peer: None,
> ```

How do we use this? I only see it being set.



_Code quote:_
```XML
            sleep_waiting_for_unblocked_peer: None,
```
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q9tif8_9WrsBJXIAM:-O1q9tif8_9WrsBJXIAN:b-364q4i) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L104)):*
> ```XML
> 
>     // TODO(shahak): Remove return value and use events in tests.
>     fn assign_peer_to_session(&mut self, outbound_session_id: OutboundSessionId) -> Option<PeerId> {
> ```

This fn doesn't fit all at once onto my screen :( . WDYT about splitting it. Maybe the `peer.map` below can be broken out?



_Code quote:_
```XML
    fn assign_peer_to_session(&mut self, outbound_session_id: OutboundSessionId) -> Option<PeerId> {
```
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q_4AU7NXSzJ6dpcPQ:-O1q_4AU7NXSzJ6dpcPR:b-k29xy8) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L152)):*
> ```XML
>             peer_id == event_peer_id &&
>             connection_id == event_connection_id
>     );
> ```

This automatically checks the field values if you don't put `_` And in the test below.



_Suggestion:_
```XML
    assert_matches!(
        peer_manager.next().await.unwrap(),
        ToSwarm::GenerateEvent(ToOtherBehaviourEvent::SessionAssigned {
            outbound_session_id,
            peer_id,
            connection_id,
        })
    );
```
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1qh38jE5ZLDA2nNt_K:-O1qh38jE5ZLDA2nNt_L:b-yf2hvo) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L203)):*
> ```XML
>             );
>         }
>     }
> ```

I don't understand how the test you wrote shows what the comment writes. From looking at the test why couldn't we just select into the second branch immediately and complete. When I see this description I imagine:
1. fail to assign the session
2. BLOCKED_UNTIL completes
3. succeed in assigning the session
(IDK if what I put actually is correct but I tried to encapsulate the above in code)



_Suggestion:_
```XML
    // After BLOCKED_UNTIL has passed, the peer manager can assign the session.
    tokio::time::pause();
    assert!(tokio::time::timeout(TIMEOUT, peer_manager.next()).await.is_err());
    tokio::time::advance(BLOCKED_UNTIL).await;
    tokio::time::resume();
    let event = tokio::time::timeout(TIMEOUT, peer_manager.next()).await.unwrap().unwrap();
    assert_matches!(
        event,
        ToSwarm::GenerateEvent(ToOtherBehaviourEvent::SessionAssigned {
            outbound_session_id,
            peer_id,
            connection_id,
        })
    );
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pExAx8wWQycmfzYRZ:-O1tz3JyEe6VXOURCD9g:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L187)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Minimize macro usage.
</blockquote></details>

Done
___
*[`crates/papyrus_network/src/peer_manager/behaviour_impl.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pFGxX-dSRViYp7WpM:-O1twHqSCVUWPfrH5Rl0:byzsyex) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/behaviour_impl.rs#L193)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Didn't we do this at the beginning? At this point aren't we basically guaranteed to have nothing ready?
</blockquote></details>

assign_peer_to_session can add events to the queue
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1pFlAA96wcfJHzlhj3:-O1trEhk0Jxe1zmmL-Vy:b2gom6h) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L63)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is this the config you discussed with me and Dan about what happens if a node goes down? If so, what is the condition for blacklist? We want to be able to recover from network failures (look identical to the node crashing). I don't want a severe punishment for "honest failure".

Can we make this configurable?
</blockquote></details>

Yes, Any bad behaviour.
There's a TODO for making this configurable somewhere else in the code
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q8BAF98oqOcECykpy:-O1twlTY4s4ObLEQAzM8:bxystfu) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L83)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

How do we use this? I only see it being set.
</blockquote></details>

in the poll, in behaviour_impl.rs
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q9tif8_9WrsBJXIAM:-O1tz6GD6-4t71Nar9qq:bxs6glv) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L104)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This fn doesn't fit all at once onto my screen :( . WDYT about splitting it. Maybe the `peer.map` below can be broken out?
</blockquote></details>

I don't know if this code will stay with us in the long run, so I prefer not to put too much effort onto it. Plus, we have bigger things to do. For now I've putted a TODO
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q_4AU7NXSzJ6dpcPQ:-O1trS_D0tnbKqQnv-M-:b-41whap) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L152)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This automatically checks the field values if you don't put `_` And in the test below.
</blockquote></details>

No it doesn't. it hides the current values
The following test passes even though according to what you said it shouldn't:
```
#[test]
fn foo_test() {
    #[derive(std::fmt::Debug)]
    enum Foo {
        A { x: u32, y: u32 },
        B,
    }

    let x = 1;
    let y = 2;
    let foo = Foo::A { x: 2, y: 3 };
    assert_matches!(foo, Foo::A { x, y })
}
```
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1qh38jE5ZLDA2nNt_K:-O1tyuETDci2wV0mbi8Q:b4excek) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L203)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't understand how the test you wrote shows what the comment writes. From looking at the test why couldn't we just select into the second branch immediately and complete. When I see this description I imagine:
1. fail to assign the session
2. BLOCKED_UNTIL completes
3. succeed in assigning the session
(IDK if what I put actually is correct but I tried to encapsulate the above in code)
</blockquote></details>

1. is tested above, 2. is tested in the first select arm, and 3. is tested in the second select arm

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q9tif8_9WrsBJXIAM:-O1ujuxW0qLkQPg3OCTJ:b-kxxe99) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/mod.rs#L104)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't know if this code will stay with us in the long run, so I prefer not to put too much effort onto it. Plus, we have bigger things to do. For now I've putted a TODO
</blockquote></details>

I agree we have bigger things, but splitting a function isn't a big task. But if you don't expect it to stay then fine the TODO is enough.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q_4AU7NXSzJ6dpcPQ:-O1ukWRZ0QnG0Uqwt5Ma:b-sk1rcx) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L152)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No it doesn't. it hides the current values
The following test passes even though according to what you said it shouldn't:
```
#[test]
fn foo_test() {
    #[derive(std::fmt::Debug)]
    enum Foo {
        A { x: u32, y: u32 },
        B,
    }

    let x = 1;
    let y = 2;
    let foo = Foo::A { x: 2, y: 3 };
    assert_matches!(foo, Foo::A { x, y })
}
```
</blockquote></details>

Wow this is incredibly confusing. I tested my statement with the following code:
```    assert_matches!(
        peer_manager.next().await.unwrap(),
        ToSwarm::GenerateEvent(ToOtherBehaviourEvent::SessionAssigned {
            outbound_session_id: OutboundSessionId { value: 2 },
            peer_id,
            connection_id,
        })
    );
```
When I use value 1 (the correct value) the test passes. When I set it to 2 the test fails due to mismatch. 

If do something like you, capturing in variables instead of writing explicitly like I did, then the test passes like you said. A great example of why macros are scary.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1qh38jE5ZLDA2nNt_K:-O1ulcWz9qMdRcGrjPfV:brpn883) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L203)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

1. is tested above, 2. is tested in the first select arm, and 3. is tested in the second select arm
</blockquote></details>

ok I see point 1 now. I still don't understand why 2 & 3 are in a select which runs things concurrently. If you are trying to show that order matters why not do it sequentially without the select?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1q_4AU7NXSzJ6dpcPQ:-O1vBmeW0hy0U1K4deXL:bp9blvj) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L152)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Wow this is incredibly confusing. I tested my statement with the following code:
```    assert_matches!(
        peer_manager.next().await.unwrap(),
        ToSwarm::GenerateEvent(ToOtherBehaviourEvent::SessionAssigned {
            outbound_session_id: OutboundSessionId { value: 2 },
            peer_id,
            connection_id,
        })
    );
```
When I use value 1 (the correct value) the test passes. When I set it to 2 the test fails due to mismatch. 

If do something like you, capturing in variables instead of writing explicitly like I did, then the test passes like you said. A great example of why macros are scary.
</blockquote></details>

I did not understand. Huddle?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O1qh38jE5ZLDA2nNt_K:-O2TC9L9BduRQx4rVkpF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e4c9cef6735f633ddf9bf4011005ef7b8850e87c/crates/papyrus_network/src/peer_manager/test.rs#L203)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

ok I see point 1 now. I still don't understand why 2 & 3 are in a select which runs things concurrently. If you are trying to show that order matters why not do it sequentially without the select?
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 183 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O2TCoNo4i6wBN8LMW6d:-O2TCoNo4i6wBN8LMW6e:be06r3g) ([raw file](https://github.com/starkware-libs/papyrus/blob/f31d1dc70f70c854f5893596a594a8fe18f274d1/crates/papyrus_network/src/peer_manager/test.rs#L183)):*
> ```XML
>     tokio::time::pause();
>     tokio::time::advance(BLOCKED_UNTIL).await;
>     tokio::time::resume();
> ```

Can we just advance without pause/resume?



_Code quote:_
```XML
    tokio::time::pause();
    tokio::time::advance(BLOCKED_UNTIL).await;
    tokio::time::resume();
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, and @matan-starkware)

___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 183 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2222#-O2TCoNo4i6wBN8LMW6d:-O2TD9dU1ocNcPRcrtCM:box2jc8) ([raw file](https://github.com/starkware-libs/papyrus/blob/f31d1dc70f70c854f5893596a594a8fe18f274d1/crates/papyrus_network/src/peer_manager/test.rs#L183)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can we just advance without pause/resume?
</blockquote></details>

I get this error if I don't pause
thread 'peer_manager::test::peer_assignment_no_unblocked_peers' panicked at /home/shahak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/time/clock.rs:199:9:
time is not frozen

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2222)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

**Pull request merged**
