### PR TITLE
feat(config): add serde option for vector configurations

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzRSNvr9v8K8EeDk9_f:-NzRSNvr9v8K8EeDk9_g:b-vuhb3s) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce7c981068a5663e3997ff06ee17fa7772abb2f6/crates/papyrus_config/src/converters.rs#L82)):*
> ```XML
> }
> 
> /// Serializes a vector to string structure. The vector is expected to be a list of u8 values
> ```

IMO hex string is more intuitive and easy for the user

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzRT5Tq7-1VHQX6rwa1:-NzRT5Tq7-1VHQX6rwa2:buy9zsw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce7c981068a5663e3997ff06ee17fa7772abb2f6/crates/papyrus_config/src/converters.rs#L87)):*
> ```XML
>     match optional_vector {
>         None => "".to_owned(),
>         Some(vector) => vector.iter().map(|v| format!("{v}")).collect::<Vec<String>>().join(" "),
> ```

Why separated by spaces and not ", ". There's no place where we serialize a vector this way

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_config/src/converters.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzRSNvr9v8K8EeDk9_f:-NzRtL--AW5adk5v4qr6:b-ggjy2f) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce7c981068a5663e3997ff06ee17fa7772abb2f6/crates/papyrus_config/src/converters.rs#L82)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO hex string is more intuitive and easy for the user
</blockquote></details>

I chose this way as it was used in the previous conversion function (map2string)
___
*[`crates/papyrus_config/src/converters.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzRT5Tq7-1VHQX6rwa1:-NzRtK1N84OPRV-GfmIM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ce7c981068a5663e3997ff06ee17fa7772abb2f6/crates/papyrus_config/src/converters.rs#L87)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why separated by spaces and not ", ". There's no place where we serialize a vector this way
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSxJZV7_AGVXZx1_mB:-NzSxJZV7_AGVXZx1_mC:barqe3s) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L89)):*
> ```XML
>             format!(
>                 "0x{}",
>                 vector.iter().map(|v| format!("{:02x}", v)).collect::<Vec<String>>().join("")
> ```

rename `v` to `num`
___
*[`crates/papyrus_config/src/converters.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSxquA-XVXyJ8puAYq:-NzSxquA-XVXyJ8puAYr:b-y68vqh) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L116)):*
> ```XML
>     if hex_str.len() != 64 {
>         return Err(D::Error::custom(
>             "Couldn't deserialize vector. Expected hex string of length 64",
> ```

Move this to the validation of the Network config. This can be valid under other configs
___
*[`crates/papyrus_config/src/converters.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSyHBfAnTL9A9Ul03R:-NzSyHBfAnTL9A9Ul03S:b-md0orb) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L125)):*
> ```XML
>         let byte = u8::from_str_radix(byte_str, 16).map_err(|e| {
>             D::Error::custom(format!(
>                 "Couldn't deserialize vector. Failed to parse byte: /{}/ {}",
> ```

Why surround with slashes?

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_config/src/converters.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSxquA-XVXyJ8puAYq:-NzXi-P2BHMujhRiWa-s:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L116)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to the validation of the Network config. This can be valid under other configs
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/converters.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSyHBfAnTL9A9Ul03R:-NzXUgHD3S3aIXlsKGAJ:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L125)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why surround with slashes?
</blockquote></details>

removed

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSxquA-XVXyJ8puAYq:-NzXlSKcC-7G8CeXnXwO:bme6igf) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L116)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no changes here You should erase this check
___
*[`crates/papyrus_config/src/validators.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzXlGnq7DW6CVROws9z:-NzXlGnq7DW6CVROwsA-:b-9n7joe) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b59d9881c87ceb35eff330a3ddd4ec36d22a6f6/crates/papyrus_config/src/validators.rs#L31)):*
> ```XML
> 
> /// Custom validation for a 32 bytes hex string.
> pub fn validate_hex_string_secret_representation(hex_string: &str) -> Result<(), ValidationError> {
> ```

secret -> u256

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_config/src/converters.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzSxquA-XVXyJ8puAYq:-NzXm2NpASyrwRIpV46z:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/367aa1e5b003e3d246d5cbaf44a4e88d77007a98/crates/papyrus_config/src/converters.rs#L116)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I see no changes here You should erase this check
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/validators.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzXlGnq7DW6CVROws9z:-NzXtBlfEVjFRVixpwmh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4b59d9881c87ceb35eff330a3ddd4ec36d22a6f6/crates/papyrus_config/src/validators.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

secret -> u256
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzXteyWBPI6YlyfN42u:-NzXteyWBPI6YlyfN42v:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/62b5afb94279de5e66cb0c7bbb444a608fdeb970/crates/papyrus_config/src/converters.rs#L83)):*
> ```XML
> 
> /// Serializes a vector to string structure. The vector is expected to be a hex string.
> pub fn serialize_optional_vector(optional_vector: &Option<Vec<u8>>) -> String {
> ```

Same here
___
*[`crates/papyrus_config/src/converters.rs` line 97 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-NzXtaMH3kzbgCs4ifvC:-NzXtaMH3kzbgCs4ifvD:b64vuyp) ([raw file](https://github.com/starkware-libs/papyrus/blob/62b5afb94279de5e66cb0c7bbb444a608fdeb970/crates/papyrus_config/src/converters.rs#L97)):*
> ```XML
> /// Deserializes a vector from string structure. The vector is expected to be a list of u8 values
> /// separated by spaces.
> pub fn deserialize_optional_vector<'de, D>(de: D) -> Result<Option<Vec<u8>>, D::Error>
> ```

vector -> vec_u8/bytes

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-:-NzXyPBY2LkoFZBYQ8qv:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2075#-:-NzY-Oj62HEgu44xT8xZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
