### PR TITLE
test(starknet_client): add tests for a 0.13.2 block

### PR DESCRIPTION
**Pull request by ShahakShama**
- fix: put none in commitments if they come from a deprecated formula
- test(starknet_client): add tests for a 0.13.2 block

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)

### CODE REVIEW

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/resources/reader/block_post_0_13_2.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O0mDzlJA3fNFZl7ibYm:-O0mDzlK4QgjWdR71Urg:b-rk78cg) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae49485627616b6b7c07ab759065691e05f9821e/crates/starknet_client/resources/reader/block_post_0_13_2.json#L1)):*
> ```JSON
> {
> ```

IDK how to review this file, so I'm relying on your test making use of it and that's it...



_Code quote:_
```JSON
{
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O0mEK8IAF1mVnlefTnX:-O0mEK8IAF1mVnlefTnY:basc0wo) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae49485627616b6b7c07ab759065691e05f9821e/crates/starknet_client/src/reader/objects/block_test.rs#L159)):*
> ```XML
>     );
> 
>     // TODO(shahak): Find a block with at least 2 transactions, and uncomment the code below.
> ```

What is the blocker for this? Why not do it now?



_Code quote:_
```XML
    // TODO(shahak): Find a block with at least 2 transactions, and uncomment the code below.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O0mEK8IAF1mVnlefTnX:-O1p0Hmx9wsO1aPVA8Tl:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/ae49485627616b6b7c07ab759065691e05f9821e/crates/starknet_client/src/reader/objects/block_test.rs#L159)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What is the blocker for this? Why not do it now?
</blockquote></details>

Done

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1pCXB14uYGyK3_J-yb:-O1pCXB14uYGyK3_J-yc:b-9jwjde) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f46255fc9a6dc327543a18ff3e74688edcb246e/crates/starknet_client/src/reader/objects/block_test.rs#L175)):*
> ```XML
>             }
>         )
>     );
> ```

It looks like you don't care about any of the fields, so why not remove this clutter?

(for the entire test)



_Suggestion:_
```XML
    assert_matches!(
        err,
        ReaderClientError::TransactionReceiptsError(
_        )
    );
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1pCXB14uYGyK3_J-yb:-O1tqfUD0Wupzj-z-GEo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f46255fc9a6dc327543a18ff3e74688edcb246e/crates/starknet_client/src/reader/objects/block_test.rs#L175)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

It looks like you don't care about any of the fields, so why not remove this clutter?

(for the entire test)
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1pCXB14uYGyK3_J-yb:-O1ud0_eBZXfa4PtSRXS:buzisaz) ([raw file](https://github.com/starkware-libs/papyrus/blob/5f46255fc9a6dc327543a18ff3e74688edcb246e/crates/starknet_client/src/reader/objects/block_test.rs#L175)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I left comments on the other places "(for the entire test)"
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucpQa1L25V3g009st:-O1ucpQa1L25V3g009su:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L126)):*
> ```XML
>                 num_of_receipts: _,
>             }
>         )
> ```





_Suggestion:_
```XML
        ReaderClientError::TransactionReceiptsError(
_
        )
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucv1zAHvzVh5cGLV-:-O1ucv1zAHvzVh5cGLV0:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L141)):*
> ```XML
>                 receipt_tx_index: _,
>             }
>         )
> ```





_Suggestion:_
```XML
        ReaderClientError::TransactionReceiptsError(
_
        )
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucxop7uICyYTqEFfF:-O1ucxoq6_UCzn0sl4kl:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L156)):*
> ```XML
>                 receipt_tx_hash: _,
>             }
>         )
> ```





_Suggestion:_
```XML
        ReaderClientError::TransactionReceiptsError(
_
        )
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2181)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucpQa1L25V3g009st:-O2c8WVE7QMBtMM5hsQ4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L126)):*
> ```XML
>                 num_of_receipts: _,
>             }
>         )
> ```

Done.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucv1zAHvzVh5cGLV-:-O2c8a2W9D1KupL-G4XQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L141)):*
> ```XML
>                 receipt_tx_index: _,
>             }
>         )
> ```

Done.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2181#-O1ucxop7uICyYTqEFfF:-O2c8ag-CU_tNfsy7wOU:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b66a9147ed0484258a1af050fa48d08f5da50ae6/crates/starknet_client/src/reader/objects/block_test.rs#L156)):*
> ```XML
>                 receipt_tx_hash: _,
>             }
>         )
> ```

Done.

**Pull request closed without merging**
