### PR TITLE
chore(consensus): add script for running consensus simulation

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: all files reviewed, 7 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CWdqdEdpWXOLQADrd:-O1CWdqdEdpWXOLQADre:bgtxdx2) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L9)):*
> ```Python
> 
> SECRET_KEY = "0xabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
> BOOT_NODE_PEER_ID = "12D3KooWDFYi71juk6dYWo3UDvqs5gAzGDc124LSvcR5d187Tdvi"
> ```

Add a comment to explain that the values are coupled.



_Code quote:_
```Python
SECRET_KEY = "0xabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
BOOT_NODE_PEER_ID = "12D3KooWDFYi71juk6dYWo3UDvqs5gAzGDc124LSvcR5d187Tdvi"
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CZdsZ7FKota81EB9Z:-O1CZds_6GZUg1QQJXHa:b-3lccwf) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L22)):*
> ```Python
>         processes.append(process)
> 
>     def cleanup():
> ```

Let's just put this directly into the `finally`.



_Code quote:_
```Python
    def cleanup():
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CWpke2dqOUT323wyL:-O1CWpke2dqOUT323wyM:bkqkkjp) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L24)):*
> ```Python
>     def cleanup():
>         for process in processes:
>             os.killpg(os.getpgid(process.pid), signal.SIGTERM)
> ```

Let's just pipe through the `Ctrl+C` and let the process exit gracefully.



_Suggestion:_
```Python
            os.killpg(os.getpgid(process.pid), signal.SIGINT)
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CY40b5zpdezFzH2nm:-O1CY40b5zpdezFzH2nn:b-2bjuvk) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L50)):*
> ```Python
>     # Clean and create data directories
>     for i in range(num_validators):
>         data_dir = f"data{i}"
> ```

Let's also put this in the `temp_dir` defined below. Then we don't need to worry about deleting and can leave .gitignore as is.



_Code quote:_
```Python
        data_dir = f"data{i}"
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYKIE8wGGhBtjZTVs:-O1CYKIE8wGGhBtjZTVt:bqm2mcu) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L69)):*
> ```Python
>         f"--consensus.num_of_validators {num_validators} "
>         f"> {temp_dir}/validator1.ansi"
>     )
> ```

Let's create 2 functions: `bootnode_command` and `peernode_command` to encapsulate these large strings.



_Code quote:_
```Python
    command = (
        f"RUST_LOG=papyrus_consensus=debug,papyrus=info "
        f"target/release/papyrus_node --network.#is_none false "
        f"--base_layer.node_url {base_layer_node_url} "
        f"--network.secret_key {SECRET_KEY} "
        f"--storage.db_config.path_prefix ./data1 "
        f"--consensus.#is_none false --consensus.validator_id 0x1 "
        f"--consensus.num_of_validators {num_validators} "
        f"> {temp_dir}/validator1.ansi"
    )
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYaoR2Upq7Gf17MTB:-O1CYaoR2Upq7Gf17MTC:bbztjnm) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L74)):*
> ```Python
>     # Add other validators
>     for i in range(2, num_validators):
>         base_port = 10000 + i * 3  # Ensure unique port ranges for each validator
> ```

create a constant



_Suggestion:_
```Python
# The number of ports each papyrus node uses.
NUM_PORTS = 3
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYkQo9MCMaqHt4o9d:-O1CYkQo9MCMaqHt4o9e:bcpqien) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L100)):*
> ```Python
>         f"--consensus.#is_none false --consensus.validator_id 0x0 "
>         f"--consensus.num_of_validators {num_validators} "
>         f"--network.tcp_port {base_port + 5} "
> ```

Why 5 instead of 3?



_Code quote:_
```Python
5
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: all files reviewed, 9 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 16 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1G12mS57g6JuZn_eC9:-O1G12mS57g6JuZn_eCA:buno13j) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L16)):*
> ```Python
> 
> 
> def run_parallel_commands(commands, runtime):
> ```

This is overloaded, consider another name such as duration or ttl



_Code quote:_
```Python
runtime
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1G2-HSEOKEQABQKCrL:-O1G2-HSEOKEQABQKCrM:ba0eo3h) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L35)):*
> ```Python
> 
> 
> def convert_ansi_to_txt(temp_dir, num_validators):
> ```

Why ANSI (and not UTF-8 for example)?



_Code quote:_
```Python
convert_ansi_to_txt
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1G2EQv-YxB50JJmjcS:-O1G2EQv-YxB50JJmjcT:b-vrhss2) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L46)):*
> ```Python
>     # Run cargo build
>     print("Running cargo build...")
>     run_command("cargo build -r")
> ```

1. Is there an assumption regarding from where we run this?
If so, please state it.

2. In addition, consider building specifically what we need (I guess `--package papyrus_node` in this case)



_Code quote:_
```Python
run_command("cargo build -r")
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1G3Ou8-d6yqXw4HB96:-O1G3Ou94AVakcn5GE59:b84bb4y) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L59)):*
> ```Python
> 
>     validator_commands = []
>     # Ensure validator 1 runs first
> ```

Please add a comment explaining the deployment order and role of validators



_Code quote:_
```Python
 # Ensure validator 1 runs first
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: all files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CWdqdEdpWXOLQADrd:-O1G2AqWA9ezU73iKaCy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L9)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Add a comment to explain that the values are coupled.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CZdsZ7FKota81EB9Z:-O1FuvE63H_aHqmKmPmO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L22)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's just put this directly into the `finally`.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CWpke2dqOUT323wyL:-O1G5DTE1JNaEglb_hRJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L24)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's just pipe through the `Ctrl+C` and let the process exit gracefully.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CY40b5zpdezFzH2nm:-O1G0WvW1Zq_fiJGS9u1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L50)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's also put this in the `temp_dir` defined below. Then we don't need to worry about deleting and can leave .gitignore as is.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYKIE8wGGhBtjZTVs:-O1GJJqV2gHqwjaLcCg-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L69)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's create 2 functions: `bootnode_command` and `peernode_command` to encapsulate these large strings.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYaoR2Upq7Gf17MTB:-O1G17500DeWtzqtTGlQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L74)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

create a constant
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1CYkQo9MCMaqHt4o9d:-O1G1JGw44q6oCbokICu:bloffe) ([raw file](https://github.com/starkware-libs/papyrus/blob/47bde1895e1c5aa89496a7862a5502439c2b16b4/crates/sequencing/papyrus_consensus/run_consensus.py#L100)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why 5 instead of 3?
</blockquote></details>

by mistake, I should not add anything here

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvFOdB-vQ7LVjjXQG:-O1GvFOe5O1-TIgqH4cy:bwhhss6) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L36)):*
> ```Python
>     # The number of ports each papyrus node uses.
>     NUM_PORTS = 3
>     base_port = 10000 + (num_validators * NUM_PORTS if i == 0 else i * NUM_PORTS)
> ```

- I prefer 1000 to 10,000 since the boot node uses port 10000 
- Why can't we just do this? It's this basically what you had before, without the ternary? It seems simpler.



_Suggestion:_
```Python
    base_port = 1000 + i * NUM_PORTS
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvWwi7O31TdD-AyrB:-O1GvWwi7O31TdD-AyrC:b-3bouee) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L49)):*
> ```Python
>         f"--network.bootstrap_peer_multiaddr.#is_none false "
>         f"--network.bootstrap_peer_multiaddr /ip4/127.0.0.1/tcp/10000/p2p/{BOOT_NODE_PEER_ID} "
>         f"| sed -r 's/\\x1B\\[[0-9;]*[mK]//g' > {temp_dir}/validator{i}.txt"
> ```

Add a comment to explain this "Use sed to strip special formatting"



_Code quote:_
```Python
        f"| sed -r 's/\\x1B\\[[0-9;]*[mK]//g' > {temp_dir}/validator{i}.txt"
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GwM-E57hPjG9y1Z8c:-O1GwM-F48Y_1vaM9KCX:bonnfiv) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L53)):*
> ```Python
> 
> 
> def main(base_layer_node_url, num_validators, duration):
> ```

assert this is at least 2.



_Code quote:_
```Python
num_validators
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvvEJ4J_N-6A2D6hN:-O1GvvEJ4J_N-6A2D6hO:b3kre) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L54)):*
> ```Python
> 
> def main(base_layer_node_url, num_validators, duration):
>     # Building the Papyrus Node project assuming its output will be located in the papyrus target directory.
> ```

?



_Suggestion:_
```Python
 package
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1Gw2ji3T9Cf07baLxB:-O1Gw2ji3T9Cf07baLxC:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L73)):*
> ```Python
>     validator_commands = []
>     # Ensure validator 1 runs first
>     command = (
> ```





_Suggestion:_
```Python
bootnode_command
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: all files reviewed, 5 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvFOdB-vQ7LVjjXQG:-O1GxZtC5AfI4p9YIAOY:b-7rhafd) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L36)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

- I prefer 1000 to 10,000 since the boot node uses port 10000 
- Why can't we just do this? It's this basically what you had before, without the ternary? It seems simpler.
</blockquote></details>

Done, added `find_free_port` func
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvWwi7O31TdD-AyrB:-O1GyQuHAnG8Bw_JsZl9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L49)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Add a comment to explain this "Use sed to strip special formatting"
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GwM-E57hPjG9y1Z8c:-O1GxyFa3bZP3Qiq-XJR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L53)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

assert this is at least 2.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 54 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1GvvEJ4J_N-6A2D6hN:-O1Gxxs-9cfk5mEkHH4s:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L54)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 73 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2198#-O1Gw2ji3T9Cf07baLxB:-O1GxpSrD0llv-c-7j0z:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/347388749d045f5a1a61b3626d56982ba50c4034/crates/sequencing/papyrus_consensus/run_consensus.py#L73)):*
> ```Python
>     validator_commands = []
>     # Ensure validator 1 runs first
>     command = (
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2198)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
