### PR TITLE
feat(JSON-RPC): broadcasted declare tx

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/969)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/969)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/resources/V0_4_0/starknet_api_openrpc.json` line 1829 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/969#-NavFeJ_4EmTzIVasXJR:-NavUfqU1qH0Z3LDjQfQ:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee85461c13be426ea9eccebfa4f479a56daf51cb/crates/papyrus_gateway/resources/V0_4_0/starknet_api_openrpc.json#L1829)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this (also from v1)
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/969#-NavGKvl2isRe74cksxT:-NavVe735xMOJT4ILM6Z:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3cae8a37ad807f15c2e3588ddb0c39646b075c65/crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs#L55)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

ContractClass and EntryPointByType should sit in another file. My suggestion is create a file called impl_get_test_instance.rs in the v0_4_0 directory (and use it only in cfg test) and have all the auto_impl_get_test_instance! there.

For now you can put a TODO to move these two
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/969#-NavH0N53xkJ1Zv_yyf4:-NavVwJW9RSuvWNKUruv:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/3cae8a37ad807f15c2e3588ddb0c39646b075c65/crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this ignore
</blockquote></details>

done
___
*[`crates/papyrus_gateway/src/v0_4_0/mod.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/969#-NavGk5XBbSZG-inazfR:-NavW25mBGbiUCSLDrae:b-hfbd7r) ([raw file](https://github.com/starkware-libs/papyrus/blob/3cae8a37ad807f15c2e3588ddb0c39646b075c65/crates/papyrus_gateway/src/v0_4_0/mod.rs#L5)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I personally prefer putting the test module inside the module itself and change its path with `#[path]`, but this works as well
</blockquote></details>

I kept the same structure as 0.3

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/969)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/969#-NavH0N53xkJ1Zv_yyf4:-NavZ9154thYKlsUMDkb:b-3fm5j5) ([raw file](https://github.com/starkware-libs/papyrus/blob/3cae8a37ad807f15c2e3588ddb0c39646b075c65/crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs#L71)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done
</blockquote></details>

I didn't mean remove the test :sweat_smile:

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/969#-:-Nav_KF3BP4QKfL5cd5I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by yair-starkware** [comment]
For now decided not to fix the schema file

**Pull request closed without merging**
