### PR TITLE
feat(common): calculate deploy account transaction hash

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @OmriEshhar1, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbHWqY8yMVJKxPXRs8:-NcbHWqZ5cY-OC6jBt66:bs5u4n6) (no related file):*
Maybe this should sit in starknet_api? @dan-starkware WDYT?

___
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGgja0Tvfn1MR11VZ:-NcbGgja0Tvfn1MR11V_:bhq0zbb) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash.rs#L45)):*
> ```XML
> }
> 
> fn ascii_as_felt(ascii_str: &str) -> Result<StarkFelt, StarknetApiError> {
> ```

I spoke about this with @EvyatarO and the chain id should contain only ASCII characters. We should verify that this is the case
The correct place to do that is when the node starts. Could you add a preliminary PR to this PR that validates that chain id is ASCII only?
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGUQNEWOw1wLOfgwJ:-NcbGUQNEWOw1wLOfgwK:b-1scp01) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash_test.rs#L34)):*
> ```XML
>     // https://alpha4.starknet.io/feeder_gateway/get_block?blockNumber=385429
>     let tx = DeployAccountTransaction {
>         max_fee: Fee(u128::from_str_radix("81ca6d7a5d", 16).unwrap()),
> ```

Move this to a resource file and load it with serde_json (Move the expected hash as well)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @EvyatarO, @OmriEshhar1, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbHWqY8yMVJKxPXRs8:-NcbtIIs9ole90nGrJ08:b-1dw0o4) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Maybe this should sit in starknet_api? @dan-starkware WDYT?
</blockquote></details>

papyrus_common is a temporary location.

___
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGgja0Tvfn1MR11VZ:-NcbtTUC3K_1haO0kOc2:bmsnu4l) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I spoke about this with @EvyatarO and the chain id should contain only ASCII characters. We should verify that this is the case
The correct place to do that is when the node starts. Could you add a preliminary PR to this PR that validates that chain id is ASCII only?
</blockquote></details>

1. IMO, if we verify the chain id, we need to compare it against the list of optional chain ids.
2. WDYT about a verification step of the config?
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGUQNEWOw1wLOfgwJ:-NcbuSjM0gf_C-gd3tCY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash_test.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to a resource file and load it with serde_json (Move the expected hash as well)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dan-starkware, @EvyatarO, and @OmriEshhar1)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGgja0Tvfn1MR11VZ:-NcqbHok1vAJhBhYNpCD:b-6x897g) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash.rs#L45)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

1. IMO, if we verify the chain id, we need to compare it against the list of optional chain ids.
2. WDYT about a verification step of the config?
</blockquote></details>

1. We want to allow private starknets and appchains. They just need to be with ASCII characters
2. Sounds good

**Review by ShahakShama — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @EvyatarO, and @OmriEshhar1)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @EvyatarO, and @OmriEshhar1)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-NcbGgja0Tvfn1MR11VZ:-Ncqcdv9AMTz1iy8hDHg:bu5xrmz) ([raw file](https://github.com/starkware-libs/papyrus/blob/9bc25166fa72db0ae8d5c211d96edbdbd697339c/crates/papyrus_common/src/transaction_hash.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

1. We want to allow private starknets and appchains. They just need to be with ASCII characters
2. Sounds good
</blockquote></details>

I'll add it in a new PR.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1093#-:-NcvZ1B1AOkO4k-GR7sc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @OmriEshhar1)

**Pull request merged**
