### PR TITLE
feat(network): replace ThinStateDiff with StateDiffChunk in db_executor Data

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/Cargo.toml` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSfxWm6o0plLQrqZ6H:-NzSfxWm6o0plLQrqZ6I:bbtxm0z) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/Cargo.toml#L65)):*
> ```TOML
> tokio-stream.workspace = true
> void.workspace = true
> test_utils = { path = "../test_utils" }
> ```

Add newline at end of file
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSlIU72Z-J55aFLSWL:-NzSlIU72Z-J55aFLSWM:bcidanf) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/src/db_executor/mod.rs#L50)):*
> ```XML
> pub enum Data {
>     BlockHeaderAndSignature(SignedBlockHeader),
>     StateDiffChunk { state_diff: StateDiffChunk },
> ```

Change this to StateDiffChunk(StateDiffChunk)
If you think the current way is better, rename state_diff to state_diff_chunk
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSgCfQ1kMNAs8zOJ-K:-NzSgCfQ1kMNAs8zOJ-L:bx7v5hd) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/src/db_executor/mod.rs#L79)):*
> ```XML
>             }
>             Data::StateDiffChunk { state_diff } => {
>                 let x = DataOrFin(Some(state_diff));
> ```

x is not a good variable name
___
*[`crates/papyrus_protobuf/src/sync.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSkzaaBgOA50iqgPUi:-NzSkzaaBgOA50iqgPUj:bphvux2) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_protobuf/src/sync.rs#L80)):*
> ```XML
> }
> 
> pub struct StateDiffChunkVec(pub Vec<StateDiffChunk>);
> ```

Move this code to the network crate next to the db executor
___
*[`crates/papyrus_protobuf/src/sync.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSl3VW8zCqGcE1Dgre:-NzSl3VW8zCqGcE1Dgrf:byys5dd) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_protobuf/src/sync.rs#L80)):*
> ```XML
> }
> 
> pub struct StateDiffChunkVec(pub Vec<StateDiffChunk>);
> ```

No need to create this struct. Create a function called split_state_diff that receives a ThinStateDiff and outputs Vec<StateDiffPart>
___
*[`crates/papyrus_protobuf/src/sync.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSmvBw07Unz7PVUceI:-NzSmvBw07Unz7PVUceJ:bl8jox8) ([raw file](https://github.com/starkware-libs/papyrus/blob/ada342b26ff93aa3bc8cb18ed782cc056148df67/crates/papyrus_protobuf/src/sync.rs#L86)):*
> ```XML
>         let mut state_diff_chunks = Vec::new();
> 
>         for (contract_address, class_hash) in thin_state_diff.deployed_contracts.iter() {
> ```

No need for iter() since you receive the thin_state_diff by value. This will remove the need for all these dereferences and cloning

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/Cargo.toml` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSfxWm6o0plLQrqZ6H:-NzSqRJACvb4GR5paGIU:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/Cargo.toml#L65)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add newline at end of file
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSlIU72Z-J55aFLSWL:-NzSp-O23Q06snTbQx_C:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/src/db_executor/mod.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to StateDiffChunk(StateDiffChunk)
If you think the current way is better, rename state_diff to state_diff_chunk
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSgCfQ1kMNAs8zOJ-K:-NzSp-l7BTsDuBnfDwId:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_network/src/db_executor/mod.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

x is not a good variable name
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/sync.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSl3VW8zCqGcE1Dgre:-NzSr5vPEMxqejGDt_Ev:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_protobuf/src/sync.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to create this struct. Create a function called split_state_diff that receives a ThinStateDiff and outputs Vec<StateDiffPart>
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/sync.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSkzaaBgOA50iqgPUi:-NzSr94f2EdWqOcOxP_S:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/53bd5de09d0eaf6e04764e223df408b91f8819ff/crates/papyrus_protobuf/src/sync.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this code to the network crate next to the db executor
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/sync.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzSmvBw07Unz7PVUceI:-NzSpJdh1cBjwMOb9ryx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ada342b26ff93aa3bc8cb18ed782cc056148df67/crates/papyrus_protobuf/src/sync.rs#L86)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need for iter() since you receive the thin_state_diff by value. This will remove the need for all these dereferences and cloning
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzY3-BIBfE7UkE5brrh:-NzY3-BIBfE7UkE5brri:b-c3o5jc) ([raw file](https://github.com/starkware-libs/papyrus/blob/86581894eaf7d7a265008a7676bd3cbfb3fe8836/crates/papyrus_network/src/db_executor/mod.rs#L475)):*
> ```XML
>             contract_address,
>             class_hash: Some(class_hash),
>             nonce: thin_state_diff.nonces.get(&contract_address).cloned(),
> ```

What happens if there's a contract that wasn't deployed in this state diff but its nonce was updated?
You should pass on all the keys of deployed_contracts, nonces, storage diffs and replaced classes, remove any duplicates, and do this code for all of them while using get() in class_hash
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 484 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzY2nMp8w6sGy87595z:-NzY2nMp8w6sGy87596-:bsjzneu) ([raw file](https://github.com/starkware-libs/papyrus/blob/86581894eaf7d7a265008a7676bd3cbfb3fe8836/crates/papyrus_network/src/db_executor/mod.rs#L484)):*
> ```XML
>     }
> 
>     for (contract_address, class_hash) in thin_state_diff.replaced_classes {
> ```

Unite this with the previous for loop using iter::chain

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzY3-BIBfE7UkE5brrh:-NzYJbtaD-Z9wUzhKMEh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/86581894eaf7d7a265008a7676bd3cbfb3fe8836/crates/papyrus_network/src/db_executor/mod.rs#L475)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What happens if there's a contract that wasn't deployed in this state diff but its nonce was updated?
You should pass on all the keys of deployed_contracts, nonces, storage diffs and replaced classes, remove any duplicates, and do this code for all of them while using get() in class_hash
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 484 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-NzY2nMp8w6sGy87595z:-NzYJcMX8L_p8vfTPfH2:b-o028jk) ([raw file](https://github.com/starkware-libs/papyrus/blob/86581894eaf7d7a265008a7676bd3cbfb3fe8836/crates/papyrus_network/src/db_executor/mod.rs#L484)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unite this with the previous for loop using iter::chain
</blockquote></details>

now I am running on all the related contracts at once, so there is no need for this loop

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2082#-:-NzYLEJP02WCFR8h4Msk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
