### PR TITLE
Dvir/prepare for adding transaction

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/527)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/527)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPRYyLm0tYNfhzEunLS:-NPRYyLm0tYNfhzEunLT:b-7s3x8o) (no related file):*
this pull request is to prepare for adding new transactions
Look at the commits by their order.
first renaming function
second, add transactions and weights in a loop
third, add a general way to get the arguments in create_request with the correct type
fourth format changes
🤓

___

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/527)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @ShahakShama)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPRu63E3xfTwtNb9-iM:-NPRu63E3xfTwtNb9-iN:bw3zey0) ([raw file](https://github.com/starkware-libs/papyrus/blob/d5f413817e8234fdec761081b3738f08c651c062/crates/papyrus_load_test/src/create_request.rs#L26)):*
> ```XML
> 
> pub fn get_block_with_transaction_hashes_by_number(args: &str) -> jsonVal {
>     let mut iter = ArgsIter::new(args);
> ```

Maybe because each function in this module will use this ArgsIter the function should get it as a parameter instead of &str.

**Comment by dan-starkware** [comment]
*[`crates/papyrus_load_test/src/create_request.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPS5WtFBpXdIZid7yxK:-NPS5WtFBpXdIZid7yxL:b-vfmrw0) ([raw file](https://github.com/starkware-libs/papyrus/blob/b9c9e97cdc8646f76b6a51bb436661611cf5f123/crates/papyrus_load_test/src/create_request.rs#L5)):*
> ```XML
> use crate::jsonrpc_request;
> 
> pub fn get_block_with_transaction_hashes_by_number(args: &str) -> jsonVal {
> ```

Why not `block_number`?



_Code quote:_
```XML
args
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 3 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/527#-:-NPSTUqrAMr3ThSPKQsI:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @anatgstarkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/papyrus_load_test/src/scenarios.rs` line 4 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPSTE6e2Vh1m1HIYsdz:-NPSTE6e2Vh1m1HIYse-:bu3ueed) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a94c586e71c162050a98bdbd6ae353579b9f787/crates/papyrus_load_test/src/scenarios.rs#L4)):*
> ```XML
> use goose::scenario;
> 
> use crate::transactions::*;
> ```

Consider `use crate::transactions as txs;`



_Code quote:_
```XML
use crate::transactions::*;
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/527)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @ShahakShama)

___
*[`crates/papyrus_load_test/src/create_request.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPS5WtFBpXdIZid7yxK:-NPSUb1-BHETgRXChZQ8:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b9c9e97cdc8646f76b6a51bb436661611cf5f123/crates/papyrus_load_test/src/create_request.rs#L5)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not `block_number`?
</blockquote></details>

done
___
*[`crates/papyrus_load_test/src/scenarios.rs` line 4 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/527#-NPSTE6e2Vh1m1HIYsdz:-NPSU_suAI0zaELNvq3_:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a94c586e71c162050a98bdbd6ae353579b9f787/crates/papyrus_load_test/src/scenarios.rs#L4)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider `use crate::transactions as txs;`
</blockquote></details>

done

**Pull request merged**
