### PR TITLE
Refactor central state update downloading

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbL3LoABxvO9YRxcjj:-NUbL3LoABxvO9YRxcjk:b-h8c7mo) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L56)):*
> ```XML
> 
>             // If available, retrieve next block state update and classes.
>             // We don't return it immediately to allow initiating more downloading tasks.
> ```

Fix the comment
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbLVSK5F-2UGxCMkF0:-NUbLVSK5F-2UGxCMkF1:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L125)):*
> ```XML
>     ) -> CentralResult<()> {
>         self.schedule_class_downloads(should_poll_again);
>         self.enqueue_downloaded_classes(cx, should_poll_again)?;
> ```





_Suggestion:_
```XML
handle
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUePxWm7kHPyyKZjBu3:-NUePxWm7kHPyyKZjBu4:b-moc02a) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L146)):*
> ```XML
>     }
> 
>     /// Checks for finished class downloading tasks.
> ```

Make better comments on all of these?
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUeQ3IZB9Js0p9lShyk:-NUeQ3IZB9Js0p9lShyl:beix1e) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L152)):*
> ```XML
>         should_poll_again: &mut bool,
>     ) -> CentralResult<()> {
>         if let Poll::Ready(Some(maybe_class)) = self.download_class_tasks.poll_next_unpin(cx) {
> ```

Consider using let else, for an early return, instead of nesting.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)* status: all files reviewed, 17 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb8ZAu055RnM5CwST9:-NUb8ZAu055RnM5CwSTA:b-nlzmqu) (no related file):*
Maybe we can use here a dequeue with fixed size:
https://docs.rs/fixed-vec-deque/0.1.11/fixed_vec_deque/struct.FixedVecDeque.html

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbUwjpC7qaCRZBvT3_:-NUbUwjpC7qaCRZBvT3a:bilzjti) (no related file):*
Did you think about defining a state machine using enum?
Something like:
```
enum StreamState {
    NotReady,
    Downloading,
    Ready(CentralResult<CentralStateUpdate>),
    Exhausted,

}
```
I think the code can be easier this way

___
___
*[`crates/papyrus_sync/src/sources/central.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUavCkGB5unR0-Bv-NT:-NUavCkH11yyPBrWUJrk:b-7k9h0c) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central.rs#L26)):*
> ```XML
> use tracing::{debug, trace};
> 
> use self::state_update_stream::StateUpdateStream;
> ```

Is the self:: necessary?



_Code quote:_
```XML
self::
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbCB204-q0ANotRXwp:-NUbCB204-q0ANotRXwq:b44seuc) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L27)):*
> ```XML
> const CLASSES_INITIAL_CAPACITY: usize = MAX_STATE_UPDATES_TO_STORE_IN_MEMORY * 5;
> 
> type FuturesOrderedPinBox<T> = FuturesOrdered<Pin<Box<dyn Future<Output = T> + Send>>>;
> ```

Consider renaming to something like TasksQueue



_Code quote:_
```XML
FuturesOrderedPinBox
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbCxKl9K8D6uVX9ugy:-NUbCxKm9yl4TlPfg92v:b-yinv3l) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L34)):*
> ```XML
>     storage_reader: StorageReader,
>     download_state_update_tasks:
>         FuturesOrderedPinBox<(BlockNumber, Result<Option<StateUpdate>, ClientError>)>,
> ```

Consider:
1. Aliasing to something like StateUpdateTaskResult
2. ClientResult instead of Result



_Code quote:_
```XML
(BlockNumber, Result<Option<StateUpdate>, ClientError>)
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb-paR-cXvXMfSfM3C:-NUb-paS2YjfYm6bL15B:byetqtt) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L35)):*
> ```XML
>     download_state_update_tasks:
>         FuturesOrderedPinBox<(BlockNumber, Result<Option<StateUpdate>, ClientError>)>,
>     downloaded_state_updates: VecDeque<(BlockNumber, usize, StateUpdate)>,
> ```

Is the number of classes necessary? It can be calculated from the state update.
If you decide to keep it. please document what is the usize here, or even better - use type alias.



_Code quote:_
```XML
usize
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb0pwE871zpNu3ZNiR:-NUb0pwE871zpNu3ZNiS:b-tloa8v) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L50)):*
> ```XML
>         cx: &mut std::task::Context<'_>,
>     ) -> std::task::Poll<Option<Self::Item>> {
>         loop {
> ```

If I understand correctly, in the first iteration next_output() will always return None because do_scheduling wasn't called yet, right?
Can you switch the order of calling the functions? I.E first do_scheduling and then next_output
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb3UQ36PBWLKHI5aSj:-NUb3UQ36PBWLKHI5aSk:b9ba4wx) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L61)):*
> ```XML
>             }
> 
>             if let Err(err) = self.do_scheduling(&mut should_poll_again, cx) {
> ```

consider deleting should_poll_again and instead modify do_scheduling to return a bool
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUazmjf5QaKNCNhiR8V:-NUazmjf5QaKNCNhiR8W:by4s1nq) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L89)):*
> ```XML
>         starknet_client: Arc<TStarknetClient>,
>         storage_reader: StorageReader,
>     ) -> Self {
> ```

Consider asserting that the constants make sense, for example MAX_STATE_UPDATES_TO_STORE_IN_MEMORY >= MAX_STATE_UPDATES_TO_DOWNLOAD
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUaywva9RoULDMdVuGK:-NUaywva9RoULDMdVuGL:ba7br0e) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L103)):*
> ```XML
>     }
> 
>     // Return data needed for the next block CentralStateUpdate, or None if it is not ready.
> ```

Returns



_Code quote:_
```XML
Return
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb5-beEtpF8O-3L0d3:-NUb5-beEtpF8O-3L0d4:bou9y1z) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L152)):*
> ```XML
>         should_poll_again: &mut bool,
>     ) -> CentralResult<()> {
>         if let Poll::Ready(Some(maybe_class)) = self.download_class_tasks.poll_next_unpin(cx) {
> ```

Use early return:
```
let Poll::Ready(Some(maybe_class)) = self.download_class_tasks.poll_next_unpin(cx) else { return Ok(());};
```



_Code quote:_
```XML
if let Poll::Ready(Some(maybe_class)) = self.download_class_tasks.poll_next_unpin(cx) {
```
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbnOM42e0wgDZd4U9K:-NUbnOM42e0wgDZd4U9L:bj67wbu) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L309)):*
> ```XML
> // First tries to retrieve the class from the storage.
> // If not found in the storage, the class is downloaded.
> async fn download_class_if_necessary<TStarknetClient: StarknetClientTrait>(
> ```

Instrument the function (tracing)
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbBoj3C-xK8S648X4s:-NUbBoj3C-xK8S648X4t:b-rtagwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/441a4c72a3f8a5ff39d62dc1bf38b588151d2c72/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L312)):*
> ```XML
>     //     async fn download_class_if_necessary<
>     //     TStarknetClient: StarknetClientTrait + Send + Sync + 'static,
>     // >(
> ```

delete



_Code quote:_
```XML
    //     async fn download_class_if_necessary<
    //     TStarknetClient: StarknetClientTrait + Send + Sync + 'static,
    // >(
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @spapinistarkware and @yair-starkware)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUavCkGB5unR0-Bv-NT:-NUp6FD_18Z2LT2k4BM-:b5u9fw) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central.rs#L26)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is the self:: necessary?
</blockquote></details>

Not necessary but IMO it's better than 
`use crate::sources::central::state_update_stream::StateUpdateStream;` or `use state_update_stream::StateUpdateStream;`
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb-paR-cXvXMfSfM3C:-NUpR5rEANo28X4ASWHA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L35)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is the number of classes necessary? It can be calculated from the state update.
If you decide to keep it. please document what is the usize here, or even better - use type alias.
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbL3LoABxvO9YRxcjj:-NUpRm9U6TshkYaTDddq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix the comment
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbLVSK5F-2UGxCMkF0:-NUpSxBg7MYaj6hbYQJo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L125)):*
> ```XML
>     ) -> CentralResult<()> {
>         self.schedule_class_downloads(should_poll_again);
>         self.enqueue_downloaded_classes(cx, should_poll_again)?;
> ```

Done.
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUb5-beEtpF8O-3L0d3:-NUplM3t-_az62G0GjmR:b9dpegd) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L152)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use early return:
```
let Poll::Ready(Some(maybe_class)) = self.download_class_tasks.poll_next_unpin(cx) else { return Ok(());};
```
</blockquote></details>

Done, not sure about formatting. 
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUeQ3IZB9Js0p9lShyk:-NUplIS4CWc7KTFdV5I4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L152)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider using let else, for an early return, instead of nesting.
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbnOM42e0wgDZd4U9K:-NUplujX6GLJvN2qj9uK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L309)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Instrument the function (tracing)
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central/state_update_stream.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/660#-NUbBoj3C-xK8S648X4s:-NUplzFE7GD9kUANe3kh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ad2cfdae13047429b59b3ff0ef7d9c750566b786/crates/papyrus_sync/src/sources/central/state_update_stream.rs#L312)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/660#-:-NUqMoU1DG94TJaCK502:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
