### PR TITLE
chore(consensus): add consensus stagnation check

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WUj2S3smj0_asUBYa:-O1WUj2S3smj0_asUBYb:b6bmq5w) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L22)):*
> ```Python
>         self.cmd = cmd
>         self.process = None
>         self.last_height = (None, None)  # (timestamp, height)
> ```

height_and_timestamp = (None, None)  # (height, timestamp)



_Code quote:_
```Python
last_height
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WS7Fh5lbULDkV9HIB:-O1WS7Fh5lbULDkV9HIC:b-ufflyd) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
> ```Python
>         command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
>         result = subprocess.run(command, shell=True, capture_output=True, text=True)
>         current_height = result.stdout.strip()
> ```

Separate this into it's own private function (_get_height).
What happens if there are no metrics (the node isn't ready yet) or the value has not yet been set?



_Code quote:_
```Python
        port = self.monitoring_gateway_server_port
        command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        current_height = result.stdout.strip()
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WTIQZ63gBAT4dzOy4:-O1WTIQZ63gBAT4dzOy5:b9fr78j) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L52)):*
> ```Python
>             )
> 
>         return current_height
> ```

I think this logic should basically be externalized from the Node class. I don't want the node to consider `start_time` or `stagnation_threshold`. Instead let's create:

```
def check_height:
    let height = self._get_height()
    if self.height[0] != height:
        self.height = (height, time.time())
    return self.height
```



_Code quote:_
```Python
        current_time = time.time() - start_time
        last_time, last_height = self.last_height
        if last_height is not None and current_height == last_height:
            if current_time - last_time >= self.stagnation_threshold:
                print(
                    f"Consensus stops. Validator {self.validator_id} height {current_height} hasn't changed for {self.stagnation_threshold} seconds. Exiting..."
                )
                return None
        else:
            self.last_height = (
                (current_time, current_height) if current_height != "" else (None, None)
            )

        return current_height
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WSrP5DpgeCggdDAZ7:-O1WSrP5DpgeCggdDAZ8:btvnucm) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L64)):*
> ```Python
> 
> def run_command(command):
>     return subprocess.run(command, shell=True, check=True)
> ```

remove. Just use `subprocess.run`



_Code quote:_
```Python
def run_command(command):
    return subprocess.run(command, shell=True, check=True)
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WWJur3OURhdcsSUab:-O1WWJur3OURhdcsSUac:bg9h3id) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L75)):*
> ```Python
>         i = 1
>         while True:
>             time.sleep(10)
> ```

const at top of file, or a param with a default value



_Suggestion:_
```Python
MONITORING_PERIOD = 10
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WXP276KdxHldM7dvl:-O1WXP276KdxHldM7dvm:b-fuoy5q) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L98)):*
> ```Python
>     finally:
>         for node in nodes:
>             node.stop()
> ```

I'd prefer not having the internal function. I don't understand why we need to add threading

Here's my suggestion



_Suggestion:_
```Python
# Returns if the simulation should exit.
def monitor_simulation(nodes, start_time, duration, stagnation_timeout):
    time = time.time()
    if duration < (time - start_time):
        return False
    
    for n in nodes:
        (height, last_update) = n.check_height()
        print(f"Node: {n.validator_id}, height: {height}")
        if (time - last_update) > stagnation_timeout:
            print(f"Node: {n.validator_id} has stagnated. Exiting simulation.")
            return True
    return False

def run_simulation(nodes, duration, stagnation_timeout):
    for node in nodes:
        node.start()

    start_time = time.time()
    try:
        while True:
            time.sleep(MONITORING_PERIOD)
            print(f"Time elapsed: {time.time() - start_time}s")
            should_exit = monitor_simulation(nodes, start_time, duration, stagnation_timeout)
            if should_exit:
                break
    except KeyboardInterrupt:
        print("\nTerminating subprocesses...")
    finally:
        for node in nodes:
            node.stop()
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WVAcMD7LRmLL62X9o:-O1WVAcMD7LRmLL62X9p:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L101)):*
> ```Python
> 
> 
> def peernode_command(base_layer_node_url, temp_dir, num_validators, i, stagnation_threshold):
> ```





_Suggestion:_
```Python
def build_peernode(base_layer_node_url, temp_dir, num_validators, i):
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 156 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WRRqMEMHUVuSFoqyp:-O1WRRqMEMHUVuSFoqyq:buhnrak) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L156)):*
> ```Python
>         f"--consensus.#is_none false --consensus.validator_id 0x1 "
>         f"--consensus.num_validators {num_validators} "
>         f"--monitoring_gateway.server_address 127.0.0.1:8081 "
> ```

find_free_port?



_Code quote:_
```Python
8081
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 194 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WRcI8732R5mSBnyY1:-O1WRcI8732R5mSBnyY2:b-q89onc) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L194)):*
> ```Python
>         type=int,
>         required=False,
>         default=30,
> ```

Let's default to 1m. Sync can get stuck for a while. BTW, when we are running this, we should be aware that if we are using an already synced node, we can probably turn this down to 10s since consensus usually runs fast.



_Suggestion:_
```Python
60
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WUj2S3smj0_asUBYa:-O1WaP1w7-twjQwcSvvY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L22)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

height_and_timestamp = (None, None)  # (height, timestamp)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WS7Fh5lbULDkV9HIB:-O1WlllkEFUfHq-HoDPE:b9d2uk4) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Separate this into it's own private function (_get_height).
What happens if there are no metrics (the node isn't ready yet) or the value has not yet been set?
</blockquote></details>

the height will be "", so I added a condition to check that height is not "" when determining if the node has stagnated
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WTIQZ63gBAT4dzOy4:-O1WlV3y6B4VgpYlNCCN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L52)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think this logic should basically be externalized from the Node class. I don't want the node to consider `start_time` or `stagnation_threshold`. Instead let's create:

```
def check_height:
    let height = self._get_height()
    if self.height[0] != height:
        self.height = (height, time.time())
    return self.height
```
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WSrP5DpgeCggdDAZ7:-O1Watr59SWSrz1XyqMA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

remove. Just use `subprocess.run`
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WWJur3OURhdcsSUab:-O1Wb38qC5j34nQSi06C:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

const at top of file, or a param with a default value
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WXP276KdxHldM7dvl:-O1WlhvH7PBU062qxYea:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L98)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I'd prefer not having the internal function. I don't understand why we need to add threading

Here's my suggestion
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 101 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WVAcMD7LRmLL62X9o:-O1Wbe9N2r9Hi3fo6CLt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L101)):*
> ```Python
> 
> 
> def peernode_command(base_layer_node_url, temp_dir, num_validators, i, stagnation_threshold):
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 156 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WRRqMEMHUVuSFoqyp:-O1Wl_ha7Vf66YPQzzn4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L156)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

find_free_port?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 194 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WRcI8732R5mSBnyY1:-O1WbWiQ4NnmVhGlS597:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L194)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's default to 1m. Sync can get stuck for a while. BTW, when we are running this, we should be aware that if we are using an already synced node, we can probably turn this down to 10s since consensus usually runs fast.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WS7Fh5lbULDkV9HIB:-O1Xs5B15rTSrtPc20nL:bn19kwi) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

the height will be "", so I added a condition to check that height is not "" when determining if the node has stagnated
</blockquote></details>

Great.

On second thought, no need for it to be private. Remove the `_`.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WSrP5DpgeCggdDAZ7:-O1XsV3HCfnDsfEuvJ0h:bbqm87r) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L64)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh no, I meant remove the function `run_command`. It's too simple, not worth the indirection of having another function.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 41 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1Xsyll30hWvR_w5LpM:-O1Xsyll30hWvR_w5LpN:b5rhqpy) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7f6335a58d2b2da05e8b95fa9fb41fb962d7dbb/crates/sequencing/papyrus_consensus/run_consensus.py#L41)):*
> ```Python
>     def check_height(self):
>         height = self._get_height()
>         if self.height_and_timestamp[0] != height:
> ```

Let's add an assertion that height has increased.



_Code quote:_
```Python
if self.height_and_timestamp[0] != height:
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1XtQkBCQ7yQBa1cRaq:-O1XtQkBCQ7yQBa1cRar:b-b192jf) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7f6335a58d2b2da05e8b95fa9fb41fb962d7dbb/crates/sequencing/papyrus_consensus/run_consensus.py#L71)):*
> ```Python
>         if height != "" and (curr_time - last_update) > stagnation_timeout:
>             print(f"Node: {node.validator_id} has stagnated. Exiting simulation.")
>             return True
> ```

Instead of immediately returning, let's finish iterating all of the nodes. That way we can report if any others have stagnated also. Then return True/False at the end.



_Code quote:_
```Python
            return True
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1WSrP5DpgeCggdDAZ7:-O1jlLyj12OzQ3jgmZHG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7a1a1bc5c3b97090fe01088badacf057cdce329d/crates/sequencing/papyrus_consensus/run_consensus.py#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Oh no, I meant remove the function `run_command`. It's too simple, not worth the indirection of having another function.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 41 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1Xsyll30hWvR_w5LpM:-O1jlB3X834gUEswzT45:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7f6335a58d2b2da05e8b95fa9fb41fb962d7dbb/crates/sequencing/papyrus_consensus/run_consensus.py#L41)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's add an assertion that height has increased.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 71 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1XtQkBCQ7yQBa1cRaq:-O1jteWZ3Fn5Z_xIdrJI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7f6335a58d2b2da05e8b95fa9fb41fb962d7dbb/crates/sequencing/papyrus_consensus/run_consensus.py#L71)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Instead of immediately returning, let's finish iterating all of the nodes. That way we can report if any others have stagnated also. Then return True/False at the end.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kPkwV49zipSucAVS3:-O1kPkwV49zipSucAVS4:bupmcgh) ([raw file](https://github.com/starkware-libs/papyrus/blob/52e98d151d0881adf158aeb4264632cb9c835762/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
> ```Python
>         command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
>         result = subprocess.run(command, shell=True, capture_output=True, text=True)
>         return result.stdout.strip()
> ```

Let's return either `None` or an `int`, not a string. And add a short comment to explain why `None` can occur (either papyrus isn't ready or consensus has yet to be reached on any height).



_Code quote:_
```Python
    def get_height(self):
        port = self.monitoring_gateway_server_port
        command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        return result.stdout.strip()
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 70 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kQ9B242tfiwr6ddPO:-O1kQ9B242tfiwr6ddPP:bjolz3u) ([raw file](https://github.com/starkware-libs/papyrus/blob/52e98d151d0881adf158aeb4264632cb9c835762/crates/sequencing/papyrus_consensus/run_consensus.py#L70)):*
> ```Python
>         # Check if the height hasn't updated within the stagnation timeout period.
>         # Collect the IDs of the nodes that have stagnated.
>         if height != "" and (curr_time - last_update) > stagnation_timeout:
> ```

I think the code is clear enough to have no comment.



_Suggestion:_
```Python
        if height is not None and (curr_time - last_update) > stagnation_timeout:
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kPkwV49zipSucAVS3:-O1kTFZqE2KykJ-qRJ6S:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/52e98d151d0881adf158aeb4264632cb9c835762/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's return either `None` or an `int`, not a string. And add a short comment to explain why `None` can occur (either papyrus isn't ready or consensus has yet to be reached on any height).
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 70 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kQ9B242tfiwr6ddPO:-O1kTCQB-7phUwb1S82o:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/52e98d151d0881adf158aeb4264632cb9c835762/crates/sequencing/papyrus_consensus/run_consensus.py#L70)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think the code is clear enough to have no comment.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 37 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kWCVE6CxI-Z4VXyhM:-O1kWCVE6CxI-Z4VXyhN:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/3d2580a5e184ea5d28ca4b247cfb657923c6a768/crates/sequencing/papyrus_consensus/run_consensus.py#L37)):*
> ```Python
>         command = f"curl -s -X GET http://localhost:{port}/monitoring/metrics | grep -oP 'papyrus_consensus_height \\K\\d+'"
>         result = subprocess.run(command, shell=True, capture_output=True, text=True)
>         # returns the current consensus height, or None if node is not ready or consensus has not yet reached any height.
> ```





_Suggestion:_
```Python
        # returns the most recently decided height, or None if node is not ready or consensus has not yet reached any height.
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 67 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kWN3b7bDrLFIg8nie:-O1kWN3b7bDrLFIg8nif:by00ie) ([raw file](https://github.com/starkware-libs/papyrus/blob/3d2580a5e184ea5d28ca4b247cfb657923c6a768/crates/sequencing/papyrus_consensus/run_consensus.py#L67)):*
> ```Python
>         (height, last_update) = node.check_height()
>         print(f"Node: {node.validator_id}, height: {height}")
>         if height and (curr_time - last_update) > stagnation_timeout:
> ```

What happens if height is 0? I think we want `height is not None`. In general we try to be explicit about our checks and not rely on pythons truth conversions. Please check the rest of this script and make sure we are doing that throughout.



_Code quote:_
```Python
height
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 67 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2216#-O1kWN3b7bDrLFIg8nie:-O1kYbWe5177787qbD3S:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3d2580a5e184ea5d28ca4b247cfb657923c6a768/crates/sequencing/papyrus_consensus/run_consensus.py#L67)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What happens if height is 0? I think we want `height is not None`. In general we try to be explicit about our checks and not rely on pythons truth conversions. Please check the rest of this script and make sure we are doing that throughout.
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
