### PR TITLE
feat(config): support required params

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1094)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1094)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcaOEyo7Fo5SEPTeM80:-NcaOEyo7Fo5SEPTeM81:b-87o52x) ([raw file](https://github.com/starkware-libs/papyrus/blob/2450c577b434de1c84e939379316e7d88000cc43/crates/papyrus_config/src/lib.rs#L84)):*
> ```XML
>                 Value::Bool(_) => Some(SerializationType::Boolean),
>                 Value::String(_) => Some(SerializationType::String),
>                 _ => None,
> ```

Isn't this an error if we got here? 
Consider panic here.



_Code quote:_
```XML
_ => None,
```
___
*[`crates/papyrus_config/src/lib.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcaOmJ_5zzlGga0btjw:-NcaOmJ_5zzlGga0btjx:bsbxaip) ([raw file](https://github.com/starkware-libs/papyrus/blob/2450c577b434de1c84e939379316e7d88000cc43/crates/papyrus_config/src/lib.rs#L86)):*
> ```XML
>                 _ => None,
>             },
>             SerializedContent::PointerTarget(_) => None,
> ```

Consider having a PointerTarget variant to make the code more explicit.



_Code quote:_
```XML
None,
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1094)* status: all files reviewed, 5 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcSdhi-4bFgA6Ltu7Vu:-NcSi_UVDWSXnOLokQSU:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add todo to change the base layer URL to a required param
</blockquote></details>

Done.

___
___
*[`crates/papyrus_config/src/command.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcScLzF6TCnWR5RCNm6:-NcSezKkC99U3xKz9fB_:bwo7mn7) ([raw file](https://github.com/starkware-libs/papyrus/blob/762e77bb7b5955ba16cc124fb9dac2e82f0b30fd/crates/papyrus_config/src/command.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do pointer targets not have a type?
</blockquote></details>

The type will be determined after the pointing will resolve.
___
*[`crates/papyrus_config/src/config_test.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcScyPVD44d-LImFKF0:-NcSfSEx-iML96xctX52:bnwuc3j) ([raw file](https://github.com/starkware-libs/papyrus/blob/762e77bb7b5955ba16cc124fb9dac2e82f0b30fd/crates/papyrus_config/src/config_test.rs#L253)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

consider renaming to "required_param" and "optional_param"
</blockquote></details>

I want to update this config by `custom_config_example.json`.
This file is used for several tests.
___
*[`crates/papyrus_config/src/lib.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcS4Qr4B7quf_o57uGK:-NcSgIsF0F3q1c7lgcWP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5abbcc6abfac005138d28c9ae767ed4a001fbf93/crates/papyrus_config/src/lib.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Make this a method of SerializedContent
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/config_test.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-NcSdb7K5nogyNSpZ8Rc:-NcShkjy29lHFVvjsDz-:bkzfr5b) ([raw file](https://github.com/starkware-libs/papyrus/blob/762e77bb7b5955ba16cc124fb9dac2e82f0b30fd/crates/papyrus_node/src/config/config_test.rs#L19)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

todo?
</blockquote></details>

No, it's description or hint.
The tests here fail if you don't fill here all the required params.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1094#-:-NcabN6A-pBR8WQ2V-rC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1094)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
