### PR TITLE
fix(network): register and use channel test

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7VOl8ZKy_cZlZe-D):*
rename the commit to what's changed not what code part was changed



_Code quote:_
```
register and use channel test
```
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7KyxER1bF6QTp2Vs:-NuZ7KyxER1bF6QTp2Vt:b8runz1) ([raw file](https://github.com/starkware-libs/papyrus/blob/115ba258308021f2dfc24cf36edae2f1b093609e/crates/papyrus_network/src/network_manager/test.rs#L262)):*
> ```XML
>         }
>     }
>     assert_eq!(signed_header_receiver_length, query_limit);
> ```

`signed_header_reciever_collector` is a vector. you don't need to keep count just use the length

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7VOl8ZKy_cZlZe-D):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

rename the commit to what's changed not what code part was changed
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7KyxER1bF6QTp2Vs:-NuZ7jch4oPdbHApAETH:b-qixno0) ([raw file](https://github.com/starkware-libs/papyrus/blob/115ba258308021f2dfc24cf36edae2f1b093609e/crates/papyrus_network/src/network_manager/test.rs#L262)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

`signed_header_reciever_collector` is a vector. you don't need to keep count just use the length
</blockquote></details>

i wont have the vector if the future hasn't completed when the test ends, which is what we are fixing

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7KyxER1bF6QTp2Vs:-NuZ9eZZ4oqyYLyZQvGu:b-3aimc4) ([raw file](https://github.com/starkware-libs/papyrus/blob/115ba258308021f2dfc24cf36edae2f1b093609e/crates/papyrus_network/src/network_manager/test.rs#L262)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

i wont have the vector if the future hasn't completed when the test ends, which is what we are fixing
</blockquote></details>

create a variable and set it inside the select after you `await`

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-NuZ7KyxER1bF6QTp2Vs:-NuZC6dD0-bMaQ00nIHD:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/115ba258308021f2dfc24cf36edae2f1b093609e/crates/papyrus_network/src/network_manager/test.rs#L262)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

create a variable and set it inside the select after you `await`
</blockquote></details>

Done

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1858#-:-NurO0tH6HAOwXcrn3eI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
