### PR TITLE
docs: Added README.adoc, removed README.md.

### PR DESCRIPTION
**Pull request by stoobie**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

Doc edits, clarifications

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

None.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @stoobie)

___
*[`README.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTQxpZ9eqlaOL9bso9:-NiTQxpZ9eqlaOL9bsoA:b-10fn88) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L7)):*
> ```AsciiDoc
> [#about]
> 
> == About
> ```

Where did you take the 'about' section from? I see that only a small part of it was taken from the previous version.
I think it's missing some information. For example, Papyrus is not just used for querying Starknet's state, but also for updating it.
Also, I'm not sure how relevant and how accurate is the 'storage layer' section.
___
*[`README.adoc` line 42 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTT8We3CFRO5VSQUAZ:-NiTT8We3CFRO5VSQUA_:b-t839vy) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L42)):*
> ```AsciiDoc
> . Build and run a Papyrus node with the default configuration by running the following commands:
> -----
> $ mkdir data
> ```

Is the '$' at the start of each command intentional? When you copy-paste it, it copies invalid commands.
(here and elsewhere in the document)
___
*[`README.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTWs4Y-ZiAhssi61wJ:-NiTWs4Y-ZiAhssi61wK:b-hit6v4) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L46)):*
> ```AsciiDoc
> -----
> . See the available command-line arguments by running the following command:
> cargo run --release --package papyrus_node --bin papyrus_node -- --help
> ```

Why did you move this from the 'configuration' section to here?



_Code quote:_
```AsciiDoc
. See the available command-line arguments by running the following command:
cargo run --release --package papyrus_node --bin papyrus_node -- --help
```
___
*[`README.adoc` line 49 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiT_sQx2vFnEOeDXv8f:-NiT_sQx2vFnEOeDXv8g:b-aowefj) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L49)):*
> ```AsciiDoc
> 
> [#configuration]
> === Configuration
> ```

In general, the configuration section seems a bit messy.
It's not clear how to use presets vs. config files, etc.
___
*[`README.adoc` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTVIlr0mhu5VQfPBmJ:-NiTVIlr0mhu5VQfPBmK:bo9iclw) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L57)):*
> ```AsciiDoc
> You can override the default configuration by pointing to your own configuration files with the --config_file command-line option.
> 
> You can create separate configuration files for specific configuration parameters.
> ```

I'm not sure that this is true. Please double-check with Dan.



_Code quote:_
```AsciiDoc
 separate configuration files
```
___
*[`README.adoc` line 124 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTYdgh4lXlrQYoWocF:-NiTYdgh4lXlrQYoWocG:boj2972) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L124)):*
> ```AsciiDoc
>   -v <local-host-data-path>:/app/data \
> 
>   --memory --memory 1g
> ```

--memory should appear once, not twice



_Code quote:_
```AsciiDoc
--memory --memory 1g
```

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`README.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTQxpZ9eqlaOL9bso9:-NiVJ3ms91KFeAmtHkAr:b-2vjma3) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L7)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Where did you take the 'about' section from? I see that only a small part of it was taken from the previous version.
I think it's missing some information. For example, Papyrus is not just used for querying Starknet's state, but also for updating it.
Also, I'm not sure how relevant and how accurate is the 'storage layer' section.
</blockquote></details>

I got the info from https://medium.com/starkware/papyrus-an-open-source-starknet-full-node-396f7cd90202. I added that you can also update Starknet's state.

I can remove the part about storage, but it seems to talk about added value for Papyrus. Why don't you think it's relevant or accurate?

 What else
___
*[`README.adoc` line 42 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTT8We3CFRO5VSQUAZ:-NiVJlTy6t4oU_SJ7BJO:b-umv2n7) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L42)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Is the '$' at the start of each command intentional? When you copy-paste it, it copies invalid commands.
(here and elsewhere in the document)
</blockquote></details>

I removed them all. It's a convention in Linux commands to use $ for regular permissions and # for root permissions.
___
*[`README.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTWs4Y-ZiAhssi61wJ:-NiVK5dc-pANZO6whw1O:bsb9wwn) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L46)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Why did you move this from the 'configuration' section to here?
</blockquote></details>

It's a typical command to run after installing something, and it doesn't make sense to look for information on all command-line arguments in a section called "Configuring"
___
*[`README.adoc` line 49 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiT_sQx2vFnEOeDXv8f:-NiVR_x05DVvQSXb8jKC:bfgc6pg) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L49)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

In general, the configuration section seems a bit messy.
It's not clear how to use presets vs. config files, etc.
</blockquote></details>

I edited it. PTAL. It's stil not clear to me how to specify config files when using a Docker image.
___
*[`README.adoc` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTVIlr0mhu5VQfPBmJ:-NiVRmsrAf_MY8zMRMqi:b-vak8ue) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L57)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I'm not sure that this is true. Please double-check with Dan.
</blockquote></details>

He said that you can use multiple configuration files. Is this different than what I wrote?
___
*[`README.adoc` line 124 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTYdgh4lXlrQYoWocF:-NiVKZRp3ZBgbA6lHdHQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L124)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

--memory should appear once, not twice
</blockquote></details>

Done.

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @stoobie)

___
*[`README.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTQxpZ9eqlaOL9bso9:-NiYY-z_-gcI028IBJe1:b-puz2a5) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L7)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I got the info from https://medium.com/starkware/papyrus-an-open-source-starknet-full-node-396f7cd90202. I added that you can also update Starknet's state.

I can remove the part about storage, but it seems to talk about added value for Papyrus. Why don't you think it's relevant or accurate?

 What else
</blockquote></details>

OK. Yes. I think you can remove the storage section, and reword the beginning as follows:

Papyrus is a Starknet full node implemented in Rust. Papyrus tracks Starknet’s state as it evolves over time, and enables you to query this state and to execute transactions via Starknet’s JSON-RPC.
___
*[`README.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTWs4Y-ZiAhssi61wJ:-NiYb3wU4uyt-rvxSxMk:b-q9bq08) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L46)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

It's a typical command to run after installing something, and it doesn't make sense to look for information on all command-line arguments in a section called "Configuring"
</blockquote></details>

It's a command that shows you the configuration parameters of the system. I think it's better to have it under the configuration section.
___
*[`README.adoc` line 36 at r14](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiYcJmI0gP2bP47Tw68:-NiYcJmI0gP2bP47Tw69:b-nliybo) ([raw file](https://github.com/starkware-libs/papyrus/blob/00e3b943af1e91cdf022abafc413c014ddf0211f/README.adoc#L36)):*
> ```AsciiDoc
> Papyrus is a work in progress.
> 
> *Use it at your own risk.*
> ```

Isn't it too harsh?
Maybe remove the bold font?



_Code quote:_
```AsciiDoc
*Use it at your own risk.*
```

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: 2 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @stoobie)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiZ21K-33fQfo0yICJ2:-NiZ21K-33fQfo0yICJ3:b-h0wq44) (no related file):*
looks like unrelated stuff made it to the PR. probably need to rebase it or something.

___

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: 2 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @stoobie)

___
*[`README.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTWs4Y-ZiAhssi61wJ:-NiZIBtt62n_LycVozcm:brmysy8) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L46)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

It's a command that shows you the configuration parameters of the system. I think it's better to have it under the configuration section.
</blockquote></details>

I checked the command again. All it does is pretty much list the configuration parameters. So I guess it does belong in the configuration section.

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352)* status: 2 of 16 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiZ21K-33fQfo0yICJ2:-NieDxhc3BU83al92xkI:b-896fix) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

looks like unrelated stuff made it to the PR. probably need to rebase it or something.
</blockquote></details>

Done.

___
___
*[`README.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTQxpZ9eqlaOL9bso9:-NiYmpPp5iEXVYY6jUhK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L7)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

OK. Yes. I think you can remove the storage section, and reword the beginning as follows:

Papyrus is a Starknet full node implemented in Rust. Papyrus tracks Starknet’s state as it evolves over time, and enables you to query this state and to execute transactions via Starknet’s JSON-RPC.
</blockquote></details>

Done.
___
*[`README.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiTWs4Y-ZiAhssi61wJ:-NieDL160FvHUxpX_vPF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1ef40800e0c8e902dc7b19401532bd46d147deb1/README.adoc#L46)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I checked the command again. All it does is pretty much list the configuration parameters. So I guess it does belong in the configuration section.
</blockquote></details>

Done.
___
*[`README.adoc` line 36 at r14](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-NiYcJmI0gP2bP47Tw68:-NiYmv8GB-WkMDxIz-2n:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/00e3b943af1e91cdf022abafc413c014ddf0211f/README.adoc#L36)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Isn't it too harsh?
Maybe remove the bold font?
</blockquote></details>

Done.

**Review by OmriEshhar1 — APPROVED** [review]
:lgtm:

> Reviewed 13 of 14 files at r21, 1 of 14 files at r35.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1352#-:-NieLDJMDTvhoaG82R55:bnfp4nl)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
