### PR TITLE
feat(network): create network manager

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1618)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1618?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1617** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1617?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1618** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1618?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1618?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1618)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/network_manager.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1618#-NoMx6sF35hwTbGx4Z_Y:-NoMx6sG7xjRtaORuIEB:b4qk3pn) ([raw file](https://github.com/starkware-libs/papyrus/blob/f1becaa53b7d350d015d55a325c808ecf0f72c92/crates/papyrus_network/src/network_manager.rs#L17)):*
> ```XML
>     Behaviour: PapyrusBehaviour,
> {
>     pub fn new(swarm: Swarm<Behaviour>) -> Self {
> ```

I think it's better to pass the config here and the NetworkManager will create the behaviour

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1618#-:-NoQS3uj3xNiKnXxg44_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1618#-:-NoQlBhq9KWeZI2U21lG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
