### PR TITLE
 Change central_source_integration_test.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [X] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTE0nuL8JUA_3EsNU5D:-NTE0nuL8JUA_3EsNU5E:b-78y7hk) ([raw file](https://github.com/starkware-libs/papyrus/blob/ac6b0a0321d65505a3000edac3a4e56f59bebea3/crates/papyrus_node/src/bin/central_source_integration_test.rs#L17)):*
> ```XML
>     let central_source =
>         CentralSource::new(config.central, VERSION_FULL).expect("Create new client");
>     let last_block_number = BlockNumber(283410);
> ```

It should be 283414. I made a very very stupid mistake while rebasing in commit c77821d. 
___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTE12ib5y8wsf3ByEVD:-NTE12ib5y8wsf3ByEVE:b-gefix4) ([raw file](https://github.com/starkware-libs/papyrus/blob/962d37fd8085cbe5f25b60e6fa479de774330a1d/crates/papyrus_node/src/bin/central_source_integration_test.rs#L17)):*
> ```XML
>     let central_source =
>         CentralSource::new(config.central, VERSION_FULL).expect("Create new client");
>     let last_block_number = BlockNumber(792004);
> ```

I don`t have any good reason for block numbers so I take the same difference between last_block and block marker (283414-283410=794004-792000=4), and around 3000 blocks behind the last block in alpha4 (the last block in external.integration is about 285000).

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTE12ib5y8wsf3ByEVD:-NTJXv1xARk505TpBysm:b-7p7kl) ([raw file](https://github.com/starkware-libs/papyrus/blob/962d37fd8085cbe5f25b60e6fa479de774330a1d/crates/papyrus_node/src/bin/central_source_integration_test.rs#L17)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don`t have any good reason for block numbers so I take the same difference between last_block and block marker (283414-283410=794004-792000=4), and around 3000 blocks behind the last block in alpha4 (the last block in external.integration is about 285000).
</blockquote></details>

How about the last const number of blocks (say 10)? That is, query the real last block number. This way we might get more interesting blocks. 
___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTJXtBJ2hhsi1oUxlNJ:-NTJXtBJ2hhsi1oUxlNK:b-85x9up) ([raw file](https://github.com/starkware-libs/papyrus/blob/962d37fd8085cbe5f25b60e6fa479de774330a1d/crates/papyrus_node/src/bin/central_source_integration_test.rs#L32)):*
> ```XML
> 
>     let mut state_marker = BlockNumber(792000);
>     let header_stream = central_source.stream_state_updates(state_marker, last_block_number).fuse();
> ```

Please rename.



_Code quote:_
```XML
header_stream
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTYmdL7-XInMnp7_DaL:-NTYmdL7-XInMnp7_DaM:b-jrxywn) ([raw file](https://github.com/starkware-libs/papyrus/blob/cc377f5fd0b1cbabfc4c9b6154e1ad19614ee545/crates/papyrus_node/src/bin/central_source_integration_test.rs#L12)):*
> ```XML
> use tokio_stream::StreamExt;
> 
> const STREAM_LENGTH: u64 = 10;
> ```

Add an empty line?
___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTYn2iz3kxEqTQdPCSo:-NTYn2iz3kxEqTQdPCSp:bs6w29l) ([raw file](https://github.com/starkware-libs/papyrus/blob/cc377f5fd0b1cbabfc4c9b6154e1ad19614ee545/crates/papyrus_node/src/bin/central_source_integration_test.rs#L28)):*
> ```XML
>         .expect("Create new client");
>     let last_block_number = central_source
>         .starknet_client
> ```

Please use `get_block_marker`.



_Code quote:_
```XML
.starknet_client
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/610#-NTYn2iz3kxEqTQdPCSo:-NUGBy-u4G1KIPOCV85e:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/cc377f5fd0b1cbabfc4c9b6154e1ad19614ee545/crates/papyrus_node/src/bin/central_source_integration_test.rs#L28)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use `get_block_marker`.
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/610)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
