### PR TITLE
add test from_thin_transaction_output

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/774)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #771** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/771" target="_blank">Graphite</a> 
    * **PR #767** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/767" target="_blank">Graphite</a> 
      * **PR #772** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/772" target="_blank">Graphite</a> 
        * **PR #770** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/770" target="_blank">Graphite</a> 
          * **PR #773** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/773" target="_blank">Graphite</a> 
            * **PR #774** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/774" target="_blank">Graphite</a>  👈
          * **PR #763** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/763" target="_blank">Graphite</a> 
          * **PR #762** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/762" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/774?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/774)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/774#-NZLeF8n5rAA_B_FwMqF:-NZLeF8n5rAA_B_FwMqG:bzghgfg) ([raw file](https://github.com/starkware-libs/papyrus/blob/f952b3ef7059eb2f9964df53a1877ec480041b4c/crates/papyrus_gateway/src/gateway_test.rs#L154)):*
> ```XML
> 
> #[tokio::test]
> async fn test_from_thin_transaction_output() {
> ```

Move this test to a new file called transaction_test.rs in the same dir
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/774#-NZLfArT-NkGFcUhX-Ux:-NZLfArT-NkGFcUhX-Uy:b-n741e6) ([raw file](https://github.com/starkware-libs/papyrus/blob/f952b3ef7059eb2f9964df53a1877ec480041b4c/crates/papyrus_gateway/src/gateway_test.rs#L155)):*
> ```XML
> #[tokio::test]
> async fn test_from_thin_transaction_output() {
>     let thin_output = ThinTransactionOutput::Declare(ThinDeclareTransactionOutput::default());
> ```

Try to see if you can save code dup or at least separate the test to multiple cases

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/774)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/774#-NZLeF8n5rAA_B_FwMqF:-NZLlr_8-CFWNYSpmkH2:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f952b3ef7059eb2f9964df53a1877ec480041b4c/crates/papyrus_gateway/src/gateway_test.rs#L154)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this test to a new file called transaction_test.rs in the same dir
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/774#-NZLfArT-NkGFcUhX-Ux:-NZLlsJo1Ee1mUrLKTOP:b-w95v9d) ([raw file](https://github.com/starkware-libs/papyrus/blob/f952b3ef7059eb2f9964df53a1877ec480041b4c/crates/papyrus_gateway/src/gateway_test.rs#L155)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to see if you can save code dup or at least separate the test to multiple cases
</blockquote></details>

getting serious with these macros

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/774#-:-NZLmkZi3ViPAkq46Ndd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
