### PR TITLE
fix: put none in commitments if they come from a deprecated formula

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2180)

### CODE REVIEW

**Review by matan-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2180)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2180#-O0mAvmF54Gsu8WPxSws:-O0mAvmF54Gsu8WPxSwt:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/460329aea8d110fd62d8b2f685754681e2885166/crates/papyrus_protobuf/src/converters/header.rs#L202)):*
> ```XML
>                         })?
>                         .try_into()?,
>                 )))
> ```





_Suggestion:_
```XML
                let root = state_diff_commitment
                    .root
                    .ok_or(ProtobufConversionError::MissingField {
                        field_description: "StateDiffCommitment::root",
                    })?
                    .try_into()?;
                Ok::<_, ProtobufConversionError>(StateDiffCommitment(PoseidonHash(root)))
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2180)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2180#-O0mAvmF54Gsu8WPxSws:-O0mJBLG8o-a0CyjsUT3:bd7e763) ([raw file](https://github.com/starkware-libs/papyrus/blob/460329aea8d110fd62d8b2f685754681e2885166/crates/papyrus_protobuf/src/converters/header.rs#L202)):*
> ```XML
>                         })?
>                         .try_into()?,
>                 )))
> ```

I prefer the  current way

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2180#-:-O0mT7_PAxHIUUth93NH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
