### PR TITLE
prepare v0.3.0 for v0.4.0 addition

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/875)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #829** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/829" target="_blank">Graphite</a> 
    * **PR #830** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/830" target="_blank">Graphite</a> 
      * **PR #831** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/831" target="_blank">Graphite</a> 
        * **PR #832** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/832" target="_blank">Graphite</a> 
          * **PR #833** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/833" target="_blank">Graphite</a> 
            * **PR #834** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/834" target="_blank">Graphite</a> 
              * **PR #837** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/837" target="_blank">Graphite</a> 
                * **PR #845** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/845" target="_blank">Graphite</a> 
                  * **PR #846** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/846" target="_blank">Graphite</a> 
                    * **PR #850** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/850" target="_blank">Graphite</a> 
                      * **PR #875** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/875" target="_blank">Graphite</a>  👈
                      * **PR #872** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/872" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/875?utm_source=stack-comment).

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/875#-Na1XTbiB34x9Ep2q7_K:-Na1XTbiB34x9Ep2q7_L:b-867xyf) ([raw file](https://github.com/starkware-libs/papyrus/blob/c58035f11170e95e81aa26b1a64f8ae5655db2a3/crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs#L87)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> // pub struct EntryPointOffset(pub usize);
> ```

Please remove.



_Code quote:_
```XML
// pub struct EntryPointOffset(pub usize);
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/875#-Na1Xd0681w-Ntv7bTNn:-Na1Xd0681w-Ntv7bTNo:b-5wqa6v) ([raw file](https://github.com/starkware-libs/papyrus/blob/c58035f11170e95e81aa26b1a64f8ae5655db2a3/crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs#L88)):*
> ```XML
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> // pub struct EntryPointOffset(pub usize);
> pub struct EntryPointOffset(pub u64);
> ```

Why do we need this struct? Can we use u64 directly?



_Code quote:_
```XML
pub struct EntryPointOffset(pub u64);
```

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/875)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/875#-Na1XTbiB34x9Ep2q7_K:-Na1YuQPC7UCc_ku3IHw:bmjt7f) ([raw file](https://github.com/starkware-libs/papyrus/blob/c58035f11170e95e81aa26b1a64f8ae5655db2a3/crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs#L87)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

sorry my bad. should be usize
___
*[`crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/875#-Na1Xd0681w-Ntv7bTNn:-Na1YwmXBW7_3m2ARnA4:b-78l3ge) ([raw file](https://github.com/starkware-libs/papyrus/blob/c58035f11170e95e81aa26b1a64f8ae5655db2a3/crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs#L88)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need this struct? Can we use u64 directly?
</blockquote></details>

I don't think so. we need to cast the `starknet_api::deprecated_contract_class::EntryPointOffset` to this type (let's say usize).
the only place we can define the `From` trait for a primitive is the file the original `EntryPointOffset` was defined.
so I guess the only option to use a primitive is if we define this trait for conversion on starknet_api

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/875#-:-Na1gKtG1AXt3QpCJqUW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
