### PR TITLE
feat(network): add peer address struct to network config

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* **#1743** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1743?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1743?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_T5bh8mmaxE4JUyfX:-Nr_T5bh8mmaxE4JUyfY:btvqjxm) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/lib.rs#L41)):*
> ```XML
> 
> #[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
> pub struct PeerAddress {
> ```

Consider adding the word Config inside the name
___
*[`crates/papyrus_network/src/lib.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_TAGc8byXRjt7Gqfq:-Nr_TAGc8byXRjt7Gqfr:b-qu01cu) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/lib.rs#L45)):*
> ```XML
>     pub ip: String,
>     pub tcp_port: u16,
>     // TODO: Add quic_port
> ```

Change to TODO: Add quic_port as optional, and make tcp_port optional as well while enforcing at least one of them to have value
___
*[`crates/papyrus_network/src/lib.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_Thr3DbPjQK_10j6B:-Nr_Thr3DbPjQK_10j6C:bfivb2k) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/lib.rs#L186)):*
> ```XML
> impl Default for PeerAddress {
>     fn default() -> Self {
>         Self { peer_id: None, ip: format!("127.0.0.1"), tcp_port: 10002 }
> ```

I think PeerAddress should not have a default
___
*[`crates/papyrus_network/src/bin/p2p_integration_endpoint.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_TrQyAS-RJbym1u36:-Nr_TrQyAS-RJbym1u37:b-3ynxu6) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/bin/p2p_integration_endpoint.rs#L46)):*
> ```XML
>     );
>     if let Some(dial_address) = args.dial_address.as_ref() {
>         network_manager.dial(dial_address);
> ```

Move this to the peer config (or add a TODO to do so)
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_U0L4BTJFTp-e7kGu:-Nr_U0L4BTJFTp-e7kGv:blxyw7j) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/network_manager/mod.rs#L46)):*
> ```XML
> impl<DBExecutorT: DBExecutor, SwarmT: SwarmTrait> GenericNetworkManager<DBExecutorT, SwarmT> {
>     pub async fn run(mut self) -> Result<(), NetworkError> {
>         if let Some(peer) = self.peer.clone() {
> ```

Consider implementing Copy for PeerAddress
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_UAaIBStEB905HWCl:-Nr_UAaIBStEB905HWCm:b-6rup3z) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/network_manager/mod.rs#L195)):*
> ```XML
>             .peer
>             .clone()
>             .expect("cannot send query without peer")
> ```

Capitalization

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_Thr3DbPjQK_10j6B:-Nr_lBOpBDJNndLU6v9F:bidngw4) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/lib.rs#L186)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think PeerAddress should not have a default
</blockquote></details>

it must have a default for the config crate. the default values here allows you to run 2 nodes on one pc with one of them just change the peer.#is_none to false
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_U0L4BTJFTp-e7kGu:-Nr_m4WWEqJvHxf0DH9K:b-4aeqhw) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/network_manager/mod.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider implementing Copy for PeerAddress
</blockquote></details>

String does not implement copy..

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-Nr_Thr3DbPjQK_10j6B:-NriFk1jCD2t3PnGr49f:b-5s5ubo) ([raw file](https://github.com/starkware-libs/papyrus/blob/88cae1e710ca98335478451b22f89d0f18f2685b/crates/papyrus_network/src/lib.rs#L186)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it must have a default for the config crate. the default values here allows you to run 2 nodes on one pc with one of them just change the peer.#is_none to false
</blockquote></details>

And with the tcp_port in the other changed to 10002
And I don't think it must have default, because the base layer config doesn't have one
@yair-starkware am I right?
Even if NetworkConfig needs to have a default, because it only has Option<PeerAddressConfig> and not PeerAddressConfig, it can have a default without having a default for PeerAddressConfig
___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-NriGZhQ9-NqXxEyR4WY:-NriGZhQ9-NqXxEyR4WZ:b70zq4p) ([raw file](https://github.com/starkware-libs/papyrus/blob/88bb2c0a06f7246f3fbfd76cc31bee9f3ef05774/crates/papyrus_network/src/network_manager/swarm_trait.rs#L54)):*
> ```XML
>             .ip
>             .parse::<Multiaddr>()
>             .expect("string to multiaddr failed")
> ```

Maybe this should be an error and not panic?
I think the best option is to put Multiaddr in the config with custom serializers and then it will be a serde error

**Review by ShahakShama — APPROVED** [review]
> Reviewed 5 of 5 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1743#-:-NrnsFd71kh2cMEsdjdh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
