### PR TITLE
Dvir/general request scenario

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/508)

### CODE REVIEW

**Comment by DvirYo-starkware** [comment]
First commit add the general_request scenario.
Second commit delete the old scenarios.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/508)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/508#-NPC6kxS0yny6VFXtluZ:-NPC6kxTEQJ_qxyah3Km:b-t3fawv) (no related file):*
the last commit changes the results dump to be by request. we maybe decided to change this in the future but this is good for what we have now and the changes in the future will be easy.

___

**Comment by DvirYo-starkware** [comment]
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

the last commit changes the results dump to be by request. we maybe decided to change this in the future but this is good for what we have now and the changes in the future will be easy.
</blockquote></details>

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/508)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
