### PR TITLE
Yoav/config/dereference

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?

- Replace '$' references in the config map with the target values.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWQoJtDd_y0x4BkoaX:-NZWQoJtDd_y0x4BkoaY:bazj41j) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/config_test.rs#L135)):*
> ```XML
>     let invalid_map =
>         BTreeMap::from([ser_param("b", &json!(format!("{}a", POINTER_PREFIX)), "Pointer to a.")]);
>     assert!(replace_pointers(&invalid_map).is_err());
> ```

Assert the exact error type



_Code quote:_
```XML
assert!(replace_pointers(&invalid_map).is_err());
```
___
*[`crates/papyrus_config/src/lib.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWT4V302Ge5Fa35CS-:-NZWT4V302Ge5Fa35CS0:bunwldg) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/lib.rs#L128)):*
> ```XML
> /// Sets values for the pointer params in the config.
> pub fn replace_pointers(
>     config_map: &BTreeMap<ParamPath, SerializedParam>,
> ```

You should either consume the existing object or mut borrow it.



_Code quote:_
```XML
config_map: &BTreeMap<ParamPath, SerializedParam>,
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yair-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWQoJtDd_y0x4BkoaX:-NZaV3oj1T01eG3m0viN:bakfxnm) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/config_test.rs#L135)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Assert the exact error type
</blockquote></details>

Not all the error types in `SubConfigError` implement `PartialEq`.
___
*[`crates/papyrus_config/src/lib.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWT4V302Ge5Fa35CS-:-NZaVEQOCs8hgUDH4E3U:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/lib.rs#L128)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You should either consume the existing object or mut borrow it.
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_48qjo-OscExO5_64_:-N_48qjo-OscExO5_64a:bpg1w49) (no related file):*
I discussed this with @dan-starkware, and we both think that it is more important that the dumped file be readable than the code simplicity.
Please try to manipulate the serde functions to replace the enum layer (RawParam/PointerParam) with $ in the value.

___
___
*[`crates/papyrus_config/src/config_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWQoJtDd_y0x4BkoaX:-NZabB2UBAMIr9EfmB5c:bal3ryh) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/config_test.rs#L135)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Not all the error types in `SubConfigError` implement `PartialEq`.
</blockquote></details>

You can use assert_matches

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @TzahiTaub, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_48qjo-OscExO5_64_:-N_D9rnLAUH6Ixk0teoY:byrozqo) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I discussed this with @dan-starkware, and we both think that it is more important that the dumped file be readable than the code simplicity.
Please try to manipulate the serde functions to replace the enum layer (RawParam/PointerParam) with $ in the value.
</blockquote></details>

The enum was removed.

___
___
*[`crates/papyrus_config/src/config_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/801#-NZWQoJtDd_y0x4BkoaX:-N_D9w5y-IwUpbWpTIwV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1bca98fb9aebff9eb19335ada4f8260a68b1cf97/crates/papyrus_config/src/config_test.rs#L135)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can use assert_matches
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: all files reviewed, 4 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DCnKF-eXHH4va8gPU:-N_DCnKF-eXHH4va8gPV:bjxc36g) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_config/src/config_test.rs#L173)):*
> ```XML
>     assert_eq!(config_map["a"], config_map["c"]);
> 
>     let err = update_config_map_by_pointers(&mut BTreeMap::default(), &pointers_map).err().unwrap();
> ```

Not blocking - 
unwrap_err() 



_Code quote:_
```XML
.err().unwrap();
```
___
*[`crates/papyrus_config/src/lib.rs` line 209 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DDUmn-J1MNOSkATQM:-N_DDUmn-J1MNOSkATQN:b-ppssfl) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_config/src/lib.rs#L209)):*
> ```XML
>             pointers_map.insert(param_path.to_owned(), pointer_param.pointer_target);
>         } else {
>             unimplemented!()
> ```

unreachable?
Add a message



_Code quote:_
```XML
unimplemented!()
```
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DEC56AAsqbeR5JB_y:-N_DEC56AAsqbeR5JB_z:bmpc90g) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_node/src/bin/dump_config.rs#L18)):*
> ```XML
> }
> 
> fn get_pointers() -> Vec<(ParamPath, String, Vec<ParamPath>)> {
> ```

Document this function
Also, consider making this a const instead of a function by using lazy static: https://docs.rs/lazy_static/latest/lazy_static/

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @yair-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DCnKF-eXHH4va8gPU:-N_DGrXpE_gTjtcddIZh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_config/src/config_test.rs#L173)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not blocking - 
unwrap_err() 
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 209 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DDUmn-J1MNOSkATQM:-N_DHUZl2L3EzZq7Yixd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_config/src/lib.rs#L209)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

unreachable?
Add a message
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/801#-N_DEC56AAsqbeR5JB_y:-N_DOl1RB5VUHlZoESSe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1a125371612123b09b82a963fef2a29a9f31dd81/crates/papyrus_node/src/bin/dump_config.rs#L18)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Document this function
Also, consider making this a const instead of a function by using lazy static: https://docs.rs/lazy_static/latest/lazy_static/
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/801#-:-N_DPaws0Nb0nm8y63fB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
