### PR TITLE
Implement SerdeConfig trate for the rest configs.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Implement serialization and deserialization for the rest of the configs.

Issue Number: 496

## What is the new behavior?

- Implement `SerdeConfig` for each config.
- Fill the file `default_config.json`.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRrRmK5GM0o_4lV74y):*




_Suggestion:_
```
- 13618bc: Implement SerdeConfig trate for the rest of the configs
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRvY5T0oTpUpBkgNyc:-NYRvY5T0oTpUpBkgNyd:b-17fg2z) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_node/src/config/mod.rs#L68)):*
> ```XML
>                 None => BTreeMap::new(),
>                 Some(sync_config) => append_sub_config_name(sync_config.dump(), "sync"),
>             })
> ```

I don't understand what happens in the case of None. We just won't include `sync` at all in the dump then? This is something awkward that happens as a result of us flattening the fields, since now the fields won't even be documented in the dump. What would we want the JSON to look like in this case?



_Code quote:_
```XML
            .chain(match self.sync {
                None => BTreeMap::new(),
                Some(sync_config) => append_sub_config_name(sync_config.dump(), "sync"),
            })
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRsj3g5mnu2bgP6vyx:-NYRsj3h1Sv--W3t3_EQ:b-8m1rd5) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_storage/src/db/mod.rs#L63)):*
> ```XML
>                         "Path of the node's storage directory, the storage file path will be \
>                          <path>/<chain_id>.
>                     The path is not created automatically.",
> ```

ugly formatting here and in the JSON file produced. At least one of them should look nice :)



_Code quote:_
```XML
                        "Path of the node's storage directory, the storage file path will be \
                         <path>/<chain_id>.
                    The path is not created automatically.",
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware and @TzahiTaub)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRrRmK5GM0o_4lV74y):*
Done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRvY5T0oTpUpBkgNyc:-NYS3v773BqfpCiAp20G:b-2yfrbh) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_node/src/config/mod.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't understand what happens in the case of None. We just won't include `sync` at all in the dump then? This is something awkward that happens as a result of us flattening the fields, since now the fields won't even be documented in the dump. What would we want the JSON to look like in this case?
</blockquote></details>

Good point. I'm adding optional fields to the test.
Fields with None as default will be missing from the JSON.
___
*[`crates/papyrus_storage/src/db/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRsj3g5mnu2bgP6vyx:-NYS-lNN6hXr37cMF-pE:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_storage/src/db/mod.rs#L63)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

ugly formatting here and in the JSON file produced. At least one of them should look nice :)
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/papyrus_config/src/config_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYSdS1B1WE7eTc-DtWS:-NYSdS1B1WE7eTc-DtWT:b-oz1ls4) ([raw file](https://github.com/starkware-libs/papyrus/blob/2164f6a19b541ef49e0834df0559f729cc4e50bb/crates/papyrus_config/src/config_test.rs#L91)):*
> ```XML
>             SerializedParam { description: String::from("This is o."), value: json!(2) },
>         ),
>     ]);
> ```

A couple style things that to me look nicer, but I'll accept your opinion if you don't like it.

1. WDYT of using the maplit crate instead of BTreeMap?
2. I prefer `to_string/to_owned` more than `String::from`. I don't have a real reason, I just find it a little easier to read.



_Suggestion:_
```XML
    let expected = btreemap!{
        "inner.a".to_string() => SerializedParam { description: "This is a.".to_string(), value: json!(0) },
        "b".to_string() => SerializedParam { description: "This is b.".to_string(), value: json!(1) },
        "some_optional.o".to_owned() => SerializedParam { description: "This is o.".to_owned(), value: json!(2) },
    };
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRvY5T0oTpUpBkgNyc:-NYSfCqbEMf0sqhlXZrs:b-qcfdhb) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_node/src/config/mod.rs#L68)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Good point. I'm adding optional fields to the test.
Fields with None as default will be missing from the JSON.
</blockquote></details>

Probably worth adding this as a comment. Either in the test to point out this is what we want or maybe even at the trait definition to make it clear that this is what we expect?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @matan-starkware and @TzahiTaub)

___
*[`crates/papyrus_config/src/config_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYSdS1B1WE7eTc-DtWS:-NYT55LH520r-PS8Kkk1:b-1pv41t) ([raw file](https://github.com/starkware-libs/papyrus/blob/2164f6a19b541ef49e0834df0559f729cc4e50bb/crates/papyrus_config/src/config_test.rs#L91)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

A couple style things that to me look nicer, but I'll accept your opinion if you don't like it.

1. WDYT of using the maplit crate instead of BTreeMap?
2. I prefer `to_string/to_owned` more than `String::from`. I don't have a real reason, I just find it a little easier to read.
</blockquote></details>

1. The cargo auto-formatting doesn't edit code inside macros.
2. I changed it in this file.
___
*[`crates/papyrus_node/src/config/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/764#-NYRvY5T0oTpUpBkgNyc:-NYT6nUF04HCesQ4jKPG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/13618bc2aa7235ba497652509b8f6183355043a3/crates/papyrus_node/src/config/mod.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Probably worth adding this as a comment. Either in the test to point out this is what we want or maybe even at the trait definition to make it clear that this is what we expect?
</blockquote></details>

Done.

**Review by matan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/764)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
