### PR TITLE
refactor(network): remove return value from assign peer to session

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1995)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1995)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Nxwcjok6vcItVSkNXjF:-Nxwc_e72NAVTSsomvCm:b7mlzx3) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/mod.rs#L141)):*
> ```XML
>             return;
>         }
>         if let Some((peer_id, peer)) = peer {
> ```

Use the let-else syntax instead
```
let Some((peer_id, peer)) = peer else {
    return;
}
// TODO...
```
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kGnC8IY0Z6iCx-O_:-Ny-kGnC8IY0Z6iCx-Oa:bwhx4u0) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L128)):*
> ```XML
>     assert_matches!(
>         peer_manager.sessions_received_when_no_peers.last().unwrap(),
>         _outbound_session_id
> ```

This does nothing. You need to add some match argument here.
You can use assert_eq! instead. We should've used assert_eq! here in the original code too
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kTjc8FwoJ6knXslA:-Ny-kTjc8FwoJ6knXslB:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L178)):*
> ```XML
>     assert_matches!(
>         peer_manager.sessions_received_when_no_peers.last().unwrap(),
>         _outbound_session_id
> ```

Same
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kYKP4PNhSXFFOEcD:-Ny-kYKQ91nEahtXSy_f:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L335)):*
> ```XML
>     assert_matches!(
>         peer_manager.sessions_received_when_no_peers.last().unwrap(),
>         _outbound_session_id
> ```

Same

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1995)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Nxwcjok6vcItVSkNXjF:-Ny0MZiWEGT5OzDKG7NQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/mod.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use the let-else syntax instead
```
let Some((peer_id, peer)) = peer else {
    return;
}
// TODO...
```
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kGnC8IY0Z6iCx-O_:-Ny0Mavr0bKH22zO3DT_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L128)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This does nothing. You need to add some match argument here.
You can use assert_eq! instead. We should've used assert_eq! here in the original code too
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kTjc8FwoJ6knXslA:-Ny0Mbiq86nFqGliQlc_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L178)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-Ny-kYKP4PNhSXFFOEcD:-Ny0McAj6gB6STjYtMLN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d15a17bc69854362ecee1d65acfeeeec91bfe8a/crates/papyrus_network/src/peer_manager/test.rs#L335)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1995#-:-NyEX_H50zpDGvX4m5kq:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
