### PR TITLE
feat(network): close inbound session after sending fin

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1854)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1854)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTXUFOEXdqGNTFxAFw):*




_Suggestion:_
```
feat
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYiJJCxU8c9QUGMjJ:-NuTYiJK9nb9qOhUQsBY:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/mod.rs#L256)):*
> ```XML
>         }
>         let (data, inbound_session_id) = res;
>         let fin = matches!(data, Data::Fin(_));
> ```





_Suggestion:_
```XML
is_fin
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYuXc-ZO1mph9rD3S:-NuTYuXc-ZO1mph9rD3T:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/mod.rs#L264)):*
> ```XML
>         if fin {
>             self.swarm.close_inbound_session(inbound_session_id).unwrap_or_else(|e| {
>                 error!("Failed to close session. Session id not found error: {e:?}")
> ```





_Suggestion:_
```XML
Failed to close session after Fin. Session id: {inbound_session_id:?} not found error: {e:?}
```
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYb667AAzmtx7z3Jc:-NuTYb667AAzmtx7z3Jd:bqrgaek) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/test.rs#L159)):*
> ```XML
>         0
>     }
>     fn close_inbound_session(
> ```

nice but also use it in a test

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1854)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTXUFOEXdqGNTFxAFw):*
Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYiJJCxU8c9QUGMjJ:-NuTvjf5CofqWa8tXyw7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/mod.rs#L256)):*
> ```XML
>         }
>         let (data, inbound_session_id) = res;
>         let fin = matches!(data, Data::Fin(_));
> ```

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYuXc-ZO1mph9rD3S:-NuTwCVz71ndkOvbM-V0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/mod.rs#L264)):*
> ```XML
>         if fin {
>             self.swarm.close_inbound_session(inbound_session_id).unwrap_or_else(|e| {
>                 error!("Failed to close session. Session id not found error: {e:?}")
> ```

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuTYb667AAzmtx7z3Jc:-NuTvgcfA38YjPjAE6vo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/14e1d418253e87f2cc17cc85ecaff0f2176aa41d/crates/papyrus_network/src/network_manager/test.rs#L159)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

nice but also use it in a test
</blockquote></details>

Done.

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1854)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 376 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ9DUl07QL8wVlxdpz:-NuZ9DUl07QL8wVlxdq-:b-j6rd9r) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L376)):*
> ```XML
> 
> #[tokio::test]
> async fn close_inbound_session() {
> ```

nice test!
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ88qABNFXbW7lnHSb:-NuZ88qABNFXbW7lnHSc:b-9e8oi9) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L377)):*
> ```XML
> #[tokio::test]
> async fn close_inbound_session() {
>     
> ```

remove space
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 381 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ8GZ66vN9XVOU2oGd:-NuZ8GZ66vN9XVOU2oGe:b-s2htof) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L381)):*
> ```XML
>     let query_limit = 5;
>     let start_block_number = 0;
> ```

remove space here
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 382 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ8ZE_3SLO0bMU39Iy:-NuZ8ZE_3SLO0bMU39Iz:bo4gstx) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L382)):*
> ```XML
>     let start_block_number = 0;
> 
>     let query = InternalQuery {
> ```

what do you do with this query?
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 388 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ8JPC0ctDUX7hcZfq:-NuZ8JPC0ctDUX7hcZfr:btar73m) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L388)):*
> ```XML
>         step: 1,
>     };
>     // get query bytes
> ```

you can add a space here if you want
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 390 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-NuZ9IqfDpBH2p3bAlGB:-NuZ9IqfDpBH2p3bAlGC:b4rk7fy) ([raw file](https://github.com/starkware-libs/papyrus/blob/3adcf4d9ae82d93ef9fe1e4f666b66008c05e611/crates/papyrus_network/src/network_manager/test.rs#L390)):*
> ```XML
>     // get query bytes
>     let mut query_bytes = vec![];
>     protobuf::BlockHeadersRequest {
> ```

did you try to use default here? the content of the query shouldn't matter for this test

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1854#-:-NurMiMh5HCXkuamy5GO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
