### PR TITLE
Dvir/create block number file

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr2hseE-M3rnB5kN7Y:-NPr2hsf-Q7-IHT6F8Fw:b-qwyquc) (no related file):*
first commit: create a file with the last block number for the load test and a function to get this number
second: create the block_number file
third: Clippy

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr3DLc6VQlK-akuWhv:-NPr3DLd5dIv1PR0czMy:bxh5llj) (no related file):*
To create the files, run:
        cargo run -r -p papyrus_load_test -- --create_files http://127.0.0.1:8080

___
___
*[`crates/papyrus_load_test/src/create_files.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr2x3QDaDU4Ds8z9nk:-NPr2x3QDaDU4Ds8z9nl:b680882) ([raw file](https://github.com/starkware-libs/papyrus/blob/8871b33b2b8fda8e6c2343938ee5719bb05f2b1b/crates/papyrus_load_test/src/create_files.rs#L10)):*
> ```XML
> pub async fn create_files(node_address: &str) {
>     last_block_number(node_address).await;
>     block_number(5);
> ```

We should decide on this number
___
*[`crates/papyrus_load_test/src/lib.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr32eOEclNkvKW3o_J:-NPr32eOEclNkvKW3o_K:b-w9kzu4) ([raw file](https://github.com/starkware-libs/papyrus/blob/8871b33b2b8fda8e6c2343938ee5719bb05f2b1b/crates/papyrus_load_test/src/lib.rs#L40)):*
> ```XML
> 
> // Returns the last block number for which this load test is relevant.
> pub fn get_last_block_number() -> u64 {
> ```

Each time to get this number we need to read from a file. This is a small file so I think this is fine.



_Code quote:_
```XML
// Returns the last block number for which this load test is relevant.
pub fn get_last_block_number() -> u64 {
    fs::read_to_string("crates/papyrus_load_test/src/resources/last_block_number.txt")
        .unwrap()
        .parse::<u64>()
        .unwrap()
}
```

**Comment by DvirYo-starkware** [comment]
I decided to save the last block number in a file because this is interesting information to know how much the test is relevant.
The other option is to ask the node each time what is the last block, this approach has problems. first, this number can change during the load test, second, it takes more time than reading from a file.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr3DLc6VQlK-akuWhv:-NPrOwsh31H2AzgG-TQ7:bd0y0et) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

To create the files, run:
        cargo run -r -p papyrus_load_test -- --create_files http://127.0.0.1:8080
</blockquote></details>

To create the files, run:
cargo run -r -p papyrus_load_test -- --create_files 127.0.0.1:8080

___

**Comment by dan-starkware** [comment]
unwrap vs. expect

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQ0ADiz9yPiygf7nXdD:-NQ50RmG17yEFlzUYYQ9:bw2ezsj) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

unwrap vs. expect 
</blockquote></details>

I thought about it again, and it is not clear to me when to use unwrap or expect

___
___
*[`crates/papyrus_load_test/src/create_files.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQ-tqRS7STXoXJFA5CD:-NQ0MAzI04jo0U2IC8I-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/863130b4d50748dd7a6f491448992539e77dd465/crates/papyrus_load_test/src/create_files.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Done.
___
*[`crates/papyrus_load_test/src/create_files.rs` line 17 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQ-uGIBDGNYvsS-J_hS:-NQ0ZEc46awoMqk-lLMT:b-v6rucg) ([raw file](https://github.com/starkware-libs/papyrus/blob/863130b4d50748dd7a6f491448992539e77dd465/crates/papyrus_load_test/src/create_files.rs#L17)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use consts for file names and the resources directory. 
</blockquote></details>

Done.
I added a function that returns the path to the file inside the resources folder given the file name. function "path_to_resources" in libs
___
*[`crates/papyrus_load_test/src/lib.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NPr32eOEclNkvKW3o_J:-NQ5-HmZDnLMRjUZ32Jc:b-x1ifuu) ([raw file](https://github.com/starkware-libs/papyrus/blob/8871b33b2b8fda8e6c2343938ee5719bb05f2b1b/crates/papyrus_load_test/src/lib.rs#L40)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Let's talk f2f
* As argument
* Lazy initialization
* At compile time
</blockquote></details>

done, using OnceCell

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_load_test/Cargo.toml` line 16 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQK-rtW6IV1LGkISItE:-NQK-rtW6IV1LGkISItF:bbxqmii) ([raw file](https://github.com/starkware-libs/papyrus/blob/886ee46d1eb33fdac4e8ff08efab742121a9e4f9/crates/papyrus_load_test/Cargo.toml#L16)):*
> ```TOML
> reqwest = { version = "0.11" }
> test_utils = { path = "../test_utils" }
> once_cell = { version = "1.17.1" }
> ```

Please keep the list sorted by name



_Code quote:_
```TOML
once_cell = { version = "1.17.1" }
```
___
*[`crates/papyrus_load_test/src/create_files.rs` line 17 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQ-uGIBDGNYvsS-J_hS:-NQJjbSV02uqPjmRhgU1:b-qo3606) ([raw file](https://github.com/starkware-libs/papyrus/blob/863130b4d50748dd7a6f491448992539e77dd465/crates/papyrus_load_test/src/create_files.rs#L17)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Done.
I added a function that returns the path to the file inside the resources folder given the file name. function "path_to_resources" in libs
</blockquote></details>

So maybe path_in_resources or full_path are better names
___
*[`crates/papyrus_load_test/src/create_files.rs` line 9 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQJjtNk9SgdsUZ5-TXM:-NQJjtNk9SgdsUZ5-TXN:br91x9d) ([raw file](https://github.com/starkware-libs/papyrus/blob/886ee46d1eb33fdac4e8ff08efab742121a9e4f9/crates/papyrus_load_test/src/create_files.rs#L9)):*
> ```XML
> use crate::{get_random_block_number, path_to_resources};
> 
> const BLOCK_NUMBER_NUMS: u32 = 5;
> ```

Please document.
Also, consider replacing the NUMS suffix, maybe COUNT



_Code quote:_
```XML
const BLOCK_NUMBER_NUMS: u32 = 5;
```
___
*[`crates/papyrus_load_test/src/create_files.rs` line 18 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQK-6tFExVgVKLdtbXb:-NQK-6tFExVgVKLdtbXc:bp8zlz5) ([raw file](https://github.com/starkware-libs/papyrus/blob/886ee46d1eb33fdac4e8ff08efab742121a9e4f9/crates/papyrus_load_test/src/create_files.rs#L18)):*
> ```XML
> }
> 
> // Creates the block_number.txt file. Write to the file block_num block numbers.
> ```

Please fix the variable name and mention that the numbers are chosen randomly. 



_Code quote:_
```XML
block_num block
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/create_files.rs` line 18 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/536#-NQK-6tFExVgVKLdtbXb:-NQKIXyo50Pc6ozGu8aN:b-h05z96) ([raw file](https://github.com/starkware-libs/papyrus/blob/886ee46d1eb33fdac4e8ff08efab742121a9e4f9/crates/papyrus_load_test/src/create_files.rs#L18)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix the variable name and mention that the numbers are chosen randomly. 
</blockquote></details>

Done in the constant definition. The number of blocks in the file will not be random.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r5, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/536#-:-NQPiCo368pGvXEkGFS2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Pull request merged**
