### PR TITLE
feat(storage)!: add functionality to write thin state diff

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJWTnk5Iu2oJQXTYUI:-NuJWTnk5Iu2oJQXTYUJ:b-u66nb6) (no related file):*
Is the plan to separate the `append_state_diff` to `append_thin_state_diff` & `append_class`? I think it's a bad idea to keep both `append_state_diff` and `append_thin_state_diff`

___
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJTfa2E1fow94RcxSv:-NuJTfa2E1fow94RcxSw:bq9w7w4) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/serialization/serializers.rs#L302)):*
> ```XML
>         Body = 1,
>         State = 2,
>         Class = 3,
> ```

This is a breaking change, need to bump the major storage version or write a migration.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJUlrB2iAd21ZE0_FR:-NuJUlrB2iAd21ZE0_FS:bcwhhau) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L154)):*
> ```XML
>     // To enforce that no commit happen after a failure, we consume and return Self on success.
>     // TODO(shahak): Consider renaming to append_state_diff_with_classes and renaming
>     // append_thin_state_diff to append_state_diff.
> ```

IMO append_state_diff_with_classes, append_thin_state_diff



_Code quote:_
```XML
    // TODO(shahak): Consider renaming to append_state_diff_with_classes and renaming
    // append_thin_state_diff to append_state_diff.
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJVFFeCeN_qQYPo1e7:-NuJVFFeCeN_qQYPo1e8:b-dcl13q) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L396)):*
> ```XML
>         else {
>             // We downloaded the state diff where the class was declared but not the class itself.
>             return Ok(None);
> ```

IMO check the the class marker before returning None (keep the error)
___
*[`crates/papyrus_storage/src/state/mod.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJX_pG87ai_Vr3O0kp:-NuJX_pG87ai_Vr3O0kq:bkts3kb) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f1e1132120907015fece45fb4f7108a2362e59/crates/papyrus_storage/src/state/mod.rs#L449)):*
> ```XML
>         let file_offset_table = self.txn.open_table(&self.tables.file_offsets)?;
> 
>         update_marker(&self.txn, &markers_table, block_number)?;
> ```

Why did you delete this?



_Code quote:_
```XML
update_marker(&self.txn, &markers_table, block_number)?;
```
___
*[`crates/papyrus_storage/src/state/mod.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJWOyWCMbQGy1UoIXX:-NuJWOyWCMbQGy1UoIXY:b-urqeqn) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L529)):*
> ```XML
> 
>         // Advance class marker.
>         update_class_marker(&self.txn, &markers_table, &state_diffs_table, &self.file_handlers)?;
> ```

Please add a comment explaining this situation



_Code quote:_
```XML
        // Advance class marker.
        update_class_marker(&self.txn, &markers_table, &state_diffs_table, &self.file_handlers)?;
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, @ShahakShama, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJWTnk5Iu2oJQXTYUI:-NuJmBa_BkruNn6tqbko:bkcrsk6) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is the plan to separate the `append_state_diff` to `append_thin_state_diff` & `append_class`? I think it's a bad idea to keep both `append_state_diff` and `append_thin_state_diff`
</blockquote></details>

The plan is to keep them both. Use append_state_diff in central sync and append_thin_state_diff in p2p sync.
Though if you think it's not wise I can reconsider it

___
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJTfa2E1fow94RcxSv:-NuJmi5f977PznFgRYKH:bqt23dr) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/serialization/serializers.rs#L302)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is a breaking change, need to bump the major storage version or write a migration.
</blockquote></details>

I bumped it. See later in the PR
___
*[`crates/papyrus_storage/src/state/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJUlrB2iAd21ZE0_FR:-NuJnN9n3cDU2KKmcApC:b-zaz2fk) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L154)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IMO append_state_diff_with_classes, append_thin_state_diff
</blockquote></details>

I'll rename it
___
*[`crates/papyrus_storage/src/state/mod.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJVFFeCeN_qQYPo1e7:-NuJn4po6dLNibTJ8Gg9:bksh6o3) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L396)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IMO check the the class marker before returning None (keep the error)
</blockquote></details>

I'll do it
___
*[`crates/papyrus_storage/src/state/mod.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJX_pG87ai_Vr3O0kp:-NuJmvGk2_0KCmx5MOpt:b-6kcyrj) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f1e1132120907015fece45fb4f7108a2362e59/crates/papyrus_storage/src/state/mod.rs#L449)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why did you delete this?
</blockquote></details>

I moved it inside write_thin_state_diff
___
*[`crates/papyrus_storage/src/state/mod.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJWOyWCMbQGy1UoIXX:-NuJnIDB99qbSkqlg1f3:b-g5c4he) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L529)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add a comment explaining this situation
</blockquote></details>

I'll rename the function instead

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJUlrB2iAd21ZE0_FR:-NuJnXhr1nZ3vrjOr5yx:b-56pu7b) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L154)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll rename it
</blockquote></details>

I'll rename it unless we agree to remove append_state_diff
___
*[`crates/papyrus_storage/src/state/mod.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJVFFeCeN_qQYPo1e7:-NuJobMJ3EPAKaJz0Vl8:b6le0wm) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L396)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll do it
</blockquote></details>

This requires adding the markers table as a member of StateReader. Is it important enough to check this and I should add it? Are there any implications to adding it?
___
*[`crates/papyrus_storage/src/state/mod.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJWOyWCMbQGy1UoIXX:-NuJoMUF4Wy9Io9ouzFq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L529)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll rename the function instead
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJVFFeCeN_qQYPo1e7:-NuJr41i8LcN7fYBSVhK:b3ork1z) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L396)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This requires adding the markers table as a member of StateReader. Is it important enough to check this and I should add it? Are there any implications to adding it?
</blockquote></details>

I'll add it
___
*[`crates/papyrus_storage/src/state/mod.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJX_pG87ai_Vr3O0kp:-NuJrtFc4_0vrXiTpbPl:b80b63o) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f1e1132120907015fece45fb4f7108a2362e59/crates/papyrus_storage/src/state/mod.rs#L449)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I moved it inside write_thin_state_diff
</blockquote></details>

I'll remove the inner function to advance the class marker

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJVFFeCeN_qQYPo1e7:-NuNfKV8Cap8pI-p3jrV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b8893092a29208ccf8297558a0d79e819c8072b/crates/papyrus_storage/src/state/mod.rs#L396)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll add it
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuJX_pG87ai_Vr3O0kp:-NuMfi2X4OgfL93yQo2P:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/15f1e1132120907015fece45fb4f7108a2362e59/crates/papyrus_storage/src/state/mod.rs#L449)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'll remove the inner function to advance the class marker
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuNqw1yBQlpSiIbGNLc:-NuNqw1yBQlpSiIbGNLd:b38lleu) ([raw file](https://github.com/starkware-libs/papyrus/blob/898990bbf6b9fba4d248c18e41c97a23d8b8c3a9/crates/papyrus_storage/src/state/mod.rs#L193)):*
> ```XML
>         let markers_table = self.open_table(&self.tables.markers)?;
>         Ok(markers_table.get(&self.txn, &MarkerKind::Class)?.unwrap_or_default())
>     }
> ```

Currently we have an assumption that the classes are synced to the last state diff.
I think we should return both markers (perhaps also the compiled class marker) in a single function so users will have to pay attention to the change.
WDYT?



_Code quote:_
```XML
    fn get_class_marker(&self) -> StorageResult<BlockNumber> {
        let markers_table = self.open_table(&self.tables.markers)?;
        Ok(markers_table.get(&self.txn, &MarkerKind::Class)?.unwrap_or_default())
    }
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-NuNqw1yBQlpSiIbGNLc:-NuO7rni4l7ipqUXA_tj:br5ediz) ([raw file](https://github.com/starkware-libs/papyrus/blob/898990bbf6b9fba4d248c18e41c97a23d8b8c3a9/crates/papyrus_storage/src/state/mod.rs#L193)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Currently we have an assumption that the classes are synced to the last state diff.
I think we should return both markers (perhaps also the compiled class marker) in a single function so users will have to pay attention to the change.
WDYT?
</blockquote></details>

We will just remove that assumption

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1846#-:-NuOXfqEE6WH9WecoSSA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @nagmo-starkware)

**Pull request merged**
