### PR TITLE
perf(storage)!: improve serialization of location in file

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1974)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1974)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1974)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSfmoy5JerSOd59p7G:-NxSfmoy5JerSOd59p7H:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L279)):*
> ```XML
> #[test]
> fn storage_serde_test_location_in_file() {
>     // Checks serialization and serialization of the max value of LocationInFile.
> ```





_Suggestion:_
```XML
    // Checks serialization and deserialization of the max value of LocationInFile.
```
___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSg2a1EVLS-V5Aj-ch:-NxSg2a1EVLS-V5Aj-ci:bmztpdh) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L291)):*
> ```XML
>     let res = LocationInFile::deserialize_from(&mut buf.as_slice()).unwrap();
>     assert_eq!(res, item);
> }
> ```

This looks like a separate test, why not make 2 tests?



_Code quote:_
```XML
    let item = LocationInFile::get_test_instance(&mut get_rng());
    let mut buf = Vec::new();
    item.serialize_into(&mut buf).unwrap();
    let res = LocationInFile::deserialize_from(&mut buf.as_slice()).unwrap();
    assert_eq!(res, item);
}
```
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSc3Iw0tKyaY8UZGo0:-NxSc3Iw0tKyaY8UZGo1:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mod.rs#L290)):*
> ```XML
> // This serialization write the offset as 6 bytes and the length as 4 bytes.
> // This means the size of the file is limit to  256TB (1<<48 bytes) and the length 4GB (1<<32
> // bytes).
> ```





_Suggestion:_
```XML
// This serialization writes the offset as 6 bytes and the length as 4 bytes.
// This means the size of the file is limited to  256TB (1<<48 bits) and the length of the data
// is limited to 4GB (1<<32 bits).
```
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxScs-08SBYRLyIRtI7:-NxScs-1D5iv3nWRmTaG:b9waj77) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mod.rs#L294)):*
> ```XML
>     fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>         let bytes = &self.len.to_be_bytes();
>         res.write_all(&bytes[4..])?;
> ```

I don't know if this actually aligns with the comment above. You're definition here is to take all but the upper 4 bytes of len. If we have type `u64`, then indeed all but the upper 4 bytes equals the lower 4 bytes.

In the definition for `LocationInFile` I see that len and offset are of type `usize`. This means that they could potentially be of type `u32`, in which case we are entirely skipping len.

Below I have a suggestion which support 32b architecture, but another option is to put a static assertion that we are on a 64b architecture only.



_Suggestion:_
```XML
        let bytes = &self.len.to_be_bytes();
        let n_bytes = bytes.len();
        res.write_all(&bytes[(n_bytes - 4)..])?;
        (and then with -6 below)
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1974)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSfmoy5JerSOd59p7G:-NxSib5g2xx-OgufgEMY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L279)):*
> ```XML
> #[test]
> fn storage_serde_test_location_in_file() {
>     // Checks serialization and serialization of the max value of LocationInFile.
> ```

Done.
___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSg2a1EVLS-V5Aj-ch:-NxSib_k4sBfsATioyXP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L291)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This looks like a separate test, why not make 2 tests?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxSc3Iw0tKyaY8UZGo0:-NxSic866THyMHlyiLxo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mod.rs#L290)):*
> ```XML
> // This serialization write the offset as 6 bytes and the length as 4 bytes.
> // This means the size of the file is limit to  256TB (1<<48 bytes) and the length 4GB (1<<32
> // bytes).
> ```

Done.
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1974#-NxScs-08SBYRLyIRtI7:-NxSigEI5Q_MT6S5Qray:bsetbod) ([raw file](https://github.com/starkware-libs/papyrus/blob/60d053b7c44822d6a560fd236096369ce1dbd19a/crates/papyrus_storage/src/mmap_file/mod.rs#L294)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't know if this actually aligns with the comment above. You're definition here is to take all but the upper 4 bytes of len. If we have type `u64`, then indeed all but the upper 4 bytes equals the lower 4 bytes.

In the definition for `LocationInFile` I see that len and offset are of type `usize`. This means that they could potentially be of type `u32`, in which case we are entirely skipping len.

Below I have a suggestion which support 32b architecture, but another option is to put a static assertion that we are on a 64b architecture only.
</blockquote></details>

Not done. We not support 32 bit architecture

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1974)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
