### PR TITLE
feat(network): implement inbound session in handler

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(network): protocols return the IO (#1157)
- feat(network): extract get_connected_stream_futures to test utils (#1167)
- test(network): add create_swarm function (#1176)
- feat(network): add handler with unimplemented
- test(network): change get_connected_streams to return Stream
- test(network): move code
- test(network): fixes
- feat(network): add InboundSession struct
- test(network): extract hardcoded_responses to test_utils and rename to hardcoded_data
- feat(network): implement inbound session in handler

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1189)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1189)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/streamed_data_protocol/handler.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1189#-Nemep5-3w0jU5TsSuXR:-NemqgRyEDH6KPYrCcri:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c61f62f787a86c701d8de6c63682dc6d88994b6a/crates/papyrus_network/src/streamed_data_protocol/handler.rs#L79)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

reanme to something that implies waiting to finish sending then delete
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1189)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_data_protocol/handler.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1189#-Nemh3fe7ELdUMrF3obb:-Nemr6G18DQgGuNBCHmp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c61f62f787a86c701d8de6c63682dc6d88994b6a/crates/papyrus_network/src/streamed_data_protocol/handler.rs#L195)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

add a todo to cosider this flow in the future and change to debug
</blockquote></details>

Done.

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1189#-:-Neq_l6D7X-y3T6raEsn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
