### PR TITLE
Test storage readers functions after reverts (additional checks)

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe): Tests

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/457)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/body/events_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtPgpM4M18qkZI2rV2:-NLtPgpM4M18qkZI2rV3:b-xx1c6u) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/body/events_test.rs#L119)):*
> ```XML
>     let event_index = EventIndex(
>         TransactionIndex(block_number, TransactionOffsetInBlock(0)),
>         EventIndexInTransactionOutput(2),
> ```

Why 2?



_Code quote:_
```XML
        EventIndexInTransactionOutput(2),
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/state/state_test.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtQfep2HIlyrTug6Uu:-NLtQfep2HIlyrTug6Uv:blbeqpl) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L311)):*
> ```XML
>     let new_data = StarkFelt::from(1);
>     let updated_storage = IndexMap::from([(updated_storage_key, new_data)]);
>     let nonce1 = Nonce(StarkFelt::from(0));
> ```

Consider from 1 to be consistent with elsewhere 



_Code quote:_
```XML
let nonce1 = Nonce(StarkFelt::from(0));
```

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/state/state_test.rs` line 323 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtQu2DAgd9JEcMHuLY:-NLtQu2DAgd9JEcMHuLZ:b-jk24of) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L323)):*
> ```XML
>         .begin_rw_txn()
>         .unwrap()
>         .append_state_diff(BlockNumber(0), state0.clone(), vec![])
> ```

Consider renaming `state_diff0` (and 1 similarly)



_Code quote:_
```XML
state0
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/457)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/state/state_test.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtSHcYDzaFtNdSSMsa:-NLtSHcYDzaFtNdSSMsb:b-1esa0k) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L349)):*
> ```XML
>     txn.commit().unwrap();
> 
>     assert_matches!(deleted_data, Some((_thin_state_diff, _class_definitions)));
> ```

Shouldn't we check for the specific values here?



_Code quote:_
```XML
Some((_thin_state_diff, _class_definitions)))
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/457)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/457)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/body/events_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtPgpM4M18qkZI2rV2:-NLtU29Q6HmYOL2hBMGX:b-1vsjsv) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/body/events_test.rs#L119)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why 2?
</blockquote></details>

Can't remember... Fixed.
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtQfep2HIlyrTug6Uu:-NLtUZv15MSIdJ7hQZng:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L311)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider from 1 to be consistent with elsewhere 
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 323 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtQu2DAgd9JEcMHuLY:-NLtUxXq4teZysK-aCmn:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L323)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider renaming `state_diff0` (and 1 similarly)
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/457#-NLtSHcYDzaFtNdSSMsa:-NLtYMAX5JExdpOOw3kf:b-3q73ak) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e525ab5bf0d88950a84398f474d40fcbda4b5b3/crates/papyrus_storage/src/state/state_test.rs#L349)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Shouldn't we check for the specific values here?
</blockquote></details>

Done, not sure if this is the right test to check this

**Pull request merged**
