### PR TITLE
fix(execution): use StorageReader instead of a long transaction in St…

### PR DESCRIPTION
**Pull request by yair-starkware**
…ateReader

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1345)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/papyrus_execution/src/lib.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1345#-Ni3w_tv3M3fLZeLovfs:-Ni3w_tv3M3fLZeLovft:b-uy4xt7) ([raw file](https://github.com/starkware-libs/papyrus/blob/6a649521fe5926a15fb893114ef4c9ee7532667a/crates/papyrus_execution/src/lib.rs#L215)):*
> ```XML
>         &mut ExecutionResources::default(),
>         &mut context,
>     )?;
> ```

`txn` should be dropped before, right?



_Code quote:_
```XML
    let res = call_entry_point.execute(
        &mut cached_state,
        &mut ExecutionResources::default(),
        &mut context,
    )?;
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1345#-:-Ni43OXc2Ovqn19xs5O9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1345#-Ni42b-v5tvbBXuodUye:-Ni42b-v5tvbBXuodUyf:bqsp5tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/a5d43b239f3afc10a833031f68ccd06e814b6bde/crates/papyrus_execution/src/lib.rs#L175)):*
> ```XML
>     execution_config: &BlockExecutionConfig,
> ) -> ExecutionResult<CallExecution> {
>     // Pre-execution checks, drop the storage transaction before the execution to avoid long locks.
> ```

consider



_Suggestion:_
```XML
read transactions
```

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
*[`crates/papyrus_execution/src/lib.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1345#-Ni42b-v5tvbBXuodUye:-Ni43rYV7MErnNxxduwL:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a5d43b239f3afc10a833031f68ccd06e814b6bde/crates/papyrus_execution/src/lib.rs#L175)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

consider
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
