### PR TITLE
refactor(network): rename register_subscriber to register_sqmr_subscriber

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2030#-Nz31lxd75tqW8RPIE-s:-Nz31lxeDzO6IfzyaO1k:b-vipxra) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf83cabbaeb4127fa03a5fe1abc689f5c99c3c15/crates/papyrus_network/src/lib.rs#L149)):*
> ```XML
> /// This struct represents the receiver end of the response streams for a network subscriber.
> /// It is created by the network manager and passed to the subscriber when calling
> /// register_sqmr_subscriber.
> ```

Since this is public documentation, let's make this a link to the fn.



_Code quote:_
```XML
register_sqmr_subscriber.
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2030#-Nz31lxd75tqW8RPIE-s:-Nz3mLRsCguxJnnn5msH:b-dq16cv) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf83cabbaeb4127fa03a5fe1abc689f5c99c3c15/crates/papyrus_network/src/lib.rs#L149)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Since this is public documentation, let's make this a link to the fn.
</blockquote></details>

I gave you the wrong advice thinking they were in the same namespace. This works when I use cargo doc. I recommend you try it also and see.

/// This struct represents the receiver end of the response streams for a network subscriber.
/// It is created by the network manager and passed to the subscriber when calling
/// [`register_sqmr_subscriber`](`network_manager::GenericNetworkManager::register_sqmr_subscriber`).

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2030#-Nz31lxd75tqW8RPIE-s:-Nz7-ku78Tb3dD15Bb8C:b-pklgab) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf83cabbaeb4127fa03a5fe1abc689f5c99c3c15/crates/papyrus_network/src/lib.rs#L149)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I gave you the wrong advice thinking they were in the same namespace. This works when I use cargo doc. I recommend you try it also and see.

/// This struct represents the receiver end of the response streams for a network subscriber.
/// It is created by the network manager and passed to the subscriber when calling
/// [`register_sqmr_subscriber`](`network_manager::GenericNetworkManager::register_sqmr_subscriber`).
</blockquote></details>

```
/// This struct represents the receiver end of the response streams for a network subscriber.
/// It is created by the network manager and passed to the subscriber when calling
/// [`register_sqmr_subscriber`](`network_manager::GenericNetworkManager::register_sqmr_subscriber`).
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2030#-Nz31lxd75tqW8RPIE-s:-Nz73rhN0NhwqKvsXCgm:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf83cabbaeb4127fa03a5fe1abc689f5c99c3c15/crates/papyrus_network/src/lib.rs#L149)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

```
/// This struct represents the receiver end of the response streams for a network subscriber.
/// It is created by the network manager and passed to the subscriber when calling
/// [`register_sqmr_subscriber`](`network_manager::GenericNetworkManager::register_sqmr_subscriber`).
```
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2030)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
