### PR TITLE
docs(config): add examples for using pointer params

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCAi4eCpzIjTnOwln4:-NvCAi4eCpzIjTnOwln5:bjeee5l) (no related file):*
Please make these doc tests (see https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html)

___
___
*[`crates/papyrus_config/src/dumping.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvC9eaU72CsD56t8j7L:-NvC9eaU72CsD56t8j7M:bhbw92h) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa85e16a4912670670f543b1f80dd621df6cd9e0/crates/papyrus_config/src/dumping.rs#L74)):*
> ```XML
>     ///    "chain_id",
>     ///    &ChainId("SN_MAIN".to_string()),
>     ///    "The chain to follow."
> ```

Please use something more general than chain Id (the config crate is not specific to Starknet)



_Code quote:_
```XML
    ///    "chain_id",
    ///    &ChainId("SN_MAIN".to_string()),
    ///    "The chain to follow."
```
___
*[`crates/papyrus_config/src/dumping.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCAHrqEBzEmio-f-L7:-NvCAHrqEBzEmio-f-L8:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa85e16a4912670670f543b1f80dd621df6cd9e0/crates/papyrus_config/src/dumping.rs#L224)):*
> ```XML
> ///
> /// ```
> /// let pointer_target_param = ser_pointer_target_param(
> ```

Same

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCAi4eCpzIjTnOwln4:-NvCRdSB1PK7_2BkUSCs:b9yo9jd) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please make these doc tests (see https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html)
</blockquote></details>

passes compilation of doc tests

___
___
*[`crates/papyrus_config/src/dumping.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvC9eaU72CsD56t8j7L:-NvCRhyR8ZfB2EpmDnkZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa85e16a4912670670f543b1f80dd621df6cd9e0/crates/papyrus_config/src/dumping.rs#L74)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use something more general than chain Id (the config crate is not specific to Starknet)
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCAHrqEBzEmio-f-L7:-NvCRhiRDG9s9BJsDkEb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa85e16a4912670670f543b1f80dd621df6cd9e0/crates/papyrus_config/src/dumping.rs#L224)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCRspb3n2xNgB1_RKX:-NvCRspb3n2xNgB1_RKY:bbnu1sr) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L76)):*
> ```XML
>     /// use papyrus_config::{ParamPath, ParamPrivacyInput, SerializedParam};
>     /// use serde::{Deserialize, Serialize};
>     /// use tempfile::TempDir;
> ```

Use `#` to hide lines 



_Code quote:_
```XML
    /// use std::collections::BTreeMap;
    ///
    /// use papyrus_config::dumping::{ser_param, SerializeConfig};
    /// use papyrus_config::{ParamPath, ParamPrivacyInput, SerializedParam};
    /// use serde::{Deserialize, Serialize};
    /// use tempfile::TempDir;
```
___
*[`crates/papyrus_config/src/dumping.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCSMqbAYQq36yj4K4q:-NvCSMqbAYQq36yj4K4r:bqfppxf) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L245)):*
> ```XML
> ///
> /// let pointer_target_param = ser_pointer_target_param(
> ///     "string_param",
> ```

rename - shared_param



_Code quote:_
```XML
string_param
```
___
*[`crates/papyrus_config/src/dumping.rs` line 250 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCSSNf6syIdHakaugD:-NvCSSNf6syIdHakaugE:b-7lbm7w) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L250)):*
> ```XML
> /// );
> /// let pointer_param_paths =
> ///     vec!["conf1.conf2.string_param".to_owned(), "conf3.string_param".to_owned()];
> ```

rename - same_param



_Code quote:_
```XML
string_param
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCRspb3n2xNgB1_RKX:-NvR148u8BxVT0O1ILml:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L76)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use `#` to hide lines
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCSMqbAYQq36yj4K4q:-NvR13bp5-CSUL7RTgfW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L245)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

rename - shared_param
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 250 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-NvCSSNf6syIdHakaugD:-NvR13Lk3Nqmy4r1YlE-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7b73af19b424f4f8ac29cd5854c34815e742ec2/crates/papyrus_config/src/dumping.rs#L250)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

rename - same_param
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1893#-:-NvR1QCN0S2mGyXI49mb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
