### PR TITLE
fix(execution): get timestamp, gas price, sequencer from pending block if present

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1430)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-:-Njgyf-e6vYzdIrVpNYU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-NjgvrAnCvRHrYcXEsXr:-NjgvrAnCvRHrYcXEsXs:bto8qpx) ([raw file](https://github.com/starkware-libs/papyrus/blob/a707eac3cf80f70b6fcf004c786991696b6a3879/crates/papyrus_execution/src/lib.rs#L226)):*
> ```XML
>             (header.block_number, header.timestamp, header.gas_price, header.sequencer)
>         }
>     };
> ```

Consider moving this code into `create_block_context`



_Code quote:_
```XML
    let (block_number, timestamp, gas_price, sequencer) = match maybe_pending_data.as_ref() {
        Some(pending_data) => (
            block_context_number.next(),
            pending_data.timestamp,
            pending_data.gas_price,
            pending_data.sequencer,
        ),
        None => {
            let header = storage_reader
                .begin_ro_txn()?
                .get_block_header(block_context_number)?
                .expect("Should have block header.");
            (header.block_number, header.timestamp, header.gas_price, header.sequencer)
        }
    };
```
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 823 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-NjgyR0N5KBRyZu3fZRG:-NjgxnnV5On7IKk4ZCZo:b-14i5vg) ([raw file](https://github.com/starkware-libs/papyrus/blob/a707eac3cf80f70b6fcf004c786991696b6a3879/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L823)):*
> ```XML
>             Some(client_pending_data) => Some(client_pending_data_to_execution_pending_data(
>                 client_pending_data,
>                 self.pending_classes.read().await.clone(),
> ```

In a separate PR put the classes inside Arc to avoid a costly clone



_Code quote:_
```XML
.clone(),
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-NjgvrAnCvRHrYcXEsXr:-NjkWG9I97jv8XnDQK4g:bkxx2vf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a707eac3cf80f70b6fcf004c786991696b6a3879/crates/papyrus_execution/src/lib.rs#L226)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider moving this code into `create_block_context`
</blockquote></details>

In a later PR

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1430)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-NjgvrAnCvRHrYcXEsXr:-NjkZZQ7EVPwb_q796mm:buoy4hy) ([raw file](https://github.com/starkware-libs/papyrus/blob/a707eac3cf80f70b6fcf004c786991696b6a3879/crates/papyrus_execution/src/lib.rs#L226)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In a later PR
</blockquote></details>

I had a merge conflict so I fixed it in this PR since you need to re-review anyway

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1430#-:-NjktXj0EBHVULE6jm5W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
