### PR TITLE
feat(consensus): single height consensus returns Decision with Precommits

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2206)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2206** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2206?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2206)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2206#-O1J4SHA5lEmFFry2y4d:-O1J4SHB2-QjNtyiwKQK:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d8351c4e86a8ff1329cc0b9be6b47b76c04078b/crates/sequencing/papyrus_consensus/src/lib.rs#L116)):*
> ```XML
>     let mut future_messages = Vec::new();
>     loop {
>         let block = run_height(
> ```





_Suggestion:_
```XML
decision
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2206#-O1J5IouDGvjeb9MFWRM:-O1J5IouDGvjeb9MFWRN:bby8a2m) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d8351c4e86a8ff1329cc0b9be6b47b76c04078b/crates/sequencing/papyrus_consensus/src/types.rs#L152)):*
> ```XML
> pub struct Decision<BlockT>
> where
>     BlockT: ConsensusBlock,
> ```

Why not declaring the trait bounds inline for consistency?



_Code quote:_
```XML
where
    BlockT: ConsensusBlock,
```

**Review by asmaastarkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2206#-:-O1LJ7838Jdi3PSlruBT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
