### PR TITLE
feat(network): connect db executor to storage for read

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1633?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1628** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1628?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1630** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1630?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1633** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1633?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1633?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NolG4YuD-LoisdZ1nNJ:-NolG4YuD-LoisdZ1nNK:b-qox05t) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
> ```XML
>     BlockNumberOutOfRange { query: BlockQuery, counter: u64 },
>     #[error("Block not found. Block number: {0}")]
>     BlockNotFound(u64),
> ```

This should map into Fin(unknown). Right now you can put a TODO
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquTHz9TIhTMat-uMP:-NoquTHz9TIhTMat-uMQ:b-9o6nwp) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
> ```XML
>     }
> 
>     fn calc_block_number(
> ```

Why do you calc each block number separately instead of just taking the last block number and adding `step` to it
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquePw5SWZttovatEJ:-NoquePw5SWZttovatEK:b-dim16d) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L107)):*
> ```XML
>         };
>         let blocks_delta: i128 = direction_factor * (query.step * read_blocks_counter) as i128;
>         let block_number: i128 = query.start_block.0 as i128 + blocks_delta;
> ```

Add TODO to handle hash as start_block
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoqxQfC2QS0fwev54b9:-NoqxQfC2QS0fwev54bA:b-8a779a) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L139)):*
> ```XML
>         read_blocks_counter: u64,
>     ) -> Result<Data, DBExecutorError> {
>         let txn = self.storage_reader.begin_ro_txn()?;
> ```

Are we ok with opening a txn for every header?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NolG4YuD-LoisdZ1nNJ:-Noup5a40h3FoBSvKXS4:b-7v8eo) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should map into Fin(unknown). Right now you can put a TODO
</blockquote></details>

found here: https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/block_headers/mod.rs#L24
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquTHz9TIhTMat-uMP:-NounHTtE5bRIHjjBNgX:bazmwav) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you calc each block number separately instead of just taking the last block number and adding `step` to it
</blockquote></details>

then I'll have to keep track of one additional item.. the actual block number
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquePw5SWZttovatEJ:-NouoUg-CyfbNexfoux7:b-7v8by) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L107)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to handle hash as start_block
</blockquote></details>

found here: https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/block_headers/mod.rs#L59
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoqxQfC2QS0fwev54b9:-NounUXr0JUKR6KxgBHt:bx8h83y) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L139)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Are we ok with opening a txn for every header?
</blockquote></details>

I think for now yes.. optimization is for later

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NolG4YuD-LoisdZ1nNJ:-Nov4DAL7L7GK3caEYrA:b4y2quo) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

found here: https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/block_headers/mod.rs#L24
</blockquote></details>

You meant this TODO :sweat_smile: 
  // TODO: decide what is the right way to handle db errors.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquTHz9TIhTMat-uMP:-Nov4QAR6FsMsn-5Z_y-:b62c0z7) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

then I'll have to keep track of one additional item.. the actual block number
</blockquote></details>

Yes, but it will make the code much more readable IMO

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-3Fxd4acYb84EH_uA:-Np-3Fxd4acYb84EH_uB:b-8ohwn2) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/block_headers/behaviour.rs#L80)):*
> ```XML
>         let header_messages = match data {
>             Data::BlockHeaderAndSignature { header, signature } => {
>                 let mut res = vecprotobuf::block_headers_response_part::HeaderMessage::Header(
> ```

Consider reverting this
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 35 at r1 ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L35)):*
> ```XML
> pub trait DBExecutor: Stream<Item = (QueryId, Data)> + Unpin {
>     // TODO: add writer functionality
>     fn register_query(&mut self, query: BlockQuery) -> QueryId;
> ```

All three of this methods should be renamed to reflect the fact they're working on headers. I'm ok with just a TODO for now or keeping it as it is
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-4WcZ63KjQBz6EKUb:-Np-4WcZ63KjQBz6EKUc:bgqas9w) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
> ```XML
>     }
> 
>     fn calc_block_number(
> ```

Consider calculate instead of calc

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-3Fxd4acYb84EH_uA:-NpPp8SnEixJAOtKSJIZ:bz7626d) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/block_headers/behaviour.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider reverting this
</blockquote></details>

this is needed in case the signature is None. following todays conversation we might need to adjust this case (always send sigs) but it'll be a separate PR
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NolG4YuD-LoisdZ1nNJ:-NovA9vLByoESqqfxPSE:b-de15pl) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You meant this TODO :sweat_smile: 
  // TODO: decide what is the right way to handle db errors.
</blockquote></details>

both I guess :) 
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-3ml2DInsAQmkJCPA:-NpPoeVW0Bg1DjCu2XPU:b9ecx99) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

All three of this methods should be renamed to reflect the fact they're working on headers. I'm ok with just a TODO for now or keeping it as it is
</blockquote></details>

removed other than register_query which I think is not headers specific
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-NoquTHz9TIhTMat-uMP:-NpPom882JHott0sfXix:b1i7xu0) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, but it will make the code much more readable IMO
</blockquote></details>

removed from here and also discussed f2f
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-4WcZ63KjQBz6EKUb:-NpPorYZB_a0ipc7RlpD:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider calculate instead of calc
</blockquote></details>

removed

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-4WcZ63KjQBz6EKUb:-NpPpnchEUgCbhf2ufT6:b-5u1796) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

removed
</blockquote></details>

It's not removed. It's moved :)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-Np-4WcZ63KjQBz6EKUb:-NpPqUM6DqFq76bNhc8Y:b-sh6rma) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6146b20b3228939c3a1d0661c5a2af3d094a425/crates/papyrus_network/src/db_executor/mod.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's not removed. It's moved :)
</blockquote></details>

sure.. fixed

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-:-NpPrUhX0_4FYD6x_b8g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1633#-:-NpPsG17BRo0XD26WD1-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
