### PR TITLE
fix(JSON-RPC): fail rpc requests to read block content in StateOnly mode

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
Need to copy the this error to other transactions that are not supported in state only mode

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-:-Njl47NqA1-fBcF4MQ1W:b6g7ikb)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-Njq3rhJ9B1MHmi04aRb:-Njq3rhJ9B1MHmi04aRc:b-4hwxzo) ([raw file](https://github.com/starkware-libs/papyrus/blob/21eeb75c0dbd1fd4451358d2632846bed255db85/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L386)):*
> ```XML
>         else {
>             return Err(internal_server_error_with_msg(StorageError::StateOnlyInvalidRequest));
>         };
> ```

Can't we pass the config param to the RPC and check it instead of reading from the storage?



_Code quote:_
```XML
        let Some(StorageVersion::FullArchive(_)) =
            get_storage_version(&self.storage_reader).map_err(internal_server_error)?
        else {
            return Err(internal_server_error_with_msg(StorageError::StateOnlyInvalidRequest));
        };
```
___
*[`crates/papyrus_storage/src/lib.rs` line 499 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-Njq4Ce28HxKTQvz4LUj:-Njq4Ce28HxKTQvz4LUk:b9ys6ps) ([raw file](https://github.com/starkware-libs/papyrus/blob/21eeb75c0dbd1fd4451358d2632846bed255db85/crates/papyrus_storage/src/lib.rs#L499)):*
> ```XML
>     ScopeError { table_name: String, storage_scope: StorageScope },
>     #[error("The request is not valid under the state-only scope.")]
>     StateOnlyInvalidRequest,
> ```

I think this should be an RPC error, not storage error



_Code quote:_
```XML
    #[error("The request is not valid under the state-only scope.")]
    StateOnlyInvalidRequest,
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-Njq3rhJ9B1MHmi04aRb:-NjrJeEY9ZqMKSPoW90D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/21eeb75c0dbd1fd4451358d2632846bed255db85/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L386)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can't we pass the config param to the RPC and check it instead of reading from the storage?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 499 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-Njq4Ce28HxKTQvz4LUj:-NjrJdQ3CeiHO01BnD03:brrfgs8) ([raw file](https://github.com/starkware-libs/papyrus/blob/21eeb75c0dbd1fd4451358d2632846bed255db85/crates/papyrus_storage/src/lib.rs#L499)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this should be an RPC error, not storage error
</blockquote></details>

 just added a custom string since an RpcError should be defined in the spec.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-:-NjrPROE9HPb41k_grfc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-NjrP-Me5jHnqFSxmUJ0:-NjrP-Mf2wfok1VCdTQA:bjpzou9) ([raw file](https://github.com/starkware-libs/papyrus/blob/4015672fb70db90c85029dc4513fede659a2514f/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L384)):*
> ```XML
>         if self.storage_reader.get_scope() == StorageScope::StateOnly {
>             return Err(internal_server_error_with_msg(
>                 "The request is not valid under the state-only scope.",
> ```

IMO, this message is not clear to users.
Perhaps "Unsupported method in state-only mode."



_Code quote:_
```XML
"The request is not valid under the state-only scope."
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-Njvde-18Agw_3TZbxBh:-Njvde-18Agw_3TZbxBi:bfk7nq4) (no related file):*
Please add this function:
```
fn verify_storage_scope() ->RpcResult<()> {
        match self.storage_reader.get_scope() {
            StorageScope::StateOnly => Err(internal_server_error_with_msg("Unsupported method in state-only scope.")),
            StorageScope::FullArchive => Ok(()),
        }
}
```

and call `verify_storage_scope()?;` instead of all the if statements

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-:-NjvqUjt711u2wLieDub:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1440#-:-Njw-A9D728_h_s9BEcB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
