### PR TITLE
fix: read_pending_data() for get_storage_at

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1292 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NiE1DkT2T2lWK7zN17x:-NiE1DkT2T2lWK7zN17y:b3g5voh) ([raw file](https://github.com/starkware-libs/papyrus/blob/43c5d62dd44f480f3ee4daa06c1126613e7630ff/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1292)):*
> ```XML
>         .await
>         .unwrap();
>     assert_eq!(res, StarkFelt::default());
> ```

Add another test where the contract is deployed in the pending block, and the pending block is not updated (The output should be an error of CONTRACT_NOT_FOUND)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1292 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NicEvIN7dsDMgzZ0bUL:-NicEvIN7dsDMgzZ0bUM:b6iekjv) ([raw file](https://github.com/starkware-libs/papyrus/blob/43c5d62dd44f480f3ee4daa06c1126613e7630ff/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1292)):*
> ```XML
>         .await
>         .unwrap();
>     assert_eq!(res, StarkFelt::default());
> ```

Also, add a test where the same storage is updated both in the pending block and the storage block with different values. and check it twice: once when the pending is up to date and once when it isn't

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1292 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NiE1DkT2T2lWK7zN17x:-NicmVzf2mlIXMoJno9M:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/43c5d62dd44f480f3ee4daa06c1126613e7630ff/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1292)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add another test where the contract is deployed in the pending block, and the pending block is not updated (The output should be an error of CONTRACT_NOT_FOUND)
</blockquote></details>

Done.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1292 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NicEvIN7dsDMgzZ0bUL:-Nid6T5g4cMjwHEljeLk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/43c5d62dd44f480f3ee4daa06c1126613e7630ff/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1292)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Also, add a test where the same storage is updated both in the pending block and the storage block with different values. and check it twice: once when the pending is up to date and once when it isn't
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: all files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1285 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidD5Xp1YFeOBxq2lcF:-NidD5Xp1YFeOBxq2lcG:b-2cq3l3) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1285)):*
> ```XML
>     assert_eq!(res, other_value);
> 
>     // Set 'key' to have a different value in the pending block and the non-pending block, and test
> ```

Each sentence should describe only one case. And the sentence should describe the situation, not the actions we do. Here write
// Ask for storage that was changed both in the pending block and the non-pending block
The other tests I'll comment about in their places
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1300 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidDiiD-1VqVwcu2Zbs:-NidDiiD-1VqVwcu2Zbt:bylwqqa) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1300)):*
> ```XML
>     assert_eq!(res, other_value);
> 
>     // Ask for storage in pending block when it's not updated.
> ```

updated -> up to date
it's -> the pending block is
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1308 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidENkd6OyV8cozkb3s:-NidENkd6OyV8cozkb3t:b36relr) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1308)):*
> ```XML
>     assert_eq!(res, StarkFelt::default());
> 
>     let res = module
> ```

This is a separate case, add a comment before it
```
// Ask for storage updated both in pending block and non-pending block when the pending block is not up to date.
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: all files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidESlY6MjRxD64IS5g:-NidESlY6MjRxD64IS5h:bu8fcmm) (no related file):*
blocking because reviewable is dumb

___

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidESlY6MjRxD64IS5g:-NidQcvj4xqtJR3wR55N:b-896fix) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

blocking because reviewable is dumb
</blockquote></details>

Done.

___
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1285 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidD5Xp1YFeOBxq2lcF:-NidQ1CQ5szuqisxhbqA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1285)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Each sentence should describe only one case. And the sentence should describe the situation, not the actions we do. Here write
// Ask for storage that was changed both in the pending block and the non-pending block
The other tests I'll comment about in their places
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1300 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidDiiD-1VqVwcu2Zbs:-NidQang0It_SrlQGS21:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1300)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

updated -> up to date
it's -> the pending block is
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1308 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-NidENkd6OyV8cozkb3s:-NidQ_u36D6dpdG8mcDX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b5304de98ae8348d745f26de8a6c66904c8a0c8/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1308)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is a separate case, add a comment before it
```
// Ask for storage updated both in pending block and non-pending block when the pending block is not up to date.
```
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1351#-:-NidY2Ln7dfhLxf_USKn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
