### PR TITLE
chore(network): move functionality into behaviour trait for testing

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn4fbjL8bLhO-lYY3kQ:b-71li2j) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
> ```XML
> }
> 
> pub trait BehaviourTrait<DBExecutor>
> ```

Change this to pub(crate), and rename to something that I understand it's for testing only
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4g3sj3RmTwrb56FG_:-Nn4g3sj3RmTwrb56FGa:bb9qfte) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour_test.rs#L41)):*
> ```XML
> }
> 
> struct TestBehaviour {}
> ```

I'm missing the future motivation. What do you gain from implementing the trait in the test file?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8Lzpo6CKQhit6eaDs:b6n47wi) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to pub(crate), and rename to something that I understand it's for testing only
</blockquote></details>

IDK how to name it differently in a way that sounds good to me (open for suggestions..)
I added a comment to make it clearer
___
*[`crates/papyrus_network/src/block_headers/behaviour_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4g3sj3RmTwrb56FG_:-Nn8MjZI3bH-xZxYW5af:b-44bwos) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour_test.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm missing the future motivation. What do you gain from implementing the trait in the test file?
</blockquote></details>

some of the functions can't be defined in the trait since they operate on self. so in the test file I have to provide some default functionality.
later I can test the implemented functionality of `map_streamed_data_behaviour_event_to_own_event` for example by mocking the functionality of the underlying functions that interact with self.
makes sense? if not I suggest you just look at the next PR

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-:-Nn8P-Mc0zbrsT3j3bi8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8NlQT4pgfV4nbbRgB:b-2hgsbq) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

IDK how to name it differently in a way that sounds good to me (open for suggestions..)
I added a comment to make it clearer
</blockquote></details>

The comment makes it better, but maybe we can improve it by changing pub(crate) to pub(self::behaviour_test). Now that I think of it, the test module is a submodule of this module so it should work even if this trait is private (DYT private is better than pub(self::behaviour_test)?)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8STdO7gZ9gyUWqxka:b6ajzj) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The comment makes it better, but maybe we can improve it by changing pub(crate) to pub(self::behaviour_test). Now that I think of it, the test module is a submodule of this module so it should work even if this trait is private (DYT private is better than pub(self::behaviour_test)?)
</blockquote></details>

I think private is better. but it doesn't work when I make it private

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8Tlfx01YkAp1-D-4C:b-ul1s8c) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think private is better. but it doesn't work when I make it private
</blockquote></details>

So why not pub(self::behaviour_test) or pub(crate::block_headers::behaviour::behaviour_test)?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8UCmB-u2vE0T2UyaO:by6frrz) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

So why not pub(self::behaviour_test) or pub(crate::block_headers::behaviour::behaviour_test)?
</blockquote></details>

it's pretty ugly.. maybe simply pub(super)?

**Comment by ShahakShama** [comment]
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8V5fA6RGtLd0vBXm3:b-dtszde) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's pretty ugly.. maybe simply pub(super)?
</blockquote></details>

why super? why not pub(self)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1580)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1580#-Nn4fbjL8bLhO-lYY3kP:-Nn8XEnN73BI0kM3_H6N:b-h9sdgl) ([raw file](https://github.com/starkware-libs/papyrus/blob/5a68f3868a34c6629fb47cc3f83c2bb633a5240b/crates/papyrus_network/src/block_headers/behaviour.rs#L150)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

why super? why not pub(self)
</blockquote></details>

again.. doesn't work :)

**Pull request merged**
