### PR TITLE
Separate block headers and body sync

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)

### CODE REVIEW

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 491 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYNQJi23wdR9K4-abs1:-NYNQJi23wdR9K4-abs2:b-l7tucn) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L491)):*
> ```XML
>             let body_marker = txn.get_body_marker()?;
>             let last_block_number = txn.get_header_marker()?;
>             drop(txn);
> ```

Talk to Dan about what style they prefer.



_Suggestion:_
```XML
           let body_marker, last_block_number;
           {
               let txn = reader.begin_ro_txn()?;
               body_marker = txn.get_body_marker()?;
               last_block_number = txn.get_header_marker()?;
            }
```
___
*[`crates/papyrus_sync/src/sources/central.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYJ2i375O0At5GO_K-O:-NYNP4Bj-40rGBwRKwu8:b-b46gex) ([raw file](https://github.com/starkware-libs/papyrus/blob/851b5972a23da6a3eb4b3d93abc97cbdb53d8375/crates/papyrus_sync/src/sources/central.rs#L103)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

How do I make this function 'private'? I don't want it to be used externally. It should only be used by stream_new_block_headers() and stream_new_block_bodies() inside this trait.
</blockquote></details>

You don't. Trait's define an interface, not an implementation. A private function is necessarily an implementation detail. It should be left up to the implementer if they want to write this helper function or not.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 491 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYNQJi23wdR9K4-abs1:-NYNUTYjAS4COsRSufA8:bmhikf7) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L491)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Talk to Dan about what style they prefer.
</blockquote></details>

@dan-starkware - WDYT?

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @matan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO1a2R-xkH_Z_W9dyd:-NYO1a2R-xkH_Z_W9dye:bd39oa9) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L74)):*
> ```XML
>     BlockHeaderAvailable {
>         block_number: BlockNumber,
>         block: Block,
> ```

This should be header, right?



_Code quote:_
```XML
block: Block,
```
___
*[`crates/papyrus_sync/src/lib.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO2zHX1WYACBC1bAmj:-NYO2zHX1WYACBC1bAmk:bb6tcuf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L78)):*
> ```XML
>     BlockBodyAvailable {
>         block_number: BlockNumber,
>         block: Block,
> ```

Body



_Code quote:_
```XML
 block: Block,
```
___
*[`crates/papyrus_sync/src/lib.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO4L3e88PY1c-rycsT:-NYO4L3e88PY1c-rycsU:b-x3autm) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L247)):*
> ```XML
>         // Assuming the central source is trusted, detect reverts by comparing the incoming block's
>         // parent hash to the current hash.
>         self.verify_parent_block_hash(block_number, &block)?;
> ```

This logic is relevant only to headers (as they define the chain). Bodies should be validated against headers.



_Code quote:_
```XML
        // Assuming the central source is trusted, detect reverts by comparing the incoming block's
        // parent hash to the current hash.
        self.verify_parent_block_hash(block_number, &block)?;
```
___
*[`crates/papyrus_sync/src/lib.rs` line 491 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYNQJi23wdR9K4-abs1:-NYOBCd5B2nAiEtLhytt:b-d2bmvj) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L491)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

@dan-starkware - WDYT?
</blockquote></details>

We don't have specific conventions, I like @matan-starkware suggestion.
If you do so, please change in other places as well.
___
*[`crates/papyrus_sync/src/sources/central.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO3GBN1K8sg3B9xUao:-NYO3GBN1K8sg3B9xUap:b-s0yf3z) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/sources/central.rs#L117)):*
> ```XML
>         initial_block_number: BlockNumber,
>         up_to_block_number: BlockNumber,
>     ) -> BlocksStream<'_>;
> ```

The idea is that each stream returns the specific elements (headers in one and bodies in the other). The separation should be in the central, not in the sync. 



_Code quote:_
```XML
    fn stream_new_block_headers(
        &self,
        initial_block_number: BlockNumber,
        up_to_block_number: BlockNumber,
    ) -> BlocksStream<'_>;
    fn stream_new_block_bodies(
        &self,
        initial_block_number: BlockNumber,
        up_to_block_number: BlockNumber,
    ) -> BlocksStream<'_>;
```

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO1a2R-xkH_Z_W9dyd:-NYRqcQ-AQ5x2g56msd_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L74)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This should be header, right?
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/lib.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO4L3e88PY1c-rycsT:-NYSj0vq2EI-txZT3exq:b-wh7m7q) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L247)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This logic is relevant only to headers (as they define the chain). Bodies should be validated against headers.
</blockquote></details>

What do I need to validate exactly for block-body?
Just that the block-header exists? 
___
*[`crates/papyrus_sync/src/sources/central.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO3GBN1K8sg3B9xUao:-NYSir2LCdBYkRtN1akx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/sources/central.rs#L117)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

The idea is that each stream returns the specific elements (headers in one and bodies in the other). The separation should be in the central, not in the sync. 
</blockquote></details>

Done.

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_sync/src/lib.rs` line 510 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NZQLRG73iFj8XmIjKpr:-NZQLRG80rP-daxcOfTH:b-5i7io8) ([raw file](https://github.com/starkware-libs/papyrus/blob/845adc512c911cb569c0070f93d0b0926ed75e3a/crates/papyrus_sync/src/lib.rs#L510)):*
> ```XML
>             }
>             let up_to = min(last_block_number, BlockNumber(body_marker.0 + max_stream_size as u64));
>             debug!("Downloading blocks [{} - {}).", body_marker, up_to);
> ```

Consider: "Downloading blocks body."
the debug message here and in the header stream is the same. Maybe even adding an explicit "header" to the header stream.
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NZQNaXv46Sc-n0hl-CQ:-NZQNaXv46Sc-n0hl-CR:bxxt28d) ([raw file](https://github.com/starkware-libs/papyrus/blob/845adc512c911cb569c0070f93d0b0926ed75e3a/crates/papyrus_sync/src/sources/central_test.rs#L48)):*
> ```XML
> 
> #[tokio::test]
> async fn stream_block_headers() {
> ```

Consider adding tests for the bodies stream.
Because the logic and the code are the same in the header and the body stream, maybe only add a test that returns the same block numbers are returned given the same mocking.

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NZQNaXv46Sc-n0hl-CQ:-NZR49mw86VhEGfI-Diu:b-xw2inq) ([raw file](https://github.com/starkware-libs/papyrus/blob/845adc512c911cb569c0070f93d0b0926ed75e3a/crates/papyrus_sync/src/sources/central_test.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider adding tests for the bodies stream.
Because the logic and the code are the same in the header and the body stream, maybe only add a test that returns the same block numbers are returned given the same mocking. 
</blockquote></details>

OK. Done.
I hope I understood it correctly.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @OmriEshhar1)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NZRW-xN3nHg23WmvHHD:-NZRW-xN3nHg23WmvHHE:b-ukqk1) ([raw file](https://github.com/starkware-libs/papyrus/blob/7b582abd076e696aae138c681bd578bc55f46db4/crates/papyrus_node/src/bin/central_source_integration_test.rs#L33)):*
> ```XML
> 
>     let mut block_marker = initial_block_number;
>     let block_header_stream =
> ```

Consider adding a block stream test as well.
___
*[`crates/papyrus_sync/src/lib.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/761#-NYO4L3e88PY1c-rycsT:-NYWm2kj6Ue0aW-09RsK:b9xoaz1) ([raw file](https://github.com/starkware-libs/papyrus/blob/0af379c213f1bf8be6761d0f5f7bb51e8ffb7d5c/crates/papyrus_sync/src/lib.rs#L247)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

What do I need to validate exactly for block-body?
Just that the block-header exists? 
</blockquote></details>

Yes, one of the next tasks is validations.

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
