### PR TITLE
add DeployAccountTransaction to SN writer client

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZPCeg2CALJXdH_LVzG:-NZPCeg2CALJXdH_LVzH:bsbjhw0) (no related file):*
rebased on #799 

___

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR0BXE3rak24DnR6Kl:-NZR0BXE3rak24DnR6Km:bt25u5a) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction.rs#L1)):*
> ```XML
> use serde::{Deserialize, Serialize};
> ```

Rename the file to broadcast_transaction?
___
*[`crates/starknet_writer_client/src/objects/transaction.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR0kx82CfMQhQKK0Wm:-NZR0kx82CfMQhQKK0Wn:bb7lrp0) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction.rs#L9)):*
> ```XML
> #[derive(Debug, Default, Deserialize, Serialize, Clone, Eq, PartialEq)]
> #[serde(deny_unknown_fields)]
> pub struct DeployAccountTransaction {
> ```

Broadcasted...Transaction?
___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR1-Xh-dNHK9crQIYN:-NZR1-Xh-dNHK9crQIYO:b-8xr066) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction_test.rs#L15)):*
> ```XML
>     let path = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
>         .join("resources")
>         .join(path_in_resource_dir);
> ```

use read_json_file from test_utils



_Code quote:_
```XML
    let path = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("resources")
        .join(path_in_resource_dir);
```
___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR1xaT6b9pT53Fs6U6:-NZR1xaT6b9pT53Fs6U7:bkwsuvi) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction_test.rs#L19)):*
> ```XML
> }
> 
> fn validate_load_and_dump<TransactionType: for<'a> Deserialize<'a> + Serialize>(
> ```

Rename the generic param - it is misleading because you have an enum with the same name.
Another option is to create an enum of BroadcastedTransaction where each variant is a different type and avoid using generic at all.



_Code quote:_
```XML
TransactionType
```
___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR2egt-SK2to0Mt00q:-NZR2egt-SK2to0Mt00r:bidfqvj) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction_test.rs#L33)):*
> ```XML
> #[test]
> fn load_and_dump_deploy_account_same_string() {
>     validate_load_and_dump::<DeployAccountTransaction>("deploy_account.json");
> ```

By introducing the enum, you can verify that all of the transaction types are being tested by using match

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR1-Xh-dNHK9crQIYN:-NZUIp2m818EaXMfusQM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction_test.rs#L15)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

use read_json_file from test_utils
</blockquote></details>

Done.
___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZR1xaT6b9pT53Fs6U6:-NZUIqEW4qk05R0m6f6E:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/50c6d490e2e1d41b01153685fe67575671303b4f/crates/starknet_writer_client/src/objects/transaction_test.rs#L19)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename the generic param - it is misleading because you have an enum with the same name.
Another option is to create an enum of BroadcastedTransaction where each variant is a different type and avoid using generic at all.
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZWEyQu44J3YZWIFmWi:-NZWEyQu44J3YZWIFmWj:b-ij9l5u) ([raw file](https://github.com/starkware-libs/papyrus/blob/32fd41ce0691e4475cc29c287945f53a43d60558/crates/starknet_writer_client/src/objects/transaction_test.rs#L5)):*
> ```XML
> use test_utils::read_json_file;
> 
> use super::transaction::Transaction;
> ```

crate::



_Code quote:_
```XML
super
```
___
*[`crates/starknet_writer_client/src/objects/transaction_test.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/798#-NZWHRmC5iXB0tMZYWk-:-NZWHRmC5iXB0tMZYWk0:b-upip9w) ([raw file](https://github.com/starkware-libs/papyrus/blob/32fd41ce0691e4475cc29c287945f53a43d60558/crates/starknet_writer_client/src/objects/transaction_test.rs#L14)):*
> ```XML
>     let load_result = serde_json::from_value::<Transaction>(json_value.clone());
>     assert_ok!(load_result);
>     validate_transaction_matches(load_result.as_ref().unwrap());
> ```

It seems like an over-design to me, but ok...

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/798#-:-NZ__XO10blqkirxL-c2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
