### PR TITLE
bugfix - Transactions deserialization

### PR DESCRIPTION
**Pull request by nagmo-starkware**
…g from reapearing

## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NUz2wbzCqD0YZg7wb0b:-NUz2wbzCqD0YZg7wb0c:b-85l179) (no related file):*
@dan-starkware do we even care about the deserialization of Gateway objects?
Maybe we should remove the derive

___

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NUzhmZA-XFkvQu79eqs:-NUzhmZA-XFkvQu79eqt:bd0ebll) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L192)):*
> ```XML
> 
> #[tokio::test]
> async fn verify_serialization_deserialization_of_block() {
> ```

Why do we need these tests in the gateway?

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@dan-starkware do we even care about the deserialization of Gateway objects?
Maybe we should remove the derive
</blockquote></details>

Don't we use them in tests?

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Don't we use them in tests? 
</blockquote></details>

We can compare jsons instead of deserializing

**Comment by dan-starkware** [comment]
*[`crates/papyrus_gateway/src/gateway_test.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NV9XGMb816Sc2ydIl3P:-NV9XGMc0Ng5epwYMQru:b-so4xws) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L208)):*
> ```XML
> 
> #[tokio::test]
> async fn get_block_w_full_transactions() {
> ```

@yair-starkware Here for example we compare objects, not jsons. 
module.call<type> does not involve deserialising?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NUzhmZA-XFkvQu79eqs:-NVYIUdq6pVw4KCcy4nT:b-243ybn) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L192)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need these tests in the gateway?
</blockquote></details>

my bad.. should be gateway block type not api block type
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NV9XGMb816Sc2ydIl3P:-NVYHPA9DpqeiRZ0ZEN_:b-64s78h) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L208)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

@yair-starkware Here for example we compare objects, not jsons. 
module.call<type> does not involve deserialising?
</blockquote></details>

yes it does. it uses `serde_json::from_str`

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/src/gateway_test.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NV9XGMb816Sc2ydIl3P:-NVYMtngBYyV8NaA--l5:b-tlbojs) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L208)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

yes it does. it uses `serde_json::from_str`
</blockquote></details>

Can't we change the generic parameter to Serde::Value and then it won't deserialize?

**Review by yair-starkware — DISMISSED** [review]
> Reviewed 1 of 8 files at r1, 4 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NUz2wbzCqD0YZg7wb0b:-NVYoEEj8bKvpVjOeLXU:b-79j354) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We can compare jsons instead of deserializing
</blockquote></details>

I removed the block, but I'm still not convinced we can't use JSON instead.

___

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NV9XGMb816Sc2ydIl3P:-NVZQ8EV54Ki8Dn3ewLf:b-tq9ybr) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L208)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can't we change the generic parameter to Serde::Value and then it won't deserialize?
</blockquote></details>

note for future reference - we think it's possible to remove deserialization from the gateway objects  because we don't actually need it. but for now we will just finish with this fix and consider it as an option if we get into it again

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/665#-NUzhmZA-XFkvQu79eqs:-NVZeGgjEyKjIvUnBRSH:b-hfpv0l) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d340b8b7549d3b8940100f63f93117f5433e9d8/crates/papyrus_gateway/src/gateway_test.rs#L192)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

verify_serialization_deserialization_of_body
</blockquote></details>

removed

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 4 of 7 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
