### PR TITLE
Dvir/compression to contracts

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/672#-NVUNX2nDHjTfwkhvi3O:-NVUNX2nDHjTfwkhvi3P:b-97p2tp) (no related file):*
We should talk about the numbers (time and space performance)

___

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/672#-NVUY-wN85DimB4hN1e2:-NVUY-wN85DimB4hN1e3:b4bgzz3) (no related file):*
Before merging this pull request, I want to sync a node to the end to ensure there are no bugs and test the overall memory consumption and request get_class response time. 

___

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/compression_utils.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/672#-NWbf1XB5VMBSAKFF4tw:-NWbf1XB5VMBSAKFF4tx:bpmv49a) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ef33a40b93bb54bd4eb4367ec50ad47bff65747/crates/papyrus_storage/src/compression_utils.rs#L49)):*
> ```XML
>     use crate::db::serialization::StorageSerde;
> 
>     #[test]
> ```

Please move the the test file
___
*[`crates/papyrus_storage/src/compression_utils.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/672#-NWbflUF3PmkFRp6g8GP:-NWbflUF3PmkFRp6g8GQ:b-npnqo0) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ef33a40b93bb54bd4eb4367ec50ad47bff65747/crates/papyrus_storage/src/compression_utils.rs#L51)):*
> ```XML
>     #[test]
>     fn bytes_compression() {
>         let length = rand::thread_rng().gen_range(0..10000);
> ```

Do we really need randomness here?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/compression_utils.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/672#-NWbf1XB5VMBSAKFF4tw:-NWgFgqlA-7SKqyql46J:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8ef33a40b93bb54bd4eb4367ec50ad47bff65747/crates/papyrus_storage/src/compression_utils.rs#L49)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move the the test file
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/672)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
