### PR TITLE
refactor(config): move execution config to default

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1828)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1828)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVCc0k3Tk3ObQ0P94Z:-NtVCc0k3Tk3ObQ0P94_:b-uhyqji) (no related file):*
Why are there changes related to load_test?

___
___
*[`config/default_config.json` line 173 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVAwaz8xGfVmdsILM_:-NtVAwaz8xGfVmdsILMa:b-so872) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/config/default_config.json#L173)):*
> ```JSON
>   },
>   "rpc.execution_config.eth_fee_contract_address": {
>     "description": "For executing transactions, the eth address to receive fees",
> ```

The ETH fee token contract address



_Code quote:_
```JSON
For executing transactions, the eth address to receive fees
```
___
*[`config/default_config.json` line 183 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVAztG7J_hEUDZAhHA:-NtVAztG7J_hEUDZAhHB:b-l90huv) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/config/default_config.json#L183)):*
> ```JSON
>   },
>   "rpc.execution_config.strk_fee_contract_address": {
>     "description": "For executing transactions, the strk address to receive fees",
> ```

The STRK fee token contract address



_Code quote:_
```JSON
For executing transactions, the strk address to receive fees
```
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVCAuA3-XZSSMKgJN0:-NtVCAuA3-XZSSMKgJN1:biiwaau) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/crates/papyrus_execution/src/testing_instances.rs#L34)):*
> ```XML
> 
> /// Creates ExecutionConfig for tests.
> pub fn get_mock_execution_config() -> ExecutionConfig {
> ```

get_test_execution_config (mock is a different thing)

Can you also add a todo to make the execution tests use the default execution config?



_Code quote:_
```XML
get_mock_execution_config
```
___
*[`crates/papyrus_rpc/src/lib.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVD2pUE4kMnOztqJhD:-NtVD2pUE4kMnOztqJhE:b2qdcac) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/crates/papyrus_rpc/src/lib.rs#L146)):*
> ```XML
>                 &param.description[1..]
>             );
>         }
> ```

Why to do this?



_Code quote:_
```XML
        for param in execution_config_dump.values_mut() {
            param.description = format!(
                "For executing transactions, {}{}",
                param.description[0..1].to_lowercase(),
                &param.description[1..]
            );
        }
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1828)* status: 13 of 23 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVCc0k3Tk3ObQ0P94Z:-NtoorFo4iWLgDSaQ7NK:bvth56w) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why are there changes related to load_test?
</blockquote></details>

reverted

___
___
*[`config/default_config.json` line 173 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVAwaz8xGfVmdsILM_:-NtookgY5F1fO4EJMikK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/config/default_config.json#L173)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The ETH fee token contract address
</blockquote></details>

Done.
___
*[`config/default_config.json` line 183 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVAztG7J_hEUDZAhHA:-NtookTk3S3my44lgjW7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/config/default_config.json#L183)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The STRK fee token contract address
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVCAuA3-XZSSMKgJN0:-NtoojqA1m5higmBZsku:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/crates/papyrus_execution/src/testing_instances.rs#L34)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

get_test_execution_config (mock is a different thing)

Can you also add a todo to make the execution tests use the default execution config?
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/lib.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-NtVD2pUE4kMnOztqJhD:-NtodmCT4-gNvmNgSRoS:beap3b3) ([raw file](https://github.com/starkware-libs/papyrus/blob/f6c6b1c448fe2f2b46a1beaf0f2528c67ac7ca37/crates/papyrus_rpc/src/lib.rs#L146)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why to do this?
</blockquote></details>

Reused this style from other dumps

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1828#-:-NtyurQ61JEoo7y88hKz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
Please revert preset deletion

**Pull request merged**
