### PR TITLE
build: upgrade blockifier to 0.5.0-rc.1

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/python_json_formatter.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqabZih2WUZlr13LUSq:-NqabZih2WUZlr13LUSr:b2ni1ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_common/src/python_json_formatter.rs#L5)):*
> ```XML
> use serde_json::ser::{CompactFormatter, Formatter};
> 
> pub struct PythonJsonFormatter;
> ```

doc
___
*[`crates/papyrus_execution/src/lib.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-Nqabh6oCnqpVRnSEKhL:-Nqabh6oCnqpVRnSEKhM:b-bbyqqf) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_execution/src/lib.rs#L359)):*
> ```XML
>     Invoke(InvokeTransaction, OnlyQuery),
>     // todo(yair): Do we need to support V0?
>     // The usize is the abi size.
> ```

Please use type aliases instead of usize
___
*[`crates/papyrus_execution/src/lib.rs` line 726 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqacSO224Fomj6Uo5lw:-NqacSO224Fomj6Uo5lx:b-larplr) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_execution/src/lib.rs#L726)):*
> ```XML
>                 Transaction::Declare(DeclareTransaction::V0(declare_tx)),
>                 tx_hash,
>                 Some(ClassInfo { contract_class: class_v0, sierra_program_length: 0, abi_length }),
> ```

Consider using a constant



_Code quote:_
```XML
0
```
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqadJln1E9ZaT8cI1aB:-NqadJln1E9ZaT8cI1aC:bhbqlbq) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L429)):*
> ```XML
> }
> 
> fn calculate_deprecated_class_abi_length(
> ```

Move to common with a todo to implement as a method of DeprecatedContractClass.
Also, implementing this as a trait will make it easier later.



_Code quote:_
```XML
calculate_deprecated_class_abi_length
```
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqaeUOv4zrRvIYmsEgQ:-NqaeUOv4zrRvIYmsEgR:b-fj704w) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L440)):*
> ```XML
> }
> 
> fn get_class_lengths(
> ```

Why not add `get_class_for_re_execution` function like we have `get_deprecated_class_for_re_execution` and make this function work on the class itself instead of fetching from the storage
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqadzOA5Q-w9m6Q_K9l:-NqadzOA5Q-w9m6Q_K9m:b-s4wee2) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L444)):*
> ```XML
>     state_number: StateNumber,
>     class_hash: ClassHash,
> ) -> Result<(usize, usize), ErrorObjectOwned> {
> ```

Please use type aliases / struct for the return type.



_Code quote:_
```XML
(usize, usize)
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-Nqabh6oCnqpVRnSEKhL:-NqaqNmY0501IeXmLwPD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_execution/src/lib.rs#L359)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use type aliases instead of usize
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqaeUOv4zrRvIYmsEgQ:-NqaqiAWBycTjKIqJKGV:bitb7wd) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L440)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not add `get_class_for_re_execution` function like we have `get_deprecated_class_for_re_execution` and make this function work on the class itself instead of fetching from the storage
</blockquote></details>

I see no benefit for your suggestion because we will only use this function here, and we don't call this function multiple times in the same flow
___
*[`crates/papyrus_common/src/python_json_formatter.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqabZih2WUZlr13LUSq:-Nqaq7F-2GCq_1_3i63f:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_common/src/python_json_formatter.rs#L5)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqadzOA5Q-w9m6Q_K9l:-NqavfwH8zbfOEt6JY41:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L444)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use type aliases / struct for the return type.
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/mod.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-NqadJln1E9ZaT8cI1aB:-NqavuGpE0OSVKJCVQ_7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1f5cb98eb18bdb42966214dcd4cae37d0e25cd5c/crates/papyrus_rpc/src/v0_4/api/mod.rs#L429)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move to common with a todo to implement as a method of DeprecatedContractClass.
Also, implementing this as a trait will make it easier later.
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_common/src/deprecated_class_abi.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-Nqb4GTo3RMUjtmuLGFp:-Nqb4GTp9OzjUF50cpor:b-ox2wmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/39b977fe074c4a645d15d06e41ea67f68ccb472e/crates/papyrus_common/src/deprecated_class_abi.rs#L54)):*
> ```XML
> 
> // TODO: Consider moving to SN API as a method of deprecated_contract_class::ContractClass.
> pub fn calculate_deprecated_class_abi_length(
> ```

Move up in the file



_Code quote:_
```XML
pub fn calculate_deprecated_class_abi_length(
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_common/src/deprecated_class_abi.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-Nqb4GTo3RMUjtmuLGFp:-Nqb53aLAzG52WCx20eo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/39b977fe074c4a645d15d06e41ea67f68ccb472e/crates/papyrus_common/src/deprecated_class_abi.rs#L54)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move up in the file
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1707#-:-Nqb59WyChc6SNVyHCWV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
