### PR TITLE
fix(starknet_client): add new 0.13.2 builtins

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 694 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2142#-O0DOWLc0jKZtP1CBdn-:-O0DOWLc0jKZtP1CBdn0:b-ib2747) ([raw file](https://github.com/starkware-libs/papyrus/blob/b93b0238e617bc3002ce09fdec4aaa0824b3ae72/crates/starknet_client/src/reader/objects/transaction.rs#L694)):*
> ```XML
>                     Builtin::Keccak => Some((starknet_api::transaction::Builtin::Keccak, count)),
>                     // These builtins should be ignored. We don't store them because they're not
>                     // part of the RPC or P2P specs.
> ```

Consider storing them now to be on the safe side. It will be easier to remove if necessary than to add later.



_Code quote:_
```XML
                    // These builtins should be ignored. We don't store them because they're not
                    // part of the RPC or P2P specs.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`Cargo.toml` line 156 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2142#-O0DVMc10u5EWjVIx0dJ:-O0DVMc22BPIf5-WWLEE:b-xrii9z) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef2f24c03959957e324d0e4a998aaca41025e14d/Cargo.toml#L156)):*
> ```TOML
> 
> [patch.crates-io]
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "f3ebd5b" }
> ```

Don't merge until that PR is merged to SN_API
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 694 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2142#-O0DOWLc0jKZtP1CBdn-:-O0DUybV5nHNoJGM2L7s:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b93b0238e617bc3002ce09fdec4aaa0824b3ae72/crates/starknet_client/src/reader/objects/transaction.rs#L694)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider storing them now to be on the safe side. It will be easier to remove if necessary than to add later.
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 949 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2142#-O0DVpFACr6yyXryFwNb:-O0DVpFACr6yyXryFwNc:b-qs5vam) ([raw file](https://github.com/starkware-libs/papyrus/blob/ef2f24c03959957e324d0e4a998aaca41025e14d/crates/papyrus_rpc/src/v0_7/transaction.rs#L949)):*
> ```XML
>                 .filter_map(|(k, v)| {
>                     v.try_into().ok().and_then(|v| (k.try_into().ok().map(|k| (k, v))))
>                 })
> ```

Consider adding a test 



_Code quote:_
```XML
                    v.try_into().ok().and_then(|v| (k.try_into().ok().map(|k| (k, v))))
                })
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)* status: all files reviewed, 1 unresolved discussion

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)* status: all files reviewed, 1 unresolved discussion

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2142)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
