### PR TITLE
fix(network): simplify handle_recieved_data

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578)* status: all files reviewed, 8 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4cTC46CW4f7IFB9Zv:-Nn4cTC46CW4f7IFB9Zw:b2at9k8) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L28)):*
> ```XML
>         protobuf::BlockHeadersResponse,
>     >,
>     header_pending_pairing: HashMap<OutboundSessionId, protobuf::BlockHeader>,
> ```

Shouldn't this simply be an Option of BlockHeader because there is only at most 1 header pending pairing every moment?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dr2m6tV-1ptpYjxA:-Nn4dr2m6tV-1ptpYjxB:bbrex2t) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e2e0954a3657ea4b7c2ca5d4237a997e4b8ca14/crates/papyrus_network/src/block_headers/behaviour.rs#L41)):*
> ```XML
>     #[error(transparent)]
>     ProtobufConversionError(#[from] ProtobufConversionError),
>     #[error("Pairing block header and signature error")]
> ```

Consider changing the message to "Received header when expected signature or signature when received header" 
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4c0Rz0ew98igd55C-:-Nn4bj-d21vxWd-z0jQs:bca63hu) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L192)):*
> ```XML
>         ignore_event_and_return_pending: &mut bool,
>     ) -> Event {
>         // TODO: handle getting more then one message part in the response.
> ```

then -> than
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4eQty7uE-N4V6XY3h:-Nn4eQty7uE-N4V6XY3i:b-970bc3) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L196)):*
> ```XML
>             match message {
>                 protobuf::block_headers_response_part::HeaderMessage::Header(header) => {
>                     *ignore_event_and_return_pending = true;
> ```

I guess this will be fixed in a future PR
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4cGEm1rxgwUsHgBsY:-Nn4cGEm1rxgwUsHgBsZ:bxjfxxp) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L197)):*
> ```XML
>                 protobuf::block_headers_response_part::HeaderMessage::Header(header) => {
>                     *ignore_event_and_return_pending = true;
>                     // TODO: check that there is no header for this session id already.
> ```

IMO you should do this TODO before merging to main
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4eZrm8ASHPS_2SJHV:-Nn4eZrm8ASHPS_2SJHW:ba1m7jo) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L210)):*
> ```XML
>                         .and_then(|header| header.try_into().ok())
>                     else {
>                         return Event::SessionFailed {
> ```

Use ok_or and ? instead of let-else
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4ejbE30gsd54NChlM:-Nn4ejbE30gsd54NChlN:b52un0w) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L225)):*
> ```XML
>                         })
>                         .ok()
>                     else {
> ```

Use map_err and ? instead of let-else
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dQD55vQ3qtZUBLLE:-Nn4dQD55vQ3qtZUBLLF:b6ye1os) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L247)):*
> ```XML
>         } else {
>             Event::SessionFailed {
>                 session_id: SessionId::OutboundSessionId(OutboundSessionId { value: usize::MAX }),
> ```

usize::MAX?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dMft5SGvqIkK1OVP:-Nn4dMft5SGvqIkK1OVQ:b-f2xnnf) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L248)):*
> ```XML
>             Event::SessionFailed {
>                 session_id: SessionId::OutboundSessionId(OutboundSessionId { value: usize::MAX }),
>                 session_error: SessionError::StreamedDataEventConversionError,
> ```

This should be ProtobufConversionError IMO

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4cTC46CW4f7IFB9Zv:-Nn8BCpQ9ZMMvJ9i9d38:bjsccnj) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Shouldn't this simply be an Option of BlockHeader because there is only at most 1 header pending pairing every moment?
</blockquote></details>

one per session right?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dr2m6tV-1ptpYjxA:-Nn8FZG68lj04g82nlca:b-ytimpa) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e2e0954a3657ea4b7c2ca5d4237a997e4b8ca14/crates/papyrus_network/src/block_headers/behaviour.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider changing the message to "Received header when expected signature or signature when received header"
</blockquote></details>

but that's the **internal** error we get when failing to convert protobuf object to our own objects.. I think the error you are referring to is `block_headers::SessionError::ParinigError`
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4eQty7uE-N4V6XY3h:-Nn8GWN50xx1pER_BSnw:b2nign6) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L196)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I guess this will be fixed in a future PR
</blockquote></details>

yes
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4cGEm1rxgwUsHgBsY:-Nn8GZhA8jaxfrurKtTG:b-7tdf7d) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L197)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO you should do this TODO before merging to main
</blockquote></details>

agree
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4eZrm8ASHPS_2SJHV:-Nn8H_Mc63Z-jOzf6V4t:b-o0fmea) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L210)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use ok_or and ? instead of let-else
</blockquote></details>

can't use ? since the function returns an Event and not Result
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4ejbE30gsd54NChlM:-Nn8HgRU-SBMwKhu1CN_:bnj7hl0) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L225)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use map_err and ? instead of let-else
</blockquote></details>

same as above
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dQD55vQ3qtZUBLLE:-Nn8HjjiETFVn3FYxLYu:b-oszpse) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L247)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

usize::MAX?
</blockquote></details>

yeah.. it's wrong.. got fixed in one of the other PRs.. I can fix it here if you think it makes any difference
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dMft5SGvqIkK1OVP:-Nn8JHL59am1T-1xQCdC:bgwmw1s) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L248)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be ProtobufConversionError IMO
</blockquote></details>

it's not even that.. it's that the data was converted correctly to protobuf but is incompatible with what we expect it to be.. for example (under the current assumption that we get only one header part) if we get an empty vector or a message that is None.
what do you think about this new name?

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-:-Nn8Mhcv3Y1vY1gxeDNC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dr2m6tV-1ptpYjxA:-Nn8MA791G-FgLo0D3Oa:b-jeseks) ([raw file](https://github.com/starkware-libs/papyrus/blob/3e2e0954a3657ea4b7c2ca5d4237a997e4b8ca14/crates/papyrus_network/src/block_headers/behaviour.rs#L41)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

but that's the **internal** error we get when failing to convert protobuf object to our own objects.. I think the error you are referring to is `block_headers::SessionError::ParinigError`
</blockquote></details>

Yes. Why do we have the internal error anyway? Can't we just return the SessionError?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4eZrm8ASHPS_2SJHV:-Nn8MT6nCJ9aoz9r4-Av:bh95ke4) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L210)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

can't use ? since the function returns an Event and not Result
</blockquote></details>

You're right
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4dMft5SGvqIkK1OVP:-Nn8MYEGBUw1aNoPrk-o:bb6ywmx) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L248)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's not even that.. it's that the data was converted correctly to protobuf but is incompatible with what we expect it to be.. for example (under the current assumption that we get only one header part) if we get an empty vector or a message that is None.
what do you think about this new name?
</blockquote></details>

LGTM

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1578#-Nn4cTC46CW4f7IFB9Zv:-Nn8QgVp0-33vA67N7Tn:b-frpg5r) ([raw file](https://github.com/starkware-libs/papyrus/blob/bf8c4bf0f354ce6deda08ef2631cbdf27c90d74a/crates/papyrus_network/src/block_headers/behaviour.rs#L28)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

one per session right?
</blockquote></details>

You're right, WDYT about still wrapping the value with Option instead of erasing it and pushing it back? I think it will improve both readability and performance

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1578)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
