### PR TITLE
Yair/gw tracing

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Add tracing to gateway callbacks: makes every gateway callback run in a span

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/482)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
I think that when we log debug messages, we should use the Debug trait and not the Display

**Comment by yair-starkware** [comment]
Currently, we output the logs to the console, so I think the Display is more suitable.
At some point, we should collect the logs in a better way and then it will make sense to switch to the Debug trait.
@dan-starkware WDYT?

**Comment by dan-starkware** [comment]
I'm fine with display as long as there is no missing data for debugging. If there's a doubt, I think debug is better.

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/482#-:-NOP2EHQ2KQPlOvj-CMw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
