### PR TITLE
feat(network): drop outbound session

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1644)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1644)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/streamed_data/behaviour.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZBz0436MD1kMna_i:-NpOZBz0436MD1kMna_j:b1irkrc) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/behaviour.rs#L302)):*
> ```XML
>                         self.session_id_to_peer_id_and_connection_id.remove(&session_id);
>                         if let SessionId::OutboundSessionId(outbound_session_id) = session_id {
>                             if self.dropped_outbound_sessions.remove(&outbound_session_id) {
> ```

not sure why you need this if?
___
*[`crates/papyrus_network/src/streamed_data/handler.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZY0YD2rNEdM5PQyo:-NpOZY0YD2rNEdM5PQyp:b-vuakuj) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/handler.rs#L279)):*
> ```XML
>             } => {}
>             RequestFromBehaviourEvent::DropOutboundSession { outbound_session_id } => {
>                 self.pending_events.push_back(ConnectionHandlerEvent::NotifyBehaviour(
> ```

I think you should switch order of adding the event and internal handling of it. just in case

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1644)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_data/behaviour.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZBz0436MD1kMna_i:-NpOxIeqCHe_81fd5NAF:b-524sna) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/behaviour.rs#L302)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

not sure why you need this if?
</blockquote></details>

As I said in the comment below, doing 2 actions made it unreadable and you didn't understand why I do this
___
*[`crates/papyrus_network/src/streamed_data/handler.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZY0YD2rNEdM5PQyo:-NpOwzshB2svF5PBVxT-:bbuf402) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/handler.rs#L279)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think you should switch order of adding the event and internal handling of it. just in case
</blockquote></details>

Done. Noticed it's not readable to do 3 actions in 2 lines of code so I also split the code of the if

**Review by nagmo-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1644)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/streamed_data/behaviour.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZBz0436MD1kMna_i:-NpTWTuL7pKynvBcZOB8:b-9wngeu) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/behaviour.rs#L302)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As I said in the comment below, doing 2 actions made it unreadable and you didn't understand why I do this
</blockquote></details>

again.. didn't mind. but not sure about the if -> return.
is it to avoid adding the event to the pending events? i.e. mute the event?
if so (and also now I see it a few lines down maybe it'll be more redable if you state it.
let mute_event = false
...
if !mute_event { self.pending_events.push_back...}
___
*[`crates/papyrus_network/src/streamed_data/handler.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-NpOZY0YD2rNEdM5PQyo:-NpTVsUj9bsv7IsR2m9z:babe5hm) ([raw file](https://github.com/starkware-libs/papyrus/blob/cf8070fc366831421ffb1279c8e15223af01ae52/crates/papyrus_network/src/streamed_data/handler.rs#L279)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Done. Noticed it's not readable to do 3 actions in 2 lines of code so I also split the code of the if
</blockquote></details>

I didn't mind it actually

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1644#-:-NpThsqR7n8MpZfcH5Dg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
