### PR TITLE
feat(JSON-RPC): get_state_update supports pending

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1276)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1276)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1276#-NgrXYTzBdWb7fcU15cc:-NgrXYU-B9t-DLe1xvAP:b-ys3b8o) ([raw file](https://github.com/starkware-libs/papyrus/blob/86203b812c3838d89954e2d7a98fed2b6cdaccfd/crates/papyrus_rpc/src/v0_4_0/state.rs#L33)):*
> ```XML
>     pub old_root: GlobalRoot,
>     pub state_diff: ThinStateDiff,
> }
> ```

Won't it be better to add another struct for pending state update and an enum of the 2 variants?



_Code quote:_
```XML
#[derive(Debug, Clone, Eq, PartialEq, Deserialize, Serialize)]
pub struct StateUpdate {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub block_hash: Option<BlockHash>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub new_root: Option<GlobalRoot>,
    pub old_root: GlobalRoot,
    pub state_diff: ThinStateDiff,
}
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 293 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1276#-Ngrb1Th7rtoS258ZL-C:-Ngrb1Th7rtoS258ZL-D:bvaw800) ([raw file](https://github.com/starkware-libs/papyrus/blob/86203b812c3838d89954e2d7a98fed2b6cdaccfd/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L293)):*
> ```XML
>                 new_root: None,
>                 old_root: state_update.old_root,
>                 state_diff: state_update.state_diff.clone().into(),
> ```

Copy the old_root to a variable command to avoid cloning the whole state update



_Code quote:_
```XML
.clone()
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1276)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1276#-NgrXYTzBdWb7fcU15cc:-NgrmyC-DZHnhrNzEB8q:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/86203b812c3838d89954e2d7a98fed2b6cdaccfd/crates/papyrus_rpc/src/v0_4_0/state.rs#L33)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Won't it be better to add another struct for pending state update and an enum of the 2 variants?
</blockquote></details>

Done
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 293 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1276#-Ngrb1Th7rtoS258ZL-C:-Ngrcit63eGR5cPOmzdj:bopsmcw) ([raw file](https://github.com/starkware-libs/papyrus/blob/86203b812c3838d89954e2d7a98fed2b6cdaccfd/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L293)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Copy the old_root to a variable command to avoid cloning the whole state update
</blockquote></details>

I'm not cloning because of the old_root above. I'm cloning because state_update is a reference

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1276#-:-NgrqDRb-sxqlUDAnMRm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
