### PR TITLE
feat(starknet_client): retry upon StarknetErrorCode.TRANSACTION_LIMIT_EXCEEDED

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/963)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/963)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/src/starknet_client_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/963#-NauJc9t9nKaAyfJemjk:-NauJc9u-Y5ZgU1-FjUn:b-a1cs4d) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec96a91fde77fba80264950fda0729b502b27214/crates/starknet_client/src/starknet_client_test.rs#L78)):*
> ```XML
> 
> #[tokio::test]
> async fn request_with_retry_starknet_error_max_retries_reached() {
> ```

It seems like this is not the right error that should be returned to the user.
The user should receive the original Starknet errors and not a Retry error.
Talked with @dan-starkware, and as first step we could return something like InternalError, and later maybe something like a vector of all the errors received during the retry.

Can you check if that's something easy to implement?
___
*[`crates/starknet_client/src/starknet_client_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/963#-NauLFgeDM-sRgjN6v-K:-NauLFgeDM-sRgjN6v-L:b-ku9grj) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec96a91fde77fba80264950fda0729b502b27214/crates/starknet_client/src/starknet_client_test.rs#L114)):*
> ```XML
>         .with_status(StatusCode::BAD_REQUEST.as_u16().into())
>         .with_body(starknet_error_str)
>         .expect(MAX_RETRIES)
> ```

Shouldn't this be something like MAX_RETRIES - 1?



_Code quote:_
```XML
.expect(MAX_RETRIES)
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/963)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/starknet_client_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/963#-NauJc9t9nKaAyfJemjk:-NavymheDOXbv0b7uRIO:bltiabp) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec96a91fde77fba80264950fda0729b502b27214/crates/starknet_client/src/starknet_client_test.rs#L78)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It seems like this is not the right error that should be returned to the user.
The user should receive the original Starknet errors and not a Retry error.
Talked with @dan-starkware, and as first step we could return something like InternalError, and later maybe something like a vector of all the errors received during the retry.

Can you check if that's something easy to implement?
</blockquote></details>

What you're suggesting is a feature on top of this PR. This problem exists in the same way with the current RetryError
I can check if it's easy to implement and implement it after we merge this PR, but IMO this isn't urgent for this milestone
___
*[`crates/starknet_client/src/starknet_client_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/963#-NauLFgeDM-sRgjN6v-K:-Navyptg3EoO8c6clkFG:b-5n8k1y) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec96a91fde77fba80264950fda0729b502b27214/crates/starknet_client/src/starknet_client_test.rs#L114)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't this be something like MAX_RETRIES - 1?
</blockquote></details>

It's confusing, but MAX_RETRIES is inclusive

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/963)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/src/starknet_client_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/963#-NauJc9t9nKaAyfJemjk:-Naw1fT25BvmpSkqcWB_:b-id6yzx) ([raw file](https://github.com/starkware-libs/papyrus/blob/ec96a91fde77fba80264950fda0729b502b27214/crates/starknet_client/src/starknet_client_test.rs#L78)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What you're suggesting is a feature on top of this PR. This problem exists in the same way with the current RetryError
I can check if it's easy to implement and implement it after we merge this PR, but IMO this isn't urgent for this milestone
</blockquote></details>

Also, IMO InternalError is worse than the current error

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/963#-:-NbE4kyYE0pNBdZvGNgD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
