### PR TITLE
chore: upgrade SN API to have DA fields in execution resources

### PR DESCRIPTION
**Pull request by ShahakShama**
- fix(starknet_client): client can parse ExecutionResources::data_availability
- chore: upgrade SN API to have DA fields in execution resources

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1748)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1748)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkX5jQ2Bxh8dSRbnVX:-NrkX5jQ2Bxh8dSRbnVY:bfdz9kv) (no related file):*
Do we need to use these fields in the block hash calculation?

___
___
*[`Cargo.toml` line 127 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkVPrq8Eeehg9FC4Cd:-NrkVPrrCwQsyZ-TW5m6:bgdnwot) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/Cargo.toml#L127)):*
> ```TOML
> 
> [patch.crates-io]
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", branch = "shahak/execution_resources_da_on_0.8.0" }
> ```

IIRC we prevent patches from commits that are not on main in our CI



_Code quote:_
```TOML
"shahak/execution_resources_da_on_0.8.0"
```
___
*[`crates/papyrus_execution/src/objects.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkW7yw3hh-VSze9_K-:-NrkW7yw3hh-VSze9_K0:b-24e9k5) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/crates/papyrus_execution/src/objects.rs#L121)):*
> ```XML
>                         .execute_call_info
>                         .expect("Invoke transaction execution should contain execute_call_info."),
>                     transaction_execution_info.da_gas,
> ```

Note you need to remove this in the trace of the RPC v0.6



_Code quote:_
```XML
transaction_execution_info.da_gas,
```
___
*[`crates/papyrus_storage/src/lib.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkWlk28ZuEH4Bnh93k:-NrkWlk28ZuEH4Bnh93l:brnsj9s) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/crates/papyrus_storage/src/lib.rs#L133)):*
> ```XML
> /// migration is required for existing storages.
> /// This version is only checked for storages that store transactions (StorageScope::FullArchive).
> pub const STORAGE_VERSION_BLOCKS: Version = Version(14);
> ```

You need to rebase, the version bumped to 14 in a different PR



_Code quote:_
```XML
14
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1748)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, @ShahakShama, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkX5jQ2Bxh8dSRbnVX:-NrnSTyY7xWCUsgpL7MV:b4g7u1q) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do we need to use these fields in the block hash calculation?
</blockquote></details>

It's part of the receipt, and the receipt is not part of the hash
in 0.13.2 we will need

___
___
*[`Cargo.toml` line 127 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkVPrq8Eeehg9FC4Cd:-NrnSZxYC69u2fv4Nwvo:bp37h1h) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/Cargo.toml#L127)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IIRC we prevent patches from commits that are not on main in our CI
</blockquote></details>

The CI passes :sweat_smile: 
Anyway, the goal is to publish SN-API, merge your PR, rebase my PR and change the starknet_api to the new published version
___
*[`crates/papyrus_execution/src/objects.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkW7yw3hh-VSze9_K-:-NrnT6AJ93CaMJDHHJ5Q:b-iyioxf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/crates/papyrus_execution/src/objects.rs#L121)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note you need to remove this in the trace of the RPC v0.6
</blockquote></details>

It's already not part of it: https://github.com/starkware-libs/papyrus/blob/8664171a6e9dd83dbb164a20081ab40fdeee80b4/crates/papyrus_rpc/src/v0_6/transaction.rs#L778
___
*[`crates/papyrus_storage/src/lib.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-NrkWlk28ZuEH4Bnh93k:-Nrn__TH4wlS52TIBHu0:b-cl0m08) ([raw file](https://github.com/starkware-libs/papyrus/blob/b50485cc431f6bd633886a284e1509397cb56a37/crates/papyrus_storage/src/lib.rs#L133)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You need to rebase, the version bumped to 14 in a different PR
</blockquote></details>

Done.
Let's think of a way to make sure this doesn't happen again. Git didn't show any conflict

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1748#-:-Nro-woE7QEx63ABnUHj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 10 of 14 files at r3, 4 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1748)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware, @ShahakShama, and @yair-starkware)

**Pull request closed without merging**
