### PR TITLE
test(JSON-RPC): test spec for execution methods

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1552)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1552)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/test_utils.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVhZiJ8u2lYGE-aqNQ:-NmVhZiJ8u2lYGE-aqNR:b-4fx8aj) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/test_utils.rs#L344)):*
> ```XML
> }
> 
> #[allow(dead_code)]
> ```

Remove as well



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/papyrus_rpc/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVhh4dCvwihz5ogASb:-NmVhh4dCvwihz5ogASc:b-6qfn4q) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/test_utils.rs#L345)):*
> ```XML
> 
> #[allow(dead_code)]
> pub fn method_name_to_spec_method_name(method_name: &str) -> String {
> ```

Should it be public?



_Code quote:_
```XML
pub
```
___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 467 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVlz-q8SxU-tCsDDZO:-NmVlz-q8SxU-tCsDDZP:b7ezwx6) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/v0_4/execution_test.rs#L467)):*
> ```XML
>     // Using call_and_validate_schema_for_result in call_simulate_skip_validate and
>     // call_simulate_skip_fee_charge instead of here in order to also validate the simulation flags
>     // schema.
> ```

Shouldn't we use it here as well to test that the empty vector matches the schema?



_Code quote:_
```XML
    // Using call_and_validate_schema_for_result in call_simulate_skip_validate and
    // call_simulate_skip_fee_charge instead of here in order to also validate the simulation flags
    // schema.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1552)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/test_utils.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVhZiJ8u2lYGE-aqNQ:-NmVpuzc3p4BmhxEQlNf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/test_utils.rs#L344)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Remove as well
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVhh4dCvwihz5ogASb:-NmVptnE0U8Wq0sCRxMy:b-vcl0kl) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/test_utils.rs#L345)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Should it be public?
</blockquote></details>

https://github.com/starkware-libs/papyrus/blob/d335ee54d2805de0500b835398b07619d699e771/crates/papyrus_rpc/src/v0_4/api/test.rs#L974
___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 467 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-NmVlz-q8SxU-tCsDDZO:-NmVslta70xqvbXddD06:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7d60544126cabaedb0f2f17e874b56045e160419/crates/papyrus_rpc/src/v0_4/execution_test.rs#L467)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't we use it here as well to test that the empty vector matches the schema?
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1552#-:-NmVvUof-c5vgGhE4F5g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
