### PR TITLE
refactor(network): move callback from response_receiver to query_sender

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)* status: 11 of 13 files reviewed, 11 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKPOu0IU4XypHAek4:-O1VKPOu0IU4XypHAek5:b-kehksf) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L401)):*
> ```XML
>             gossipsub_impl::ExternalEvent::Received { originated_peer_id, message, topic_hash } => {
>                 let (report_callback, report_receiver) = oneshot::channel::<()>();
>                 let report_callback = Box::new(|| {
> ```

Add a TODO to change report_callback to report_sender (and the type from box<fn> to oneshot::Sender)
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKfIQBXWCnriAikSA:-O1VKfIQBXWCnriAikSB:bz97bh4) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L402)):*
> ```XML
>                 let (report_callback, report_receiver) = oneshot::channel::<()>();
>                 let report_callback = Box::new(|| {
>                     let _ = report_callback.send(());
> ```

log the error
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 464 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VIUNb7FZ4q9c92oGS:-O1VIUNc0RxLhpnaClrd:b-yaj3jy) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L464)):*
> ```XML
>                 );
>                 self.outbound_session_id_to_protocol.insert(outbound_session_id, protocol);
>                 match self
> ```

Right now this will always return an error. You should change consume_report_receiver to receive session id and inside the map extract the peer id from the session id (only when you call it)

Actually, now that I think of it, this means that you won't be able to report peers after the session was finished. I think that what we should eventually do is to store this oneshot in a hashmap of channels waiting for peer assignment, create an external event for SQMR behaviour of session assigned and once we get that event we add the oneshot to the FuturesUnordered. You can either do this or the former with a TODO to fix it
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VIyp43zy2eCbIhbfK:-O1VIyp43zy2eCbIhbfL:b-9kt6xn) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L473)):*
> ```XML
>                     Err(e) => {
>                         error!(
>                             "Failed to get peer id from session id. Session id: \
> ```

When you do the change mentioned above, change the message to "Got a report before any message was received. Ignoring report"
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VJyFa2IojsBX8Uch8:-O1VJyFa2IojsBX8Uch9:bs5ncnn) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
> ```XML
>         }
>     }
>     fn consume_report_receiver(&self, peer_id: PeerId, report_receiver: oneshot::Receiver<()>) {
> ```

Rename this. consume is not the main action you're doing here. How about handle_new_report_receiver
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKxVf4J0vKkQJgu3z:-O1VKxVf4J0vKkQJgu4-:b-bwmwzc) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L630)):*
> ```XML
> >;
> 
> pub type SubscriberSender<T> = With<
> ```

Rename to SqmrSubscriberSender
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 650 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLHKbA5BVh_Cjxau1:-O1VLHKbA5BVh_Cjxau2:bblt73n) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L650)):*
> ```XML
> 
> type BroadcastReceivedMessagesConverterFn<T> =
>     fn((Bytes, ReportCallback)) -> (Result<T, <T as TryFrom<Bytes>>::Error>, ReportCallback);
> ```

newline after this
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLN4_BQPdA-CymLa-:-O1VLN4_BQPdA-CymLa0:b-5yo6x1) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/test.rs#L240)):*
> ```XML
>         })
>         .collect::<Vec<_>>();
>     let (_report_callback, report_receiver) = oneshot::channel::<()>(); // this is used to report the peer
> ```

the comment here is unnecessary
___
*[`crates/papyrus_p2p_sync/src/client/header.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLVMxDzwItAJJtWP7:-O1VLVMxDzwItAJJtWP8:b-k7h41) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/header.rs#L47)):*
> ```XML
>     ) -> BoxFuture<'a, Result<Option<Self::Output>, P2PSyncError>> {
>         async move {
>             // TODO(shahak): Use the report callback.
> ```

move this TODO to the correct place
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLzdm6wtnJe5dHhzk:-O1VLzdm6wtnJe5dHhzl:b-b4o2c3) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L87)):*
> ```XML
>                     end_block_number,
>                 );
>                 //TODO(Eitan): abstract callback functionality to the channel struct
> ```

callback -> report
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLuVy5iFaMLGoIDyR:-O1VLuVy5iFaMLGoIDyS:b-e84hz8) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L88)):*
> ```XML
>                 );
>                 //TODO(Eitan): abstract callback functionality to the channel struct
>                 let (_report_callback, report_receiver) = oneshot::channel::<()>();
> ```

Rename callback to sender

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)* status: all files reviewed, 13 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1S9hNd9OqmpGi8XXkO:-O1S9hNd9OqmpGi8XXkP:b-j2n1tp) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L400)):*
> ```XML
>         match event {
>             gossipsub_impl::ExternalEvent::Received { originated_peer_id, message, topic_hash } => {
>                 let (report_callback, report_receiver) = oneshot::channel::<()>();
> ```

Symmetric with report_receiver. Also easier to read `report_callback` capturing `report_sender` than `report_callback`.



_Suggestion:_
```XML
report_sender
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1SEe8V5OR1_hBVK64m:-O1SEe8V5OR1_hBVK64n:b-31gw9z) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L630)):*
> ```XML
> >;
> 
> pub type SubscriberSender<T> = With<
> ```

What about naming: SubscriberSender, SubscriberSenderWithReport? (maybe the same for the receivers?)

I see you are using BroadcastSubscriberSender in  ReceivedQueryConverterFn which I presume has nothing to do with broadcast?

Honestly these types are quite complicated. It might be nice also to add a comment:



_Suggestion:_
```XML
/// Defines a channel where the sender puts and object `T` and the receiver gets it serialized to `Bytes`.
pub type SubscriberSender<T> = With<
    Sender<Bytes>,
    Bytes,
    T,
    Ready<Result<Bytes, SendError>>,
    fn(T) -> Ready<Result<Bytes, SendError>>,
>;

/// Channel where the receiver, in addition to the serialized `T`, gets a callback for reporting errors.
pub type SubscriberSenderWithReport<T> = With<
```

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)* status: all files reviewed, 13 unresolved discussions (waiting on @matan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKPOu0IU4XypHAek4:-O1VxHYr0HE7sP9fdvx_:b-ns61bm) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L401)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO to change report_callback to report_sender (and the type from box<fn> to oneshot::Sender)
</blockquote></details>

Done. GFI?
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKfIQBXWCnriAikSA:-O1VxbgBBkFKahyEzpfS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L402)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

log the error
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 464 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VIUNb7FZ4q9c92oGS:-O1W6IWf20GJj29biaIC:b-5b4uxc) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L464)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Right now this will always return an error. You should change consume_report_receiver to receive session id and inside the map extract the peer id from the session id (only when you call it)

Actually, now that I think of it, this means that you won't be able to report peers after the session was finished. I think that what we should eventually do is to store this oneshot in a hashmap of channels waiting for peer assignment, create an external event for SQMR behaviour of session assigned and once we get that event we add the oneshot to the FuturesUnordered. You can either do this or the former with a TODO to fix it
</blockquote></details>

im putting it as a todo - pr is already pretty big. i do like the first case where we call handle_new_report_receiver 
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VIyp43zy2eCbIhbfK:-O1W7L89-Jv540TsX2nL:b3zk37y) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L473)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

When you do the change mentioned above, change the message to "Got a report before any message was received. Ignoring report"
</blockquote></details>

adding this now
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VJyFa2IojsBX8Uch8:-O1VxpB64WsUJKniqnBh:b-yvlpfj) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename this. consume is not the main action you're doing here. How about handle_new_report_receiver
</blockquote></details>

Done. we should discuss using the word handle vs what we are actually doing (in this case adding the report_receiver to the polling set). i think it makes it  easier to understand the flow when function names aren't so abstract
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKxVf4J0vKkQJgu3z:-O1VylmI4Bzd-v6tQuXz:b-1ohmo2) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L630)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to SqmrSubscriberSender
</blockquote></details>

Done. also did receiver.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1SEe8V5OR1_hBVK64m:-O1W0HbZ5a0Y--1dEo59:b-l9it7u) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L630)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What about naming: SubscriberSender, SubscriberSenderWithReport? (maybe the same for the receivers?)

I see you are using BroadcastSubscriberSender in  ReceivedQueryConverterFn which I presume has nothing to do with broadcast?

Honestly these types are quite complicated. It might be nice also to add a comment:
</blockquote></details>

these channels will be changed a few more times so I think I will add it as a todo for now and then we will create good names once finished. i do agree though
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 650 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLHKbA5BVh_Cjxau1:-O1Vypka6SRcAbKyYKi3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L650)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

newline after this
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLN4_BQPdA-CymLa-:-O1VwqJoDpklpP7CRmXV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/test.rs#L240)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

the comment here is unnecessary
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/header.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLVMxDzwItAJJtWP7:-O1Vwg299chk1B5LHrJI:bg1yymy) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/header.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

move this TODO to the correct place
</blockquote></details>

Done. moved to stream builder
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLzdm6wtnJe5dHhzk:-O1Vw8NPCpyoQ5haVH4-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L87)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

callback -> report
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VLuVy5iFaMLGoIDyR:-O1Vw8hp3c1SxilSBROy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L88)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename callback to sender
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)* status: all files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1S9hNd9OqmpGi8XXkO:-O1kE9wr-GcSGSSONtfs:b32v57) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L400)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Symmetric with report_receiver. Also easier to read `report_callback` capturing `report_sender` than `report_callback`.
</blockquote></details>

+1
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKPOu0IU4XypHAek4:-O1kELen6EYlZY_H2kS4:b5lvhnr) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L401)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done. GFI?
</blockquote></details>

What I meant is returning/sending the oneshot channel instead of wrapping it in a box
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKfIQBXWCnriAikSA:-O1kEUSW3wYp3kWNMcy3:b8r2ei2) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L402)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not logging the error, this is logging everything
Capture the return value from report_callback.send(()) and if it's an error, add a log (with a different message)
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VJyFa2IojsBX8Uch8:-O1kFU8_7oaHqP0SbVcl:bbdsmax) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done. we should discuss using the word handle vs what we are actually doing (in this case adding the report_receiver to the polling set). i think it makes it  easier to understand the flow when function names aren't so abstract
</blockquote></details>

I'm open for name suggestions if you have any
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1kFjPu7887EB1jZI4S:-O1kFjPu7887EB1jZI4T:b-annydu) ([raw file](https://github.com/starkware-libs/papyrus/blob/4fa2fb1eaafee51bbe8a849fb76603a796f27c19/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L87)):*
> ```XML
>                     end_block_number,
>                 );
>                 // TODO(shahak): Use the report callback.
> ```

callback -> sender

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2213)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1S9hNd9OqmpGi8XXkO:-O1qqSpG03kZYrBZwmeB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L400)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKPOu0IU4XypHAek4:-O1uMQPYASjdNstwpaUD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L401)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What I meant is returning/sending the oneshot channel instead of wrapping it in a box
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VKfIQBXWCnriAikSA:-O1uQILmCUWzRe8XTJRR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L402)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not logging the error, this is logging everything
Capture the return value from report_callback.send(()) and if it's an error, add a log (with a different message)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 510 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2213#-O1VJyFa2IojsBX8Uch8:-O1uLoQnDxbd0aAAZU0w:b5qulym) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e08e5773b015c5b014cc6391cc86750d18f2546/crates/papyrus_network/src/network_manager/mod.rs#L510)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm open for name suggestions if you have any
</blockquote></details>

ill leave it for now - it's a discussion we should have on function naming consensus throughout the crate

**Pull request merged**
