### PR TITLE
Store starknet_version

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814)* status: all files reviewed, 8 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

___
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_81Mvp8KowHYuKktsn:-N_81Mvp8KowHYuKktso:b-2c1gvv) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
> ```XML
>         block_number: BlockNumber,
>         block_header: &BlockHeader,
>         starknet_version: StarknetVersion,
> ```

Why is it part of append_header and not a separate function?



_Code quote:_
```XML
starknet_version: StarknetVersion,
```
___
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_88b9s9-ra3aCq0g-w:-N_88b9s9-ra3aCq0g-x:bsaswre) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
> ```XML
>         block_number: BlockNumber,
>         block_header: &BlockHeader,
>         starknet_version: StarknetVersion,
> ```

Borrow instead of consuming.



_Code quote:_
```XML
starknet_version: StarknetVersion
```
___
*[`crates/papyrus_storage/src/header_test.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_87pbk0Lj2R4nOd-RR:-N_87pbk0Lj2R4nOd-RS:bwn7hat) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header_test.rs#L156)):*
> ```XML
>     fn block_header(hash: u8) -> BlockHeader {
>         BlockHeader { block_hash: BlockHash(stark_felt!(hash)), ..BlockHeader::default() }
>     }
> ```

Consider moving outside



_Code quote:_
```XML
    fn block_header(hash: u8) -> BlockHeader {
        BlockHeader { block_hash: BlockHash(stark_felt!(hash)), ..BlockHeader::default() }
    }
```
___
*[`crates/papyrus_storage/src/header_test.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_886qZ9K79O9ws4vGa:-N_886qZ9K79O9ws4vGb:b-70bo03) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header_test.rs#L170)):*
> ```XML
>     assert_eq!(block_0_starknet_version.unwrap(), StarknetVersion::default());
> 
>     let block_1_starknet_version =
> ```

Rename it to "non_existing_block_sn_version", or maybe just don't store it in a variable.
Otherwise it's confusing.



_Code quote:_
```XML
block_1_starknet_version
```
___
*[`crates/papyrus_storage/src/body/mod.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_89PD6437tUMwgERRR:-N_89PD6437tUMwgERRS:b-j9z4v1) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/body/mod.rs#L31)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
> pub struct StarknetVersion(pub String);
> ```

Why is it in the body module?
___
*[`crates/papyrus_sync/src/sources/central.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_8A8ve6fmT0ur8vIlr:-N_8A8ve6fmT0ur8vIls:bq287yu) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_sync/src/sources/central.rs#L284)):*
> ```XML
>                 Block::try_from(block).map_err(|err| CentralError::ClientError(Arc::new(err)))?,
>                 starknet_version,
>             ))
> ```

Consider introducing a function that takes a Client block and returns the block + the version to avoid cloning.
Another option is to use Rc<&str> instead of String (watch when you find the time: https://www.youtube.com/watch?v=A4cKi7PTJSs&feature=youtu.be)



_Code quote:_
```XML
            let starknet_version = StarknetVersion(
                block
                    .starknet_version
                    .as_ref()
                    .map_or("0.0.0".to_string(), |version| version.clone()),
            );
            Ok((
                Block::try_from(block).map_err(|err| CentralError::ClientError(Arc::new(err)))?,
                starknet_version,
            ))
```
___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_8B1PXDyCXoxNmdVCm:-N_8B1PXDyCXoxNmdVCn:b-eilgcb) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_sync/src/sources/central_sync_test.rs#L135)):*
> ```XML
>                     ..BlockHeader::default()
>                 };
>                 yield Ok((block_number, Block { header, body: BlockBody::default() }, StarknetVersion("starknet_version".to_string())));
> ```

Use const



_Code quote:_
```XML
StarknetVersion("starknet_version".to_string())));
```
___
*[`crates/starknet_reader_client/src/objects/block.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_8BF0V7XyamMQPwC17:-N_8BF0V7XyamMQPwC18:b-leotke) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/starknet_reader_client/src/objects/block.rs#L57)):*
> ```XML
>     pub transaction_receipts: Vec<TransactionReceipt>,
>     // Optional since old blocks don't include this field.
>     pub starknet_version: Option<String>,
> ```

Why not add #[serde(default)]?

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814)* status: 3 of 17 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_81Mvp8KowHYuKktsn:-N_8eac0AVPg200jhtuI:b9fm5wt) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it part of append_header and not a separate function?
</blockquote></details>

I think of it as part of the block metadata, where do you think it should go?
___
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_88b9s9-ra3aCq0g-w:-N_8gzW2DqAIgpTh7RPq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Borrow instead of consuming.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/header_test.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_87pbk0Lj2R4nOd-RR:-N_8hKIz3u8KnPyntHiK:bk9hirj) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header_test.rs#L156)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider moving outside
</blockquote></details>

It is used only here. Moved it to the beginning of the test. LMK if you prefer it elsewhere.
___
*[`crates/papyrus_storage/src/header_test.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_886qZ9K79O9ws4vGa:-N_8hnxE3u3ETFP0_pfO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header_test.rs#L170)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename it to "non_existing_block_sn_version", or maybe just don't store it in a variable.
Otherwise it's confusing.
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_8A8ve6fmT0ur8vIlr:-N_Awzdv-o7_qd6eOkIy:b-2iskuf) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_sync/src/sources/central.rs#L284)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider introducing a function that takes a Client block and returns the block + the version to avoid cloning.
Another option is to use Rc<&str> instead of String (watch when you find the time: https://www.youtube.com/watch?v=A4cKi7PTJSs&feature=youtu.be)
</blockquote></details>

Not sure this is what you had in mind. Let's talk f2f
___
*[`crates/papyrus_storage/src/body/mod.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_89PD6437tUMwgERRR:-N_8iQ396QDMdo-z29W1:b-ggqo88) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/body/mod.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it in the body module?
</blockquote></details>

No good reason. Moved to header.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

___
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_81Mvp8KowHYuKktsn:-N_DRH6fAzN4JkvvBgcd:bda3xun) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I think of it as part of the block metadata, where do you think it should go?
</blockquote></details>

Is it going to be part of the header in P2P for example?
I think it should probably be in a separate function.
___
*[`crates/papyrus_storage/src/serializers.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_DTL6h1cETpPQbV12W:-N_DTL6h1cETpPQbV12X:bhscfkv) ([raw file](https://github.com/starkware-libs/papyrus/blob/a361d74ee3f82e62a1e664de66557653e72084d6/crates/papyrus_storage/src/serializers.rs#L832)):*
> ```XML
> impl StorageSerde for StarknetVersion {
>     fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>         self.0.to_string().serialize_into(res)
> ```

Replace to_string with as_bytes to avoid redundant allocation



_Code quote:_
```XML
self.0.to_string().serialize_into(res)
```

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 14 files at r4, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814#-:-N_YrPIFAzsFL5I3TubE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by dan-starkware** [comment]
*[`crates/starknet_reader_client/src/objects/block.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_8BF0V7XyamMQPwC17:-N_VOkLWA5BtwxsLixu1:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/starknet_reader_client/src/objects/block.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not add #[serde(default)]?
</blockquote></details>

Done

**Comment by dan-starkware** [comment]
*[`crates/papyrus_storage/src/header.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/814#-N_81Mvp8KowHYuKktsn:-N_VOn0P4wuiPjm86A9p:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/73c5b75cb40d0874fa3761223dffcc2a3f1c0d6f/crates/papyrus_storage/src/header.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is it going to be part of the header in P2P for example?
I think it should probably be in a separate function.
</blockquote></details>

Done

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r6, 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/814#-:-N_ci9IW8VlC17aWmoua:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
