### PR TITLE
feat: support pending block for get_nonce()

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1376)

### CODE REVIEW

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-NiiyTn15qbNpVDQ4QDs:-Nij22l18c7y6Gp5otRo:b-vi0nak) ([raw file](https://github.com/starkware-libs/papyrus/blob/e5599c291b1418d1ca1de5478f26f054069858be/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L617)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider doing a match instead of if let
</blockquote></details>

Done. (although I'm not sure that it makes the code more readable. wdyt?)
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1281 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-NiiymSZ8snfVvW4ZXHh:-Nij3ASH8KnPtpLNDX3J:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e5599c291b1418d1ca1de5478f26f054069858be/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1281)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add this case when the pending block is up to date
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-NiiyTn15qbNpVDQ4QDs:-Nij3l2PCwODZO1jAn6O:b-ov93a7) ([raw file](https://github.com/starkware-libs/papyrus/blob/e5599c291b1418d1ca1de5478f26f054069858be/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L617)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Done. (although I'm not sure that it makes the code more readable. wdyt?)
</blockquote></details>

IMO its better, but not by a large margin
Whatever you think is more readable
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1273 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-Nij3xJa8A1FpJzHVy08:-Nij3xJa8A1FpJzHVy09:bas5tbt) ([raw file](https://github.com/starkware-libs/papyrus/blob/26f39114085a461b972091a663fc7e51e354342b/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1273)):*
> ```XML
> 
>     // Ask for nonce in pending block where the contract is deployed in the pending block.
>     let contract_address = ContractAddress(patricia_key!("0x1234"));
> ```

Rename to new_pending_contract_address or new_contract_address

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1376)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1273 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-Nij3xJa8A1FpJzHVy08:-Nij53S86BKUnzUl0maZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/26f39114085a461b972091a663fc7e51e354342b/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1273)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to new_pending_contract_address or new_contract_address
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1376#-:-Nij5E84B9i6kzLyrPFJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
