### PR TITLE
Yoav/config/rearrangement crate

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Sqc7N-1flwtPUPjwL:-N_Sqc7P8DGgrEqdbf52:b-p3j7a8) (no related file):*
Please document public functions with '///' and private/pub(crate) functions with '//'.

___
___
*[`crates/papyrus_config/src/config_test.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Sr6Ak4gU4bnqCAu04:-N_Sr6Ak4gU4bnqCAu05:b-u31oul) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/config_test.rs#L187)):*
> ```XML
>         BTreeMap::from([ser_param("param_path", &json!("default value"), "This is a.")]);
>     let custom_config_path =
>         get_absolute_path("crates/papyrus_config/src/custom_config_example.json");
> ```

We put json files in a resources dir.
___
*[`crates/papyrus_config/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Srf4l7ycu-TNbtjIG:-N_Srf4l7ycu-TNbtjIH:bspwq66) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/lib.rs#L11)):*
> ```XML
> //! a) a custom config file, given in the command line flag `config_file`, and
> //! b) environment variables and command line flags. The args are flattened and documented in
> //! `default_config.json` file. The environment variables should be set in uppercase.
> ```

//! Configuration utilities for Papyrus node.
//!
//! Configuration order of precedence in ascending order:
//!     - default
//!     - config file at a path provided in the command line arguments
//!     - environment variables (capital letters)
//!     - command line arguments

Regarding the rest - can we separate the code into modules (loading and dumping)?



_Code quote:_
```XML
//! Configuration utilities for a Starknet node.
//!
//! This crate divides into two parts: defining a default config and loading a custom config based
//! on the default values.
//!
//! The default configuration is serialized into `default_config.json` file, you should never edit
//! it manually.
//! Before the node is running, the configuration may be updated by:
//! a) a custom config file, given in the command line flag `config_file`, and
//! b) environment variables and command line flags. The args are flattened and documented in
//! `default_config.json` file. The environment variables should be set in uppercase.
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_TrtSkBNzwh5MLyiH2:-N_TrtSkBNzwh5MLyiH3:b-2aibt4) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_node/src/config/mod.rs#L12)):*
> ```XML
> use std::{env, fs, io};
> 
> use clap::{arg, value_parser, Arg, ArgMatches, Command};
> ```

Please arrange the functions visibility and the documentation in this file.
___
*[`crates/papyrus_node/src/config/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_TrTSzChSzrXa991_J:-N_TrTSzChSzrXa991_K:b-crauc0) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_node/src/config/mod.rs#L93)):*
> ```XML
>             .join("../..")
>             .join(DEFAULT_CONFIG_PATH);
>         let default_config_file = std::fs::File::open(path).unwrap();
> ```

Expect instead of unwrapping.



_Code quote:_
```XML
        let path = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
            .join("../..")
            .join(DEFAULT_CONFIG_PATH);
        let default_config_file = std::fs::File::open(path).unwrap();
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Sqc7N-1flwtPUPjwL:-N_XcRsq5L2lsvhD6vw8:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please document public functions with '///' and private/pub(crate) functions with '//'.
</blockquote></details>

Done.

___
___
*[`crates/papyrus_config/src/config_test.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Sr6Ak4gU4bnqCAu04:-N_Xd7H5-XCG4f1yd5Eg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/config_test.rs#L187)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We put json files in a resources dir.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Srf4l7ycu-TNbtjIG:-N_XqMXXB7RXFl9ORbju:b60r506) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/lib.rs#L11)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

//! Configuration utilities for Papyrus node.
//!
//! Configuration order of precedence in ascending order:
//!     - default
//!     - config file at a path provided in the command line arguments
//!     - environment variables (capital letters)
//!     - command line arguments

Regarding the rest - can we separate the code into modules (loading and dumping)?
</blockquote></details>

Yes, done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_TrtSkBNzwh5MLyiH2:-N_XfMSF1GqO3ecDrdxa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_node/src/config/mod.rs#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please arrange the functions visibility and the documentation in this file.
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_TrTSzChSzrXa991_J:-N_Xht5UCvpiURG59VZn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_node/src/config/mod.rs#L93)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Expect instead of unwrapping.
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 11 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/command.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YFn6K0M9afhZRBSFw:-N_YFn6K0M9afhZRBSFx:b1oy68m) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/command.rs#L10)):*
> ```XML
> use crate::{ParamPath, SerializedParam, SubConfigError};
> 
> pub fn get_command_matches(
> ```

pub(crate)
___
*[`crates/papyrus_config/src/config_test.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YGp6j0hmD5snrGrJz:-N_YGp6j0hmD5snrGrK-:b1ruj8g) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/config_test.rs#L21)):*
> ```XML
> };
> use crate::{ParamPath, PointerParam, SerializedParam, SubConfigError};
> ```

Remove the 'pub' from the test structs
___
*[`crates/papyrus_config/src/config_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YH5N-7vHmfm-3Y-dA:-N_YH5N-7vHmfm-3Y-dB:b-5eljh6) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/config_test.rs#L185)):*
> ```XML
> 
> #[test]
> pub fn test_update_by_custom_config() {
> ```

remove pub
___
*[`crates/papyrus_config/src/converters.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YHC2z5P6mzQApuZ0H:-N_YHC2z5P6mzQApuZ0I:b-162442) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/converters.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

Module level doc (this is a public module)
___
*[`crates/papyrus_config/src/dumping.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YQIrv0nb4HZUmcaob:-N_YQIrv0nb4HZUmcaoc:b-ntxc72) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L1)):*
> ```XML
> use std::collections::BTreeMap;
> ```

module-level documentation
___
*[`crates/papyrus_config/src/dumping.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YZjJ-BedRz4FFIqb3:-N_YZjJ-BedRz4FFIqb4:b-mhna6v) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L8)):*
> ```XML
> use crate::{ParamPath, PointerParam, SerializedParam, SubConfigError};
> 
> pub const DEFAULT_CHAIN_ID: &str = "SN_MAIN";
> ```

Remove ass discussed



_Code quote:_
```XML
pub const DEFAULT_CHAIN_ID: &str = "SN_MAIN";
```
___
*[`crates/papyrus_config/src/dumping.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YJ_Cf65mzYVRYMWVa:-N_YJ_Cf65mzYVRYMWVb:b-ap5oh2) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L14)):*
> ```XML
>     /// Conversion of a configuration to a mapping of flattened parameters to their descriptions and
>     /// values.
>     /// Note, in the case of a None sub configs, its elements will not included in the flatten map.
> ```

It is not clear what the implementor needs to do.
Add a doc example



_Code quote:_
```XML
/// Note, in the case of a None sub configs, its elements will not included in the flatten map.
```
___
*[`crates/papyrus_config/src/dumping.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YYqr393NSizhRexOh:-N_YUdRb-cC234RcG7je:b-qrwbfe) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L46)):*
> ```XML
> /// Adds to the map the target params with value of one of the params that points to it.
> /// Replaces the value of the pointers to contain only the name of the target they point to.
> pub fn combine_config_map_and_pointers(
> ```

Make the changes we discussed
___
*[`crates/papyrus_config/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Srf4l7ycu-TNbtjIG:-N_YSpBnAkqDle8vUq9x:bbts3s5) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/lib.rs#L11)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Yes, done.
</blockquote></details>

Write an example in which:
1. a simple config component implements the SerializeConfig trait
2. the default config is dumped to a file
3. the config is loaded

See the papyrus_storage crate for inspiration: https://docs.rs/papyrus_storage/0.0.1/papyrus_storage/
___
*[`crates/papyrus_config/src/loading.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YZ5_u-ivW1KmC2dWb:-N_YZ5_v-o1aIp9J2O-O:b2ni1ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/loading.rs#L14)):*
> ```XML
> use crate::{command, ParamPath, PointerParam, SerializedParam, SubConfigError};
> 
> pub fn load_and_process_config<T: for<'a> Deserialize<'a>>(
> ```

doc

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: 7 of 28 files reviewed, 11 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

___
*[`crates/papyrus_config/src/command.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YFn6K0M9afhZRBSFw:-N_YjIMX3jOq1j2Knl0R:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/command.rs#L10)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

pub(crate)
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/config_test.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YGp6j0hmD5snrGrJz:-N_YjUaU71cHvQWhUoZm:b-t69q0q) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/config_test.rs#L21)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Remove the 'pub' from the test structs
</blockquote></details>

Oooops.
___
*[`crates/papyrus_config/src/config_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YH5N-7vHmfm-3Y-dA:-N_YjXJs4UmIHB-TQIab:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/config_test.rs#L185)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

remove pub
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/converters.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YHC2z5P6mzQApuZ0H:-N_YoAK63_pI4tygWe0b:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/converters.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Module level doc (this is a public module)
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YQIrv0nb4HZUmcaob:-N_YxOvb0gEWoWgGbL1O:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

module-level documentation
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YZjJ-BedRz4FFIqb3:-N_Yj_kh6Ui-SNHlJFvK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L8)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Remove ass discussed
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YJ_Cf65mzYVRYMWVa:-N_h7-_-3Py4IIEr1Rpj:bskbpd5) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It is not clear what the implementor needs to do.
Add a doc example
</blockquote></details>

There is not much to do. This is a drawback that I have not been able to overcome.
___
*[`crates/papyrus_config/src/dumping.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YYqr393NSizhRexOh:-N_YjcxG2dmJ8FunM5tx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/dumping.rs#L46)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Make the changes we discussed
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_Srf4l7ycu-TNbtjIG:-N_niBszEWchdFqFUJhI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/08e36f28f2cd0080be2a1ad37bae86a414ed280b/crates/papyrus_config/src/lib.rs#L11)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Write an example in which:
1. a simple config component implements the SerializeConfig trait
2. the default config is dumped to a file
3. the config is loaded

See the papyrus_storage crate for inspiration: https://docs.rs/papyrus_storage/0.0.1/papyrus_storage/
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/loading.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YZ5_u-ivW1KmC2dWb:-N_YzkLW9XhUjVudU64i:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/loading.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 12 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o73KQ5AOHTZsaQvTN:-Na0SQWh2uB7CZggLCt_:b3v73n7) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It seems like some unrelated files were formatted. Is this intended?
</blockquote></details>

All these changes are the result of `cargo +nightly fmt --all`

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_oBiJpC_WQhujdGtIA:-Na0T1O-9Jt72XQ2LsFO:b-i24ntl) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

clippy fails:
cargo clippy --all-targets --all-features -- -D warnings -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused

</blockquote></details>

It passes locally.

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 12 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o0Bwt7rvO9MvAJKE8:-Na0XH7T52-sj3z60O-S:bt2k1mb) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/converters.rs#L3)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add doc examples
</blockquote></details>

It makes sense only if the `load` function is public (the `dump` trait function is public).
Otherwise, the doc-example will contain unnecessary files stuff.
WDYT?
___
*[`crates/papyrus_config/src/dumping.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o9xg_AhSYFNOTJ3H_:-Na0_TE17LyGfkxaMFwB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/dumping.rs#L4)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/14901245/how-to-style-a-json-block-in-github-wiki
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o1xop0nmqzNu0T6UN:-Na0aYGPDr6g0caByC1b:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/dumping.rs#L77)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

remove pub
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o1Lxp7c6MYz5-oLOX:-Na0aa9E3xYtf39mM9c6:bgck8is) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/dumping.rs#L77)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding the value to the input instead of taking the first in the vector
</blockquote></details>

OK, but not in this PR.
___
*[`crates/papyrus_config/src/dumping.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o56R8DcqzHd7icpPR:-Na0bDBi56PySxA06VsX:bfh6fmw) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/dumping.rs#L98)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Warn if the value doesn't equal the pointer target
</blockquote></details>

We talked about it:
a. Not everyone who runs the binary will see the warning.
b. We test it.
c. As you asked, I will use the (new) explicit value of the pointer and ignore the values of the pointing params.
___
*[`crates/papyrus_config/src/lib.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_oBSwd0qcrd7BMCIWt:-Na0ficIBXrrN6wuVp4K:b-w7spwp) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/lib.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

add #![warn(missing_docs)]
</blockquote></details>

:astonished: 
___
*[`crates/papyrus_config/src/loading.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_YZ5_u-ivW1KmC2dWb:-Na0lR7W8_oSruhfJ16s:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/a8fa69db948c356a7245714c23532b522b89309e/crates/papyrus_config/src/loading.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Also the function (load_and_process)
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 11 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o73KQ5AOHTZsaQvTN:-Na0mlKsCH8zjAeuAfYG:b-626p38) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

All these changes are the result of `cargo +nightly fmt --all`
</blockquote></details>

We use `cargo +nightly-2022-11-03 fmt --all`

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_oBiJpC_WQhujdGtIA:-Na0msoD2YU4VbofEh7g:b-qx4ab4) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It passes locally.
</blockquote></details>

Did you use the same cmd?

___
___
*[`crates/papyrus_config/src/dumping.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o56R8DcqzHd7icpPR:-Na0nL2Q7-IcQC5XAtJz:b-9qp766) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/dumping.rs#L98)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

We talked about it:
a. Not everyone who runs the binary will see the warning.
b. We test it.
c. As you asked, I will use the (new) explicit value of the pointer and ignore the values of the pointing params.
</blockquote></details>

Right, sorry

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 11 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_config/src/converters.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o0Bwt7rvO9MvAJKE8:-Na0zWfyB4jdzDG4qZ-g:bjleenn) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/converters.rs#L3)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It makes sense only if the `load` function is public (the `dump` trait function is public).
Otherwise, the doc-example will contain unnecessary files stuff.
WDYT?
</blockquote></details>

I thought these functions are needed also in the dumping, but I see I'm wrong.
Doesn't the whole modue can be private then (and pub(crate) where necessary)?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: all files reviewed, 9 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_oBiJpC_WQhujdGtIA:-Na0t6825xpZepP3QHgH:bsz1s9y) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Did you use the same cmd?
</blockquote></details>

Yes. It passed with and without the changes.

___
___
*[`crates/papyrus_config/src/converters.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o0Bwt7rvO9MvAJKE8:-Na13Gup-qAThC2l586Z:bophxi4) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_config/src/converters.rs#L3)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I thought these functions are needed also in the dumping, but I see I'm wrong.
Doesn't the whole modue can be private then (and pub(crate) where necessary)?
</blockquote></details>

All the functions in this module need to be public.
For example in `CentralSourceConfig`.
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o67a7C8BdORfY786N:-Na0ryL3DKhUVGERJh4O:b-7zurln) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_storage/src/compiled_class.rs#L68)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

intended?
</blockquote></details>

Undo.
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o6Pvu0g6JoYsLRYOg:-Na0rwM5-u_DhGhPw6eJ:b-7zurln) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_storage/src/compiled_class_test.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

intended?
</blockquote></details>

Undo.
___
*[`crates/papyrus_storage/src/body/events.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/854#-N_o6TxX9qCerteWyogR:-Na0sbLx95UQlhq-1BSm:b-7zurln) ([raw file](https://github.com/starkware-libs/papyrus/blob/bcff88d1815d125b61940920b2c256bd59a31400/crates/papyrus_storage/src/body/events.rs#L126)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

intended?
</blockquote></details>

Undo.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854#-:-Na1GArfD_RPDPKpuUdO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
