### PR TITLE
refactor(JSON-RPC): rpc server test util takes shared highest block

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-NbU1hvtAicVZ_Wucsoj:-NbU1hvtAicVZ_Wucsok:bg2602n) ([raw file](https://github.com/starkware-libs/papyrus/blob/3444568295f810c38bde1ce7d7618c846525adf6/crates/papyrus_gateway/src/test_utils.rs#L45)):*
> ```XML
> pub(crate) fn get_test_rpc_server_and_storage_writer_from_mock_client<T: JsonRpcServerImpl>(
>     mock_client: MockStarknetWriter,
>     shared_highest_block: Arc<RwLock<Option<BlockHashAndNumber>>>,
> ```

Create a function with just mock_client, one with just shared_highest_block and one for both

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-NbU1hvtAicVZ_Wucsoj:-NbU5zli6GJ8u222EVZs:bxhqzwc) ([raw file](https://github.com/starkware-libs/papyrus/blob/3444568295f810c38bde1ce7d7618c846525adf6/crates/papyrus_gateway/src/test_utils.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Create a function with just mock_client, one with just shared_highest_block and one for both
</blockquote></details>

It's exponential...
WDYT about one simple function, and one function with optional parameters?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-NbU1hvtAicVZ_Wucsoj:-NbU74yQ1VlJjgkdKl2V:b-9wpq9t) ([raw file](https://github.com/starkware-libs/papyrus/blob/3444568295f810c38bde1ce7d7618c846525adf6/crates/papyrus_gateway/src/test_utils.rs#L45)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It's exponential...
WDYT about one simple function, and one function with optional parameters?
</blockquote></details>

ok, but rename from_options to from_params

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-NbU1hvtAicVZ_Wucsoj:-NbUS3vRDU8dWrKbYNHO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3444568295f810c38bde1ce7d7618c846525adf6/crates/papyrus_gateway/src/test_utils.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

ok, but rename from_options to from_params
</blockquote></details>

Done.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ShahakShama)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-:-NbUnXv88SNVuPcf6QLt:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1020#-:-NbUq37m5zXFJrw4JSOY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
