### PR TITLE
Dvir/papyrus consensus context

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vs7HI8KsFU1F8UcIN:-O-Vs7HJC2QwSECpoFeF:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e6b44e54b5a428db60c307c5f9ba6b93bd87fc3/crates/sequencing/papyrus_consensus/src/lib.rs#L32)):*
> ```XML
>     loop {
>         info!("Starting consensus for height {start_height}");
>         let mut shc = SingleHeightConsensus::new(start_height, context.clone(), validator_id).await;
> ```





_Suggestion:_
```XML
        let mut shc = SingleHeightConsensus::new(current_height, context.clone(), validator_id).await;
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VsbDa8nGDBAjyxNV9:-O-VsbDb7fX2ROnaHQwv:b3kre) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L2)):*
> ```XML
> #[cfg(test)]
> #[path = "papyrus_context_test.rs"]
> ```

?



_Suggestion:_
```XML
papyrus_consensus_context_test
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VtQZn07QIUbC1G9Cu:-O-VtQZo3nee2nPsyltg:be0jf2k) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L57)):*
> ```XML
> }
> 
> const CHANNEL_SIZE: usize = 5000;
> ```

Why 5k?



_Code quote:_
```XML
const CHANNEL_SIZE: usize = 5000;
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vvmh_3WXl_vxDmRoy:-O-Vvmh_3WXl_vxDmRoz:b-1oa7z1) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L100)):*
> ```XML
>                         .block_hash,
>                 })
>                 .expect("Send should succeed");
> ```

And below



_Suggestion:_
```XML
            let block_hash = txn
                        .get_block_header(height)
                        .expect("Get header from storage failed")
                        .expect(&format!(
                            "Block in {height} was no found in storage although waiting for it"
                        ))
                        .block_hash;
            fin_sender
                .send(PapyrusConsensusBlock {
                    content: transactions,
                    id: block_hash,
                })
                .expect("Send should succeed");
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vu1z04gCtKHK4ZyML:-O-Vu1z11MFASC6AjWAV:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L124)):*
> ```XML
>                 .expect("Get transactions from storage failed")
>                 .expect(&format!(
>                     "Block in {height} was no found in storage although waiting for it"
> ```





_Suggestion:_
```XML
                    "Block in {height} was not found in storage despite waiting for it"
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vv0_C8m_yJ-C4mLHp:-O-Vv0_C8m_yJ-C4mLHq:b-1oa7z1) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L128)):*
> ```XML
> 
>             for tx in transactions.iter() {
>                 let recived_tx = content
> ```

And below



_Suggestion:_
```XML
received_tx
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vvcs3COEEcgh5VZBs:-O-Vvcs4BbttF6jAiW6I:bh0ivsu) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L162)):*
> ```XML
>     fn proposer(&self, _validators: &Vec<ValidatorId>, _height: BlockNumber) -> ValidatorId {
>         0u8.into()
>     }
> ```

btw for `validators`, in M1 we just expect to pass a config on startup with a static list of validators.  
`proposer` will just be something simple like `self.config.validators[height % len]`



_Code quote:_
```XML
    async fn validators(&self, _height: BlockNumber) -> Vec<ValidatorId> {
        vec![0u8.into(), 1u8.into(), 2u8.into()]
    }

    fn proposer(&self, _validators: &Vec<ValidatorId>, _height: BlockNumber) -> ValidatorId {
        0u8.into()
    }
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VtnZP2N8Wu-DIhtiI:-O-VtnZP2N8Wu-DIhtiJ:b-xe0psq) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L195)):*
> ```XML
> const SLEEP_BETWEEN_CHECK_FOR_BLOCK: Duration = Duration::from_secs(10);
> 
> async fn wait_to_block(
> ```

This means that papyrus storage is behind the block that we want and so we will wait until the block can be found?



_Suggestion:_
```XML
async fn wait_for_block(
```
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_context_test.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VwUNW9mggFFuXCe7g:-O-VwUNW9mggFFuXCe7h:b-aqj66l) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_context_test.rs#L101)):*
> ```XML
> }
> 
> fn get_storage_with_block_and_papyrus_context()
> ```

Doesn't mention network_receiver and is already pretty long.

I thought that convention was to put these types of functions above the tests themselves?



_Suggestion:_
```XML
test_setup
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 130 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-WDtTtBgy8SGGv2I5i:-O-WDtTu2L82Rmoku-5D:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/59a9dcdb3e3533edf917f504eee559d717fb25e6/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L130)):*
> ```XML
>                     .next()
>                     .await
>                     .expect(&format!("Not recived transaction equals to {tx:?}"));
> ```





_Suggestion:_
```XML
received
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vs7HI8KsFU1F8UcIN:-O-W7a9k9iDJJ7hSSQqr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5e6b44e54b5a428db60c307c5f9ba6b93bd87fc3/crates/sequencing/papyrus_consensus/src/lib.rs#L32)):*
> ```XML
>     loop {
>         info!("Starting consensus for height {start_height}");
>         let mut shc = SingleHeightConsensus::new(start_height, context.clone(), validator_id).await;
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VsbDa8nGDBAjyxNV9:-O-W7byz6uqJdWIrOaCx:b-wcqfwb) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L2)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

This is on purpose. The name is getting too long, and the context is clear. I change this to end with this PR.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VtQZn07QIUbC1G9Cu:-O-W9rMq4pQkO9-03mhA:b-pinrw7) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L57)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why 5k?
</blockquote></details>

why not? It should be larger than any existing block and not be too high.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vvmh_3WXl_vxDmRoy:-O-WAkL54aBbDv1k_0zh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L100)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

And below
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vu1z04gCtKHK4ZyML:-O-WAwQ4CQhqJ8FJdlqA:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L124)):*
> ```XML
>                 .expect("Get transactions from storage failed")
>                 .expect(&format!(
>                     "Block in {height} was no found in storage although waiting for it"
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vv0_C8m_yJ-C4mLHp:-O-WAw8d-Xy5nFXv8LIr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L128)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

And below
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-Vvcs3COEEcgh5VZBs:-O-WCWyp2FFx_IS8LRnl:b-3bck55) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L162)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

btw for `validators`, in M1 we just expect to pass a config on startup with a static list of validators.  
`proposer` will just be something simple like `self.config.validators[height % len]`
</blockquote></details>

Make this change after you run the consensus for the first time. It will make a problem when you don't have all the validators.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VtnZP2N8Wu-DIhtiI:-O-WB0KSD_G6pKg0Q5Lw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs#L195)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This means that papyrus storage is behind the block that we want and so we will wait until the block can be found?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/papyrus_context_test.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2111#-O-VwUNW9mggFFuXCe7g:-O-WCT8v1S3dg__pU32n:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/63bbbe2438d131f89c3d881124cc7a9ebcd6e46b/crates/sequencing/papyrus_consensus/src/papyrus_context_test.rs#L101)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Doesn't mention network_receiver and is already pretty long.

I thought that convention was to put these types of functions above the tests themselves?
</blockquote></details>

Done.

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 2 of 2 files at r3, 3 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
