### PR TITLE
feat(JSON-RPC, execution): add units to the fee

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-NlwvEXbDVqSZKsibDHX:-NlwvEXbDVqSZKsibDHY:bmstl9) ([raw file](https://github.com/starkware-libs/papyrus/blob/4f12f6614a7c882f13452e6d59aa96ca7cfde37a/crates/papyrus_execution/src/lib.rs#L477)):*
> ```XML
> // TODO(yair): Return structs instead of tuples.
> #[allow(clippy::too_many_arguments)]
> #[allow(clippy::type_complexity)]
> ```

Fixing in the following PR
___
*[`crates/papyrus_execution/src/lib.rs` line 722 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-NlwvJBZ2rwL-d8ooq-r:-NlwvJBZ2rwL-d8ooq-s:bmstl9) ([raw file](https://github.com/starkware-libs/papyrus/blob/4f12f6614a7c882f13452e6d59aa96ca7cfde37a/crates/papyrus_execution/src/lib.rs#L722)):*
> ```XML
> // TODO(yair): Return structs instead of tuples.
> #[allow(clippy::too_many_arguments)]
> #[allow(clippy::type_complexity)]
> ```

Fixing in the following PR

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-NlwzCRN7z7rbgUu2mxe:-NlwzCRN7z7rbgUu2mxf:bckktwa) ([raw file](https://github.com/starkware-libs/papyrus/blob/560977a219182bbb9052828a3da9cc7efd033404/crates/papyrus_execution/src/lib.rs#L459)):*
> ```XML
>         .into_iter()
>         .enumerate()
>         .map(|(index, (tx_execution_info, _induced_state_dif, price_unit))| {
> ```

typo. dif -> diff
___
*[`crates/papyrus_execution/src/lib.rs` line 527 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-Nlwyz6j3TgTBkKVU4bX:-Nlwyz6j3TgTBkKVU4bY:bn5o807) ([raw file](https://github.com/starkware-libs/papyrus/blob/560977a219182bbb9052828a3da9cc7efd033404/crates/papyrus_execution/src/lib.rs#L527)):*
> ```XML
>                 PriceUnit::Fri
>             }
>             _ => PriceUnit::Wei,
> ```

Consider adding a version method and using it here instead

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-NlwzCRN7z7rbgUu2mxe:-NlxN5SR-dDgJKmv4B1_:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/560977a219182bbb9052828a3da9cc7efd033404/crates/papyrus_execution/src/lib.rs#L459)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

typo. dif -> diff
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 527 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-Nlwyz6j3TgTBkKVU4bX:-NlxN-XNB7nNmB6EsbDM:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/560977a219182bbb9052828a3da9cc7efd033404/crates/papyrus_execution/src/lib.rs#L527)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider adding a version method and using it here instead
</blockquote></details>

done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-:-Nm5ToA6DW31aaBhnsWH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 539 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-Nm5TdXf-ocXhn7m8kqz:-Nm5TdXf-ocXhn7m8kr-:b-whg6fp) ([raw file](https://github.com/starkware-libs/papyrus/blob/bb684b01a9f6ea6ea090659aa9a85a59ee0f7fa5/crates/papyrus_execution/src/lib.rs#L539)):*
> ```XML
>                 PriceUnit::Wei
>             }
>             TransactionVersion::THREE => PriceUnit::Fri,
> ```

Consider uniting THREE with _

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 539 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-Nm5TdXf-ocXhn7m8kqz:-Nm6DX-h5yAHvteuoIQa:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/bb684b01a9f6ea6ea090659aa9a85a59ee0f7fa5/crates/papyrus_execution/src/lib.rs#L539)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider uniting THREE with _
</blockquote></details>

done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1522#-:-NmArWjrBpJCITVo7vMO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
