### PR TITLE
Add execution crate with blockifier state implementation

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?
Introducing an execution crate, implementing the the blockifier state reader API.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/685)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/685)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxM0_s-JgQsqwCseIu:-NVxM0_s-JgQsqwCseIv:b-5e58cg) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L19)):*
> ```XML
> 
> /// A [`StateReader`] with a fixed block number that implements [`blockifier`] [`StateReader`].
> ```

unneeded line break
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxM8YE7jQCZ7K47MEg:-NVxM8YE7jQCZ7K47MEh:bsy8764) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L22)):*
> ```XML
> pub struct PapyrusStateReader<'env> {
>     pub reader: RawPapyrusStateReader<'env>,
>     // Invariant: Read-Only.
> ```

should this be here?
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxd86eAwoEBg-Zp39c:-NVxd86eAwoEBg-Zp39d:b-z8h0gs) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L39)):*
> ```XML
> }
> 
> impl<'env> StateReader for PapyrusStateReader<'env> {
> ```

there probably needs to be a test for the implementation of these APIs. right?
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxNr4N667H-PxKTRf6:-NVxNr4N667H-PxKTRf7:b-gyfvri) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L64)):*
> ```XML
>         match self.reader.get_class_hash_at(state_number, &contract_address) {
>             Ok(Some(class_hash)) => Ok(class_hash),
>             Ok(None) => Ok(ClassHash::default()),
> ```

I'm not sure I understand what's the meaning of none here.. 
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxOC969Ya-C1tWoh5_:-NVxOC969Ya-C1tWoh5a:b-j0d31j) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L87)):*
> ```XML
>         _class_hash: ClassHash,
>     ) -> StateResult<CompiledClassHash> {
>         todo!()
> ```

is this intentional?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/685)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxM8YE7jQCZ7K47MEg:-NVy59Bc8pw-vG0RYLJC:b34wvh7) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L22)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

should this be here?
</blockquote></details>

Are you referring to the comment? why not? (if you want, you can highlight code before commenting and it'll be clearer)
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxd86eAwoEBg-Zp39c:-NVy5QQF9og8mkBuuW3L:b-g99j1n) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L39)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

there probably needs to be a test for the implementation of these APIs. right?
</blockquote></details>

yes :smiling_face_with_tear: 
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxNr4N667H-PxKTRf6:-NVy5U1K5fjBaaPpScqG:b-ia541z) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L64)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I'm not sure I understand what's the meaning of none here.. 
</blockquote></details>

Means the read command was executed successfully (no DB/network errors), but the `class_hash` given doesn't exist in the DB.
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxOC969Ya-C1tWoh5_:-NVy5s02COTtI3xNw0XD:bohum6y) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L87)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

is this intentional?
</blockquote></details>

Yes, will be added soon (maybe even someone is working on it currently).

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/685)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @giladchase and @nagmo-starkware)

___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxM0_s-JgQsqwCseIu:-NVxpoyE07Dap9yZCeSw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L19)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

unneeded line break
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxd86eAwoEBg-Zp39c:-NVzpc83Ealcp7_9ODjJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

yes :smiling_face_with_tear: 
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxNr4N667H-PxKTRf6:-NVzlP4z34ThaqPbKsiO:b-hsg6ym) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L64)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Means the read command was executed successfully (no DB/network errors), but the `class_hash` given doesn't exist in the DB.
</blockquote></details>

The function assumes the class is declared.
___
*[`crates/papyrus_execution/src/blockifier_state_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVzpj0347EdhLjMBbY2:-NVzpj0347EdhLjMBbY3:b-t8axrz) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state_test.rs#L22)):*
> ```XML
> 
> #[test]
> fn entry_point_with_papyrus_state() -> papyrus_storage::StorageResult<()> {
> ```

This test will stay at the blockifier, for now.

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/685)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_execution/src/blockifier_state.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/685#-NVxNr4N667H-PxKTRf6:-NW0y0p00sXaqK21TnBK:b4i0zu3) ([raw file](https://github.com/starkware-libs/papyrus/blob/8d7457462e335007d62a3c25d0ec8e5ca9415413/crates/papyrus_execution/src/blockifier_state.rs#L64)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

The function assumes the class is declared.
</blockquote></details>

@dan-starkware are you trying to say that you expect the None case to never happen? if so I think we should add a comment that says that.
I'll rephrase my original question.. assuming we get None from the reader, that means the call didn't fail but the value was not found. why would we return a hash of zero? (the default for ClassHash) 
I think that if the reason is that it's an illegal hash and we expect the caller to verify, it should say so. 
An alternative is in fact return a None which is clearly not a value the caller can use.

**Pull request merged**
