### PR TITLE
feat(network): change fetch_block_data_from_db return output to Vec<Data>

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-Nz88fOF013uXaBgVvX2:-Nz88fOF013uXaBgVvX3:bsi4ztd) ([raw file](https://github.com/starkware-libs/papyrus/blob/42c7e4c11c8911bd6c9bd4a5ae99e3a982bad2b0/crates/papyrus_network/src/db_executor/mod.rs#L218)):*
> ```XML
>         query: Query,
>         data_type: impl FetchBlockDataFromDb + Send + 'static,
>         mut sender: Sender<Data>,
> ```

Change this to Sender<Vec<Data>>, and then in the bottom change the call to first() to a for loop and then you can remove the clone

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-Nz88fOF013uXaBgVvX2:-NzMVk86-e10T1y4fM_4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/42c7e4c11c8911bd6c9bd4a5ae99e3a982bad2b0/crates/papyrus_network/src/db_executor/mod.rs#L218)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to Sender<Vec<Data>>, and then in the bottom change the call to first() to a for loop and then you can remove the clone
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSDOdn2xfVHH48oWBv:-NzSDOdo62eXCoGHN0fQ:b-47850o) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L79)):*
> ```XML
>                 if i == 0 {
>                     // requested DataType dictates what kind of Data we should expect.
>                     match requested_data_type {
> ```

Change the match here to be on data, and then do assert_matches on requested_data_type
This will allow you to unite both matches to a single one
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSCLcY7Nc4eZsa5E8t:-NzSCLcY7Nc4eZsa5E8u:bwb8jyw) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L84)):*
> ```XML
>                         }
>                         DataType::StateDiff => {
>                             for data in data.iter() {
> ```

Move the for outside of the match
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSDHecANmpUSGmS8pi:-NzSDHed9sH915of4voq:bkflt9z) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L91)):*
> ```XML
>                     }
>                 }
>                 for data in data.iter() {
> ```

Once you do my suggestion above, you can have one for

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSDOdn2xfVHH48oWBv:-NzSHNll4erG3xFKgfsn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the match here to be on data, and then do assert_matches on requested_data_type
This will allow you to unite both matches to a single one
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSCLcY7Nc4eZsa5E8t:-NzSHO718iUpgoEhFqae:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L84)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move the for outside of the match
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSDHecANmpUSGmS8pi:-NzSHToE1_Dfk0kDeblH:b-8fx2u7) ([raw file](https://github.com/starkware-libs/papyrus/blob/5934b19a6234e79397d4e12e717ff967f579b834/crates/papyrus_network/src/db_executor/test.rs#L91)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Once you do my suggestion above, you can have one for
</blockquote></details>

:+1:

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSWyWV-suz7AUxIDsD:-NzSWyWV-suz7AUxIDsE:b-i73z9a) ([raw file](https://github.com/starkware-libs/papyrus/blob/d794cb0d5889ba4028ed341dc2f7c47b7ddcf91d/crates/papyrus_network/src/db_executor/test.rs#L84)):*
> ```XML
>                         }
>                         Data::StateDiff{state_diff: ThinStateDiff { .. }} => {
>                             assert_matches!(data, Data::StateDiff{..});
> ```

Remove this assertion (you already validated this in the match), and return the TODO

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/test.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-NzSWyWV-suz7AUxIDsD:-NzSa5WS0bC-YeNS2JDk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d794cb0d5889ba4028ed341dc2f7c47b7ddcf91d/crates/papyrus_network/src/db_executor/test.rs#L84)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this assertion (you already validated this in the match), and return the TODO
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2067#-:-NzSaKvABgPbWkJedfY3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
