### PR TITLE
refactor(network): change streamed_data to streamed_bytes

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): move code around
- refactor(network): change streamed_data to streamed_bytes

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1719)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1719** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1719?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1723** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1723?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1719?utm_source=stack-comment).

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1719)* status: 3 of 37 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/streamed_bytes/mod.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1719#-Ns8pZY11QTkZbz694aO:-NsDUDCh8ij3FskLDZVq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/333e6e20660675e433d429b7c218a6accb55a0a5/crates/papyrus_network/src/streamed_bytes/mod.rs#L66)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/streamed_bytes/mod.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1719#-Ns8paPd2vaxdWYjHeoO:-NsDUD1DBi2-sPz_qzDB:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/333e6e20660675e433d429b7c218a6accb55a0a5/crates/papyrus_network/src/streamed_bytes/mod.rs#L70)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this is an important comment. either find a way to deal with it or put it in a better place.
also consider using the Protocol enum from my PR somehow
</blockquote></details>

Done.

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1719#-:-NsDUXPwBufZJHRccftX:bnfp4nl)* status: 3 of 37 files reviewed, all discussions resolved

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1719#-:-NsDZu8i8wC3CwaiTFFs:bnfp4nl)* status: 3 of 37 files reviewed, all discussions resolved

**Pull request merged**
