### PR TITLE
Add dump trait for sub configs.

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 496

## What is the new behavior?

- A dump file for configurations with the default values and the members' descriptions.
- Currently only for the gateway config.

## Does this introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information

The default config yaml file is flattened and structured as follows:
\- - variable path
\- variable Description
\- default value

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGtx6r6mxaLR_OFy2L):*
I see the `SubConfig` trait which adds dump functionality.
___
*[`crates/papyrus_gateway/src/lib.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGugg41k9QUXumBuSo:-NXGugg41k9QUXumBuSp:baandsf) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L59)):*
> ```XML
> }
> 
> impl SubConfig for GatewayConfig {
> ```

This is a lot of boilerplate, do we really want to implement this for every config? We technically have the ability to serialize with just a macro from serde, so it's not obvious to me why we want to pay this cost?



_Code quote:_
```XML
impl SubConfig for GatewayConfig
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGuoz67NAQwvSnT-HP:-NXGuoz67NAQwvSnT-HQ:b-5x4134) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L64)):*
> ```XML
>     }
> 
>     fn dump(&self) -> Vec<(ParamPath, SerializedValue, Description)> {
> ```

Since you just use type aliases there is no enforcement (since they are all really String), but I think the description is consistently second.



_Suggestion:_
```XML
ParamPath, Description, SerializedValue
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGvbgdDfSkawBWuhRw:-NXGvbgdDfSkawBWuhRx:b-j0x2m4) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L68)):*
> ```XML
>             (
>                 GatewayConfig::chain_id_path(),
>                 String::from("The chain to follow. For more details see https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#chain-id."),
> ```

Also was there no way to utilize the comment descriptions like what we discussed on zoom? That is nice since it keeps the comments near the struct definition which is really nice.



_Code quote:_
```XML
                String::from("The chain to follow. For more details see https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#chain-id."),
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGt_6L3O0NNBwXVbGM:-NXGt_6L3O0NNBwXVbGN:b-gpyiq) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L78)):*
> ```XML
>             (
>                 GatewayConfig::max_events_chunk_size_path(),
>                 String::from("Maximum chunk size supported by the node in get_events requests."),
> ```

What are the units? bytes? TXs? something else?



_Code quote:_
```XML
chunk size
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

___
*[`crates/papyrus_gateway/src/lib.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGvbgdDfSkawBWuhRw:-NXGw9q5-1DwlSOP0sg8:ba8rfs1) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Also was there no way to utilize the comment descriptions like what we discussed on zoom? That is nice since it keeps the comments near the struct definition which is really nice.
</blockquote></details>

Could be worth opening an issue on https://github.com/clap-rs/clap

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: all files reviewed, 7 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

___
*[`config/default_config.yaml` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd6XjV0BqvXaCBGmGc:-NXd6XjV0BqvXaCBGmGd:bt7qrj5) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/config/default_config.yaml#L1)):*
> ```YAML
> {
> ```

Is this still yaml? It looks like JSON
___
*[`crates/papyrus_config/Cargo.toml` line 8 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd6UAZ44i8HCJLhh0M:-NXd6UA_4qteTUrmzv3k:b8dw327) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/Cargo.toml#L8)):*
> ```TOML
> [dependencies]
> serde.workspace = true
> serde_json.workspace = true
> ```

What are these?



_Code quote:_
```TOML
serde.workspace = true
serde_json.workspace = true
```
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd7c8_BJC4_-Iw6V2w:-NXd7c8_BJC4_-Iw6V2x:b-libv5q) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L23)):*
> ```XML
> 
>     /// Serializes the sub-config into JSON.
>     fn dumps(&self) -> Map<String, Value> {
> ```

Are we able to deserialize this into the Struct it was created from or just into a JSON Map?



_Code quote:_
```XML
    fn dumps(&self) -> Map<String, Value> {
```
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdBET93P3KvLtOQscf:-NXdBET93P3KvLtOQscg:bl0xtjs) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L23)):*
> ```XML
> 
>     /// Serializes the sub-config into JSON.
>     fn dumps(&self) -> Map<String, Value> {
> ```

Does this work well recursively? So if I have a SubConfig with fields that are also SubConfigs? (This can be a follow up PR if it's complex enough)



_Code quote:_
```XML
fn dumps(&self) -> Map<String, Value> {
```
___
*[`crates/papyrus_config/src/lib.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdBcYS78cmXldilygL:-NXdBcYS78cmXldilygM:bxl5hnp) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L25)):*
> ```XML
>     fn dumps(&self) -> Map<String, Value> {
>         let descriptions = Self::fields_description();
>         let json_map: Map<String, Value> = serde_json::to_value(self)
> ```

Ok my understanding is that all fields in the struct (json_map) must be described by the implementer in `fields_description`. We don't check for excess fields in `fields_description`. Do we want to do that somehow? (`descriptions.len() == json_map.len()`)? It would be really nice if it could be compile time but that's probably a big pain.



_Code quote:_
```XML
        let descriptions = Self::fields_description();
        let json_map: Map<String, Value> = serde_json::to_value(self)
```
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdCN591OhRfOZkMEix:-NXdCN591OhRfOZkMEiy:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
> ```XML
> 
> #[test]
> fn test_dump_default_config() {
> ```





_Suggestion:_
```XML
/// Regression test which checks that the default config hasn't changed as well as dumping/parsing configs.
fn test_dump_default_config() {
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGvbgdDfSkawBWuhRw:-NXd7mOkCi61mHA-NVP0:byetjaz) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L68)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

There is no simple way to do it.
I will take care of the command line flags later, and maybe change how we process the descriptions.
</blockquote></details>

 So I guess we are giving up on automated "comment -> description"
___
*[`crates/papyrus_gateway/src/lib.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGt_6L3O0NNBwXVbGM:-NXd7DycCoi7fBD_I4HI:b-phnf9y) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L78)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I copied the description,
The content is out of the scope of this PR.
</blockquote></details>

I won't block but I think adding units to the comment would be nice and (I'm assuming) not add much work to the PR.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @matan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_config/Cargo.toml` line 8 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd6UAZ44i8HCJLhh0M:-NXdF1nRB1_KRAcMrXld:brq5o02) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/Cargo.toml#L8)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What are these?
</blockquote></details>

It allows us to use this crate within the config crate.
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd7c8_BJC4_-Iw6V2w:-NXdHKlE9S9LdPQ459a1:b-4ctxgu) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L23)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are we able to deserialize this into the Struct it was created from or just into a JSON Map?
</blockquote></details>

In the next PR I'll add loading functionality.
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdBET93P3KvLtOQscf:-NXey14o0lRlF4VxlC-s:b-896fja) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L23)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Does this work well recursively? So if I have a SubConfig with fields that are also SubConfigs? (This can be a follow up PR if it's complex enough)
</blockquote></details>

Done!
___
*[`crates/papyrus_config/src/lib.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdBcYS78cmXldilygL:-NXey2k2BNMRPJ7aDg_6:b-proyl) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_config/src/lib.rs#L25)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Ok my understanding is that all fields in the struct (json_map) must be described by the implementer in `fields_description`. We don't check for excess fields in `fields_description`. Do we want to do that somehow? (`descriptions.len() == json_map.len()`)? It would be really nice if it could be compile time but that's probably a big pain.
</blockquote></details>

Irrelevant.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXdCN591OhRfOZkMEix:-NXeyqb82NI2uDMNI2pf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
> ```XML
> 
> #[test]
> fn test_dump_default_config() {
> ```

Done.
___
*[`crates/papyrus_gateway/src/lib.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXGvbgdDfSkawBWuhRw:-NXdDcCeCnieHrNFNvQd:b-nvrvxh) ([raw file](https://github.com/starkware-libs/papyrus/blob/aa6d7a553f0aaf2ff06993feab19c7bff110608f/crates/papyrus_gateway/src/lib.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

 So I guess we are giving up on automated "comment -> description"
</blockquote></details>

Not in this PR
___
*[`config/default_config.yaml` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXd6XjV0BqvXaCBGmGc:-NXdFutb5vQT53-CVgs-:b-sb9kuh) ([raw file](https://github.com/starkware-libs/papyrus/blob/f7630149fcee10048bf5ecdb87cbd9f4851126c5/config/default_config.yaml#L1)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is this still yaml? It looks like JSON
</blockquote></details>

Right!
I changed it for the JSON maps.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 5 files at r2, 1 of 2 files at r3, 1 of 4 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: all files reviewed, 9 unresolved discussions (waiting on @OmriEshhar1 and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXjt9c83iWjyCHLe_T8:-NXjt9c83iWjyCHLe_T9:b8t3ob7) (no related file):*
The purpose of the dump is for creating the default config file?
You started with quite a hard part of the task (simulating reflection on the config components). 
I think that for the first step, you can implement the dump function hard-coded for a single component.
However, if you already work on this, maybe TAL at https://docs.rs/schemars/latest/schemars/

Also, please provide a function that uses this functionality so it will be clearer how it is being used.

___
___
*[`crates/papyrus_config/src/lib.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXniR_S4Ux7QYCEV1SQ:-NXniR_S4Ux7QYCEV1SR:bc64xq) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L17)):*
> ```XML
> }
> 
> pub trait SubConfig: Serialize {
> ```

Please document the purpose of this trait.
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXnfZ1p1R8TJTQRGN-s:-NXnfZ1p1R8TJTQRGN-t:box0fmj) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L23)):*
> ```XML
>         let config_name = Self::config_name();
>         format!("{config_name}.{param_name}")
>     }
> ```

Extract to a function outside the trait:
```
fn param_path<T: SubConfig>(p: T) -> ParamPath {
    let config_name = T::config_name();
    ...
}
```




_Code quote:_
```XML
    fn param_path(param_name: &String) -> ParamPath {
        let config_name = Self::config_name();
        format!("{config_name}.{param_name}")
    }
```
___
*[`crates/papyrus_config/src/lib.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXnhZM50KfUqRTEcPM_:-NXnh66LEkUNSp-HPJi9:b2oepqk) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L31)):*
> ```XML
>     /// The path of each param is rooted at this config name.
>     /// Used by `dump` when a field itself implements `SubConfig`.
>     fn dump_sub_config(&self) -> HashMap<ParamPath, SerializedParam> {
> ```

Does the implementor of the trait need to know that he can use this function?
Why not implement the trait for each sub-component where the config_name function returns "{config_name}.{sub_config_name}"
___
*[`crates/papyrus_gateway/default_config.json` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo9FzI8vcr921ajwCw:-NXo9FzI8vcr921ajwCx:bxxgck1) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/default_config.json#L1)):*
> ```JSON
> {
> ```

Why do we need this file?
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo8gYSExin3vOw2E0s:-NXo8gYSExin3vOw2E0t:b-wxbn08) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
> ```XML
> }
> 
> #[test]
> ```

Use https://docs.rs/insta/latest/insta/ 
(Already using it in main branch)
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 128 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo8yNA6Pe7UlsOk07k:-NXo8yNA6Pe7UlsOk07l:b9f3z7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/src/gateway_test.rs#L128)):*
> ```XML
>     }
> 
>     assert_eq!(deserialized_map, default_gateway.dump_sub_config());
> ```

Shouldn't you call dump instead of dump_sub_config?



_Code quote:_
```XML
dump_sub_config
```
___
*[`config/default_config.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXjtUajCZwCm9MnZH2s:-NXjtUak0vPURJJeaCIr:b-tm3k52) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/config/default_config.json#L1)):*
> ```JSON
> {
> ```

Is this file manually written, or did you use the trait to create it automatically?

**Comment by yair-starkware** [comment]
*[`crates/papyrus_gateway/Cargo.toml` line 18 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXoAXZe79DPLBOHdLd-:-NXoAXZf9Igq1_QeZBv1:bhjqkge) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/Cargo.toml#L18)):*
> ```TOML
> serde = { workspace = true, features = ["derive"] }
> serde_json.workspace = true
> serde_yaml.workspace = true
> ```

Why is it needed?



_Code quote:_
```TOML
serde_yaml.workspace = true
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: 1 of 7 files reviewed, 10 unresolved discussions (waiting on @matan-starkware, @OmriEshhar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXjt9c83iWjyCHLe_T8:-NXsomRe0-pvesr1Iyc6:b-q6xv0b) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The purpose of the dump is for creating the default config file?
You started with quite a hard part of the task (simulating reflection on the config components). 
I think that for the first step, you can implement the dump function hard-coded for a single component.
However, if you already work on this, maybe TAL at https://docs.rs/schemars/latest/schemars/

Also, please provide a function that uses this functionality so it will be clearer how it is being used.
</blockquote></details>

1. Creating the default config file with descriptions will not be convenient with schemars.
2. I am adding the function 'dump_sub_config_to_file'.

___
___
*[`crates/papyrus_config/src/lib.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXjhhEP4RwA6RKK88QC:-NXojSmB7MeJOW7Z7wdi:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc8fe4de38752751ad87f59b6507f32bb97bb096/crates/papyrus_config/src/lib.rs#L29)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think an example might be good. You can actually put it as part of a comment on dump. Rust allows writing code in comments and these are great since they provide examples, and they actually run so they don't go stale.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXniR_S4Ux7QYCEV1SQ:-NXp0_uF-Fna13x45WfY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L17)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please document the purpose of this trait.
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXnfZ1p1R8TJTQRGN-s:-NXojOOBDbCeZP5DEQdV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L23)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Extract to a function outside the trait:
```
fn param_path<T: SubConfig>(p: T) -> ParamPath {
    let config_name = T::config_name();
    ...
}
```

</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXnhZM50KfUqRTEcPM_:-NXokQIU4pZNTyUH42oE:bjywxzu) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/crates/papyrus_config/src/lib.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Does the implementor of the trait need to know that he can use this function?
Why not implement the trait for each sub-component where the config_name function returns "{config_name}.{sub_config_name}"
</blockquote></details>

It supports a recursive structure of sub-configs.
The implementation of `dump` uses `dump_sub_config` for the inner sub-configs.
On the root config, we will call `dump`, whatever the root may be.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 108 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo8gYSExin3vOw2E0s:-NXtJVI_DyEUtwIwtau6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/src/gateway_test.rs#L108)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use https://docs.rs/insta/latest/insta/ 
(Already using it in main branch)
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 128 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo8yNA6Pe7UlsOk07k:-NXoWAkvEJof4dlGtf6K:b-uq3f2p) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/src/gateway_test.rs#L128)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't you call dump instead of dump_sub_config?
</blockquote></details>

Down the road, the serialized file will contain all the sub-configs, and the test will take `Config::default().dump()`.
These records will contain the prefix "GatewayConfig."
___
*[`crates/papyrus_gateway/Cargo.toml` line 18 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXoAXZe79DPLBOHdLd-:-NXomX-N01nENgHnY9Cv:bss4a2b) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/Cargo.toml#L18)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Removed.
___
*[`crates/papyrus_gateway/default_config.json` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXo9FzI8vcr921ajwCw:-NXoSipYCC6scvbTUJ4N:b-ftxts8) ([raw file](https://github.com/starkware-libs/papyrus/blob/daff48c94a8bb7ca5753ea1367938e16dc60370f/crates/papyrus_gateway/default_config.json#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this file?
</blockquote></details>

Sorry. Removed.
___
*[`config/default_config.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/723#-NXjtUajCZwCm9MnZH2s:-NXoyPgC2_xlo-QWgtmu:b-efhak0) ([raw file](https://github.com/starkware-libs/papyrus/blob/256f07c8e4187e14d66391191c7b0225e80d2545/config/default_config.json#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this file manually written, or did you use the trait to create it automatically?
</blockquote></details>

Automatically.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723#-:-NXtRHgU7dpoXVQ_Bb3R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @OmriEshhar1)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r11, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/723)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
