### PR TITLE
feat(network): add conversion from protobuf transaction outputs to sn api

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7k7i63lPmB7vJREa3:-Nz7jrh7CNkUaizUtkSM:b4ooout) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/receipt.rs#L107)):*
> ```XML
> }
> 
> // The price_unit will be updated in the caller function
> ```

Change this to:
// The returned price_unit isn't correct. It can be fixed by calling set_price_unit_based_on_transaction
In general, comments should be in the scope of the function and not the entire crate
Same in other places
___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 452 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7jWmbBs19WJSpG9bj:-Nz7jWmbBs19WJSpG9bk:bty3asz) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/receipt.rs#L452)):*
> ```XML
> }
> 
> fn create_receipt_common_from_txn_output_fields(
> ```

Add proto to this name somewhere
create_proto_receipt_common_from_txn_output_fields
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1122 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7keP-CXp0xfm8rMI1:-Nz7keP-CXp0xfm8rMI2:bu78j2q) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/transaction.rs#L1122)):*
> ```XML
>         _ => return,
>     };
>     if let Some(ref mut receipt_type) = receipt.r#type {
> ```

use let-else to remove one indentation to all the code below
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1125 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7knVX-vpleny3ogdN:-Nz7knVX-vpleny3ogdO:b8kvx8o) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/transaction.rs#L1125)):*
> ```XML
>         match receipt_type {
>             protobuf::receipt::Type::Invoke(invoke) => {
>                 if let Some(ref mut common) = invoke.common {
> ```

return here the reference to common and in all other transactions and then, in a single place, set the price unit

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7k7i63lPmB7vJREa3:-Nz7nrBY8kQzg1IVs01P:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/receipt.rs#L107)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to:
// The returned price_unit isn't correct. It can be fixed by calling set_price_unit_based_on_transaction
In general, comments should be in the scope of the function and not the entire crate
Same in other places
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 452 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7jWmbBs19WJSpG9bj:-Nz7nt9-89M1MI9bAlpq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/receipt.rs#L452)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add proto to this name somewhere
create_proto_receipt_common_from_txn_output_fields
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1122 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7keP-CXp0xfm8rMI1:-Nz7pqEk2toDFZtBWMxF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/transaction.rs#L1122)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use let-else to remove one indentation to all the code below
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1125 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7knVX-vpleny3ogdN:-Nz7pqlw3nIZtWvVy-jy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/38fcac05e435bb73acd9b5ad4610d927309876d4/crates/papyrus_protobuf/src/converters/transaction.rs#L1125)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

return here the reference to common and in all other transactions and then, in a single place, set the price unit
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7uOS66O4PooI9Pi7T:-Nz7uOS66O4PooI9Pi7U:bl3zpjd) ([raw file](https://github.com/starkware-libs/papyrus/blob/45b99ec95717f9a90f71b6b627e25cd38bbfd78f/crates/papyrus_protobuf/src/converters/receipt.rs#L115)):*
> ```XML
>             value.execution_status,
>         );
>         // The returned price_unit isn't correct.
> ```

Move this to the start of the function. And change it to docstring (3 slashes)
Same everywhere

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/receipt.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-Nz7uOS66O4PooI9Pi7T:-Nz7xDsI0U-Ea_Bdo295:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/45b99ec95717f9a90f71b6b627e25cd38bbfd78f/crates/papyrus_protobuf/src/converters/receipt.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to the start of the function. And change it to docstring (3 slashes)
Same everywhere
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2055#-:-Nz7y7spE9maWyBnEY0e:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
