### PR TITLE
refactor(consensus): change StartRound to GetProposal and pass leader_fn to sm from shc

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P-RHe6TDphMXBPx3E):*
We should also mention StartRound -> GetProposal



_Code quote:_
```
- 3bff719: refactor(consensus): shc sends leader_fn to sm
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P043D8ht1y4ylHNvZ:-O2P043E6dDxGZnC9rWr:btnhd44) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L195)):*
> ```XML
>                 StateMachineEvent::Proposal(_, _) => {
>                     // Ignore proposals sent by the StateMachine as SingleHeightConsensus already
>                     // sent this out when responding to a GetProposal.
> ```

We currently have only 1 flow for sending a proposal; building a new block. In the future we will also have a method whereby the SM sends us `Proposal` without `GetProposal`. In that case we will need to stream based on the `Proposal`. Nothing to do now.



_Suggestion:_
```XML
                    // Ignore proposals sent by the StateMachine as SingleHeightConsensus already
                    // sent this out when responding to a GetProposal.
                    // TODO(matan): How do we handle this when validValue is set?
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P0slh38u7VC1odclp:-O2P0slh38u7VC1odclq:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L214)):*
> ```XML
> 
>     #[instrument(skip(self, context), level = "debug")]
>     async fn handle_state_machine_start_round<ContextT: ConsensusContext<Block = BlockT>>(
> ```





_Suggestion:_
```XML
handle_state_machine_get_proposal
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P0vWjD86aeziWaICG:-O2P0vWjD86aeziWaICH:bun1ob0) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L223)):*
> ```XML
>         assert!(block_hash.is_none(), "Reproposing is not yet supported");
>         let proposer_id = context.proposer(&self.validators, self.height);
>         if proposer_id != self.id {
> ```

This check isn't relevant anymore.



_Code quote:_
```XML
        if proposer_id != self.id {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P1IH66Cno_FlS2AwA:-O2P1IH66Cno_FlS2AwB:b-yfkrwx) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/state_machine.rs#L27)):*
> ```XML
>     ///    block hash.
>     /// 2. If no block hash was supplied by the state machine, the caller must find/build a block
>     ///    to respond with.
> ```

Sent by the state machine when a block is required to propose (BlockHash is always None).  While waiting for the response of GetProposal, the state machine will buffer all other events.

The caller must respond with a valid block hash for this height to the state machine, and the same round sent out.



_Code quote:_
```XML
    /// While waiting for the response of GetProposal, the state machine will buffer all other
    /// events.
    ///
    /// How should the caller handle this event?
    /// 1. If a block hash was supplied by the state machine, the caller responds with the supplied
    ///    block hash.
    /// 2. If no block hash was supplied by the state machine, the caller must find/build a block
    ///    to respond with.
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P-RHe6TDphMXBPx3E):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We should also mention StartRound -> GetProposal
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P0slh38u7VC1odclp:-O2P3CWl6cAtpik6wWuZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L214)):*
> ```XML
> 
>     #[instrument(skip(self, context), level = "debug")]
>     async fn handle_state_machine_start_round<ContextT: ConsensusContext<Block = BlockT>>(
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P0vWjD86aeziWaICG:-O2P3Nv16NowkByoKPXs:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L223)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This check isn't relevant anymore.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2P1IH66Cno_FlS2AwA:-O2P4ffPDBwPBVbo158L:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3bff719a210785d404ce9a20ae4b5c93d05ba055/crates/sequencing/papyrus_consensus/src/state_machine.rs#L27)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Sent by the state machine when a block is required to propose (BlockHash is always None).  While waiting for the response of GetProposal, the state machine will buffer all other events.

The caller must respond with a valid block hash for this height to the state machine, and the same round sent out.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QOdQ46Up-U288J9Ad):*




_Suggestion:_
```
- 8eb6d8b: refactor(consensus): change StartRound to GetProposal and pass leader_fn to sm from shc
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QP23UDGxUAvKRQSiT:-O2QP23UDGxUAvKRQSiU:bie0qrw) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L222)):*
> ```XML
>     ) -> VecDeque<StateMachineEvent> {
>         // TODO(matan): Support re-proposing validValue.
>         assert!(block_hash.is_none(), "Reproposing is not yet supported");
> ```

This is now irrelevant. If you want to look up reproposing see line 16 in the Tendermint paper's algorithm (p6). Given this change we will handle reproposing by the state machine sending a `Proposal` event, but not yet.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QOvwFAItBaeoYTPJB:-O2QOvwFAItBaeoYTPJC:bgwvfvd) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L244)):*
> ```XML
>         assert!(old.is_none(), "There should be no entry for this round.");
> 
>         // TODO(matan): Send to the state machine and handle voting.
> ```

Can you remove this please?



_Code quote:_
```XML
        // TODO(matan): Send to the state machine and handle voting.
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QQcmbDr2mD-9A69kk:-O2QQcmbDr2mD-9A69kl:b-3qq0kr) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L14)):*
> ```XML
> #[test_case(false; "validator")]
> fn events_arrive_in_ideal_order(is_proposer: bool) {
>     let mut state_machine = StateMachine::new(0_u32.into(), 4);
> ```

Let's create a const at the top the test file and use that everywhere.



_Code quote:_
```XML
(0_u32.into()
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QOdQ46Up-U288J9Ad):*
Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QP23UDGxUAvKRQSiT:-O2SwK4B6GOFnqA--_0E:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L222)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is now irrelevant. If you want to look up reproposing see line 16 in the Tendermint paper's algorithm (p6). Given this change we will handle reproposing by the state machine sending a `Proposal` event, but not yet.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QOvwFAItBaeoYTPJB:-O2Snttn3pB5JI5QbCND:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L244)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you remove this please?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QQcmbDr2mD-9A69kk:-O2SwL6L9OURxcBZBB_P:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L14)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's create a const at the top the test file and use that everywhere.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QP23UDGxUAvKRQSiT:-O2TOGC_-WmQZkGlBwEX:bgfne6p) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L222)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In retrospect I actually do want the assertion, but no TODO:
assert!(block_hash.is_none(), "BlockHash must be None since the state machine is requesting a BlockHash");
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QQcmbDr2mD-9A69kk:-O2TO6ub1WR9vHgsUxMn:buifmqh) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L14)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are still a lot of places you don't use this (leader_fn)

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2240)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2240#-O2QQcmbDr2mD-9A69kk:-O2TQv3w24Ple4LlYbF8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8eb6d8bc26a516087036bdae4ea9ab81f7fd0fff/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L14)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

There are still a lot of places you don't use this (leader_fn)
</blockquote></details>

Done.

**Pull request closed without merging**
