### PR TITLE
feat(execution): add pending members to ExecutionStateReader

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/objects.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-NiorHdN1H3Li3nPxFDN:-NiorHdN1H3Li3nPxFDO:b-tmfz92) ([raw file](https://github.com/starkware-libs/papyrus/blob/edfd1e869a4a7cb4c4a00f9e082c4baf97a98590/crates/papyrus_execution/src/objects.rs#L329)):*
> ```XML
> /// A state diff for the pending block.
> #[derive(Debug, Default, Deserialize, Serialize, Clone, Eq, PartialEq)]
> pub struct PendingStateDiff {
> ```

I think it should be `pub(crate)`



_Code quote:_
```XML
pub 
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/objects.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-NiorHdN1H3Li3nPxFDN:-NiorymF3zeiOtOyNmJl:bnr7z46) ([raw file](https://github.com/starkware-libs/papyrus/blob/edfd1e869a4a7cb4c4a00f9e082c4baf97a98590/crates/papyrus_execution/src/objects.rs#L329)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it should be `pub(crate)`
</blockquote></details>

rpc will depend on it

**Comment by yair-starkware** [comment]
*[`crates/papyrus_execution/src/objects.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-NiorHdN1H3Li3nPxFDN:-NiosLxVCOS21xHdxBag:baaosnx) ([raw file](https://github.com/starkware-libs/papyrus/blob/edfd1e869a4a7cb4c4a00f9e082c4baf97a98590/crates/papyrus_execution/src/objects.rs#L329)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rpc will depend on it
</blockquote></details>

So why did we move the StateDiff to common?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/objects.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-NiorHdN1H3Li3nPxFDN:-NiosS8XDNBzm5JuVINn:bsdsj54) ([raw file](https://github.com/starkware-libs/papyrus/blob/edfd1e869a4a7cb4c4a00f9e082c4baf97a98590/crates/papyrus_execution/src/objects.rs#L329)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

So why did we move the StateDiff to common?
</blockquote></details>

because it was in the client

**Comment by ShahakShama** [comment]
*[`crates/papyrus_execution/src/objects.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-NiorHdN1H3Li3nPxFDN:-NiosVA280lo1ZyGwUfV:b8bcen8) ([raw file](https://github.com/starkware-libs/papyrus/blob/edfd1e869a4a7cb4c4a00f9e082c4baf97a98590/crates/papyrus_execution/src/objects.rs#L329)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

because it was in the client
</blockquote></details>

and rpc, as the crate that knows both the client and the execution, will convert from the client StateDiff to the execution StateDiff

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386#-:-NiotHoD1sRA0vXdX8jA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
