### PR TITLE
ci: test p2p sync

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2140)

### CODE REVIEW

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2140)* status: 6 of 9 files reviewed, 15 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`.github/workflows/ci.yml` line 70 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CySd1-96LNeX49D4u:-O0CySd1-96LNeX49D4v:b-musscl) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/.github/workflows/ci.yml#L70)):*
> ```YAML
>         uses: actions/setup-python@v2
>         with:
>           python-version: "3.x"
> ```

What is this x? I think you should put a python version here
___
*[`scripts/ci_papyrus_mainnet_config_p2p_sync_receiver.json` line 14 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwTW88HxybPyXPuET:-O0CwTW88HxybPyXPuEU:bpikozw) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/ci_papyrus_mainnet_config_p2p_sync_receiver.json#L14)):*
> ```JSON
>     "network.bootstrap_peer_multiaddr.#is_none": false,
>     "network.bootstrap_peer_multiaddr": "/ip4/127.0.0.1/tcp/10000/p2p/12D3KooWDFYi71juk6dYWo3UDvqs5gAzGDc124LSvcR5d187Tdvi"
> }
> ```

Add newline at end of file. Same below
___
*[`scripts/p2p_syncing_test.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cvwg9ECuFGOD6O8Uk:-O0Cvwg9ECuFGOD6O8Ul:bf39t4w) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L1)):*
> ```Python
> import subprocess
> ```

Create a dir for p2p_syncing_test inside scripts, and put the 3 files inside it. Rename them to main.py, server_node_config.json, client_node_config.json
___
*[`scripts/p2p_syncing_test.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxjUy-c-tE2ZEcwlh:-O0CxjUy-c-tE2ZEcwli:bx02r0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L1)):*
> ```Python
> import subprocess
> ```

Run black on this file. Install it from https://pypi.org/project/black/. The command should be `black -l 100 -t py3x file_name` where x is the python version you're using (see comment above)
___
*[`scripts/p2p_syncing_test.py` line 9 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwYTl9tA1lxETRTeZ:-O0CwYTl9tA1lxETRTe_:b-kyfwx5) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L9)):*
> ```Python
> import sys
> 
> def run_cargo_command(command):
> ```

Remove this function, and use subprocess.check_call instead
The output of the error from check_call is good enough. No need for the custom print you've added
___
*[`scripts/p2p_syncing_test.py` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cx3KNCq7go5gOBNn4:-O0Cx3KNCq7go5gOBNn5:bm2bqt6) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L17)):*
> ```Python
>         sys.exit(1)
> 
> def run_curl_command():
> ```

Rename to run_curl_on_client_node_monitoring
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwjJq-MJLilSaOHZd:-O0CwjJq-MJLilSaOHZe:b-t2za09) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
> ```Python
> 
> def run_curl_command():
>     result = subprocess.run("curl -X GET http://localhost:8082/monitoring/metrics", shell=True, capture_output=True, text=True)
> ```

Use subprocess.check_output instead.
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cwqn_Du-UrWBU7Szb:-O0Cwqn_Du-UrWBU7Szc:b-auwt7g) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
> ```Python
> 
> def run_curl_command():
>     result = subprocess.run("curl -X GET http://localhost:8082/monitoring/metrics", shell=True, capture_output=True, text=True)
> ```

Don't use shell=True. Instead, pass the command as a list of commands
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwvgJ00aHuOQRPscj:-O0CwvgJ00aHuOQRPsck:bcfjdyk) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
> ```Python
> 
> def run_curl_command():
>     result = subprocess.run("curl -X GET http://localhost:8082/monitoring/metrics", shell=True, capture_output=True, text=True)
> ```

extract http://localhost:8082/monitoring/metrics to a constant
___
*[`scripts/p2p_syncing_test.py` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxCZt0-hqTHbqYzfR:-O0CxCZt0-hqTHbqYzfS:b-nfcojr) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L21)):*
> ```Python
>     return result.stdout
> 
> def parse_output(curl_output):
> ```

rename to extract_state_marker_from_curl/monitoring_output
___
*[`scripts/p2p_syncing_test.py` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwIAx6Vh8UpF_6nQo:-O0CwIAx6Vh8UpF_6nQp:b-rh6csf) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L43)):*
> ```Python
>         print("Usage: python3 p2p_syncing_test.py <BASE_LAYER_NODE_URL>")
>         sys.exit(1)
>     
> ```

Change this to 4 spaces. Same throughout the file
___
*[`scripts/p2p_syncing_test.py` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxgVe4vMAgXk5QaDO:-O0CxgVe4vMAgXk5QaDP:b-gsuese) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L46)):*
> ```Python
>     base_layer_node_url = sys.argv[1]
> 
>     cargo_command_1 = f"target/release/papyrus_node --base_layer.node_url {base_layer_node_url} --config_file scripts/ci_papyrus_mainnet_config_p2p_sync_receiver.json"
> ```

This is not a cargo command
___
*[`scripts/p2p_syncing_test.py` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cyd2K0NRvEuWq7ae7:-O0Cyd2K0NRvEuWq7ae8:b-91uir6) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L46)):*
> ```Python
>     base_layer_node_url = sys.argv[1]
> 
>     cargo_command_1 = f"target/release/papyrus_node --base_layer.node_url {base_layer_node_url} --config_file scripts/ci_papyrus_mainnet_config_p2p_sync_receiver.json"
> ```

Same as before, make this a list of strings and remove shell=True
___
*[`scripts/p2p_syncing_test.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cxb8l1NrQji6uvylg:-O0Cxb8l1NrQji6uvylh:b3cd6fn) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L53)):*
> ```Python
>     process2 = run_cargo_command(cargo_command_2)
>     
>     time.sleep(30)
> ```

Extract 30 to a constant, and try to decrease it
___
*[`scripts/p2p_syncing_test.py` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CzAOf98kkwsSq6_82:-O0CzAOf98kkwsSq6_83:b-9x0h6s) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L66)):*
> ```Python
>         sys.exit(1)
> 
>     terminate_process_group(os.getpgid(process1.pid))
> ```

This will happen only if the test passes. You want to kill the process in any case. Create a context manager that kills the processes upon exit https://realpython.com/python-with-statement/#the-with-statement-approach
And remove all those exits and raise exceptions instead

**Comment by dan-starkware** [comment]
Can we break this into two separate PRs?

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2140)* status: 6 of 9 files reviewed, 16 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`.github/workflows/ci.yml` line 70 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CySd1-96LNeX49D4u:-O0D3MKO7yaV1bgIEx2H:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/.github/workflows/ci.yml#L70)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What is this x? I think you should put a python version here
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cvwg9ECuFGOD6O8Uk:-O0D4rtl4KR3E9e_Cfnk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Create a dir for p2p_syncing_test inside scripts, and put the 3 files inside it. Rename them to main.py, server_node_config.json, client_node_config.json
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxjUy-c-tE2ZEcwlh:-O0D4sX27mfLlwlad7Gw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Run black on this file. Install it from https://pypi.org/project/black/. The command should be `black -l 100 -t py3x file_name` where x is the python version you're using (see comment above)
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 9 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwYTl9tA1lxETRTeZ:-O0DKo8JEQ3woJpPzJEB:b-l7idi) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L9)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this function, and use subprocess.check_call instead
The output of the error from check_call is good enough. No need for the custom print you've added
</blockquote></details>

subprocess.check_call is blocking
___
*[`scripts/p2p_syncing_test.py` line 17 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cx3KNCq7go5gOBNn4:-O0D4u2T9T4uJ6jmULqK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to run_curl_on_client_node_monitoring
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwjJq-MJLilSaOHZd:-O0DL6lg9K0EuMV6vsvn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use subprocess.check_output instead.
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cwqn_Du-UrWBU7Szb:-O0DL7P5BvAhoDE1vF8t:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Don't use shell=True. Instead, pass the command as a list of commands
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwvgJ00aHuOQRPscj:-O0DLVefDOaEYVMIRcPx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

extract http://localhost:8082/monitoring/metrics to a constant
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxCZt0-hqTHbqYzfR:-O0D66wDDw8HoO0GUpkF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L21)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to extract_state_marker_from_curl/monitoring_output
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 43 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CwIAx6Vh8UpF_6nQo:-O0DQL_M71_p--EUIxA8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to 4 spaces. Same throughout the file
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CxgVe4vMAgXk5QaDO:-O0DLnKiCqsqlF4eMbkD:b-n9tkhd) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not a cargo command
</blockquote></details>

changed
___
*[`scripts/p2p_syncing_test.py` line 46 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cyd2K0NRvEuWq7ae7:-O0DLvHg9kv9EJE8Jh8R:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before, make this a list of strings and remove shell=True
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0Cxb8l1NrQji6uvylg:-O0DM4My4qq9D9-u1emy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract 30 to a constant, and try to decrease it
</blockquote></details>

Done.
___
*[`scripts/p2p_syncing_test.py` line 66 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0CzAOf98kkwsSq6_82:-O0DOXh9E2qJaxLNbTTj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/fb234994e5ed2c24c0da8a7c6b9f1dc336b06f12/scripts/p2p_syncing_test.py#L66)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This will happen only if the test passes. You want to kill the process in any case. Create a context manager that kills the processes upon exit https://realpython.com/python-with-statement/#the-with-statement-approach
And remove all those exits and raise exceptions instead
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2140)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`scripts/p2p_syncing_test/main.py` line 70 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0DW_fO0uAFDD7XzBj5:-O0DW_fO0uAFDD7XzBj6:bfrss6) ([raw file](https://github.com/starkware-libs/papyrus/blob/511d7fea7911cbd19d4e153cad071ea016984a99/scripts/p2p_syncing_test/main.py#L70)):*
> ```Python
>             if papyrus_state_marker is None:
>                 print("Failed to extract state marker value from monitoring output.")
>                 sys.exit(1)
> ```

exit will make you not call the __exit__ of the context manager
Instead, here write `assert papyrus_state_marker is not None, "Failed to ..."`
In the one below write `assert papyrus_state_marker < 10, f"papyrus_state_marker value is ..."`
And erase the expect below, the error from subprocess is clear enough

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2140)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`scripts/p2p_syncing_test/main.py` line 70 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2140#-O0DW_fO0uAFDD7XzBj5:-O0DZ0sQCf0T-UxpANTR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/511d7fea7911cbd19d4e153cad071ea016984a99/scripts/p2p_syncing_test/main.py#L70)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

exit will make you not call the __exit__ of the context manager
Instead, here write `assert papyrus_state_marker is not None, "Failed to ..."`
In the one below write `assert papyrus_state_marker < 10, f"papyrus_state_marker value is ..."`
And erase the expect below, the error from subprocess is clear enough
</blockquote></details>

Done.

**Pull request closed without merging**
