### PR TITLE
fix: fix the deprecated L1_Handler transaction hash computation

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)* status: all files reviewed, 6 unresolved discussions (waiting on @Yael-Starkware and @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV9wjV7MtVhc4PjuhH:-NdV9wjV7MtVhc4PjuhI:b-ezo4br) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L279)):*
> ```XML
> #[derive(PartialEq)]
> enum L1HandlerVersions {
>     PreL1Handler,
> ```

Consider AsInvoke instead of PreL1Handler
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdVAVaT3GMw9dS6Qmoh:-NdVAVaT3GMw9dS6Qmoi:b-jsqiep) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L280)):*
> ```XML
> enum L1HandlerVersions {
>     PreL1Handler,
>     Deprecated,
> ```

Deprecated is now not a good name. find another name for it
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV599FDion_0JHyAih:-NdVAEPA7FbBGKOuKk8E:b-tmusw2) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L284)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This function is hard to track and will be harder with more hash versions.

Consider one of the following:
1. Splitting the PreL1Handler to a function that doesn't call 'get_common_l1_handler_transaction_hash'.
2. Determine the chain_if conditions by `<` instead of `=`.
</blockquote></details>

3. Whenever there's a branch, stop the chain and store it in a mid variable and do a match to determine what's the next value you should chain
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV6sK9Eu9CCo_qz7Dj:-NdVAi6l45-H69jeVk-a:bhuuf81) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash_test.rs#L35)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Rename it?
</blockquote></details>

Possible name, TransactionTestData

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV6NYP8OYTcntmOS7F:-NdZEDGj4pOFgb_9guPI:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L273)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Consider
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV747V-KMMfCN7q5Ci:-NdZECCI0vO_0hTwPrC-:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L278)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Please move the definition up. (maybe right before the first use?)
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV9wjV7MtVhc4PjuhH:-NdZDLzL-9Yf7LzfWDWV:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L279)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider AsInvoke instead of PreL1Handler
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdVAVaT3GMw9dS6Qmoh:-NdZDMhC7bJ6F4KiEjDw:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L280)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Deprecated is now not a good name. find another name for it
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV599FDion_0JHyAih:-NdZEF8--WfeXrGoMFGq:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash.rs#L284)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

3. Whenever there's a branch, stop the chain and store it in a mid variable and do a match to determine what's the next value you should chain
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdV6sK9Eu9CCo_qz7Dj:-NdZBfX-51HZwrXwJsyk:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7e15e847adc7dead526d9ee843e5e21230636aa/crates/papyrus_common/src/transaction_hash_test.rs#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Possible name, TransactionTestData
</blockquote></details>

done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-:-NdZWHho9f14fqq64htz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

**Review by yoavGrs — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdZWT0j0liLUMP88Pbb:-NdZWT0j0liLUMP88Pbc:boqxa5j) ([raw file](https://github.com/starkware-libs/papyrus/blob/70bbbf19055c4bd85baf7563f71fc6226914da9c/crates/papyrus_common/src/transaction_hash.rs#L285)):*
> ```XML
> ) -> Result<StarkHash, StarknetApiError> {
>     Ok(PedersenHashChain::new()
>         .chain_if(&L1_HANDLER, version > L1HandlerVersions::AsInvoke)
> ```

WDYT about a `chain_if_else` function, for switching between two options by a condition?

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-NdZWT0j0liLUMP88Pbb:-NdZsFhd-6qLUwft5O1N:b-7rl0kd) ([raw file](https://github.com/starkware-libs/papyrus/blob/70bbbf19055c4bd85baf7563f71fc6226914da9c/crates/papyrus_common/src/transaction_hash.rs#L285)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

WDYT about a `chain_if_else` function, for switching between two options by a condition?
</blockquote></details>

done

**Review by yoavGrs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1132#-:-NdZscsYEIPTY_51GRKP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
