### PR TITLE
feat(network): add get blocks inbound response logic

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1130** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1130" target="_blank">Graphite</a> 
    * **PR #1123** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1123" target="_blank">Graphite</a> 
      * **PR #1131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1131" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1131?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrEJqBUYStRaZRv_X:-NdUrEJqBUYStRaZRv_Y:b-vbymnb) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L22)):*
> ```XML
> /// Receives a request to get a range of blocks and sends a stream of data on the blocks.
> pub struct InboundProtocol {
>     request_relay_sender: UnboundedSender<GetBlocks>,
> ```

Change type to oneshot channel
https://docs.rs/futures/latest/futures/channel/oneshot/struct.Receiver.html
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUqmjR5fhDasMytwkv:-NdUqmjR5fhDasMytwkw:b-bo712p) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
> ```XML
> pub struct InboundProtocol {
>     request_relay_sender: UnboundedSender<GetBlocks>,
>     response_relay_receiver: UnboundedReceiver<Option<GetBlocksResponse>>,
> ```

response_relay_receiver -> responses_relay_receiver
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUs3LW1OBfQrhO7bve:-NdUs3LW1OBfQrhO7bvf:b-3945ml) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
> ```XML
> pub struct InboundProtocol {
>     request_relay_sender: UnboundedSender<GetBlocks>,
>     response_relay_receiver: UnboundedReceiver<Option<GetBlocksResponse>>,
> ```

explain the meaning of None in comment
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrPIj41jaMTMO963c:-NdUrPIj41jaMTMO963d:b-7a0o1i) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L39)):*
> ```XML
> 
> #[derive(thiserror::Error, Debug)]
> pub enum InboundProtocolError {
> ```

Consider uniting with OutboundProtocolError
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtIlK7eUrbjtJhANA:-NdUtIlK7eUrbjtJhANB:b-qjvecc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L64)):*
> ```XML
> 
>     fn upgrade_inbound(mut self, mut io: Stream, _: Self::Info) -> Self::Future {
>         Box::pin(
> ```

Why did you pin it? explain in a comment
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUuFsn1K4cAnZ-xETT:-NdUuFsn1K4cAnZ-xETU:btwun0v) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L69)):*
> ```XML
>                     self.request_relay_sender.unbounded_send(get_blocks_msg)?;
>                 }
>                 let mut expect_end_of_stream = false;
> ```

This can be a lot more simpler if you return when you receive Some(None) and you return error when you receive None. In that case, you don't need this variable
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtkkP75gayPzpVowT:-NdUtkkP75gayPzpVowU:b-bxdjy2) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L72)):*
> ```XML
>                 loop {
>                     match self.response_relay_receiver.next().await {
>                         Some(response) => match response {
> ```

If response_relay_receiver.next() didn't return None, assert that expect_end_of_stream is false (return error if it isn't)
(Assuming you didn't erase expect_end_of_stream as suggested above)
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUsSTv1ZHS5RjWtXxs:-NdUsSTv1ZHS5RjWtXxt:b-8qo6dz) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L73)):*
> ```XML
>                     match self.response_relay_receiver.next().await {
>                         Some(response) => match response {
>                             Some(res) => write_message(res, &mut io).await?,
> ```

flatten into one match with the following arms instead
Some(Some(response))
Some(None)
None
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUvTpV6TUk48Oudexs:-NdUvTpV6TUk48Oudext:b-92gu9d) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L167)):*
> ```XML
> }
> 
> use crate::messages::block::BlockHeader;
> ```

Move this to protocol_test (or test_utils file if you use it somewhere else
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUzWsi6zlFMMAPTD6i:-NdUzWsi6zlFMMAPTD6j:b83cife) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L60)):*
> ```XML
> 
>     let (outbound_protocol, mut responses_receiver) = OutboundProtocol::new(Default::default());
>     let (inbound_protocol, (mut request_relay_receiver, response_relay_sender)) =
> ```

Consider prefixing each channel with outbound/inbound
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUvdoWB8WuU5mtgWzq:-NdUvdoWB8WuU5mtgWzr:b7djx23) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L73)):*
> ```XML
>                 .unwrap();
>         },
>         // plays the role of the network and DB handlers
> ```

We're still not sure about the names of these yet. Write something more generic like 
// Sends responses to the inbound protocol and receives responses from the outbound protocol
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUw_oZ-fiD3Ouz5pmL:-NdUw_oZ-fiD3Ouz5pmM:b-qedi2k) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L75)):*
> ```XML
>         // plays the role of the network and DB handlers
>         async move {
>             // ignore block query for now, just send hardcoded responses
> ```

Why ignore? Assert that the received request is the request that the outbound sent
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUwUC25A-5Rzvqnsrl:-NdUwUC25A-5Rzvqnsrm:b-khsujs) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L76)):*
> ```XML
>         async move {
>             // ignore block query for now, just send hardcoded responses
>             let _blocks_query = request_relay_receiver.next().await.unwrap();
> ```

Rename to _request

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)* status: all files reviewed, 14 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/get_blocks/handler.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUzkis42XyytiawQEK:-NdUzkis42XyytiawQEL:b-ot1skv) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/handler.rs#L120)):*
> ```XML
> 
>     fn listen_protocol(&self) -> SubstreamProtocol<Self::InboundProtocol, Self::InboundOpenInfo> {
>         let (inbound_protocol, _) = InboundProtocol::new();
> ```

Add TODO to do something with _

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)* status: 0 of 3 files reviewed, 13 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/get_blocks/handler.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUzkis42XyytiawQEK:-NdV1XC11KvAwyHMiAU1:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/handler.rs#L120)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to do something with _
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrEJqBUYStRaZRv_X:-NdZ76WSEsmSXCnn31ss:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change type to oneshot channel
https://docs.rs/futures/latest/futures/channel/oneshot/struct.Receiver.html
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUqmjR5fhDasMytwkv:-NdV2Uj95_dk5eez_9i_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

response_relay_receiver -> responses_relay_receiver
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUs3LW1OBfQrhO7bve:-NdV7rl59h_sjO3gTnuu:b1tpnxs) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

explain the meaning of None in comment
</blockquote></details>

what none?
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrPIj41jaMTMO963c:-NdVAu223VuQzk_7SoAz:bobovfi) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider uniting with OutboundProtocolError
</blockquote></details>

I'm not sure about it. I say keep it like that for now. adding a todo to not forget about it
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtIlK7eUrbjtJhANA:-NdV7whP0bu3D8rxPut4:blqf7g8) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did you pin it? explain in a comment
</blockquote></details>

compiler said so :)
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUuFsn1K4cAnZ-xETT:-NdVAUuF9JjqhluAvxhJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This can be a lot more simpler if you return when you receive Some(None) and you return error when you receive None. In that case, you don't need this variable
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtkkP75gayPzpVowT:-NdVAUht0XKY_MmYo2XS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If response_relay_receiver.next() didn't return None, assert that expect_end_of_stream is false (return error if it isn't)
(Assuming you didn't erase expect_end_of_stream as suggested above)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUsSTv1ZHS5RjWtXxs:-NdVAUKR5AOQ3kFWZ7Ju:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

flatten into one match with the following arms instead
Some(Some(response))
Some(None)
None
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUvTpV6TUk48Oudexs:-NdVA_7Y68WvPMPJ0BuA:b3vg4g9) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L167)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to protocol_test (or test_utils file if you use it somewhere else
</blockquote></details>

I prefer to leave it like that for now. next we'll move the channel to the handler and then the behavior and we'll move it in the end to the DB handler.
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUvdoWB8WuU5mtgWzq:-NdVBptI-24O68sMAbAh:b-glsopb) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We're still not sure about the names of these yet. Write something more generic like 
// Sends responses to the inbound protocol and receives responses from the outbound protocol
</blockquote></details>

I don't think it conveys the same meaning. I want the reader to understand that this part is the part of the p2p handler (network handler) and the DB  reader.
I think that it's fine even if we rename it later. 
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUw_oZ-fiD3Ouz5pmL:-NdVDI-SC8jmA7VgZslI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L75)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why ignore? Assert that the received request is the request that the outbound sent
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUwUC25A-5Rzvqnsrl:-NdVGWzc9JZ7f1iyRlLf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to _request
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)* status: all files reviewed, 7 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUs3LW1OBfQrhO7bve:-NdZEaIo7nL89EJbNzZp:b-e0ppb2) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

what none?
</blockquote></details>

What does it mean when response_relay_receiver received None
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrPIj41jaMTMO963c:-NdZG7mV6Qs7g4wA_Kdl:b-1rijqo) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L39)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I'm not sure about it. I say keep it like that for now. adding a todo to not forget about it
</blockquote></details>

Very well, then add the TODO
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtIlK7eUrbjtJhANA:-NdZGBqg0mqTzw4Y8mnq:b-jeyjnc) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L64)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

compiler said so :)
</blockquote></details>

Understand what the compiler said and explain that in a comment
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUvTpV6TUk48Oudexs:-NdZGY6DDBspKKui3tfn:b-sc9vbg) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L167)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I prefer to leave it like that for now. next we'll move the channel to the handler and then the behavior and we'll move it in the end to the DB handler.
</blockquote></details>

I think that it's better to remove it and if we'll want it in the DB handler then we'll take care of that. but I'm ok with leaving it if that's what you think
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZGk19CPdw6eaSqXoA:-NdZGk19CPdw6eaSqXoB:b-ifcvr) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol.rs#L122)):*
> ```XML
>     #[error(transparent)]
>     IOError(#[from] io::Error),
>     #[error(transparent)]
> ```

Change here the error message in the same way you did with InboundProtocolError
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUwUC25A-5Rzvqnsrl:-NdZHRwt-kZxUI7_z9-M:b3pju46) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L76)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We'll might change this protocol to GetHeaders so IMO it's better to simply call this request, but whatever you prefer
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZH9g7BlPE-_GTDaTm:-NdZH9g7BlPE-_GTDaTn:b2liabm) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol_test.rs#L60)):*
> ```XML
> 
>     let (outbound_protocol, mut outbound_responses_relay_receiver) =
>         OutboundProtocol::new(Default::default());
> ```

Instead of calling default here, create a variable for the request and set the variable to default and use it here and in the assertion below
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZHNmPDsCeGGpLVW45:-NdZHNmPDsCeGGpLVW46:buuwqyo) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol_test.rs#L204)):*
> ```XML
>         // plays the role of the network handler
>         async move {
>             let _blocks_query = inbound_request_relay_receiver.await.unwrap();
> ```

Rename to _request or _blocks_request

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUs3LW1OBfQrhO7bve:-NdZJuBX3q84TsD3GbNu:b4heuqo) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What does it mean when response_relay_receiver received None
</blockquote></details>

oh got it. I think it's very obvious from the usage. look at [write_message(](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol.rs#L80)
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUrPIj41jaMTMO963c:-NdZKOKU9wvTcngGmuoC:b-heu256) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Very well, then add the TODO
</blockquote></details>

here: [// TODO(nevo): consider consolidating with InboundProtocolError](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol.rs#L117)
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUtIlK7eUrbjtJhANA:-Nd_5WcO5np1DAkzzN93:b-18v2u) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Understand what the compiler said and explain that in a comment
</blockquote></details>

due to recent changes it's unneeded anymore
___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZGk19CPdw6eaSqXoA:-NdZMxt-BuiE96gRMoFM:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol.rs#L122)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change here the error message in the same way you did with InboundProtocolError
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUwUC25A-5Rzvqnsrl:-NdZLahB2NT2modHpQ7-:b-rek2y0) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We'll might change this protocol to GetHeaders so IMO it's better to simply call this request, but whatever you prefer
</blockquote></details>

I think we need to call it data since we'll eventually generalize it to be used to more the just the blocks :) 
I think let's not waste effort in trying to make everything perfect right away. we'll modify as needed as we progress 
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZH9g7BlPE-_GTDaTm:-NdZKnvg6TqX5vBGgrqX:b7eh9ik) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol_test.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of calling default here, create a variable for the request and set the variable to default and use it here and in the assertion below
</blockquote></details>

ok I'm fine with it. but since it's a work in progress and will definitely change soon I think it's nitpicking 
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdZHNmPDsCeGGpLVW45:-NdZMgrj8zF4waKr-Dff:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol_test.rs#L204)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to _request or _blocks_request
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-:-Nd_8onq9JyM-RX8snJn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/get_blocks/protocol.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUs3LW1OBfQrhO7bve:-Nd_7ShU9e4xNM75DiAg:b5knxhk) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol.rs#L23)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

oh got it. I think it's very obvious from the usage. look at [write_message(](https://github.com/starkware-libs/papyrus/blob/50376780de8455fa4f0931fc310dc8257e2c3057/crates/papyrus_network/src/get_blocks/protocol.rs#L80)
</blockquote></details>

I get it, but right now we're not at the usage. I think it will be clearer to document it here.
Now that I think of it, the correct way to document it is to write documentation for the new method and describe the sender end
As we agreed on slack, you can do this in a later PR
___
*[`crates/papyrus_network/src/get_blocks/protocol_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1131#-NdUwUC25A-5Rzvqnsrl:-Nd_8MypDUMK9bmxih7U:b-sa2c36) ([raw file](https://github.com/starkware-libs/papyrus/blob/f291cee1db27eba206104be47f9e9437893d6274/crates/papyrus_network/src/get_blocks/protocol_test.rs#L76)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think we need to call it data since we'll eventually generalize it to be used to more the just the blocks :) 
I think let's not waste effort in trying to make everything perfect right away. we'll modify as needed as we progress
</blockquote></details>

Ok, but I think that request/response are good names even when we generalize

**Pull request closed without merging**
