### PR TITLE
fix: cairo-lang-starknet version fixate

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1635)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1635)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`Dockerfile` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1635#-Nol8l3b47Ktg63hXcId:-Nol8l3b47Ktg63hXcIe:b-sxb33p) ([raw file](https://github.com/starkware-libs/papyrus/blob/b43f005b39f1aafe0e8f61595fb34cfeb70f17af/Dockerfile#L48)):*
> ```Dockerfile
> RUN rustup target add x86_64-unknown-linux-musl && \
>     CARGO_INCREMENTAL=0 cargo build  --target x86_64-unknown-linux-musl --release --package papyrus_node && \
>     # TODO: Consider seperating the load test for CI to a different image.
> ```

Why not translate to spanish

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1635)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`Dockerfile` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1635#-Nol8l3b47Ktg63hXcId:-Nol9I9b3zYaeX_gUmWR:b-u7wk1n) ([raw file](https://github.com/starkware-libs/papyrus/blob/b43f005b39f1aafe0e8f61595fb34cfeb70f17af/Dockerfile#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not translate to spanish
</blockquote></details>

because we speak rust

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1635#-:-Nol9XqJ2Qk9ct-LNsV5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

___
*[`Dockerfile` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1635#-Nol8l3b47Ktg63hXcId:-Nol9Twx7e1ut1YUiT_a:b-w9sxr8) ([raw file](https://github.com/starkware-libs/papyrus/blob/b43f005b39f1aafe0e8f61595fb34cfeb70f17af/Dockerfile#L48)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

because we speak rust
</blockquote></details>

Ok then

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1635#-:-Noqn_lK2WoF9qx3N_Bu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
