### PR TITLE
Support periodic backups to S3

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/backup-values.yaml` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4VXb7w5677NXDc9z:-NQQ4VXcD6WIgY_OYR35:b-3ke96z) ([raw file](https://github.com/starkware-libs/papyrus/blob/500b9a66976dd10bc241b3b8e7259e347eabaec4/deployments/helm/backup-values.yaml#L20)):*
> ```YAML
>   additional_headers: # optional addtional headers for SN communication
> 
> sleep_interval: 6h
> ```

not consistent with values.yaml



_Code quote:_
```YAML
sleep_interval: 6h
s3_bucket_name: papyrus-backup
aws_access_key_id: dummy access_key
aws_secret_access_key: dummy secret_key
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/files/backup.sh` line 18 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4a_j1g4lRem7-mtt:-NQQ4a_j1g4lRem7-mtu:b32vah) ([raw file](https://github.com/starkware-libs/papyrus/blob/f9a6e9baf054d91155e3842b2a190dec8f61a0c1/deployments/helm/files/backup.sh#L18)):*
> ```Shell
> 
>     # stop papyrus
>     kill -9 "$PAPYRUS_PID"
> ```

15



_Code quote:_
```Shell
9
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQQ4dZZ-5KVs6Jozuu5:b-bo8md5) ([raw file](https://github.com/starkware-libs/papyrus/blob/f9a6e9baf054d91155e3842b2a190dec8f61a0c1/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
> ```YAML
> data:
>   AWS_ACCESS_KEY_ID: {{ .Values.backup.aws.access_key_id | b64enc }}
>   AWS_SECRET_ACCESS_KEY: {{ .Values.backup.aws.secret_access_key | b64enc }}
> ```

region also needed



_Code quote:_
```YAML
  AWS_ACCESS_KEY_ID: {{ .Values.backup.aws.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.aws.secret_access_key | b64enc }}
```

**Review by eranreshef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @dan-starkware)

___
*[`deployments/helm/backup-values.yaml` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4VXb7w5677NXDc9z:-NQUH1fj8i9AkjCZUw23:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/500b9a66976dd10bc241b3b8e7259e347eabaec4/deployments/helm/backup-values.yaml#L20)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

not consistent with values.yaml
</blockquote></details>

Done.
___
*[`deployments/helm/files/backup.sh` line 18 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4a_j1g4lRem7-mtt:-NQUH2XS9QnPjWy6Hlhv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f9a6e9baf054d91155e3842b2a190dec8f61a0c1/deployments/helm/files/backup.sh#L18)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

15
</blockquote></details>

Done.
___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUH3aJ-bTwovg6_p0s:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f9a6e9baf054d91155e3842b2a190dec8f61a0c1/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

region also needed
</blockquote></details>

Done.

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUYYNE5iUgqXvoovkm:b-xxcdwj) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where?

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUZ12QDX1hCf2Yd9iJ:bde6xx) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Where?
</blockquote></details>

Its not consumed as an env var, it is used with the `--region` flag in the `aws s3 cp ...` command

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUZQUO7MYntQMM1VK-:b-whnoqw) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

Its not consumed as an env var, it is used with the `--region` flag in the `aws s3 cp ...` command
</blockquote></details>

`aws s3 cp "/app/data/$CHAIN_ID/mdbx.dat" "s3://$S3_BUCKET_NAME/$CHAIN_ID/$PAPYRUS_VERSION/$(date +%s).dat --region ${S3_BUCKET_REGION}"`

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUaERc5LX_i1NPSdiR:b-oy7upt) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

`aws s3 cp "/app/data/$CHAIN_ID/mdbx.dat" "s3://$S3_BUCKET_NAME/$CHAIN_ID/$PAPYRUS_VERSION/$(date +%s).dat --region ${S3_BUCKET_REGION}"`
</blockquote></details>

why not adding it to the secret instead to the cmd?

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUaKjc8_Z3UU5T-xnX:b79xvq2) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why not adding it to the secret instead to the cmd?
</blockquote></details>

you may want to use additional aws cmd in the future....

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUbR836bBmr4xSq_hc:b-fuz6ua) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

you may want to use additional aws cmd in the future....
</blockquote></details>

I may, but currently it describes the region where the bucket resides. In the future we may also want to upload to multiple buckets in multiple regions...

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eranreshef-starkware)

___
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUdOFVBQh2H-qfIg29:b-o8z2ko) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

I may, but currently it describes the region where the bucket resides. In the future we may also want to upload to multiple buckets in multiple regions...
</blockquote></details>

and then we will need to support multiple regions... currently just put all AWS related envs in same place

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/templates/aws-creds-secret.yaml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/547#-NQQ4dZZ-5KVs6Jozuu4:-NQUfGsaB9ZbnvhNBcfl:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/faaaac698aac85cad555628ad35d737e63c1fb2b/deployments/helm/templates/aws-creds-secret.yaml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

and then we will need to support multiple regions... currently just put all AWS related envs in same place
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/547#-:-NQUhYpd-fXNLYZmwWyh:bnfp4nl)* status: 1 of 11 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
