### PR TITLE
feat(network): db_executor

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1173)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1130** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1130" target="_blank">Graphite</a> 
    * **PR #1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1173" target="_blank">Graphite</a>  👈
    * **PR #1152** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1152" target="_blank">Graphite</a> 
    * **PR #1147** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1147" target="_blank">Graphite</a> 
    * **PR #1131** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1131" target="_blank">Graphite</a> 
    * **PR #1123** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1123" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1173?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1173)* status: 4 of 5 files reviewed, 9 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIC7F90sF07GUP36Ms:-NeIC7F90sF07GUP36Mt:b-nuq5e7) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/lib.rs#L41)):*
> ```XML
>     pub skip: u64,
>     pub step: u64,
>     pub outbound_session_id: InboundSessionId,
> ```

inbound_session_id, not outbound
I think you shouldn't add the session id here since this can be useful both for the db executor and the sync notifier
___
*[`crates/papyrus_network/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeICA7y9Im7gzf7O6qn:-NeICA7y9Im7gzf7O6qo:bsewjj) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/lib.rs#L46)):*
> ```XML
> #[derive(Default)]
> pub struct BlockResult {
>     pub outbound_session_id: InboundSessionId,
> ```

Same here (also regarding removing)
___
*[`crates/papyrus_network/src/lib.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeINkoE43AQ1yKc-MES:-NeINkoE43AQ1yKc-MET:bfw1kvx) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/lib.rs#L47)):*
> ```XML
> pub struct BlockResult {
>     pub outbound_session_id: InboundSessionId,
>     pub data: Block,
> ```

I'd start with BlockHeader
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIDlQ35NKy8ARKzOP7:-NeIDlQ35NKy8ARKzOP8:bro1hng) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L22)):*
> ```XML
> 
> #[allow(dead_code)]
> impl<'a> DbExecutor<'a> {
> ```

Define a trait for DbExecutor. This will both make the code more readable and allow mocking it for tests
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIE9UZAX_MAf_HsdRt:-NeIE9UZAX_MAf_HsdRu:b-dja5my) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L23)):*
> ```XML
> #[allow(dead_code)]
> impl<'a> DbExecutor<'a> {
>     pub(crate) fn new() -> Self {
> ```

These methods can be pub since the entire struct is pub(crate)
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIERwJ6pzKeIgWnB8b:-NeIDwzl8JQ9kKo-jt-J:bm1p0jo) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L36)):*
> ```XML
>     }
> 
>     pub(crate) fn get_query_sender(&self) -> UnboundedSender<BlockQuery> {
> ```

Do one of the following:
1. return query_sender and blocks_data_receiver in new instead of storing them in the struct
2. Remove all the channels, have a method for send_query and receive_data (receive data will return Poll<Data>), and have a buffer (VecDeque) to store pending queries and data
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIOHq_29KX-ErHylo3:-NeIO3wSAPaEpUSNB0V-:b-cwctt4) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
> ```XML
>     type Item = DbExecutorStatus;
> 
>     fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
> ```

This will mean that the status will return every poll even if the node doesn't want the status. I think you should change this method to return nothing (and receive cx) and add a different method to get the status
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIPUWg1wFzjsm50AIM:-NeIPUWg1wFzjsm50AIN:b-stxqy8) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
> ```XML
>     type Item = DbExecutorStatus;
> 
>     fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
> ```

This function is too big, try to extract to methods and then I'll be able to review it
___
*[`crates/papyrus_network/src/streamed_data_protocol/mod.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIPu21CzBTWvs8PXGc:-NeIPu21CzBTWvs8PXGd:b-v3d4u4) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/streamed_data_protocol/mod.rs#L9)):*
> ```XML
> #[derive(Clone, Copy, Debug, Default, Display, Eq, Hash, PartialEq)]
> pub struct OutboundSessionId {
>     value: usize,
> ```

Make this pub as well

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1173)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIC7F90sF07GUP36Ms:-NeIRiik5DjbB-6q4D2I:b-x1vd40) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/lib.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

inbound_session_id, not outbound
I think you shouldn't add the session id here since this can be useful both for the db executor and the sync notifier
</blockquote></details>

so let's add a generic session id. I think it's a good idea to add it to this struct that way we can make sure in compilation that a query is always attached to a session
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIDlQ35NKy8ARKzOP7:-NeIS00o5T53RWeZSwsv:bnwt6wh) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Define a trait for DbExecutor. This will both make the code more readable and allow mocking it for tests
</blockquote></details>

already doing it in the for the executors struct test. next PR
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIE9UZAX_MAf_HsdRt:-NeISAjTEE0uZfpdB5vy:b-e7fu2x) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These methods can be pub since the entire struct is pub(crate)
</blockquote></details>

I prefer safety.. you can always make it public if you need to. if it's already public no one will do the work of reducing public outputs
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIERwJ6pzKeIgWnB8b:-NeISa8S4p6L7MGTni0f:be2tgf7) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Do one of the following:
1. return query_sender and blocks_data_receiver in new instead of storing them in the struct
2. Remove all the channels, have a method for send_query and receive_data (receive data will return Poll<Data>), and have a buffer (VecDeque) to store pending queries and data
</blockquote></details>

I don't see why.. this is the design we agreed on
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIOHq_29KX-ErHylo3:-NeISpqaCB1ebj80qg1n:b-4zynr1) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This will mean that the status will return every poll even if the node doesn't want the status. I think you should change this method to return nothing (and receive cx) and add a different method to get the status
</blockquote></details>

I think it's beneficial to return the status on every poll. that way you really get the most up to date status.
between polls it can't change and if the caller doesn't want to use the status it can ignore it
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIPUWg1wFzjsm50AIM:-NeIaRk48pXZec9EXGmn:b-pagozn) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This function is too big, try to extract to methods and then I'll be able to review it
</blockquote></details>

not sure if it makes it simpler but here it is

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1173)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIC7F90sF07GUP36Ms:-NeIcNJ43uGYyCVzwv8h:b-5c3msg) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/lib.rs#L41)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

so let's add a generic session id. I think it's a good idea to add it to this struct that way we can make sure in compilation that a query is always attached to a session
</blockquote></details>

Very well, I already added it in the handler code in my computer so I'll use it too
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIERwJ6pzKeIgWnB8b:-NeIcgs37Ommvkv9axTk:b-nlvxft) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L36)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't see why.. this is the design we agreed on
</blockquote></details>

What we agreed on is 1 (unless we didn't understand each other or my memory fails me)
but your code made me think of 2 which I think is the best (just like we preferred not using channels in streamed_data)
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIOHq_29KX-ErHylo3:-NeIczo13rbpGh31lWNv:b-3kb5rq) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think it's beneficial to return the status on every poll. that way you really get the most up to date status.
between polls it can't change and if the caller doesn't want to use the status it can ignore it
</blockquote></details>

But it can cause performance issues. I'm ok with resolving this now but I think we should have this in mind
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIPUWg1wFzjsm50AIM:-NeIebgV8DIN_YrOzjU2:b-1ctm1u) ([raw file](https://github.com/starkware-libs/papyrus/blob/551c15437f8ca9a5261327817a5ed6d9762d70fc/crates/papyrus_network/src/executor/db_executor.rs#L80)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

not sure if it makes it simpler but here it is
</blockquote></details>

Much better
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIdxy41wemb7FlEmfp:-NeIdxy41wemb7FlEmfq:bp5ezdy) ([raw file](https://github.com/starkware-libs/papyrus/blob/cce421e20717e6a1d849fedefccc10364d923e3e/crates/papyrus_network/src/executor/db_executor.rs#L55)):*
> ```XML
> 
>     fn poll_for_new_queries(&mut self, cx: &mut Context<'_>, new_status: &mut DbExecutorStatus) {
>         if !self.status.query_receiver_terminated {
> ```

Either move this if to the main poll function, or move the if into the inner function in the data polling
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIdrPYCgiEhuuH5nZ5:-NeIdrPYCgiEhuuH5nZ6:b-9jcs30) ([raw file](https://github.com/starkware-libs/papyrus/blob/cce421e20717e6a1d849fedefccc10364d923e3e/crates/papyrus_network/src/executor/db_executor.rs#L78)):*
> ```XML
>         mut new_status: DbExecutorStatus,
>     ) -> Poll<Option<DbExecutorStatus>> {
>         match Pin::new(&mut self.db_ops).poll_next(cx) {
> ```

Use poll_next_unpin instead
___
*[`crates/papyrus_network/src/executor/db_executor.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIej9r8ZrhMq5hUMrq:-NeIej9r8ZrhMq5hUMrr:bcw6mkg) ([raw file](https://github.com/starkware-libs/papyrus/blob/cce421e20717e6a1d849fedefccc10364d923e3e/crates/papyrus_network/src/executor/db_executor.rs#L101)):*
> ```XML
>                 // if the query receiver is terminated and there are no open queries, terminate the
>                 // stream
>                 if self.status.query_receiver_terminated {
> ```

In general, I think that if a channel is terminated it's an error and not a regular flow, and it shouldn't appear in the status
___
*[`crates/papyrus_network/src/streamed_data_protocol/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1173#-NeIfwJjDTSB7bdP7H_d:-NeIfwJjDTSB7bdP7H_e:b-d1rnqd) ([raw file](https://github.com/starkware-libs/papyrus/blob/cce421e20717e6a1d849fedefccc10364d923e3e/crates/papyrus_network/src/streamed_data_protocol/mod.rs#L24)):*
> ```XML
> }
> 
> impl Default for SessionId {
> ```

Do you need to impl Default? I prefer not to have a default if it's unclear what it is
If you do need it, use #[default] instead

**Pull request closed without merging**
