### PR TITLE
feat(storage)!: mark some tables as versioned

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)

### CODE REVIEW

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by liorgold2 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bFDV4nWngPx6IULq:-Nq1bFDV4nWngPx6IULr:b-pfmok1) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L440)):*
> ```XML
>         contract_storage: TableIdentifier<(ContractAddress, StorageKey, BlockNumber), NoVersionValueWrapper<StarkFelt>, SimpleTable>,
>         declared_classes: TableIdentifier<ClassHash, VersionZeroWrapper<LocationInFile>, SimpleTable>,
>         declared_classes_block: TableIdentifier<ClassHash, NoVersionValueWrapper<BlockNumber>, SimpleTable>,
> ```

What's this table? In general, makes sense to document each of them with a one-line comment.
___
*[`crates/papyrus_storage/src/lib.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bNcx5ZhoD9N5tyCV:-Nq1bNcyDmNkZrTMh9e7:bubazel) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L442)):*
> ```XML
>         declared_classes_block: TableIdentifier<ClassHash, NoVersionValueWrapper<BlockNumber>, SimpleTable>,
>         deprecated_declared_classes: TableIdentifier<ClassHash, VersionZeroWrapper<IndexedDeprecatedContractClass>, SimpleTable>,
>         deployed_contracts: TableIdentifier<(ContractAddress, BlockNumber), NoVersionValueWrapper<ClassHash>, SimpleTable>,
> ```

Maybe this should be versioned?
___
*[`crates/papyrus_storage/src/lib.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bRjh4CR6c7tofNUD:-Nq1bRjh4CR6c7tofNUE:bbjxj0b) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L443)):*
> ```XML
>         deprecated_declared_classes: TableIdentifier<ClassHash, VersionZeroWrapper<IndexedDeprecatedContractClass>, SimpleTable>,
>         deployed_contracts: TableIdentifier<(ContractAddress, BlockNumber), NoVersionValueWrapper<ClassHash>, SimpleTable>,
>         events: TableIdentifier<(ContractAddress, EventIndex), NoVersionValueWrapper<EventContent>, SimpleTable>,
> ```

`events` should be versioned.
___
*[`crates/papyrus_storage/src/lib.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bcF2CirwnlyYruaJ:-Nq1bcF2CirwnlyYruaK:bkdu5rg) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L446)):*
> ```XML
>         headers: TableIdentifier<BlockNumber, VersionZeroWrapper<BlockHeader>, SimpleTable>,
>         markers: TableIdentifier<MarkerKind, VersionZeroWrapper<BlockNumber>, SimpleTable>,
>         nonces: TableIdentifier<(ContractAddress, BlockNumber), NoVersionValueWrapper<Nonce>, SimpleTable>,
> ```

I think `nonces` should be versioned as well. E.g., consider nonce generalization in the future.

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware, @liorgold2, and @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bFDV4nWngPx6IULq:-Nq7az8H94ikPRbogmER:b-hevik2) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L440)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What's this table? In general, makes sense to document each of them with a one-line comment.
</blockquote></details>

Discussed f2f. We will document it
___
*[`crates/papyrus_storage/src/lib.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bNcx5ZhoD9N5tyCV:-Nq7u56G26ckxPdtp-tV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L442)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Maybe this should be versioned?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bRjh4CR6c7tofNUD:-Nq7uLKm9BkDOZJEPCqA:bcwwaka) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L443)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`events` should be versioned.
</blockquote></details>

Discussed f2f, decided not to.
___
*[`crates/papyrus_storage/src/lib.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1678#-Nq1bcF2CirwnlyYruaJ:-Nq7uKqrDIjArEOLLqOP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/953f633d69daa1c367460bd891ddb653847e168a/crates/papyrus_storage/src/lib.rs#L446)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think `nonces` should be versioned as well. E.g., consider nonce generalization in the future.
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2)

**Review by yair-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1678)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2)

**Pull request merged**
