### PR TITLE
Bump starknet api version to include state mutability field in the Fu…

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
…nctionAbiEntry.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/893)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/893)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @yair-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/893)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/893#-NaBLmCo9ytYI8fyCM06:-NaBLmCo9ytYI8fyCM07:bm9au38) (no related file):*
1. The wip commit is because of a rebase that was made to make it compile.
2. Maybe you should check this after rebasing on main.
3. If I didn't say, I also checked this with a real node, sync a node to a point with a contract class with a state mutability field and request this class from the gateway, everything works fine.

___

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 16 files at r2, 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/893#-:-NaC256g2N9NPUxIgq7a:bnfp4nl)* status: 8 of 16 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/893#-:-NaC87Q42Lf2GuT0KuD-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

**Pull request merged**
