### PR TITLE
fix: read_pending_data() for get_state_update()

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1957 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1390#-Nj2XgT6A2q53wop2PXZ:-Nj2XgT6A2q53wop2PX_:bo7iv01) ([raw file](https://github.com/starkware-libs/papyrus/blob/5dec234c48efac06dd11f6f3614d3cecab0545f0/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1957)):*
> ```XML
> 
>     // Get state update of pending block when the pending block is not up to date.
>     let expected_pending_update = StateUpdate::PendingStateUpdate(PendingStateUpdate::default());
> ```

Put a non-default value for the root of the latest block in the storage and put the same value in expected_pending_update.old_root

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 1957 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1390#-Nj2XgT6A2q53wop2PXZ:-Nj2hbetCJ8uEjPlIvXn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5dec234c48efac06dd11f6f3614d3cecab0545f0/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L1957)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put a non-default value for the root of the latest block in the storage and put the same value in expected_pending_update.old_root
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390#-:-Nj2hsov9id0zyvIHJ5-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1390)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
