### PR TITLE
feat(JSON-RPC): implement estimateMessageFee

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)

### CODE REVIEW

**Review by nagmo-starkware — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 1050 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nlrw2wECmf_xO9FhcLS:-Nlrw2wECmf_xO9FhcLT:b-e6gcj9) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e0be73bb9a84ebaede8068857a34b7e38243ca1/crates/papyrus_rpc/src/v0_4/execution_test.rs#L1050)):*
> ```XML
>     assert_eq!(l1_handler_tx.contract_address, *CONTRACT_ADDRESS);
>     assert_eq!(l1_handler_tx.entry_point_selector, selector_from_name("l1_handle"));
>     assert_eq!(*l1_handler_tx.calldata.0.get(0).unwrap(), stark_felt!("0x987")); // L1 address of the sender
> ```

this is based on a magic string.. would easily break

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4/execution_test.rs` line 1050 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nlrw2wECmf_xO9FhcLS:-NlxEJQbDp6t6HLY7jUd:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e0be73bb9a84ebaede8068857a34b7e38243ca1/crates/papyrus_rpc/src/v0_4/execution_test.rs#L1050)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this is based on a magic string.. would easily break
</blockquote></details>

done

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SWSQ-d9HtIgua1u2:-Nm5SWSQ-d9HtIgua1u3:bwx1w9u) (no related file):*
Fix the table in the README to show that we support this method

___
___
*[`crates/papyrus_rpc/src/v0_4/transaction.rs` line 758 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5R89A-F-5hd7wfnqV:-Nm5R89A-F-5hd7wfnqW:b-anb7tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/transaction.rs#L758)):*
> ```XML
> }
> 
> fn eth_address_to_felt(eth_address: EthAddress) -> StarkFelt {
> ```

Add a TODO to move this to SN_API, and changing it to `From`
___
*[`crates/papyrus_rpc/src/v0_4/transaction.rs` line 759 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5S5j36YxhQDvQa739:-Nm5S5j36YxhQDvQa73A:b-mh1kiv) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/transaction.rs#L759)):*
> ```XML
> 
> fn eth_address_to_felt(eth_address: EthAddress) -> StarkFelt {
>     let as_json = serde_json::to_value(eth_address).expect("Expecting valid eth address");
> ```

Change this to construct the felt from the bytes
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1303 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SqzI1WD_c58Sl8YM:-Nm5SqzI1WD_c58Sl8YN:bb4l1f8) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1303)):*
> ```XML
>         // Convert the message to an L1 handler transaction, and estimate the fee of the
>         // transaction.
>         // The fee param doesn't matter for the estimation, any value other then 0 is acceptable.
> ```

Consider adding a small explanation why the fee doesn't matter. It isn't clear to me
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1334 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5Sf9x2KFzCiCBIfAu:-Nm5Sf9x2KFzCiCBIfAv:bdnnivf) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1334)):*
> ```XML
>         .await
>         .map_err(internal_server_error)?;
> ```

use BlockNotRevertedValidator

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @nagmo-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SWSQ-d9HtIgua1u2:-Nm5Ti5u8pFvEFC83Lmr:b-bhqiw2) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Fix the table in the README to show that we support this method
</blockquote></details>

After I implement it in all spec versions

___
___
*[`crates/papyrus_rpc/src/v0_4/transaction.rs` line 758 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5R89A-F-5hd7wfnqV:-Nm686wSAdmmXzWd3N2h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/transaction.rs#L758)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO to move this to SN_API, and changing it to `From`
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4/transaction.rs` line 759 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5S5j36YxhQDvQa739:-Nm687Km8YoW7D_wVmty:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/transaction.rs#L759)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to construct the felt from the bytes
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1303 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SqzI1WD_c58Sl8YM:-NmAprM8CUEp_7n2Rvyy:b-x1hnzv) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1303)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider adding a small explanation why the fee doesn't matter. It isn't clear to me
</blockquote></details>

Dived deeper into this issue and changed it a bit.
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1334 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5Sf9x2KFzCiCBIfAu:-Nm6BIcA-KyFGcAB6Mgh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1334)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use BlockNotRevertedValidator
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1303 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SqzI1WD_c58Sl8YM:-NmAqeCK9-prEF6Ghdt2:b-xsknwh) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1303)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Dived deeper into this issue and changed it a bit.
</blockquote></details>

Maybe we can concise it a bit.
The fee input is used to bound the amount of fee used. Because we want to estimate the fee, we pass u128::MAX so the execution won't fail.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-:-NmArOoA9QxCgZTitSAe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 1303 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-Nm5SqzI1WD_c58Sl8YM:-NmArx6zCIEgVzKIpR6e:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/efcd97f0e19a655142c209f107d1533928be7631/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L1303)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Maybe we can concise it a bit.
The fee input is used to bound the amount of fee used. Because we want to estimate the fee, we pass u128::MAX so the execution won't fail.
</blockquote></details>

done

**Review by ShahakShama — APPROVED** [review]
> Reviewed 5 of 11 files at r5, 1 of 1 files at r6, 12 of 12 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_5/api/api_impl.rs` line 1423 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-NmPpLzj0bScqFTtMx7G:-NmPpLzj0bScqFTtMx7H:bw2tmg5) ([raw file](https://github.com/starkware-libs/papyrus/blob/58a7b6e8089a6da44115f940ccbb9fbf3e94b2e2/crates/papyrus_rpc/src/v0_5/api/api_impl.rs#L1423)):*
> ```XML
>                     )));
>                 }
>                 let (gas_price, fee, _unit) = fee_as_vec.first().expect("No fee was returned");
> ```

Try to avoid panicing if possible

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-:-NmPqLcxBOx1ojvNpFHC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1519#-:-NmPtybt5BIix6l0hBnl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @nagmo-starkware)

**Pull request merged**
