### PR TITLE
chore: run tests in the CI using nextest

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1063)

### CODE REVIEW

**Comment by dan-starkware** [comment]
First commit is not related, right?

**Comment by dan-starkware** [comment]
How did CI duration change?

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1063)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

**Comment by Yael-Starkware** [comment]
> First commit is not related, right?

right! I'll create a new clean PR.

**Pull request closed without merging**
