### PR TITLE
Add starknet_syncing API

### PR DESCRIPTION
**Pull request by OmriEshhar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)

### CODE REVIEW

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827#-:-N_7srudD_D097GwULXq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_gateway/src/api/v0_3_0/mod.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_7sKNC8LHL8dFVeenA:-N_7sKNC8LHL8dFVeenB:b8h3lgb) ([raw file](https://github.com/starkware-libs/papyrus/blob/550f93dbb5ecd11f00c94a1103dbff86a0e1a787/crates/papyrus_gateway/src/api/v0_3_0/mod.rs#L113)):*
> ```XML
>     fn get_events(&self, filter: EventFilter) -> RpcResult<EventsChunk>;
> 
>     /// Gets the synching status of the node.
> ```

Since this return value is misleading I would use something more explicit



_Suggestion:_
```XML
/// Returns the synching status of the node, or false if the node is not synching.
```
___
*[`crates/papyrus_gateway/src/api/v0_3_0/mod.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_7rkdO6rhKxamveuvJ:-N_7rkdO6rhKxamveuvK:bia3yrz) ([raw file](https://github.com/starkware-libs/papyrus/blob/550f93dbb5ecd11f00c94a1103dbff86a0e1a787/crates/papyrus_gateway/src/api/v0_3_0/mod.rs#L115)):*
> ```XML
>     /// Gets the synching status of the node.
>     #[method(name = "syncing")]
>     fn syncing(&self) -> RpcResult<bool>;
> ```

Maybe an enum with the real variants (false or sync_status)? Can also be in a separate PR.
This way the temporary impl. can return not synced at all.



_Code quote:_
```XML
bool
```

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/api/v0_3_0/mod.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_7rkdO6rhKxamveuvJ:-N_7uiBAC5GrxriH3ZHA:b-xan1rp) ([raw file](https://github.com/starkware-libs/papyrus/blob/550f93dbb5ecd11f00c94a1103dbff86a0e1a787/crates/papyrus_gateway/src/api/v0_3_0/mod.rs#L115)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Maybe an enum with the real variants (false or sync_status)? Can also be in a separate PR.
This way the temporary impl. can return not synced at all.
</blockquote></details>

I'll do it on next PR

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/api/v0_3_0/mod.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_7rkdO6rhKxamveuvJ:-N_7uyjn5F2bkSgeso3O:b-azpg4l) ([raw file](https://github.com/starkware-libs/papyrus/blob/550f93dbb5ecd11f00c94a1103dbff86a0e1a787/crates/papyrus_gateway/src/api/v0_3_0/mod.rs#L115)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I'll do it on next PR
</blockquote></details>

Actually, you're right, I'll do it now...

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 2 unresolved discussions (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XYIXfC4DHx45xPU4V:-N_XYIXg3LNcdwh334uw:b-b21gq4) (no related file):*
Please add a test that verifies that the serialization conforms to the spec (or a TODO)

___
___
*[`crates/papyrus_gateway/src/api.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XTZu32w-WJqRA0wNC:-N_XTZu32w-WJqRA0wND:b-qors4i) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L99)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> pub struct SyncStatus {
> ```

* Please document
* I guess that later on this will move closer to the sync module. (can stay here in the meantime)



_Code quote:_
```XML
pub struct SyncStatus
```
___
*[`crates/papyrus_gateway/src/api.rs` line 109 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XTnz871ZIWY2qoDRa:-N_XTnz871ZIWY2qoDRb:bi2lx1k) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L109)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> pub enum SyncingState {
> ```

Please move before the SyncStatus struct. 



_Code quote:_
```XML
pub enum SyncingState
```
___
*[`crates/papyrus_gateway/src/api.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XU2bjCxpYNnXo1lWi:-N_XU2bjCxpYNnXo1lWj:b-idmd01) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L110)):*
> ```XML
> #[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> pub enum SyncingState {
>     IsSyncing(bool),
> ```

We don't really need the bool value here, right?
Can we do something like this and serialize it as false?



_Suggestion:_
```XML
Synced,
```

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_bVGjX2VqSMKnCZBQg:-N_bVGjX2VqSMKnCZBQh:bcm9zcw) (no related file):*
I don't see the new definition of struct SyncStatus.
Did you push it?

___

**Review by OmriEshhar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/api.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XU2bjCxpYNnXo1lWi:-N_bVx5f2HiNX-G6gfb3:b5mlgui) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L110)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We don't really need the bool value here, right?
Can we do something like this and serialize it as false?
</blockquote></details>

I'm not sure that I understand the naming.
You want to reutrn 'false' for 'Synced' when it's actually 'true'?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 6 of 14 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XYIXfC4DHx45xPU4V:-N_Z57GI2XWZW8CYQ9vx:blcgmca) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a test that verifies that the serialization conforms to the spec (or a TODO)
</blockquote></details>

Done (TODO).

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_bVGjX2VqSMKnCZBQg:-N_h7I7-9iPartDYBMtE:b-wcs1uf) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I don't see the new definition of struct SyncStatus.
Did you push it?
</blockquote></details>

In `crates/papyrus_common/src/lib.rs`.

___
___
*[`crates/papyrus_gateway/src/api.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XTZu32w-WJqRA0wNC:-N_Z2l4I73wNGBhCUmJF:bpczoqk) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L99)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

* Please document
* I guess that later on this will move closer to the sync module. (can stay here in the meantime)
</blockquote></details>

Done.
Moved to the new common crate.
___
*[`crates/papyrus_gateway/src/api.rs` line 109 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XTnz871ZIWY2qoDRa:-N_YKV634SB_7-mCcbuC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L109)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move before the SyncStatus struct. 
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/api.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XU2bjCxpYNnXo1lWi:-N_YKQPH6vGICEfB5iWl:b-jl63id) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L110)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We don't really need the bool value here, right?
Can we do something like this and serialize it as false?
</blockquote></details>

Done.
Let's postpone the serialization.

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 4 of 8 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/papyrus_common/src/lib.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_h7OOg10qPihpplrdm:-N_h7OOg10qPihpplrdn:b-lqi3s6) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb253a3c946122c1b652fc4b39a3f0eb2d163bb7/crates/papyrus_common/src/lib.rs#L6)):*
> ```XML
> #[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> pub enum SyncingState {
>     Synced(bool),
> ```

this has a reverse meaning, doesn't it?
According to the spec, we should return 'false' if the syncing finished, but if the syncing finished, it means that Synced=true...



_Code quote:_
```XML
Synced(bool),
```
___
*[`crates/papyrus_common/src/lib.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_h7G0I5gWHcLnC-XA6:-N_h7G0I5gWHcLnC-XA7:bqwjghy) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb253a3c946122c1b652fc4b39a3f0eb2d163bb7/crates/papyrus_common/src/lib.rs#L10)):*
> ```XML
> }
> 
> // TODO(yoav): add a test that verifies that the serialization conforms to the spec.
> ```

separate the TODO from the struct comment

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @OmriEshhar1)

___
*[`crates/papyrus_common/src/lib.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_h7OOg10qPihpplrdm:-N_hFp8_74XBds6VHj2h:b-ecjocz) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb253a3c946122c1b652fc4b39a3f0eb2d163bb7/crates/papyrus_common/src/lib.rs#L6)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

this has a reverse meaning, doesn't it?
According to the spec, we should return 'false' if the syncing finished, but if the syncing finished, it means that Synced=true...
</blockquote></details>

I removed the `bool`.
___
*[`crates/papyrus_common/src/lib.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_h7G0I5gWHcLnC-XA6:-N_hFkdb6e4gJuTbVO-t:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb253a3c946122c1b652fc4b39a3f0eb2d163bb7/crates/papyrus_common/src/lib.rs#L10)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

separate the TODO from the struct comment
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/api.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_XU2bjCxpYNnXo1lWi:-N_hFnJZ2ukVXvWdLjB9:b-w0ucfp) ([raw file](https://github.com/starkware-libs/papyrus/blob/d0bcb1caf3fc066293faf0b54dc33bdead5be7bb/crates/papyrus_gateway/src/api.rs#L110)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
Let's postpone the serialization.
</blockquote></details>

Done as well.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 3 of 8 files at r8, 2 of 4 files at r9, 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/papyrus_common/Cargo.toml` line 7 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_mVZEr8Wu1nZQcrGrF:-N_mVZEr8Wu1nZQcrGrG:bn3r560) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cfd345976caac0579c7cd41aa4a37944324ae8b/crates/papyrus_common/Cargo.toml#L7)):*
> ```TOML
> repository.workspace = true
> license-file.workspace = true
> ```

please add description as well
___
*[`crates/papyrus_common/src/lib.rs` line 6 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_mW-r0-K6nYqWbbRoS:-N_mW-r0-K6nYqWbbRoT:b-hj4t2s) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cfd345976caac0579c7cd41aa4a37944324ae8b/crates/papyrus_common/src/lib.rs#L6)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq)]
> pub enum SyncingState {
> ```

Please document



_Code quote:_
```XML
pub enum SyncingState {
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 9 of 22 files reviewed, all discussions resolved (waiting on @dan-starkware and @OmriEshhar1)

___
*[`crates/papyrus_common/Cargo.toml` line 7 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_mVZEr8Wu1nZQcrGrF:-N_n4dqU4or2HtpceClu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cfd345976caac0579c7cd41aa4a37944324ae8b/crates/papyrus_common/Cargo.toml#L7)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

please add description as well
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/lib.rs` line 6 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_mW-r0-K6nYqWbbRoS:-N_n4IK49ZcI7-wafrYg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2cfd345976caac0579c7cd41aa4a37944324ae8b/crates/papyrus_common/src/lib.rs#L6)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r12, 10 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

___
*[`crates/papyrus_common/src/lib.rs` line 5 at r13](https://reviewable.io/reviews/starkware-libs/papyrus/827#-N_r9YOzDok6QDn0s500:-N_r9YOzDok6QDn0s501:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/bc20bb9e5824b936a5411dccd0f94a26fcbc5acd/crates/papyrus_common/src/lib.rs#L5)):*
> ```XML
> use starknet_api::block::{BlockHash, BlockNumber};
> 
> /// The sync state is already synced or syncing.
> ```

Consider



_Suggestion:_
```XML
/// Represent the syncing status of the node.
```

**Review by dan-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by OmriEshhar1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r12, 2 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 19 of 23 files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827)* status: 19 of 23 files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/827#-:-Na1GuVRCktGBFMKh8Hq:bnfp4nl)* status: 19 of 23 files reviewed, all discussions resolved (waiting on @OmriEshhar1)

**Pull request merged**
