### PR TITLE
feat(network): add common.proto

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/build.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyE_lqMBdY0eVg2zM73:-NyE_lqMBdY0eVg2zM74:bryk45o) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/build.rs#L30)):*
> ```XML
>         prost_build::compile_protos(
>             &[
>                 "src/protobuf_messages/proto/p2p/proto/common.proto",
> ```

There's no need for that. common.proto is imported by header/state.proto so we get it from them. I prefer to put here the files containing what we directly need (header and state diff) and not the files containing what we transitively need
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/common.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEarf75H6wg3sEuZhj:-NyEarf75H6wg3sEuZhk:bng2of9) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/src/converters/protobuf_conversion/common.rs#L11)):*
> ```XML
> #[allow(dead_code)]
> pub const PATRICIA_HEIGHT: u32 = 251;
> // TODO: move to starknet_api
> ```

Add newline before this line
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEb6YD5CWvd9a-Jzrv:-NyEb6YD5CWvd9a-Jzrw:b-bwfcvg) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L170)):*
> ```XML
>                 transaction_commitment,
>                 event_commitment,
>                 state_diff_length: Some(0),
> ```

Why did you remove the previous state_diff_length field? Extract it from the commitment
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEblou8ucpRG1OrLn1:-NyEblou8ucpRG1OrLn2:b-tb8fjg) ([raw file](https://github.com/starkware-libs/papyrus/blob/48f8c3ef0964cef249234fcf5e5d876e5185203a/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L201)):*
> ```XML
>             // TODO(shahak): fill this. If the state_diff_length is None make this None.
>             state_diff_commitment: None,
>             state_diff_length: header
> ```

This will make the node not work. Could you fill the state diff commitment field with the length and 0 hash with a TODO to fill the hash?
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEc1xsExzic40T5Hzc:-NyEc1xsExzic40T5Hzd:b-42fdxf) ([raw file](https://github.com/starkware-libs/papyrus/blob/48f8c3ef0964cef249234fcf5e5d876e5185203a/crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs#L134)):*
> ```XML
> // A wrapper struct for Vec<StateDiffsResponse> so that we can implement traits for it.
> pub struct StateDiffsResponseVec(pub Vec<protobuf::StateDiffsResponse>);
> ```

Return this newline

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/common.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEarf75H6wg3sEuZhj:-NyF0ZLYAEBQnsqxR9oV:b8lelrt) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/src/converters/protobuf_conversion/common.rs#L11)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add newline before this line
</blockquote></details>

found an equivalent enum named `DataAvailabilityMode`, so there is no need to declare a new one
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEb6YD5CWvd9a-Jzrv:-NyF0RMLEITFwfrUMpEc:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L170)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did you remove the previous state_diff_length field? Extract it from the commitment
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEblou8ucpRG1OrLn1:-NyF0TCP1aJJm81WvOZV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/48f8c3ef0964cef249234fcf5e5d876e5185203a/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L201)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This will make the node not work. Could you fill the state diff commitment field with the length and 0 hash with a TODO to fill the hash?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyEc1xsExzic40T5Hzc:-NyF0TqJ-_hjKRq7Rl2r:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/48f8c3ef0964cef249234fcf5e5d876e5185203a/crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs#L134)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Return this newline
</blockquote></details>

Done.
___
*[`crates/papyrus_network/build.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyE_lqMBdY0eVg2zM73:-NyF0V-rBOqTJy8oIiZV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/83e7735aecec9628d8d559f0f4f10e429456e47a/crates/papyrus_network/build.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

There's no need for that. common.proto is imported by header/state.proto so we get it from them. I prefer to put here the files containing what we directly need (header and state diff) and not the files containing what we transitively need
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyJr-F06OMVhBjIsnAB:-NyJr-F17dqYXunLtnZP:b-9nddx5) ([raw file](https://github.com/starkware-libs/papyrus/blob/836157705d0e8e89a38878b297cc4224a418a55d/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L178)):*
> ```XML
>                 transaction_commitment,
>                 event_commitment,
>                 // TODO(shahak): fill this.
> ```

Move the todo to the correct line (receipt commitment)
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyJrGVf8Zm0ObaXwSgR:-NyJrGVf8Zm0ObaXwSgS:beghlch) ([raw file](https://github.com/starkware-libs/papyrus/blob/836157705d0e8e89a38878b297cc4224a418a55d/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L205)):*
> ```XML
>                 state_diff_length: header
>                     .state_diff_length
>                     .unwrap_or(0)
> ```

Remove this. keep it None in case it's None and use map to convert the value

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyJr-F06OMVhBjIsnAB:-NyK0oeA3SbRBvrrI1Uj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/836157705d0e8e89a38878b297cc4224a418a55d/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L178)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move the todo to the correct line (receipt commitment)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/header.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-NyJrGVf8Zm0ObaXwSgR:-NyK0pT22SSruZZioWtG:b8zayav) ([raw file](https://github.com/starkware-libs/papyrus/blob/836157705d0e8e89a38878b297cc4224a418a55d/crates/papyrus_network/src/converters/protobuf_conversion/header.rs#L205)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this. keep it None in case it's None and use map to convert the value
</blockquote></details>

it's not an Option, so we have to give it a default value

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1998#-:-NyKnyrq7C-9ky5CN-Pl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
