### PR TITLE
fix(common): accurate transaction hash validation according tx version

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)

### CODE REVIEW

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne328I33boPffZi2xp7:-Ne328I4-BKBn34Tb-Hn:b-i5jsw) (no related file):*
In the tests, we should have an example for each of the cases: goerli, old mainnet, and new mainnet (choose one of the transaction types).

___
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne3147p6gfjOH66aPsd:-Ne3147p6gfjOH66aPse:b-g9xays) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L77)):*
> ```XML
> }
> 
> /// From this block number onwards, the transaction hash can be directly determined
> ```

Only on mainnet.



_Code quote:_
```XML
From this block number onwards
```
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne32l6z3jXWw9YMOnqz:-Ne32l6z3jXWw9YMOnr-:b-fkj770) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L89)):*
> ```XML
> ) -> Result<bool, StarknetApiError> {
>     let mut possible_hashes;
>     // For transactions on the testnet or those with a low block_number, we validate the
> ```

Move to the function doc.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne31BaLEKBA1S1mHchE:-Ne31BaLEKBA1S1mHchF:bivxrgq) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L93)):*
> ```XML
>     // transactions on the mainnet, the hash is validated by calculating the precise hash
>     // based on the transaction version.
>     if chain_id.0 != *"SN_MAIN" || block_number < &TRANSACTION_HASH_WITH_VERSION {
> ```

Please move to a const of type `ChainId`.



_Code quote:_
```XML
"SN_MAIN"
```
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne330ip6NcclDbg4k3k:-Ne330iq7jA58Tfhete6:b-3mjul3) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L93)):*
> ```XML
>     // transactions on the mainnet, the hash is validated by calculating the precise hash
>     // based on the transaction version.
>     if chain_id.0 != *"SN_MAIN" || block_number < &TRANSACTION_HASH_WITH_VERSION {
> ```

IMO a readable flow is:
If it's a new mainnet block - compare hashes and return,
(else) - collect the possible hash etc.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne33zAfCr12MZngpJos:-Ne33zAfCr12MZngpJot:b-lad6u0) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash_test.rs#L53)):*
> ```XML
>             validate_transaction_hash(
>                 &transaction_test_data.transaction,
>                 &BlockNumber(2000),
> ```

Is it the block number of all the transactions in the test?



_Code quote:_
```XML
BlockNumber(2000)
```
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne349qW5ZbQ9OYao0ne:-Ne349qW5ZbQ9OYao0nf:bx3lgsi) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash_test.rs#L83)):*
> ```XML
>             validate_transaction_hash(
>                 &transaction_test_data.transaction,
>                 &BlockNumber(0),
> ```

The same question.



_Code quote:_
```XML
BlockNumber(0)
```

**Review by yoavGrs — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne330ip6NcclDbg4k3k:-Ne3g258Bcs2r1IIIT8J:b-456v3m) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L93)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

IMO a readable flow is:
If it's a new mainnet block - compare hashes and return,
(else) - collect the possible hash etc.
</blockquote></details>

It's easier to follow code like:
```
If A {return a}, if B {return b}, return c.
```
than:
```
If A {do something}, if B {do something}, return X.
```

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne7Po5I5IIbb7H3g1vV:-Ne7Po5J6MUlbXLxmqtu:bs6cbdr) ([raw file](https://github.com/starkware-libs/papyrus/blob/5526bbe51bb2acc2aadba4549c37b32a3be3830f/crates/papyrus_common/src/transaction_hash.rs#L84)):*
> ```XML
> /// transaction hash against all potential historical hash computations. For recent
> /// transactions on mainnet, the hash is validated by calculating the precise hash
> /// based on the transaction version.
> ```

Split it between a description (with `//`) of this function and documentation of the public validate_transaction_hash function.



_Code quote:_
```XML
/// For transactions on testnet or those with a low block_number, we validate the
/// transaction hash against all potential historical hash computations. For recent
/// transactions on mainnet, the hash is validated by calculating the precise hash
/// based on the transaction version.
```
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne7Qb1MEDJ1GfxqfGmT:-Ne7Qb1MEDJ1GfxqfGmU:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/5526bbe51bb2acc2aadba4549c37b32a3be3830f/crates/papyrus_common/src/transaction_hash.rs#L90)):*
> ```XML
>     transaction: &Transaction,
> ) -> Result<Vec<TransactionHash>, StarknetApiError> {
>     let possible_hashes = if chain_id == &ChainId("SN_MAIN".to_string())
> ```





_Suggestion:_
```XML
Ok(if chain_id == &ChainId("SN_MAIN".to_string())
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne328I33boPffZi2xp7:-Ne3V2zGAV5J-lgiijJ5:bvr3m58) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In the tests, we should have an example for each of the cases: goerli, old mainnet, and new mainnet (choose one of the transaction types).
</blockquote></details>

we have many goerli. we have one old mainnet, I'm adding a new mainnet

___
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne3147p6gfjOH66aPsd:-Ne3Q2PU1J-Wn5nY-zaa:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L77)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Only on mainnet.
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne32l6z3jXWw9YMOnqz:-Ne3Q1932XPQrOwn0q0v:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L89)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Move to the function doc.
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne31BaLEKBA1S1mHchE:-Ne3Q-db8vt91wwVXoe3:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L93)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Please move to a const of type `ChainId`.
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne330ip6NcclDbg4k3k:-Ne3TxlM1hJkOaRyE8Ez:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash.rs#L93)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It's easier to follow code like:
```
If A {return a}, if B {return b}, return c.
```
than:
```
If A {do something}, if B {do something}, return X.
```
</blockquote></details>

done
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne7Po5I5IIbb7H3g1vV:-Ne7wQGm2tRcV20m9tXr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5526bbe51bb2acc2aadba4549c37b32a3be3830f/crates/papyrus_common/src/transaction_hash.rs#L84)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Split it between a description (with `//`) of this function and documentation of the public validate_transaction_hash function.
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne7Qb1MEDJ1GfxqfGmT:-Ne7ulMgCEdaKSsqefRn:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/5526bbe51bb2acc2aadba4549c37b32a3be3830f/crates/papyrus_common/src/transaction_hash.rs#L90)):*
> ```XML
>     transaction: &Transaction,
> ) -> Result<Vec<TransactionHash>, StarknetApiError> {
>     let possible_hashes = if chain_id == &ChainId("SN_MAIN".to_string())
> ```

done
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne33zAfCr12MZngpJos:-Ne3NDPzCORniHiiy4eW:b-975mkr) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash_test.rs#L53)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Is it the block number of all the transactions in the test?
</blockquote></details>

you're right I'll get the correct one.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-Ne349qW5ZbQ9OYao0ne:-Ne3PyZg4Hj7_kqGO-B4:b-urb88d) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2d26c7cf56ad38d1c40afeef6a75c3747a0b6c9/crates/papyrus_common/src/transaction_hash_test.rs#L83)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The same question.
</blockquote></details>

same answer

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 78 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1156#-NeD7PpG6EqyY6Z63dHG:-NeD7PpG6EqyY6Z63dHH:b-959jw9) ([raw file](https://github.com/starkware-libs/papyrus/blob/9abe6f163a63808d5cdfe1a6a233b0b615323908/crates/papyrus_common/src/transaction_hash.rs#L78)):*
> ```XML
> 
> /// On mainnet, from this block number onwards, the transaction hash can be directly determined
> /// based on the transaction version.
> ```

Consider 
On mainnet, from this block number onwards, there are no deprecated transaction hashes and we can only check the up-to-date transaction hash

**Review by yoavGrs — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
