### PR TITLE
Add to load_test gateway functions (without adding or changing scenar…

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
…ios).

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMbwaMU5Ql0Oz0S0ILS:-NMbwaMV9JhaVnaBtMe9:b-ggvfwk) (no related file):*
I didn't add a function for get_event because the EventFilter object is too complex. I can add it, but it will be a little bit complex.
I didn't test the functions at all. a test can be to build a load test with each function and check if the test fails.
maybe we should move all those functions to a different file. 

___
___
*[`crates/papyrus_load_test/src/main.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMZNPUb7T124VD3N0qw:-NMZNPUc2h_4gvtp-405:b6tcxw2) ([raw file](https://github.com/starkware-libs/papyrus/blob/20628b973d0ea05be7ed8cf0924b91fa5bd9ddbe/crates/papyrus_load_test/src/main.rs#L164)):*
> ```XML
>     user: &mut GooseUser,
>     block_number: u64,
>     index: u64,
> ```

Maybe using usize like in the original function will be better.

**Comment by anatgstarkware** [comment]
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I didn't add a function for get_event because the EventFilter object is too complex. I can add it, but it will be a little bit complex.
I didn't test the functions at all. a test can be to build a load test with each function and check if the test fails.
maybe we should move all those functions to a different file. 
</blockquote></details>

You can have an `EventFilter` with just `chunk_size`

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_load_test/src/main.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMhS4qaC08NgQWZT8pI:-NMhS4qaC08NgQWZT8pJ:btxzb2f) ([raw file](https://github.com/starkware-libs/papyrus/blob/3281e03d937d5b4028f3c88036e07b888230d272/crates/papyrus_load_test/src/main.rs#L49)):*
> ```XML
> async fn loadtest_get_block_with_tx_hashes_by_hash(user: &mut GooseUser) -> TransactionResult {
>     // TODO(shahak): Get a hash by getting a block instead of relying on that this hash exists.
>     let _: serde_json::Value = get_block_w_tx_hashes_by_hash(
> ```

w -> with
___
*[`crates/papyrus_load_test/src/main.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMhVi4T4LlSNRSIMrn6:-NMhVi4T4LlSNRSIMrn7:b-2lnmgq) ([raw file](https://github.com/starkware-libs/papyrus/blob/3281e03d937d5b4028f3c88036e07b888230d272/crates/papyrus_load_test/src/main.rs#L58)):*
> ```XML
> 
> /////////////////////////////////////////////////////////////////////
> // functions for gateways requests
> ```

This gets to the point where one file isn't enough
Instead of making comments like this, create a file for each group of functions/scenarios. I'll continue the review after this change as it will be more clearer to review this way

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_load_test/src/main.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMhS4qaC08NgQWZT8pI:-NMhpQrDBPRJdoKcLszH:bpqe8y1) ([raw file](https://github.com/starkware-libs/papyrus/blob/3281e03d937d5b4028f3c88036e07b888230d272/crates/papyrus_load_test/src/main.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

w -> with
</blockquote></details>

the reason i changed it is to match the function name from the gateway api
___
*[`crates/papyrus_load_test/src/main.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NMhVi4T4LlSNRSIMrn6:-NMhpssz0lIyjaN-HJ3C:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/3281e03d937d5b4028f3c88036e07b888230d272/crates/papyrus_load_test/src/main.rs#L58)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This gets to the point where one file isn't enough
Instead of making comments like this, create a file for each group of functions/scenarios. I'll continue the review after this change as it will be more clearer to review this way
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 7 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGBwfh7s0Kbvz_dnqd:-NNGBwfh7s0Kbvz_dnqe:btmyrvo) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/gateway_functions.rs#L7)):*
> ```XML
> type MethodResult<T> = Result<T, Box<TransactionError>>;
> 
> async fn post_jsonrpc_request<T: DeserializeOwned>(
> ```

These two should be in a utility file
___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGC-8BBD4-tnYGKgU0:-NNGC-8C8EuogNKcZOlO:bnpdg6c) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/gateway_functions.rs#L33)):*
> ```XML
> }
> 
> /////////////////////////////////////////////////////////////
> ```

No need for this comment
___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGDa3f9pBdO965lXxx:-NNGDa3f9pBdO965lXxy:b-ew24js) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/gateway_functions.rs#L43)):*
> ```XML
> 
> // block_hash_and_number
> pub async fn get_block_hash_and_number<T: DeserializeOwned>(
> ```

This file is still enormous.
WDYT about creating the following files:
get_block_scenarios
get_storage_scenarios
get_transaction_scenarios
get_transaction_count_scenarios (can be united with some other file)
get_state_diff_scenarios
get_nonce_scenarios (can be united with some other file)
___
*[`crates/papyrus_load_test/src/main.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGCbTQ2RGN8pB3w3T2:-NNGCbTQ2RGN8pB3w3T3:b-1ectvc) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/main.rs#L17)):*
> ```XML
> use serde::Serialize;
> 
> async fn loadtest_get_block_with_tx_hashes_by_number(user: &mut GooseUser) -> TransactionResult {
> ```

Move this to the other file
___
*[`crates/papyrus_load_test/src/main.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGCOxG35zXcdTUzxVz:-NNGCOxG35zXcdTUzxW-:b-549sw3) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/main.rs#L39)):*
> ```XML
>                 .register_transaction(transaction!(loadtest_get_block_with_tx_hashes_by_number)),
>         )
>         .register_scenario(
> ```

You forgot to register the rest of the scenarios. Is this intentional?
Also, writing down all the scenarios here will beat the purpose of splitting to files
I suggest writing a utility function that receives a vector of scenarios and a goose object by ref and adds the scenarios to the object. You can then either create a scenarios vector in each file or create a load scenarios function for each file. If you go with the latter, you can skip writing the utility function if you prefer

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 7 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGBwfh7s0Kbvz_dnqd:-NNGIFaq-pXC0OZJInmT:b-v5cp4x) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/gateway_functions.rs#L7)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These two should be in a utility file
</blockquote></details>

Oops. Didn't see you already did this

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/475)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_load_test/src/gateway_functions.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/475#-NNGDa3f9pBdO965lXxx:-NNGIZZ-DBIgeSKU3YzN:b-day9ap) ([raw file](https://github.com/starkware-libs/papyrus/blob/94fc7a1cdbe1a802ecfbbea6fe9dbb5c813e6cc4/crates/papyrus_load_test/src/gateway_functions.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This file is still enormous.
WDYT about creating the following files:
get_block_scenarios
get_storage_scenarios
get_transaction_scenarios
get_transaction_count_scenarios (can be united with some other file)
get_state_diff_scenarios
get_nonce_scenarios (can be united with some other file)
</blockquote></details>

If you disagree, at least rename this file to scenarios

**Pull request closed without merging**
