### PR TITLE
chore(execution): bump blockifier and SN API

### PR DESCRIPTION
**Pull request by giladchase**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1367)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1367)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`Cargo.lock` line 40 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-Nidz6PP8FrPrB8jdRqA:-Nidz6PP8FrPrB8jdRqB:b-fosi3l) ([raw file](https://github.com/starkware-libs/papyrus/blob/144522e71b9edcebff9ca94fcb338d84d200460c/Cargo.lock#L40)):*
> ```TOML
>  "cpufeatures",
> ]
> ```

Can we avoid the update?
___
*[`crates/papyrus_execution/src/lib.rs` line 217 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-NiduqJw8oz4wxsWZYCu:-NiduqJw8oz4wxsWZYCv:b-6u06li) ([raw file](https://github.com/starkware-libs/papyrus/blob/2adbdb3d984d3c84039974891f0afe519c74770a/crates/papyrus_execution/src/lib.rs#L217)):*
> ```XML
>     let mut context = EntryPointExecutionContext::new_invoke(
>         &block_context,
>         &AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default()),
> ```

Please add TODO(yair): fix when supporting v3 transactions



_Code quote:_
```XML
 &AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default()),
```
___
*[`crates/papyrus_execution/src/lib.rs` line 495 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-NidtYmp0wtltGV_4Z4Y:-NidtYmp0wtltGV_4Z4Z:b-ho6459) ([raw file](https://github.com/starkware-libs/papyrus/blob/2adbdb3d984d3c84039974891f0afe519c74770a/crates/papyrus_execution/src/lib.rs#L495)):*
> ```XML
>             None,
>             None,
>             false,
> ```

Please add TODO(yair): support only_query version bit (enable in the RPC v0.6 and use the correct value)
Also please use const var instead of hard-coded false



_Code quote:_
```XML
 false,
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r9, 1 of 1 files at r12, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1367)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1367)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`Cargo.lock` line 40 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-Nidz6PP8FrPrB8jdRqA:-Nie0zC93hNmqa3J8t_a:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/144522e71b9edcebff9ca94fcb338d84d200460c/Cargo.lock#L40)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we avoid the update?
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 495 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-NidtYmp0wtltGV_4Z4Y:-Nie1eSJEFwhL2TQE9nP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2adbdb3d984d3c84039974891f0afe519c74770a/crates/papyrus_execution/src/lib.rs#L495)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add TODO(yair): support only_query version bit (enable in the RPC v0.6 and use the correct value)
Also please use const var instead of hard-coded false
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1367#-:-NieHSEx7jbLYuipovmx:bnfp4nl)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
