### PR TITLE
release: adjust DeployAccount transaction to V3 changes in starknet-api

### PR DESCRIPTION
**Pull request by barak-b-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2MXJGAZSjeK9FO5vp:-Ne2MXJGAZSjeK9FO5vq:b-wvfqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L229)):*
> ```XML
>                 }
>                 starknet_api::transaction::DeployAccountTransaction::V3(_) => {
>                     Err(internal_server_error("Version 3 transactions are not supported on v0.3.0"))
> ```

Same as previous PR
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2MaTP48mT903alTV5:-Ne2MaTP48mT903alTV6:b-wvfqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L251)):*
> ```XML
>                     }
>                     starknet_api::transaction::DeployAccountTransaction::V3(_) => Err(
>                         internal_server_error("Version 3 transactions are not supported on v0.4.0"),
> ```

Same as previous PR
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2Mis43DJmaURhLRXG:-Ne2Mis43DJmaURhLRXH:biw7iae) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/starknet_client/src/reader/objects/transaction.rs#L327)):*
> ```XML
>         match deploy_account_tx.version {
>             v if v == *TX_V1 => Ok(Self::V1(deploy_account_tx.try_into()?)),
>             v if v == *TX_V3 => Ok(Self::V3(deploy_account_tx.try_into()?)),
> ```

Consider adding a comment why there's no v2

**Comment by ShahakShama** [comment]
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2QEtA82UVO-Yywpx7:-Ne2QEtA82UVO-Yywpx8:bmajb7x) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/starknet_client/src/writer/objects/transaction.rs#L114)):*
> ```XML
> }
> 
> /// A deploy account transaction that can be added to Starknet through the Starknet gateway.
> ```

Add a TODO on me to add tests for deploy account v3

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: 3 of 15 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @elintul, and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2MXJGAZSjeK9FO5vp:-Ne2wGdeDUoFxaWkfti4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L229)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as previous PR
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2MaTP48mT903alTV5:-Ne2wswaEOJ1MQFQeNc3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L251)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as previous PR
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne2QEtA82UVO-Yywpx7:-Ne3IvBEAj_8kRondVmx:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/209d772463b858e5fa969ec1848e48512246f947/crates/starknet_client/src/writer/objects/transaction.rs#L114)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO on me to add tests for deploy account v3
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-:-Ne3K2MID_asRGKjd719:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne7cspa0htbqId54_MI:-Ne7cspa0htbqId54_MJ:br8lafz) ([raw file](https://github.com/starkware-libs/papyrus/blob/560284315eb0f47fa951b9ab781374c0abedde2c/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L114)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct DeployAccountTransactionV1 {
> ```

Isn't there a struct for DeployAccountTransactionV1 in starknet_api?
___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne7d_0Y3KIu5WmZNEGI:-Ne7d_0Y3KIu5WmZNEGJ:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/560284315eb0f47fa951b9ab781374c0abedde2c/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L119)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct DeployAccountTransactionV1 {
> ```

Same here

**Comment by barak-b-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-Ne7cspa0htbqId54_MI:-Ne7igCI2Xa331rDFYpQ:bkalhi8) ([raw file](https://github.com/starkware-libs/papyrus/blob/560284315eb0f47fa951b9ab781374c0abedde2c/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L114)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Isn't there a struct for DeployAccountTransactionV1 in starknet_api?
</blockquote></details>

There is but this one includes the `version` field.
There might be some more elegant way to do that but the convention in this file is to "recreate" the structs, look for example on Declare versions (almost copy-paste from starknet_api, except for the version field):



_Code quote:_
```XML
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
#[serde(deny_unknown_fields)]
pub struct DeclareTransactionV0V1 {
    pub class_hash: ClassHash,
    pub sender_address: ContractAddress,
    pub nonce: Nonce,
    pub max_fee: Fee,
    pub version: TransactionVersion,
    pub signature: TransactionSignature,
}
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct DeclareTransactionV2 {
    pub class_hash: ClassHash,
    pub compiled_class_hash: CompiledClassHash,
    pub sender_address: ContractAddress,
    pub nonce: Nonce,
    pub max_fee: Fee,
    pub version: TransactionVersion,
    pub signature: TransactionSignature,
}
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-:-Ne7lGwV9SvP3So7htRx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: 9 of 17 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 456 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeD9J3s-Upfeoctp8xp:-NeD9J3t-ECIqMU1ndFl:b-qy9zdu) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6c31d3dabeff609ae78f437e28a9f30ccbbee55/crates/papyrus_common/src/transaction_hash.rs#L456)):*
> ```XML
>     chain_id: &ChainId,
> ) -> Result<TransactionHash, StarknetApiError> {
>     let contract_address = calculate_contract_address(
> ```

Comment and change to unimplemented!();
___
*[`crates/papyrus_rpc/src/v0_3_0/transaction.rs` line 149 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeD9q8w8OD-1qx8sJpb:-NeD9q8w8OD-1qx8sJpc:b-xsdj3x) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6c31d3dabeff609ae78f437e28a9f30ccbbee55/crates/papyrus_rpc/src/v0_3_0/transaction.rs#L149)):*
> ```XML
>                 version: tx_v1(),
>             })),
>             starknet_api::transaction::DeployAccountTransaction::V3(_) => {
> ```

Add TODO on me to test this (no need to add unimplemented!())
___
*[`crates/papyrus_storage/src/serializers.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeD9UIE1oc08X5nPA8R:-NeD9UIE1oc08X5nPA8S:b-nykysq) ([raw file](https://github.com/starkware-libs/papyrus/blob/0fc7c010b09ef2334a46810aa99fe2d1cc2e2938/crates/papyrus_storage/src/serializers.rs#L198)):*
> ```XML
>         pub account_deployment_data: AccountDeploymentData,
>     }
>     pub enum DeployAccountTransaction {
> ```

Increase the storage version (ask @dan-starkware how to do that)
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 298 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeDBGew32G4HXX5EXRn:-NeDBGew32G4HXX5EXRo:bakkiwo) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6c31d3dabeff609ae78f437e28a9f30ccbbee55/crates/starknet_client/src/reader/objects/transaction.rs#L298)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Clone, Eq, PartialEq)]
> #[serde(deny_unknown_fields)]
> pub struct IntermediateDeployAccountTransaction {
> ```

Add a TODO to add serde tests for v3 on me
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 327 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeDB7zE0KrGXjV5Bt0h:-NeDB7zE0KrGXjV5Bt0i:b-a5kotg) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6c31d3dabeff609ae78f437e28a9f30ccbbee55/crates/starknet_client/src/reader/objects/transaction.rs#L327)):*
> ```XML
>             // Since v3 transactions, all transaction types are aligned with respect to the version,
>             // v2 was skipped in the Deploy Account type.
>             v if v == *TX_V3 => Ok(Self::V3(deploy_account_tx.try_into()?)),
> ```

I see this code is not tested at all, so just put a TODO on top of the TryFrom to add tests (put it on me)
___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 242 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeDA1EG4BOHmhXBOk42:-NeDA1EG4BOHmhXBOk43:b-qy9zdu) ([raw file](https://github.com/starkware-libs/papyrus/blob/c6c31d3dabeff609ae78f437e28a9f30ccbbee55/crates/starknet_client/src/writer/objects/transaction.rs#L242)):*
> ```XML
>             }
>             starknet_api::transaction::DeployAccountTransaction::V3(tx) => {
>                 DeployAccountTransaction::DeployAccountV3(DeployAccountV3Transaction {
> ```

Comment and change to unimplemented!();

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: 9 of 17 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @elintul)

___
*[`crates/papyrus_storage/src/serializers.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/1144#-NeD9UIE1oc08X5nPA8R:-NeDCYda6g9xLMuukK9p:b-mw2gd8) ([raw file](https://github.com/starkware-libs/papyrus/blob/0fc7c010b09ef2334a46810aa99fe2d1cc2e2938/crates/papyrus_storage/src/serializers.rs#L198)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Increase the storage version (ask @dan-starkware how to do that)
</blockquote></details>

This is relevant only to the deploy account PR

**Review by ShahakShama — APPROVED** [review]
> Reviewed 4 of 8 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1144)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

**Pull request closed without merging**
