### PR TITLE
fix(JSON-RPC): validate in execution that the block wasnt reverted mid-execution

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1507)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1507)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4/block.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1507#-Nlc4XBR90sgVIOwYY93:-Nlc4XBR90sgVIOwYY94:b2ni1ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecfaf1f3b57cd3e7c129417beecdee48efa8d1a6/crates/papyrus_rpc/src/v0_4/block.rs#L118)):*
> ```XML
> }
> 
> impl BlockNotRevertedValidator {
> ```

doc
___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 818 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1507#-Nlc419C6sESRHdB1Q58:-Nlc419C6sESRHdB1Q59:bf7l2ar) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecfaf1f3b57cd3e7c129417beecdee48efa8d1a6/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L818)):*
> ```XML
>         };
>         let block_number = get_accepted_block_number(&txn, block_id)?;
>         let block_not_reverted_validator = BlockNotRevertedValidator::new(block_number, &txn)?;
> ```

Consider doing something like:
```
BlockNotRevertedValidator::run_and_validate(block_number, &txn, || {...}).await?;
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1507)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/api/api_impl.rs` line 818 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1507#-Nlc419C6sESRHdB1Q58:-NlqZ0RZEzyV-fVP0KY8:b-v42sy9) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecfaf1f3b57cd3e7c129417beecdee48efa8d1a6/crates/papyrus_rpc/src/v0_4/api/api_impl.rs#L818)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider doing something like:
```
BlockNotRevertedValidator::run_and_validate(block_number, &txn, || {...}).await?;
```
</blockquote></details>

That ruins the concept of the struct. I prefer the current way

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1507)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4/block.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1507#-Nlc4XBR90sgVIOwYY93:-NlqZ8w248SEMEi-mZ_e:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ecfaf1f3b57cd3e7c129417beecdee48efa8d1a6/crates/papyrus_rpc/src/v0_4/block.rs#L118)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1507)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
