### PR TITLE
feat(starknet_client): client's Block supports v0.13 blocks

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(starknet_client): rename block.json to block_pre_v0_13.json
- feat(starknet_client): client's Block supports v0.13 blocks

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/starknet_client/resources/reader/block.json` line 0 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIpdbZBI7zg84faWFf:-NjIpdbZBI7zg84faWFg:b5l1nis) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/resources/reader/block.json#L0)):*
Why is it not recognized as a new file? Did you run `mv` instead of `git mv`?
___
*[`crates/starknet_client/src/reader/objects/block.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIqA0VEJtufD-d235l:-NjIqA0VEJtufD-d235m:b-7qsulu) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block.rs#L38)):*
> ```XML
>     pub eth_l1_gas_price: GasPrice,
>     #[serde(default)]
>     pub strk_l1_gas_price: GasPrice,
> ```

I think this should be an option.



_Code quote:_
```XML
    #[serde(default)]
    pub strk_l1_gas_price: GasPrice,
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIqbgn1aElcn1lSBAa:-NjIqbgn1aElcn1lSBAb:b74kfhs) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block_test.rs#L28)):*
> ```XML
> fn load_block_succeeds() {
>     for block_path in ["reader/block.json", "reader/block_pre_v0_13.json"] {
>         serde_json::from_str::<Block>(&read_resource_file(block_path)).unwrap();
> ```

Please use expect and add the file path to the message.



_Code quote:_
```XML
.unwrap();
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIrDVI--yFp7c5o3_G:-NjIrDVI--yFp7c5o3_H:bj7g1nw) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block_test.rs#L165)):*
> ```XML
> 
>     let mut err_block: Block = serde_json::from_str(&raw_block).unwrap();
>     err_block.transaction_receipts[0] = TransactionReceipt {
> ```

What changed here?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_client/resources/reader/block.json` line  at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIpdbZBI7zg84faWFf:-NjIwPd6AerwuRVXaoq6:b-678nvb) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/resources/reader/block.json#L)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it not recognized as a new file? Did you run `mv` instead of `git mv`?
</blockquote></details>

I ran git mv. IDK why. that's why I splitted it to two commits
___
*[`crates/starknet_client/src/reader/objects/block.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIqA0VEJtufD-d235l:-NjIwXoQCHE-Vu202zHI:bjgzw8k) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block.rs#L38)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this should be an option.
</blockquote></details>

That's what v0.13 does for old blocks, it puts 0
And this field is present for all blocks in v0.13, unlike the other fields here.
If we put this an Option then it will be with a TODO to return to not option once all environments are 0.13
@dan-starkware WDYT?
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIqbgn1aElcn1lSBAa:-NjJ-M9qAKz2ZlTzRagr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block_test.rs#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use expect and add the file path to the message.
</blockquote></details>

Done.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIrDVI--yFp7c5o3_G:-NjIxJXZDI9QIUOP0SLw:byc4407) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block_test.rs#L165)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What changed here?
</blockquote></details>

This test relied heavily on the structure of the block
It tested an error where the receipt is of L1_HANDLER and the transaction is not L1_HANDLER
Because I didn't want to wait until there will be a 0.13 block with l1_hander, and because I think this test should test a less isoteric error, I changed it to test the error where the hash in the receipt is incorrect

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-:-NjJDCOV4L08Rrb0aoSi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/starknet_client/src/reader/objects/block.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1415#-NjIqA0VEJtufD-d235l:-NjJChnxAaQQDD3TEFwW:btz69ax) ([raw file](https://github.com/starkware-libs/papyrus/blob/96e07de40a670df3b692c19ee7d4c54e8183846f/crates/starknet_client/src/reader/objects/block.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

That's what v0.13 does for old blocks, it puts 0
And this field is present for all blocks in v0.13, unlike the other fields here.
If we put this an Option then it will be with a TODO to return to not option once all environments are 0.13
@dan-starkware WDYT?
</blockquote></details>

Oh if you put 0 then it's correct as is

**Review by yair-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
