### PR TITLE
feat(common): calculate deploy transaction hash

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgCZh-kDv4Bah1OFr:-NczgCZh-kDv4Bah1OFs:bddt9nh) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L22)):*
> ```XML
> 
> /// Calculates hash of a Starknet transaction.
> pub fn get_tx_hash(tx: &Transaction, chain_id: &ChainId) -> Result<StarkHash, StarknetApiError> {
> ```

We do not use short names in code. Change to get_transaction_hash
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczf4lh5YfXJmc_GZzL:-Nczf4lh5YfXJmc_GZzM:b-pb5mxk) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L35)):*
> ```XML
> 
> /// Validates hash of a starknet transaction.
> /// A hash is valid if it is obtained from a hash calculation that was ever used in Starknet.
> ```

Consider instead
/// A hash is valid if it is the result of one of the hash functions that were ever used in Starknet
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczdqqf25Et7qHpTSfO:-Nczdqqf25Et7qHpTSfP:bh1jqo3) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L125)):*
> ```XML
> }
> 
> fn get_deploy_transaction_hash(
> ```

deploy is deprecated. So it's a bit confusing to have a non-deprecated and deprecated hash. Is there a version for each hash and then maybe we'll rename the functions to get_deploy_transaction_hash_v0/v1
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgKAgEonwfi7ATYiJ:-Nczg7th-BNwhNobum_c:b-1iblg5) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L21)):*
> ```XML
> 
> #[derive(Deserialize, Serialize)]
> struct TxWithHash {
> ```

We do not use short names in code. Change to TransactionWithHash and change all the variables/members/file_names here to not include tx (I Forgot to say this in the previous PR)
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczfsX9EBD2Q14houAL:-NczfsX9EBD2Q14houAM:b-b0hf7y) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L24)):*
> ```XML
>     tx: Transaction,
>     tx_hash: StarkHash,
>     is_deprecated: bool,
> ```

Remove this field. Instead, have a different file for each transaction and you'll know that the transaction in deprecated_deploy.json is deprecated
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczfi9O9XjHVFCz4PAD:-Nczfi9O9XjHVFCz4PAE:b-pt9ccc) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L30)):*
> ```XML
> fn test_transaction_hash() {
>     // The tx details were taken from
>     // https://alpha4.starknet.io/feeder_gateway/get_block?blockNumber=385429
> ```

You can also add the transaction index in the block
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgcKI-0H82UMWBYWw:-NczgcKI-0H82UMWBYWx:b-dda3fl) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L37)):*
> ```XML
>     let file = std::fs::File::open(file_path).unwrap();
>     let reader = BufReader::new(file);
>     let txs_with_hash: Vec<TxWithHash> = serde_json::from_reader(reader).unwrap();
> ```

Use read_json_file instead (in crate test_utils)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgCZh-kDv4Bah1OFr:-Nczzrh4AKAcl5SfcFW_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We do not use short names in code. Change to get_transaction_hash
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczf4lh5YfXJmc_GZzL:-NczzytlCOOE7oukZxUI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider instead
/// A hash is valid if it is the result of one of the hash functions that were ever used in Starknet
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczdqqf25Et7qHpTSfO:-Nd--LXC-8W6V7v5cNwt:be1r3b1) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L125)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

deploy is deprecated. So it's a bit confusing to have a non-deprecated and deprecated hash. Is there a version for each hash and then maybe we'll rename the functions to get_deploy_transaction_hash_v0/v1
</blockquote></details>

Both variants are in version 0.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgKAgEonwfi7ATYiJ:-Nd-8tBRDKoV3E2Xggiy:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L21)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We do not use short names in code. Change to TransactionWithHash and change all the variables/members/file_names here to not include tx (I Forgot to say this in the previous PR)
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczfsX9EBD2Q14houAL:-Nd-8vVG27J-xjdacisq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this field. Instead, have a different file for each transaction and you'll know that the transaction in deprecated_deploy.json is deprecated
</blockquote></details>

Done.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczfi9O9XjHVFCz4PAD:-Nd-Ac2tESmeyXIQOUju:b-a2ujfl) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can also add the transaction index in the block
</blockquote></details>

Changed.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-NczgcKI-0H82UMWBYWw:-Nd-AeWNDWFECo3LyR1D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash_test.rs#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use read_json_file instead (in crate test_utils)
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczdqqf25Et7qHpTSfO:-Nd-HlsuByC2pT4HfI_s:b6wpzqd) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L125)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Both variants are in version 0.
</blockquote></details>

Then keep it as it was (deprecated and not deprecated)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1114#-Nczdqqf25Et7qHpTSfO:-Nd-L03i2P9YWsjw36W6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/6133bea690aaea572c26c91020072a93cedbb36b/crates/papyrus_common/src/transaction_hash.rs#L125)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Then keep it as it was (deprecated and not deprecated)
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
