### PR TITLE
Dvir/deploy trans contract address location

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: 0 of 12 files reviewed, 5 unresolved discussions

___
*[`Cargo.toml` line 80 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TWCzBA2Ziu-vQSGwO:-N_TWCzBA2Ziu-vQSGwP:br0at7) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/Cargo.toml#L80)):*
> ```TOML
> simple_logger = "4.0.0"
> # starknet_api = "0.2.0"
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "6e2dda22208e028aff778e449ac467012a08fcec" }
> ```

I will change this after 
https://reviewable.io/reviews/starkware-libs/starknet-api/95
 merges.
___
*[`crates/papyrus_gateway/src/v0_3_0/transaction.rs` line 300 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TXJZg6l7VgamQ3MN3:-N_TXJZg6l7VgamQ3MN4:b-kfsizn) ([raw file](https://github.com/starkware-libs/papyrus/blob/f0b11548e79d2082a593675cc5f024a76caad027/crates/papyrus_gateway/src/v0_3_0/transaction.rs#L300)):*
> ```XML
>     pub receipt: TransactionReceipt,
> }
> ```

Now that the contract address includes in the transaction's output, it makes all the TransactionReceipt be with the same structure and makes things cleaner.
___
*[`crates/papyrus_gateway/src/v0_3_0/transaction.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TY2iV5v2xReNSGBg_:-N_TY2iV5v2xReNSGBga:b-xlyvs1) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/papyrus_gateway/src/v0_3_0/transaction.rs#L311)):*
> ```XML
> }
> 
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> ```

The change is to make it deserialize correctly (we deserialize this struct only in tests); before that, the enum "TransactionReceipt" that was deleted does that. I will try to make it nicer in a different pull request.
___
*[`crates/papyrus_gateway/src/v0_3_0/transaction_test.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TWRg77U8vowwffK-h:-N_TWRg77U8vowwffK-i:beyy8fb) ([raw file](https://github.com/starkware-libs/papyrus/blob/f0b11548e79d2082a593675cc5f024a76caad027/crates/papyrus_gateway/src/v0_3_0/transaction_test.rs#L98)):*
> ```XML
> }
> 
> macro_rules! test_recipe_from_transtaction_output {
> ```

This test is for a function that doesn't exists anymore.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TWduy2tQM7C-L-1hm:-N_TWduy2tQM7C-L-1hn:bggvgrx) ([raw file](https://github.com/starkware-libs/papyrus/blob/f0b11548e79d2082a593675cc5f024a76caad027/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L209)):*
> ```XML
>         let block_number = transaction_index.0;
>         let status = get_block_status(&txn, block_number)?;
>         let header: BlockHeader =
> ```

Now we need only the block hash and not all the header or the transaction object.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`Cargo.toml` line 80 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TWCzBA2Ziu-vQSGwO:-N_UN1SMDG6PoliIRdQS:bcnbcfm) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/Cargo.toml#L80)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I will change this after 
https://reviewable.io/reviews/starkware-libs/starknet-api/95
 merges.
</blockquote></details>

Adding a blocking comment to avoid mistakes
___
*[`crates/papyrus_gateway/src/v0_3_0/transaction.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TY2iV5v2xReNSGBg_:-N_UOQue6NrUHBjV6yl-:b-ts2xqq) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/papyrus_gateway/src/v0_3_0/transaction.rs#L311)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

The change is to make it deserialize correctly (we deserialize this struct only in tests); before that, the enum "TransactionReceipt" that was deleted does that. I will try to make it nicer in a different pull request.
</blockquote></details>

Can we remove the untagged attribute and use the type as a tag?
___
*[`crates/starknet_reader_client/src/objects/transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_VCdPu1WHNvQWOunLt:-N_VCdPu1WHNvQWOunLu:bi2f6n6) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/starknet_reader_client/src/objects/transaction.rs#L80)):*
> ```XML
>     }
> 
>     pub fn contract_address(&self) -> Option<ContractAddress> {
> ```

Do we really want this function?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/transaction.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_TY2iV5v2xReNSGBg_:-N_XOT_e0IhnGU1dq0Fb:bxri4yj) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/papyrus_gateway/src/v0_3_0/transaction.rs#L311)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we remove the untagged attribute and use the type as a tag?
</blockquote></details>

This is what I plan to do.
___
*[`crates/starknet_reader_client/src/objects/transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_VCdPu1WHNvQWOunLt:-N_XOPZ10P8sHiM6_Lx9:b2nign6) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/starknet_reader_client/src/objects/transaction.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do we really want this function?
</blockquote></details>

yes

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_reader_client/src/objects/transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_VCdPu1WHNvQWOunLt:-N_YsdSH6RGJVlX3PtWI:b-8h07wg) ([raw file](https://github.com/starkware-libs/papyrus/blob/de90eeb317e96518c0af2207c34acba1f8737e7b/crates/starknet_reader_client/src/objects/transaction.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why? 
</blockquote></details>

Because I need this information in "into_starknet_api_transaction_output" and  I don't want to do that logic there because it is dependent only on the transaction structure.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`Cargo.toml` line 79 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/858#-N_YwT3079e806wJxiXO:-N_YwT31DY5sFqzRB4hW:bxqpbro) ([raw file](https://github.com/starkware-libs/papyrus/blob/3959c0ef934720837c67c0ba5cb487ef68fdd088/Cargo.toml#L79)):*
> ```TOML
> serde_yaml = "0.9.16"
> simple_logger = "4.0.0"
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "998099c7cc5be13ba3d0a985df3b77b2afd93ab4" }
> ```

This is the commit after the merge to starknet-api.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/858)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

**Pull request merged**
