### PR TITLE
move and finalize

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/704)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #698** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/698" target="_blank">Graphite</a> 
    * **PR #699** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/699" target="_blank">Graphite</a> 
      * **PR #700** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/700" target="_blank">Graphite</a> 
        * **PR #701** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/701" target="_blank">Graphite</a> 
          * **PR #702** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/702" target="_blank">Graphite</a> 
            * **PR #703** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/703" target="_blank">Graphite</a> 
              * **PR #704** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/704" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/704?utm_source=stack-comment).

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #698** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/698" target="_blank">Graphite</a> 
    * **PR #699** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/699" target="_blank">Graphite</a> 
      * **PR #700** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/700" target="_blank">Graphite</a> 
        * **PR #701** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/701" target="_blank">Graphite</a> 
          * **PR #702** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/702" target="_blank">Graphite</a> 
            * **PR #703** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/703" target="_blank">Graphite</a> 
              * **PR #704** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/704" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/704?utm_source=stack-comment).

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/704)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/api/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/704#-NWkTedM1EtmtVndiv3L:-NWkTedNB4qiA_zpHL4m:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/99989d883f43732f9d168ed4d9971fabd68c0dff/crates/papyrus_gateway/src/api/mod.rs#L102)):*
> ```XML
> }
> 
> pub fn get_methods_from_supported_apis(
> ```

Please document.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/704)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
