### PR TITLE
add resources for Starknet Write Client

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/790)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/790)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/790#-NZ6a9bf41xFw5IqYPGY:-NZ6a9bf41xFw5IqYPGZ:bwphewx) (no related file):*
These are generated by the starknet simulator

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/790#-NZ6bY2k0vu4e7x7nOc9:-NZ6bY2k0vu4e7x7nOcA:bm1zf85) (no related file):*
I'll rename starknet_client to starknet_reader_client in a different PR

___

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/790)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`invoke.json` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/790#-NZKPjaEAbn7keV9wMwD:-NZKPjaF2x6SNV4tuqfH:bvdjcm) ([raw file](https://github.com/starkware-libs/papyrus/blob/45a880a19bed48e6669f01ea607d513029417066/invoke.json#L1)):*
> ```JSON
> {"version": "0x1", "max_fee": "0xde0b6b3a7640000", "signature": ["0xfdb1626b6acc48f92185e6018b577a51d540982883d53036977df9a08fb564", "0x37dabc3ef10428306a7ac9003d721bafdcda2b933f053c92ab6288d8408b1d9"], "nonce": "0x9", "sender_address": "0x219937256cd88844f9fdc9c33a2d6d492e253ae13814c2dc0ecab7f26919d46", "calldata": ["0x1", "0x12c3a0b15ef9bf39e03af3653ad1cff528cd32bd75167cdeb7615d8da93fd17", "0x27c3334165536f239cfd400ed956eabff55fc60de4fb56728b6a4f6b87db01c", "0x0", "0x7", "0x7", "0x12c3a0b15ef9bf39e03af3653ad1cff528cd32bd75167cdeb7615d8da93fd17", "0x2d7cf5d5a324a320f9f37804b1615a533fde487400b41af80f13f7ac5581325", "0x4", "0xe88ed417dee71cd1ebad48637002ebaa09b2fa00", "0x2", "0x1e8d90c08bb80f786f13eb48376bbb462d0bc09b9ccc69e9cda78192263dc4a", "0x1c190b4c7ce26ff28464062dd13641fb42cf9a075229d87e25674c6f2b57693"], "type": "INVOKE_FUNCTION"}
> ```

Why is this file not inside resources?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/790)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`invoke.json` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/790#-NZKPjaEAbn7keV9wMwD:-NZKQJIZ-EsMfbe-Bz36:bvki0p9) ([raw file](https://github.com/starkware-libs/papyrus/blob/45a880a19bed48e6669f01ea607d513029417066/invoke.json#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is this file not inside resources?
</blockquote></details>

My bad. I keep thinking git mv accepts as the 2nd argument the new name of the file and not the entire path for the file

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/790#-:-NZKQtH_9jOsRugwsTXw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
