### PR TITLE
feat(common): implementing cargo-chef in dockerfile for better dependencies layer caching

### PR DESCRIPTION
**Pull request by idan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2228)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2228)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @eranreshef-starkware)

**Review by eranreshef-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by eranreshef-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2228)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`Dockerfile` line 48 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2228#-O1vZoo4-vb-d8pM1-CA:-O1vZoo5EpA1_kG-K5TU:b-trjeo4) ([raw file](https://github.com/starkware-libs/papyrus/blob/f2735cce4e4d973960355089d1b19029b8c56eb3/Dockerfile#L48)):*
> ```Dockerfile
> ENV CARGO_INCREMENTAL=0
> 
> # Add the target for x86_64-unknown-linux-musl and compile papyrus_node.
> ```

the documentation here needs to change

**Review by eranreshef-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
