### PR TITLE
refactor(network): remove protobuf from network_manager test

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-Ul9Zd7HoXz1l98WdF:-O-Ul9Ze4XujGP9TsQdt:b-k9t86z) ([raw file](https://github.com/starkware-libs/papyrus/blob/927e7357c7a84ca6b995b7e3fc9c3cad9f3f876d/crates/papyrus_network/src/network_manager/test.rs#L121)):*
> ```XML
>                 signatures: vec![],
>             };
>             let data_bytes = Vec::<u8>::from(DataOrFin(Some(signed_header)));
> ```

I meant that you should not have headers at all here, just some random hardcoded vec<u8>

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-Ul9Zd7HoXz1l98WdF:-O-_GbdMEl-k_Uxtr7kG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/927e7357c7a84ca6b995b7e3fc9c3cad9f3f876d/crates/papyrus_network/src/network_manager/test.rs#L121)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I meant that you should not have headers at all here, just some random hardcoded vec<u8>
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aKamr4HylurvrmPWN:-O-aKamr4HylurvrmPWO:bxh00hs) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L95)):*
> ```XML
>     }
> 
>     fn create_received_data_events_for_input(
> ```

You can still call it query, just keep it Vec<u8>
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aKoNv51GOpWmX6sNr:-O-aKoNv51GOpWmX6sNs:bh5lrb5) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L95)):*
> ```XML
>     }
> 
>     fn create_received_data_events_for_input(
> ```

Add to the name of this function what it does
create_response_events_for_query_each_num_becomes_response
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aLjX00w2t6w08L7YJ:-O-aLjX00w2t6w08L7YK:b-rx5kxm) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L105)):*
> ```XML
>                     data: vec![data],
>                     outbound_session_id,
>                     peer_id: PeerId::random(),
> ```

Could you fix this on the way? you should receive peer_id from the caller (send_query. It has a peer_id argument)
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aLw-r8HYW4dx3jB4G:-O-aLw-r8HYW4dx3jB4H:b-vivl7w) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L257)):*
> ```XML
>         .take(VEC.len())
>         .map(|(i, (result, _report_callback))| {
>             let result = result.unwrap();
> ```

Add comment that this is how the mock swarm parses the query and sends responses to it

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aKoNv51GOpWmX6sNr:-O-aVWbh1EydkWk__oEu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L95)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add to the name of this function what it does
create_response_events_for_query_each_num_becomes_response
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aLjX00w2t6w08L7YJ:-O-aVWwOCozpx0ROAk_9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L105)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Could you fix this on the way? you should receive peer_id from the caller (send_query. It has a peer_id argument)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-O-aLw-r8HYW4dx3jB4G:-O-aVXLpAzEbRLM014z8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/df6753ba5560491e098f737cd1c1ffd399ec9486/crates/papyrus_network/src/network_manager/test.rs#L257)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add comment that this is how the mock swarm parses the query and sends responses to it
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2109#-:-O-iegMI6IksnCe0fcps:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
