### PR TITLE
chore(node): make get transaction hash example async

### PR DESCRIPTION
**Pull request by eitanm-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1959)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1959)* status: all files reviewed, 8 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGrU3j49nQyrWnpBPf:-NxGrU3kBJDxMghHo1ZU:bh1hclp) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L21)):*
> ```XML
> const DEFAULT_TRANSACTION_HASH_PATH: &str =
>     "crates/papyrus_common/resources/transaction_hash_new.json";
> const MAX_CONCURRENT_SPAWNS: u64 = 100;
> ```

add a new line between the consts and the struct
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGrkTmCtoRVUpWkl_1:-NxGrkTmCtoRVUpWkl_2:bijo0ef) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L27)):*
> ```XML
>     file_path: String,
>     deprecated: bool,
>     concurrent_spawns: u64,
> ```

change this to 'concurrent requests'. The fact that you are using spawn is an implementation detail; its meaning is the number of concurrent requests to the node.



_Code quote:_
```XML
concurrent_spawns
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGsgEV6ZDSGeM5AjQH:-NxGsgEW5p95slGxofr_:betxrfe) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L81)):*
> ```XML
>         .parse::<u64>()
>         .expect("Failed parsing iteration_increments");
>     let _concurrent_spawns = matches
> ```

remove the _ in the beginning



_Code quote:_
```XML
_concurrent_spawns
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxH6-P9BR_53ioUftBR:-NxH6-P9BR_53ioUftBS:b7jvro4) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L136)):*
> ```XML
> 
>     let transaction_types = Arc::new(Mutex::new(get_all_transaction_types()));
>     let acumulated_transactions = Arc::new(Mutex::new(vec![]));
> ```

consider using here once_cell/lazy_static to get rid of the Arc



_Code quote:_
```XML
    let transaction_types = Arc::new(Mutex::new(get_all_transaction_types()));
    let acumulated_transactions = Arc::new(Mutex::new(vec![]));
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGv2yB3-07KUO2sN_3:-NxGv2yB3-07KUO2sN_4:bnu77d7) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L143)):*
> ```XML
>     } else {
>         block_number_response
>     };
> ```

what is the reason for the changes here? it looks like they don't have something with the PR



_Code quote:_
```XML
    let block_number_response = get_current_block_number_via_rpc(&client, node_url.clone()).await?;
    let mut block_number: u64 = if deprecated {
        min(block_number_response, MAINNET_TRANSACTION_HASH_WITH_VERSION.0)
    } else {
        block_number_response
    };
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGyoMz2MWMF8fGn7qA:-NxGyoMz2MWMF8fGn7qB:b-9ggugc) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L147)):*
> ```XML
>     while block_number > 0
>         && !transaction_types.lock().expect("Couldn't lock transaction types").is_empty()
>     {
> ```

as far as I understand, `handles` length is equal to`concurrent_spawns`-`handles_counter`; why do you also need the `handles_counter`?
In addition, consider removing the explicit type for `handles`
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxH6qGvBd1F_Vd287T7:-NxH6qGvBd1F_Vd287T8:b15uo29) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L160)):*
> ```XML
>             let client_ref = client.clone();
>             let node_url_ref = node_url.clone();
>             let current_block_number = block_number;
> ```

consider removing this and using `block_number` instead



_Code quote:_
```XML
let current_block_number = block_number;
```
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGwkJ21GyzKxFQRpwo:-NxGwkJ21GyzKxFQRpwp:blc7nm6) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L162)):*
> ```XML
>             let current_block_number = block_number;
> 
>             let handle = tokio::spawn(async move {
> ```

what is the reason for using spawn instead of only futures?
It makes the code more complex and maybe even slower because of the overhead of handling different threads.
consider changing this.

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1959)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGrU3j49nQyrWnpBPf:-NxLuNsRBAS3ovybch63:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L21)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

add a new line between the consts and the struct
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGrkTmCtoRVUpWkl_1:-NxLuW0sCIQsX2d7S1yk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L27)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

change this to 'concurrent requests'. The fact that you are using spawn is an implementation detail; its meaning is the number of concurrent requests to the node.
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGsgEV6ZDSGeM5AjQH:-NxLuZWYDwaoiFH_v_id:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L81)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

remove the _ in the beginning
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGv2yB3-07KUO2sN_3:-NxMMt8AARlNa2nqOWTw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L143)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

what is the reason for the changes here? it looks like they don't have something with the PR
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGyoMz2MWMF8fGn7qA:-NxMNWsPDfqTyRnU07hZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L147)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

as far as I understand, `handles` length is equal to`concurrent_spawns`-`handles_counter`; why do you also need the `handles_counter`?
In addition, consider removing the explicit type for `handles`
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxH6qGvBd1F_Vd287T7:-NxN-kWe2Setw-ghoEm0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L160)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider removing this and using `block_number` instead
</blockquote></details>

Done.
___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxGwkJ21GyzKxFQRpwo:-NxN-lDH2KqXRHQIJpSt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/49aa9250abc2b4aee4986dc1fa720092facdd7cd/crates/papyrus_node/examples/get_transaction_hash.rs#L162)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

what is the reason for using spawn instead of only futures?
It makes the code more complex and maybe even slower because of the overhead of handling different threads.
consider changing this.
</blockquote></details>

Done.

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1959)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_node/examples/get_transaction_hash.rs` line 135 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1959#-NxN3VLxA7DmT21s0-26:-NxN5AyG4UwuLj_nfIMu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/73091d9541ee0d0752addcc3e9dd0bc51a9118a2/crates/papyrus_node/examples/get_transaction_hash.rs#L135)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why not just set? it shouldn't be init.
</blockquote></details>

Done.

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1959)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
