### PR TITLE
feat(JSON-RPC): add pending support for get_events with minimal test

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfYmzN7X_0yHgIcIBO:-NhfYmzN7X_0yHgIcIBP:btpl2uq) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L565)):*
> ```XML
>     // Can't have a different struct for pending events because then that struct will need to have
>     // deny_unknown_fields. And there's a bug in serde that forbids having deny_unknown_fields with
>     // flatten: https://github.com/serde-rs/serde/issues/1701
> ```

Consider using this struct as an intermediate for serde and converting it to and from an enum 
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfZqzJ6IdsXgHZ7ZOs:-NhfZqzJ6IdsXgHZ7ZOt:b-liae4w) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L591)):*
> ```XML
>         let txn = self.storage_reader.begin_ro_txn().map_err(internal_server_error)?;
>         let Some(latest_block_number) = get_latest_block_number(&txn)? else {
>             if matches!(filter.to_block, Some(BlockId::Tag(Tag::Pending)) | None) {
> ```

Why return this error in the case of None? The behavior seemed to return up to the latest block number.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 704 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nhfaw6v1Su8gEDXKrEs:-Nhfaw6v1Su8gEDXKrEt:b-f7xlk6) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L704)):*
> ```XML
>                     }) {
>                         continue;
>                     }
> ```

What is this check?



_Code quote:_
```XML
                    if !filter.keys.iter().enumerate().all(|(i, keys)| {
                        event.content.keys.len() > i
                            && (keys.is_empty() || keys.contains(&event.content.keys[i]))
                    }) {
                        continue;
                    }
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 707 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfbCis92-CkLsBh4zZ:-NhfbCis92-CkLsBh4z_:byqokq6) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L707)):*
> ```XML
>                     if let Some(filter_address) = filter.address {
>                         if event.from_address != filter_address {
>                             break;
> ```

Shouldn't this be `continue`?



_Code quote:_
```XML
break;
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfbgkR28boTmz748Wx:-NhfbgkR28boTmz748Wy:bqhkp0c) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L711)):*
> ```XML
>                     }
> 
>                     if filtered_events.len() == filter.chunk_size {
> ```

IIUC you can move this check to the end of the loop to avoid an unnecessary iteration



_Code quote:_
```XML
if filtered_events.len() == filter.chunk_size {
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: 0 of 56 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfYmzN7X_0yHgIcIBO:-Nhg6oE19kRrR-uKE5Xw:b-5mu5hz) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L565)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider using this struct as an intermediate for serde and converting it to and from an enum
</blockquote></details>

I think it's not worth it
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfZqzJ6IdsXgHZ7ZOs:-Nhg6vLABNZVHf852kDT:bbvqgtp) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L591)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why return this error in the case of None? The behavior seemed to return up to the latest block number.
</blockquote></details>

None is equivalent to Pending ( @ArielElp please confirm I'm correct)
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 704 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nhfaw6v1Su8gEDXKrEs:-NiAmhMGAPonE-ted5Ct:b4qrbhg) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L704)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What is this check?
</blockquote></details>

This is the keys filter check
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfbgkR28boTmz748Wx:-NiAnAvACfAEzGwKKw05:b-psy3b4) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L711)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IIUC you can move this check to the end of the loop to avoid an unnecessary iteration
</blockquote></details>

Moved to the start

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @ShahakShama)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NiEXAp55jNOG-XRH5H1):*
Shouldn't the scope be JSON-RPC?



_Code quote:_
```
sync
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfZqzJ6IdsXgHZ7ZOs:-NiEK0jl-4vJA2tUaM7q:b-buqfm2) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L591)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

None is equivalent to Pending ( @ArielElp please confirm I'm correct)
</blockquote></details>

Also, if not supported then shouldn't we return an internal error instead of empty data?
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 704 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nhfaw6v1Su8gEDXKrEs:-NiETAg99BfXHUAT7V8H:bcrn9l3) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L704)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is the keys filter check
</blockquote></details>

Can you elaborate?
Also, this code is repeating afterward, can you extract it to a function?
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NiEM1T41CkZbg_9r2kf:-NiEM1T41CkZbg_9r2kg:b-xxnny0) ([raw file](https://github.com/starkware-libs/papyrus/blob/c8291ae01006c379ecf6939fe17884ff76dfba66/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L676)):*
> ```XML
>                         // events, and we can stop the iteration.
>                         break;
>                     }
> ```

Isn't passing the address to the iter_events make it impossible to get events of a different contract?



_Code quote:_
```XML
                    if from_address != filter_address {
                        // The iterator of this loop outputs only events that have the filter's
                        // address, unless there are no more such events and then it outputs other
                        // events, and we can stop the iteration.
                        break;
                    }
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NhfZqzJ6IdsXgHZ7ZOs:-Ni_iA8KBcAZxA7i4Dvz:b-jgozl7) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L591)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Also, if not supported then shouldn't we return an internal error instead of empty data?
</blockquote></details>

There's a difference. Error means something is wrong. empty will simply mean that the pending block over the genesis block will never have transactions until we sync on the first block
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 704 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nhfaw6v1Su8gEDXKrEs:-Ni_mM_5EeRMqwd8zENf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/de3376bafd938b8f7681d2f519ff769ccdede655/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L704)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you elaborate?
Also, this code is repeating afterward, can you extract it to a function?
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NiEM1T41CkZbg_9r2kf:-Ni_VHUa0jqD7QkqkSP4:b-2lehgq) ([raw file](https://github.com/starkware-libs/papyrus/blob/c8291ae01006c379ecf6939fe17884ff76dfba66/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L676)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't passing the address to the iter_events make it impossible to get events of a different contract?
</blockquote></details>

Turns out the iterator will output events from a different contract when it finished all the events from the contract instead of stopping

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ArielElp and @dan-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NiEM1T41CkZbg_9r2kf:-Nin9B4xBGHmo2W4bEvv:b-ozlibs) ([raw file](https://github.com/starkware-libs/papyrus/blob/c8291ae01006c379ecf6939fe17884ff76dfba66/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L676)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Turns out the iterator will output events from a different contract when it finished all the events from the contract instead of stopping
</blockquote></details>

Isn't this a bug?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ArielElp, @dan-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-NiEM1T41CkZbg_9r2kf:-Nio36uI6Fo90AlYXjF5:b-7nqv7i) ([raw file](https://github.com/starkware-libs/papyrus/blob/c8291ae01006c379ecf6939fe17884ff76dfba66/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L676)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't this a bug?
</blockquote></details>

IDK, I just found out this weird behaviour and commented it so others will know. I guess we can ask @nagmo-starkware when he's back

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @dan-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_4_0/transaction.rs` line 565 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6hpMoAn3vRY71O0sz:-Nj6hpMoAn3vRY71O0t-:b-n8vlfb) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/transaction.rs#L565)):*
> ```XML
>     // Can't have a different struct for pending events because then that struct will need to have
>     // deny_unknown_fields. And there's a bug in serde that forbids having deny_unknown_fields with
>     // flatten: https://github.com/serde-rs/serde/issues/1701
> ```

Can you add TODO to fix it?
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 620 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6icpa0kc-cGGf7URa:-Nj6icpa0kc-cGGf7URb:b-7p3mj1) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L620)):*
> ```XML
>                 warn!(
>                     "Handling pending events when there are no accepted blocks is currently \
>                      unsupported. Returning no events."
> ```

I think the error is hard to understand.
Maybe: "Received a request for pending events while not fully synced. Unable to respond to the request, returning no events."



_Code quote:_
```XML
                    "Handling pending events when there are no accepted blocks is currently \
                     unsupported. Returning no events."
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 706 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6xwn02RAOKo1IQKES:-Nj6xwn02RAOKo1IQKET:bxip6pz) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L706)):*
> ```XML
>         }
> 
>         if include_pending_block {
> ```

Not blocking, but consider preparing an iterator by using chain + skip + take instead of using nested for loops.
I think it can make the code more readable
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 716 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6yMpkD29Zh6bbCtnL:-Nj6yMpkD29Zh6bbCtnM:b-7ppuv) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L716)):*
> ```XML
>             } else {
>                 (0, 0)
>             };
> ```

Add comment for this part



_Code quote:_
```XML
            let (transaction_start, event_start) = if start_event_index.0.0 > latest_block_number {
                (start_event_index.0.1.0, start_event_index.1.0)
            } else {
                (0, 0)
            };
```
___
*[`crates/papyrus_rpc/src/v0_4_0/api/test.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6zZPHDHlOVZ9vJJB5:-Nj6zZPHDHlOVZ9vJJB6:b1n3til) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/test.rs#L0)):*
Consider moving test data to a separate file

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @yair-starkware)

___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 620 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6icpa0kc-cGGf7URa:-Nj7crr96ntzHfvxojuD:b-1cpayq) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L620)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the error is hard to understand.
Maybe: "Received a request for pending events while not fully synced. Unable to respond to the request, returning no events."
</blockquote></details>

Is this better?
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 706 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6xwn02RAOKo1IQKES:-Nj7hDmP4bmNmsuxAokX:b-jaj6pq) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L706)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not blocking, but consider preparing an iterator by using chain + skip + take instead of using nested for loops.
I think it can make the code more readable
</blockquote></details>

maybe in a future PR
___
*[`crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs` line 716 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-Nj6yMpkD29Zh6bbCtnL:-Nj7hqm-1Ff8TMZhRFSv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/84a173ecbca40d65451b6722185a949b182caade/crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs#L716)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add comment for this part
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1303#-:-Nj7o671EuRqAa7sMNuB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @dan-starkware)

**Pull request merged**
