### PR TITLE
fix(network): add support to block hash in query

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-Npo18_H4R7oY7zdzwQM:-Npo18_H4R7oY7zdzwQN:b-3fhom1) ([raw file](https://github.com/starkware-libs/papyrus/blob/91db54cf88c101d4432a7582830c61b0eda12298/crates/papyrus_network/src/block_headers/mod.rs#L73)):*
> ```XML
>                         let block_hash = BlockHash(StarkHash::new(bytes).map_err(|error| {
>                             if !matches!(error, StarknetApiError::OutOfRange { .. }) {
>                                 panic!(
> ```

don't panic. make it recoverable

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-Npo18_H4R7oY7zdzwQM:-Npo1ehb8zcBwPA3FM6V:b-hlv1p1) ([raw file](https://github.com/starkware-libs/papyrus/blob/91db54cf88c101d4432a7582830c61b0eda12298/crates/papyrus_network/src/block_headers/mod.rs#L73)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

don't panic. make it recoverable
</blockquote></details>

map to what? the remaining errors are InnerDeserialization and ParseIntError, and they don't make sense in this context.

All this problem starts because StarknetApi didn't define to each function the errors it can return in a strict way, so I think it's ok to panic here

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-Npo18_H4R7oY7zdzwQM:-Npo3MDV-iiEjzb05nVO:b-vvpzmc) ([raw file](https://github.com/starkware-libs/papyrus/blob/91db54cf88c101d4432a7582830c61b0eda12298/crates/papyrus_network/src/block_headers/mod.rs#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

map to what? the remaining errors are InnerDeserialization and ParseIntError, and they don't make sense in this context.

All this problem starts because StarknetApi didn't define to each function the errors it can return in a strict way, so I think it's ok to panic here
</blockquote></details>

you can add a variant `ProtobufConversionError::Unknown`

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-Npo18_H4R7oY7zdzwQM:-Npo3i8zCKg2XQWzw4il:b-1l3cj1) ([raw file](https://github.com/starkware-libs/papyrus/blob/91db54cf88c101d4432a7582830c61b0eda12298/crates/papyrus_network/src/block_headers/mod.rs#L73)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

you can add a variant `ProtobufConversionError::Unknown`
</blockquote></details>

I think panic is better

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-Npo18_H4R7oY7zdzwQM:-Nposs-EEwe405_mc3PW:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/91db54cf88c101d4432a7582830c61b0eda12298/crates/papyrus_network/src/block_headers/mod.rs#L73)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think panic is better
</blockquote></details>

Done

**Review by nagmo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660#-:-NptaTQ8AXXT8XzU8P6m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1660)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
