### PR TITLE
test(sync): add negative tests for state diff p2p sync

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(sync): add state diff sync to p2p sync
- test(sync): move code
- test(sync): make code compile
- test(sync): add negative tests for state diff p2p sync

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1829)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1829)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/state_diff_test.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1829#-Ntyq4n05cxbKfVlFClJ:-Ntyq4n05cxbKfVlFClK:b-hl6vi0) ([raw file](https://github.com/starkware-libs/papyrus/blob/d92c9e4474f53f2d675e183ce1eac14c97b6b5ff/crates/papyrus_p2p_sync/src/state_diff_test.rs#L226)):*
> ```XML
>     let parse_queries_future = async move {
>         // We wait for the state diff sync to see that there are no headers and start sleeping
>         tokio::time::sleep(SLEEP_DURATION_TO_LET_SYNC_ADVANCE).await;
> ```

I didn't understand what's this sleep is for

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1829)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_p2p_sync/src/state_diff_test.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1829#-Ntyq4n05cxbKfVlFClJ:-Ntys1e8CZxplnoi94q9:byfjpu3) ([raw file](https://github.com/starkware-libs/papyrus/blob/d92c9e4474f53f2d675e183ce1eac14c97b6b5ff/crates/papyrus_p2p_sync/src/state_diff_test.rs#L226)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I didn't understand what's this sleep is for
</blockquote></details>

I think that we can remove it in this test because the query size is 1. in the other test in main we need this sleep to ensure the state diff won't cut the query into two

**Review by nagmo-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1829#-:-Ntyu0oDAvJe7Zp7By6R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1829)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
