### PR TITLE
feat(block_builder): initial mock block builder

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @eranreshef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCXZVN6-_AN5ElhRM6:-NxCXZVN6-_AN5ElhRM7:b-m4pqbo) (no related file):*
I thought that for milestone 1, we wouldn't create a whole block builder; rather, we'd just put the implementation inside context. I added pseudo-code to the [doc](https://docs.google.com/document/d/1ZJtgEcPzNW3hmzEIXNh-czY_OIEavNmXMj_4CeLA4A8/edit#heading=h.3gnnbr8l2zwu).  IIUC The model you are proposing is that the concrete `Context` struct we use will hold `BlockBuilder` as a field and call to it internally?

___
___
*[`crates/sequencing/papyrus_block_builder/src/lib.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCXds_8HdygRufV_-T:-NxCXds_8HdygRufV_-U:b-ppyn5f) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e814b3fb9d03916318b9e00530b608504d5e98/crates/sequencing/papyrus_block_builder/src/lib.rs#L26)):*
> ```XML
> pub trait BlockBuilderTrait {
>     fn build(&self, block_number: BlockNumber) -> BlockBuilderResult<Receiver<Transaction>>;
> }
> ```

I intend that from Milestone 1 Context will already be async. I think the (a)sync decision will end coloring a lot of things as we work to implement consensus, and that pushing off that decision will just cause us complexity in the future. I can see a few options:
1. You disagree; context starts as sync.
2. Everything goes async.
3. Context is async and BlockBuilder is sync. We can use an asymmetrical channel with a sync sender and async receiver. [crossfire](https://docs.rs/crossfire/1.0.1/crossfire/mpmc/fn.bounded_tx_blocking_rx_future.html).
    a. BlockBuilder returns this asymmetric channel .
    b. BlockBuilder stays as is, and Context can wrap the return value (but that adds another hope for each Transaction).



_Code quote:_
```XML
pub trait BlockBuilderTrait {
    fn build(&self, block_number: BlockNumber) -> BlockBuilderResult<Receiver<Transaction>>;
}
```
___
*[`crates/sequencing/papyrus_block_builder/src/lib.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCOnDM2VbTRJXso7oC:-NxCOnDN8yl2S4xdy4lA:bbfmiri) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e814b3fb9d03916318b9e00530b608504d5e98/crates/sequencing/papyrus_block_builder/src/lib.rs#L52)):*
> ```XML
>         let txn = self.storage_reader.begin_ro_txn().unwrap();
>         let block = txn.get_block_transactions(block_number).unwrap();
>         drop(txn);
> ```

How do you feel about the long call instead of an explicit drop? I tend not to like explicit drops.



_Suggestion:_
```XML
        let block = self
            .storage_reader
            .begin_ro_txn()
            .unwrap()
            .get_block_transactions(block_number)
            .unwrap();
```

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @eranreshef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCXZVN6-_AN5ElhRM6:-NxD6yUP1z4UwQcruNmG:b-o0el4f) (no related file):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I thought that for milestone 1, we wouldn't create a whole block builder; rather, we'd just put the implementation inside context. I added pseudo-code to the [doc](https://docs.google.com/document/d/1ZJtgEcPzNW3hmzEIXNh-czY_OIEavNmXMj_4CeLA4A8/edit#heading=h.3gnnbr8l2zwu).  IIUC The model you are proposing is that the concrete `Context` struct we use will hold `BlockBuilder` as a field and call to it internally?
</blockquote></details>

f2f - keeping this approach in Milestone 1.

___
___
*[`crates/sequencing/papyrus_block_builder/src/lib.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCXds_8HdygRufV_-T:-NxD732Y0Cl_bcFlc9aA:b-tog45v) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e814b3fb9d03916318b9e00530b608504d5e98/crates/sequencing/papyrus_block_builder/src/lib.rs#L26)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I intend that from Milestone 1 Context will already be async. I think the (a)sync decision will end coloring a lot of things as we work to implement consensus, and that pushing off that decision will just cause us complexity in the future. I can see a few options:
1. You disagree; context starts as sync.
2. Everything goes async.
3. Context is async and BlockBuilder is sync. We can use an asymmetrical channel with a sync sender and async receiver. [crossfire](https://docs.rs/crossfire/1.0.1/crossfire/mpmc/fn.bounded_tx_blocking_rx_future.html).
    a. BlockBuilder returns this asymmetric channel .
    b. BlockBuilder stays as is, and Context can wrap the return value (but that adds another hope for each Transaction).
</blockquote></details>

f2f - will make BlockBuilderTrait async in milestone 1. Dan can do it in this PR or if he prefers we'll handle this in a follow up.

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware, @eranreshef-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_block_builder/src/lib.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxCOnDM2VbTRJXso7oC:-NxHH5kbEDjxVw0ssBoN:b-k73z76) ([raw file](https://github.com/starkware-libs/papyrus/blob/26e814b3fb9d03916318b9e00530b608504d5e98/crates/sequencing/papyrus_block_builder/src/lib.rs#L52)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

How do you feel about the long call instead of an explicit drop? I tend not to like explicit drops.
</blockquote></details>

thanks

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @DvirYo-starkware, @eranreshef-starkware, and @matan-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1961)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @eranreshef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxHuxm6BgD1mgH9Velu:-NxHuxm6BgD1mgH9Velv:bp7wnrt) (no related file):*
I prefer not to put implementations in `lib.rs` and keep it just for module declarations and exports. I take it that is not what we do in papyrus and I don't know if it is widely done, but I have found that easier on myself.

___
___
*[`crates/sequencing/papyrus_block_builder/src/test.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1961#-NxHvlAv-QaNvJtzluOK:-NxHvlAv-QaNvJtzluOL:bj42ggd) ([raw file](https://github.com/starkware-libs/papyrus/blob/3392903fc1675d19eb2496713f12c0b2d6e5ec10/crates/sequencing/papyrus_block_builder/src/test.rs#L31)):*
> ```XML
> }
> 
> // TODO: add test for non-existing block.
> ```

?
// TODO: add test for sending info and dropping the sender before receiving.

I think this means we need the channel type used internally to be exposed for testing purposes.



_Code quote:_
```XML
// TODO: add test for non-existing block.
```

**Pull request merged**
