### PR TITLE
feat(network): improve send_data readability and use new BlockSignature from starknet_api

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1600)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1590** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1590?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1588** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1600** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1581** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1580** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1579** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1578** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1600?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1600)* status: all files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-Nnt30yKEw6q2nvYfNWH:-Nnt30yKEw6q2nvYfNWI:b9lxdu3) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6fd396b4608ca7663ee547e414982612e248f96/crates/papyrus_network/src/block_headers/behaviour.rs#L78)):*
> ```XML
>                 ]
>             }
>             Data::Fin { .. } => {
> ```

Add TODO to support different versions of Fin
Also, I think that Fin should not be known to the user. I think that there should be a pub function called `close_inbound_session` that sends the Fin message (And it can get a reason)
Future PR
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-Nnt3VxKBcoU0RFaQulH:-Nnt3VxKBcoU0RFaQulI:b8mzlvf) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6fd396b4608ca7663ee547e414982612e248f96/crates/papyrus_network/src/block_headers/behaviour.rs#L83)):*
> ```XML
>         };
>         for header_message in header_messages {
>             let Ok(_) = self.streamed_data_behaviour.send_data(
> ```

Use map_err and ?. And if that doesn't work use `.is_ok()`

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1600)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-Nnt30yKEw6q2nvYfNWH:-No6KBOv6kLjDZUGeHlN:bhghob3) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6fd396b4608ca7663ee547e414982612e248f96/crates/papyrus_network/src/block_headers/behaviour.rs#L78)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to support different versions of Fin
Also, I think that Fin should not be known to the user. I think that there should be a pub function called `close_inbound_session` that sends the Fin message (And it can get a reason)
Future PR
</blockquote></details>

not sure I agree since fin is not allways the end of the stream right? but ok for now I'm adding a TODO
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-Nnt3VxKBcoU0RFaQulH:-No6M65lCtVqieudQWf6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6fd396b4608ca7663ee547e414982612e248f96/crates/papyrus_network/src/block_headers/behaviour.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use map_err and ?. And if that doesn't work use `.is_ok()`
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-:-No6MmY19euHfmZUSE6X:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1600#-Nnt30yKEw6q2nvYfNWH:-No6MYjPD4TXHmKnS-Bm:bxniqry) ([raw file](https://github.com/starkware-libs/papyrus/blob/b6fd396b4608ca7663ee547e414982612e248f96/crates/papyrus_network/src/block_headers/behaviour.rs#L78)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

not sure I agree since fin is not allways the end of the stream right? but ok for now I'm adding a TODO
</blockquote></details>

In Headers it is. In other protocols you are correct

**Pull request merged**
