### PR TITLE
Update SN API dependency revision.

### PR DESCRIPTION
**Pull request by alonh5**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/655)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/655)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/655#-NUGWaIk8XCElxrJP8K5:-NUGWaIk8XCElxrJP8K6:b-v6b2fz) (no related file):*
@dan-starkware  do we need to check if the storage version is affected before merging this PR?

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/655#-:-NUGkBOm1apix6yJQ8sL:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/655#-NUGWaIk8XCElxrJP8K5:-NUGkD2ID11QqWS4Xu8D:b-yr0hnc) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@dan-starkware  do we need to check if the storage version is affected before merging this PR?
</blockquote></details>

Checked, nothing changed in the storage.

___

**Review by alonh5 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by yair-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
