### PR TITLE
fix(common): v3 transaction hash calculation

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLyeN17_j-i7nFjUlo:-NfLyeN17_j-i7nFjUlp:b-dr8xmc) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L228)):*
> ```XML
>         .chain(&l1_resource)
>         .chain(&l2_resource)
>         .get_poseidon_hash())
> ```

Add comment why is this poseidon (with maybe reference to starknet docs)
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzGm01KsIeO-4dXjF:-NfLzGm01KsIeO-4dXjG:b-y9meh4) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L231)):*
> ```XML
> }
> 
> // Concat of: [0 | resource_name (56 bit) | max_amount (64 bit) | max_price_per_unit (128 bit)].
> ```

Same as below
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLz66ABbuV26fD-y1s:-NfLz66ABbuV26fD-y1t:b-3m02m7) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L244)):*
> ```XML
> }
> 
> // Concat of [0...0 (192 bit) | nonce_mode (32 bit) | fee_mode (32 bit)].
> ```

You're already describing the concat in the expression. Consider instead
Receives nonce_mode and fee_mode and returns [0...0 ...
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzVz11PktkBjowWiK:-NfLzVz11PktkBjowWiL:b-o7lb1y) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash_test.rs#L47)):*
> ```XML
>     // The details were taken from Starknet Goerli. You can found the transactions by hash in:
>     // https://alpha4.starknet.io/feeder_gateway/get_transaction?transactionHash=<transaction_hash>
>     // The V3 transaction hashes generated by internal simulations.
> ```

generated -> are generated

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLyeN17_j-i7nFjUlo:-NfPP9fv-A5CVZRVZWu0:bzf9h4n) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L228)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add comment why is this poseidon (with maybe reference to starknet docs)
</blockquote></details>

1. A node doesn't design the hash.
2. It is not in the docs yet.
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzGm01KsIeO-4dXjF:-NfPPVXAAScE08ftCxfX:b36ecxi) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L231)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as below
</blockquote></details>

Same as below.
___
*[`crates/papyrus_common/src/transaction_hash_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzVz11PktkBjowWiK:-NfPR71P3nDrzadaunsJ:bczckbu) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash_test.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

generated -> are generated
</blockquote></details>

were generated?

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzGm01KsIeO-4dXjF:-NfPUQDr99nshRg287Zg:b-qxl4ug) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L231)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Same as below.
</blockquote></details>

you did not do the same fix as below

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yoavGrs)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-NfLzGm01KsIeO-4dXjF:-NfP_8p03BMeXA6YxQUB:bv7bgt6) ([raw file](https://github.com/starkware-libs/papyrus/blob/81181f0c5c3f6bd6c84bd6412dd8e7c10dfc9ba1/crates/papyrus_common/src/transaction_hash.rs#L231)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

you did not do the same fix as below
</blockquote></details>

Done.
(I did the same as above :( )

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-:-NfR6Xd42q7Jj5EcvN1b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1210#-:-NgNjbawBdHKWUHbPfCH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
