### PR TITLE
feat(network): add register_subscriber to network manager

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1673?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1672** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1672?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1673** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1673?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1673?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673)* status: all files reviewed, 13 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxJPx0QokjFakiVV-:-NpyxJPx0QokjFakiVV0:brrn7dg) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L33)):*
> ```XML
> }
> 
> pub enum Data {
> ```

Rename to DataType (I think you should erase this, see next comments)
___
*[`crates/papyrus_network/src/lib.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxAnHCgLsNBWe4dWH:-NpyxAnHCgLsNBWe4dWI:byabfuh) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L38)):*
> ```XML
> 
> #[derive(Default)]
> pub struct Query {
> ```

Unite this struct with BlockQuery (if you keep the data_type, then change this struct to contain a BlockQuery and a data type)
___
*[`crates/papyrus_network/src/lib.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpywFAbCh5gDc3fzZyV:-NpywFAbCh5gDc3fzZyW:b-8kp782) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L43)):*
> ```XML
>     pub limit: u64,
>     pub step: u64,
>     pub data_type: Data,
> ```

Right now we only have headers, and we're not sure if this is the way to go when we'll have more data types
I suggest to remove this for now
___
*[`crates/papyrus_network/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxXbQ-MUbERSlBpgG:-NpyxXbQ-MUbERSlBpgH:bnot281) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L83)):*
> ```XML
> 
> #[allow(unused)]
> struct ResponseSenders {
> ```

Move next to ResponseReceivers
___
*[`crates/papyrus_network/src/lib.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-Npyz05E0PiokIKeTCyB:-Npyz05E0PiokIKeTCyC:bv797so) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L87)):*
> ```XML
> }
> 
> type QueryId = usize;
> ```

Let's remove this for now. We're not sure if we'll use it
If you keep it, change it to `struct QueryId(usize)` so that it will enforce type safety
___
*[`crates/papyrus_network/src/lib.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxmNA3qCWm6-_Swng:-NpyxmNA3qCWm6-_Swnh:b-8mf3hu) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L135)):*
> ```XML
> }
> 
> impl Sink<Query> for QuerySender {
> ```

This is only for when we have multiple subscribers. Please erase this struct
___
*[`crates/papyrus_network/src/lib.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxsEJ4CsAG1tkjUhz:-NpyxsEJ4CsAG1tkjUi-:b-w1rxq) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L159)):*
> ```XML
> }
> 
> impl Default for Direction {
> ```

Use derive(Default) and #[default]
___
*[`crates/papyrus_network/src/lib.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxwFc6yldoDj9fGVL:-NpyxwFc6yldoDj9fGVM:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L165)):*
> ```XML
> }
> 
> impl Default for Data {
> ```

same
___
*[`crates/papyrus_network/src/lib.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxyGo6M_DXJ_skPZk:-NpyxyGo6M_DXJ_skPZl:b6zwn1s) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L171)):*
> ```XML
> }
> 
> impl ResponseSenders {
> ```

Consider making the fields public instead
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyyuqyCm69Nx8DEwwr:-NpyyuqyCm69Nx8DEwws:b-jrdxqj) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/mod.rs#L20)):*
> ```XML
> 
> type StreamCollection = SelectAll<BoxStream<'static, (Data, InboundSessionId)>>;
> type SyncSubscriberChannels = (Receiver<(Query, QueryId)>, ResponseSenders);
> ```

We don't need QueryId right now. Let's add it if we find out that we need it
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyzGXN1z96rWxv45tz:-NpyzGXN1z96rWxv45u-:b-9ab3k8) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/mod.rs#L27)):*
> ```XML
>     header_buffer_size: usize,
>     query_results_router: StreamCollection,
>     next_query_id: usize,
> ```

If you keep this, then find a different name other than query because it is taken by db executor (or rename in db executor)
___
*[`crates/papyrus_network/src/network_manager/tests.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-Npyy_Dz4i4zK_i9AQWD:-Npyy_Dz4i4zK_i9AQWE:bbvokcp) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/tests.rs#L1)):*
> ```XML
> use futures::future::poll_fn;
> ```

Rename the file to test.rs and unite with my PR #1683 
___
*[`crates/papyrus_network/src/network_manager/tests.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyzfRF4qGSKTH_t5K3:-NpyzfRG5BGC1t1hpUaj:btxfu7b) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/tests.rs#L11)):*
> ```XML
> async fn register_subscriber_and_use_channels() {
>     let ((storage_reader, _storage_writer), _temp_dir) = get_test_storage();
>     let mut net_manager = NetworkManager::new(NetworkConfig::default(), storage_reader);
> ```

net_manager -> network_manager

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxJPx0QokjFakiVV-:-NqMf4r_1H0ty0aPTgcg:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L33)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to DataType (I think you should erase this, see next comments)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxAnHCgLsNBWe4dWH:-NqMYt3w1NScu7Tk-6kT:bmibzrw) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unite this struct with BlockQuery (if you keep the data_type, then change this struct to contain a BlockQuery and a data type)
</blockquote></details>

I thought about it and did it on purpose. in order to not expose the internals of the network I created the two types and not reused the BlockQyuery. that way there's no coupling between the user of the network and the internal design.
___
*[`crates/papyrus_network/src/lib.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpywFAbCh5gDc3fzZyV:-NqMZKVC8Ph2fMnZuTku:b-27lflf) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Right now we only have headers, and we're not sure if this is the way to go when we'll have more data types
I suggest to remove this for now
</blockquote></details>

but we did decide on this design.. so I wanted it to be a guide for the next one to implement this.
___
*[`crates/papyrus_network/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxXbQ-MUbERSlBpgG:-NqMg8waEjAi_SuNWaMY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move next to ResponseReceivers
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-Npyz05E0PiokIKeTCyB:-NqMfmlEDGCGzJTgmVJo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L87)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Let's remove this for now. We're not sure if we'll use it
If you keep it, change it to `struct QueryId(usize)` so that it will enforce type safety
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxmNA3qCWm6-_Swng:-NqMfRPt7sxHJeUExjtv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L135)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is only for when we have multiple subscribers. Please erase this struct
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxsEJ4CsAG1tkjUhz:-NqMfEQ2DyMWri8ZIKDH:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L159)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use derive(Default) and #[default]
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxwFc6yldoDj9fGVL:-NqMf8RCA8NYXD_7K0Ji:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L165)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyyuqyCm69Nx8DEwwr:-NqMfpUL5gVCqWU63wQf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/mod.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We don't need QueryId right now. Let's add it if we find out that we need it
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyzGXN1z96rWxv45tz:-NqMfxzL124tv4YIFFLS:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/network_manager/mod.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If you keep this, then find a different name other than query because it is taken by db executor (or rename in db executor)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxAnHCgLsNBWe4dWH:-NqMm5Db27xI11Op_rbu:bv9mno1) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L38)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I thought about it and did it on purpose. in order to not expose the internals of the network I created the two types and not reused the BlockQyuery. that way there's no coupling between the user of the network and the internal design.
</blockquote></details>

As we said Be'al pe, remane BlockQuery to InternalQuery

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-NpyxAnHCgLsNBWe4dWH:-NqNIc9iCbwh8sbRhy1X:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/864f685cb3194130fd5baa4c3ec69275f65ec67e/crates/papyrus_network/src/lib.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As we said Be'al pe, remane BlockQuery to InternalQuery
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1673#-:-NqNIt7ABo0YCJaPKrZN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
