### PR TITLE
Yair/0.11

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/573)

### CODE REVIEW

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 35 files at r1, 1 of 6 files at r2, 7 of 34 files at r3, 7 of 21 files at r4, 26 of 26 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/573#-:-NRm8nz005Htc1MgT49p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/573#-NRm8hdF8LNhQPxon_Zk:-NRm8hdF8LNhQPxon_Zl:b-828r0x) (no related file):*
You should merge the SN API PR first.

___
___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 10 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/573#-NRm5tlS-UxC1cPABR34:-NRm5tlS-UxC1cPABR35:bfmfmgq) ([raw file](https://github.com/starkware-libs/papyrus/blob/da1534af67ad0ae1937569b24272cdb244b8e41c/crates/papyrus_node/src/bin/central_source_integration_test.rs#L10)):*
> ```XML
> async fn main() {
>     // TODO(yair): the chain changed to integration for the 0.11 development. Change it back to the
>     // default once 0.11 is on mainnet.
> ```

We can actually leave it as it is and just remove the comment.



_Code quote:_
```XML
    // TODO(yair): the chain changed to integration for the 0.11 development. Change it back to the
    // default once 0.11 is on mainnet.
```
___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/573#-NRm7LYB5tObJqX3dRLl:-NRm7LYB5tObJqX3dRLm:bhc402u) ([raw file](https://github.com/starkware-libs/papyrus/blob/da1534af67ad0ae1937569b24272cdb244b8e41c/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L11)):*
> ```XML
>     let config = Config::load(vec![
>         "--chain_id=SN_GOERLI".to_string(),
>         "--central_url=https://external.integration.starknet.io/".to_owned(),
> ```

Since this test relies on specific blocks, we should  revert back to mainnet.
Consider adding a TODO to find interesting blocks at integration and use integration instead of mainnet.



_Code quote:_
```XML
    let config = Config::load(vec![
        "--chain_id=SN_GOERLI".to_string(),
        "--central_url=https://external.integration.starknet.io/".to_owned(),
    ])
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/573)* status: 38 of 45 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/bin/central_source_integration_test.rs` line 10 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/573#-NRm5tlS-UxC1cPABR34:-NRmMiUh8lC5w3Rjmf_p:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/da1534af67ad0ae1937569b24272cdb244b8e41c/crates/papyrus_node/src/bin/central_source_integration_test.rs#L10)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We can actually leave it as it is and just remove the comment.
</blockquote></details>

done
___
*[`crates/papyrus_node/src/bin/starknet_client_integration_test.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/573#-NRm7LYB5tObJqX3dRLl:-NRmMeLJ6f7wswbNA3H1:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/da1534af67ad0ae1937569b24272cdb244b8e41c/crates/papyrus_node/src/bin/starknet_client_integration_test.rs#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Since this test relies on specific blocks, we should  revert back to mainnet.
Consider adding a TODO to find interesting blocks at integration and use integration instead of mainnet.
</blockquote></details>

done

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
