### PR TITLE
Dvir/client integration test

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [X] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/600)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/600)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/600#-NSfsBDKCyi1FRCoeEgh:-NSfsBDL4FfreV2t5ZNk:b-rz8b3a) (no related file):*
The first commit changes this test to use alpha4 instead of main-net.
Before this change, we asked mainnet for block numbers that are much higher than what it has, the answer was Ok(None), and we haven't caught it. So before this change, this test doesn't test anything.
also now if we ask for a higher block number than the last block in alpha4 we will not catch it. I think we should add this to the test.
In general, I think we should change some things in this test: to unwarp the results to find those Ok(None) cases, remove the let statement, delete the expect messages, and add an explanation to what every request checks.

___

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/600)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/600#-NSfsBDKCyi1FRCoeEgh:-NStmoU9B_psReDaoZLZ:b98ld58) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

The first commit changes this test to use alpha4 instead of main-net.
Before this change, we asked mainnet for block numbers that are much higher than what it has, the answer was Ok(None), and we haven't caught it. So before this change, this test doesn't test anything.
also now if we ask for a higher block number than the last block in alpha4 we will not catch it. I think we should add this to the test.
In general, I think we should change some things in this test: to unwarp the results to find those Ok(None) cases, remove the let statement, delete the expect messages, and add an explanation to what every request checks.
</blockquote></details>

This is weird. Maybe it was supposed to be set on Goerli? 
We need to investigate this because blocks were chosen specifically to test some features

___

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/600)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/600#-NSfsBDKCyi1FRCoeEgh:-NStq5gtENMYQrQKaSjP:b-h21pyn) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is weird. Maybe it was supposed to be set on Goerli? 
We need to investigate this because blocks were chosen specifically to test some features
</blockquote></details>

I believe it really was supposed to be set on Goerli.
As I said I think we should change a lot in this test. I can do it if you think also we should.

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/600#-:-NSuDH437Nand-CYXnmR:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Pull request merged**
