### PR TITLE
feat(consensus): create consensus crate

### PR DESCRIPTION
**Pull request by matan-starkware**
**Stack**:
- #1993
- #1992 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1992)

### CODE REVIEW

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1992)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1992#-NxvT_kA-wtKQPZedlVw:-NxvT_kB5HBtPGintonR:bccike0) ([raw file](https://github.com/starkware-libs/papyrus/blob/704aef5a5e75f9bb410e2140a7d2d9ab8ba1cfa0/crates/sequencing/papyrus_consensus/src/lib.rs#L14)):*
> ```XML
>         assert_eq!(result, 4);
>     }
> }
> ```

default for new lib.rs. Will remove in the next file when I actually add content.



_Code quote:_
```XML
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1992)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @ShahakShama)

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1992)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1992)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
