### PR TITLE
refactor(network): move Protocol to papyrus_p2p_sync

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193)

### CODE REVIEW

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193)* status: 7 of 19 files reviewed, 11 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x-_FL95ioFsgp6bAu:-O0xiCus7MAKZ6ZWhMVY:bawnoeb) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/network_manager/mod.rs#L107)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The arguments of this function should be the only place where a protocol is a String. Please convert it to StreamProtocol as soon as you get it and across the entire network crate work with StreamProtocol
</blockquote></details>

Done. i left it as string for client as well.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0582EelDuGKhO7xn:-O0xob-A6sniQQJCp_dz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/network_manager/test.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this into HashSet
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0G9s2Qb1Id-5rnPz:-O0xqBAU1RzXumQt07WJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/network_manager/test.rs#L268)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make the supported_inbound_protocols field public, and validate its content here
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/sqmr/behaviour.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0c_V7cdQf_85VzmS:-O0xqytjEi4OPjo1DeCQ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/sqmr/behaviour.rs#L121)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this. And instead add a TODO in register_sqmr_protocol_client/server to support multiple protocols where they're all different versions of the same protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/sqmr/behaviour.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0rqR1DIzOAmTK3t3:-O0x86qECG2tRmgIGfM4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/sqmr/behaviour.rs#L252)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can make this pub
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x25-w4EIFrIhpYwYS:-O0xqQ4-89w2zrM5rizP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_p2p_sync/src/lib.rs#L10)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add newline below this
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x27tp20e1ojMOTL8i:-O0xqgPD5uJUS4rAqx-D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_p2p_sync/src/lib.rs#L11)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the document here

/// The p2p sync protocol names needed for negotiation, as they appear in the p2p specs
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x22h5AQsTbr-H4oDE:-O0xqg0V4IJgQ07SJSkD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_p2p_sync/src/lib.rs#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're doing this TODO now
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x20SY1PbzSd0Ny7aI:-O0xqfhd1jn5iyNXV_1j:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_p2p_sync/src/lib.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to derive display
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x2MZ38sTNYONG_uRN:-O0xqfS01S7P46JUuWiI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_p2p_sync/src/lib.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can erase everything under this line until the end of the file
</blockquote></details>

Done.

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193)* status: 4 of 19 files reviewed, 11 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0G9s2Qb1Id-5rnPz:-O1BxsYyCwY0GXmGwLdM:b-3olo5t) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/network_manager/test.rs#L268)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

network manager takes ownership of swarn so even with it public it doesn't allow for validation here
___
*[`crates/papyrus_network/src/test_utils/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x1SPh09pGQVAcmkMh:-O1By12aEwCV0QrjTOGF:b-9zdhbx) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/test_utils/mod.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This doesn't belong to Handler. Instead create a lazy static constant of SUPPORTED_PROTOCOLS which is this vec
</blockquote></details>

created todo

**Review by ShahakShama — DISMISSED** [review]
> Reviewed 2 of 11 files at r3, 12 of 13 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x0G9s2Qb1Id-5rnPz:-O1FeBHqB_6A-E5lHnR9:b9yviyb) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/network_manager/test.rs#L268)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

network manager takes ownership of swarn so even with it public it doesn't allow for validation here
</blockquote></details>

Ok, I've got an idea
Instead of a hashset, have a sender channel of supported inbound protocols, and pass the receiver end to the test (have the sender channel as an option or vec, and have a method that sets the sender channel and returns the receiver)
Unblocking for now
___
*[`crates/papyrus_network/src/sqmr/handler_test.rs` line 50 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O1Fernt0hgAdZveADO-:-O1Fernt0hgAdZveADO0:b-1mi57m) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca9953caf48474c29250a709b4e61161662c8c9a/crates/papyrus_network/src/sqmr/handler_test.rs#L50)):*
> ```XML
>         .into_iter()
>         .next()
>         .expect("No supported protocol in test set");
> ```

You can unwrap here. This message isn't good
___
*[`crates/papyrus_network/src/sqmr/protocol.rs` line 16 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O1Ff5UV3HxIdF_4w-MG:-O1Ff5UV3HxIdF_4w-MH:bb7r2f0) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca9953caf48474c29250a709b4e61161662c8c9a/crates/papyrus_network/src/sqmr/protocol.rs#L16)):*
> ```XML
> use super::Bytes;
> 
> // TODO(eitan): make this a hashset
> ```

why?
___
*[`crates/papyrus_network/src/test_utils/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O0x1SPh09pGQVAcmkMh:-O1FfbdM2NEyAEnLVOaL:b-nhyzv8) ([raw file](https://github.com/starkware-libs/papyrus/blob/7e1d553327fc31cfe5eaa54ec534b47e74151e15/crates/papyrus_network/src/test_utils/mod.rs#L52)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

created todo
</blockquote></details>

Please do the TODO in the next PR
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-O1FfnlhElUdJgsg6sdh:-O1FfnlhElUdJgsg6sdi:btcmyqh) ([raw file](https://github.com/starkware-libs/papyrus/blob/ca9953caf48474c29250a709b4e61161662c8c9a/crates/papyrus_p2p_sync/src/lib.rs#L8)):*
> ```XML
> pub const BUFFER_SIZE: usize = 100000;
> 
> /// TODO: Support multiple protocols where they're all different versions of the same protocol
> ```

This TODO should be in the network crate on top of register_sqmr_protocol_server/client

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-:-O1GqoQ37CSU-ZKsfRw4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-:-O1IjkYr1HKocxCZ6FqX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2193#-:-O1L7VEs7o0rSH9vcxhK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
