### PR TITLE
Remove nanos from sync config.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/462)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/462)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`config/config.yaml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/462#-NLz0rJpCT0O5Ks6JeGH:-NLz0rJpCT0O5Ks6JeGI:bpinij9) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0dfbd878d942e1df39c229a01cb75d9829e1538/config/config.yaml#L28)):*
> ```YAML
> sync:
>     block_propagation_sleep_duration: 10
>     recoverable_error_sleep_duration: 10
> ```

Add _sec to the name



_Code quote:_
```YAML
    block_propagation_sleep_duration: 10
    recoverable_error_sleep_duration: 10
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/462)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/462)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`config/config.yaml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/462#-NLz0rJpCT0O5Ks6JeGH:-NLz906PDo-F3SM7ICl3:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/c0dfbd878d942e1df39c229a01cb75d9829e1538/config/config.yaml#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add _sec to the name
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/462#-:-NLzD3Ec2FXtsxmMcMkO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
