### PR TITLE
chore(JSON-RPC): remove v0_3

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1469)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1469)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_load_test/src/main.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1469#-NkQcmDE7z-RHYl6cOL-:-NkQcmDE7z-RHYl6cOL0:b-m0hrcv) ([raw file](https://github.com/starkware-libs/papyrus/blob/129cd1c40de0a71a6718a674aa688b94191486a6/crates/papyrus_load_test/src/main.rs#L32)):*
> ```XML
>     let metrics = GooseAttack::initialize()?
>         // The choice between V0_3 and V0_4 must be also in the environment variable VERSION_ID.
>         .register_scenario(scenarios::general_request_v0_3())
> ```

@DvirYo-starkware FYI (If you happen to be next to a computer :) )

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1469)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_load_test/src/scenarios.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1469#-NkR00R83dbOtL3IblT2:-NkR00R83dbOtL3IblT3:bj2rh8y) ([raw file](https://github.com/starkware-libs/papyrus/blob/129cd1c40de0a71a6718a674aa688b94191486a6/crates/papyrus_load_test/src/scenarios.rs#L102)):*
> ```XML
> }
> 
> // TODO(dvir): add also traceTransaction, simulateTransactions, estimateFee and call endpoints.
> ```

Why delete the todo?



_Code quote:_
```XML
// TODO(dvir): add also traceTransaction, simulateTransactions, estimateFee and call endpoints.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1469)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_load_test/src/scenarios.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1469#-NkR00R83dbOtL3IblT2:-NkR0_x-9u5fqt7d74eQ:b-8yt1et) ([raw file](https://github.com/starkware-libs/papyrus/blob/129cd1c40de0a71a6718a674aa688b94191486a6/crates/papyrus_load_test/src/scenarios.rs#L102)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why delete the todo?
</blockquote></details>

I didn't delete it. Reviewable/git is dumb. It's added above this function

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1469)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
Please also fix the README

**Pull request merged**
