### PR TITLE
Dvir/check already exists hash between deprecate declare and new declare

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/593)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/593)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/593#-NSC-2OmAhBkf77fgehv:-NSC-2On3O3PSxLvgXGE:b-7vd51w) (no related file):*
This pull request ensures that the same class hash will not be used to declare classes with the deprecate and the new version. 

First commit adds tests to make sure this will not happen.
Second commit adds the checks in the writing.
Third commit fixes tests that failed because of the change.

___
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1490 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/593#-NSC1oio8wSfnB50VDeQ:-NSC1oio8wSfnB50VDeR:b2op5pd) ([raw file](https://github.com/starkware-libs/papyrus/blob/33192886dacf206893222f8728820746e9c9e87c/crates/papyrus_gateway/src/gateway_test.rs#L1490)):*
> ```XML
> 
> #[tokio::test]
> async fn serialize_returns_valid_json() {
> ```

Before this change, two classes were declared with hash 0x0 (deprecated and new version). The new version was returned when getting the class with hash 0x0 because the get_class_at first checks the new version. The test passed, although it was wrong.
I added a schema test also for the deprecated version.
___
*[`crates/papyrus_storage/src/state/mod.rs` line 448 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/593#-NSC12xc8V7CIfIneZYc:-NSC12xc8V7CIfIneZYd:b-lgc2o3) ([raw file](https://github.com/starkware-libs/papyrus/blob/18507f5daba504349119a0ba0f23fc52c8e91ffb/crates/papyrus_storage/src/state/mod.rs#L448)):*
> ```XML
>         // TODO(dan): remove this check after regenesis, in favor of insert().
>         if let Some(value) = deprecated_declared_classes_table.get(txn, &class_hash)? {
>             if value.contract_class != deprecated_contract_class {
> ```

Maybe we should combine those two if to one. what do you think?



_Code quote:_
```XML
        if let Some(value) = deprecated_declared_classes_table.get(txn, &class_hash)? {
            if value.contract_class != deprecated_contract_class {
                return Err(StorageError::ClassAlreadyExists { class_hash });
            }
            continue;
        }
        if (declared_classes_table.get(txn, &class_hash)?).is_some() {
            return Err(StorageError::ClassAlreadyExists { class_hash });
        }
```
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 406 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/593#-NSC1ax37hs2moAKAVXh:-NSC1ax43oy2OLJhosfq:bsrkvep) ([raw file](https://github.com/starkware-libs/papyrus/blob/33192886dacf206893222f8728820746e9c9e87c/crates/papyrus_storage/src/state/state_test.rs#L406)):*
> ```XML
>     // Create another state diff, deploying new contracts and changing the state of the contract
>     // deployed in state0.
>     let contract1 = ContractAddress(patricia_key!("0x111"));
> ```

The same hash to declare deprecated and the new version is bad.

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/593)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 448 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/593#-NSC12xc8V7CIfIneZYc:-NTOoFmR1UR1VnRXLGQJ:b-fpn24h) ([raw file](https://github.com/starkware-libs/papyrus/blob/18507f5daba504349119a0ba0f23fc52c8e91ffb/crates/papyrus_storage/src/state/mod.rs#L448)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think you should move the checks to an external function
</blockquote></details>

Done. I think it is cleaner, more understandable, and more efficient to do it in the same function. Do you agree?

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/593#-:-NThDa5qAWRoJbneT5sS:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/593)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

**Pull request merged**
