### PR TITLE
refactor(network): db executor communicates through channels

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)

### CODE REVIEW

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-:-O-jeb5v4fNN7hzlGHeH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-:-O-kTmqmChqZZTAqr0ts:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oVHGk9wMwkleeUnhp:-O-oVHGk9wMwkleeUnhq:b-3ve4nw) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L88)):*
> ```XML
>     state_diff_queries_receiver:
>         Option<SqmrQueryReceiver<StateDiffQuery, DataOrFin<StateDiffChunk>>>,
> }
> ```

The DBExecutor is going to become the SyncServer. And therefore it make sense to have specific reference to header and state diff. right?



_Code quote:_
```XML
pub struct DBExecutor {
    storage_reader: StorageReader,
    // TODO(shahak): Make this non-option.
    header_queries_receiver: Option<SqmrQueryReceiver<HeaderQuery, DataOrFin<SignedBlockHeader>>>,
    // TODO(shahak): Make this non-option.
    state_diff_queries_receiver:
        Option<SqmrQueryReceiver<StateDiffQuery, DataOrFin<StateDiffChunk>>>,
}
```
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-oW5qM3lYfEwuDcfeY:bpxdryx) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
> ```XML
> 
>             tokio::select! {
>                 Some((query_result, response_sender)) = header_queries_receiver_future => {
> ```

What happens if the future returns None?



_Code quote:_
```XML
                Some((query_result, response_sender)) = header_queries_receiver_future => {
```
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oX5r99yOp5fHQ7aDb:-O-oX5r99yOp5fHQ7aDc:b-twde87) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L264)):*
> ```XML
>     // If this function fails, we still want to send fin before failing.
>     let result = send_data_without_fin_for_query(&storage_reader, query, &mut sender).await;
>     sender.feed(DataOrFin(None)).await?;
> ```

when do we flush?



_Code quote:_
```XML
sender.feed(DataOrFin(None)).await?;
```
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oX1dNDcW6tt_rl_X2:-O-oX1dNDcW6tt_rl_X3:bz8n995) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L295)):*
> ```XML
>         for data in data_vec {
>             // TODO: consider implement retry mechanism.
>             sender.feed(DataOrFin(Some(data))).await?;
> ```

When do we flush?



_Code quote:_
```XML
sender.feed(DataOrFin(Some(data))).await?;
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oVHGk9wMwkleeUnhp:-O-ol8b0CP5JTkiZ8-5N:bxi8fr8) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L88)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

The DBExecutor is going to become the SyncServer. And therefore it make sense to have specific reference to header and state diff. right?
</blockquote></details>

Yes, we will move it from the network crate
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-olEXPCu8Neu-mJByc:b-gn7b7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What happens if the future returns None?
</blockquote></details>

Fixed. If you're interested I can tell you what was the previous code in huddle
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oX5r99yOp5fHQ7aDb:-O-olodgA9H2n_ug9dn6:bf0of14) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L264)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

when do we flush?
</blockquote></details>

We don't need to, it's flushed automatically (not sure when but I've checked the final PR with e2e with the node executable so it works)
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oX1dNDcW6tt_rl_X2:-O-om3VE74p-fc6b-45i:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L295)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

When do we flush?
</blockquote></details>

Same

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-ooVo35fW0KMI3Bc7Z:b-rhn30m) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Fixed. If you're interested I can tell you what was the previous code in huddle
</blockquote></details>

I don't see any change in the code.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-opWTmAoLy43m_9qff:b-mx6wym) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't see any change in the code.
</blockquote></details>

Forgot to push :sweat_smile:

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-pK8x944-LU2WwDPsO:b-usm6tj) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Forgot to push :sweat_smile:
</blockquote></details>

Ok. Do we prefer `expect` outside of test code?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O-q1rBX91rGt0Fy11U9:b-sjnhmr) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Ok. Do we prefer `expect` outside of test code?
</blockquote></details>

You and clippy are best friends

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2121#-O-oW5qM3lYfEwuDcfeX:-O093IDL83qqMFGvO00-:b2nh52p) ([raw file](https://github.com/starkware-libs/papyrus/blob/cb8c766cec6317cf2eab8e5599daf065d9effc52/crates/papyrus_network/src/db_executor/mod.rs#L123)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You and clippy are best friends
</blockquote></details>

:D

**Pull request merged**
