### PR TITLE
feat(network): add Transaction Protocol

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07hQOy80_xO1eNB3PO:-O07hQOy80_xO1eNB3PP:b-gpz0cv) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_network/src/db_executor/mod.rs#L220)):*
> ```XML
>         for (transaction, transaction_output) in transactions.iter().zip(transaction_outputs.iter())
>         {
>             result.push((transaction.clone(), transaction_output.clone()));
> ```

Use into_iter and remove clone
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07heqcCYT1uJ9cGdus:-O07heqcCYT1uJ9cGdut:bfrvxgt) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_network/src/db_executor/test.rs#L29)):*
> ```XML
> const BUFFER_SIZE: usize = 10;
> 
> // TODO(shahak): Add test for state_diff_query_positive_flow.
> ```

Add test for transactions, or add a TODO to add such test (maybe it's better to add a TODO in order to keep this PR thin)
I think the best way to do this without code duplication is to have a function that receives the storage reader and the expected items and runs the test, and then call it for headers and for transactions
This function can run all the tests, not just the positive flow one
___
*[`crates/papyrus_node/src/main.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07iTvF5KBBc_B4EkiE:-O07iQrH5YF5HmuHOgIO:b-fzhgnx) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_node/src/main.rs#L304)):*
> ```XML
>         network_manager.register_sqmr_subscriber(Protocol::SignedBlockHeader);
>     let state_diff_client_channels = network_manager.register_sqmr_subscriber(Protocol::StateDiff);
>     let transaction_client_channels =
> ```

Remove this line. @eitanm-starkware will add it when he adds transaction as a sync protocol

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07hQOy80_xO1eNB3PO:-O07mRTb5cJ5Q-fmxm_8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_network/src/db_executor/mod.rs#L220)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use into_iter and remove clone
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07heqcCYT1uJ9cGdus:-O07mSBw0ApoXU_TvKX6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_network/src/db_executor/test.rs#L29)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add test for transactions, or add a TODO to add such test (maybe it's better to add a TODO in order to keep this PR thin)
I think the best way to do this without code duplication is to have a function that receives the storage reader and the expected items and runs the test, and then call it for headers and for transactions
This function can run all the tests, not just the positive flow one
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/main.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07iTvF5KBBc_B4EkiE:-O07mSkt9qzZSLDRX2QZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0df65bf72bac034eb5662ae4eeaadc261259f243/crates/papyrus_node/src/main.rs#L304)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this line. @eitanm-starkware will add it when he adds transaction as a sync protocol
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O07p8KZCla-J43Byjsv:-O07p8K_2mBLtQkAO9A5:bddz5fg) (no related file):*
Blocking until the base PR is merged

___

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 109 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-O0EUEnB1m5rJWbathhT:-O0EUEnC8PSonej3f-9T:bx6ayz6) ([raw file](https://github.com/starkware-libs/papyrus/blob/12396a341966f41d46357d744037a7f46ba2f35c/crates/papyrus_network/src/db_executor/mod.rs#L109)):*
> ```XML
>                     }
>                 }
>                 result = self.state_diff_queries_receiver.next() => {
> ```

Why did you change this? keep the same code for all protocols

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2135#-:-O0EZsuX2832W9YDI8Nb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
