### PR TITLE
Dvir/append state update replaced classes

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [X] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/mod.rs` line 327 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NSfOdIEDHzQENGrNJy2:-NSfOdIEDHzQENGrNJy3:bwwsqlq) ([raw file](https://github.com/starkware-libs/papyrus/blob/2e59fb5cc76fdf622fc2063600d72fabd0d4c77b/crates/papyrus_storage/src/state/mod.rs#L327)):*
> ```XML
>         }
> 
>         write_replaced_classes(
> ```

Put this in the end because we need to know all the declared classes and deployed contracts to discover illegal replacements.
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 242 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NSfOyW-CQog2lZwRaz7:-NSfOyW-CQog2lZwRaz8:b6kmgo9) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b6bb35884702722c1116f59bdec19eb19359032/crates/papyrus_storage/src/state/state_test.rs#L242)):*
> ```XML
> }
> 
> // TODO(dvir): add replaced classes and declared classes to the state diff comparison.
> ```

We should talk about this.



_Code quote:_
```XML
// TODO(dvir): add replaced classes and declared classes to the state diff comparison.
// TODO(dvir): consider dividing this test into different components.
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/state/state_test.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NStlGNtB8i5CvU0wCLu:-NStlGNtB8i5CvU0wCLv:bc82k69) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b6bb35884702722c1116f59bdec19eb19359032/crates/papyrus_storage/src/state/state_test.rs#L152)):*
> ```XML
>     // Replace to the same class hash.
>     // Replace twice the same contract.
>     let diff1 = StateDiff {
> ```

The same contract can't be replaced multiple times in the same state diff (we will get only the last replacement).
@dan-starkware - should we add this as an invariant?
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 165 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NStluAR-U78uPtYBXtq:-NStluAR-U78uPtYBXtr:b7izrxt) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b6bb35884702722c1116f59bdec19eb19359032/crates/papyrus_storage/src/state/state_test.rs#L165)):*
> ```XML
>         ..Default::default()
>     };
>     // Replace contract and class that was deployed in the same block.
> ```

This scenario can't happen - we will get the replacing class as the class of the deployed contract (checked with Yoni)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/state/state_test.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NStlGNtB8i5CvU0wCLu:-NTiDlx_AR1Apsf6gFuo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b6bb35884702722c1116f59bdec19eb19359032/crates/papyrus_storage/src/state/state_test.rs#L152)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The same contract can't be replaced multiple times in the same state diff (we will get only the last replacement).
@dan-starkware - should we add this as an invariant?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/state/state_test.rs` line 165 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NStluAR-U78uPtYBXtq:-NTiDmBn0dCuHMOqdFNt:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/2b6bb35884702722c1116f59bdec19eb19359032/crates/papyrus_storage/src/state/state_test.rs#L165)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This scenario can't happen - we will get the replacing class as the class of the deployed contract (checked with Yoni)
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/state/state_test.rs` line 160 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NTiImOT3xqw0XKmcrmY:-NTiImOT3xqw0XKmcrmZ:b-pg0ddt) ([raw file](https://github.com/starkware-libs/papyrus/blob/7cfaadab01fea620af66bed4153c2bf995b877a9/crates/papyrus_storage/src/state/state_test.rs#L160)):*
> ```XML
>         ..Default::default()
>     };
>     // Replace to class that was deployed in the same block.
> ```

declared



_Code quote:_
```XML
deployed
```

**Comment by DvirYo-starkware** [comment]
*[`crates/papyrus_storage/src/state/state_test.rs` line 160 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NTiImOT3xqw0XKmcrmY:-NUqiJVl4-yEvh6xNmiz:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/7cfaadab01fea620af66bed4153c2bf995b877a9/crates/papyrus_storage/src/state/state_test.rs#L160)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

declared
</blockquote></details>

done

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/599#-NUqiNY75oVa760ZQDy1:-NUqiNY75oVa760ZQDy2:b-ym4zpj) (no related file):*
Commits 15 and 16 remove the validation and the test for those validations.

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r15, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/599#-:-NUu0erq5kVfF_K09VYT:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware)

**Pull request merged**
