### PR TITLE
improve middleware tests

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #892** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/892" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/892?utm_source=stack-comment).

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)* status: all files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLfnKS4AuIepXGLOma:-NaLfnKS4AuIepXGLOmb:b3a13v9) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L49)):*
> ```XML
> }
> 
> async fn call_proxy_request_get_method_in_out(
> ```

Consider separating into 2 functions (batch/single).
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLfz7j4huIYhhtb-ps:-NaLfOxQBqH2fgUXoq3a:bo0h6yh) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L78)):*
> ```XML
>         .body(Body::from(request_body.unwrap()))
>         .unwrap();
>     match proxy_rpc_request(req_no_version).await {
> ```

Consider let-else instead of matching.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLgrd6987W3nSaEDWN:-NaLgrd6987W3nSaEDWO:be6uf9n) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L96)):*
> ```XML
>                     body_batch.iter().for_each(|body| {
>                         assert_eq!(params.to_string(), body.params.unwrap().to_string());
>                     });
> ```

Why not simply
```
for body in body_batch
```



_Code quote:_
```XML
                    body_batch.iter().for_each(|body| {
                        assert_eq!(params.to_string(), body.params.unwrap().to_string());
                    });
```
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLk33AA5DZjUYuh9ou:-NaLk33AA5DZjUYuh9ov:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L139)):*
> ```XML
>     }
>     let join_res = join_all(handles).await;
>     join_res.into_iter().for_each(|res| {
> ```

same



_Code quote:_
```XML
join_res.into_iter().for_each(
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkwVmC7wc9_Z0m4lp:-NaLkwVmC7wc9_Z0m4lq:bmjogu9) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L95)):*
> ```XML
>     let Some(version) = uri_components.get(2) else {
>         // as long as 'deny_requests_with_unsupported_path' middleware is used, this should never happen
>         // but for safety we return an error and not unreachable!()
> ```

Consider logging (using instrument)
___
*[`crates/papyrus_gateway/src/middleware.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkRKqErEKT0HuAnKY:-NaLkRKqErEKT0HuAnKZ:b1fxl3f) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L96)):*
> ```XML
>         // as long as 'deny_requests_with_unsupported_path' middleware is used, this should never happen
>         // but for safety we return an error and not unreachable!()
>         return Err(BoxError::from("Invalid path format"));
> ```

Add the path to the error message.

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)* status: all files reviewed, 5 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLgrd6987W3nSaEDWN:-NaLyDi355zYCgXeW-yX:b2u084f) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not simply
```
for body in body_batch
```
</blockquote></details>

why is it better? I like better the iterator way stylistically
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLk33AA5DZjUYuh9ou:-NaLyNUF56MAsJ2hheYn:b-4nq930) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L139)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

same :)
___
*[`crates/papyrus_gateway/src/middleware.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkwVmC7wc9_Z0m4lp:-NaMgkQy1eLvS31EMsBl:b-mrj9vw) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider logging (using instrument)
</blockquote></details>

did you read the comment? shouldn't get there
___
*[`crates/papyrus_gateway/src/middleware.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkRKqErEKT0HuAnKY:-NaMgpAHDw6Z7ldNFO4q:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add the path to the error message.
</blockquote></details>

same

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)* status: all files reviewed, 5 unresolved discussions (waiting on @nagmo-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLgrd6987W3nSaEDWN:-NaMjHpf2pl6vHy-O35G:b-ukv320) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L96)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why is it better? I like better the iterator way stylistically
</blockquote></details>

You got to be kidding me.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkwVmC7wc9_Z0m4lp:-NaMjX6C4_KMm89BEASq:bg2brpn) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L95)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

did you read the comment? shouldn't get there
</blockquote></details>

Yeah I think we should call unreachable, but if returning an error let's at least log it

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLfnKS4AuIepXGLOma:-Na_PHfq6ZmoBjuXT_wC:b-s1vowj) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider separating into 2 functions (batch/single).
</blockquote></details>

did some refactoring. see if it makes more sense now. I don't want to duplicate the logic
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLgrd6987W3nSaEDWN:-Na_LEIxATAtUsLoqKqJ:b-30ufpk) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/gateway_test.rs#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You got to be kidding me.
</blockquote></details>

AFAIK in compiled languages you get performance benefits from using iterators over for loops since the compiler should have good optimizations. I looked it up and I in fact see that it is the case in Rust as well: [Comparing Performance: Loops vs. Iterators](https://doc.rust-lang.org/book/ch13-04-performance.html#comparing-performance-loops-vs-iterators)
___
*[`crates/papyrus_gateway/src/middleware.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/892#-NaLkwVmC7wc9_Z0m4lp:-Na_PZyzB8n1h0k7ZoaA:b32wtd) ([raw file](https://github.com/starkware-libs/papyrus/blob/06d0e2cc965921fa0971565dd13182852aa2c5fe/crates/papyrus_gateway/src/middleware.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yeah I think we should call unreachable, but if returning an error let's at least log it
</blockquote></details>

ok

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/892)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
