### PR TITLE
fix(storage): append_classes can receive classes not from the state diff

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat(storage): add read/write functionality for classes
- fix(storage): append_classes can receive classes not from the state diff

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1875)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1875)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1875#-Nux9WGX69b5_y6k_dwJ:-Nux9WGY--6cTNhAqf7Q:bnqhdr9) (no related file):*
Why is this test needed?

___
___
*[`crates/papyrus_storage/src/class.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1875#-Nux9Ac26epNyMg_PLU9:-Nux9Ac26epNyMg_PLUA:b-4q67gy) ([raw file](https://github.com/starkware-libs/papyrus/blob/0db29f9e27db90f39592b3b80dec4b77766a69e5/crates/papyrus_storage/src/class.rs#L7)):*
> ```XML
> //!
> //! Note that the written classes' hashes should be the same as those declared in the block's state
> //! diff and deploy transactions. This is not validated but breaking this will cause the DB to be
> ```

Add `deploy transactions (now deprecated)`



_Code quote:_
```XML
deploy transactions
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1875)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1875#-Nux9WGX69b5_y6k_dwJ:-NuxHApuBhtf8LFteo7w:b-ksqwzm) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is this test needed?
</blockquote></details>

In case we split the deprecated classes table, we'll need to change where do we update the blocks table

___

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1875)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/class.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1875#-Nux9Ac26epNyMg_PLU9:-Nux_nnH2kItWSIUCuD6:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0db29f9e27db90f39592b3b80dec4b77766a69e5/crates/papyrus_storage/src/class.rs#L7)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add `deploy transactions (now deprecated)`
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1875#-:-NuxcKEDCQmRV2MpwlIp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
