### PR TITLE
feat(sync): update pending only when it's more advanced

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1288)

### CODE REVIEW

**Review by yair-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1288)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_sync/src/lib.rs` line 901 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1288#-Nh5lAuO6gA1AKikntrI:-Nh5lAuO6gA1AKikntrJ:byzm3zj) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4543e93b5404e58018602fed4c3f0041bfa8fd9/crates/papyrus_sync/src/lib.rs#L901)):*
> ```XML
>     loop {
>         let new_pending_data = pending_source.get_pending_data().await?;
>         if new_pending_data.block.parent_block_hash != latest_block_hash {
> ```

Consider adding a log message

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1288)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_sync/src/lib.rs` line 902 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1288#-Nh5me4X1GV3YJi7FZl9:-Nh5me4X1GV3YJi7FZlA:bva28lg) ([raw file](https://github.com/starkware-libs/papyrus/blob/6bdd89abfe32386377204b64b489ad9686c23f1e/crates/papyrus_sync/src/lib.rs#L902)):*
> ```XML
>         let new_pending_data = pending_source.get_pending_data().await?;
>         if new_pending_data.block.parent_block_hash != latest_block_hash {
>             debug!("A new block was found. Stopping pending sync.");
> ```

Is this the correct message? I thought something like "Node not fully synced, stopping pending sync."



_Code quote:_
```XML
A new block was found. Stopping pending sync.
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 902 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1288#-Nh5me4X1GV3YJi7FZl9:-Nh5pRzN4mW4MpirXLmx:b-9duihf) ([raw file](https://github.com/starkware-libs/papyrus/blob/6bdd89abfe32386377204b64b489ad9686c23f1e/crates/papyrus_sync/src/lib.rs#L902)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this the correct message? I thought something like "Node not fully synced, stopping pending sync."
</blockquote></details>

The pending sync only starts when the node is fully synced, so this message is ok

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/lib.rs` line 902 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1288#-Nh5me4X1GV3YJi7FZl9:-Nh5rYOHBo_ViTFnj8Uw:b32wtd) ([raw file](https://github.com/starkware-libs/papyrus/blob/6bdd89abfe32386377204b64b489ad9686c23f1e/crates/papyrus_sync/src/lib.rs#L902)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The pending sync only starts when the node is fully synced, so this message is ok
</blockquote></details>

ok

**Pull request merged**
