### PR TITLE
feat(storage, monitoring): mmap files stats

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1830)

### CODE REVIEW

**Comment by yair-starkware** [comment]
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1830#-NtjVIxDBG4YVsKeL-Rl:-NtjVIxE1GstDUoNe9uC:b-o21gsy) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b2f54a9b1307c9b987ba6b2cb13be2c4fb5e3dc/crates/papyrus_storage/src/mmap_file/mod.rs#L173)):*
> ```XML
>     offset: usize,
> ) -> MmapFileResult<(FileHandler<V, RW>, FileHandler<V, RO>)> {
>     let file = OpenOptions::new().read(true).write(true).create(true).truncate(false).open(path)?;
> ```

Fixing a clippy error



_Code quote:_
```XML
truncate(false).
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1830)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1830#-Nu-A7Bv1etmHFhS-Ner:-Nu-A7Bv1etmHFhS-Nes:b-tzf7x1) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b2f54a9b1307c9b987ba6b2cb13be2c4fb5e3dc/crates/papyrus_storage/src/lib.rs#L681)):*
> ```XML
>     pub fn stats(&self) -> HashMap<String, MMapFileStats> {
>         HashMap::from_iter([
>             ("thin_state_diff".to_string(), self.thin_state_diff.stats()),
> ```

Please add a TODO to make these strings consts.



_Code quote:_
```XML
"thin_state_diff"
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1830)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1830#-Nu-A7Bv1etmHFhS-Ner:-Nu45V3Z1E3OvJoL5laj:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8b2f54a9b1307c9b987ba6b2cb13be2c4fb5e3dc/crates/papyrus_storage/src/lib.rs#L681)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a TODO to make these strings consts.
</blockquote></details>

done

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1830#-:-NuSpdvw7iLIGLb5UEB8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
