### PR TITLE
feat(network): add conversion from protobuf::receipt::DeployAccount to sn api

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2047)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2047)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynRhce8IYAQOjEKua3:-NynRhcfCgErEGEwa8im:b-zcmdq9) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L20)):*
> ```XML
> 
> // TODO: use the conversion in Starknet api once its upgraded
> fn try_from_starkfelt_to_u128(felt: StarkFelt) -> Result<u128, &'static str> {
> ```

No need to duplicate this. Move the original function to common.rs, make it pub(super) and import it here and in transaction.proto
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynSyWk7FZJWVt2WyZw:-NynSyWk7FZJWVt2WyZx:b-kn55rq) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L35)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::receipt::DeployAccount> for DeployAccountTransactionOutput {
> ```

Add comment that it will return Output with empty events
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynStuH-a9QIHBtZsfz:-NynStuH-a9QIHBtZsg-:bmixj27) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L38)):*
> ```XML
>     type Error = ProtobufConversionError;
>     fn try_from(value: protobuf::receipt::DeployAccount) -> Result<Self, Self::Error> {
>         let common = value.common.clone().ok_or(ProtobufConversionError::MissingField {
> ```

Why clone?
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynSoIZ6tj7CED8fS61:-NynSoIZ6tj7CED8fS62:b-bj7jz) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L74)):*
> ```XML
>                 StarkHash::new(felt).expect("converting StarkHash from [u8; 32] failed"),
>             )
>             .expect("converting PatriciaKey from StarkHash failed"),
> ```

Here you're in TryFrom, you can return error

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2047)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynRhce8IYAQOjEKua3:-NyneejHEFTFU4NP2bV7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to duplicate this. Move the original function to common.rs, make it pub(super) and import it here and in transaction.proto
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynSyWk7FZJWVt2WyZw:-NyneguVAAU4MARm7UW7:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add comment that it will return Output with empty events
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynStuH-a9QIHBtZsfz:-Nyneikd-F0WlwbiJ7ku:b-yfjhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why clone?
</blockquote></details>

there is no need, fixed
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynSoIZ6tj7CED8fS61:-Nynep8q2dQxcRp4UMKw:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c978966a14aa494f81e275035da74810b42aa8/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L74)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Here you're in TryFrom, you can return error
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2047)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynxgUa6a9klVEqP4dZ:-NynxgUa6a9klVEqP4d_:b2olfrz) ([raw file](https://github.com/starkware-libs/papyrus/blob/79dad8a96718f0808ce894dc6262d7dcf8357ae2/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L20)):*
> ```XML
> use crate::protobuf_messages::protobuf::{self};
> 
> // the output will have an empty events vec
> ```

Capitalize (the -> The)
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-Nynxqhy5jpWWQJcM3ae:-Nynxqhy5jpWWQJcM3af:b-enmdv2) ([raw file](https://github.com/starkware-libs/papyrus/blob/79dad8a96718f0808ce894dc6262d7dcf8357ae2/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L53)):*
> ```XML
>             })?;
>         let felt = StarkFelt::try_from(contract_address)?;
>         let contract_address = if let Ok(patricia_key) = PatriciaKey::try_from(felt) {
> ```

Use map_err and ? instead.
___
*[`crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-Nyny1EJ3s4pK8xwpNrR:-Nyny1EJ3s4pK8xwpNrS:b-ehqtkk) ([raw file](https://github.com/starkware-libs/papyrus/blob/79dad8a96718f0808ce894dc6262d7dcf8357ae2/crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs#L57)):*
> ```XML
>         } else {
>             return Err(ProtobufConversionError::OutOfRangeValue {
>                 type_description: "Felt252",
> ```

Put here "PatriciaKey"

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2047)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2047#-NynyL0D2HJJT-mNBZJ5:-NynyL0E8ppKAd_wdpAG:b-vrqmnb) (no related file):*
There's a bug that caused me to approve the PR so I'm blocking here

___

**Pull request merged**
