### PR TITLE
Documentation for the base layer in the storage

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/839)

### CODE REVIEW

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/839)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/base_layer.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/839#-N_93_Xv-2WphMUBJYFg:-N_93_Xv-2WphMUBJYFh:b-reb617) ([raw file](https://github.com/starkware-libs/papyrus/blob/b3fc4c749d2b40d427775a7b883bd8fd1ed4a09f/crates/papyrus_storage/src/base_layer.rs#L30)):*
> ```XML
> //! writer
> //!     .begin_rw_txn()?                                    // Start a RW transaction.
> //!     .update_base_layer_block_marker(&BlockNumber(0))?    //Update the base layer block marker.
> ```

Change the block number to a value other than zero. The default value is zero so also without updating the marker, the assert will not fail.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/839)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/base_layer.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/839#-N_93_Xv-2WphMUBJYFg:-N_9eLty0JsvQnGeZFLm:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b3fc4c749d2b40d427775a7b883bd8fd1ed4a09f/crates/papyrus_storage/src/base_layer.rs#L30)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Change the block number to a value other than zero. The default value is zero so also without updating the marker, the assert will not fail.
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/839)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/base_layer.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/839#-N_Akp5w6wcyE4V3b8wi:-N_Akp5w6wcyE4V3b8wj:b-j8m5lg) ([raw file](https://github.com/starkware-libs/papyrus/blob/69753c4787afd13b95319d90ae63d59d59121b56/crates/papyrus_storage/src/base_layer.rs#L22)):*
> ```XML
> //! # let db_config = DbConfig {
> //! #     path_prefix: dir,
> //! #     chain_id: ChainId("SN_MAIN".to_owned()),
> ```

Consider `to_string` everywhere (or string::from, I don't remember which one we use)



_Code quote:_
```XML
.to_owned()
```

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
