### PR TITLE
feat(sync): central class cache

### PR DESCRIPTION
**Pull request by dan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware)

___
*[`config/default_config.json` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsqvFs63yIa51U3PB8:-NgsqvFs63yIa51U3PB9:bbekequ) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/config/default_config.json#L13)):*
> ```JSON
>   },
>   "central.class_cache_size": {
>     "description": "Size of class cache, must be a natural number.",
> ```

Not everyone's a mathematician (and within the mathematicians there's a debate if 0 is natural)
Write positive and/or non-zero instead
___
*[`crates/papyrus_sync/src/sources/central.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsrV_G131PRJzw8WqE:-NgsrV_G131PRJzw8WqF:bekfcyx) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L40)):*
> ```XML
> };
> use starknet_client::{ClientCreationError, RetryConfig};
> use tokio::sync::Mutex;
> ```

Describe in a comment why do we use tokio mutex and not std
___
*[`crates/papyrus_sync/src/sources/central.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsrTGq3Jku936oIR8J:-NgsrTGq3Jku936oIR8K:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L55)):*
> ```XML
>     pub max_state_updates_to_store_in_memory: usize,
>     pub max_classes_to_download: usize,
>     // TODO(dan): validate that class_cache_size is a natural number.
> ```

Same here
___
*[`crates/papyrus_sync/src/sources/central.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-Ngsre78EwGHYI0cesKo:-Ngsre78EwGHYI0cesKp:b-gncy1v) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L69)):*
> ```XML
>             max_state_updates_to_store_in_memory: 20,
>             max_classes_to_download: 20,
>             class_cache_size: 30,
> ```

Does it make sense that class_cache_size is bigger than max_classes_to_download?
___
*[`crates/papyrus_sync/src/sources/central.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-Ngsrj_HBm1xAKTMvA3f:-Ngsrj_HBm1xAKTMvA3g:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L122)):*
> ```XML
>                 "class_cache_size",
>                 &self.class_cache_size,
>                 "Size of class cache, must be a natural number.",
> ```

Same here
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 457 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-Ngsrwum5kXIKSdm6aDO:-Ngsrwum5kXIKSdm6aDP:bheteae) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central_test.rs#L457)):*
> ```XML
> 
> fn get_test_class_cache() -> Arc<Mutex<LruCache<ClassHash, ApiContractClass>>> {
>     Arc::from(Mutex::new(LruCache::new(NonZeroUsize::new(2).expect("2 should not be zero."))))
> ```

IMO you can unwrap here instead of writing this message

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`config/default_config.json` line 13 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsqvFs63yIa51U3PB8:-NgsxzS0CAd7na7hbzRj:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/config/default_config.json#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Not everyone's a mathematician (and within the mathematicians there's a debate if 0 is natural)
Write positive and/or non-zero instead
</blockquote></details>

Done.
___
*[`crates/papyrus_sync/src/sources/central.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsrV_G131PRJzw8WqE:-Ngt02Qx4Qmg0f76NToS:bc1ogyq) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Describe in a comment why do we use tokio mutex and not std
</blockquote></details>

IMO it is clear from the code. Can you suggest a comment?
___
*[`crates/papyrus_sync/src/sources/central.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-Ngsre78EwGHYI0cesKo:-NgsyxC5-K_lupctdows:b2nhswy) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Does it make sense that class_cache_size is bigger than max_classes_to_download?
</blockquote></details>

Yes
___
*[`crates/papyrus_sync/src/sources/central_test.rs` line 457 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-Ngsrwum5kXIKSdm6aDO:-NgszAMuB4PaLK3fGOd9:bmepcco) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central_test.rs#L457)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO you can unwrap here instead of writing this message
</blockquote></details>

copilot :)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsrV_G131PRJzw8WqE:-Ngt0js50ZFcFn296jGK:b714y9b) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L40)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO it is clear from the code. Can you suggest a comment?
</blockquote></details>

I don't know what's the reason :sweat_smile:

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_sync/src/sources/central.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-NgsrV_G131PRJzw8WqE:-NgteL4P0ofUd_-GOm3p:bhx4nmh) ([raw file](https://github.com/starkware-libs/papyrus/blob/af94b430fc7fbbf085b03a50c518fb99c80c52df/crates/papyrus_sync/src/sources/central.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't know what's the reason :sweat_smile:
</blockquote></details>

Reconsidered, since we don't lock across await and waiting for the lock shouldn't take much time I switched to sync::Mutex

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1279#-:-Nh0lloe6xWWW_S7BQeQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
