### PR TITLE
chore: update clippy errors for 06.16.2024

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2110)

### CODE REVIEW

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2110#-:-O-Uqrc6AsEZ_MD5CFjQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

**Comment by yair-starkware** [comment]
*[`crates/papyrus_network/src/db_executor/mod.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2110#-O-VaKBJ3LsqTpM_BmPV:-O-VaKBK0cX2UV3zURHv:b-tyzo63) ([raw file](https://github.com/starkware-libs/papyrus/blob/14ee3bba7da9507212468c80488298f0e14b61d9/crates/papyrus_network/src/db_executor/mod.rs#L263)):*
> ```XML
> 
> // A wrapper struct for Vec<StateDiffsResponse> so that we can implement traits for it.
> pub struct StateDiffsResponseVec(pub Vec<protobuf::StateDiffsResponse>);
> ```

Why do you delete this?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2110)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2110#-O-VaKBJ3LsqTpM_BmPV:-O-VaeOR4iNW00cQdj3P:b9ipbdn) ([raw file](https://github.com/starkware-libs/papyrus/blob/14ee3bba7da9507212468c80488298f0e14b61d9/crates/papyrus_network/src/db_executor/mod.rs#L263)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do you delete this?
</blockquote></details>

We need to remove this regardless (We forgot erasing when we added something else instead)
Clippy said there's an error here so I've decided to delete this instead of fixing the error

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2110)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @DvirYo-starkware)

**Pull request merged**
