### PR TITLE
feat(network): add network config to main

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1670?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1663** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1663?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1670** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1670?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1670?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`config/default_config.json` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-Npt-elN9F9uM0TlsKty:-Npt-elN9F9uM0TlsKtz:bk64t6l) ([raw file](https://github.com/starkware-libs/papyrus/blob/7eba7fc1bc2eefb954a9d7896fc5dbfb858a6b59/config/default_config.json#L100)):*
> ```JSON
>     "description": "Flag for an optional field",
>     "privacy": "TemporaryValue",
>     "value": false
> ```

Default should be true ( @dan-starkware said that the network should be off by default)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`config/default_config.json` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-Npt-elN9F9uM0TlsKty:-NptZT6w2FOBELvWdsca:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/7eba7fc1bc2eefb954a9d7896fc5dbfb858a6b59/config/default_config.json#L100)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Default should be true ( @dan-starkware said that the network should be off by default)
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-:-Npxbf-_7vBiqQsx-o3V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by ShahakShama — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: all files reviewed, 3 unresolved discussions (waiting on @nagmo-starkware)

___
*[`config/default_config.json` line 97 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqY-pAp-spmFhOZhbz6:-NqY-pAp-spmFhOZhbz7:b-7nc7l1) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/config/default_config.json#L97)):*
> ```JSON
>     "privacy": "Public"
>   },
>   "network.#is_none": {
> ```

Making sure - you used the dump_config script to edit this file, right? not manually
___
*[`crates/papyrus_node/Cargo.toml` line 25 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqXzSWtEqfq1EpFqBZv:-NqXzSWu-40VpyE8dEE6:b-x641aq) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/crates/papyrus_node/Cargo.toml#L25)):*
> ```TOML
> papyrus_common = { path = "../papyrus_common", version = "0.3.0-rc.0" }
> papyrus_monitoring_gateway = { path = "../papyrus_monitoring_gateway" }
> papyrus_network = { path = "../papyrus_network", version = "0.3.0-dev.1" }
> ```

Why is this different from the rest of the crates?



_Code quote:_
```TOML
"0.3.0-dev.1"
```
___
*[`crates/papyrus_node/src/main.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqY--LzCSlsrgOrcfV3:-NqY--LzCSlsrgOrcfV4:b-wfnq7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/crates/papyrus_node/src/main.rs#L160)):*
> ```XML
> 
> async fn run_network(config: Option<NetworkConfig>, storage_reader: StorageReader) {
>     let Some(network_config) = config else { return pending().await };
> ```

I think both here and in the sync the check whether the config is Some should be from outside the function - like the storage_metric_handle

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`config/default_config.json` line 97 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqY-pAp-spmFhOZhbz6:-NqaSRFh6BgUnI5m15MD:b2nign6) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/config/default_config.json#L97)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Making sure - you used the dump_config script to edit this file, right? not manually
</blockquote></details>

yes
___
*[`crates/papyrus_node/Cargo.toml` line 25 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqXzSWtEqfq1EpFqBZv:-NqaTFQLC0FXZE0cHG5u:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/crates/papyrus_node/Cargo.toml#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is this different from the rest of the crates?
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/main.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqY--LzCSlsrgOrcfV3:-NqaTX7E8wVEdvfEJv0m:b-si0x96) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/crates/papyrus_node/src/main.rs#L160)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think both here and in the sync the check whether the config is Some should be from outside the function - like the storage_metric_handle
</blockquote></details>

I don't know if that's the right approach but I do agree that we need to think a bit about cleaning up main.
WDYT about merging this PR as is and creating a new PR after we discuss it?

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-:-NqagBpK9hGHNx1YFJ9u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqY--LzCSlsrgOrcfV3:-Nqag9bH5iwNX-KSOaHI:b32wtd) ([raw file](https://github.com/starkware-libs/papyrus/blob/f8bc620c308f6cf519f78b9b9d5ba632531eb63e/crates/papyrus_node/src/main.rs#L160)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't know if that's the right approach but I do agree that we need to think a bit about cleaning up main.
WDYT about merging this PR as is and creating a new PR after we discuss it?
</blockquote></details>

ok

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-:-Nqgbwtf-r9fkt9dWOE_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`Dockerfile` line 39 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-Nqgb0-447XEZphu9uY2:-Nqgb0-447XEZphu9uY3:b8b9p6j) ([raw file](https://github.com/starkware-libs/papyrus/blob/77ebdf575781e4133c249e8b09ff06240a94076d/Dockerfile#L39)):*
> ```Dockerfile
> WORKDIR /app/
> 
> RUN apt update && apt install -y clang zip unzip
> ```

Why zip?
___
*[`config/default_config.json` line 98 at r9](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-NqgbBQ145MDvMzsx1Hi:-NqgbBQ145MDvMzsx1Hj:b4tmwz0) ([raw file](https://github.com/starkware-libs/papyrus/blob/77ebdf575781e4133c249e8b09ff06240a94076d/config/default_config.json#L98)):*
> ```JSON
>   },
>   "network.#is_none": {
>     "description": "Flag for an optional field",
> ```

Can we improve this description? same for sync.#is_none

**Comment by dan-starkware** [comment]
Please move network config related changes to a preliminary PR

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: 8 of 12 files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware, @ShahakShama, and @yair-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 5 files at r5, 1 of 1 files at r6, 2 of 5 files at r8, 1 of 2 files at r9, 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1670#-Nqgom2RAXkh5mdf4OeL:-Nr5BQLGB8vjPQcyKt7p:b-896fix) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move network config related changes to a preliminary PR
</blockquote></details>

Done.

___

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1670)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Pull request merged**
