### PR TITLE
Yair/execution api

### PR DESCRIPTION
**Pull request by yair-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/794)

### CODE REVIEW

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 5 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/794)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dan-starkware, and @yair-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZQ88CR4CajSPTNsU_F:-NZQ88CR4CajSPTNsU_G:bj9mk9r) ([raw file](https://github.com/starkware-libs/papyrus/blob/75e45c41a79a1f5cf6535288eaf751c775e69180/crates/papyrus_execution/src/execution_test.rs#L48)):*
> ```XML
> 
> fn prepare_storage(mut storage_writer: StorageWriter) {
>     let class_hash0 = ClassHash(StarkFelt::from(2u128));
> ```

consider: 2u128.into()
___
*[`crates/papyrus_execution/src/state_reader.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZPXuZO9-WAIsgPI2yI:-NZPXuZO9-WAIsgPI2yJ:b-pedlmx) ([raw file](https://github.com/starkware-libs/papyrus/blob/a0e7e4354c31945e103fe02f5abb35b8e1c0b9e4/crates/papyrus_execution/src/state_reader.rs#L38)):*
> ```XML
>             .map_err(|err| StateError::StateReadError(err.to_string()))?
>             .get_nonce_at(self.state_number, &contract_address)
>             .map_err(|err| StateError::StateReadError(err.to_string()))?
> ```

the same mapping is performed in multiple places, consider using a function for that.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/794)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @dan-starkware)

___
*[`crates/papyrus_execution/src/execution_test.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZQ88CR4CajSPTNsU_F:-NZevgaz7UsttaFfQjjc:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/75e45c41a79a1f5cf6535288eaf751c775e69180/crates/papyrus_execution/src/execution_test.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider: 2u128.into()
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/state_reader.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZPXuZO9-WAIsgPI2yI:-NZeverxAO_vqlCoJ8AC:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a0e7e4354c31945e103fe02f5abb35b8e1c0b9e4/crates/papyrus_execution/src/state_reader.rs#L38)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

the same mapping is performed in multiple places, consider using a function for that.
</blockquote></details>

done

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/794)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5, @DvirYo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZzLOjk9wOYv3FB5-Pf:-NZzLOjk9wOYv3FB5-Pg:b4sntv8) (no related file):*
Please better document.

___
___
*[`crates/papyrus_execution/src/execution_test.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZzKEh1CLVJYp3zlYDV:-NZzKEh1CLVJYp3zlYDW:b-vjjv6p) ([raw file](https://github.com/starkware-libs/papyrus/blob/11a408dcac003237cef460160256aea9fb254452/crates/papyrus_execution/src/execution_test.rs#L33)):*
> ```XML
> // todo(yair): Consider saving the json of the result instead of doing this process.
> fn get_test_deprecated_contract_class() -> DeprecatedContractClass {
>     let mut raw_contract_class = read_json_file("deprecated_class.json");
> ```

Seems that the reference casm files are reverted.



_Code quote:_
```XML
read_json_file("deprecated_class.json")
```

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/794)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5, @DvirYo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZzLOjk9wOYv3FB5-Pf:-NZzLOjk9wOYv3FB5-Pg:b4sntv8) (no related file):*
Please better document.

___
___
*[`crates/papyrus_execution/src/execution_test.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/794#-NZzKEh1CLVJYp3zlYDV:-NZzKEh1CLVJYp3zlYDW:b-vjjv6p) ([raw file](https://github.com/starkware-libs/papyrus/blob/11a408dcac003237cef460160256aea9fb254452/crates/papyrus_execution/src/execution_test.rs#L33)):*
> ```XML
> // todo(yair): Consider saving the json of the result instead of doing this process.
> fn get_test_deprecated_contract_class() -> DeprecatedContractClass {
>     let mut raw_contract_class = read_json_file("deprecated_class.json");
> ```

Seems that the reference casm files are reverted.



_Code quote:_
```XML
read_json_file("deprecated_class.json")
```

**Pull request closed without merging**
