### PR TITLE
feat(network): add register_broadcast_subscribers without connecting to behaviour

### PR DESCRIPTION
**Pull request by ShahakShama**
- refactor(network): mixed event contains the outputting behaviour instead of notified behaviour
- feat(network): add broadcast behaviour with unimplemented
- feat(network): connect broadcast behaviour to mixed behaviour
- feat(network): add register_broadcast_subscribers without connecting to behaviour

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1983)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1983)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSpu25TK8T5dKcJAS:-NxvSpu25TK8T5dKcJAT:bcwosrj) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L17)):*
> ```XML
> use papyrus_common::metrics as papyrus_metrics;
> use papyrus_storage::StorageReader;
> use streamed_bytes::Bytes;
> ```

Why do we have this type? I see it's just `Vec<u8>`



_Code quote:_
```XML
use streamed_bytes::Bytes;
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSBUk1WknY2jv9hl-:-NxvSBUk1WknY2jv9hl0:bd6i89b) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L102)):*
> ```XML
>         &mut self,
>         topic: Topic,
>         buffer_size: usize,
> ```

How does one determine how large to make `buffer_size`? Does this implicitly limit the max message size (i.e., if I want to handle a proto up to size 1MB, I need the buffer to be 1MB?)? Do we want to add a comment?
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvRtoOEQjcJc9JkSi3:-NxvRtoOEQjcJc9JkSi4:b-pkfga6) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L117)):*
> ```XML
>         if insert_result.is_some() {
>             panic!("Topic {} was registered twice", topic);
>         }
> ```

Do we ever imagine a world where 2 components want to use the same topic? Therefore, they would want something like "register_or_get"?



_Code quote:_
```XML
        if insert_result.is_some() {
            panic!("Topic {} was registered twice", topic);
        }
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1983)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSpu25TK8T5dKcJAS:-NxvVe2E64z5oFppOzMw:b-bjplsj) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L17)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why do we have this type? I see it's just `Vec<u8>`
</blockquote></details>

It's a type alias
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSBUk1WknY2jv9hl-:-NxvVDKf0PFMRz4z-E2n:bsw7z20) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L102)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

How does one determine how large to make `buffer_size`? Does this implicitly limit the max message size (i.e., if I want to handle a proto up to size 1MB, I need the buffer to be 1MB?)? Do we want to add a comment?
</blockquote></details>

They should take the amount of RAM memory they want to allocate for this topic and divide it by the expected message size.

IMO we should just use unbounded channels for now. Maybe now is the time to push for it
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvRtoOEQjcJc9JkSi3:-NxvV1nh2VXSSrTeJf3D:b-x8szi8) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L117)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Do we ever imagine a world where 2 components want to use the same topic? Therefore, they would want something like "register_or_get"?
</blockquote></details>

I don't think it's possible because you can't clone a receiver channel so they will each need to read from the same receiver

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1983)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSpu25TK8T5dKcJAS:-Nxvaffr02BGyU4qMOY3:bms9wgv) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's a type alias
</blockquote></details>

Yes, why? We are adding an extra layer of abstraction that makes it harder to know what the actual type is. For what reason?
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSBUk1WknY2jv9hl-:-Nxvaq7z5ogvnxd3gYsh:b-2cmnvj) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L102)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

They should take the amount of RAM memory they want to allocate for this topic and divide it by the expected message size.

IMO we should just use unbounded channels for now. Maybe now is the time to push for it
</blockquote></details>

Oh right. Yeah, why don't we use unbounded (I guess there is a performance cost probably)? Do you want to take that up with Dan I can unblock here, as that seems out of scope for now? Or do we want to gradually shift to unbounded and start here?
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvRtoOEQjcJc9JkSi3:-Nxvb2H0AAA-dp3KxoBK:b74y4kn) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't think it's possible because you can't clone a receiver channel so they will each need to read from the same receiver
</blockquote></details>

Oh this is not an option now at all. ok

**Review by matan-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1983)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1983#-NxvSBUk1WknY2jv9hl-:-Ny-FJSl5nPEsdVVQlbO:bk3kqv0) ([raw file](https://github.com/starkware-libs/papyrus/blob/f4c45c059072b6d7f578c9087fc71d93be38f468/crates/papyrus_network/src/network_manager/mod.rs#L102)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Oh right. Yeah, why don't we use unbounded (I guess there is a performance cost probably)? Do you want to take that up with Dan I can unblock here, as that seems out of scope for now? Or do we want to gradually shift to unbounded and start here?
</blockquote></details>

Discussed f2f that we will leave this as we expect to move towards bounded channels in the future and Shahak will just add some info to the function level comment.

**Pull request closed without merging**
