### PR TITLE
chore: dump_declared_classes cleanup

### PR DESCRIPTION
**Pull request by Yael-Starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1369)

### CODE REVIEW

**Review by OmriEshhar1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/dump_declared_classes/README.md` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1369#-NihoXndD7iuKji4xr1v:-NihoXndD7iuKji4xr1w:bzcndyk) ([raw file](https://github.com/starkware-libs/papyrus/blob/962b414100ad3950eb7c04c78642297c3318b61f/crates/dump_declared_classes/README.md#L1)):*
> ```Markdown
> # Dump Declared Classes Tool
> ```

Don't you want to put the information from this deleted README file in another place?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1369)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

___
*[`crates/dump_declared_classes/README.md` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1369#-NihoXndD7iuKji4xr1v:-NiiB3i7ArwcJ8Mk_2g0:bl7tnra) ([raw file](https://github.com/starkware-libs/papyrus/blob/962b414100ad3950eb7c04c78642297c3318b61f/crates/dump_declared_classes/README.md#L1)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Don't you want to put the information from this deleted README file in another place?
</blockquote></details>

good point, done.

**Review by OmriEshhar1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1369#-:-NiiGnEs091C9YhRfnEM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
