### PR TITLE
feat(consensus): create the m2 state machine skeleton, which doesn't actually handle events

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2159)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2161** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2161?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2159** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2159?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2159)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OOuOCDlyr2osy8pBS:-O0OOuOCDlyr2osy8pBT:b-7tle4o) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/lib.rs#L22)):*
> ```XML
> #[allow(missing_docs)]
> pub mod single_height_consensus;
> #[allow(missing_docs)]
> ```

Consider documenting instead (or whitelist on finer granularity, not whole modules)



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OG97298HNhGy33fM4:-O0OG97298HNhGy33fM5:bymnlnl) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/state_machine.rs#L10)):*
> ```XML
> #[derive(Debug, Clone, PartialEq)]
> pub enum StateMachineEvent {
>     // BlockHash, Round
> ```

Consider an alias 



_Code quote:_
```XML
Round
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OG5ZB0LxA8GEoFcnt:-O0OG5ZB0LxA8GEoFcnu:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/state_machine.rs#L12)):*
> ```XML
>     // BlockHash, Round
>     GetProposal(Option<BlockHash>, u32),
>     // BlockHash, Round, ValidRound
> ```


___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OGPQ4CkX7UF9_sh_t:-O0OGPQ4CkX7UF9_sh_u:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/state_machine.rs#L27)):*
> ```XML
> }
> 
> /// State Machine for Milestone 2. Major assumptions:
> ```





_Suggestion:_
```XML
State Machine. Major assumptions:
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OOh44982KW3lxUaKB:-O0OOh44982KW3lxUaKC:bcr64k7) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/state_machine.rs#L79)):*
> ```XML
> 
>     pub fn handle_event(&mut self, event: StateMachineEvent) -> Vec<StateMachineEvent> {
>         // Mimic LOC 18 in the paper; the state machine doesn't handle any events until `getValue`
> ```

Consider adding a proper reference.



_Code quote:_
```XML
Mimic LOC 18 in the paper
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2159#-O0OOQloAW4EycX0O8r4:-O0OOQloAW4EycX0O8r5:bmt5uhh) ([raw file](https://github.com/starkware-libs/papyrus/blob/18c7fa851447629e5e6b31adaf366a4bf458b300/crates/sequencing/papyrus_consensus/src/state_machine.rs#L84)):*
> ```XML
>             match event {
>                 StateMachineEvent::GetProposal(_, round) if round == self.round => {
>                     self.events_queue.push_front(event);
> ```

Shouldn't we mark that we can handle new events?



_Suggestion:_
```XML
self.events_queue.push_front(event);
self.awaiting_get_proposal = false;
```

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2159)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
