### PR TITLE
refactor(network): replace peeraddrconfig with multiaddress

### PR DESCRIPTION
**Pull request by eitanm-starkware**
refactor(network): replace peeraddrconfig

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1851)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1851)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1851#-NurQ2pJAzVmtRJi5bZP:-NurQ2pJAzVmtRJi5bZQ:b-zf6l5h) (no related file):*
please test this by running two nodes locally and seeing they can sync

___

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1851)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1851#-NurQ2pJAzVmtRJi5bZP:-NvB1RBv7y7hGysIy_1C:b-896fix) (no related file):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please test this by running two nodes locally and seeing they can sync
</blockquote></details>

Done.

___

**Review by nagmo-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1851)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1851#-:-NvlLInt-vifTguG4M8L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
