### PR TITLE
Dvir/loadtest transaction hash

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/569)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/569)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/create_files.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/569#-NRSUubI4RFbTKX67oa4:-NRSUubI4RFbTKX67oa5:bidjh8w) ([raw file](https://github.com/starkware-libs/papyrus/blob/5ac42c1f1de4b7f88f0770ea4b0fec4d96fc570c/crates/papyrus_load_test/src/create_files.rs#L90)):*
> ```XML
>     };
>     vec![block_hash.to_string()]
> }
> ```

Do you know any cleaner way to do the matches in this function?
I want the value inside the enum.
Maybe I should use if let instead?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/569)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_load_test/src/create_files.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/569#-NRSUubI4RFbTKX67oa4:-NRbe19z7N9kf2e4TJsP:babzs1f) ([raw file](https://github.com/starkware-libs/papyrus/blob/5ac42c1f1de4b7f88f0770ea4b0fec4d96fc570c/crates/papyrus_load_test/src/create_files.rs#L90)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We can go around this by using the actual types instead of `serde_json::Value`.

I think that if let is more suitable to cases where it should be applied only once (otherwise you'll have nested ifs?)

Please add informative messages to unreachable and be consistent throughout the code (fn get_block_hash_args uses panic)
</blockquote></details>

1. I don’t think I understand what you mean. Maybe return the serde_json::Value itself instead of String?
3. done.

**Review by dan-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/569#-:-NRc_Aw-BVVLoXkVnO40:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
