### PR TITLE
helm: align image tag, conditional ports

### PR DESCRIPTION
**Pull request by eranreshef-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/765)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/765)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @eranreshef-starkware)

___
*[`deployments/helm/values.yaml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/765#-NYWkdS4C4--_3nTYPAw:-NYWkdS4C4--_3nTYPAx:br6abqr) ([raw file](https://github.com/starkware-libs/papyrus/blob/4dac84c8e5d57690e3df8b2a976e5aaf2681f1ee/deployments/helm/values.yaml#L9)):*
> ```YAML
> image:
>   repository: ghcr.io/starkware-libs/papyrus
>   tag: 0.1.2-alpha
> ```

As generic values, should this remain `dev` ?



_Code quote:_
```YAML
0.1.2-alpha
```

**Comment by eranreshef-starkware** [comment]
*[`deployments/helm/values.yaml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/765#-NYWkdS4C4--_3nTYPAw:-NYYMU1OADAwgVwUpe-d:bgesf80) ([raw file](https://github.com/starkware-libs/papyrus/blob/4dac84c8e5d57690e3df8b2a976e5aaf2681f1ee/deployments/helm/values.yaml#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

As generic values, should this remain `dev` ?
</blockquote></details>

The "official" helm chart should use the latest "official release".
I've added an override under the CI dir which will cause the CI to use the `dev` tag.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eranreshef-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/765#-:-NYwQv-a8UPF0z9J183s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eranreshef-starkware)

**Pull request merged**
