### PR TITLE
chore(consensus): allow running multiple simulations of consensus

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2227)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2227)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qjrsy3zTYQDVS2Ed6:-O1qjrsy3zTYQDVS2Ed7:bodyc8c) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L99)):*
> ```Python
> def build_node(base_layer_node_url, temp_dir, num_validators, i):
> 
>     monitoring_gateway_server_port = find_free_port()
> ```

Why the empty line?



_Suggestion:_
```Python
def build_node(base_layer_node_url, temp_dir, num_validators, i):
    monitoring_gateway_server_port = find_free_port()
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qjvA1486_ttIyvAg-:-O1qjvA1486_ttIyvAg0:b2n1glk) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L100)):*
> ```Python
> 
>     monitoring_gateway_server_port = find_free_port()
>     tcp_port = BOOTNODE_TCP_PORT if i == 1 else find_free_port()
> ```

Let's create a variable so the code is self documenting (use below also)



_Suggestion:_
```Python
    is_bootstrap = (i == 1)
    tcp_port = BOOTNODE_TCP_PORT if is_bootstrap else find_free_port()
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qkOF3-L6GzWmMMPX0:-O1qkOF3-L6GzWmMMPX1:bgeto58) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L116)):*
> ```Python
> 
>     if i == 1:
>         specific_command = f"--network.secret_key {SECRET_KEY} "
> ```

let's just create `command` not `common_command` and do `command += XXX`



_Code quote:_
```Python
        specific_command = f"--network.secret_key {SECRET_KEY} "
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 151 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qktEn-k7Hh8fC0vkY:-O1qktEo4lSHobeYSc_g:buk2xl2) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L151)):*
> ```Python
> 
>     # Ensure validator 0 runs last
>     nodes.append(build_node(base_layer_node_url, temp_dir, num_validators, 0))
> ```

We already have the comment at the top of the function, so let's keep these terse.



_Suggestion:_
```Python
    nodes.append(build_node(base_layer_node_url, temp_dir, num_validators, 1))  # Bootstrap

    for i in range(2, num_validators):
        nodes.append(build_node(base_layer_node_url, temp_dir, num_validators, i))

    nodes.append(build_node(base_layer_node_url, temp_dir, num_validators, 0))  # Proposer
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2227)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qjrsy3zTYQDVS2Ed6:-O1u6StC-CohTcoOj74D:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L99)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why the empty line?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 100 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qjvA1486_ttIyvAg-:-O1u6T7lAxGjclv_VUnk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L100)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's create a variable so the code is self documenting (use below also)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 116 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qkOF3-L6GzWmMMPX0:-O1u6U7v5wl0iQJednjz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L116)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

let's just create `command` not `common_command` and do `command += XXX`
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 151 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-O1qktEn-k7Hh8fC0vkY:-O1u6UsuBolibVaCKvFK:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/9f0ea571e26d90c4ece67950bf221c5bbeea2b37/crates/sequencing/papyrus_consensus/run_consensus.py#L151)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We already have the comment at the top of the function, so let's keep these terse.
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2227)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by matan-starkware — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2227#-:-O2OQdS31l39T3a6EXTN:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
