### PR TITLE
feat(network): get data type dynamically based on protocol name

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1791)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1791?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1791** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1791?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1790?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nagmo-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1791)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1791#-NsP2mIH7vc9plFpS8-n:-NsP2mIH7vc9plFpS8-o:bti6yok) ([raw file](https://github.com/starkware-libs/papyrus/blob/0885f07bce6a4d65e89b696716c5b0d0fe4a06b9/crates/papyrus_network/src/lib.rs#L131)):*
> ```XML
> 
> #[derive(thiserror::Error, Debug)]
> pub enum ProtocolConversionError {
> ```

Consider defining this as a struct until we'll have 2 or more variants. The struct can be called UnknownProtocolError or UnknownProtocolConversionError

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1791#-:-NsbmwxtEfFa9-70-1oB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
