### PR TITLE
fix(network): read_message returns None if EOF instead of empty message

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1212)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1212)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/messages/messages_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1212#-NfPY9nE5bvdSSkTCyI7:-NfPY9nE5bvdSSkTCyI8:bhxw4ov) ([raw file](https://github.com/starkware-libs/papyrus/blob/5509315b39b7e4f483c6c4e1855fa85c419255cd/crates/papyrus_network/src/messages/messages_test.rs#L23)):*
> ```XML
> 
> #[tokio::test]
> async fn read_when_other_stream_is_closed_returns_none() {
> ```

name is confusing maybe: `when_reading_and_other_stream_is_closed_return_none`
___
*[`crates/papyrus_network/src/messages/messages_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1212#-NfPYLQ7-CXQ1PTEJH11:-NfPYLQ7-CXQ1PTEJH12:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/5509315b39b7e4f483c6c4e1855fa85c419255cd/crates/papyrus_network/src/messages/messages_test.rs#L30)):*
> ```XML
> 
> #[tokio::test]
> async fn read_when_other_stream_didnt_send_returns_pending() {
> ```

same
___
*[`crates/papyrus_network/src/messages/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1212#-NfPYTUnCnl0BMFlnqx0:-NfPYTUnCnl0BMFlnqx1:bntii7p) ([raw file](https://github.com/starkware-libs/papyrus/blob/5509315b39b7e4f483c6c4e1855fa85c419255cd/crates/papyrus_network/src/messages/mod.rs#L34)):*
> ```XML
> ) -> Result<Option<T>, io::Error> {
>     let buf = read_length_prefixed(&mut io, MAX_MESSAGE_SIZE).await?;
>     // read_length_prefixed returns an empty vec if it reaches EOF. We opened an issue in libp2p to
> ```

as we said. add conclusion as a todo

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1212)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_network/src/messages/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1212#-NfPYTUnCnl0BMFlnqx0:-NfPbGrOAStrju-XrQru:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/5509315b39b7e4f483c6c4e1855fa85c419255cd/crates/papyrus_network/src/messages/mod.rs#L34)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

as we said. add conclusion as a todo
</blockquote></details>

Done.

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1212#-:-NfPbSwbAX638IWvx13u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by nagmo-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
