### PR TITLE
test(JSON-RPC): fix bug in get_starknet_spec_api_schema_for_method_errors

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1065)

### CODE REVIEW

**Review by nagmo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1065)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1065#-Nc2FTxI7RHEJZIF8zbs:-Nc2FTxI7RHEJZIF8zbt:b-d62wlg) ([raw file](https://github.com/starkware-libs/papyrus/blob/193c3e0c3c1b60690030e40d1fbec508418ea69e/crates/papyrus_gateway/src/test_utils.rs#L203)):*
> ```XML
> }
> 
> fn fix_errors(spec: &mut serde_json::Value) {
> ```

please add an explanation. also maybe an example of what the spec looks like before and after the fix.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1065)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @nagmo-starkware, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1065#-Nc2FTxI7RHEJZIF8zbs:-Nc2SHJI4gQVYoZZLYtW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/193c3e0c3c1b60690030e40d1fbec508418ea69e/crates/papyrus_gateway/src/test_utils.rs#L203)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

please add an explanation. also maybe an example of what the spec looks like before and after the fix.
</blockquote></details>

Done.

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1065)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/papyrus_gateway/src/test_utils.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1065#-Nc2UCaH7o7IbWgRSWH4:-Nc2UCaH7o7IbWgRSWH5:bqsp5tq) ([raw file](https://github.com/starkware-libs/papyrus/blob/fcfddd7f7788f9840d90c96bf1d49d17ae00253f/crates/papyrus_gateway/src/test_utils.rs#L254)):*
> ```XML
>         let mut properties = serde_json::Map::from_iter([
>             (
>                 "code".to_owned(),
> ```

consider



_Suggestion:_
```XML
"code".to_string()
```

**Review by nagmo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1065#-:-Nc2Vq33C9Ebbsr3Lp_O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @yair-starkware)

**Pull request merged**
