### PR TITLE
Yoav/config/use the new process

### PR DESCRIPTION
**Pull request by yoavGrs**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The config is held in ConfigBuilder, a struct with optional elements, during the config creation process.

Issue Number: 496

## What is the new behavior?

- The config is held in a map during the config creation process.
- The default config is taken from default_config.json
- All the config param are in the CLI with new flag names.

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

- Use the new default config file (instead of the config.yaml file).
- Use the new CLI flags.

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8RjKF3Nz8DshVddeC:-N_8RjKF3Nz8DshVddeD:bejg81x) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/bin/dump_config.rs#L15)):*
> ```XML
>     serde_json::to_writer_pretty(&mut writer, &dumped).expect("writing failed");
>     writer.flush().expect("flushing failed");
> }
> ```

Didn't we have a regression test that creates the file?



_Code quote:_
```XML
/// Updates the default config file by:
/// cargo run --bin dump_config -q
fn main() {
    let dumped = Config::default().dump();
    let file = File::create(DEFAULT_CONFIG_FILE).expect("creating failed");
    let mut writer = BufWriter::new(file);
    serde_json::to_writer_pretty(&mut writer, &dumped).expect("writing failed");
    writer.flush().expect("flushing failed");
}
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Q4l-4UKkMpd2ghlB:-N_8Q4l-4UKkMpd2ghlC:b-u3bg9y) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L36)):*
> ```XML
> /// The configurations of the various components of the node.
> #[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
> pub struct Config {
> ```

Let's rename this to NodeConfig in a separate PR



_Code quote:_
```XML
Config
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8QPRe8yqEDcBy7SBa:-N_8QPRe8yqEDcBy7SBb:b-ycg0bz) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L49)):*
> ```XML
>     fn default() -> Self {
>         Config {
>             // TODO(yoav): Read the default values from a dump file.
> ```

Shouldn't you handle this now?



_Code quote:_
```XML
// TODO(yoav): Read the default values from a dump file.
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Ql0O7LOo9GlGj2ty:-N_8Ql0O7LOo9GlGj2tz:b-2u6xfh) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L87)):*
> ```XML
>         .version(VERSION_FULL)
>         .about("Papyrus is a StarkNet full node written in Rust.")
> }
> ```

Can you move this from this file (maybe to main)?



_Code quote:_
```XML
pub fn node_command() -> Command {
    Command::new("Papyrus")
        .version(VERSION_FULL)
        .about("Papyrus is a StarkNet full node written in Rust.")
}
```
___
*[`crates/papyrus_node/src/config/mod.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8MErB3gY_R3SMQPeO:-N_8MErB3gY_R3SMQPeP:bfhbo64) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L106)):*
> ```XML
>                 )
>             })
>             .collect();
> ```

Consider extracting to a separate function.
Also, shouldn't this move to the Config crate?
+ consider adding serde_json:: to the Value and Map types



_Code quote:_
```XML
        let file = std::fs::File::open(Path::new(DEFAULT_CONFIG_FILE)).unwrap();
        let deserialized_default_config: Map<String, Value> =
            serde_json::from_reader(file).unwrap();

        let mut config_map: BTreeMap<String, SerializedParam> = deserialized_default_config
            .into_iter()
            .map(|(key, value)| {
                (
                    key,
                    SerializedParam {
                        description: value["description"].as_str().unwrap().to_owned(),
                        value: value["value"].to_owned(),
                    },
                )
            })
            .collect();
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841)* status: all files reviewed, 5 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/bin/dump_config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8RjKF3Nz8DshVddeC:-N_8g7Z-BupNK8Xg79od:b6eqip7) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/bin/dump_config.rs#L15)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Didn't we have a regression test that creates the file?
</blockquote></details>

No, the test `test_dump_default_config` doesn’t create this file.
___
*[`crates/papyrus_node/src/config/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Q4l-4UKkMpd2ghlB:-N_8gbHO4zuwGWdSNAa0:b32w0x) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L36)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Let's rename this to NodeConfig in a separate PR
</blockquote></details>

OK
___
*[`crates/papyrus_node/src/config/mod.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8QPRe8yqEDcBy7SBa:-N_8XDcU4ix-TKQsMpxg:byr4flj) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't you handle this now?
</blockquote></details>

Right.
___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Ql0O7LOo9GlGj2ty:-N_8iRSG4bAASchUr3Kp:b-jfa6do) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L87)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you move this from this file (maybe to main)?
</blockquote></details>

I can put this function in `main`, and move the command as an argument to `Config::load\_and\_process`.
But as we can't import from `main`, then any use of `load\_and\_process` in tests (5 tests, 3 files) should be coupled with a dummy command.
___
*[`crates/papyrus_node/src/config/mod.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8MErB3gY_R3SMQPeO:-N_8avefDJXKk0hLfs9K:blw3iko) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L106)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider extracting to a separate function.
Also, shouldn't this move to the Config crate?
+ consider adding serde_json:: to the Value and Map types
</blockquote></details>

The creation of the BTreeMap will be changed in the next PR, when we use pointers.
I'm adding a todo for this.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Ql0O7LOo9GlGj2ty:-N_8u2R04iwJ97ZnPR_A:b1gs9ly) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L87)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I can put this function in `main`, and move the command as an argument to `Config::load\_and\_process`.
But as we can't import from `main`, then any use of `load\_and\_process` in tests (5 tests, 3 files) should be coupled with a dummy command.
</blockquote></details>

Where is the part that prepares the command line?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_node/src/config/mod.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/841#-N_8Ql0O7LOo9GlGj2ty:-N_8zonSElmNMQXKkIWf:b-du86s4) ([raw file](https://github.com/starkware-libs/papyrus/blob/e6553f8935f3298554d43d5860d0fe3c966a1e81/crates/papyrus_node/src/config/mod.rs#L87)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Where is the part that prepares the command line?
</blockquote></details>

In `crates/papyrus_config/src/command.rs`.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/841#-:-N_D7LEn44y8i5yl5ks4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
