### PR TITLE
Idan/papyrus integration deployment

### PR DESCRIPTION
**Pull request by idan-stark**
Added few changes to the deployment manifests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2101)

### CODE REVIEW

**Review by AlonStark — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2101)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @idan-stark)

___
*[`deployments/install_papyrus.py` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-O-1_uDo-IbEq6wttdgA:-O-1_uDrEky_tbd1q7kG:b-bvwa2r) ([raw file](https://github.com/starkware-libs/papyrus/blob/971959493e653c4fc6577579382f3c5d607fb4fe/deployments/install_papyrus.py#L19)):*
> ```Python
>     parser.add_argument("--create_namespace", action="store_true", default=False, help="Enabling this option will install a new namespace with the given name.")
>     parser.add_argument("--values_file", action="store", default=None, help="Add additional values file.")
>     parser.add_argument("--with_alerts", action="store_true", default=False, help="Enabling this option will also deploy a grafana alerts deashboard with the pod.")
> ```

I think my formatting (with new lines between arguements) makes things a bit more readable and without exceeding the character limit, why change it?
___
*[`deployments/install_papyrus.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-O-1aQeo4OEcFUDBEIFF:-O-1aQeo4OEcFUDBEIFG:b-hjbu5v) ([raw file](https://github.com/starkware-libs/papyrus/blob/971959493e653c4fc6577579382f3c5d607fb4fe/deployments/install_papyrus.py#L53)):*
> ```Python
>         assert args.prometheus_uid is not None, "Must provide Prometheus UID when deploying with Grafana."
>         generate_grafana_tokens(
>             grafana_namespace=GRAFANA_NAMESPACE, 
> ```

Is this not more limiting? This seems to indicate all grafana namespace for this will be ``papyrus``?



_Code quote:_
```Python
 grafana_namespace=GRAFANA_NAMESPACE,
```

**Comment by idan-stark** [comment]
*[`deployments/install_papyrus.py` line 53 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-O-1aQeo4OEcFUDBEIFF:-O-1ewaA6lhbrs2SRI2q:b-886gsx) ([raw file](https://github.com/starkware-libs/papyrus/blob/971959493e653c4fc6577579382f3c5d607fb4fe/deployments/install_papyrus.py#L53)):*
<details><summary><i>Previously, AlonStark wrote…</i></summary><blockquote>

Is this not more limiting? This seems to indicate all grafana namespace for this will be ``papyrus``?
</blockquote></details>

Fixed

**Comment by idan-stark** [comment]
*[`deployments/install_papyrus.py` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-O-1_uDo-IbEq6wttdgA:-O-1fC_04CI9lJTle4Tj:b-4y50ha) ([raw file](https://github.com/starkware-libs/papyrus/blob/971959493e653c4fc6577579382f3c5d607fb4fe/deployments/install_papyrus.py#L19)):*
<details><summary><i>Previously, AlonStark wrote…</i></summary><blockquote>

I think my formatting (with new lines between arguements) makes things a bit more readable and without exceeding the character limit, why change it?
</blockquote></details>

Less lines is more readable in my opinion, I can see all args together. 
And we usually work with 24" screens not laptop screen (:

**Review by AlonStark — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-:-O-2k17_2G5yhk6W7sTK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @idan-stark)

___
*[`deployments/install_papyrus.py` line 19 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2101#-O-1_uDo-IbEq6wttdgA:-O-2js8C83nLfo4YkH-E:bg9rpsk) ([raw file](https://github.com/starkware-libs/papyrus/blob/971959493e653c4fc6577579382f3c5d607fb4fe/deployments/install_papyrus.py#L19)):*
<details><summary><i>Previously, idan-stark (Idan Shamam) wrote…</i></summary><blockquote>

Less lines is more readable in my opinion, I can see all args together. 
And we usually work with 24" screens not laptop screen (:
</blockquote></details>

I'll approve for now but let's discuss on Thursday because it stirs from company convensions

**Pull request merged**
