### PR TITLE
feat(network): fix fin handling

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1624)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1624?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1617** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1617?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1624** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1624?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1618** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1618?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1621** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1621?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1624?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1624#-:-NoQvBCu-68rbR8X6LRt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1624#-NoQv8QL-DgMguS-ufa9:-NoQv8QL-DgMguS-ufaA:b5bx7uy) ([raw file](https://github.com/starkware-libs/papyrus/blob/8906f4728ccb6d60ae8cdfc13680da876cc72f63/crates/papyrus_network/src/block_headers/mod.rs#L24)):*
> ```XML
>     #[error("Waiting to complete pairing of header and signature")]
>     WaitingToCompletePairing,
>     // TODO: consider separating the case when Fin is an error and when it is not.
> ```

Add TODO to make the i32 an enum

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1624#-NoQv8QL-DgMguS-ufa9:-NoRQ78j-5ZWBOW7MSH8:b-4y3sra) ([raw file](https://github.com/starkware-libs/papyrus/blob/8906f4728ccb6d60ae8cdfc13680da876cc72f63/crates/papyrus_network/src/block_headers/mod.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to make the i32 an enum
</blockquote></details>

next PR

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1624#-:-NoRaflpCvQt18YsNtCz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
