### PR TITLE
chore(config): add num_of_validators to ConsensusConfig

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r9, 16 of 16 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`config/default_config.json` line 82 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/2194#-O1HHSuP1_HVhuZln4SW:-O1HHSuP1_HVhuZln4SX:bjfg4vu) ([raw file](https://github.com/starkware-libs/papyrus/blob/96ba2239a0dbdb1f86f3ec366a8299da5aeea25c/config/default_config.json#L82)):*
> ```JSON
>     "value": true
>   },
>   "consensus.num_of_validators": {
> ```

Let's make this change everywhere in the PR



_Suggestion:_
```JSON
num_validators
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`config/default_config.json` line 82 at r10](https://reviewable.io/reviews/starkware-libs/papyrus/2194#-O1HHSuP1_HVhuZln4SW:-O1HJ5_t9pJyT4DDdqgp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/96ba2239a0dbdb1f86f3ec366a8299da5aeea25c/config/default_config.json#L82)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's make this change everywhere in the PR
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 8 at r11](https://reviewable.io/reviews/starkware-libs/papyrus/2194#-O1HK9sP6a1h9I5LWveM:-O1HK9sQ1bJ-oBLVpjKp:b-jwp0vb) ([raw file](https://github.com/starkware-libs/papyrus/blob/57c013076dddd4f7856dcdc67691efe13a664419/crates/sequencing/papyrus_consensus/run_consensus.py#L8)):*
> ```Python
> import tempfile
> import socket
> from contextlib import closing
> ```

I think this is meant to be a separate PR



_Code quote:_
```Python
import subprocess
import time
import os
import signal
import argparse
import tempfile
import socket
from contextlib import closing
```

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
