### PR TITLE
check starknet_api dependency

### PR DESCRIPTION
**Pull request by nagmo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/868)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #868** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/868" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/868?utm_source=stack-comment).

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/868)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_llahZD_gNdv5lknbO:-N_llahZD_gNdv5lknbP:b1pqxl1) (no related file):*
@dan-starkware should also review

___
___
*[`check_starknet_api_version_dependency.sh` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_lki_VAx9L36Uoesjz:-N_lki_VAx9L36Uoesk-:b-yush8x) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee83a5a9e3d73055ba20794309f1189aca98e99e/check_starknet_api_version_dependency.sh#L6)):*
> ```Shell
> 
> # Fetch the package's dependencies and check if "starknet_api" is one of them.
> DEPENDENCIES=$(cargo metadata --no-deps --format-version 1 | jq '.packages[].dependencies[].name' | grep -oE "\"[^\"]+\"" | tr -d "\"")
> ```

break this command into multiple lines and describe what you're doing in each line for the non-bash experts
___
*[`check_starknet_api_version_dependency.sh` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_ll1EB2a1eD-0CIWZh:-N_ll1EB2a1eD-0CIWZi:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee83a5a9e3d73055ba20794309f1189aca98e99e/check_starknet_api_version_dependency.sh#L10)):*
> ```Shell
> if [[ $DEPENDENCIES =~ starknet_api ]]; then
>     # If "starknet_api" is a dependency, fetch its Git revision.
>     REVISION=$(cargo metadata --no-deps --format-version 1 | jq '.packages[].dependencies[] | select(.name == "starknet_api") | .source' | tr -d "\"" | sort -u)
> ```

Same here
___
*[`check_starknet_api_version_dependency.sh` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_llF1tE3NAMGukc_AB:-N_llF1tE3NAMGukc_AC:b-dlj0cn) ([raw file](https://github.com/starkware-libs/papyrus/blob/ee83a5a9e3d73055ba20794309f1189aca98e99e/check_starknet_api_version_dependency.sh#L15)):*
> ```Shell
>         # Extract the commit hash from the Git URL.
>         COMMIT_HASH=${BASH_REMATCH[1]}
>         
> ```

Fix indentation
___
*[`.github/workflows/ci.yml` line 168 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_llQmZ74Y4OhrnMDnh:-N_llQmZ74Y4OhrnMDni:b-3utn5w) ([raw file](https://github.com/starkware-libs/papyrus/blob/2efd0225ef4b36508c8ec7daed537383523926f3/.github/workflows/ci.yml#L168)):*
> ```YAML
>           toolchain: stable
>       - run: sudo apt-get install jq
>       - run: ./check_starknet_api.sh # this script checks that if the starknet_api dependency is by git rev then this rev (commit) is on main
> ```

Check if we previously had a newline at the end of the file (because now we don't)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/868)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`check_starknet_api_version_dependency.sh` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_lki_VAx9L36Uoesjz:-Na5taqDAIsX-KPztPKp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7a4f62b28fe7b1656ecaa667eb83596c40e864c/check_starknet_api_version_dependency.sh#L6)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

break this command into multiple lines and describe what you're doing in each line for the non-bash experts
</blockquote></details>

Done.
___
*[`check_starknet_api_version_dependency.sh` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_ll1EB2a1eD-0CIWZh:-Na5tb9D82Cuf3kzAW14:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e7a4f62b28fe7b1656ecaa667eb83596c40e864c/check_starknet_api_version_dependency.sh#L10)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 168 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/868#-N_llQmZ74Y4OhrnMDnh:-Na5u6rj1vkyOytdCzVW:bdx88cz) ([raw file](https://github.com/starkware-libs/papyrus/blob/b417ee1df3d5ee06b789a12143e034fda7b5b55e/.github/workflows/ci.yml#L168)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Check if we previously had a newline at the end of the file (because now we don't)
</blockquote></details>

there wasn't

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/868#-:-Na5xsNl-tKMu54IEZXi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

**Pull request merged**
