### PR TITLE
feat(storage): add common prefix table type

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1761)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1761)* status: all files reviewed, 15 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-Ns96qq_-l4YQQcFsXdr:-Ns96qq_-l4YQQcFsXds:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L33)):*
> ```XML
> 
> // A table with keys with common prefix. The same common prefix will be saved only once.
> // NOTICE: the size of the serialized sub key and value must be half of page size.
> ```





_Suggestion:_
```XML
must be no more than half of page size.
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCfs_r21ZU7TU_o6rc:-NsCfs_r21ZU7TU_o6rd:b-18tkdo) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L38)):*
> ```XML
> impl DupSortTableType for CommonPrefix {}
> 
> trait DupSortUtils<K: KeyTrait, V: ValueSerde> {
> ```

Please document.
Also, consider moving further down the file (in a designated commit/PR) 



_Code quote:_
```XML
trait DupSortUtils<K: KeyTrait, V: ValueSerde>
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCrnr_5vYPR9AuvqPh:-NsCrnr_5vYPR9AuvqPi:bynsx5w) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L46)):*
> ```XML
> 
>     // Returns the sub key and value bytes.
>     fn get_sub_key_value(key: &K, value: &V::Value) -> DbResult<Vec<u8>>;
> ```

Consider 
1. Removing bytes (or add bytes elsewhere) 
2. Explicit name to avoid confusion 



_Suggestion:_
```XML
    // Returns the sub key and value.
    fn get_sub_key_and_value(key: &K, value: &V::Value) -> DbResult<Vec<u8>>;
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCfFwf6UV8r7HyZ74s:-NsCfFwf6UV8r7HyZ74t:b-ioovy1) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L49)):*
> ```XML
> 
>     // Returns the first key that is greater than or equal to the given key.
>     fn get_first_key_after(key: &K) -> DbResult<Vec<u8>>;
> ```

The comments says `>=` but the name implies `>`
Consider renaming, maybe use lower bound (like we have in the simple table cursor)



_Code quote:_
```XML
    // Returns the first key that is greater than or equal to the given key.
    fn get_first_key_after(key: &K) -> DbResult<Vec<u8>>;
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCm5ee5RU5C8CLUfyY:-NsCm5ef1FJiWLxZRgCb:bl1qpw8) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L55)):*
> ```XML
> 
>     // Returns a key value pair from main_key bytes and sub_key_value bytes.
>     fn get_key_value_pair(main_key: &[u8], sub_key_value: &[u8]) -> Option<(K, V::Value)>;
> ```

Not sure I understand.  This means that the user value is empty?



_Code quote:_
```XML
    // Returns a key value pair from main_key bytes and sub_key_value bytes.
    fn get_key_value_pair(main_key: &[u8], sub_key_value: &[u8]) -> Option<(K, V::Value)>;
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCfc6qAfQe0THhq7b-:-NsCfc6qAfQe0THhq7b0:b1shxhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L58)):*
> ```XML
> }
> 
> // TODO(dvir): consider add test for the implementation.
> ```

Why consider and not implementing?



_Code quote:_
```XML
// TODO(dvir): consider add test for the implementation.
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCpama1GP5rrH6xSLH:-NsCpama1GP5rrH6xSLI:b-xdq0fu) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L81)):*
> ```XML
>     fn get_first_key_after(key: &(MainKey, SubKey)) -> DbResult<Vec<u8>> {
>         key.1.serialize()
>     }
> ```

This does not seem to
`// Returns the first key that is greater than or equal to the given key.`



_Code quote:_
```XML
    fn get_first_key_after(key: &(MainKey, SubKey)) -> DbResult<Vec<u8>> {
        key.1.serialize()
    }
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCmdUmApWAQBNHJnJL:-NsCmdUmApWAQBNHJnJM:b-yyk7fj) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L92)):*
> ```XML
>     ) -> Option<((MainKey, SubKey), V::Value)> {
>         Some((
>             (MainKey::deserialize(&mut main_key)?, SubKey::deserialize_from(&mut sub_key_value)?),
> ```

This is somewhat confusing. Please explain why not using `SubKey::deserialize` here.



_Code quote:_
```XML
SubKey::deserialize_from(&mut sub_key_value)?)
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCk5699fEXHvy-3y8R:-NsCk5699fEXHvy-3y8S:b483uv7) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L98)):*
> ```XML
> }
> 
> // Adds one to the number represented by the bytes.
> ```

What about endianness?



_Code quote:_
```XML
// Adds one to the number represented by the bytes.
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCl6Sn1HKbBmJ71liD:-NsCl6Sn1HKbBmJ71liE:b-zarlwz) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L110)):*
> ```XML
> 
>     // If we reach this point, it means there was a carry into the most significant byte.
>     bytes.insert(0, 1);
> ```

Do we need to implement this logic ourselves? 



_Code quote:_
```XML
    for byte in bytes.iter_mut().rev() {
        if *byte == u8::MAX {
            *byte = 0;
        } else {
            *byte += 1;
            return; // No need to continue if there is no carry.
        }
    }

    // If we reach this point, it means there was a carry into the most significant byte.
    bytes.insert(0, 1);
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCqVisAnRvBZq4FUwD:-NsCqVisAnRvBZq4FUwE:b-q5kw8b) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L164)):*
> ```XML
>     ) -> DbResult<Option<<Self::Value as ValueSerde>::Value>> {
>         let main_key = T::get_main_key(key)?;
>         let first_key = T::get_first_key_after(key)?;
> ```

If I understand right, this should be `first_sub_key`.
Otherwise please explian.



_Code quote:_
```XML
first_key
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCuN_B0V5eVu7gejIy:-NsCuN_B0V5eVu7gejIz:biob5ub) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L186)):*
> ```XML
>     ) -> DbResult<()> {
>         let main_key = T::get_main_key(key)?;
>         let sub_key = T::get_sub_key(key)?;
> ```

Please move closer to usage.
Also in insert.



_Code quote:_
```XML
let sub_key = T::get_sub_key(key)?;
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCuidt6BLKICbrtiK7:-NsCuidt6BLKICbrtiK8:b-efl0x) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L235)):*
> ```XML
>         )?;
> 
>         if let Some((_key_prefix, sub_key_value)) =
> ```

Please add a comment explaining why we should also delete prev/next in insert



_Code quote:_
```XML
if let Some((_key_prefix, sub_key_value)) =
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCvBN45M0W9Hi5NOKl:-NsCvBN45M0W9Hi5NOKm:bxyc0gf) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L309)):*
> ```XML
>     // TODO(dvir): make this function walk only once on the table and not twice. This will
>     // require to add functionality of libmdbx to the binding or use assumption on the current
>     // implementation of the binding.
> ```

Please add a reference to the corresponding PR.



_Code quote:_
```XML
    // TODO(dvir): make this function walk only once on the table and not twice. This will
    // require to add functionality of libmdbx to the binding or use assumption on the current
    // implementation of the binding.
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCvPU77biH2Yfhhk0E:-NsCvPU8-wihfvy1rVRE:binmfz1) ([raw file](https://github.com/starkware-libs/papyrus/blob/75d8bbf68227a7a4a5d272ca2aad66ea9ee704cd/crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs#L6)):*
> ```XML
> 
> #[test]
> fn common_prefix_table_test() {
> ```

IIRC our convention is no `test` prefix/suffix in test names. 



_Code quote:_
```XML
common_prefix_table_test
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1761)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCm5ee5RU5C8CLUfyY:-NsDC7hx1EH4N6STP--Q:b-g70rpk) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L55)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not sure I understand.  This means that the user value is empty?
</blockquote></details>

Do you talk about the Option return value? This is like our deserialize function, if the bytes are not what we expected when trying to deserialize a given type, then we return None.
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCfc6qAfQe0THhq7b-:-NsDCT_z5LowII_peNC7:b-23wqk1) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L58)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why consider and not implementing?
</blockquote></details>

Because this logic and code are straightforward, and the use of it is tested in the table tests. Maybe I will do it in a different PR.
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCpama1GP5rrH6xSLH:-NsDCxgM7BDrM4yIZvAE:bepiz8a) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L81)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This does not seem to
`// Returns the first key that is greater than or equal to the given key.`
</blockquote></details>

You are right the documentation should say sub key. fixed
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCmdUmApWAQBNHJnJL:-NsDDTh3DrfsDVoZyimk:bwhcp9) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L92)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This is somewhat confusing. Please explain why not using `SubKey::deserialize` here.
</blockquote></details>

This is because we have an array of bytes, that is, the concatenation of the sub-key bytes and the value bytes. The deserialized function will also check if we use all the bytes, which is incorrect after deserializing only the subkey.
Another option is to deserialize the bytes as a tuple of (subkey, value), but this will add more restrictions on the implementation and will add an assumption about the serialization of a tuple.
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCk5699fEXHvy-3y8R:-NsDG5IbDCpV4o4rruxr:b-anx9ng) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L98)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What about endianness?
</blockquote></details>

As far as I know, endianness is relevant only for the order inside a byte, which is not something I change here. It could be important lets talk about this face to face.
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCl6Sn1HKbBmJ71liD:-NsDGduk-y76nb5_SUYM:b-qr2ezn) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L110)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Do we need to implement this logic ourselves?
</blockquote></details>

I didn't find any crate that does that exactly.  
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCqVisAnRvBZq4FUwD:-NsDIGHs7D7PufEFyLvF:bl5c99o) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L164)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

If I understand right, this should be `first_sub_key`.
Otherwise please explian.
</blockquote></details>

To be explicit as can for get_first_key_after, the function name changed to get_sub_key_lower_bound, the documentation changed, and the variable names changed.
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NsCvPU77biH2Yfhhk0E:-NsDOUTlAJlmExSpcwGN:bnxmweo) ([raw file](https://github.com/starkware-libs/papyrus/blob/51e1b539b16e794a744cbdf14e85a0a34179c06c/crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs#L6)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IIRC our convention is no `test` prefix/suffix in test names.
</blockquote></details>

Done. For the add_one, I import the add_one function, so I need a different name for the test.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1761)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NtFWeN57qSE2VaZVKS8:-NtFWeN57qSE2VaZVKS9:b-2isyzf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d58bf99950c3e8ecd29c5ac922ba8cb0e45d7f67/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L40)):*
> ```XML
> // TODO(dvir): consider move this to the end of the file.
> // This trait is the functionality that table types using libmdbx DUP_SORT feature should implement
> // to be auto implement the Table trait for them (and cursor trait).
> ```

Consider something along:



_Suggestion:_
```XML
// This trait represents the required functionality for table types using libmdbx DUP_SORT feature,
// ensuring their automatic implementation of the Table trait (along with the cursor trait).
```
___
*[`crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-NtFXmiq-xRyvzvFgA1Z:-NtFXmiq-xRyvzvFgA1_:b-1nftzx) ([raw file](https://github.com/starkware-libs/papyrus/blob/d58bf99950c3e8ecd29c5ac922ba8cb0e45d7f67/crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs#L59)):*
> ```XML
>     // Returns a key value pair from main_key bytes and sub_key_value bytes. None will return in
>     // case of a failure.
>     fn get_key_value_pair(main_key: &[u8], sub_key_value: &[u8]) -> Option<(K, V::Value)>;
> ```

As discussed, consider



_Suggestion:_
```XML
sub_key_and_value
```

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1761#-:-NtGUXm4CP53bbj95AHC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
