### PR TITLE
feat(consensus): minor cleanups in SHC and SM

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2188)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2188)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @asmaastarkware, @matan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2188#-O1Daf9n7T9sgboW66Fq:-O1Daf9n7T9sgboW66Fr:bn5edye) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d97add6cd2832f28ce3bd95291d71201b0e0e75/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L137)):*
> ```XML
>         message: ConsensusMessage,
>     ) -> Result<Option<BlockT>, ConsensusError> {
>         debug!("Received message: {:?}", message);
> ```

Please explain



_Code quote:_
```XML
debug!("Received message: {:?}", message);
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2188)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @matan-starkware, and @ShahakShama)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2188)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @dan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2188#-O1Daf9n7T9sgboW66Fq:-O1GIRy9500X-7qvts6s:b-jbybt4) ([raw file](https://github.com/starkware-libs/papyrus/blob/2d97add6cd2832f28ce3bd95291d71201b0e0e75/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L137)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please explain
</blockquote></details>

reconsidered to add instrumentation and just `skip_all` since I don't want to print `message` on every log.

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2188#-:-O1GnvaPB8y8O-ru_2Mq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware and @ShahakShama)

**Pull request merged**
